### ISSUE TITLE
Libexec missing after install

### ISSUE THREAD

**Issue by sebastiaandegeus** [Homebrew/homebrew-php#1106]
After installing php55 for example the libexec dir does not exist. 

OS X 10.9.2 (13C64)

**Comment by WangWenchao** [comment]
yes I meet this today , as the README page said add the php5_module ,but the 5.6.4  has not libexec 

~  ll /usr/local/Cellar/php56/5.6.4/
total 992
drwxr-xr-x  14 kewin  admin     476 Jan 10 17:11 .
drwxr-xr-x   3 kewin  admin     102 Jan 10 17:03 ..
-rw-r--r--   1 kewin  admin     633 Jan 10 17:11 INSTALL_RECEIPT.json
-rw-r--r--   1 kewin  wheel    3218 Dec 17 09:25 LICENSE
-rw-r--r--   1 kewin  wheel  488279 Dec 17 09:25 NEWS
-rw-r--r--   1 kewin  wheel    1473 Dec 17 09:25 README.md
drwxr-xr-x  12 kewin  admin     408 Jan 10 17:11 bin
-rw-r--r--   1 kewin  admin     767 Jan 10 17:11 homebrew.mxcl.php56.plist
drwxr-xr-x   3 kewin  admin     102 Jan 10 17:11 include
drwxr-xr-x   3 kewin  admin     102 Jan 10 17:11 lib
drwxr-xr-x   3 kewin  admin     102 Jan 10 17:11 php
drwxr-xr-x   4 kewin  admin     136 Jan 10 17:11 sbin
drwxr-xr-x   3 kewin  admin     102 Jan 10 17:11 share
drwxr-xr-x   3 kewin  admin     102 Jan 10 17:03 var

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.

**Comment by black-snow** [comment]
Upgraded my php versions a couple days ago and now all the `libexec` are gone (54, 56, 80) and this apache won't start.

Everything was working just fine. Then I did `brew update && brew upgrade`.

**Comment by developer-lindner** [comment]
@black-snow me too, got a broken local dev environment now. thank you guys! -.-

**Comment by javian** [comment]
@developer-lindner @black-snow please file a seperate issues - the OP is 2 years old and is most likely not related to your issues.
