### ISSUE TITLE
listen.mode for unix socket not 0666 per default

### ISSUE THREAD

**Issue by frankbirzle** [Homebrew/homebrew-php#1153]
When upgrading to the latest php54 (php54: stable 5.4.28, HEAD) version the permissions for the unix socket where not set to 0666 by default, which caused a problem in conjunction with Nginx. 

I don't know if it's related to the formula or the PHP version, but setting it to 

    listen.mode = 0666

in my php-fpm.conf solved the problem for me.

**Comment by alanthing** [comment]
This is resolved in [Abstract/abstract-php.rb](/Homebrew/homebrew-php/blob/3a58add5a4c28f61e5c444e85823c4e26eb6a154/Abstract/abstract-php.rb#L401)
