### ISSUE TITLE
Problem with apache module after upgrade

### ISSUE THREAD

**Issue by sivolobov** [Homebrew/homebrew-php#1229]
I have a problem after brew updating/upgrading that was four days ago. PHP 5.3 has been broken totally (https://github.com/Homebrew/homebrew-php/issues/1225). PHP 5.4 is working fine via CLI but Apache 2.2 module has been broken. I tried all recommendations from https://github.com/homebrew/homebrew-php#common-issues and https://github.com/homebrew/homebrew-php#common-upgrade-issues. I tried to untap and tap brew repositories (dupes, versions, homebrew-php). I did `brew cleanup` and then again tried all the efforts but nothing changed. I deleted all the `php54-*` packages and again reinstall php54 but again has the same error:

```
httpd: Syntax error on line 118 of /usr/local/etc/apache2/2.2/httpd.conf: Cannot load /usr/local/opt/php54/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php54/libexec/apache2/libphp5.so, 10): Symbol not found: _ap_unixd_config\n  Referenced from: /usr/local/opt/php54/libexec/apache2/libphp5.so\n  Expected in: /usr/local/Cellar/httpd22/2.2.27/bin/httpd\n in /usr/local/opt/php54/libexec/apache2/libphp5.so
```

After all of that I installed PHP 5.5 but had the same error. I have reinstalled httpd22 (Apache 2.2) from homebrew but the error is still there. I also tried to switch to lower version (PHP 5.4.24), the error has been changed to similar but instead of `Symbol not found: _ap_unixd_config` was `Image not found`. But after that I cleaned up the brew repository and had no versions in Cellar. After that I tried to reinstall PHP 5.4.24 from brew (checkout the php54.rb to the version 5.4.24). And now I have the same error as for 5.4.30 and 5.5.14.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10 DP2 (than was DP3 and now DP4, problem is still there)
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | homebrew-php
**Xcode Version:** | 5.1.1
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
  | Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
  | Target: x86_64-apple-darwin14.0.0
  | Thread model: posix
**Output of php -v:** | PHP 5.4.30 (cli) (built: Jul  1 2014 11:35:05) 
  | Copyright (c) 1997-2014 The PHP Group
  | Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
**Output of httpd -v** | Server version: Apache/2.2.27 (Unix)
  | Server built:   Jul  2 2014 14:49:11
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/sivolobov/c2e8dcc28b1cfaa816b2
**Output of brew doctor within a gist** | https://gist.github.com/sivolobov/c82c65ad0c22d4800d02

**Comment by alanthing** [comment]
Closing due to age since last error. For others, run `brew update` and `brew reinstall ...` as others have mentioned, then open a new ticket if necessary following Homebrew's [Troubleshooting](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md) page.

**Comment by vaskaloidis** [comment]
Please do not close this issue, or please reopen - nobody has posted a solution that actually works correctly. The -homebrew-apxs extension does not correctly configure homebrew php for homebrew apache 2.2 and thus does not solve the initial issue. This seems to be a legitimate issue, still.

**Comment by albygnagna** [comment]
Got the same problem updating xcode and all brew formulas. I'm using PHP 5.5.18 and would be better to keep the same version avoiding downgrade to PHP5.4.
Thanks

**Comment by Klerith** [comment]
Same issue here, someone can explain better what to do to fix this issue?

**Comment by mgracer48** [comment]
someone reopen this

**Comment by mgracer48** [comment]
im getting issue too

**Comment by pinouf** [comment]
i had this issue... just resolved it with update apache to  2.4

**Comment by kwhat** [comment]
`brew reinstall php56 --with-homebrew-apxs` does not appear to work with brew/httpd22.  You must migrate to httpd24.

**Comment by 747823** [comment]
Same problem here.
`Syntax error on line 172 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.23/libexec/apache2/libphp5.so into server`
Tried httpd 2.2 and 2.4, same issue. I guess I'll try a different version of php as well just to see
