### ISSUE TITLE
Don't know how to define struct flock on this system, set --enable-opcache=no

### ISSUE THREAD

**Issue by WebtoolsWendland** [Homebrew/homebrew-php#1245]
$ brew install php55
==> Downloading http://www.php.net/get/php-5.5.14.tar.bz2/from/this/mirror
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.14 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5 --wi
checking for mmap() using shm_open() shared memory support... no
checking for mmap() using regular file shared memory support... no
checking "whether flock struct is linux ordered"... "no"
checking "whether flock struct is BSD ordered"... "no"
configure: error: Don't know how to define struct flock on this system, set --enable-opcache=no

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': Class is not a module (TypeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:390:in `<class:HTTP>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:384:in `<module:Net>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:25:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/https.rb:21:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/utils.rb:310:in `open'
	from /usr/local/Library/Homebrew/utils.rb:352:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:380:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:171:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:167:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:207:in `dump'
	from /usr/local/Library/brew.rb:158:in `rescue in <main>'
	from /usr/local/Library/brew.rb:66:in `<main>'

**Comment by indeyets** [comment]
I have a similar error and after digging `config.log` I believe the issue is a new version of libtool. some of dependencies (odbc in my case) depend on old one, can't find id and build fails. but autotools are not smart-enough to figure out this error properly.

```
configure:65331: checking "whether flock struct is BSD ordered"
configure:65352: clang -o conftest -I/usr/include -g -O2 -fvisibility=hidden  -no-cpp-precomp -liconv -L/usr/lib  -Wl,-rpath,/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/openssl/lib -Wl,-rpath,/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/zlib/lib -Wl,-rpath,/opt/homebrew/opt/jpeg/lib -L/opt/homebrew/opt/jpeg/lib -Wl,-rpath,/opt/homebrew/opt/libpng/lib -L/opt/homebrew/opt/libpng/lib -Wl,-rpath,/opt/homebrew/Cellar/freetype/2.5.5/lib -L/opt/homebrew/Cellar/freetype/2.5.5/lib -Wl,-rpath,/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/gettext/lib -Wl,-rpath,/opt/homebrew/opt/gmp/lib -L/opt/homebrew/opt/gmp/lib -Wl,-rpath,/opt/homebrew/Cellar/icu4c/54.1/lib -L/opt/homebrew/Cellar/icu4c/54.1/lib -Wl,-rpath,/opt/homebrew/opt/unixodbc/lib -L/opt/homebrew/opt/unixodbc/lib conftest.c -lldap -llber -lstdc++ -liconv -liconv -lgmp -lintl -lpng -lz -ljpeg -lcrypto -lssl -lcrypto -lcurl -lbz2 -lz -lcrypto -lssl -lcrypto -lm  -lxml2 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lcurl -lxml2 -lfreetype -licui18n -licuuc -licudata -licuio -lodbc >&5
configure:65352: $? = 0
configure:65352: ./conftest
dyld: Library not loaded: /opt/homebrew/Cellar/libtool/2.4.2/lib/libltdl.7.dylib
  Referenced from: /opt/homebrew/lib/libodbc.2.dylib
  Reason: image not found
./configure: line 2347: 82910 Trace/BPT trap: 5       ./conftest$ac_exeext
configure:65352: $? = 133
configure: program exited with status 133
```

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
