### ISSUE TITLE
Use a PHP shebang'd wrapper script in php-code-sniffer formula

### ISSUE THREAD

**Issue by jedgell** [Homebrew/homebrew-php#1249]
#### Specifics

The formula for php-code-sniffer writes a wrapper script which utilizes a shell shebang `#!/bin/sh` causing unexpected functionality when the script is executed by the PHP binary. 

#### Symptoms, aka: heartache

1. Editors like NetBeans that have phpcs support built in will often try to execute something along the lines of:

	```
	"/usr/local/bin/php" "/usr/local/bin/phpcs" "-i"
	```
	Which results, in my case, in a shell command of:
	
	```
	"/usr/bin/env" "php" "/usr/local/Cellar/php-code-sniffer/1.5.2/scripts/phpcs" "$@"
	```

	and never returns, because the wrapper script is telling phpcs it has an argument of `$@`, not `-i`.

2. This also prevents require()'ing or include()'ing the script from another script to sub-set it's functionality without knowing the full path to the actual script.

3. I don't believe the author intended the script to be wrapped in this manner, as, though it is a shell script, it too contains a PHP shebang (and contains rather poor option checking).

### Proposed solution

I'm a relative loser when it comes to ruby, so I can't propose the solution I'd really like to see: _symlink the thing and don't use a wrapper_. 

However, I also try to be a good netizen (been a while since you heard _that_ word, hasn't it?) and I'm going to propose a solution via pull request for a "purely PHP" solution: a PHP shebang'd script.

### Mandatory groveling

Errr...what?

But seriously, thank-you and all of the other contributors for your hard work on this project. I have to switch between PHP versions all the time for projects in different environments and since 'tapping this keg', I've been much more efficient. Kudos to all of you!

**Comment by alanthing** [comment]
This appears to have been resolved in #1249. Closing.
