### ISSUE TITLE
RFC: Adding more PHP maintainers

### ISSUE THREAD

**Issue by josegonzalez** [Homebrew/homebrew-php#1267]
@Homebrew/php anyone you guys think we should add to the homebrew-php maintainer list? I noticed the bug list is getting a bit large - I'm not doing my part of course - and if you guys can think of some people pushing good changes/debugging, we can add them :)

If anyone would like to nominate themselves, that's cool too.

**Comment by alanthing** [comment]
@mikemcquaid added me a couple days ago (I've been the primary maintainer for [homebrew/apache](https://github.com/Homebrew/homebrew-apache) since it was created.). I've been working on PRs this weekend and will tackle the issue queue this week.

**Comment by josegonzalez** [comment]
@alanthing looking to see great things from you! :)

**Comment by mikemcquaid** [comment]
Also hope that's cool that I added him @josegonzalez; I just figured as @alanthing already runs another tap (@Homebrew/apache) he knows what he's doing enough to help out.

**Comment by lucasmichot** [comment]
Welcome on board @alanthing :-)

**Comment by josegonzalez** [comment]
Heh no worries! The more the merrier :)

**Comment by alanthing** [comment]
I have [experience building PHP](http://alanthing.com/blog/2013/07/11/creating-php-packages-software-collection/) and have been [creating guides involving PHP](https://echo.co/tags/homebrew) for a few years. If I do anything out of sync from how you've been doing things, just let me know! Happy to be able to help give back to this project that has benefitted me and my co-workers so much.

**Comment by ablyler** [comment]
I'm late to the party, but ditto on the welcome @alanthing!  Looks like you are from my old stomping grounds of Central PA. :+1:

**Comment by josegonzalez** [comment]
@alanthing You basically saved the day with your work just now. Honestly and truly, thank you for the time you put in on the homebrew bottles integration.

And to everyone else who's stepped up over the years, thank you all as well. I never imagined my small revival of homebrew-php way back in 2012 would have resulted in this awesome project. If any of you are ever in NYC, please feel more than free to hit me up for a beer, some good Schweinebraten, a milkshake or whatever :)

**Comment by alanthing** [comment]
You're welcome! It's been fun so far!
