### ISSUE TITLE
RFC: Dealing with existing / new phar formulas

### ISSUE THREAD

**Issue by ablyler** [Homebrew/homebrew-php#1298]
I propose we stop accepting new phar formulas and instead re-direct them to https://github.com/lucasmichot/phar-installer.  At some point, it would be nice to remove the existing phar formulas after they have been migrated to the pear-installer.  Thoughts @Homebrew/php?

**Comment by josegonzalez** [comment]
@lucasmichot status of this?

**Comment by ablyler** [comment]
Closing, we can re-open if phar-installer comes back to life.
