### ISSUE TITLE
brew install php5* fails on compiling zend_dtrace?

### ISSUE THREAD

**Issue by brombrom** [Homebrew/homebrew-php#1317]
Hello! I've ran into a problem after `brew upgrade` with PHP 5.4. Removing (including aggressive cleanup) and reinstalling gives the same error. When trying `brew install php5*` (either 5.4, 5.5, or 5.6—haven't checked other versions) the compiler drops out on zend_dtrace_gen. The filled in report, including the gists is below.

I've scoured past issues of people running into seemingly similar problems, but I can't for the life of me figure out the cause. Judging from the past issues, #1170, #566, and #561, `brew install httpd` would solve it. Since httpd is split up into 2.2 and 2.4, I tried `httpd22` because I head using `http24` might cause compatibility errors. Then I tried `brew install php54 --homebrew-apxs` to no avail, figuring httpd might not be the issue. Provided in the gist is the output for a default `brew install php54`.

For now I've defaulted to the native OS X PHP (v5.4) which keeps my local dev running, but I'm afraid I'll miss the joys of homebrew's build quite soon.

I'm hoping you guys might have a suggestion as to how to solve it.

Edit: I should add that I tried reinstalling the XCode command-line tools with `xcode-select --install`, which failed (crashed on bad url?). I did manage to reinstall them (the recent September 2014 release) from the Apple dev site.

Parameter | Value
------------------ | ------------------
**OS X Version:** | Version 10.9.4
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | homebrew-php (but switched to OS X default for time being)
**Xcode Version:** | Version 5.1.1 (5B1008)
**Output of gcc -v:** | ➜  ~  gcc -v
 | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
 | Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
 | Target: x86_64-apple-darwin13.3.0
 | Thread model: posix
**Output of php -v:** | ➜  ~  php -v
 | PHP 5.4.24 (cli) (built: Jan 19 2014 21:32:15) 
 | Copyright (c) 1997-2013 The PHP Group
 | Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb** | https://gist.github.com/multiphrenia/f6f6a99fb01a94517242
**Output of brew doctor within a gist** | https://gist.github.com/multiphrenia/d0ca2e2a1cf86301bb71

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
