### ISSUE TITLE
Failed to generate phar.php when building php55 --with-mssql on OS X Yosemite GM

### ISSUE THREAD

**Issue by darronz** [Homebrew/homebrew-php#1326]
I have a problem installing `php55 --with-mssql` on Yosemite. Installing without any switches works fine.

It fails with the following error when trying to generate `phar.php`

```
Generating phar.php
/bin/sh: line 1: 36977 Segmentation fault: 11  ` if test -x "/private/tmp/php55-Fq2ici/php-5.5.16/sapi/cli/php"; then /private/tmp/php55-Fq2ici/php-5.5.16/build/shtool echo -n -- "/private/tmp/php55-Fq2ici/php-5.5.16/sapi/cli/php -n"; if test "x" != "x"; then /private/tmp/php55-Fq2ici/php-5.5.16/build/shtool echo -n -- " -d extension_dir=/private/tmp/php55-Fq2ici/php-5.5.16/modules"; for i in bz2 zlib phar; do if test -f "/private/tmp/php55-Fq2ici/php-5.5.16/modules/$i.la"; then . /private/tmp/php55-Fq2ici/php-5.5.16/modules/$i.la; /private/tmp/php55-Fq2ici/php-5.5.16/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /private/tmp/php55-Fq2ici/php-5.5.16/build/shtool echo -n -- "/private/tmp/php55-Fq2ici/php-5.5.16/sapi/cli/php"; fi;` -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /private/tmp/php55-Fq2ici/php-5.5.16/ext/phar/build_precommand.php > ext/phar/phar.php
make: *** [ext/phar/phar.php] Error 139

```

| Parameter | Value |
|-----------|-------|
|**OSX Version:**|10.10 (14A389) Yosemite GM|
|**Homebrew version:**|0.9.5|
|**PHP version:**|5.6.1 (cli)|
|**Xcode version:**|6.1 (6A1052c)|
|**Command line tools version:**|6.1 GM|
|**Output of `gcc -v`:** |Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
||Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)|
||Target: x86_64-apple-darwin14.0.0|
||Thread model: posix |
|**Output of `php -v`:**|PHP 5.5.16 (cli) (built: Sep 12 2014 06:19:10)
||Copyright (c) 1997-2014 The PHP Group|
||Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies|
|**Output of `brew install -v php55 --with-mssql`:**|https://gist.github.com/darronz/6d7a59290feeef5c915e|
|**Output of brew doctor:** | Your system is ready to brew. |

**Comment by simonj621** [comment]
I also had to use --without-snmp as @wiseloren suggested. This was for php56 on 10.10.1 Yosemite. 

brew install php56 --with-fpm --with-imap --without-apache --with-debug --without-snmp

**Comment by stewartadam** [comment]
I'm seeing this as well on OS X 10.10.1 and php54, adding --without-snmp worked. I have the homebrew curl and openssl packages installed, if that makes a difference.

**Comment by davidfirst** [comment]
I had the same issue with php53 (OS v10.10.1):
`brew install php53 --with-fpm`

Adding --without-snmp resolved the issue:
`brew install php53 --with-fpm --without-snmp`

**Comment by velikanov** [comment]
and one more question is remain - what if I need mssql and snmp both installed?

**Comment by wrathagom** [comment]
Do you have a reason to need mssql specifically instead of just dblib? I've been able to move entirely to dblib which means I have a connection string that is platform agnostic more or less.

**Comment by FladeX** [comment]
Option `--without-snmp` works for me too, thanks!

**Comment by kgoossens** [comment]
Had the same problem with php56, but was lucky the workaround remains the same as well ;-)
```
brew install php56 --without-snmp
```
Thx guys!

**Comment by faizalheesyam** [comment]
finally the answer to my pain, **--without-snmp**... T_T

thanks guys!

**Comment by alanthing** [comment]
Running `/.configure` with no options from the PHP source does not include SNMP by default. Because the scope of needing to add `--without-snmp` is beyond what we are currently checking for (if using `--with-thread-safety` or `--with-homebrew-openssl`), I'm wondering if we should not make SNMP a default. Unless SNMP is a strong requirement for PHP on OS X, and because the PHP project does not enable it by default, perhaps we should make it opt-in instead of opt-out. 

What do you all think?

**Comment by stewartadam** [comment]
+1 for opt-in instead!

**Comment by velikanov** [comment]
@alanthing :+1:

**Comment by wiseloren** [comment]
Yes, opt in.  This has a number of duplicate tickets all with similar problems that that would fix. #1430 #1426 #1525 #1311

**Comment by alanthing** [comment]
Committed in 7c56043. My test builds locally worked but I'd appreciate feedback from others as well.

**Comment by alanthing** [comment]
Closing since `--without-snmp` and Homebrew's OpenSSL are used by default.
