### ISSUE TITLE
Problem with pear in php55 & php56

### ISSUE THREAD

**Issue by genjusz** [Homebrew/homebrew-php#1331]
I've tried to install *php55* (5.5.16) and *php56* (5.6.0) with no luck.
After running install with *-vd* flags it occured to me that problem is with *pear*.
I don't know why, but compiler does not create *pear* binary in */usr/local/Cellar/php55/5.5.16/bin/*
Also there are warnings before that command:

<pre>Installing PEAR environment:      /usr/local/Cellar/php55/5.5.16/lib/php/
[PEAR] Archive_Tar: there was a problem with getting the configured temp directory
[PEAR] Console_Getopt: there was a problem with getting the configured temp directory
[PEAR] Structures_Graph: there was a problem with getting the configured temp directory
[PEAR] XML_Util: there was a problem with getting the configured temp directory
[PEAR] PEAR: there was a problem with getting the configured temp directory</pre>

Compiler fails on command:

<pre>==> /usr/local/Cellar/php55/5.5.16/bin/pear config-set php_ini /usr/local/etc/php/5.5/php.ini
Failed to execute: /usr/local/Cellar/php55/5.5.16/bin/pear</pre>

Attached logs are from php55 install.

<code>brew doctor</code> shows lack of *php55*, because I did one install with <code>--without-pear</code> flag and then some php55 extensions (php55-xcode etc). After removing *php55* for further debuging of this problem <code>brew doctor</code> gives this warning

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.9.5
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.4.30
**Xcode Version:** | 5.1.1
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
 | Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
 | Target: x86_64-apple-darwin13.3.0
 | Thread model: posix
**Output of php -v:** | PHP 5.4.30 (cli) (built: Jul 29 2014 23:43:29) 
 | Copyright (c) 1997-2014 The PHP Group
 | Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
**Output of brew install -vd php55** | https://gist.github.com/genjusz/0e290c0ba2b3673cd736
**Output of brew doctor within a gist** | https://gist.github.com/genjusz/dd33cfcda568cbed9570

<pre>==> Formula
Tap: josegonzalez/homebrew-php
Path: /usr/local/Library/Taps/josegonzalez/homebrew-php/Formula/php55.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
HEAD: bbf9ad18c54bb56a13a62a88222304126780eb12
CPU: 8-core 64-bit sandybridge
OS X: 10.9.5-x86_64
Xcode: 5.1.1
CLT: 6.0.0.0.1.1410400753
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CMAKE_PREFIX_PATH: /usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/zlib:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/gettext/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/libtool/bin:/usr/bin:/bin:/usr/sbin:/sbin</pre>

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
