### ISSUE TITLE
OSX 10.9.5 Xcode 6.0.1 PHP 5.6 (also 5.5) - GD build test failed

### ISSUE THREAD

**Issue by Rastusik** [Homebrew/homebrew-php#1332]
While installing PHP 5.6, I'm becoming this error:

brew install php56 --with-fpm --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl --with-phpdbg --with-thread-safety
==> Downloading http://www.php.net/get/php-5.6.0.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.0
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.0 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-confi
checking for png_write_image in -lpng... yes
If configure fails try --with-xpm-dir=<DIR>
checking for fabsf... yes
checking for floorf... yes
configure: error: GD build test failed. Please check the config.log for details.

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

The following trick doesn't work:

brew rm freetype jpeg libpng gd zlib
brew install freetype jpeg libpng gd zlib

I have uninstalled 5.5 before. When I try to install it again, I'm becoming the same GD error.

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.9.5 |
| **Homebrew Version:** | 0.9.5 |
| **PHP Version in use:** | 5.6 (trying to install) |
| **Xcode Version:** | 6.0.1 |
| **Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 |
|  | Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn) |
|  | Target: x86_64-apple-darwin13.4.0 |
|  | Thread model: posix |
| **Output of php -v:** | none, since I'm trying to build 5.6 |
| **Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/Rastusik/115d0f7f85f0a0e9fd27 |
| **Output of brew doctor within a gist** | Your system is ready to brew. |

**Comment by SaifurRahmanMohsin** [comment]
Thanks @Rastusik Your last solution worked well.

**Comment by kwhat** [comment]
Dude, just cause you got it to work doesn't mean the bug is solved.  @Rastusik Please reopen this.

**Comment by Rastusik** [comment]
wouldn't it be better to open a new issue? or do you have exactly the same problem?

**Comment by kwhat** [comment]
Same exact issue 3 years latter.  The only difference is that I had to run `brew uninstall $(brew list)` about 4 times.

**Comment by Rastusik** [comment]
ok then, fingers crossed :) I'm moving to docker so I don't have to deal with this anymore

**Comment by kwhat** [comment]
We are as well!  Long live docker! ;)
