### ISSUE TITLE
Error installing php 53/54 on 10.9.5 / 6.0.1

### ISSUE THREAD

**Issue by googletorp** [Homebrew/homebrew-php#1344]
I recently needed to reinstall my computer and so I'm setting up my dev environment.

I'm trying to install PHP 5.3 but the error I'm getting also applies for 5.4 I've tried to do all of the things I could find googling with people having similar errors.

The short list of errors is
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
make: *** Waiting for unfinished jobs....
make: *** [libs/libphp5.bundle] Error 1

Similar errors var found in

https://github.com/Homebrew/homebrew-php/issues/1218

$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

$ php -v
PHP 5.4.30 (cli) (built: Jul 29 2014 23:43:29)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

Entire log from verbose output is here: https://gist.github.com/googletorp/7837ac9f484f347c9c50

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
