### ISSUE TITLE
Cannot install php54

### ISSUE THREAD

**Issue by tunght13488** [Homebrew/homebrew-php#1369]
Cannot install php54

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.9.4
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | stock-apple
**Xcode Version:** | Version 6.0.1 (6A317)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
 | Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
 | Target: x86_64-apple-darwin13.3.0
 | Thread model: posix
**Output of php -v:** | PHP 5.4.24 (cli) (built: Jan 19 2014 21:32:15)
 | Copyright (c) 1997-2013 The PHP Group
 | Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/tunght13488/5a745e1955f1c6147b99
**Output of brew doctor within a gist** | https://gist.github.com/tunght13488/8541c6dcb0238336e2ef

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
