### ISSUE TITLE
Can`t install php56 on Mac OSX 10.9.4

### ISSUE THREAD

**Issue by KonstantinKuklin** [Homebrew/homebrew-php#1371]
I tried to install php56 and got error message

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.9.4
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | homebrew-php
**Xcode Version:** | 6.0.1
**Output of gcc -v:** |Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn) Target: x86_64-apple-darwin13.4.0 Thread model: posix
**Output of php -v:** | none php
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/KonstantinKuklin/04b1787b2725d8419886
**Output of brew doctor within a gist** | https://gist.github.com/KonstantinKuklin/be984a0b0182a218056b

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
