### ISSUE TITLE
OpenSSL Situation

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-php#1373]
Currently, we ship every PHP with the built-in OpenSSL. This seems to be a conscious decision looking through the various formulae. 

Given the state of OS X's OpenSSL in terms of being very intermittently updated and considerably behind the 1.0.1 branch in terms of features and support, I'm wondering if we should ship every PHP with Homebrew's OpenSSL by default.

I'm happy to do the leg work involved here, but I didn't want to change a few hundred lines of code and build every php locally to test this change if the maintainers here were :-1: on this idea :smile_cat:.

**Comment by alanthing** [comment]
We're using built-in by default now, see 9f7a735.
