### ISSUE TITLE
Reinstall php56 after OSX 10.10 upgrade

### ISSUE THREAD

**Issue by pulpfree** [Homebrew/homebrew-php#1383]
After upgrading to Yosemite I found the same situation as the Mavericks upgrade in that I need to update the libphp5.so file as the upgrade overwrites the brew file. Doing so causes apache to crash when attempting restart so I attempted a brew reinstall php56. The error is: configure: error: Cannot find OpenSSL's <evp.h>.
Now I've found this error has been an issue with other OSX 10.10 installs and the workaround included downgrading to older version of Xcode and ruby. The default php install (from OSX 10.10) is working ok, but would like to use brew for packages etc.

Update on this issue. Found a workaround at https://github.com/Homebrew/homebrew-php/issues/1181 from arsonik which suggests the following: 
`sudo ln -s /Applications/Xcode6-Beta4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include /usr/include`
(use whatever Beta version you may have.)
This seemed to work. I'm assuming php is then compiled with a different lib/headers etc. All works fine after copying the brew libphp5.so file to /usr/libexec/apache2

**Comment by alanthing** [comment]
Make sure you're using the latest versions of the formula by running `brew update` first. Closing, but feel free to re-open if this continues to persist.
