### ISSUE TITLE
This service is defined to be constantly running and is inherently inefficient

### ISSUE THREAD

**Issue by marckula** [Homebrew/homebrew-php#1394]
after upgrading to 10.10 and attempting to reinstall php55 php-fpm, I'm getting these syslog events when attempting to launch php-fpm using the following command:
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php55.plist

com.apple.xpc.launchd[1] (homebrew.mxcl.php55): This service is defined to be constantly running and is inherently inefficient.
com.apple.xpc.launchd[1] (homebrew.mxcl.php55[64365]): Service exited with abnormal code: 78

is there a new plist for 10.10?

**Comment by alanthing** [comment]
This might mean that PHP-FPM is crashing frequently and launchd is having to re-start it often. Reinstall php55 or your other desired version and re-open this issue if the problem persists.
