### ISSUE TITLE
libicui18n.54.dylib Library not loaded when switching versions

### ISSUE THREAD

**Issue by samheuck** [Homebrew/homebrew-php#1401]
If there are multiple versions of PHP installed, and you switch versions by running ```brew unlink php55 && brew link php53```, for instance, php must be re-complied for it to find the libicui18n.54.dylib.

Mac OS 10.7.5 (though I believe it occurs later versions as well)

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.

**Comment by sebastianhegge** [comment]
for php 5.3 it is currently not working. it's stil searching for /usr/local/opt/icu4c/lib/libicui18n.54.dylib and not for /usr/local/opt/icu4c/lib/libicui18n.55.dylib as it should.

**Comment by sebastianhegge** [comment]
This worked for me:
https://github.com/Homebrew/homebrew-php/issues/1701
