### ISSUE TITLE
phpMyAdmin Permission denied - Mac OS X 10.10

### ISSUE THREAD

**Issue by kliker** [Homebrew/homebrew-php#1407]
I upgraded to OS X 10.10 and [http://localhost/phpmyadmin](http://localhost/phpmyadmin) started returning:

> Forbidden
> You don't have permission to access /phpmyadmin/ on this server.

Since OS X 10.10 is now running Apache 2.4, [Access Control](http://httpd.apache.org/docs/2.4/upgrading.html#access) needs to be 

> Require all granted

instead of 

> Order allow,deny
> Allow from all

Here is the formula that needs to be updated:
https://github.com/Homebrew/homebrew-php/blob/master/Formula/phpmyadmin.rb

**Comment by Timopheym** [comment]
+1

**Comment by ajhsu** [comment]
+1

**Comment by alanthing** [comment]
Resolved in #1482.

**Comment by playma** [comment]
thank you !

**Comment by jbouhier** [comment]
+1

**Comment by noxidsoft** [comment]
+1 oh my puppy, I cannot believe this was all it was O__o
