### ISSUE TITLE
PHP54 not installing with "--with-imap --without-apache"

### ISSUE THREAD

**Issue by benrolfe** [Homebrew/homebrew-php#1422]
I'm running the following command:

brew install php54 --with-fpm --with-imap --without-apache --with-debug --with-gmp --with-mssql --with-pgsql --with-tidy --without-snmp --force

The console shows that PHP gets installed, but it fails to start with launchctl.

However, by removing "--with-imap --without-apache", it works. See below:

brew install php54 --with-fpm --with-debug --with-gmp --with-mssql --with-pgsql --with-tidy --without-snmp --force

Is this a known issue? What's causing the problem?

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
