### ISSUE TITLE
make: *** [ext/fileinfo/libmagic/apprentice.lo] Error 1

### ISSUE THREAD

**Issue by sekayasin** [Homebrew/homebrew-php#1427]
brew install php55
make: *** [ext/fileinfo/libmagic/apprentice.lo] Error 1

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
