### ISSUE TITLE
Homebrew segmentation fault - OSX Yosemite

### ISSUE THREAD

**Issue by joelsaxton** [Homebrew/homebrew-php#1430]
I am trying to install php55 with mcrypt to run Laravel on my Macbook. I have the updated Xcode and CL tools. I have tried every which way to get this to work. This is what I see now:

brew install php55
==> Installing php55 from homebrew/homebrew-php
==> Downloading http://www.php.net/get/php-5.5.18.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-5.5.18
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.18 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5
==> make

{lots and lots of output here which I am not going to share because it is such a huge mess}

Generating phar.php
/bin/sh: line 1: 21026 Segmentation fault: 11  ` if test -x "/private/tmp/php55-XHkgjh/php-5.5.18/sapi/cli/php"; then /private/tmp/php55-XHkgjh/php-5.5.18/build/shtool echo -n -- "/private/tmp/php55-XHkgjh/php-5.5.18/sapi/cli/php -n"; if test "x" != "x"; then /private/tmp/php55-XHkgjh/php-5.5.18/build/shtool echo -n -- " -d extension_dir=/private/tmp/php55-XHkgjh/php-5.5.18/modules"; for i in bz2 zlib phar; do if test -f "/private/tmp/php55-XHkgjh/php-5.5.18/modules/$i.la"; then . /private/tmp/php55-XHkgjh/php-5.5.18/modules/$i.la; /private/tmp/php55-XHkgjh/php-5.5.18/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /private/tmp/php55-XHkgjh/php-5.5.18/build/shtool echo -n -- "/private/tmp/php55-XHkgjh/php-5.5.18/sapi/cli/php"; fi;` -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /private/tmp/php55-XHkgjh/php-5.5.18/ext/phar/build_precommand.php > ext/phar/phar.php
make: *** [ext/phar/phar.php] Error 139

I have tried a couple times and it fails the same way. Thanks for your help.

**Comment by supratims** [comment]
--with-imap --without-snmp worked like a charm for me too. Was stuck with this for a while.

**Comment by AlexGx** [comment]
--with-imap --without-snmp worked, thanks!
