### ISSUE TITLE
php56 won't install on OSX 10.10

### ISSUE THREAD

**Issue by AlexMax** [Homebrew/homebrew-php#1442]
Pretty simple, I tried to install PHP 5.6.3 and it fails it at the configure stage.

Adding `--with-homebrew-openssl` warns me about snmp, adding `--without-snmp` to that gives me an error about not being able to find bzip2.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | N/A
**Xcode Version:** | 6.1
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1<br>Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)<br>Target: x86_64-apple-darwin14.0.0<br>Thread model: posix
**Output of php -v:** | PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25)<br>Copyright (c) 1997-2014 The PHP Group<br>Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
**Output of brew install -v php56 --with-fpm** | https://gist.github.com/AlexMax/461f7defa7776537d98f
**Output of brew doctor within a gist** | https://gist.github.com/AlexMax/461f7defa7776537d98f

**Comment by alanthing** [comment]
This doesn't appear to be a problem any more with recent formulas. Closing.

**Comment by codejanovic** [comment]
I got the same problem on 10.10.5 - brew can't find any formula for any php version. I also reinstalled Xcode CLT & Homebrew, but that did not help. Any Suggestions? Should we reopen this ticket?

**Comment by anash28** [comment]
I am having the same problem on Mac OSX Yosemite (10.10.5) as well. Is it possible for the Brew doctors to re-open this issue for further investigation please?
``` 
anash$ brew install php56
Error: No available formula with the name "php56" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
``` 

If i`m following correctly, it seems the formulae is not found properly for just _homebrew/php/php56_ without the other library dependencies (i.e amqp, zookeeper, etc)

**Comment by anash28** [comment]
Ouch. Disregard, noobie move. I didnt do what I was instructed TODO: 
```
anash$ brew install homebrew/php/php56 
==> Tapping homebrew/php
```
^ This worked fine :+1:  :disappointed:

**Comment by rafagaseo** [comment]
For me working with: 

`brew tap homebrew/php`
