### ISSUE TITLE
PHP 5.5.19 Refuses to install on OSX 10.10

### ISSUE THREAD

**Issue by jadissa** [Homebrew/homebrew-php#1443]
Jadissas-iMac:html raegriffin$ brew list
apr		faad2		gmp		icu4c		libao		libpng		mcrypt		openssl		unixodbc
apr-util	ffmpeg		gnutls		jpeg		libgcrypt	libtasn1	mhash		pcre		x264
autoconf	freetype	httpd22		json-c		libgpg-error	libtool		mysql		php55		xvid
faac		gettext		httpd24		lame		libid3tag	mad		nettle		pkg-config	zlib
Jadissas-iMac:html raegriffin$ brew uninstall php55
Uninstalling /usr/local/Cellar/php55/5.5.18...
Jadissas-iMac:html raegriffin$ brew cleanup
Removing: /Library/Caches/Homebrew/php55-5.5.19...
Jadissas-iMac:html raegriffin$ brew install php55
==> Installing php55 from homebrew/homebrew-php
==> Downloading https://www.php.net/get/php-5.5.19.tar.bz2/from/this/mirror
######################################################################## 100.0%
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.19 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5 --with-config-file-path=/usr/local/etc/php/5.5 --with-config-file
==> make
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....
warning: no debug symbols in executable (-arch x86_64)
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ext/opcache/.libs/opcache.a(shared_alloc_shm.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ext/opcache/.libs/opcache.a(shared_alloc_shm.o) has no symbols

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

**Comment by d0nn13** [comment]
Please run with ```-v``` switch enabled and send output.

```brew install -v php55```

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
