### ISSUE TITLE
Problems installing php 5.6

### ISSUE THREAD

**Issue by abbert** [Homebrew/homebrew-php#1445]
_zm_info_apache in php_functions.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....

OSX 10.10.1

Anyone any idea?

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
