### ISSUE TITLE
Brew upgrade php56-xdebug fails

### ISSUE THREAD

**Issue by ch3mik** [Homebrew/homebrew-php#1447]
Error: inreplace failed
expected replacement of /^(zend_)?extension=.+$/ with "zend_extension=\"/usr/local/Cellar/php56-xdebug/2.2.6/xdebug.so\""

I've had commented out this extension in ext-xdebug.ini file.

**Comment by fudriot** [comment]
I have the same issue in my end.

**Comment by fudriot** [comment]
I solved it! It happened I had an existing config file `/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini`. After removing it, `php56-xdebug`` compiled successfully.

**Comment by alanthing** [comment]
I've seen this happen with other extensions too, where an existing config file can cause problems. Good advice @fabarea.
