### ISSUE TITLE
Trouble with php53 after upgrading to yosemite

### ISSUE THREAD

**Issue by drewbix** [Homebrew/homebrew-php#1449]
Everything seemed to be working fine except mcrypt seems to not be working for some reason. I tried reinstalling it (php53-mcrypt) and I keep getting this same error. I get the same error when trying to reinstall just php53 now. Any tips?

==> Installing php53 from josegonzalez/homebrew-php
==> Downloading https://www.php.net/get/php-5.3.29.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php53-5.3.29
==> Patching
patching file configure
patching file configure.in
patching file Zend/zend_language_parser.y
patching file configure
patching file Zend/acinclude.m4
==> rm Zend/zend_{language,ini}_parser.[ch]
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php53/5.3.29 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.3 --with-config-file-path=/usr/local/etc/php/5.3 --with-config-file-scan-dir=/usr/l
checking whether to enable LIBXML support... yes
checking libxml2 install dir... no
checking for xml2-config path... /usr/bin/xml2-config
checking whether libxml build works... no
configure: error: build test failed.  Please check the config.log for details.

**Comment by alanthing** [comment]
Try reinstalling `libxml2` and try again, ala:

    brew uninstall libxml2
    brew install libxml2
