### ISSUE TITLE
There is some issue with install php55

### ISSUE THREAD

**Issue by webappbuilder** [Homebrew/homebrew-php#1455]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': Class is not a module (TypeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:390:in `<class:HTTP>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:384:in `<module:Net>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:25:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/https.rb:21:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/utils.rb:308:in `open'
	from /usr/local/Library/Homebrew/utils.rb:350:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:378:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:171:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:167:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:207:in `dump'
	from /usr/local/Library/brew.rb:158:in `rescue in <main>'
	from /usr/local/Library/brew.rb:66:in `<main>'

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
