### ISSUE TITLE
Segmentation fault while building php

### ISSUE THREAD

**Issue by prateekbansal** [Homebrew/homebrew-php#1458]
Generating phar.php
/bin/sh: line 1: 24852 Segmentation fault: 11  ` if test -x "/private/tmp/php54-98GlMU/php-5.4.35/sapi/cli/php"; then /private/tmp/php54-98GlMU/php-5.4.35/build/shtool echo -n -- "/private/tmp/php54-98GlMU/php-5.4.35/sapi/cli/php -n"; if test "x" != "x"; then /private/tmp/php54-98GlMU/php-5.4.35/build/shtool echo -n -- " -d extension_dir=/private/tmp/php54-98GlMU/php-5.4.35/modules"; for i in bz2 zlib phar; do if test -f "/private/tmp/php54-98GlMU/php-5.4.35/modules/$i.la"; then . /private/tmp/php54-98GlMU/php-5.4.35/modules/$i.la; /private/tmp/php54-98GlMU/php-5.4.35/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /private/tmp/php54-98GlMU/php-5.4.35/build/shtool echo -n -- "/private/tmp/php54-98GlMU/php-5.4.35/sapi/cli/php"; fi;` -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /private/tmp/php54-98GlMU/php-5.4.35/ext/phar/build_precommand.php > ext/phar/phar.php
make: *** [ext/phar/phar.php] Error 139

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
