### ISSUE TITLE
Composer: Use native OS X's PHP

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-php#1465]
Allow users to continue using OS X's native PHP (PHP 5.5) instead of requiring a version from homebrew-php.

**Comment by tmoitie** [comment]
To be honest I let composer handle itself - it has a self update facility that doesn't really correspond to official releases so doesn't really need managing by brew.

**Comment by alanthing** [comment]
This repository/tap's primary purpose is to install PHP with Homebrew and various related packages. I think it's fair that if you want composer to work with the default `php`, then upstream's installation procedure (`curl -sS https://getcomposer.org/installer | php`) is far more simple than what you would get with  a modification to this formula (example: `#install brew ; brew tap homebrew/php && brew install composer --with-builtin-php` or similar). I'm closing this and suggesting you install composer as per https://getcomposer.org/download/ as customize to your needs.
