### ISSUE TITLE
Cannot find OpenSSL's <evp.h>

### ISSUE THREAD

**Issue by Iceoul** [Homebrew/homebrew-php#1467]
$ brew install php56（when enter this commend,there will show this error message:）

configure: error: Cannot find OpenSSL's <evp.h>

How to do next?

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
