### ISSUE TITLE
Install php56-mongo failed

### ISSUE THREAD

**Issue by ebuildy** [Homebrew/homebrew-php#1475]
I am running Yosemite, php56 has been installed successfully.

    brew install php56-mongo

==> Installing php56-mongo from homebrew/homebrew-php
==> Installing php56-mongo dependency: php56
==> Downloading https://www.php.net/get/php-5.6.3.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.3
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.3 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-scan-
==> make

.... lot of lines ^^ ..........

And Kaboom:

/bin/sh: line 1: 11711 Segmentation fault: 11  ` if test -x "/private/tmp/php56-n3TEaF/php-5.6.3/sapi/cli/php"; then /private/tmp/php56-n3TEaF/php-5.6.3/build/shtool echo -n -- "/private/tmp/php56-n3TEaF/php-5.6.3/sapi/cli/php -n"; if test "x" != "x"; then /private/tmp/php56-n3TEaF/php-5.6.3/build/shtool echo -n -- " -d extension_dir=/private/tmp/php56-n3TEaF/php-5.6.3/modules"; for i in bz2 zlib phar; do if test -f "/private/tmp/php56-n3TEaF/php-5.6.3/modules/$i.la"; then . /private/tmp/php56-n3TEaF/php-5.6.3/modules/$i.la; /private/tmp/php56-n3TEaF/php-5.6.3/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /private/tmp/php56-n3TEaF/php-5.6.3/build/shtool echo -n -- "/private/tmp/php56-n3TEaF/php-5.6.3/sapi/cli/php"; fi;` -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /private/tmp/php56-n3TEaF/php-5.6.3/ext/phar/build_precommand.php > ext/phar/phar.php
make: *** [ext/phar/phar.php] Error 139

**Comment by alanthing** [comment]
Since we've updated PHP to 5.6.6, which is built from a bottle to minimize compilation issues; could you `brew update`, `brew upgrade php56`, and then try this install again?

**Comment by alanthing** [comment]
I'm closing this due to the number of changes made in the last several weeks. Please re-open or comment if your issues persist.

**Comment by alanthing** [comment]
I also have PRs in the testing queue for the latest version of Mongo, which should build binary bottles, so, once merged, try the latest version with a bottled PHP binary before reporting back.
