### ISSUE TITLE
php-5.6-pdo-dblib fails when commented

### ISSUE THREAD

**Issue by velikanov** [Homebrew/homebrew-php#1480]
got this in .ini file:

    ;[pdo_dblib]
    ;extension="/usr/local/Cellar/php56-pdo-dblib/%whatever%/pdo_dblib.so"

when running brew upgrade:

    Error: inreplace failed
    /usr/local/etc/php/5.6/conf.d/ext-pdo_dblib.ini:
      expected replacement of /^(zend_)?extension=.+$/ with "extension=\"/usr/local/Cellar/php56-pdo-dblib/5.6.3/pdo_dblib.so\""

**Comment by alanthing** [comment]
This was resolved in #1436.

**Comment by velikanov** [comment]
:+1:
