### ISSUE TITLE
Apache won't start after installing php56 --with-postgresql

### ISSUE THREAD

**Issue by BillGoldsmith** [Homebrew/homebrew-php#1489]
apachectl says:

httpd: Syntax error on line 172 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _lo_lseek64\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /usr/lib/libpq.5.dylib\n in /usr/local/opt/php56/libexec/apache2/libphp5.so

Haven't been able to find any references to this specific error.  This is a brand new, fresh install of 10.10 with Homebrew 0.9.5, Xcode 6.1.1, & the stock Apache. php built without errors, & cli works just fine. which php returns /usr/local/bin/php.

**Comment by ClleaR** [comment]
same problem

**Comment by linkingarts** [comment]
Not sure if this is what CamJN did but

```
$ sudo rm /usr/lib/libpq.5.dylib
$ sudo ln -s /usr/local/Cellar/postgresql/9.3.5_1/lib/libpq.dylib /usr/lib/libpq.5.dylib
$ sudo apachectl restart
$ sudo apachectl configtest
```

**Comment by BillGoldsmith** [comment]
That's it.  I just did:
sudo rm /usr/lib/libpq.5.dylib
sudo ln -s /usr/local/Cellar/postgresql/9.4.0/lib/libpq.dylib /usr/lib/libpq.5.dylib
(same as above, but with my postgres version) & apache starts without error.
Obviously having php use the correct library would be preferable, but at least my box is happy :-)

**Comment by linkingarts** [comment]
yeah, I don't think this is exactly optimal but it works for now...

**Comment by jfi** [comment]
This worked for me too, thanks all.

**Comment by alanthing** [comment]
This code determines which files to include when using `--with-postgres`:

```ruby
    if build.with? 'postgresql'
      if Formula['postgresql'].opt_prefix.directory?
        args << "--with-pgsql=#{Formula['postgresql'].opt_prefix}"
        args << "--with-pdo-pgsql=#{Formula['postgresql'].opt_prefix}"
      else
        args << "--with-pgsql=#{`pg_config --includedir`}"
        args << "--with-pdo-pgsql=#{`which pg_config`}"
      end
    end
```

I've never used Postgres on OS X; would it make sense if the issue here was that Homebrew's installation was picking up a `pg_config` in /usr/local/bin and include directories from /usr (ie - outside of Homebrew)? Judging by your workarounds, it seems as though the method used to determine the include directory and the `pg_config` binary might be the issue. Thoughts?

**Comment by BillGoldsmith** [comment]
Here's what I see on my system:

Mac-sd:~ bill$ ls -l `which pg_config`
lrwxr-xr-x  1 bill  admin  40 Dec 30 18:07 /usr/local/bin/pg_config -> ../Cellar/postgresql/9.4.0/bin/pg_config

Postgres was installed via Hombrew, prior to installing php.  I confirmed that via timestamp:

Mac-sd:~ bill$ ls -l `which php`
lrwxr-xr-x  1 bill  admin  29 Dec 31 10:15 /usr/local/bin/php -> ../Cellar/php56/5.6.4/bin/php

OSX used to ship with a version of Postgres installed by default, but I don't believe that's any longer the case. So the Homebrew installation should be the only one. I don't see any others:

Mac-sd:~ bill$ sudo find /usr -name psql
/usr/local/bin/psql
/usr/local/Cellar/postgresql/9.4.0/bin/psql

**Comment by alanthing** [comment]
@BillGoldsmith you should have the directory `/usr/local/opt/postgres` if you have installed postgres within the last few months. Do you recall when you installed postgres locally? You may want to consider reinstalling it after a `brew update`, and then trying this install option again. The formula is looking for the /usr/local/opt directory for the `pg_config` information. Just something to try.

**Comment by BillGoldsmith** [comment]
I installed postgres via `brew install postgres`, which uses
/usr/local/var/postgres.  Seems like php should expect that as a
possibility, no?

thanks
-bg

---
Bill Goldsmith
Radio Paradise
www.radioparadise.com

**Comment by alanthing** [comment]
That's for the user data directory, right? Homebrew creates a symlink for the current "Cellar". For example, `/usr/local/opt/php56` is a symlink to `/usr/local/Cellar/php56/5.6.6/`. You could reinstall postgres and give it a shot nonetheless.

**Comment by ablyler** [comment]
@BillGoldsmith did you install php with the `--with-postgres` option?

**Comment by ablyler** [comment]
Closing due to lack of feedback.

**Comment by edrozenberg** [comment]
Same problem here. On two different Macs. Installed and reinstalled homebrew postgres and php56 several times. I do have a /usr/local/opt/postgresql directory. The error is the same as mentioned by others:

    sudo apachectl configtest

    httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _lo_lseek64\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /usr/lib/libpq.5.dylib\n in /usr/local/opt/php56/libexec/apache2/libphp5.so

**Comment by edrozenberg** [comment]
Works fine with php55 by the way. Something in the php56 config step must be picking up a wrong path somehow, even though the php56 config output looks totally fine:

````
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.12 
--localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 
--with-config-file-path=/usr/local/etc/php/5.6 
--with-config-file-scan-dir=/usr/local/etc/php/5.6/conf.d 
--mandir=/usr/local/Cellar/php56/5.6.12/share/man --enable-bcmath 
--enable-calendar --enable-dba --enable-exif --enable-ftp --enable-gd-native-ttf 
--enable-mbregex --enable-mbstring --enable-shmop --enable-soap --enable-sockets 
--enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip 
--with-freetype-dir=/usr/local/opt/freetype --with-gd 
--with-gettext=/usr/local/opt/gettext --with-iconv-dir=/usr 
--with-icu-dir=/usr/local/opt/icu4c --with-jpeg-dir=/usr/local/opt/jpeg 
--with-kerberos=/usr --with-libedit --with-mhash --with-ndbm=/usr 
--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc 
--with-png-dir=/usr/local/opt/libpng --with-unixODBC=/usr/local/opt/unixodbc 
--with-xmlrpc --with-zlib=/usr --with-readline=/usr/local/opt/readline 
--without-gmp --without-snmp --with-apxs2=/usr/sbin/apxs 
--libexecdir=/usr/local/Cellar/php56/5.6.12/libexec --with-bz2=/usr 
--with-openssl=/usr/local/opt/openssl --enable-fpm --with-fpm-user=_www 
--with-fpm-group=_www --with-curl --with-xsl=/usr 
--with-imap=/usr/local/opt/imap-uw --with-imap-ssl=/usr/local/opt/openssl 
--with-ldap --with-ldap-sasl=/usr --with-mysql-sock=/tmp/mysql.sock 
--with-mysqli=mysqlnd --with-mysql=mysqlnd --with-pdo-mysql=mysqlnd 
--disable-opcache --enable-pcntl --with-pgsql=/usr/local/opt/postgresql 
--with-pdo-pgsql=/usr/local/opt/postgresql --enable-phpdbg --enable-phpdbg 
--enable-zend-signals
````

**Comment by edrozenberg** [comment]
As a workaround I did the same as other folks, copied the 5.7 libpq from the homebrew postgres to /usr/lib and changed the symlinks so I wind up with the following:

    /usr/lib]$ ls -al libpq*

````
-rwxr-xr-x  1 root  wheel   152K Jul  5 23:41 libpq.5.5.dylib
-rwxr-xr-x  1 root  wheel   153K Aug 19 07:26 libpq.5.7.dylib
lrwxr-xr-x  1 root  wheel    15B Aug 19 07:44 libpq.5.dylib -> libpq.5.7.dylib
lrwxr-xr-x  1 root  wheel    15B Aug 19 07:45 libpq.dylib -> libpq.5.7.dylib
````

**Comment by javian** [comment]
This is most likely due the apache envvars script as described in #2508 not loading the right library as you've already identified.
