### ISSUE TITLE
Cannot find OpenSSL's <evp.h>

### ISSUE THREAD

**Issue by figueiredouc** [Homebrew/homebrew-php#1490]

**Comment by DomT4** [comment]
See #1467 and #1181.

Either install Apple's CLT package, or try ` brew install phpxx --with-brewed-openssl `.

**Comment by nathandunn** [comment]
does not fix for me (did both)

**Comment by Anei** [comment]
@nathandunn please see #1467, I found my solution there.

**Comment by nathandunn** [comment]
@Anei  Wasn't sure which one, but I think this one did the trick:

Yep, installing the Command Line tools directly from Apple did the trick:
["Command Line Tools (OS X 10.10) for Xcode - Xcode 6.1.1" (169.94 MB)](https://developer.apple.com/downloads/index.action?name=for%20Xcode%20-#)

I didn't think that was a solution as I had went into the App Store update and I was "up to date" with the command line tools.  Thanks / feel free to close.
