### ISSUE TITLE
Not able to install php55 in /usr/local/Cellar !!

### ISSUE THREAD

**Issue by paramsinghvc** [Homebrew/homebrew-php#1505]
I'm running Yosemite and have installed nginx, mysql. I can find them in /usr/local/Cellar but the whole problem is with php55 with fpm. It's folder is not there inside that directory nor elsewhere but when I run php -v or php-fpm -v, it shows the installed version. I'm very confused. Please help me. I need to run Nginx host using php-fpm for which I have to start php-fpm first.

**Comment by alanthing** [comment]
Did you install via `brew install php55 --with-fpm` or similar? Also, post the gist-logs per the [Troubleshooting page](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md). I'm closing this but feel free to re-open if you continue to have trouble.
