### ISSUE TITLE
Libcrypto not found on php55 install

### ISSUE THREAD

**Issue by skhani** [Homebrew/homebrew-php#1506]
brew install php55                                         
==> Installing php55 from homebrew/homebrew-php
==> Downloading https://www.php.net/get/php-5.5.20.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-5.5.20
==> Patching
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.20 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5 --with-config-fi
checking for X509_free in -lcrypto... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... no
configure: error: libcrypto not found!
couldn't understand kern.osversion `14.0.0'

any ideas? 
I've tried moving over the libcrypto files to /usr/lib  but no luck

**Comment by alanthing** [comment]
Please follow the [Troubleshooting](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md) steps and re-open if you'd like further help.
