### ISSUE TITLE
Unable to install phplint - osx Yosemite

### ISSUE THREAD

**Issue by satblip** [Homebrew/homebrew-php#1514]
Hey guys,

I'm not able to install PHPLint on osx. Here is the trace:
https://gist.github.com/anonymous/a6860a60549fae281f8d

Many thanks in advance!

Best regards,
Louis

**Comment by alanthing** [comment]
Were you able to get this resolved on your own? I'm not seeing anything conclusive in your gist other than a compiler error. You may want to try re-installing the Xcode Command Line Tools. Re-open this issue if necessary.
