### ISSUE TITLE
Failed to update tap: homebrew/php

### ISSUE THREAD

**Issue by aiyuchen** [Homebrew/homebrew-php#1520]
How Can I do it
```
brew update
error: Your local changes to the following files would be overwritten by merge:
	Formula/php56.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failed to update tap: homebrew/php
```

**Comment by alanthing** [comment]
Try this:

    cd $(brew --prefix)/Library/Taps/homebrew/homebrew-php
    git checkout -- Formula/php56.rb

Then, run `brew update` again.

**Comment by aiyuchen** [comment]
@alanthing thks

**Comment by alanthing** [comment]
You're welcome!

**Comment by jorgeorpinel** [comment]
I have the same problem, alanthing's solution didn't work for me ):

**Comment by josegonzalez** [comment]
Seems like your repo is just broken. Untap `homebrew/php` and retap it.

**Comment by jorgeorpinel** [comment]
Thanks @josegonzalez I have no idea what tapping or untapping are but `brew untap homebrew/php` before `brew update` worked (:
