### ISSUE TITLE
Failed brew update for tap josegonzales/php

### ISSUE THREAD

**Issue by perajovic** [Homebrew/homebrew-php#1521]
Just updated to 10.10.2 and I'm getting an error from screenshot.

Any hints?

![screen shot 2015-01-27 at 19 49 33](https://cloud.githubusercontent.com/assets/747716/5924668/d4387b4c-a65d-11e4-9edc-7ae0b1e1d39a.png)

**Comment by alanthing** [comment]
Make sure you're using the HTTPS git URL:

    cd $(brew --prefix)/Library/Taps/homebrew/homebrew-php
    git remote set-url origin https://github.com/Homebrew/homebrew-php.git

Then, try `brew update` again.

**Comment by josegonzalez** [comment]
Wow it hasn't been josegonzalez/php in quite a while...

**Comment by perajovic** [comment]
Thanks.

Just I think that first command should be:
```cd  $(brew --prefix)/Library/Taps/josegonzalez/homebrew-php```

**Comment by alanthing** [comment]
Sure, but as @josegonzalez implied, that's a pretty old path. You might want to `brew untap josegonzalez/php && brew tap homebrew/php` so documentation and hive-mind info is up to date.

**Comment by perajovic** [comment]
Ok. I understand now.

If I untap ```josegonzalez/php``` and tap ```homebrew/php``` should I reinstall php stuff installed with ```josegonzalez/php```?

**Comment by alanthing** [comment]
Nah, you shouldn't need to reinstall anything. This will just ensure the git repository in the tap folder is using the current URL to this Github project. Installed packages will still work.

**Comment by perajovic** [comment]
Yes it works. Thanks once again!
