### ISSUE TITLE
php56 Problems with 10.10.2

### ISSUE THREAD

**Issue by majorsl** [Homebrew/homebrew-php#1528]
Hello, I'm have a couple of problems with php56 on OS X 10.10.2 (with Server 4). Trying to use Homebrew's php in place of OS X servers crippled one.

First one, and I may have posted in the wrong area, is --with-tidy it fails. Details and gist are over here:
https://github.com/Homebrew/homebrew-dupes/issues/419

I skipped tidy to see if there were any other issues while waiting for a tip on that, and...

Secondly, the launchd script refers to: /usr/local/opt/php56/sbin/php-fpm

I have neither that sbin directory path nor the php.fpm, although php56 reported build success. Here's some output for that issue:

https://gist.github.com/anonymous/335d51158ead7c33c186

Thanks for any suggestions!

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
