### ISSUE TITLE
Unable to complete the make

### ISSUE THREAD

**Issue by andreamoro** [Homebrew/homebrew-php#1531]
I have the package running on my Mac OS X Yosemite since 30 minutes now without no sign this to complete.

After having installed all the packages required as described in the appropriate section, I used the following command
`brew install php56 --with-fpm`

and the output doesn't seem to be willing to change from
    $~/WebSites/Jump$ brew install php56 --with-fpm
    ==> Installing php56 from homebrew/homebrew-php
    ==> Downloading https://www.php.net/get/php-5.6.5.tar.bz2/from/this/mirror
    Already downloaded: /Library/Caches/Homebrew/php56-5.6.5
    ==> ./configure --prefix=/usr/local/Cellar/php56/5.6.5 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/us
    ==> make

Any idea?

**Comment by alanthing** [comment]
Add `-v`, ala `brew install -v php56 --with-fpm` and report back.
