### ISSUE TITLE
Drush should have flags for version branches

### ISSUE THREAD

**Issue by fuzzy76** [Homebrew/homebrew-php#1538]
This would be nice both for people that need to use legacy branches, and those that want the master branch (since it is required for D8 compatibility, and will stay so until Drush v8).

**Comment by alanthing** [comment]
I actually think the currently situation is good- the current version of Drush, 6.5, works with the current version of Drupal, 7, by default with no options. If you're using Drupal 8, which is pre-release, you can instead Drush from brew with --HEAD. Once Drupal 8 and Drush 7 are released, we can make a drush6 formula for folks who need drush for older versions of Drupal. Sound good?

**Comment by fuzzy76** [comment]
You are completely right. I did not realize --HEAD worked with Drush, but it does. :)
