### ISSUE TITLE
php55, php56 install freezes Yosemite

### ISSUE THREAD

**Issue by prismwebdesign** [Homebrew/homebrew-php#1541]
## System Information
Mac OS X Version: 10.10.2 (14C109)
Homebrew Version: 0.9.5
Stock apple PHP currently installed
Xcode Version 6.1.1 (6A2008a)
gcc -v: 
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```
php -v:
```
PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```
brew doctor: ```Your system is ready to brew.```

gist of command output: https://gist.github.com/prismwebdesign/16930d1e3aefc612ccf5
gist of command output: https://gist.github.com/prismwebdesign/4f9166fed958788049e6

## Error Details
I've been trying to install php55 or php56 on my mac ever since the release of Yosemite. Whenever I issue "brew install php55" or "brew install php56" command, regardless of the options, it will freeze my computer during the make phase. As you can see in the gists, it makes it as far as the unixtime2tm compilation when it then hangs, my computer becomes inop, and I have to manually power off the computer. Does anyone have any ideas?

**Comment by ededagic** [comment]
Same problem here.

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.

**Comment by prismwebdesign** [comment]
It works now. Thank you, @alanthing!!!

**Comment by prismwebdesign** [comment]
@alanthing The bottles are working great. But I think there's a deeper issue. Everytime something attempts to compile on my machine, my computer will freeze. The latest manifestation of this issue is php56-mcrypt. Do you have any idea how I'd go about trying to troubleshoot the brew compilation issue? My hunch is that the problem lies in a misconfiguration in the build process, but I'm not sure where.

**Comment by 007pig** [comment]
Same problem here.

**Comment by 007pig** [comment]
I don't think this issue is resolved.

brew install --without-apache php56

Still freeze my OS.
