### ISSUE TITLE
brew installs php56, but after install no formula, no installation

### ISSUE THREAD

**Issue by salex772** [Homebrew/homebrew-php#1542]
What is the status of installation. I got this

========
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://www.php.net/get/php-5.6.5.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.5
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.5 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-conf
==> make
==> make install
==> /usr/local/Cellar/php56/5.6.5/bin/pear config-set php_ini /usr/local/etc/php/5.6/php.ini system
config-set
php_ini
/usr/local/etc/php/5.6/php.ini
system

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

===================================

but I cannot find php after it, where is it? No folder under Cellar, no any folders with php and also brew list does not contain php56.

WTF ???

**Comment by alanthing** [comment]
Do a `brew uninstall --force php56` and try again and let us know how it goes.

**Comment by salex772** [comment]
I did it and then tried again. But the same. No status, no errors, no php56.
Have a look on my screenshot http://joxi.ru/Y2LjbjaIqZljr6

**Comment by alanthing** [comment]
We recently rolled out bottles for the main php5x formulas in 9f7a735. Please `brew update`, `brew upgrade`, and retry. If you have further problems, please reopen this issue.
