### ISSUE TITLE
[php55] php_intl.dll enabled,but appear warning unable to load php_intl.dll

### ISSUE THREAD

**Issue by xujiajun** [Homebrew/homebrew-php#1546]
hi, i use brew install php55,
i remove “ ; ”    let  extension=php_intl.dll enabled in php.ini

then i  reloaded  php-fpm and  nginx , inputed in the iterm：
> php -v

warnings  to appear：

 > PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55/5.5.14/lib/php/extensions/no-debug-non-zts-20121212/php_intl.dll' - dlopen(/usr/local/Cellar/php55/5.5.14/lib/php/extensions/no-debug-non-zts-20121212/php_intl.dll, 9): image not found in Unknown on line 0

so i googled the answer to the question, but no one worked.

finally , i found this[https://github.com/Homebrew/homebrew-php/issues/1302] , 
i tried php --ini 
but i can't found ext-intl.ini file  that lucasmichot said.
even i didnt have  dir  “/usr/local/etc/php/conf.d”

who can help me ? Any suggestions ?Thanks a lot.

**Comment by alanthing** [comment]
You should re-add the comment. Extensions ending in ".dll" are for Windows.

INTL is already enabled: run `php -i | grep intl` and you'll see that, without any changes to php.ini, the extension is loaded. You may need to do further configuration on the intl parameters, but you do not need to load the extension manually.

**Comment by xujiajun** [comment]
@alanthing   if without any changes to php.ini,   run  `php - i |grep intl ` , nothing appear. it  didn't match your expectations. it  means NTL  is not loaded.

**Comment by szujak** [comment]
@xujiajun you can try http://stackoverflow.com/a/23344126
