### ISSUE TITLE
Ioncube Loader 5.6

### ISSUE THREAD

**Issue by ededagic** [Homebrew/homebrew-php#1550]
Hello,
could it be possible to add the ioncube loader formula for php 5.6?

**Comment by alanthing** [comment]
Closing; it's being worked on in #1552.

**Comment by Zifius** [comment]
The formula has been added, thanks for raising the issue

**Comment by ededagic** [comment]
THX!
-------------------------------------------------------

Edin Dedagic

Web -/App Entwicklung

 

Dedagic und Scholten GbR

Kruppstr. 82-100

45145 Essen

 

Tel.:        +49 (0) 201 - 47 64 60 26

Fax.:       +49 (0) 201 - 47 64 60 27

Mob.:     +49 (0) 174 - 24 51 43 8

 

Web.:     www.webversiert.de

 

Der Inhalt dieser e-Mail ist ausschließlich für den bezeichneten 
Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser e-Mail 
oder dessen Vertreter sein sollten, beachten Sie bitte, dass jede Form der 
Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser 
e-Mail unzulässig ist. Wir bitten Sie sofort den Absender zu informieren 
und die e-Mail zu löschen.

 

The information contained in this e-mail is intended solely for the 
addressee. Access to this e-mail by anyone else is unauthorized. If you 
are not the intended recipient, any form of disclosure, reproduction, 
distribution or any action taken or refrained from in reliance on it, is 
prohibited and may be unlawful. Please notify the sender immediately and 
destroy this e-mail.


Von:  Alexander Turiak <notifications@github.com>
Antworten an:  Homebrew/homebrew-php 
<reply+0088fc8201750942c499e598855877258bd277ae6aef00ff92cf00000001110ea5e3
92a169ce03815f12@reply.github.com>
Datum:  Mittwoch, 4. März 2015 11:52
An:  Homebrew/homebrew-php <homebrew-php@noreply.github.com>
Cc:  Edin Dedagic <edin@webversiert.de>
Betreff:  Re: [homebrew-php] Ioncube Loader 5.6 (#1550)


The formula has been added, thanks for raising the issue
