### ISSUE TITLE
Something error for php56-xdebug and composer

### ISSUE THREAD

**Issue by breestealth** [Homebrew/homebrew-php#1555]
If I install php56-xdebug(`brew install php56-xdebug`) and run `composer <TAB>`, I will get the message
```
composer Failed loading /usr/local/opt/php56-xdebug/xdebug.so:  dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php56-xdebug/xdebug.so
```
Instead I install php56-xdebug with `brew install php56-xdebug --HEAD` it would be OK.

Maybe the precompiled version of php56-xdebug has something wrong.

**Comment by alanthing** [comment]
You probably need to upgrade PHP 5.6 to the latest version. Run `brew
update ; brew upgrade php56`

On Wednesday, February 25, 2015, Francis Chen <notifications@github.com>
wrote:

> If I install php56-xdebug(brew install php56-xdebug) and run composer
> <TAB>, I will get the message
>
> composer Failed loading /usr/local/opt/php56-xdebug/xdebug.so:  dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): Symbol not found: _basic_globals
>   Referenced from: /usr/local/opt/php56-xdebug/xdebug.so
>   Expected in: flat namespace
>  in /usr/local/opt/php56-xdebug/xdebug.so
>
> Instead I install php56-xdebug with brew install php56-xdebug --HEAD it
> would be OK.
>
> Maybe the precompiled version of php56-xdebug has something wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew-php/issues/1555>.
>


-- 
Sent from a mobile device

**Comment by breestealth** [comment]
I have run `brew update && brew upgrade` when I upgrade the homebrew, so I am sure that the php56 is the newest version.
This is the result of `php -v`:
```
php -v
Failed loading /usr/local/opt/php56-xdebug/xdebug.so:  dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php56-xdebug/xdebug.so
PHP 5.6.6 (cli) (built: Feb 24 2015 18:27:17)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

And I found if I remove the php56 and install from homebrew, I got the message:
```
> brew install php56
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-php/php56-5.6.6.yosemite.bottle.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 27f4b0c52c0504a45b4a412c8f4cf36c4ff841c8
Actual: d4d0fed5375d3d82f05d5618c40af42a43a6f5f8
Archive: /Library/Caches/Homebrew/php56-5.6.6.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
```
So the homebrew install php56 for me in the compile form.

**Comment by breestealth** [comment]
And I download the `php56-5.6.6.yosemite.bottle.tar.gz` and find the sha1sum of the Formula is mismatch as the message I mentioned above.

**Comment by breestealth** [comment]
I think I found the reason of this issue. 
The sha1 of `php56-5.6.6.yosemite.bottle.tar.gz` is mismatch, so Homebrew install PHP56 from source. When I `brew install php56-xdebug` the precompile version of php56-xdebug was downloaded and loaded. 
The php5.6.6 which is from source code is not compatible with the precompile php56-xdebug.
