### ISSUE TITLE
Failed loading /usr/local/opt/php56-xdebug/xdebug.so: dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): Symbol not found: _basic_globals

### ISSUE THREAD

**Issue by ianbytchek** [Homebrew/homebrew-php#1556]
I'm getting those very weird issues after upgrading to the latest xdebug. A similar thing happens with the blackfire-php56 extension, but different symbol.

```
$ php -v
Failed loading /usr/local/opt/php56-xdebug/xdebug.so:  dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php56-xdebug/xdebug.so
PHP 5.6.6 (cli) (built: Feb 20 2015 18:13:17) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

What is this and how to fix this?

**Comment by ianbytchek** [comment]
Fixed by reinstalling the xdebug plugin with `--build-from-source` option. Is there a reason though why something like this happens?

```
Symbol not found: _basic_globals
```

I get this with some other plugins and I'm pretty sure I screwed something somewhere up. I've reinstalled php clean, that didn't help.

**Comment by alanthing** [comment]
I don't think this is your fault- we're moving from source-by-default for the main PHP formulas to bottles-by-default, and we might be running into an issue where small compiler differences create trouble. I'm removing the bottle references in xdebug for now. I have some suspicions about how to fix the problem long-term, but I need to do testing first.

Run `brew update` and try again without `--build-from-source` and let us know if it improves things for you.

**Comment by edigu** [comment]
It seems like this problem not directly related with xdebug. Today I tried to remove, cleanup and install php56 with the command and extensions below:

$ brew install php56 --with-homebrew-curl --with-thread-safety --with-postgresql

 - php56-amqp
 - php56-apcu
 - php56-http
 - php56-igbinary
 - php56-imagick
 - php56-mcrypt
 - php56-memcached
 - php56-solr
 - php56-tidy
 - php56-xdebug

And now getting bunch of similar startup errors:

```
$ php -v
Failed loading /usr/local/opt/php56-xdebug/xdebug.so:  dlopen(/usr/local/opt/php56-xdebug/xdebug.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php56-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php56-xdebug/xdebug.so
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-igbinary/igbinary.so' - dlopen(/usr/local/opt/php56-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php56-igbinary/igbinary.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-igbinary/igbinary.so' - dlopen(/usr/local/opt/php56-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php56-igbinary/igbinary.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-memcached/memcached.so' - dlopen(/usr/local/opt/php56-memcached/memcached.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-memcached/memcached.so
  Expected in: flat namespace
 in /usr/local/opt/php56-memcached/memcached.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-memcached/memcached.so' - dlopen(/usr/local/opt/php56-memcached/memcached.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-memcached/memcached.so
  Expected in: flat namespace
 in /usr/local/opt/php56-memcached/memcached.so in Unknown on line 0
PHP 5.6.6 (cli) (built: Mar 17 2015 13:35:17) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

any ideas?

**Comment by edigu** [comment]
Interesting, i just reinstalled all extensions using `--build-from-source` parameter and now everything is fine.

```
$ brew reinstall php56-amqp php56-apcu php56-http php56-igbinary php56-imagick php56-mcrypt php56-memcached php56-solr php56-tidy php56-xdebug --build-from-source
$ php -v
PHP 5.6.6 (cli) (built: Mar 17 2015 13:35:17) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by alanthing** [comment]
Hm, there must be something about the compile process for the binary bottles versus a normal build-from-source option that makes it so mixed source and compiled modules can't co-exist. We've been building our bottles on bot.brew.sh and I'll look more into how that build environment might be different than others. For now, and for anyone visiting this issue; if you've built `php56` (or another version) from source, you'll want to also build modules/extensions from source.

**Comment by jrschumacher** [comment]
I have experienced this too. I am using the homebrew version of gcc if that matters

```
> $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/4.9.2_1/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/lto-wrapper
Target: x86_64-apple-darwin14.0.0
Configured with: ../configure --build=x86_64-apple-darwin14.0.0 --prefix=/usr/local/Cellar/gcc/4.9.2_1 --libdir=/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-cloog=/usr/local/opt/cloog --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc 4.9.2_1' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.2 (Homebrew gcc 4.9.2_1)
```

**Comment by koenpunt** [comment]
Adding a note for the requirement of adding `--build-from-source` when installing extensions for a php installed with `--with-debug` would be nice, until things are working properly.

**Comment by alanthing** [comment]
To sum this up: It seems as though this might be cause by the main `php56` (or 55, etc) being installed with `--with-debug` or `--enable-phpdgb-debug`, and then subsequent extensions cannot use the pre-built binary bottles that do not have debug enabled, and thus need the `--build-from-source` option so they inherit PHP's built options.

The main `php5x` formulas already have a **lot** of notes/caveats. But, I'll try and find an appropriate place for such a note.

Thanks @koenpunt and everything else who contributed on this issue.

**Comment by JackyChan** [comment]
It seems that cause by --with-thread-safety, if compile php with thread safe, then the extension fail to load.

**Comment by javian** [comment]
Yes - bottles are not compiled with any additional php options you might have so you need to install the formula with `brew install --build-from-source php56-xdebug` and then it should work.
