### ISSUE TITLE
Segfault issues with xdebug 2.3.1

### ISSUE THREAD

**Issue by localheinz** [Homebrew/homebrew-php#1569]
Would it make sense to update the `php(\d{2})-xdebug.rb` formulas to revert to xdebug 2.30 to avoid segmentation fault issues?

See http://bugs.xdebug.org/view.php?id=1122

**Comment by localheinz** [comment]
I fixed the issue by installing it myself:

* http://xdebug.org/docs/install

There's a great wizard which makes it a non-issue.

* http://xdebug.org/wizard.php

Leaving this issue open, though, as it is a problem.

**Comment by alanthing** [comment]
Could you please elaborate on the solution?

**Comment by localheinz** [comment]
@alanthing 

Sure, here's what I did:

### Uninstall xdebug previously installed with Homebrew

```bash
$ brew uninstall php56-xdebug
```

### Get `phpinfo()`

```
$ php -i | pbcopy
```

### Check out the wizard

Head over to http://xdebug.org/wizard.php, paste into textfield and hit the button, but instead of the download steps suggested there

>1. Download xdebug-2.3.1.tgz
2. Unpack the downloaded file with tar -xvzf xdebug-2.3.1.tgz
3. Run: cd xdebug-2.3.1

do the following

```bash
$ mkdir ~/Sites/xdebug && cd ~/Sites/xdebug
$ git clone git@github.com:xdebug/xdebug.git
$ cd xdebug
```

Then continue with the rest of the instructions. 

Hope it helps!

**Comment by alanthing** [comment]
Thanks for sharing. I have PRs submitted for testing to revert to 2.2.x until 2.3.2 is released. I'll close this issue.

If you're watching the Xdebug project for when 2.3.2 is released, please send us a PR for updating here in Homebrew-php so we can get the latest version out for everyone.

**Comment by wonder95** [comment]
I have been fighting all day trying to get php56-xdebug working - it uses xdebug 2.3.2 - but I am still getting the same segmentation fault error.

**Comment by grayloon** [comment]
You mean 2.2.7?
