### ISSUE TITLE
php55-ioncubeloader incorrect SHA1

### ISSUE THREAD

**Issue by nesh** [Homebrew/homebrew-php#1570]
Looks like ioncube changed contents of the loader archives so I'm getting SHA1 Mismatch errors:
Looking at the code expected for 64bit is `1d255625981c1117195bf526d431852104e57c9c` while downloaded file is `efaf20824824395823c7f5c3ddf95042f65cf85d`. I got identical (new) signatures from the files downloaded directly from their site. Same is for 32bit versions.

Any pointers how to fix it?

**Comment by alanthing** [comment]
We discussed this in #1568 and resolved in #1567. The ionCube folks don't provide URLs specific to versions, so we have to omit the SHA1 or it will randomly fail to install whenever they push an updated. It's not ideal, but at least it keeps installations moving forward.

For you, run `brew update` and try to re-install.

**Comment by nesh** [comment]
Thanks, worked like charm :)
