### ISSUE TITLE
phplint fails

### ISSUE THREAD

**Issue by Mech7** [Homebrew/homebrew-php#1577]
$ brew install homebrew/php/phplint
==> Installing phplint from homebrew/homebrew-php
==> Downloading http://www.icosaedro.it/phplint/phplint-pure-c-1.1_20130803.tar.gz
######################################################################## 100.0%
==> Patching
patching file include/missing.c
patching file phpl
==> gcc-4.9 -fnested-functions src/phplint.c -o src/phplint
2015-03-05 16:19:13 +0100

gcc-4.9 -fnested-functions src/phplint.c -o src/phplint

gcc-4.9: error: unrecognized command line option '-fnested-functions'

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

**Comment by alanthing** [comment]
Please see #1529
