### ISSUE TITLE
Can't install xdebug

### ISSUE THREAD

**Issue by mihailShumilov** [Homebrew/homebrew-php#1601]
godson$ brew install php55-xdebug
==> Installing php55-xdebug from homebrew/homebrew-php
==> Downloading http://xdebug.org/files/xdebug-2.2.5.tgz
Already downloaded: /Library/Caches/Homebrew/php55-xdebug-2.2.5.tgz
Error: Unable to guess PHP branch for Formulary::Formulae::Php55Xdebug

**Comment by alanthing** [comment]
Please run `brew update` and try again. The currently-available version in `php55-xdebug` is 2.2.7.
