### ISSUE TITLE
xhprof: Unable to initialize module

### ISSUE THREAD

**Issue by johnbillion** [Homebrew/homebrew-php#1615]
XHProf (installed with brew's `php56-xhprof`) won't initialize because the build it was compiled with doesn't match the one that `php56` was compiled with.

```
PHP Warning:  PHP Startup: xhprof: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
```

Any ideas how to get it working?

**Comment by alanthing** [comment]
We're working on this in #1556. I'll close this issue and we'll work on the debug compile option there. Until then, try installing php56-xhprof with --build-from-source and see if that gets you through this issue.
