### ISSUE TITLE
php53-imagick needs path to imagemagick

### ISSUE THREAD

**Issue by gbeine** [Homebrew/homebrew-php#1618]
brew install php53-imagick fails, even if imagemagick is installed.
This can be fixed by adding the --with-imagick option to the configure args.

Fix:
    system "./configure", "--prefix=#{prefix}",
                          phpconfig,
                          "--with-imagick=#{Formula['imagemagick'].opt_prefix}"

Here is the output of the installation
Problem:
==> Installing php53-imagick from homebrew/homebrew-php
==> Downloading http://pecl.php.net/get/imagick-3.1.0RC2.tgz
Already downloaded: /Library/Caches/Homebrew/php53-imagick-3.1.0RC2.tgz
==> Verifying php53-imagick-3.1.0RC2.tgz checksum
tar xf /Library/Caches/Homebrew/php53-imagick-3.1.0RC2.tgz
==> Patching
patching file imagick-3.1.0RC2/config.m4
==> /opt/homebrew/opt/php53/bin/phpize
Configuring for:
PHP Api Version:         20090626
Zend Module Api No:      20090626
Zend Extension Api No:   220090626
configure.in:3: warning: prefer named diversions
configure.in:3: warning: prefer named diversions
==> ./configure --prefix=/opt/homebrew/Cellar/php53-imagick/3.1.0RC2 --with-php-config=/opt/homebrew/opt/php53/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /opt/homebrew/Library/ENV/4.3/sed
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for icc... no
checking for suncc... no
checking whether clang and cc understand -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... i386-apple-darwin14.1.0
checking host system type... i386-apple-darwin14.1.0
checking target system type... i386-apple-darwin14.1.0
checking for PHP prefix... /opt/homebrew/Cellar/php53/5.3.29
checking for PHP includes... -I/opt/homebrew/Cellar/php53/5.3.29/include/php -I/opt/homebrew/Cellar/php53/5.3.29/include/php/main -I/opt/homebrew/Cellar/php53/5.3.29/include/php/TSRM -I/opt/homebrew/Cellar/php53/5.3.29/include/php/Zend -I/opt/homebrew/Cellar/php53/5.3.29/include/php/ext -I/opt/homebrew/Cellar/php53/5.3.29/include/php/ext/date/lib
checking for PHP extension directory... /opt/homebrew/Cellar/php53/5.3.29/lib/php/extensions/no-debug-zts-20090626
checking for PHP installed headers prefix... /opt/homebrew/Cellar/php53/5.3.29/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.14.1 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable the imagick extension... yes, shared
checking whether to enable the imagick GraphicsMagick backend... no
checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
==> Formula
Tap: homebrew/homebrew-php
Path: /opt/homebrew/Library/Taps/homebrew/homebrew-php/Formula/php53-imagick.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 30124bbcbe42e431aff973cbf72b23329074a3d2
Last commit: vor 24 Stunden
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
CPU: 8-core 64-bit ivybridge
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: N/A
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /opt/homebrew/bin/python => /opt/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_40
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew/opt/gettext:/opt/homebrew/opt/libffi:/opt/homebrew/opt/zlib:/opt/homebrew/opt/icu4c:/opt/homebrew/opt/openssl:/opt/homebrew
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/apache2:/opt/X11/include:/opt/X11/include/freetype2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /opt/X11/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/libffi/lib/pkgconfig:/opt/homebrew/opt/glib/lib/pkgconfig:/opt/homebrew/opt/enchant/lib/pkgconfig:/opt/homebrew/opt/libpng/lib/pkgconfig:/opt/homebrew/opt/freetype/lib/pkgconfig:/opt/homebrew/opt/zlib/lib/pkgconfig:/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/openssl/lib/pkgconfig:/opt/homebrew/opt/libevent/lib/pkgconfig:/opt/homebrew/opt/fontconfig/lib/pkgconfig:/opt/homebrew/opt/libtiff/lib/pkgconfig:/opt/homebrew/opt/little-cms/lib/pkgconfig:/opt/homebrew/opt/little-cms2/lib/pkgconfig:/opt/homebrew/opt/gd/lib/pkgconfig:/opt/homebrew/opt/pixman/lib/pkgconfig:/opt/homebrew/opt/cairo/lib/pkgconfig:/opt/homebrew/opt/gobject-introspection/lib/pkgconfig:/opt/homebrew/opt/gdk-pixbuf/lib/pkgconfig:/opt/homebrew/opt/harfbuzz/lib/pkgconfig:/opt/homebrew/opt/pango/lib/pkgconfig:/opt/homebrew/opt/atk/lib/pkgconfig:/opt/homebrew/opt/gtk+/lib/pkgconfig:/opt/homebrew/opt/libcroco/lib/pkgconfig:/opt/homebrew/opt/libgsf/lib/pkgconfig:/opt/homebrew/opt/librsvg/lib/pkgconfig:/opt/homebrew/opt/liblqr/lib/pkgconfig:/opt/homebrew/opt/ilmbase/lib/pkgconfig:/opt/homebrew/opt/openexr/lib/pkgconfig:/opt/homebrew/opt/webp/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/imagemagick/lib/pkgconfig:/opt/homebrew/opt/postgresql/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/ENV/pkgconfig/10.10:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
ACLOCAL_PATH: /opt/homebrew/opt/gettext/share/aclocal:/opt/homebrew/share/aclocal:/opt/X11/share/aclocal
PATH: /opt/homebrew/Library/ENV/4.3:/opt/homebrew/opt/autoconf/bin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/glib/bin:/opt/homebrew/opt/aspell/bin:/opt/homebrew/opt/enchant/bin:/opt/homebrew/opt/libpng/bin:/opt/homebrew/opt/freetype/bin:/opt/homebrew/opt/icu4c/bin:/opt/homebrew/opt/jpeg/bin:/opt/homebrew/opt/openssl/bin:/opt/homebrew/opt/unixodbc/bin:/opt/homebrew/opt/libevent/bin:/opt/homebrew/opt/php53/bin:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/libtool/bin:/opt/homebrew/opt/fontconfig/bin:/opt/homebrew/opt/libtiff/bin:/opt/homebrew/opt/little-cms/bin:/opt/homebrew/opt/little-cms2/bin:/opt/homebrew/opt/gd/bin:/opt/homebrew/opt/libwmf/bin:/opt/homebrew/opt/cairo/bin:/opt/homebrew/opt/gobject-introspection/bin:/opt/homebrew/opt/gdk-pixbuf/bin:/opt/homebrew/opt/harfbuzz/bin:/opt/homebrew/opt/pango/bin:/opt/homebrew/opt/jasper/bin:/opt/homebrew/opt/gtk+/bin:/opt/homebrew/opt/libcroco/bin:/opt/homebrew/opt/libgsf/bin:/opt/homebrew/opt/librsvg/bin:/opt/homebrew/opt/openexr/bin:/opt/homebrew/opt/jbig2dec/bin:/opt/homebrew/opt/ghostscript/bin:/opt/homebrew/opt/giflib/bin:/opt/homebrew/opt/webp/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/imagemagick/bin:/opt/homebrew/opt/postgresql/bin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin

Error: php53-imagick 3.1.0RC2 did not build
Logs:
     /Users/gbeine/Library/Logs/Homebrew/php53-imagick/01.phpize
     /Users/gbeine/Library/Logs/Homebrew/php53-imagick/02.configure
     /Users/gbeine/Library/Logs/Homebrew/php53-imagick/02.configure.cc
     /Users/gbeine/Library/Logs/Homebrew/php53-imagick/config.log

**Comment by alanthing** [comment]
This will be resolved in #1614.
