### ISSUE TITLE
Failed loading /usr/local/Cellar/php56/5.6.6/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  dlopen(/usr/local/Cellar/php56/5.6.6/lib/php/extensions/no-debug-non-zts-20131226/opcache.so, 9): image not found

### ISSUE THREAD

**Issue by yihangho** [Homebrew/homebrew-php#1620]
I am seeing this error message in, for example, Apache error log and when running `php -v`.

Parameter | Value
------------------ | ------------------
**OS X Version:** | OS X 10.10.2
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.6.6
**Xcode Version:** | 6.2 (6C131e)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1<br>Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)<br>Target: x86_64-apple-darwin14.1.0<br>Thread model: posix
**Output of php -v:** | Failed loading /usr/local/Cellar/php56/5.6.6/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  dlopen(/usr/local/Cellar/php56/5.6.6/lib/php/extensions/no-debug-non-zts-20131226/opcache.so, 9): image not found<br>PHP 5.6.6 (cli) (built: Mar 10 2015 14:21:21) <br>Copyright (c) 1997-2015 The PHP Group<br>Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
**Output of brew install -v php56 within a gist** | https://gist.github.com/yihangho/cdd85ddb7d57b37961f9
**Output of brew doctor within a gist** | Your system is ready to brew.

**Comment by alanthing** [comment]
Looks like you have an old reference to opcache in your settings. Look in /usr/local/etc/php/5.6/php.ini or /usr/local/etc/php/5.6/conf.d/ext-* and remove all references to opcache.

**Comment by yihangho** [comment]
Awesome, that works perfectly. Thanks!

**Comment by jkrehm** [comment]
Just a note in case anyone else runs into this after upgrading to 5.6.7, I had to install `php56-opcache` separately and remove my `opcache` configuration - specifically `zend_extension="opcache.so"` - from `php.ini`. That's what finally got the `/usr/local/Cellar/php56/5.6.7/lib/php/extensions/no-debug-non-zts-20131226/opcache.so` error message to go away. I did not have a reference to `no-debug-non-zts-20131226` anywhere in my configuration, yet it threw up the error, so that must be its default location when you don't specify a full path.

**Comment by anthonybrown** [comment]
worked perfectly @alanthing

**Comment by brunowego** [comment]
:+1:

**Comment by amedeomantica** [comment]
👍

**Comment by jamesmillar** [comment]
+1 :D

**Comment by ghazlewood** [comment]
> Just a note in case anyone else runs into this after upgrading to 5.6.7, I had to install php56-opcache separately and remove my opcache configuration - specifically zend_extension="opcache.so" - from php.ini

:+1:

**Comment by pcambra** [comment]
:+1:

**Comment by pavarnos** [comment]
+1. maybe zend_extension=opcache.so could be commented out in the default configuration if opcache is not included by default?

**Comment by msalahat** [comment]
(y)

**Comment by dmayo2** [comment]
Rock On.

**Comment by ScoutCodes** [comment]
@alanthing , thank you very much)
