### ISSUE TITLE
Need help..

### ISSUE THREAD

**Issue by alfista-sk** [Homebrew/homebrew-php#1621]
Sorry that I write to issues but, don't know where should I write.

I need this PHP modules and can find it. Please is possible to the me which are it from your modules.

gmp (for SFTP storage)
apc
apcu
xcache
imagick
smbclient (for SMB storage)
intl (increases language translation performance and fixes sorting of non-ASCII characters)
mb multibyte

Thanks.

**Comment by josegonzalez** [comment]
Once you install our tap, you can do `brew list | grep php` to see available modules. Some of these are actually built into the php formula itself.

**Comment by alfista-sk** [comment]
Hi, thanks but when I try to find it like: mb multibyte, intl, smbclient but found only with others names.

please is possible to help me? I'm not very familiar with this part. I need it for a web application (ownCloud) for my mac.

I have try to install the mcrypt too but has problems with it doesn't work, but this is another issue.

Thanks for your understanding and help. Your soft help me much. :-)

**Comment by alanthing** [comment]
If the extensions you need are not found via a `brew search php56-${name}`, then you can build them yourself using `pecl` or grabbing the source code and then `phpize ; ./configure ; make ; make install`. The details for doing so are outside the scope of this project.
