### ISSUE TITLE
install php56 --with-mssql NOT including mssql extension

### ISSUE THREAD

**Issue by grgaortiz** [Homebrew/homebrew-php#1623]
I've tried: *brew install php56 --with-mssql --without-snmp*

and also without: *--without-snmp*

I've also loaded *freetds* previous to those cmds

I've updated with *brew update && brew upgrade* and everything is up to date.

I've tried other php versions such as 5.5 and 5.4

**Comment by alanthing** [comment]
https://github.com/Homebrew/homebrew-php#filing-bug-reports

**Comment by tucq88** [comment]
@grgaortiz Did you able to install PHP56 with MSSQL. I'm struggling for hours but can't find any solution.
