### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by hmert** [Homebrew/homebrew-php#1629]
```
_zm_info_apache in php_functions.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....
```

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.2 (14C1514)
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | PHP 5.5.22 (cli) (built: Feb 26 2015 06:47:16) 
**Xcode Version:** | <your Xcode version>
**gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn) Target: x86_64-apple-darwin14.1.0 Thread model: posix
**php -v:** | PHP 5.5.22 (cli) (built: Feb 26 2015 06:47:16) Copyright (c) 1997-2015 The PHP Group Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies     with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans
**brew upgrade -v** | https://gist.github.com/hmert/18713d211fa6e1f1f2d5
**brew doctor** | https://gist.github.com/hmert/e44fc78f8e06bc7d0352

**Comment by alanthing** [comment]
Please try (re)installing Xcode Command Line tools and trying again: `xcode-select --install`

If that doesn't work, try switching the compilers to the non-full-Xcode version and trying again: `sudo xcode-select --switch /Library/Developer/CommandLineTools`
