### ISSUE TITLE
configure: error: could not find zlib.h

### ISSUE THREAD

**Issue by parisnakitakejser** [Homebrew/homebrew-php#1634]
Command: brew install php56-http php56-gmagick php56-imagick php56-mysqlnd_ms

Error:
checking for iswalnum... yes
checking for inet_pton... yes
checking for idna.h... not found
checking for zlib.h... not found
configure: error: could not find zlib.h

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

**Comment by alanthing** [comment]
Please try (re)installing Xcode Command Line tools and trying again: `xcode-select --install`

If that doesn't work, try switching the compilers to the non-full-Xcode version and trying again: `sudo xcode-select --switch /Library/Developer/CommandLineTools`

**Comment by parisnakitakejser** [comment]
i have fixed it, thanks for respons, its end op i reinstall my computer to start on a fresh! and now everything work :)
