### ISSUE TITLE
PHP56, Gettext and nginx crashes

### ISSUE THREAD

**Issue by loranger** [Homebrew/homebrew-php#1638]
Hello,

I'm pulling my hair off with a weird issue :
PHP56, with gettext makes FPM crash with nginx.
It used to work but not anymore and I can't figure out why.

I use this simple file :
```php
<?php

echo _('translation');
```
When I execute it with PHP cli, everything is fine :
```bash
$ php -f index.php
translation
```
When I execute it with the built-in server, it works :
```bash
$ php -S localhost:8989
PHP 5.6.7 Development Server started at Thu Apr  2 11:23:52 2015
Listening on http://localhost:8989
Press Ctrl-C to quit.
[Thu Apr  2 11:24:08 2015] ::1:56458 [200]: /
```
```bash
$ curl http://localhost:8989
translation
```
But as soon as I try to view this page with nginx, FPM segfault :
```bash
$ curl http://127.0.0.1/lab/gettext/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```
I say gettext is involved because I juste have to remove the underscore in my php file `echo ('translation');` to make it work :
```bash
$ curl http://127.0.0.1/lab/gettext/
translation
```

I really don't know what to do. As I said, it used to work perfectly before, and I have no clue about a relation between Gettext, PHP-FPM and Nginx.

My nginx configuration file is quite simple :
```conf
server {
	listen			80;
	server_name		_;
	root /Users/loranger/Sites/lab;

    location / {
        index  index.html index.htm index.php;
    }

    location ~ \.php$ {
       fastcgi_pass   127.0.0.1:9000;
       fastcgi_index  index.php;
       fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
       include        fastcgi_params;
    }

}
```

I tried to `brew reinstall php56 gettext nginx` but the result remains the same.

Did I miss something ?

[Here is the dump](https://gist.github.com/loranger/6e9d5e00221c98db1bb3) of the last FPM crash.

Here is my environment :

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.2
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | php56: stable 5.6.7 (bottled), HEAD
**Xcode Version:** | 6.2 (6C131e)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 <br />Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)<br />Target: x86_64-apple-darwin14.1.0<br />Thread model: posix
**Output of php -v:** | PHP 5.6.7 (cli) (built: Apr  2 2015 10:48:23) <br />Copyright (c) 1997-2015 The PHP Group<br />Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies<br />    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
**Output of brew install -v php56.rb** | https://gist.github.com/loranger/b5848c37e30e45ad087f
**Output of brew info php56** | https://gist.github.com/loranger/608b9109c23df527de77
**Output of brew doctor** | https://gist.github.com/loranger/d49725243267faef40d9

**Comment by alanthing** [comment]
https://gist.github.com/loranger/b5848c37e30e45ad087f seems to indicate that your custom compile options did not "take" because PHP 5.6.7 was already installed. Instead of a re-install, try completely uninstalling php56 and then re-installing with your custom options. Report back how it goes then. I don't know how much I can help beyond this as your setup is not one I'm terribly familiar with.

**Comment by loranger** [comment]
Thank you for the reply.
I followed you advice and remove php56 and its extensions.
I did a `brew cleanup` and [rebuild PHP](https://gist.github.com/loranger/a86b99e94fcaaa8229dd), then I installed the [php extensions](https://gist.github.com/loranger/8a8fe35843688fc94da8) but the issue remains and [PHP-FPM still crashes](https://gist.github.com/loranger/512b30a04eebbe39fafc).
Maybe the issue is on the nginx side of my setup, But I cannot figure out what's involving gettext there...

**Comment by loranger** [comment]
... Aaaaaand after the morning upgrade (which upgraded `libvpx 1.4.0`, `phpmd 2.2.2` and `tor 0.2.5.12`) everything is back to normal.
Really weird.
I think I have a bigger issue than it looks like.

Anyway, Thank you @alanthing for your support.
