### ISSUE TITLE
Add PHP7 formula

### ISSUE THREAD

**Issue by alanwillms** [Homebrew/homebrew-php#1642]
It would be nice to have a formula so that we can easily install PHP 7 development preview.

**Comment by tpetry** [comment]
+1

**Comment by alanthing** [comment]
At this time, while it's in pre-release phase, I'm not terribly interested in writing a formula from scratch since I am completely unaware with how version 7 works, or how it may change and break until it is released. If you or someone else wants to submit a pull request, we will happily consider it with caveats that it may break.

**Comment by stovak** [comment]
this worked for me: brew tap guoxiao/homebrew-php7

at least good enough to test some of my code.

**Comment by alanthing** [comment]
That's great, hopefully others searching find this issue and can use that tap. Once PHP7 is released, I'll reach out to @guoxiao to see about getting version 7 folded in here, but PHP 7 is potentially too volatile to consider inclusion now. Thanks!

**Comment by guoxiao** [comment]
@alanwillms @stovak 
I'm very glad that someone found my tap. :smile: but now the tap is only my experiment and still in progress, and most extensions cannot build. So it's only enough to test some code, but may not be enough to run a complete website now.

**Comment by alanwillms** [comment]
@alanthing can you reopen this now? PHP 7.0.0.alpha1 has been released: http://php.net/archive/2015.php#id2015-06-11-3

**Comment by nivv** [comment]
:+1:

**Comment by jakeasmith** [comment]
Oh funny, just found this through a google search after my blind attempt at `brew install php7` failed :) Do you have a minimum version in mind before you're ready to add support? Alpha, Beta, RC1?

**Comment by alanthing** [comment]
I would still prefer to direct people to @guoxiao's tap as it is far from a stable release. Others in @Homebrew/php -- feel free to override if deemed appropriate.

**Comment by till** [comment]
@alanthing did something change? — `homebrew/php/php70`

**Comment by stovak** [comment]
tried reinstalling beta 1 last night and it threw a "buildconf" error.

**Comment by vedmant** [comment]
It's already php 7 beta 2 version, so there will not by any breaking changes for php 7, just bugfixing. I think it's time to create formula for php7.

**Comment by alanwillms** [comment]
@vedmant they already created a few formulas, however most are missing, like php70-redis, php70-mongo, etc.

**Comment by ablyler** [comment]
@alanwillms most of the extensions do not have versions that compile against php70, as they become avaliable / stable we will add them.
