### ISSUE TITLE
Boris not working with PHP55

### ISSUE THREAD

**Issue by MKorostoff** [Homebrew/homebrew-php#1644]
### Summary
The [boris](https://github.com/borisrepl/boris) PHP interactive shell is currently available for installation with brew.  This provides the ability to enter one line of php at a time, and see the result immediately (much like the mysql command prompt).  It is a very useful feature.  After I upgraded from php54 to php55, I found that boris was no longer working.  I suspect this is due to an unmet dependency in Boris.  If I'm not mistaken, Boris depends on php [readline](http://php.net/manual/en/ref.readline.php) which I don't believe is available from brew.

### Steps to reproduce:
- Install php55 with brew (`brew install php55`, version 5.5.23)
- Install boris with brew (`brew install boris`, version 1.0.8)
- Give the command "boris" to enter a PHP interactive shell
- Set some variable in the php interactive shell, e.g. `$var = 123;`
- Attempt to print the variable you just set, e.g. `print $var;`
- See that boris exits and throws an error ([full error message here](https://gist.github.com/MKorostoff/1bddcd6536fbc6c5d7e5))
![boris](https://cloud.githubusercontent.com/assets/1197335/7007200/92e8ab20-dc55-11e4-9d08-ee631c7a9e27.png)

### Reference
https://github.com/borisrepl/boris/issues/17

### Steps to resolve
- add support for php readline in php55 (i.e. `brew install php55-readline`)
- add php55-readline as a dependency for the boris formula

### Temporary work-around
Downgrade to php54 for command line only

**Comment by MKorostoff** [comment]
Update!  Actually, I found a slightly better work around than downgrading to 5.4.  I installed 5.5 [from here](http://php-osx.liip.ch/), then changed the following config files:

### ~/.bash_profile
Added:
```
export PATH=/usr/local/php5/bin:$PATH
export DRUSH_PHP=/usr/local/php5/bin/php
```
Drush PHP is a Drupal specific tool.  Anyone out there reading this, if you're not using Drupal, don'w worry about it.

### httpd.conf
Removed:
```
LoadModule php5_module    /usr/local/opt/php55/libexec/apache2/libphp5.so
```

Added:
```
LoadModule php5_module    /usr/local/php5-5.5.22-20150219-213913/libphp5.so
```

This is all, admittedly, a touch on the silly side because now I'm running a version of boris installed with brew, which depends on a version of php _not_ installed with brew.  But hey, whatever works :)

**Comment by alanthing** [comment]
Making sure I have my head wrapped around this- are you saying that having a Homebrew-installed version of readline used in the main php55 and php56 formulas would fix your issue with Boris?

**Comment by MKorostoff** [comment]
@alanthing Let me clarify as best I can, but I must admit I'm not terribly confident of this diagnosis.  I installed both Boris and PHP55 through homebrew.  I think Boris is failing because it requires php readline.  I think php readline is not present in the version of php55 available through homebrew.  Once I switch my php version to [the one available here](http://php-osx.liip.ch/) Boris begins working.

**Comment by cmckni3** [comment]
I tweaked the homebrew formula and installed php55 on my machine with readline support enabled (see my [commit](https://github.com/cmckni3/homebrew-php/commit/6008213e750ac98d06ea23c59acf2286f2423835)). This didn't fix the segfault for me.

I have the `pcntl`, `posix`, and `readline` php modules available and enabled.

**Comment by ablyler** [comment]
I've added readline support to the php install.
