### ISSUE TITLE
php53-http and php54-http will not compile

### ISSUE THREAD

**Issue by FunTimeCoding** [Homebrew/homebrew-php#1652]
brew gist-logs output: https://gist.github.com/f6febcaa1db984f59932

I googled the compiler error `error: use of undeclared identifier 'ptrdiff_t'` without success. I dug through stackexchange, sorted by time and all, linked and unlinked various other php things. I looked up the dependency tree of php54-http to see if I might have some of them linked wrong or compiled with the wrong compiler, but it doesn't make sense.

Any suggestions?

**Comment by FunTimeCoding** [comment]
php56-http compiles fine

**Comment by FunTimeCoding** [comment]
I suspect it could have to do with the fixes in pecl_http 2.3.1 https://pecl.php.net/package-changelog.php?package=pecl_http

**Comment by FunTimeCoding** [comment]
I was able to install a newer pecl_http by hand using the following commands:

```sh
mkdir -p /tmp/pear/temp
mkdir -p /tmp/pear/cache
mkdir -p /tmp/pear/download
pear config-set temp_dir /tmp/pear/temp
pear config-set cache_dir /tmp/pear/cache
pear config-set download_dir /tmp/pear/download
pear channel-update pear.php.net
pecl channel-update pecl.php.net
pear upgrade-all
pecl upgrade-all
pecl install pecl_http
```

I said yes to everything and entered the required paths using the output of

```sh
brew --prefix zlib
brew --prefix curl
brew --prefix libevent
```

And I modified, took the first three lines from from `php.ini` and moved them to `ext-http.ini`.

```sh
vim /usr/local/etc/php/5.3/php.ini
vim /usr/local/etc/php/5.3/conf.d/ext-http.ini
```

**Comment by alanthing** [comment]
Could you try this again? The commands below ensure you're using the Xcode Command Line Tools and not the full Xcode compilers. Random errors seem to be solved by doing this...

```
xcode-select --install
sudo xcode-select --switch /Library/Developer/CommandLineTools
```

**Comment by FunTimeCoding** [comment]
I tried that now. It still won't compile, but the result looks different.

https://gist.github.com/anonymous/95c2530e9e1540b37e54

**Comment by alanthing** [comment]
Those errors look like you have files in `$(brew --prefix)/etc/php/5.4/conf.d` that being with `ext-xxxx.ini` referencing extensions you no longer have installed in `/usr/local/opt`. Try deleting the ones that aren't valid anymore, like APC and such, and try again.

**Comment by FunTimeCoding** [comment]
I'm not going to investigate this further. I thought I had them all removed before trying this. Now I got a working php53 setup with http compiled manually.
