### ISSUE TITLE
ext-xdebug.ini file not created when installing

### ISSUE THREAD

**Issue by pjfsilva** [Homebrew/homebrew-php#1654]
I just installed on my new Yosemite powerd Mac PHP55 from homebrew and now I'm trying to install xdebug. The problem is that the ext-xdebug.ini doesn't seem to be created.

I tried for example this reinstall command but the ext-xdebug.ini isn't created and no error is thrown. Any idea how to debug this?

```
pjfsilva-mac:5.5 pjfsilva$ sudo brew reinstall php55-xdebug
==> Reinstalling php55-xdebug
==> Downloading https://homebrew.bintray.com/bottles-php/php55-xdebug-2.3.2.yose
Already downloaded: /Library/Caches/Homebrew/php55-xdebug-2.3.2.yosemite.bottle.tar.gz
==> Pouring php55-xdebug-2.3.2.yosemite.bottle.tar.gz
==> Caveats
To finish installing xdebug for PHP 5.5:
  * /usr/local/etc/php/5.5/conf.d/ext-xdebug.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the xdebug module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the xdebug module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php55-xdebug/2.3.2: 5 files, 264K
```

**Comment by alanthing** [comment]
Uninstall it, then, do you have the `conf.d` folder?

**Comment by pjfsilva** [comment]
uninstalled it and I don't have the conf.d folder.
Installed again and still no conf.d folder.
I tried manually creating the conf.d folder and installing again, still no ext-xdebug.ini was created...

Any way to debug this and maybe see the error that is causing this?!?

**Comment by jfmercer** [comment]
This is the default behavior for the time being. The file should be in ````/usr/local/etc/php/5.5/conf.d/````. Here's a work-around. 
````
touch /usr/local/etc/php/5.5/conf.d/ext-xdebug.ini
````
Then, write this to your new ````ext-xdebug.ini```` file: 
````
[xdebug]
zend_extension="/usr/local/opt/php55-xdebug/xdebug.so"
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000
xdebug.max_nesting_level = 200
````

**Comment by alanthing** [comment]
After looking through the code in the Abstract folder for PHP extensions and the major PHP versions, the conf.d is created by the php5x formulas and not extensions. Therefore, if you don't have the conf.d folder and don't want to re-install PHP, simply create the folder, but do not create an empty ext-x.ini file. That filepath needs to not exist for the formula to properly create the ini file as expected.

**Comment by eliorivero** [comment]
Had the same issue when running php from command line. Specifically, when doing tab completion (using [wp-completion.bash](http://wp-cli.org/#complete)) with [wp-cli](http://wp-cli.org/) I got:

`Failed loading /usr/local/Cellar/php55/5.5.23/lib/php/extensions/no-debug-non-zts-20121212/xdebug.so:  dlopen(/usr/local/Cellar/php55/5.5.23/lib/php/extensions/no-debug-non-zts-20121212/xdebug.so, 9): image not found
`

I followed the steps from @jfmercer above, so thanks John for posting that, and also edited `/usr/local/etc/php/5.5/php.ini` to comment the line

`
zend_extension = "xdebug.so"
`

to

`
;zend_extension = "xdebug.so"
`

so it wouldn't load from here but from `/usr/local/etc/php/5.5/conf.d`. This solved everything.

**Comment by harmenjanssen** [comment]
For the record: I _did_ have the `conf.d` folder, containing a couple other extensions, but `ext-xdebug.ini` wasn't created for me either.

Creating it manually as suggested above worked for me.

**Comment by webhacking** [comment]
same problem . .

**Comment by x3ro** [comment]
Ran into this as well. Directory exists but ini file is not being created (in this case for `php56-apcu`). Has this issue come up elsewhere @alanthing?
