### ISSUE TITLE
php56 problems with OS X 10.10.3

### ISSUE THREAD

**Issue by SatoruTakahashi** [Homebrew/homebrew-php#1660]
Hi , I have trouble with installing php56 on Mac OSX 10.10.3

This is the command line I tried.

> $ brew install php56 --with-pgsql

> 1 error generated.
> make: *** [ext/intl/intl_convertcpp.lo] Error 1
> make: *** Waiting for unfinished jobs....

Without  the option "--with-pgsql" , installing process complete without any problem.

**Comment by opengeek** [comment]
I am having the exact same issue with different options on a clean OS X 10.10.3 installation...

`brew install php56 --without-apache --with-imap --with-gmp`

**Comment by opengeek** [comment]
in my case, leaving off `--without-apache` forced download of a yosemite specific package that was not previously downloaded and installed immediately... ??

**Comment by rescats** [comment]
same issue here on a brand new install.  clean osx 10.10.3

**Comment by green2k** [comment]
The same problem here, but with "brew install php55 --with-postgresql"

**Comment by pseux** [comment]
Also getting this error when installing on osx 10.10.3 using:
`brew install php55 --without-apache`

    1 error generated.
    make: *** [ext/intl/intl_convertcpp.lo] Error 1
    make: *** Waiting for unfinished jobs....

**Comment by alexblunck** [comment]
I had the same issue on a fresh 10.10.3 install.

I'm not sure why, but installing Xcode fixed it for me. 

This is the command I ran:
`brew install php56 --with-imap --with-homebrew-openssl --with-mssql --without-snmp`

**Comment by green2k** [comment]
For me, only manual compilation of pgsql extension helped.

**Comment by OKNoah** [comment]
Same issue with php54

**Comment by Jastrzebowski** [comment]
Same for me
```
brew install php56 --with-imap, --with-postgresql, --without-apache
```

> installing Xcode fixed it for me.

Which is kind of sad to have to install 2.5 GB otherwise unused software :(

**Comment by OKNoah** [comment]
I did `brew update` and problems went away :)

**Comment by SatoruTakahashi** [comment]
I also did ~~brew update~~ and the problems was resolved :)

**Comment by SatoruTakahashi** [comment]
I also did `brew udpate` and the problem was resolved anyway.
thx everyone :)
