### ISSUE TITLE
php55-pcntl - Symbol not found: _zend_sigaction

### ISSUE THREAD

**Issue by alexandre-butynski** [Homebrew/homebrew-php#1661]
This issue appeared since my update to Yosemite. When I try to launch something using php55-pcntl (e.g. `behat` or `php artisan tinker`), I obtain this error message :

```
dyld: lazy symbol binding failed: Symbol not found: _zend_sigaction
  Referenced from: /usr/local/opt/php55-pcntl/pcntl.so
  Expected in: flat namespace

dyld: Symbol not found: _zend_sigaction
  Referenced from: /usr/local/opt/php55-pcntl/pcntl.so
  Expected in: flat namespace

Trace/BPT trap: 5
```

I tried to update Homebrew, remove and reinstall all packages but the problem remains the same. 

Anybody experimenting something similar ?

**Comment by alanthing** [comment]
Upgrading between major OS versions is bound to create some issues with Homebrew-built packages from the old OS, including linked libraries, static libraries, etc. I understand you uninstalled and reinstalled PHP packages, but there may be some other underlying dependencies that PHP and/or pcntl reference that are using old binaries from Mavericks.

You might want to try uninstalling **all** brew packages and reinstalling on Yosemite:

```
for pkg in `brew list`; do echo "++ $pkg"; brew unlink $pkg ; brew uninstall --force $pkg && brew install --verbose $pkg; done
```

That's a rather destructive and potentially-unsafe command, but use it as a template to get started.

**Comment by future5985** [comment]
My issue:https://github.com/Homebrew/homebrew-php/issues/2255
Help.

**Comment by yukhoichan** [comment]
I also encounted this problem when using Composer to install packages. 
I solved it by disabling pcntl.so in php.ini and restarting Apache.

Steps:
1. Run `$ php -i | grep php.ini` to check the configuration file used by php-cli
2. Edit the configuration file, and comment the line "extension=pcntl.so"
3. Save and restart Apache

This solution is not appropriate if your works really depend on pcntl

**Comment by hakirra** [comment]
@yukhoichan Thanks for you. this approach very nice .

**Comment by hakirra** [comment]
@alexandre-butynski   Edit the php.ini file, and comment extension=pcntl.so

**Comment by javian** [comment]
@yukhoichan this bug was reported over a year ago - are you saying it still appears with the recent updates ?
