### ISSUE TITLE
not have php52 ?

### ISSUE THREAD

**Issue by mejinke** [Homebrew/homebrew-php#1663]
Some programs only support php5.2. how install php5.2 by brew?

**Comment by josegonzalez** [comment]
@mejinke While we do not support PHP 5.2 anymore (it's even been unsupported by the PHP team since 2011) you can probably install it from source using:

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-php/b1816d241414d3d53f4a7cc773ff9ee5a60d7211/Formula/php52.rb
```

**Comment by mejinke** [comment]
@josegonzalez brew install https://raw.githubusercontent.com/Homebrew/homebrew-php/b1816d241414d3d53f4a7cc773ff9ee5a60d7211/Formula/php52.rb
error:
`
......
patching file sapi/cgi/fpm/fpm_unix.h
patching file sapi/cgi/fpm/fpm_worker_pool.c
patching file sapi/cgi/fpm/fpm_worker_pool.h
patching file sapi/cgi/fpm/init.d/php-fpm.in
patching file sapi/cgi/fpm/xml_config.c
patching file sapi/cgi/fpm/xml_config.h
patching file sapi/cgi/fpm/zlog.c
patching file sapi/cgi/fpm/zlog.h
Error: no implicit conversion of Float into String
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:330:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:330:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:330:in `+'
/usr/local/Library/Homebrew/install_renamed.rb:19:in `+'
/usr/local/Library/Taps/josegonzalez/homebrew-php/Abstract/abstract-php.rb:72:in `config_path'
/usr/local/Library/Taps/josegonzalez/homebrew-php/Abstract/abstract-php.rb:98:in `install'
/usr/local/Library/Formula/php52.rb:30:in `install'
/usr/local/Library/Homebrew/build.rb:136:in `block in install'
/usr/local/Library/Homebrew/formula.rb:410:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:777:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:775:in `stage'
/usr/local/Library/Homebrew/formula.rb:406:in `brew'
/usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:186:in `<main>'
`
OS X 10.10
