### ISSUE TITLE
Unable to access https URLs with PHP curl

### ISSUE THREAD

**Issue by jwriteclub** [Homebrew/homebrew-php#1676]
After the upgrade to 10.10, I've had persistent problems with curl within PHP not being able to load HTTPS URLS with the curl error message "Curl Error: Protocol "https" not supported or disabled in libcurl". I've rebuilt php56 from the standard homebrew recipe both with and without the homebrew versions of curl and openssl.

This issue persists whether a sample script is run via the CLI or Apache. I've tried the advice #1396 of running `brew link -f openssl` as well as the complex complete uninstall and reinstall of all of the php dependencies as suggested in the common errors section.

The command line CURL (installed via homebrew) has no problem accessing HTTPS URLS:

```
curl -sD - https://api.github.com/rate_limit
HTTP/1.1 200 OK
Server: GitHub.com
Date: Sat, 25 Apr 2015 01:37:23 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 283
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
X-RateLimit-Reset: 1429927767
Cache-Control: no-cache
X-GitHub-Media-Type: github.v3
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: 46B84C9D:54CA:9E2BA46:553AEFD2
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
X-Served-By: a6882e5cd2513376cb9481dbcd83f3a2

{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 59,
      "reset": 1429927767
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1429925903
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 59,
    "reset": 1429927767
  }
}
```

PHPInfo reports the following for CURL

Parameter | Value
------------------ | ------------------
cURL support | enabled
cURL Information | 7.42.0
Age | 3
**Features** | **Value**
AsynchDNS | No
CharConv | No
Debug | No
GSS-Negotiate | No
IDN | No
IPv6 | Yes
krb4 | No
Largefile | Yes
libz | Yes
NTLM | Yes
NTLMWB | Yes
SPNEGO | No
SSL | Yes
SSPI | No
TLS-SRP | Yes
Protocols | dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host | x86_64-apple-darwin14.3.0
SSL Version | OpenSSL/1.0.2a
ZLib Version | 1.2.5

In addition, `curl_version()` reports:

```
array(
    ['version_number'] => 469504
    ['age'] => 3
    ['features'] => 573981
    ['ssl_version_number'] => 0
    ['version'] => 7.42.0
    ['host'] => 'x86_64-apple-darwin14.3.0'
    ['ssl_version'] => 'OpenSSL/1.0.2a'
    ['libz_version'] => 1.2.5
    ['protocols'] => array(
        [0] => 'dict'
        [1] => 'file'
        [2] => 'ftp'
        [3] => 'ftps'
        [4] => 'gopher'
        [5] => 'http'
        [6] => 'https'
        [7] => 'imap'
        [8] => 'imaps'
        [9] => 'ldap'
        [10] => 'ldaps'
        [11] => 'pop3'
        [12] => 'pop3s'
        [13] => 'rtsp'
        [14] => 'smb'
        [15] => 'smbs'
        [16] => 'smtp'
        [17] => 'smtps'
        [18] => 'telnet'
        [19] => 'tftp'
    )
)
```

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.3
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | homebrew stable
**Xcode Version:** | Lastest CLT
**Output of gcc -v:** | Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
**Output of php -v:** | PHP 5.6.7 (cli) (built: Apr 24 2015 18:01:23)  / PHP Version 5.6.7
**Output of brew install -v --with-homebrew-curl --with-homebrew-openssl php56 within a gist** | https://gist.github.com/jwriteclub/b621429a97565ea217f0
**Output of brew doctor within a gist** | https://gist.github.com/jwriteclub/52fc219b3b4d58b4e409

**Comment by alanthing** [comment]
We're including homebrew OpenSSL by default now, so I don't think that's the issue. What happens if you don't include `--with-homebrew-curl`? Also, I'm not terribly familiar with the differences in OS X vs Homebrew curl in PHP; is it a big difference? If so, we can consider also making `--with-homebrew-curl` the default like we've done with OpenSSL.

**Comment by jwriteclub** [comment]
I've tried it without homebrew curl. In that case I get a linking error about the wrong version of dylibs being present (cURL 7.4.0 vs 8.0.0).

I'm not entirely sure what sequence of events triggers this bug, but we've got an office full of macs which all have their own homebrew installs and are all having the exact same problem. This is killing productivity and I'm happy to put a bounty on getting it fixed.

**Comment by skler** [comment]
I have the same problem with PHP 5.5.25; it's compiled with default parameters. 
```
$ php -v
PHP 5.5.25 (cli) (built: May 22 2015 15:48:30)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by ablyler** [comment]
@jwriteclub / @skler: are you still having the issue?  if so, can you provide an example PHP script?

**Comment by jwriteclub** [comment]
Here's a gist with a working example https://gist.github.com/jwriteclub/494fdbf74b7234b564d1

I've also identified the problem: at some point the build started enforcing the distinction between CURLPROTO_HTTPS and CURLPROTO_HTTP. Historically in homebrew-php builds, and in current HHVM and php-fpm56 builds, this distinction is not enforced, allowing SSL connections even if the CURLOPT_PROTOCOLS option is set to CURLPROTO_HTTP only. 

I'm submitting a pull request to our REST library to fix this issue today. I am inclined to close this ticket without making a change to homebrew-php. This behavior is clearly the expected behavior in terms of how CURLOPT_PROTOCOLS should work, and even though some other builds may be broken, this ticket (and possibly a note in the wiki) should provide sufficient help to others who may encounter this problem.
