### ISSUE TITLE
php53 install-cli failed, php54 and php56 with same install options installed fine

### ISSUE THREAD

**Issue by apit** [Homebrew/homebrew-php#1679]
```
brew install php53 --with-fpm --without-apache

==> ./configure --prefix=/opt/homebrew/Cellar/php53/5.3.29 --localstatedir=/opt/homebrew/var --sysconfdir=/opt/homebrew/etc/php/5.3 --with-config-file-path=/opt/homebrew/etc/php/5.3
==> make
==> make install
make install

Installing PHP CLI binary:        /opt/homebrew/Cellar/php53/5.3.29/bin/
cp: /opt/homebrew/Cellar/php53/5.3.29/bin/#INST@98462#: No such file or directory
make: *** [install-cli] Error 1
couldn't understand kern.osversion `14.3.0
```

This is my `brew config` output:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 606127a8f43b67a4a695a5c4d3739a44b7a577d8
Last commit: 7 hours ago
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.10.3-x86_64
Xcode: N/A
CLT: 6.2.0.0.1.1424975374
couldn't understand kern.osversion `14.3.0'
GCC-4.2: build 5666
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/stupoh/Library/Enthought/Canopy_64bit/System/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_67```

**Comment by alanthing** [comment]
Try installing without the `--with-fpm --without-apache` options. The updated formulas build both PHP-FPM and mod_php, but you can safely ignore the one you won't use and it'll take up a very minimal amount of extra space.

If you continue to have trouble, please post full logs here for additional assistance:

```
brew gist-logs php53
```

**Comment by lancegliser** [comment]
Still seeing very similar issues here. Full gist here: https://gist.github.com/anonymous/b34e046a688f8eb5c328

Lances-MacBook-Pro:vhosts-conf lgliser$ brew reinstall --without-apache php53
==> Reinstalling php53 with --without-apache
==> Downloading https://www.php.net/get/php-5.3.29.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php53-5.3.29
==> Downloading https://gist.githubusercontent.com/alanthing/9b786af22698eda39497/raw/0fcbbff7fe4b05ed7c011730cc8
Already downloaded: /Library/Caches/Homebrew/php53--patch-9d70a202321cd91acb31037dd0c5dcd5dc8fe32f325b8a291388f07e0bbdc533.patch
==> Patching
patching file Makefile.global
patching file Zend/acinclude.m4
patching file Zend/zend_language_parser.y
patching file acinclude.m4
patching file aclocal.m4
patching file configure
patching file configure.in
patching file generated_lists
patching file main/php_config.h.in
patching file sapi/cgi/Makefile.frag
patching file sapi/cgi/config9.m4
patching file sapi/cli/Makefile.frag
patching file sapi/cli/config.m4
patching file sapi/fpm/Makefile.frag
patching file sapi/fpm/config.m4
patching file sapi/litespeed/Makefile.frag
patching file sapi/litespeed/config.m4
patching file sapi/milter/Makefile.frag
patching file sapi/milter/config.m4
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php53/5.3.29 --localstatedir=/usr/local/var --sysconfdir=/usr/local/et
==> make
==> make install
make install

Installing PHP CLI binary:        /usr/local/Cellar/php53/5.3.29/bin/
cp: /usr/local/Cellar/php53/5.3.29/bin/#INST@69251#: No such file or directory
make: *** [install-cli] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues
