### ISSUE TITLE
brew in Yosemite, 10.10.3 (14D136), just cannot find php formula 

### ISSUE THREAD

**Issue by oliverwreath** [Homebrew/homebrew-php#1680]
$ brew install php56
Error: No available formula for php56 
Searching formulae...
Searching taps...
homebrew/php/php56-amqp			homebrew/php/php56-proctitle
....
....

<problem description>

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.3 (14D136)
**Homebrew Version:** | Homebrew 0.9.5
**Xcode Version:** | Version 6.3.1 (6D1002)
**Output of gcc -v:** | Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
**Output of php -v:** | PHP 5.5.20 (cli) (built: Feb 25 2015 23:30:53)  Zend Engine v2.5.0, 

$ php -v
PHP 5.5.20 (cli) (built: Feb 25 2015 23:30:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

$ XCode version 
Version 6.3.1 (6D1002)

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by alanthing** [comment]
Try running `brew tap --repair` and repeating.

**Comment by oliverwreath** [comment]
Problem solved by >>>>
```javascript
brew install homebrew/php/php56
php -v
```

it just nested in the php folder nowadays, probably due to the growth of homebrew php. 
turns out this works well XD 

maybe it could be solved by tapping too :)
