### ISSUE TITLE
Php53 failed to build on 10.9.5

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-php#1694]
_From @Etroid on April 29, 2015 16:23_

System: MAC OS X 10.9.5
Homebrew: 0.9.5
XCode: 6.2

Getting an error when executing "brew install php53 --without-apache --with-fpm --with-intl --with-xdebug"

Installing PHP CLI binary:        /usr/local/Cellar/php53/5.3.29/bin/
cp: /usr/local/Cellar/php53/5.3.29/bin/#INST@42658#: No such file or directory
make: *** [install-cli] Error 1

More information can be found here:
<a href="https://gist.github.com/3550beca6fefdcfd7b19">https://gist.github.com/3550beca6fefdcfd7b19</a>

_Copied from original issue: Homebrew/homebrew#39188_

**Comment by alanthing** [comment]
@Etroid Please post full logs here for additional assistance:

```
brew gist-logs php53
```

**Comment by tom--** [comment]
I am experiencing a similar error on 10.10.3 https://gist.github.com/07e69aad391069d599ff

Is there a resolution or was this closed owing to no response from OP? It looks like the gist-logs is linked in the OP's message.

    $ brew install php53 --without-apache --without-ldap --without-pear
    ==> Installing php53 from homebrew/homebrew-php
    ==> Downloading https://www.php.net/get/php-5.3.29.tar.bz2/from/this/mirror
    Already downloaded: /Library/Caches/Homebrew/php53-5.3.29
    ==> Downloading https://gist.githubusercontent.com/alanthing/9b786af22698eda39497/raw/0fcbbff7fe4b05ed7c011730cc80e50bd9123dec/m
    Already downloaded: /Library/Caches/Homebrew/php53--patch-9d70a202321cd91acb31037dd0c5dcd5dc8fe32f325b8a291388f07e0bbdc533.patch
    ==> Patching
    patching file Makefile.global
    patching file Zend/acinclude.m4
    patching file Zend/zend_language_parser.y
    patching file acinclude.m4
    patching file aclocal.m4
    patching file configure
    patching file configure.in
    patching file generated_lists
    patching file main/php_config.h.in
    patching file sapi/cgi/Makefile.frag
    patching file sapi/cgi/config9.m4
    patching file sapi/cli/Makefile.frag
    patching file sapi/cli/config.m4
    patching file sapi/fpm/Makefile.frag
    patching file sapi/fpm/config.m4
    patching file sapi/litespeed/Makefile.frag
    patching file sapi/litespeed/config.m4
    patching file sapi/milter/Makefile.frag
    patching file sapi/milter/config.m4
    ==> ./configure --prefix=/usr/local/Cellar/php53/5.3.29 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.3 --wit
    ==> make
    ==> make install
    make install

    Installing PHP CLI binary:        /usr/local/Cellar/php53/5.3.29/bin/
    cp: /usr/local/Cellar/php53/5.3.29/bin/#INST@69481#: No such file or directory
    make: *** [install-cli] Error 1

    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/homebrew/homebrew-php/issues

**Comment by Etroid** [comment]
Would like to reopen this issue since it was never resolved. Also, like the previous commenter mentioned I had added all the necessary logs in the original issue.

**Comment by tom--** [comment]
I do not know if anyone who might do something with this bug is notified when we comment on it. Do we need to open a new bug? This one is already (confusingly) repeated in  #39188

**Comment by patrickmaciel** [comment]
I have the same problem:

    ==> ./configure --prefix=/usr/local/Cellar/php53/5.3.29 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.3 --with-config-file-path=/usr/local/etc/php/5.3 --with-co
    ==> make
    ==> make install
    make install

    Installing PHP CLI binary:        /usr/local/Cellar/php53/5.3.29/bin/
    cp: /usr/local/Cellar/php53/5.3.29/bin/#INST@40889#: No such file or directory
    make: *** [install-cli] Error 1

    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/homebrew/homebrew-php/issues

**Comment by mikemcquaid** [comment]
Please post full logs rather than just `READ THIS: https://git.io/brew-troubleshooting` which tells you to do that, thanks.

**Comment by tom--** [comment]
I posted full logs and so did @Etroid. If there is something else we could do in addition, please let me know.

**Comment by DomBlack** [comment]
I am getting the same error, however I'm on:

System: MAC OS X 10.10.4
Homebrew: 0.9.5
XCode: 6.4

See the brew gist: https://gist.github.com/anonymous/b44f5f8a7916a3a6f3f3

**Comment by ablyler** [comment]
I'm able to re-produce this.  Looking into it now.

**Comment by ablyler** [comment]
This has been fixed, thanks for the reports!
