### ISSUE TITLE
Installing php56 (php-5.6.8) on Travis CI fails / takes too long to make

### ISSUE THREAD

**Issue by Glavin001** [Homebrew/homebrew-php#1695]
After homebrew-php updated from php-5.6.7 to php-5.6.8 (possibly #1664), my builds on Travis CI all fail when installing `php56`. 

> No output has been received in the last ... minutes, this potentially indicates a stalled build or something wrong with the build itself.

See https://travis-ci.org/Glavin001/atom-beautify#L1610

**Comment by alanthing** [comment]
We cannot support builds in TravisCI environments. That said, you could try:

* add a timeout command in front of the installation steps, then:
* post the output of `brew gist-logs php56` here

We'll see if we can help but TravisCI is not our target; OS X workstations are.

**Comment by Glavin001** [comment]
Testing now they pass installing of `php56` with `brew install php56`: https://travis-ci.org/Glavin001/atom-beautify/builds/61045399

I'm going to close this as it looks like it has been resolved somewhere, without change on my part.
Thanks.
