### ISSUE TITLE
** README - update icu4c (and possibly others) if you update PHP

### ISSUE THREAD

**Issue by alanthing** [Homebrew/homebrew-php#1701]
**EDIT:** This is resolved. The `intl` extension has been removed from the main `php5x` formulas and moved into `php5x-intl`. If you are experiencing this problem (replace `php56` with `php55`, `php54`, etc as needed)...

* Uninstall your existing Homebrew PHP version if it is the latest release from [php.net](http://php.net)

   `brew uninstall --force php56`
* Update your formulas: 

   `brew update`
* Fix any tap link errors: 

   `brew tap --repair`
* Purge any previous bottle downloads: 

   `find $(brew --cache) -mindepth 1 -print -delete`
* Install your `php5x` version (remember, both `--with-apache` and `--with-fpm` are included by default and do not conflict, so you don't need to include or exclude either of those options, and you'll get the binary bottle, saving a *lot* of compile time)

   `brew install -v php56`
* **Optional: If you need the `intl` extension**: 

   `brew install php56-intl`

Leave a comment in this issue if you need assistance, or create a new issue.

---

**Original issue:**

The binary bottles for the latest versions of php54, php55, and php56 were built with the newest versions of dependencies. On my system, I had to `brew update && brew upgrade icu4c` to resolve an issue with a dynamic link for `/usr/local/opt/icu4c/lib/libicui18n.55.dylib` when I only upgraded `php56`. Depending on how others' systems are configured, you may need to upgrade additional components as well. While it may take a while, a `brew update && brew upgrade` of all system components might be the easiest way to resolve.

I'll leave this issue open for a few weeks to allow folks to find it before opening new issues. Please add your comments if you come across other related issues, or if it's not related, create a new issue.

**Comment by RandomDSdevel** [comment]
Could [this](https://github.com/Homebrew/homebrew/issues/39221) be related?

**Comment by josegonzalez** [comment]
Can we require a specific version of a formula?

**Comment by alanthing** [comment]
@RandomDSdevel I think so. If you update icu4c you should be alright.

**Comment by alanthing** [comment]
@josegonzalez I've not come across any version requirements like Debs and RPMs that stuck with me, but I could be wrong. Homebrew's approach is "run the latest all the time" which makes situations like this a bummer. Hopefully, there's a little expectation of "bleeding edge" if you're upgrading some packages, and it shouldn't be too bad to just upgrade a few more.

**Comment by DomT4** [comment]
> Homebrew's approach is "run the latest all the time" which makes situations like this a bummer. 

You can always whack a specific version in Homebrew/versions if it's useful.

**Comment by jacknagel** [comment]
Can we not revision bump the php formulae, just like we do for dependents in core?

**Comment by angge-deborja** [comment]
I ran `brew update && brew upgrade` and ended up with version 55.1 for icu4c. Now, I can't execute any php commands.
```sh
$ php -v
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Trace/BPT trap: 5
```

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.9.5
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | homebrew-php stable
**Xcode Version:** | 5.0
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
 | Apple LLVM version 5.0 (clang-500.2.75) (based on LLVM 3.3svn)
 | Target: x86_64-apple-darwin13.4.0
 | Thread model: posix
**Output of php -v:** | dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
 |  Referenced from: /usr/local/bin/php
 |  Reason: image not found
 | Trace/BPT trap: 5

**Comment by DomT4** [comment]
^ ` brew reinstall php `.

**Comment by FunTimeCoding** [comment]
I tried reinstalling php53 and it keeps wanting the old icu4c version which is missing, it works however with 54+.

**Comment by DomT4** [comment]
If there's a silent ` icu4c ` link from `php53` then `php53` needs to be bumped as well. 54+ was bumped, 53 wasn't.

**Comment by angge-deborja** [comment]
@DomT4 I tried reinstalling php53 and still, it keeps referring to version 54.1 of icu4c.

**Comment by DomT4** [comment]
Given `php53` hasn't been rebottled yet, you'll need to build it from source to fix the problem. ` brew reinstall php53 -fs`.

**Comment by angge-deborja** [comment]
@DomT4 Thank you! php53 works fine now. :bow:

**Comment by sebastianhegge** [comment]
worked for me, too, thx!

**Comment by alanthing** [comment]
Long-term, we should look into the dependency on icu4c because the current situation means that we need to rebuild our binary bottles whenever icu4c updates. That's untenable to keep up with.

Short-term, we can use the brew bot to build new bottles- but I might not be able to get to it for a few days.

In the meantime, follow @DomT4's instructions and rebuild from source with the `-fs` options.

**Comment by bipinu** [comment]
I had to ``` --build-from-source ``` for php56 to fix tidy alert. ```-fs``` didn't help.
Not sure if it's because I use thread safe PHP.

**Comment by alanthing** [comment]
I removed the old bottle definitions to hold us over until new bottles are built. I should have that done this week.

**Comment by alanthing** [comment]
Ok- I'll soon have a solution, pending tests. Because the `intl` extension relies on an external dependency, I'm removing it from the default `php5x` install into `php5x-intl` formulas. And further, because it depends on a library file with a hard version, `libicui18n.55.dylib` instead of `libicui18n.dylib`, I'm using `#{Formula['icu4c'].prefix}` instead of `#{Formula['icu4c'].opt_prefix}` so updates to icu4c don't break an un-updated `php5x-intl`. This should satisfy current and future problems regarding upgrades and this versioned library.

The intl extension will now be similar to mcrypt in that it's shipped with PHP's source code but not included by default in Homebrew-php because of hard external requirements.

Since we're investing in binary bottles now, we may want to consider moving more of the built-in extensions to separate formulas, but we can evaluate those as needed.

**Comment by alanthing** [comment]
We should be out of the woods here now. New bottles are built for major `php5x` versions without the `intl` extension, and thus no longer relying on the version-specific library for `icu4c`. If you've made it this far, scroll up to the top as I will edit my original comment leave updating instructions up there.

**Comment by deizel** [comment]
Thanks for these instructions - they solved the issue I was having after upgrading PHP.

For what it's worth, `rm -rf $(brew --cache)/*` will delete every file you have permission to on your entire hard drive and all attached volumes if you misspell `brew --cache` (or it somehow returns a null value).

May I suggest something like `find $(brew --cache) -mindepth 1 -delete` instead? :wink:

**Comment by alanthing** [comment]
@deizel whoa, yes, I'm sorry I didn't consider that. I think I lifted `rm -rf $(brew --cache)` from the Homebrew FAQ docs and didn't think about the ramifications if it didn't work. Thanks for the suggested alternative; I edited by comment above. I'm also glad you caught your typo before it got too far along!

**Comment by deizel** [comment]
@alanthing Almost forgot to reply to this, but thanks for the quick response and remedy. :+1: 

Interestingly, I've since found another project where something similar happened in the past.

However, since the script ran non-interactively, the affected user wasn't so lucky..

https://news.ycombinator.com/item?id=8896186

**Comment by nandastone** [comment]
@alanthing thanks mate, 5.6 back in action!

**Comment by josegonzalez** [comment]
@alanthing looks like this issue is cropping up again (at least for me). The bottles are built against `libicui18n.55`, though I have `libicui18n.56` locally. Is there a way I can bump the build? I'm going to rebuild from source for now, but want to be sure this isn't an issue for our users if possible.

**Comment by DomT4** [comment]
File a PR to increase the formula revision of `php**-intl` and then merge it with new bottles. Will resolve the problem.
