### ISSUE TITLE
Failed to upgrade php55 5.5.24 on 10.10.3 - No available formula for tidy

### ISSUE THREAD

**Issue by jgacas** [Homebrew/homebrew-php#1709]
Formula tidy was removed from homebrew dupes, http://braumeister.org/repos/Homebrew/homebrew-dupes/formula/tidy, and it seems that php55 has an dependency on that formula, which causes upgrade to fail with message:
Error: No available formula for tidy

**Comment by jgacas** [comment]
php stopped working after upgrade failed:

$php -v
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Trace/BPT trap: 5

**Comment by alanthing** [comment]
See #1701
