### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib

### ISSUE THREAD

**Issue by kwcms** [Homebrew/homebrew-php#1710]
brew install php56
php -v 
===================
kang@local /u/l/C/i/55.1> php -v                                                                                                            master
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
[3]    77807 trace trap  php -v

==================

drwxr-xr-x  6 kang  admin   204B  4 30 03:59 icu
-r--r--r--  1 kang  admin    25M  5  5 16:00 libicudata.55.1.dylib
lrwxr-xr-x  1 kang  admin    21B  4 30 03:59 libicudata.55.dylib -> libicudata.55.1.dylib
-r--r--r--  1 kang  admin    25M  4 30 03:59 libicudata.a
lrwxr-xr-x  1 kang  admin    21B  4 30 03:59 libicudata.dylib -> libicudata.55.1.dylib
-r--r--r--  1 kang  admin   2.1M  5  5 16:00 libicui18n.55.1.dylib
lrwxr-xr-x  1 kang  admin    21B  4 30 03:59 libicui18n.55.dylib -> libicui18n.55.1.dylib
-r--r--r--  1 kang  admin   3.7M  4 30 03:59 libicui18n.a
lrwxr-xr-x  1 kang  admin    21B  4 30 03:59 libicui18n.dylib -> libicui18n.55.1.dylib
-r--r--r--  1 kang  admin    57K  5  5 16:00 libicuio.55.1.dylib
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicuio.55.dylib -> libicuio.55.1.dylib
-r--r--r--  1 kang  admin    64K  4 30 03:59 libicuio.a
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicuio.dylib -> libicuio.55.1.dylib
-r--r--r--  1 kang  admin   304K  5  5 16:00 libicule.55.1.dylib
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicule.55.dylib -> libicule.55.1.dylib
-r--r--r--  1 kang  admin   572K  4 30 03:59 libicule.a
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicule.dylib -> libicule.55.1.dylib
-r--r--r--  1 kang  admin    46K  5  5 16:00 libiculx.55.1.dylib
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libiculx.55.dylib -> libiculx.55.1.dylib
-r--r--r--  1 kang  admin    60K  4 30 03:59 libiculx.a
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libiculx.dylib -> libiculx.55.1.dylib
-r--r--r--  1 kang  admin    64K  5  5 16:00 libicutest.55.1.dylib
lrwxr-xr-x  1 kang  admin    21B  4 30 03:59 libicutest.55.dylib -> libicutest.55.1.dylib
-r--r--r--  1 kang  admin    79K  4 30 03:59 libicutest.a
lrwxr-xr-x  1 kang  admin    21B  4 30 03:59 libicutest.dylib -> libicutest.55.1.dylib
-r--r--r--  1 kang  admin   175K  5  5 16:00 libicutu.55.1.dylib
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicutu.55.dylib -> libicutu.55.1.dylib
-r--r--r--  1 kang  admin   244K  4 30 03:59 libicutu.a
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicutu.dylib -> libicutu.55.1.dylib
-r--r--r--  1 kang  admin   1.3M  5  5 16:00 libicuuc.55.1.dylib
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicuuc.55.dylib -> libicuuc.55.1.dylib
-r--r--r--  1 kang  admin   2.1M  4 30 03:59 libicuuc.a
lrwxr-xr-x  1 kang  admin    19B  4 30 03:59 libicuuc.dylib -> libicuuc.55.1.dylib
drwxr-xr-x  7 kang  admin   238B  5  5 16:00 pkgconfig

**Comment by DomT4** [comment]
`brew update && brew reinstall php56` should work.

**Comment by kwcms** [comment]
@DomT4 
the latest homebrew icu4c version is 55.1, php53 php54 php55 php56 need 54.1

**Comment by DomT4** [comment]
They don't need it. They're perfectly compatible with the newest `icu4c`. Homebrew-php pushed new bottles with the links to `icu4c 55.1` the other day, [here](https://github.com/Homebrew/homebrew-php/commit/ba202e651634523e2ed2db63b291fbe3cc235e9f). If your `brew` is up-to-date and you've reinstalled `phpxx` it should work just fine.

**Comment by alanthing** [comment]
Also follow #1701
