### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [Homebrew/homebrew-php#1714]
From what I understand MySQL is installed by default... but I can't seem to find anything about how to start and stop MySQL through Terminal. How can I gain access to it (incidentally, what's that command you can run after a MySQL installation that takes you through simple hardening steps?).

Thanks for any information. I'm a PC who's new to Homebrew and OSX.

Edit: Incidentally I'm trying to get PHPMyAdmin working (which I installed via brew install phpmyadmin) -- Error message: Connection for controluser as defined in your configuration failed.

**Comment by mologie** [comment]
The PHP *extension* named mysqlnd (which also provides mysql and mysqli compatibility layers) is installed by default when you install PHP through homebrew-php. The MySQL server itself is not installed. It is not preinstalled on OS X either.

If you wish to install MySQL on your system, run `brew install mysql` or `brew install mariadb`. The command `brew info mysql` incidentally answers all most of your questions in the Caveats section. To secure your installation, run `mysql_secure_installation` just like on Debian or other UNIX systems.

**Comment by JohnnyWalkerDesign** [comment]
Thank you! Works perfectly!
