### ISSUE TITLE
build swftools and zlib not found

### ISSUE THREAD

**Issue by sbellan61** [Homebrew/homebrew-php#1715]
I'm trying to install swftools on my Mac OS 10.10.2.

I've successfully installed zlib with 

brew tap homebrew/dupes
brew install zlib

and installed the other swftools dependencies (jpeglib, freetype). But when I do ./configure, I get

ERROR:
You need zlib to compile swftools

Yet, it seems the zlib install was successful:

brew list zlib
/usr/local/Cellar/zlib/1.2.8/include/ (2 files)
/usr/local/Cellar/zlib/1.2.8/lib/libz.1.2.8.dylib
/usr/local/Cellar/zlib/1.2.8/lib/pkgconfig/zlib.pc
/usr/local/Cellar/zlib/1.2.8/lib/ (3 other files)
/usr/local/Cellar/zlib/1.2.8/share/man/man3/zlib.3

So it seems like the swftools configuration just isn't finding zlib--but I have no idea how to help it. Help appreciated!

**Comment by alanthing** [comment]
This is not the correct project; please post to github.com/Homebrew
