### ISSUE TITLE
Add phc

### ISSUE THREAD

**Issue by NathanJang** [Homebrew/homebrew-php#1717]
I would like to add [phc](http://www.phpcompiler.org/), which is a compiler for PHP files. However, the [installation instructions](http://www.phpcompiler.org/doc/latest/install.html) are complicated and require multiple dependencies, so I don't know how to go about it. Maybe someone with more experience can try 😁

**Comment by alanthing** [comment]
Hm, the last release was in 2011, and the last commit was 2013. I'm not sure there is much value in spending the time to adapt it to Homebrew. We'll accept pull requests if someone else creates it, but I doubt that any of the maintainers will want to take this on.
