### ISSUE TITLE
Homebrew php broken and unable to reinstall

### ISSUE THREAD

**Issue by alisamii** [Homebrew/homebrew-php#1718]
I'm having a major issue. I have had a stable and working AMP stack installed via homebrew with DNSMASQ dynamic domains.

Today, I booted my mac to find that Safar, Chrome and all web browsers report that they cannot load the local dev sites (any of them) because the server cannot be found.

I checked on the command line and the domain names are properly resolving and pinging back.

    ➜  ping blck3.dev
    PING blck3.dev (127.0.0.1): 56 data bytes
    64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.068 ms
    64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.075 ms
    64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.095 ms
    64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.082 ms
    64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.053 ms

    --- blck3.dev ping statistics ---
    5 packets transmitted, 5 packets received, 0.0% packet loss
    round-trip min/avg/max/stddev = 0.053/0.075/0.095/0.014 ms

I then decided to check my apache config for errors and I get the following:

    ➜  httpd -v
    Server version: Apache/2.4.10 (Unix)
    Server built:   Jan  8 2015 20:48:33
    ➜  apachectl configtest
    httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php55/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php55/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib\n  Referenced from: /usr/local/opt/php55/libexec/apache2/libphp5.so\n  Reason: image not found

So, I decided to reinstall php55 as some people have reported that reinstalling php55 will solve the issue, but homebrew reports that there is no such formula.

    /usr/local/opt
    ➜  brew info php55
    Error: No available formula for php55
    ✘ /usr/local/opt
    ➜  brew info php56
    Error: No available formula for php56
    ✘ /usr/local/opt

I then did a search to see if I was having any issues specific to my machine wherein I couldn't see the php formulae:

    ➜  brew search php
    php53-sodium   php54-sodium   php55-sodium   php56-sodium   virtphp
    Caskroom/cask/eclipse-php     Caskroom/cask/netbeans-php    Caskroom/cask/phpstorm

I was surprised that neither php55, php55-mcrypt, php56 nor php56-mcrypt were available.

So, I checked to make sure all the relevant taps are properly tapped:

    ➜  brew tap homebrew/dupes
    Warning: Already tapped!
    /usr/local/opt
    ➜  brew tap homebrew/versions
    Warning: Already tapped!
    /usr/local/opt
    ➜  brew tap homebrew/homebrew-php
    Warning: Already tapped!

I then ran brew doctor which gives me the following error:

    ➜  brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:

        binutilsfb
        cloog018
        gmp4
        isl011
        libmpc08
        mpfr2
        rar

I have no idea what has gone wrong, because everything was working fine on Friday, nothing was touched over the weekend, and as of this morning...nothing seems to work properly.

Please advise, as this is a major problem for me and which I need to resolve ASAP.

Thank you,

Ali

**Comment by alanthing** [comment]
Please see #1701 about the libicui18n.54.dylib issue. As for the error on `brew info`, run `brew tap --repair` and see if that helps.

**Comment by alisamii** [comment]
OK, `brew tap --repair` seems to have fixed the `brew info` problems.

Re #1701 can you please give me a nutshell command to try and address the problem I'm having?

FYI, my `brew info php55` gives the following info:

    ➜  brew info php55
    php55: stable 5.5.24, HEAD
    https://php.net
    /usr/local/Cellar/php55/5.5.18 (0B)
      Built from source
    /usr/local/Cellar/php55/5.5.22 (497 files, 50M) *
      Built from source with: --with-gmp
    From: https://github.com/homebrew/homebrew-php/blob/master/Formula/php55.rb
    ==> Dependencies
    Required: freetype ✔, gettext ✔, homebrew/dupes/zlib ✔, icu4c ✔, jpeg ✔, libpng ✔, openssl ✔, unixodbc ✔
    Optional: enchant ✔, gmp ✔

**Comment by alanthing** [comment]
Run `brew update` and `brew install php55` as you intended to. You also might want to `brew upgrade` beforehand to ensure you'll fully up to date. I removed the pre-built binary bottle references until we sort out the icu4c issue.

**Comment by alisamii** [comment]
OK, I ran `brew update` and it returned `Already up-to-date.` So I ran `brew outdated` and it returned:

    composer (1.0.0-alpha9 < 1.0.0-alpha10)
    php55 (5.5.18, 5.5.22 < 5.5.24)
    php55-mcrypt (5.5.22 < 5.5.24)
    phpmyadmin (4.3.7 < 4.4.4)
    phpunit (4.5.0 < 4.6.6)

So right now, I'm running `brew upgrade`.

Should I still run `brew install php55` or `brew install php55 -fs` as mentioned in #1701 by you 7 days ago?

**Comment by alisamii** [comment]
Well, `brew upgrade` failed with the following error:

    ==> Upgrading composer
    dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
      Referenced from: /usr/local/opt/php55/bin/php
      Reason: image not found
    sh: line 1: 12885 Done(23)                curl -s http://getcomposer.org/installer
         12886 Trace/BPT trap: 5       | /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off -d date.timezone=UTC -d apc.enable_cli=Off -- --check
    composer: Composer PHP requirements check has failed. The following verification command:

        curl -s http://getcomposer.org/installer | /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off -d date.timezone=UTC -d apc.enable_cli=Off -- --check

    failed because of the following reason:


    Error: An unsatisfied requirement failed this build.

**Comment by alanthing** [comment]
Uninstall your existing php55 version and re-installing it. We're addressing that specific error as I write this.
