### ISSUE TITLE
Please remove all bintray binary

### ISSUE THREAD

**Issue by vimac** [Homebrew/homebrew-php#1743]
Bintray binary causing "Unable to initialize module" when php build with "--debug" flag, thanks

**Comment by alanthing** [comment]
Could you provide more detail? See the project README for the information we're looking for.

Also, many people find the binaries useful. If you wish to not use them for a specific installation, please build PHP from source.

**Comment by vimac** [comment]
For example, I installed php56 with these flag: 
```
brew install php56 --with-debug, --with-homebrew-curl
```

But, when I try to install php56-redis, installation will be ok, but when I try to run "php -m", I got this message: 

```
Warning: PHP Startup: redis: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
Unknown(0) : Warning - PHP Startup: redis: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
```

The "--with-debug" flag is important to me cause I'm learning php extension development
Then I have to modify php56-redis.rb, after remove these text:
```
  bottle do
    root_url "https://homebrew.bintray.com/bottles-php"
    sha256 "4c902fc0ba648255cb52307fa0937d8bd33c934c52c609d70476d24d82377537" => :yosemite
    sha256 "4bcfa55b1ed6349ae5467687c40829b50a466658041694cf5507767a357271fc" => :mavericks
    sha256 "b9f8123e103eb0329d9306d3dbd6e1bde1a60eb48d6a09a80cb6171b2f0edf00" => :mountain_lion
  end
```
Then reinstall(compile and install) the redis extension, it will be ok

**Comment by alanthing** [comment]
If you compile PHP with debug, you'll have to install extensions from source as well.

**Comment by vimac** [comment]
I know that, but the homebrew doesn't know, it still fetch bintray binary firstly as the FORMULA file  described :(

**Comment by DomT4** [comment]
Just pass `-fs` to your install arguments. `brew install example -fs`. It'll skip the bottle block entirely.

**Comment by DomT4** [comment]
You can also set `HOMEBREW_BUILD_FROM_SOURCE="1"` in your shell profile, which forces *everything* to build from source. It's a fairly drastic option to take though.

**Comment by josegonzalez** [comment]
Closing, as there isn't anything we can do and alternatives have been provided. This is more about your personal workflow than how homebrew-php distributes itself (or homebrew for that matter).

**Comment by pudy** [comment]
@DomT4 thank you , I fix the warning by -fs.
