### ISSUE TITLE
Can't install php55 or php56 on Yosemite

### ISSUE THREAD

**Issue by rnikander** [Homebrew/homebrew-php#1749]
First I try this:

    brew install homebrew/php/php56 --with-postgresql

And it craps out with this:

    ==> ./configure --prefix=/usr/local/Cellar/php56/5.6.9 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5
    checking for gzgets in -lz... yes
    checking whether to enable bc style precision math functions... yes
    checking for BZip2 support... yes
    checking for BZip2 in default path... not found
    configure: error: Please reinstall the BZip2 distribution
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/homebrew/homebrew-php/issues

So then I try without bz2:

    brew install homebrew/php/php56 --with-postgresql --without-bz2

And it dies again, with this:

    ==> ./configure --prefix=/usr/local/Cellar/php56/5.6.9 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5
    checking whether to enable ctype functions... yes
    checking for cURL support... yes
    checking for cURL in default path... not found
    configure: error: Please reinstall the libcurl distribution -
        easy.h should be in <curl-dir>/include/curl/
    
So then I try an option about curl:

    brew install homebrew/php/php56 --with-postgresql --without-bz2 --with-homebrew-curl

And it dies again:

    ==> ./configure --prefix=/usr/local/Cellar/php56/5.6.9 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5
    checking for curl_easy_strerror in -lcurl... yes
    checking for curl_multi_strerror in -lcurl... yes
    checking for QDBM support... no
    checking for GDBM support... no
    configure: error: DBA: Could not find necessary header file(s).

I give up.

**Comment by alanthing** [comment]
Please include all logs as specific on the project front page.

**Comment by rnikander** [comment]
Okay, I reran it and got the same error. It's in the gist. Now it's warning about macports too, because I installed that after reporting the bug yesterday. But I haven't installed any ports yet.

**OS X Version:** : 10.10.3
**Homebrew Version:** 0.9.5
**PHP Version in use:** n/a - trying to install
**Xcode Version:** 6.3.1
**Output of gcc -v:** 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
**Output of php -v:**  n/a
**Output of brew install -v homebrewphp/php56 ... within a gist** 
https://gist.github.com/rnikander/11353b4265c99fe7a031
**Output of brew doctor within a gist**
https://gist.github.com/rnikander/ac8bfaf069a20c5b2b3e

**Comment by tntclaus** [comment]
Exactly same problem here for php55 and php56. First it fails to get bz2, then — curl

**OS X Version:** 10.10.3
**Homebrew Version:** 0.9.5
**Xcode Version:** 6.3.2
**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
**Output of brew install ... within a gist** 
https://gist.github.com/tntclaus/8ea214e8a49eb6357856
**Output of brew doctor:**
Warning: Your XQuartz (2.7.5) is outdated
Please install XQuartz 2.7.7:
  https://xquartz.macosforge.org

**Comment by tntclaus** [comment]
@rnikander   Ok, after 5 more minutes of googling I found the solvation. Here it is:
https://github.com/Homebrew/homebrew-php/issues/1396#issuecomment-59987249

Xcode Command Line Tools need to be installed. I am copy pasting an answer from the linked comment.

1. brew uninstall php56
1. brew cleanup
1. xcode-select --install --> A window should appear to install.
1. brew install php56
