### ISSUE TITLE
Can we have a 2.x pecl-php-coucbase for php54-couchbase?

### ISSUE THREAD

**Issue by polesen** [Homebrew/homebrew-php#1751]
Would it be possible to upgrade the formula for php54-couchbase to build a newer 2.x php-pecl-couchbase? Currently, it seems to be building 1.2.2.

Or should that be a completely new formula, to avoid breaking someone?

**Comment by alanthing** [comment]
In my opinion, as long as 2.x is stable, the formula should be using the latest stable version. If you want to update the paths, sha256s, etc, and submit a PR, we'll let the Brew Test Bot run through it and see how it goes!
