### ISSUE TITLE
configure: error: Please reinstall the BZip2 distribution

### ISSUE THREAD

**Issue by xqpmjh** [Homebrew/homebrew-php#1753]
I got the following error when installing php：
$ brew install php56 --without-apache --with-fpm --with-mysql
......
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution
......

--------------------------------------------------------------------------------

I found the bzip2 in：
/usr/bin/bzip2

--------------------------------------------------------------------------------

I had tried install CLT, but seems already installed：
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

--------------------------------------------------------------------------------

My brew config :
# brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: bd76bd45f9fd8fb654735548d5b7d17a42c1658f
Last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit broadwell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: N/A
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_45

--------------------------------------------------------------------------------

How can I solve this?

**Comment by DomT4** [comment]
For whatever reason, re the discussion in https://github.com/Homebrew/homebrew/issues/39949 it's not recognising your CLT as existing. You can grab a new one [here](https://developer.apple.com/downloads/index.action) with a standard AppleID. Install that and then try again.

**Comment by xqpmjh** [comment]
Yes, it's fixed after installing the lastest version of CLT!

The problem maybe my old version of CLT didn't match the Xcode which I updated last week.

![image](https://cloud.githubusercontent.com/assets/463617/7745828/987372a6-ffe0-11e4-9ecc-7703dff08889.png)

Thank you Dominyk!

**Comment by alanthing** [comment]
I feel like this keeps coming up and it might be when someone has Xcode.app installed and not the CLI tools. Xcode has most libraries, but unless you install the separate CLT package, you might be missing some things.

In case someone stumbles upon this later, here's how you can ensure you're using the CLT for compiling:

```
xcode-select --install
sudo xcode-select --switch /Library/Developer/CommandLineTools
```

**Comment by DomT4** [comment]
@alanthing You could always enforce it for them?

```diff
diff --git a/abstract-php.rb b/abstract-php.rb
index c99552f..a82775d 100644
--- a/abstract-php.rb
+++ b/abstract-php.rb
@@ -206,8 +206,8 @@ INFO
       args << "--libexecdir=#{libexec}"
     end

-    if build.with? 'bz2'
-      args << '--with-bz2=/usr'
+    if build.with?("bz2") && MacOS::CLT.installed?
+      args << "--with-bz2=/usr"
     end

     if build.with? 'debug'
```

I think that should work.

**Comment by alanthing** [comment]
Interesting; if that fails, will it show some output on how to deal with it?

**Comment by DomT4** [comment]
No, It'll just silently refuse to pass the option to `configure`. If you wanted to be verbose about it you could do:

```ruby
    if build.with? "bz2"
      unless MacOS::CLT.installed?
        onoe <<-EOS.undent
          Please install Apple's Command Line Tools package
          to use the `--with-bz2` option. Proceeding without
          the option enabled.
        EOS
      else
        args << "--with-bz2=/usr"
      end
    end
```

That works.

**Comment by lachenmayer** [comment]
+1, just came across exactly this error. Would be great if a simple `brew install PHP56` without any added options told me what to do.
FWIW, I only had to run `xcode-select --install` and then everything worked.
Cheers :)
