### ISSUE TITLE
Error: Formulae found in multiple taps

### ISSUE THREAD

**Issue by lukasoppermann** [Homebrew/homebrew-php#1763]
Hey, `brew doctor` gives me the following error, how I can resolve it?

```
Error: Formulae found in multiple taps:
 * homebrew/php/php55
 * josegonzalez/php/php55

Please use the fully-qualified name e.g. homebrew/php/php55 to refer the formula.
```

**Comment by alanthing** [comment]
`josegonzalez/php` was deprecated a very long time ago. To resolve:

```
brew untap josegonzalez/php
brew tap --repair
brew update
```

**Comment by lukasoppermann** [comment]
Perfect, I had to run and additional `brew install php55` (this was displayed by homebrew) but now its fine. Thanks.

**Comment by DmitryVengerov** [comment]
Hi guys! 
I did as you wrote above and i dont know how works it. After pasting commands i open new terminal tab and i see this every time
`Error: No available formula with the name "josegonzalez/php/php55"`
`Please tap it and then try again: brew tap josegonzalez/php`

After ` brew tap josegonzalez/php` I see the same thing
After `brew install php55` I see the same thing 
:rage: :rage: :rage: :broken_heart:

**Comment by alcaeus** [comment]
You're trying to install `josegonzalez/php/php55` when you should just run `brew install php55` after untapping `josegonzalez/php` as is outlined in the first and second comments, respectively.

**Comment by josegonzalez** [comment]
Please refrain from commenting on 3+ year old issues.

This tap is no longer called josegonzalez/homebrew-php. For usage, see our readme. If you are still having issues, please file a new issue instead of commenting on a very old one.
