### ISSUE TITLE
Error when install homebrew/php/php55

### ISSUE THREAD

**Issue by abada** [Homebrew/homebrew-php#1765]
abada-2:Library abdellatifhenno$ brew install homebrew/php/php55 --with-fpm --without-apache --with-imap --with-debug --without-snmp
==> Installing php55 from homebrew/homebrew-php
==> Downloading https://www.php.net/get/php-5.5.25.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-5.5.25
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.25 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/php5520150601-4976-mk7hj3/php-5.5.25':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

LOG

https://gist.github.com/134178c6636310e10e82

**Comment by alanthing** [comment]
Please include gist logs via https://git.io/brew-troubleshooting

**Comment by abada** [comment]
I did

` brew gist-logs homebrew/php/php55` 

https://gist.github.com/134178c6636310e10e82

Thanks

**Comment by Zifius** [comment]
@abada did you resolve this? If not there are a lot of recommendations in the https://gist.github.com/anonymous/134178c6636310e10e82#file-doctor-out output

**Comment by ablyler** [comment]
Closing due to lack of feedback.
