### ISSUE TITLE
Can not install php56-mongo after upgrade

### ISSUE THREAD

**Issue by be-next-hotdog** [Homebrew/homebrew-php#1770]
While i wanna reinstall php56 mongo extension, i got the error as follow, 

$ sudo brew install php56-mongo
Error: Formulae found in multiple taps: 
 * homebrew/php/php56-mongo
 * josegonzalez/php/php56-mongo

And, so i typed the full name as : 

$ sudo brew install homebrew/php/php56-mongo
==> Installing php56-mongo from homebrew/homebrew-php
Error: Formulae found in multiple taps: 
 * homebrew/php/php56
 * josegonzalez/php/php56

Please use the fully-qualified name e.g. homebrew/php/php56 to refer the formula.

Anyone could give me some tips for this problem ? be graceful for your help !

**Comment by alanthing** [comment]
https://github.com/Homebrew/homebrew-php/issues/1763#issuecomment-107036448

**Comment by be-next-hotdog** [comment]
Cool, thx a lot, it did worked.
