### ISSUE TITLE
PHP 56 and opcache

### ISSUE THREAD

**Issue by toddmbloom** [Homebrew/homebrew-php#1771]
For some reason, I cannot get opcache to work on my PHP 5.6 installation. 

Whenever I do the install, `brew services restart php56`, and `php -v` I get the following:

```
Failed loading /usr/local/opt/php56-opcache/opcache.so:  dlopen(/usr/local/opt/php56-opcache/opcache.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php56-opcache/opcache.so
  Expected in: flat namespace
 in /usr/local/opt/php56-opcache/opcache.so
PHP 5.6.9 (cli) (built: Jun  4 2015 10:34:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

I've tried the following:

`brew install php56 --with-thread-safety --homebrew-apxs --enable-opcache `

As well as `--disable-opcache` because I've seen posts in this issue queue saying to do both.

Whenever I go to phpinfo(), though, it always says --disable-opcache in the configure statement even if additional ini files parsed lists ext-opcache.ini. 

Neither will show an opcache configuration in the body of phpinfo, though. :\

**Comment by toddmbloom** [comment]
Hm, With those options (--with-thread-safety) it seems that I have to install all my extensions with --build-from-source even though I didn't build php56 from source (I used Homebrew). :(

**Comment by alanthing** [comment]
You've assumed correctly. That's just the nature of using binary bottles to satisfy **most** user requirements but unfortunately not **all** users' requirements, such as yours.

**Comment by toddmbloom** [comment]
Ok! As long as --build-from-source isn't a "workaround"! :) It seems to work fine so all is good!

**Comment by alanthing** [comment]
It is a workaround b/c, up until recently, everything in homebrew-php was built from source. We've only recently begun to ship binary bottles, but those fit the most-likely of workflows.

**Comment by toddmbloom** [comment]
Great! That makes complete sense! Well everything still seems to work so it's all okay and I learned something new! Thanks!

**Comment by glassdimly** [comment]
Hey all,

I still get this error, but I can't seem to force php56 to rebuild with --enable-opcache. --enable-opcache is not listed in the available build options (brew options php56) for the package. You can see from the below output that it seems to be stripping out --enable-opcache.
````
$ brew reinstall php56 --build-from-source --enable-opcache --with-debug --with-pear --with-thread-safety --enable-maintainer-zts
==> Reinstalling homebrew/php/php56 with --with-debug, --with-pear, --with-thread-safety
````
I have also installed php56-opcache but that doesn't seem to help, either. I still see the exact same responses from phpinfo() and php -v that the @toddmbloom posted at the top.

I've also removed php55 and php55-opcache and then recompiled php56. Any ideas here?

**Comment by glassdimly** [comment]
I've create a gist of my php56 installation via 
    brew gist-logs php56
Here: https://gist.github.com/anonymous/8dd391e140e6f4b260aa

**Comment by glassdimly** [comment]
brew reinstall php56-opcache --build-from-source

Worked for me.

**Comment by jim0203** [comment]
brew reinstall php56-opcache --build-from-source

worked for me, too. Seems like that is the solution. Thanks @toddmbloom @alanthing
