### ISSUE TITLE
homebrew-php updates require me to update httpd.conf each time

### ISSUE THREAD

**Issue by reneruiz** [Homebrew/homebrew-php#1772]
I'm sure there's a more efficient way of doing this but it seems every time I update homebrew-php, I need to update this line in httpd.conf:

```
LoadModule php5_module /usr/local/Cellar/php54/5.4.39/libexec/apache2/libphp5.so
```

Can someone point me in the right direction?

**Comment by alanthing** [comment]
That's the best way to ensure mod_php doesn't break, to be honest. But, if you want to try an alternative method, try this:

```
LoadModule php5_module /usr/local/opt/php54/libexec/apache2/libphp5.so
```

Untested here, but give it a whirl.

**Comment by edrozenberg** [comment]
Seeing the same issue  - requires manual intervention to keep php working after every php version upgrade.

Since ```/usr/local/etc/apache2/2.4/httpd.conf``` is loading anything present in ```/usr/local/etc/apache2/2.4/other```, I've been deleting the php line from httpd.conf and instead added a file ```/usr/local/etc/apache2/2.4/other/php7.conf``` with contents:

```
<IfModule php7_module>
	AddType application/x-httpd-php .php
	AddType application/x-httpd-php-source .phps
	<IfModule dir_module>
		DirectoryIndex index.html index.php
	</IfModule>
</IfModule>
```
