### ISSUE TITLE
PHP Startup: memcached: Unable to initialize module

### ISSUE THREAD

**Issue by longfeiRen** [Homebrew/homebrew-php#1774]
brew install php55 --without-snmp --without-apache --with-debug --with-fpm --with-intl --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl --with-imap --with-mysql --with-tidy
==> Installing php55 from homebrew/homebrew-php
==> Downloading https://www.php.net/get/php-5.5.25.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-5.5.25
ç==> ./configure --prefix=/usr/local/Cellar/php55/5.5.25 --localstatedir=/usr/loc
==> make
==> make install
==> /usr/local/Cellar/php55/5.5.25/bin/pear config-set php_ini /usr/local/etc/ph
==> Caveats
The php.ini file can be found in:
    /usr/local/etc/php/5.5/php.ini

✩✩✩✩ PEAR ✩✩✩✩

If PEAR complains about permissions, 'fix' the default PEAR permissions and config:
    chmod -R ug+w /usr/local/Cellar/php55/5.5.25/lib/php
    pear config-set php_ini /usr/local/etc/php/5.5/php.ini system

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP55 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"

✩✩✩✩ FPM ✩✩✩✩

To launch php-fpm on startup:
    mkdir -p ~/Library/LaunchAgents
    cp /usr/local/opt/php55/homebrew.mxcl.php55.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php55.plist

The control script is located at /usr/local/opt/php55/sbin/php55-fpm

OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:

  PATH="/usr/local/sbin:$PATH"

You may also need to edit the plist to use the correct "UserName".

Please note that the plist was called 'homebrew-php.josegonzalez.php55.plist' in old versions
of this formula.

To have launchd start homebrew/php/php55 at login:
    ln -sfv /usr/local/opt/php55/*.plist ~/Library/LaunchAgents
Then to load homebrew/php/php55 now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php55.plist
==> Summary
🍺  /usr/local/Cellar/php55/5.5.25: 496 files, 45M, built in 5.3 minutes
Ren:~ ninlongfei$ çphp -v
-bash: çphp: command not found
Ren:~ ninlongfei$ php -v
PHP 5.5.25 (cli) (built: Jun  8 2015 11:05:17) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

brew install php55-memcached
==> Installing php55-memcached from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php55-memcached: php55-igbinary, libevent, memcached, libmemcached
==> Installing homebrew/php/php55-memcached dependency: php55-igbinary
==> Downloading https://homebrew.bintray.com/bottles-php/php55-igbinary-1.2.1.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/php55-igbinary-1.2.1.yosemite.bottle.tar.gz
==> Pouring php55-igbinary-1.2.1.yosemite.bottle.tar.gz
==> Caveats
To finish installing igbinary for PHP 5.5:
  * /usr/local/etc/php/5.5/conf.d/ext-igbinary.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the igbinary module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the igbinary module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php55-igbinary/1.2.1: 9 files, 80K
==> Installing homebrew/php/php55-memcached dependency: libevent
==> Downloading https://homebrew.bintray.com/bottles/libevent-2.0.22.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libevent-2.0.22.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libevent/2.0.22: 48 files, 1.8M
==> Installing homebrew/php/php55-memcached dependency: memcached
==> Downloading https://homebrew.bintray.com/bottles/memcached-1.4.24.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring memcached-1.4.24.yosemite.bottle.tar.gz
==> Caveats
To have launchd start memcached at login:
    ln -sfv /usr/local/opt/memcached/*.plist ~/Library/LaunchAgents
Then to load memcached now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist
Or, if you don't want/need launchctl, you can just run:
    /usr/local/opt/memcached/bin/memcached
==> Summary
🍺  /usr/local/Cellar/memcached/1.4.24: 10 files, 192K
==> Installing homebrew/php/php55-memcached dependency: libmemcached
==> Downloading https://homebrew.bintray.com/bottles/libmemcached-1.0.18_1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmemcached-1.0.18_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libmemcached/1.0.18_1: 227 files, 2.2M
==> Installing homebrew/php/php55-memcached
==> Downloading https://homebrew.bintray.com/bottles-php/php55-memcached-2.2.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring php55-memcached-2.2.0.yosemite.bottle.tar.gz
==> Caveats
To finish installing memcached for PHP 5.5:
  * /usr/local/etc/php/5.5/conf.d/ext-memcached.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the memcached module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the memcached module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php55-memcached/2.2.0: 5 files, 112K
Ren:Homebrew ninlongfei$ php -v
PHP Warning:  PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20121212,NTS
PHP    compiled with build ID=API20121212,NTS,debug
These options need to match
 in Unknown on line 0

Warning: PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20121212,NTS
PHP    compiled with build ID=API20121212,NTS,debug
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: memcached: Unable to initialize module
Module compiled with build ID=API20121212,NTS
PHP    compiled with build ID=API20121212,NTS,debug
These options need to match
 in Unknown on line 0

Warning: PHP Startup: memcached: Unable to initialize module
Module compiled with build ID=API20121212,NTS
PHP    compiled with build ID=API20121212,NTS,debug
These options need to match
 in Unknown on line 0
PHP 5.5.25 (cli) (built: Jun  8 2015 11:05:17) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by ablyler** [comment]
@longfeiRen try installing php55 without the debugging flag.

**Comment by ablyler** [comment]
Closing due to lack of feedback.
