### ISSUE TITLE
cannot install php extensions!

### ISSUE THREAD

**Issue by ChinaGithub** [Homebrew/homebrew-php#1775]
localhost:Formula xxx$ brew install homebrew/php/php56-msgpack
==> Installing php56-msgpack from homebrew/homebrew-php
Error: Formulae found in multiple taps: 
 * homebrew/php/php56
 * josegonzalez/php/php56

Please use the fully-qualified name e.g. homebrew/php/php56 to refer the formula.

---
my input name is homebrew/php/php56-msgpack is  fully-qualified name, But Why?  
brew version 0.9.5
os:Mac OS X Yosemite 10.10.3

**Comment by alanthing** [comment]
```
brew untap josegonzalez/php
brew tap --repair
brew update
```

**Comment by ChinaGithub** [comment]
thanks very much~ deal it @alanthing

**Comment by zpf8861** [comment]
太牛逼了

**Comment by chenyachao** [comment]
thanks. @alanthing

**Comment by tommyhuanglei** [comment]
赞，管用

**Comment by frankyxhl** [comment]
Thanks!

**Comment by abbish** [comment]
Good

**Comment by kangnixi** [comment]
赞！
Good！

**Comment by rakkang** [comment]
It's working! Thx. @alanthing

**Comment by yuqiangit** [comment]
thanks

**Comment by qingsonge** [comment]
Thank you very much, my problem is resolved

**Comment by Qambar** [comment]
Thanks ! :+1:

**Comment by Yemsheng** [comment]
Very good. Thanks !

**Comment by liulyliu** [comment]
thanks!

**Comment by josegonzalez** [comment]
You're welcome!
