### ISSUE TITLE
PHP 7.0.0?

### ISSUE THREAD

**Issue by jonnybarnes** [Homebrew/homebrew-php#1777]
Is there going to be a way to install PHP7 alphas/betas? [Alpha 1](http://php.net/archive/2015.php#id2015-06-11-3) has just been released, and it’d be cool to test if my code works on PHP7.

**Comment by vinkla** [comment]
+1

**Comment by lucasmichot** [comment]
PR are welcome

**Comment by tobiastom** [comment]
I would love to test it as well.

**Comment by alanthing** [comment]
Please see #1642 -- personally, I'd like to hold off until it's released stable. The linked issue has reference to another Homebrew tap where a preliminary `php7.rb` formula is being worked on.
