### ISSUE TITLE
Options --with-enchant and --with-imap cause segmentation fault at runtime

### ISSUE THREAD

**Issue by lifepillar** [Homebrew/homebrew-php#1789]
If I install PHP with `brew install php56 --with-enchant  --with-imap`, then accessing a page with a script `<?php phpinfo(); ?>` causes `php-fpm` to segfault.

Crash log: https://gist.github.com/lifepillar/c1f26492b5c4ad953db7

```
brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4e2b15c546f989d567e0902ded0b085f48ba652d
Last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit broadwell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_45
```

**Comment by ablyler** [comment]
@lifepillar: does `php -i` also cause a segfault for you?

**Comment by ablyler** [comment]
Closing due to lack of feedback.

**Comment by lifepillar** [comment]
Sorry, for some reasons Github notifications started to go into spam and… I forgot about this. Could you re-open this issue? I can reproduce the segfault with PHP 7.0.0RC7, and no, `php -i` does not crash.
