### ISSUE TITLE
Failed install: missing bottle for php55-opcache

### ISSUE THREAD

**Issue by ptim** [Homebrew/homebrew-php#1790]
I'm trying to `brew install php55-opcache`, but the requested file: php55-opcache-5.5.26.yosemite.bottle.tar.gz is not available at https://homebrew.bintray.com/bottles-php/ . php55-opcache-5.5.25.yosemite.bottle.tar.gz is the most recent version...

I tried `brew gist-logs php55-opcache`, but (I guess) because the install didn't get past the download, all I see is `Error: No logs`.

Hope this is the correct place to report.. TIA

Here is my terminal output:

```
brew install -v php55-opcache
==> Installing php55-opcache from homebrew/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-php/php55-opcache-5.5.26.yosemite.bottle.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.3) https://homebrew.bintray.com/bottles-php/php55-opcache-5.5.26.yosemite.bottle.tar.gz -C 0 -o /Library/Caches/Homebrew/php55-opcache-5.5.26.yosemite.bottle.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php55-opcache"
Download failed: https://homebrew.bintray.com/bottles-php/php55-opcache-5.5.26.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.3) https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror -C 0 -o /Library/Caches/Homebrew/php55-opcache-5.5.26.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to www.php.net port 443: Operation timed out
Error: Failed to download resource "php55-opcache"
Download failed: https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror
```

**Comment by ptim** [comment]
I've solved this for now by:

```
cd /usr/local/Library/Taps/homebrew/homebrew-php/Formula
git checkout d6de38b066f93bc207831b3508c65fccac91fe94
brew install -v php55-opcache
```

Seems to have worked :)

```
Additional .ini files parsed	/usr/local/etc/php/5.5/conf.d/ext-opcache.ini
...
Opcode Caching	Up and Running
Optimization	Enabled
Startup	OK
```

I was following instructions from http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula, and found the right commit here: https://github.com/Homebrew/homebrew-php/commit/d6de38b066f93bc207831b3508c65fccac91fe94

**Comment by DsXack** [comment]
problem with SSL certificate of www.php.net. Problem solved in #1786

**Comment by alanthing** [comment]
Thank you for this issue. I'll create a wiki page, but looks like we need to have new bottles built for the following every time PHP is updated:

* php5x-intl
* php5x-mcrypt
* php5x-opcache
* php5x-pcntl
* php5x-pdo-dblib
* php5x-pdo-pgsql
* php5x-pspell
* php5x-tidy

I'll get that going now.

**Comment by alanthing** [comment]
I put a rough version of notes, mainly for myself, here: https://github.com/Homebrew/homebrew-php/wiki/Bottles

The bottles are being built now and I'll close this issue when they're ready.

**Comment by alanthing** [comment]
Had a weird issue with the brew test bot and the branch. I just made a new branch, pull request, and brew test bot job. Should be pushed up within a few hours so I'll close this.
