### ISSUE TITLE
php55-redis 2.2.6 upgrade errors

### ISSUE THREAD

**Issue by nickfan** [Homebrew/homebrew-php#1793]
brew upgrade
==> Upgrading 1 outdated package, with result:
php55-redis 2.2.6
==> Upgrading php55-redis
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.6.tar.gz
######################################################################## 100.0%
==> Patching
==> /usr/local/opt/php55/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php55-redis/2.2.6 --with-php-config=/
==> make
static void redis_error_throw(char *err, size_t err_len TSRMLS_DC) {
^
4 errors generated.
make: *** [library.lo] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

**Comment by ablyler** [comment]
@nickfan can you try again, and re-open if this is still an issue?
