### ISSUE TITLE
Error: Formulae found in multiple taps:

### ISSUE THREAD

**Issue by patrickmaciel** [Homebrew/homebrew-php#1795]
When I try to install php-cs-fixer I get this error.

How to solve that?

    brew install josegonzalez/php/php-cs-fixer
                                                                                                                                   
    Error: Formulae found in multiple taps:
     * homebrew/php/php53
     * josegonzalez/php/php53

    Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.

**Comment by xu-cheng** [comment]
You should untap `josegonzalez/php` which is `homebrew/php` now.

**Comment by patrickmaciel** [comment]
Everything in `josegonzalez/php` is in `homebrew/php` now?

**Comment by xu-cheng** [comment]
> Everything in josegonzalez/php is in homebrew/php now?

Yes. The repo has been transferred to Homebrew org long time ago.

**Comment by patrickmaciel** [comment]
Thanks my friend. It's work.
