### ISSUE TITLE
Can't install PHP55 ... 404 Not Found

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/homebrew-php#1797]
_From @ksnyde on June 15, 2015 9:47_

I recently ran into a problem where attempt to `upgrade` any of the PHP taps fails with a 404 error. Specifically:

> ==> Upgrading homebrew/php/php55
> ==> Downloading https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror
> ==> Downloading https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror
> curl: (22) The requested URL returned error: 404 Not Found
> Download failed: https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror

This has put me into a very bad place as I can't do anything with PHP at the moment. Any help would be greatly appreciated.

_Copied from original issue: Homebrew/homebrew#40734_

**Comment by jacknagel** [comment]
_From @ksnyde on June 15, 2015 9:49_

Note that trying to upgrade **PHP55-mcrypt** results in the same outcome ... non-PHP based *upgrades* are working fine.

**Comment by ksnyde** [comment]
@jacknagel thanks for transporting me to the right homebrew issues ... why is PHP carved out separately?

**Comment by alanthing** [comment]
@ksnyde This has been resolved in #1786.

**Comment by ksnyde** [comment]
This is still open! The issue that was fixed is the SSL certificate issue which can be worked around locally (I had already done this). Once you're *past* the SSL cert issue the **404 Not Found** error occurs.

**Comment by alanthing** [comment]
Please provide more information as per the front page of this project. If I visit the download URLs in #1786, I can download PHP source without issue.

**Comment by ksnyde** [comment]
But what about the URLs in THIS issue? See above. Also note I am in the UK and I think -- you probably know more about this -- this URL redirects to a regional CDN hosted version?

**Comment by alanthing** [comment]
#1786 is merged, so if you run `brew update` you will no longer see the www URLs. What URLs are you being presented with and seeing fail **after** a `brew update`?

**Comment by ksnyde** [comment]
oh shit. had forgotten to do the update. my bad. thanks for your patience.

**Comment by alanthing** [comment]
No worries! Does it work for you now? Let us know if it's still unresolved and we can dive into it.
