### ISSUE TITLE
Macport and brew conflict

### ISSUE THREAD

**Issue by grasses** [Homebrew/homebrew-php#1809]
error log:

/usr/local/opt/php56/bin/phpize

Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

but I do not want to uninstall Macport.

**Comment by alanthing** [comment]
This is a warning, it did not necessarily create a problem.

We cannot guarantee compatibility with other package managers, so we warn you about it. It's up to you if you want to take action. I know many people who have both installed without problem, but your mileage may vary.
