### ISSUE TITLE
PHP70 alpha 2 apache module issue

### ISSUE THREAD

**Issue by th3fallen** [Homebrew/homebrew-php#1829]
Not sure if this is an issue for here or not but when installing php70 via your tap and linking it all i get this when attempting to restart apache

```httpd: Syntax error on line 169 of /private/etc/apache2/httpd.conf: Can't locate API module structure `php5_module' in file /usr/local/lib/libphp5.so: dlsym(0x7fb5abe02810, php5_module): symbol not found```

Note that ```/usr/local/lib/libphp5.so``` is symlinked to the active version of php on my machine by sphp any one else had this issue or been able to resolve it?

**Comment by ablyler** [comment]
@th3fallen does the following work?

```
LoadModule php7_module /usr/local/opt/php70/libexec/apache2/libphp7.so
````

**Comment by philcook** [comment]
The loading of the PHP 7 module works for me.

**Comment by ablyler** [comment]
Thanks @philcook! I'll work on updating the documentation for php70.

**Comment by th3fallen** [comment]
still doesnt work for me with that, but that's likely to my borked brew instalation on 10.11

I'll report back once i get it sorted out.

**Comment by philcook** [comment]
Strange that the apache config seems fine but my work mac just loads the php as text in browser.

I think there may be extra apache config to add with PHP 7.0 but failing to find any docs about this. Will keep digging but if anyone else finds anything out please let me know.

**Comment by th3fallen** [comment]
Finally got brew fixed.

@philcook LoadModule php7_module fails, and same as you loading a php file just shows the code in your browser meaning its not loaded correctly.

If you find something please let me know.

@ablyler this shouldn't be closed.

**Comment by philcook** [comment]
For some reason we now need to specify PHP files are set to use PHP within the apache config. Strange not had to do this for previous versions but it works.

Simply add this to your httpd.conf
```
<FilesMatch \.php$>
SetHandler application/x-httpd-php
</FilesMatch>
```
Source [Install Ubuntu](http://php7.zend.com/install-ubuntu.php)

Now I get a phpinfo() running. Will add do another PR to add this to the CLI instructions for the apache config.

So I get phpinfo now but my other web projects I am getting a forbidden. Hmm more work required to find out why.

**Comment by th3fallen** [comment]
strange but your absolutely correct that worked for me too

**Comment by philcook** [comment]
@th3fallen great glad to hear. Are you getting any 403 forbidden errors with any web projects? They are all over the shop for me.

**Comment by th3fallen** [comment]
@philcook nope all is well for me...

**Comment by philcook** [comment]
@th3fallen argh damn thats what I was afraid of. More fiddling for me then.
