### ISSUE TITLE
Make error php56

### ISSUE THREAD

**Issue by ibernale** [Homebrew/homebrew-php#1842]
I have an error installing php56 with brew:

bash-3.2# brew install php56
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.6.11.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.11
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.11 --localstatedir=/usr/local/var --sysconfdir=/usr/loc
==> make
      _zm_info_apache in php_functions.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....

OS  X Yosemite 10.10.3
Brew 0.9.5
XCode 6.3.2

Any idea?

**Comment by ablyler** [comment]
@ibernale please provide the `brew doctor` and other output that is outlined in https://github.com/Homebrew/homebrew-php#filing-bug-reports

**Comment by toabi** [comment]
Same issue here. Brew doctor is happy.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.4
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | PHP 5.5.24
**Xcode Version:** | 6.4
**Output of gcc -v:** | Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
**Output of php -v:** | PHP 5.5.24 (cli) (built: May 19 2015 10:10:05) 
**Output of brew install -v php56 ** | https://gist.github.com/toabi/d965617ad54788cd35f4
**Output of brew doctor within a gist** | … is happy

**Comment by ablyler** [comment]
@toabi is this still an issue?

**Comment by javian** [comment]
Closing issue due to no response.
