### ISSUE TITLE
When connecting to a SSL MySQL Database getting a "Abort trap: 6" Error

### ISSUE THREAD

**Issue by rajdsouza** [Homebrew/homebrew-php#1899]
This error only started after installing the latest openssl using "brew install openssl"

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.4
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.5.26
**Xcode Version:** | Version 6.4 (6E35b)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn) Target: x86_64-apple-darwin14.4.0 Thread model: posix
**Output of php -v:** | PHP 5.5.26 (cli) (built: Jul 14 2015 08:34:24)  Copyright (c) 1997-2015 The PHP Group Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies     with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
**Output of brew doctor within a gist** | https://gist.github.com/rajdsouza/ba507d3e7c3f32016396

installed php using the following
```
brew install php55 --with-fpm --without-apache --with-debug --with-gmp --with-mssql --with-tidy --without-snmp --force
brew install php55-mcrypt  php55-crypto php55-mongo php55-ssh2 php55-xdebug
```
```
rajdsouza:web rajdsouza$ ./shell somecommand.php
Abort trap: 6
rajdsouza:web rajdsouza$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46
rajdsouza:web rajdsouza$ php --version
PHP 5.5.26 (cli) (built: Jul 14 2015 08:34:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
rajdsouza:web rajdsouza$ php -i | grep openssl
Configure Command =>  './configure'  '--prefix=/usr/local/Cellar/php55/5.5.26' '--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/5.5' '--with-config-file-path=/usr/local/etc/php/5.5' '--with-config-file-scan-dir=/usr/local/etc/php/5.5/conf.d' '--mandir=/usr/local/Cellar/php55/5.5.26/share/man' '--enable-bcmath' '--enable-calendar' '--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' '--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' '--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-libedit' '--with-mhash' '--with-ndbm=/usr' '--with-openssl=/usr/local/opt/openssl' '--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc' '--with-png-dir=/usr/local/opt/libpng' '--with-unixODBC=/usr/local/opt/unixodbc' '--with-xmlrpc' '--with-zlib=/usr/local/opt/zlib' '--with-bz2=/usr' '--disable-debug' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' '--with-gmp=/usr/local/opt/gmp' '--with-curl' '--with-xsl=/usr' '--with-ldap' '--with-ldap-sasl=/usr' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-mysql=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-mssql=/usr/local/opt/freetds' '--with-pdo-dblib=/usr/local/opt/freetds' '--disable-opcache' '--enable-pcntl' '--with-tidy=/usr/local/opt/tidy-html5' '--enable-dtrace' '--enable-zend-signals'
openssl
rajdsouza:web rajdsouza$ brew --version
0.9.5
```

```
rajdsouza:web rajdsouza$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
```

**Comment by rajdsouza** [comment]
Installed a new version but the same error still exists

Link to the installation log
https://gist.github.com/rajdsouza/79cf722e8cc45cfe8035

```
rajdsouza:web rajdsouza$ ./shell stocktake confirmPending
Abort trap: 6
```

**Comment by rajdsouza** [comment]
Also could this be an issue
![screen shot 2015-07-14 at 1 23 47 pm](https://cloud.githubusercontent.com/assets/1773830/8665804/c2183202-2a2b-11e5-82a0-733001be1c0e.png)

**Comment by ablyler** [comment]
@rajdsouza can you uninstall and then install both php and openssl and see if it is still an issue?  there were some changes to the openssl formula that might be the cause.

**Comment by rajdsouza** [comment]
Tried a uninstall and reinstall. the issue still persists. See the whole transcript.
https://gist.github.com/rajdsouza/0df777c0643c814b92ca

It connects to mysql servers but not using ssl.

**Comment by rajdsouza** [comment]
Have installed php56 and the same issue still exists. No updates from openssl package too.

**Comment by rajdsouza** [comment]
http://serverfault.com/questions/700747/how-to-fix-logjam-vulnerability-with-mysql

This explains why we are getting the issue. Is there a way to force install a previous version openssl ?

**Comment by ablyler** [comment]
@rajdsouza are you connecting to a MySQL that is also running on your Mac?

**Comment by rajdsouza** [comment]
Yes that is correct

**Comment by javian** [comment]
@rajdsouza is this still an issue ?

**Comment by javian** [comment]
Closing due to no response.

**Comment by rajdsouza** [comment]
Have upgraded mariadb to version 10.1.14. This seems to fix the issue.

**Comment by NinoSkopac** [comment]
I have the same problem.

mac os sierra
openssl OpenSSL 0.9.8zh 14 Jan 2016
php 5.6.30

Trying to connect to DB via SSL

**Comment by javian** [comment]
@NinoSkopac I thinkt its easiest if you open a new issue and supply the config that's requested. I'm locking this issue so if anyone else is having this issue then please follow the same procedure =)
