### ISSUE TITLE
`brew install php56 --with-phpdbg` says "phpdbg is not supported for this version of PHP"

### ISSUE THREAD

**Issue by tboyce12** [Homebrew/homebrew-php#1915]
I am unable to `brew install php56 --with-phpdbg` -- the error says PHP 5.6 does not support phpdbg (sounds untrue based on my research). I even deleted `/usr/local`, did a fresh install of Homebrew, no success. I just want to be able to step through the PHP codebase I am learning line-for-line and examine variables, etc... shouldn't be asking too much (new job, also new to PHP). Any thoughts on what's up here? Please let me know if there is more useful info I can supply. Thanks!

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.4 (14E46)
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | Not yet installed via homebrew
**Xcode Version:** | Version 6.4 (6E35b)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
 | Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
 | Target: x86_64-apple-darwin14.4.0
 | Thread model: posix
**Output of php -v:** | PHP 5.5.24 (cli) (built: May 19 2015 10:10:05) 
 | Copyright (c) 1997-2015 The PHP Group
 | Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | [Raw Gist](https://gist.githubusercontent.com/tboyce12/343e720456eedd7bae0f/raw/d530e3dc0265295774c27879d719ef034001568e/cli)
**Output of brew doctor within a gist** | $ brew doctor
 | Your system is ready to brew.
**List of all brew commands I ran** | [Raw Gist](https://gist.githubusercontent.com/tboyce12/e986b7f6c33082c9fb59/raw/0a1ca70d61fadc76f58400a1a92097925da38a8e/brew-fail.txt)

**Comment by ablyler** [comment]
Should be fixed now.

**Comment by tboyce12** [comment]
Thanks so much!
