### ISSUE TITLE
Phpinfo still shows the old version- PHP with Nginx on Mac

### ISSUE THREAD

**Issue by tarex2013** [Homebrew/homebrew-php#1927]
Hey folks,
Just removed php54 and installed php56. Removed php54 process from ~/Library/LaunchAgents and from /usr/local/opt. php -v on CLI is showing the right version, however phpinfo is still shows old php version of php 5.4

I have restarted php and nginx process but still no luck.

Any Idea

**Comment by alanthing** [comment]
Can you screenshot the top of a `phpinfo();` page?

**Comment by tarex2013** [comment]
![screen shot 2015-07-20 at 17 45 52](https://cloud.githubusercontent.com/assets/4078105/8781519/6cdc9c16-2f07-11e5-81dc-0b3dec9a76ed.png)

@alanthing 
See attached. All following files are removed but phpinfo still pointing to them

Configuration File (php.ini) Path	/usr/local/etc/php/5.4
Loaded Configuration File	/usr/local/etc/php/5.4/php.ini
Scan this dir for additional .ini files	/usr/local/etc/php/5.4/conf.d

thx

**Comment by josegonzalez** [comment]
If you are using apache, you need to tell apache to use your new php version. That does not happen automatically.
