### ISSUE TITLE
php warning - unable to load dynamic library mysqlnd_ms

### ISSUE THREAD

**Issue by BardiaAfshin** [Homebrew/homebrew-php#1928]
I'm getting the following warning whenever I trigger php

```bash
 php --version
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55-mysqlnd_ms/1.4.2/mysqlnd_ms.so' - dlopen(/usr/local/Cellar/php55-mysqlnd_ms/1.4.2/mysqlnd_ms.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55-mysqlnd_ms/1.4.2/mysqlnd_ms.so' - dlopen(/usr/local/Cellar/php55-mysqlnd_ms/1.4.2/mysqlnd_ms.so, 9): image not found in Unknown on line 0
PHP 5.5.27 (cli) (built: Jul 14 2015 17:04:01) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by ablyler** [comment]
@BardiaAfshin what does `brew info php55-mysqlnd_ms` output?

**Comment by ablyler** [comment]
Closing due to lack of feedback.

**Comment by BardiaAfshin** [comment]
homebrew/php/php55-mysqlnd_ms: stable 1.5.2 (bottled), HEAD
https://pecl.php.net/package/mysqlnd_ms
/usr/local/Cellar/php55-mysqlnd_ms/1.5.2 (5 files, 228K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php55-mysqlnd_ms.rb
==> Dependencies
Build: autoconf ✔
Required: php55 ✔
==> Options
--without-config-file
	Do not install extension config file
--without-homebrew-php
	Ignore homebrew PHP and use default instead
--HEAD
	Install HEAD version
==> Caveats
To finish installing mysqlnd_ms for PHP 5.5:
  * /usr/local/etc/php/5.5/conf.d/ext-mysqlnd_ms.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the mysqlnd_ms module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the mysqlnd_ms module.
  * - If you see it, you have been successful!
