### ISSUE TITLE
Cant use gmp module

### ISSUE THREAD

**Issue by Maidomax** [Homebrew/homebrew-php#1929]
I run `brew install php56 --with-gmp`, the installation seems to go well, but after I try using a function from 'gmp', namely `gmp_strval()`, I get the error that the function is undefined. When I try including 'gmp.so' in 'php'ini' like I would with other modules, I get the message:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/gmp.so' - dlopen(/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/gmp.so, 9): image not found in Unknown on line 0
```

What do I need to do to get the module to run?

**Comment by ablyler** [comment]
@Maidomax i just moved gmp into a separate formula.  Try installing php56-gmp

**Comment by Maidomax** [comment]
@ablyler That's it, it works, thanks!
