### ISSUE TITLE
Cannot build php56 5.6.11 on OS X 10.11 Developer Beta 4

### ISSUE THREAD

**Issue by nesl247** [Homebrew/homebrew-php#1931]
On Developer Beta 4, using XCode 7.0 Beta 4, I get the following error during make. I already recompiled openssl after upgrading and using the new tools from Xcode 7.0 Beta 4.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.11 Developer Beta 4
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.6.11
**Xcode Version:** | 7.0 Beta 4
**Output of gcc -v:** | Below
**Output of php -v:** | Below
**Output of brew install -v:** | Below
**Output of brew doctor within a gist** | Warning about OS X 10.11

gcc -v
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.59.1)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

php-v
```
dyld: Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/opt/php56/bin/php
  Reason: image not found
fish: 'php -v' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

make error
```
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
make: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
make: *** [libs/libphp5.bundle] Error 1
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/fpm/php-fpm] Error 1
```

**Comment by alanthing** [comment]
Bear in mind, we won't be supporting OS X 10.11 until it's generally available.

**Comment by leecade** [comment]
@nesl247 

```
brew link libxml2 --force
```

**Comment by alex88** [comment]
@leecade you made my day! Thanks! Maybe configure should use homebrew's libxml2?

**Comment by nesl247** [comment]
Thanks for the info @leecade. I haven't had a chance to try and rebuild PHP again, but when I do I'll give that a shot.

**Comment by alex88** [comment]
Just tested and it solves the issue

**Comment by XMap** [comment]
###brew install php56
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.6.11.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.11
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.11_2 --localstatedir=/usr/l
==> make
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

**Comment by nesl247** [comment]
Got the same thing as you @XMap.

**Comment by ecanuto** [comment]
Add --with-homebrew-libressl --with-homebrew-libxml2 fixes the problem.

Try use:

brew install --with-homebrew-libressl --with-homebrew-libxml2 php56

**Comment by thecatontheflat** [comment]
thank you @ecanuto
