### ISSUE TITLE
Problem installing php70-opcache from bottle

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew-php#1937]
The first two lines of `ext-opcache.ini` is as following:
```ini
[opcache]
zend_extension="@@HOMEBREW_PREFIX@@/opt/php70-opcache/opcache.so"
```

The `@@HOMEBREW_PREFIX@@` should be replaced but not.

**Comment by craigcarnell** [comment]
@guoxiao Same issue here

**Comment by ablyler** [comment]
@guoxiao / @craigcarnell are you still having this issue? I can't reproduce it.
