### ISSUE TITLE
Move curl into an .so

### ISSUE THREAD

**Issue by atrauzzi** [Homebrew/homebrew-php#1944]
Some people on my team use the PHP from homebrew to run the local google app engine development server.

Unfortunately, because cURL is bundled with the build as opposed to being an `.so`, we are unable to either prevent it from being loaded, or load it using our project-root level `php.ini` file (a convention with GAE).

Despite the fact that cURL is pretty much a guarantee for most PHP setups, this is a scenario where it would be nice to still have control over when the module is loaded.  Otherwise, we end up trying to double-load it.

**Comment by javian** [comment]
How does it manage to get double loaded ? I didn't understand that part.

**Comment by dunn** [comment]
`libcurl.dylib` is installed; on OSX `dylib` is generally used instead of `so`.

**Comment by javian** [comment]
@atrauzzi would an acceptable option be to compile without curl support altogether and have curl be provided GCE alone ?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in 2+ weeks.
