### ISSUE TITLE
Cannot find libz when install php56

### ISSUE THREAD

**Issue by SeanCode** [Homebrew/homebrew-php#1946]
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.11_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by LoicUV** [comment]
Same issue with php54 on OS X 10.11 PB3 : 

==> ./configure --prefix=/usr/local/Cellar/php54/5.4.43_2 --localstatedir=/usr/local/var --sysconfdir=/usr/lo
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by dunn** [comment]
Could you both post `brew gist-logs php56`, please?

**Comment by LoicUV** [comment]
https://gist.github.com/anonymous/0cf06eeb396dd4106f7a

**Comment by LoicUV** [comment]
Looks like I fixed my issue, I did install Xcode 7 and ran
```
sudo xcode-select -s /Applications/Xcode-beta.app
```

But I forgot Command Line Tools to be installed with 
`xcode-select --install`


Then `brew reinstall php54` did the trick.
Sorry for my mistake, thanks for you time though.

**Comment by DouglasUrner** [comment]
Thank you! That solved my problem too (on 10.11 beta 4).

**Comment by andreas4all** [comment]
I have same issue with php 5.6.12 in brew. After update Mac OS X I got this error. I just re-install xcode tools with

```bash
xcode-select --install
```

and after this is all OK.

**Comment by stopspazzing** [comment]
TY solved my problem on Mac OS X using brew and php 5.6.x - So annoying.

**Comment by ahoffmann-wi** [comment]
`xcode-select --install` worked for me after receiving this error message following an upgrade to El Capitan

**Comment by mariusvw** [comment]
Having El Capitan 10.11 running gave me the same issue.

Same here, reinstalling xcode cli tools solved the problem.

**Comment by margaritis** [comment]
Command Line Tools were missing after Xcode 7 upgrade. `xcode-select --install` did the trick.

**Comment by wildone** [comment]
Thanks guys, on El Capitan this worked:

xcode-select --install
brew upgrade

**Comment by Chen-tao** [comment]
actually I upgrade my Xcode, but I still found this case 
and ``xcode-select --install`` is worked.

**Comment by ravitejaobelisk** [comment]
`xcode-select --install` worked for me. OSX El Capitan

**Comment by friparia** [comment]
`xcode-select --install` worked for me, thank you

**Comment by shuizhongyueming** [comment]
`xcode-select --install` worked for me, thanks a lot!

**Comment by AHoffmeyerSixt** [comment]
xcode-select --install worked for me. OSX El Capitan

**Comment by iPadGuy** [comment]
`xcode-select --install 
brew upgrade`

Worked for me, too.
OS X El Capitan.

**Comment by mkurde** [comment]
xcode-select --install 
brew upgrade

did the job. Thank you.
