### ISSUE TITLE
php55, php56 install freezes 10.11

### ISSUE THREAD

**Issue by 007pig** [Homebrew/homebrew-php#1949]
See #1541. The same happens to El Capitan. I can't reopen that issue so I start a new one. I can't install PHP via homebrew at all. The whole OS freezes when making php.

**Comment by 007pig** [comment]
OK finally I found a way to fix the issue. I deleted everything in /usr/local, reinstalled homebrew and it worked again. I think there must be some old files which were not compatible with php56.

**Comment by ohpyupi** [comment]
Doesn't seems to be a good solution. I have all setup configure for my production app, and so much worried about deleting entierly /usr/local.
