### ISSUE TITLE
osx 10.11 beta 3 issue brew install php56

### ISSUE THREAD

**Issue by tabvn** [Homebrew/homebrew-php#1951]
https://gist.github.com/dfa4015b56adf8cd5362

**Comment by tabvn** [comment]
toan:Desktop toan$ sudo brew install php56
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.6.11.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.6.11.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.11_2 --localstatedir=/usr/l
==> make
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

**Comment by ablyler** [comment]
@tabvn you don't need to sudo to brew install.

**Comment by ablyler** [comment]
@tabvn is look like you need to upgrade Xcode 

```
Warning: Your Xcode (6.4) is outdated
Please update to Xcode 7.0.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/
```
