### ISSUE TITLE
upgrade is not transparent if there is more than one formula installed

### ISSUE THREAD

**Issue by Maks3w** [Homebrew/homebrew-php#1952]
Note: I'm not sure if this is an issue of homebrew php or not

I'm a PHP developer and I have multiple php versions installed, php54, php55, php56, php7, ... and I test the software to be compatible with more than one version (i.e. is not factible to me to do brew unlink && brew link)

My issue is each time a patch version is released (php 5.4.X > php 5.4.X+1) I have to reconfigure all my dev environment to point the new paths.

So, Is it possible to create a symlink to point the latest patch version automatically after upgrade?

ex: `/usr/local/Cellar/php54/latest -> /usr/local/Cellar/php54/5.4.43`,  `/usr/local/Cellar/php55/latest -> /usr/local/Cellar/php54/5.5.27`

The above example use `latest` as a symlink to the latest patch version. By this way I have only configure my dev environment paths once.

**Comment by Maks3w** [comment]
There are symlinks to latest formulas on `/usr/local/Library/LinkedKegs`

Thanks to: http://superuser.com/a/593931/217381

**Comment by Maks3w** [comment]
However not all php formula are present because `brew unlink` remove the symlink present in `/usr/local/Library/LinkedKegs` and `/usr/local/bin`

Could be possible `brew unlink` to preserve the symlink present in `/usr/local/Library/LinkedKegs`?

**Comment by ablyler** [comment]
@Maks3w https://github.com/wilmoore/php-version#simple-php-version-switching might be a good solution for you.

**Comment by Maks3w** [comment]
No the issue is there are missing symlinks present in /usr/local/Library/LinkedKegs

Please reopen

**Comment by ablyler** [comment]
@Maks3w that isn't possible currently, however https://github.com/Homebrew/homebrew-php/issues/1999 might make it possible. :-)

**Comment by Maks3w** [comment]
In the meantime I did brew link with force switch enable for achieve the desired effect
