### ISSUE TITLE
brew install php55-memcached failed

### ISSUE THREAD

**Issue by chenlexing** [Homebrew/homebrew-php#1953]
derekmpro:~ derek$ brew install php55-memcached
==> Installing php55-memcached from homebrew/homebrew-php
==> Downloading http://pecl.php.net/get/memcached-2.2.0.tgz
Already downloaded: /Library/Caches/Homebrew/php55-memcached-2.2.0.tgz
==> /usr/local/opt/php55/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php55-memcached/2.2.0 --with-php-config=/usr/local/opt/php55/bin/php-config --with-libmemcached-d
checking whether to enable memcached sasl support... yes
checking whether to enable memcached protocol support... no
checking for ZLIB... yes, shared
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking for zlib location... configure: error: memcached support requires ZLIB. Use --with-zlib-dir=<DIR> to specify the prefix where ZLIB headers and library are located

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

derekmpro:~ derek$

**Comment by ablyler** [comment]
@chenlexing what is the output of `brew doctor`?

**Comment by chenlexing** [comment]
Thanks for you reply.

please see below info:

derekmpro:~ derek$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: /Library/Frameworks/libcurl.framework detected
This can be picked up by CMake's build system and likely cause the build to
fail. You may need to move this file out of the way to compile CMake.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
derekmpro:~ derek$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:227:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
derekmpro:~ derek$

**Comment by ablyler** [comment]
@chenlexing, file an issue with https://github.com/Homebrew/homebrew in regards to `brew update` not working.

**Comment by CashWilliams** [comment]
I think this is a valid bug.


OS X 10.10.5 clean install

```
 $ brew install php55-memcache
==> Installing php55-memcache from homebrew/homebrew-php
==> Downloading http://pecl.php.net/get/memcache-2.2.7.tgz
Already downloaded: /Library/Caches/Homebrew/php55-memcache-2.2.7.tgz
==> /usr/local/opt/php55/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php55-memcache/2.2.7 --with-php-config=/usr/local/opt/php55/bin/php-config
checking if awk is broken... no
checking whether to enable memcache support... yes, shared
checking whether to enable memcache session handler support... yes
checking for the location of ZLIB... no
checking for the location of zlib... configure: error: memcache support requires ZLIB. Use --with-zlib-dir=<DIR> to specify prefix where ZLIB include and library are located

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues


 $ brew doctor
Your system is ready to brew.
```

**Comment by cordoval** [comment]
I have the same problem why closing?

**Comment by CashWilliams** [comment]
@cordoval see https://github.com/Homebrew/homebrew-php/issues/2029 which fixed issue for me

**Comment by cordoval** [comment]
thx it will work!

**Comment by feivorid** [comment]
thx a lot, it work!
