### ISSUE TITLE
install php56  Cannot find lib

### ISSUE THREAD

**Issue by isfpcn** [Homebrew/homebrew-php#1998]
yaoqingsongdeMacBook-Pro:Cellar yaoqingsong$ cd /usr/local/Cellar/
yaoqingsongdeMacBook-Pro:Cellar yaoqingsong$ ls
cmake		icu4c		lzlib		pcre		unixodbc
curl		imap-uw		mysql		pkg-config	wget
freetype	jpeg		nginx		readline	xz
gettext		libpng		openssl		tidy-html5	zlib

yaoqingsongdeMacBook-Pro:Cellar yaoqingsong$ brew install php56
==> Installing php56 from josegonzalez/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/p

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php56"
Download failed: https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php56-5.6.12.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://php.net/get/php-5.6.12.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.12
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.12 --localstatedir=/usr/loc
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/josegonzalez/homebrew-php/issues

os x versions : 10.10.4

**Comment by ablyler** [comment]
@isfpcn what is the output of `brew doctor`?

**Comment by xi4oh4o** [comment]
@isfpcn try brew link zlib --force :+1:

**Comment by LynQJ** [comment]
I have the same problem. I installed php53.

**Comment by ablyler** [comment]
zlib is included as part of the Xcode command line tools, please make sure you have that installed and include the output of brew doctor if this issue is still occurring.

**Comment by designsimply** [comment]
I'm seeing the same problem: when I try to install php56, it errors out with:

```
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz
```

Running `brew doctor` returns `Your system is ready to brew.`

I checked to make sure Xcode command line tools were installed by looking in Xcode > Preferences > Locations ([screenshot](https://cloudup.com/crnyevM04au)).

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.5-x86_64
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | stock-apple
**Xcode Version:** | 6.4
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1<br>Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)<br>Target: x86_64-apple-darwin14.5.0<br>Thread model: posix
**Output of php -v:** | PHP 5.5.27 (cli) (built: Jul 23 2015 00:21:59) <br>Copyright (c) 1997-2015 The PHP Group<br>Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
**brew install options used** | `brew install --without-apache --without-ldap --with-fpm --with-mysql --verbose php56`
**Output of `brew gist-logs php56` within a gist** | https://gist.github.com/anonymous/e49ff0688a79240d1fdb 
**Output of brew doctor** | Your system is ready to brew.

**Comment by designsimply** [comment]
Just realized I cannot re-open #1998 myself. Should I create a new issue?

**Comment by ablyler** [comment]
@designsimply: no worries, I re-opened. what is the output of `ls -l /usr/lib/libz*` and `ls -l /usr/local/lib/libz*`?

**Comment by designsimply** [comment]
Thanks for re-opening!

```
↪ ls -l /usr/lib/libz*                                                                                                                               [127] ✘
lrwxr-xr-x  1 root  wheel      12 Nov 12  2014 /usr/lib/libz.1.1.3.dylib -> libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Nov 12  2014 /usr/lib/libz.1.2.5.dylib -> libz.1.dylib
-rwxr-xr-x  1 root  wheel  169312 Sep  9  2014 /usr/lib/libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Nov 12  2014 /usr/lib/libz.dylib -> libz.1.dylib
                                                                                                                                                            
↪ ls -l /usr/local/lib/libz*
lrwxr-xr-x  1 designsimply  admin  34 Aug 22 15:51 /usr/local/lib/libzip -> ../Cellar/libzip/0.11.2/lib/libzip
lrwxr-xr-x  1 designsimply  admin  42 Aug 22 15:51 /usr/local/lib/libzip.2.dylib -> ../Cellar/libzip/0.11.2/lib/libzip.2.dylib
lrwxr-xr-x  1 designsimply  admin  36 Aug 22 15:51 /usr/local/lib/libzip.a -> ../Cellar/libzip/0.11.2/lib/libzip.a
lrwxr-xr-x  1 designsimply  admin  40 Aug 22 15:51 /usr/local/lib/libzip.dylib -> ../Cellar/libzip/0.11.2/lib/libzip.dylib
```

**Comment by ezrohir** [comment]
I have the same problem in OS X version 10.10.5. 
when i restalled xcode-select,everything is OK.

**Comment by bcalik** [comment]
Same problem here.
I have a fresh installation of El Capitan Beta 7.
I have installed XCode 7 Beta 6.

Here is the xcode-select output:
```
$ xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer
````

brew doctor says `You are using OS X 10.11`, nothing else.

Here is the install php56 output:

```
$ brew install php56
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.6.12.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.12
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.12 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by koraktor** [comment]
@bcalik Thanks for the `brew reinstall` hint. Had the same problems.

**Comment by spicyjack** [comment]
Any chance this can be re-opened?

`$ brew install php54 --with-postgresql
==> Installing php54 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.4.45.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php54-5.4.45
==> ./configure --prefix=/usr/local/Cellar/php54/5.4.45 --localstatedir=/usr/loc
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz`

It seems like the headers installed with the command line tools can't be found when brew goes to compile something; I've verified the headers for zlib exist in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/

I can sort of work around this by compiling PHP using `brew install --interactive`, but I'd have to `brew link --force` a bunch of stuff, then change the `./configure` line for PHP in order for PHP to find everything.

OS X 10.10.5
Xcode command line tools version 6.4, as verified via Xcode preferences

`$ xcode-select -p
/Applications/Xcode.app/Contents/Developer`

`$ ls -l /usr/lib/libz* /usr/local/lib/libz*
ls: /usr/local/lib/libz*: No such file or directory
lrwxr-xr-x  1 root  wheel      12 Jan 28  2015 /usr/lib/libz.1.1.3.dylib -> libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Jan 28  2015 /usr/lib/libz.1.2.5.dylib -> libz.1.dylib
-rwxr-xr-x  1 root  wheel  169312 Sep  9  2014 /usr/lib/libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Jan 28  2015 /usr/lib/libz.dylib -> libz.1.dylib`

`$ brew doctor
Your system is ready to brew.`

`$ ls -l /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/zlib.h
-rw-r--r--  1 root  wheel  80511 Sep  9  2014 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/zlib.h`

**Comment by spicyjack** [comment]
**WARNING** Dirty hack ahead; it's very unclean, but it works

Symlinking the include directory to `/usr/include` allowed PHP 5.4 to compile and install without any extra magick beyond having the correct dependencies installed.

    # create symlink
    sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include /usr
    # view the symlink with:
    ls -l /usr
    # install PHP 5.4
    brew install php54 --with-postgresql
    # remove the symlink when you're done, PLEASE!
    sudo rm /usr/include

**Comment by christoph-kluge** [comment]
Also another way to fix: 
`brew untap josegonzalez/homebrew-php && brew tap homebrew/homebrew-php`

I had the same issue and since I had still josegonzale's php-formulas tapped I had simply to untap it and use the official homebrew formulas

**Comment by cpanxaoc** [comment]
That's assuming the `josegonzales` tap was enabled on your machine.  On my machine, it wasn't.

**Comment by Potato83** [comment]
Any other ideas on this? I've tried all the things... still I get:

brew install --without-apache --with-fpm --with-mysql php56

checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

I'm on El Capitan, Xcode and CLT are installed and up to date.

**Comment by ablyler** [comment]
@Potato83 please open a new issue instead of posting on this closed one.

**Comment by dennislan** [comment]
@christoph-kluge  Also another way to fix: 
brew untap josegonzalez/homebrew-php && brew tap homebrew/homebrew-php

Solve my problem, thanks
