### ISSUE TITLE
apache fails to start after installing php56

### ISSUE THREAD

**Issue by steowens** [Homebrew/homebrew-php#2004]
<pre>
root# brew install php56 --with-mysql --with-homebrew-apache --with-fpm
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-php/php56-5.6.12.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-5.6.12.yosemite.bottle.tar.gz
==> Pouring php56-5.6.12.yosemite.bottle.tar.gz
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php5_module    /usr/local/opt/php56/libexec/apache2/libphp5.so

The php.ini file can be found in:
    /usr/local/etc/php/5.6/php.ini

✩✩✩✩ PEAR ✩✩✩✩

If PEAR complains about permissions, 'fix' the default PEAR permissions and config:
    chmod -R ug+w /usr/local/Cellar/php56/5.6.12/lib/php
    pear config-set php_ini /usr/local/etc/php/5.6/php.ini system

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP56 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

✩✩✩✩ FPM ✩✩✩✩

To launch php-fpm on startup:
    mkdir -p ~/Library/LaunchAgents
    cp /usr/local/opt/php56/homebrew.mxcl.php56.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php56.plist

The control script is located at /usr/local/opt/php56/sbin/php56-fpm

OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:

  PATH="/usr/local/sbin:$PATH"

You may also need to edit the plist to use the correct "UserName".

Please note that the plist was called 'homebrew-php.josegonzalez.php56.plist' in old versions
of this formula.

To have launchd start homebrew/php/php56 at login:
  ln -sfv /usr/local/opt/php56/*.plist ~/Library/LaunchAgents
Then to load homebrew/php/php56 now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php56.plist
==> Summary
🍺  /usr/local/Cellar/php56/5.6.12: 501 files, 52M
root# apachectl restart
httpd: Syntax error on line 118 of /usr/local/etc/apache2/2.2/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.12/libexec/apache2/libphp5.so into server: dlopen(/usr/local/Cellar/php56/5.6.12/libexec/apache2/libphp5.so, 10): Symbol not found: _ap_unixd_config\n  Referenced from: /usr/local/Cellar/php56/5.6.12/libexec/apache2/libphp5.so\n  Expected in: /usr/local/Cellar/httpd22/2.2.31/bin/httpd\n in /usr/local/Cellar/php56/5.6.12/libexec/apache2/libphp5.so
root# vi /etc/apache2/httpd.conf
</pre>

**Comment by steowens** [comment]
In /usr/local/etc/apache2/2.2/httpd.conf
<pre>
LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so
</pre>

**Comment by ablyler** [comment]
@steowens did you install apache from homebrew as well?

**Comment by ablyler** [comment]
@steowens are you still having issues?

**Comment by steowens** [comment]
I think I have it worked out. Thank you for the follow up.
