### ISSUE TITLE
No available formula and please tap

### ISSUE THREAD

**Issue by runepiper** [Homebrew/homebrew-php#2006]
Sorry for the bad headline :smile: 
Every time I open up my Terminal this message appears:
```
Error: No available formula for runepiper/php/php55 
Please tap it and then try again: brew tap runepiper/php
```
I tried to tap them but it's simply not possible. How can I get rid of this?

**Comment by josegonzalez** [comment]
Sounds like you're trying to install a formula in your bash config or similar. Might want to take a look at that.

**Comment by runepiper** [comment]
Hmm not deliberately. How can I fix that?

**Comment by josegonzalez** [comment]
Search through your preferred shell's config files.

**Comment by runepiper** [comment]
You gave me the right tip. In ~/.bash_profile I found a line which was pointing to something that didn't exists. Thanks!
