### ISSUE TITLE
Can't upgrade php to 5.5.28 on 10.10

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew-php#2032]
_From @caiofbpa on September 4, 2015 2:40_

Here are the gist-logs: https://gist.github.com/anonymous/d0916bf63ed0a43da718

_Copied from original issue: Homebrew/homebrew#43566_

**Comment by caiofbpa** [comment]
Thanks @mistydemeo. I meant 10.11, I'm on the public beta.

**Comment by mistydemeo** [comment]
Try upgrading to Xcode 7. You can't build most software on 10.11 with Xcode 6.

**Comment by javian** [comment]
@caiofbpa did this get resolved ?

**Comment by caiofbpa** [comment]
Yes it works now.
