### ISSUE TITLE
Cannot find libz

### ISSUE THREAD

**Issue by liulingfree** [Homebrew/homebrew-php#2033]
i have a error when i install php56,this is the information:
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by mxi1** [comment]
I encountered the same issue when trying to install php55, which says
```
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz
```

Actually, zlib has already been installed.
```
brew search zlib
homebrew/dupes/zlib (installed)	   lzlib (installed)
```

Thanks.

**Comment by ablyler** [comment]
@liulingfree / @mxi1 can you try this: `sudo xcode-select -s /Library/Developer/CommandLineTools`

**Comment by jeffgeorge** [comment]
I was having this same issue and it looks like it was because I was still using the CLI Tools from the Xcode Beta app as `xcode-select -p` was returning `/Applications/Xcode-beta.app/Contents/Developer`.

`sudo xcode-select --install && sudo xcode-select -s /Library/Developer/CommandLineTools` got it sorted for me, php 5.5.29 installs fine now.

**Comment by Zifius** [comment]
Can confirm that getting Command Line Tools for XCode 7 GM solves the issue

**Comment by liulingfree** [comment]
@ablyler It's Perfect solution

**Comment by andrewtch** [comment]
Fixes just running sudo xcode-select --install , thanks

**Comment by sesser** [comment]
Ditto to what @andrewtch said.

**Comment by Drarok** [comment]
:+1: `xcode-select --install` fixed for me, too.

**Comment by Era2016** [comment]
it really works !!

**Comment by milkolori** [comment]
It worked for me too. Thanks!

**Comment by claudioviola** [comment]
Works for me. oSx El Capitan 10.11.5

**Comment by lferro9000** [comment]
I had this same issue with a fresh install of brew / xcode.

The strange thing is that when i typed brew doctor, the output didn't warned of any issue with the system.

Perhaps this should be added into the brew doctor validations?
