### ISSUE TITLE
how to test extension?

### ISSUE THREAD

**Issue by jk2K** [Homebrew/homebrew-php#2057]
https://github.com/Homebrew/homebrew-php#php-extension-definitions

I don't understand these words
> Before testing the extension, you will need run the command brew tap --repair to create a symlink in $HOMEBREW_PREFIX/Library/Formula

can show an example of how to add extensions?
I don't know how to test my extensions can be installed correctly

**Comment by jk2K** [comment]
I found the solution of testing extension
`brew install path/to/homebrew-php/the-formula-you-want-to-test.rb`

but i still don't know what effect  this comand `brew tap --repair`

**Comment by ablyler** [comment]
@jk2K honestly, I just edit the formula in place now.
