### ISSUE TITLE
PHP 5.4.45 upgrade bug osx 10.10

### ISSUE THREAD

**Issue by azertys** [Homebrew/homebrew-php#2059]
After upgrading to PHP 5.4.45 from 5.4.43 i'm getting: 
```
httpd: Syntax error on line 169 of /private/etc/apache2/httpd.conf: Cannot load 
/usr/local/opt/php54/libexec/apache2/libphp5.so into server: 
dlopen(/usr/local/opt/php54/libexec/apache2/libphp5.so, 10): Library not loaded: 
/usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: 
/usr/local/opt/php54/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so 
requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

Reverting to the previous version seems to fix it, but can't use the latest one. I'm using the latest version of `libxml2.2` from brew.

**Comment by michael-harvey** [comment]
Seeing same issue here with php54, php55 & php56.

**Comment by ablyler** [comment]
@azertys @michael-harvey can you run:
```
brew update
brew upgrade libxml2
```

**Comment by azertys** [comment]
@ablyler I'm getting `Error: libxml2 2.9.2 already installed` when trying that.

**Comment by jrockowitz** [comment]
I am seeing the same issue. Here is my list of installed packages. Does anyone see anything that stands out?

autoconf 2.69
automake 1.15
bash-completion 1.3
brew-cask 0.56.0
composer 1.0.0-alpha10
dialog 1.2-20150528
fontconfig 2.11.1
freetype 2.6_1
gdbm 1.11
gettext 0.19.5.1
ghostscript 9.16
gnupg 1.4.19
icu4c 55.1
jbig2dec 0.12
jenkins 1.629
jpeg 8d
libevent 2.0.22
libgpg-error 1.20_1
libksba 1.3.3
libpng 1.6.18
libtiff 4.0.6
libtool 2.4.6
libxml2 2.9.2
libyaml 0.1.6_1
little-cms2 2.7
mcrypt 2.6.8
memcached 1.4.24
mhash 0.9.9.9
mysql 5.6.26
node 0.12.7_1
openmotif 2.3.4
openssl 1.0.2d_1
pcre 8.37
php55 5.5.29_2
php55-mcrypt 5.5.29
php55-memcache 2.2.7
php55-opcache 5.5.29
php55-tidy 5.5.29_2
php55-twig 1.16.2
php55-uploadprogress 1.0.3.1
php55-xdebug 2.3.3
php55-xhprof 254eb24
phpmyadmin 4.4.11
pkg-config 0.28
pv 1.6.0
python 2.7.10_2
readline 6.3.8
rename 1.600
sqlite 3.8.11.1
tidy-html5 5.0.0
tree 1.7.0
unixodbc 2.3.2_1
varnish 4.0.3
wget 1.16.3
xpdf 3.04_1
xz 5.2.1

**Comment by ablyler** [comment]
@azertys @jrockowitz what does `otool -L /usr/local/bin/php` return?

**Comment by azertys** [comment]
@ablyler 
```
/usr/local/bin/php:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libpam.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
	/usr/local/lib/libpng16.16.dylib (compatibility version 35.0.0, current version 35.0.0)
	/usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.2.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.0.0)
	/usr/local/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

Weirdly enough i do have version 12 of libxml2 apparently. 
Managed to get this working by running:
`brew remove php54`
`brew uninstall --force php54`
`brew install php54`

What i did before getting this bug was running a `brew update brew upgrade` which updated all my packages. So php54 must have gotten updated first and installed using the old libxml2 which triggered my initial issue. So maybe a bug in the php54 dependencies?

**Comment by ablyler** [comment]
@azertys maybe, I also added a new revision of the php formulas last night to create bottles for OS X 10.11, maybe that also helped.

**Comment by jrockowitz** [comment]
My versions seem correct but I am still having getting the warning after doing a complete reinstall of php55. I am installing `brew install php55 --with-mysql --with-intl`. The issue started to happen with `php55 5.5.29_2` and `php55 5.5.29` was okay. Still @azertys solutions makes sense, just not working for me.  BTW, apache is still loading fine so this is not a critical issue.


    /usr/local/bin/php:
      /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
      /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
      /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
      /usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
      /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
      /usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
      /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
      /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
      /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
      /usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
      /usr/local/lib/libpng16.16.dylib (compatibility version 35.0.0, current version 35.0.0)
      /usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
      /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
      /usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
      /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
      /usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.2.0)
      /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
      /usr/local/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.0.0)
      /usr/local/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
      /usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
      /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)

**Comment by jrockowitz** [comment]
Using a completely new VM of OSX 10.10.5, I am able to duplicate this issue using the below steps.

    # Install Homebrew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
    brew tap homebrew/php
    
    # Install PHP
    brew install php55
    
    # Add PHP extension to OSX Apache
    sudo sed -i -- "s|\#LoadModule php5_module libexec/apache2/libphp5.so|LoadModule php5_module /usr/local/opt/php55/libexec/apache2/libphp5.so|g" /etc/apache2/httpd.conf
    
    # Restart Apache
    sudo apachectl -e info -k restart

I have snapshot of the VM before executing the above code so If needed I can repeat these steps with any additional debugging or verbose options.

**Comment by ablyler** [comment]
@jrockowitz can you run: `otool -L /usr/local/opt/php55/libexec/apache2/libphp5.so`?

**Comment by jp7jp** [comment]
Hello @ablyler, I got the same problem here after upgrading from PHP 5.5.28 to 5.5.29_2:

```
/usr/local/opt/php55/libexec/apache2/libphp5.so:
	/usr/lib/libaprutil-1.0.dylib (compatibility version 4.0.0, current version 4.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 168.2.0)
	/usr/lib/libapr-1.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
	/usr/local/lib/libpng16.16.dylib (compatibility version 35.0.0, current version 35.0.0)
	/usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.2.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.0.0)
	/usr/local/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

OS X 10.10.5

**Comment by jrockowitz** [comment]
It is the same as before and as @jp7jp output

**Comment by adriantombu** [comment]
Hi guys, same problem here with php 5.6.13, even though libxml2 seems properly installed

`/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.2.0)`

**Comment by azertys** [comment]
The problems returned for me too after updating to php 5.4.45_2. Dig a little deeper and i think the problem has to do with the version of apache and not the php installation itself. I'm using apache 2.4 that comes installed with Yosemite which is compiled against libxml2 version 10. 
Since i installed libxml 2 with brew and forced linked it, i don't have the original version of libxml that came with Yosemite anymore.
The only solution for me is to install the httpd 2.4 package from brew as it will get compiled with the same version of libxml2 as php.
Noticed that in the past there were these checks in the repo that could prevent the current issue: https://github.com/Homebrew/homebrew-php/pull/449/files
Haven't tested that though.

**Comment by lark1n** [comment]
Hi! I have the same problem :(

**Comment by ablyler** [comment]
I'm working on a fix for this, I believe it was https://github.com/Homebrew/homebrew-php/commit/0ba8cfa899cb32777a84c7b7e80e1c6c9893dfff that is causing this issue.  I'm in the process of testing reverting this change.

**Comment by rdohms** [comment]
@ablyler any progress? just ran into this today as well, as you were typing the last comment :P

**Comment by tonylegrone** [comment]
I've been having the same issue. I finally broke down and ran `brew install homebrew/apache/httpd22 --with-privileged-ports` and that has worked around the issue.

**Comment by ablyler** [comment]
I'm making progress, I reverted that commit and @jrockowitz 's test now passed, however php won't compile on OS X 10.11 now (https://github.com/Homebrew/homebrew-php/issues/1931).  Working on finding out if depending on libxml2 for OS X 10.11 or above is the answer.

**Comment by ablyler** [comment]
If anyone wants to help test this run the following:

```
cd /usr/local/Library/Taps/homebrew/homebrew-php
git fetch origin pull/2257/head:libxml-fix
git checkout libxml-fix
brew install php55
```

I'm currently testing this on OS X 10.9-10.11.

**Comment by jrockowitz** [comment]
I can confirm that your fix works on 10.10.5 using the below steps

  # Install Homebrew
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
  brew tap homebrew/php

  # Switch to fix
  cd /usr/local/Library/Taps/homebrew/homebrew-php
  git fetch origin pull/2257/head:libxml-fix
  git checkout libxml-fix

  # Install PHP
  brew install php55

  # Add PHP extension to OSX Apache
  sudo sed -i -- "s|\#LoadModule php5_module libexec/apache2/libphp5.so|LoadModule php5_module /usr/local/opt/php55/libexec/apache2/libphp5.so|g" /etc/apache2/httpd.conf

  # Restart Apache
  sudo apachectl -e info -k restart

**Comment by ablyler** [comment]
@jrockowitz thanks! I'll merge this change in as soon as brew bot finishes building the bottles.

**Comment by ablyler** [comment]
@jrockowitz published!

**Comment by lark1n** [comment]
:+1:

**Comment by rdohms** [comment]
uhu... i'm still having this with 5.6 on 10.10.5 .. going to investigate a bit more.

**Comment by rdohms** [comment]
ok got it! nice, thanks!

**Comment by andreij** [comment]
Did on Osx. 10.11:

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
brew tap homebrew/php

# Switch to fix
cd /usr/local/Library/Taps/homebrew/homebrew-php
git fetch origin pull/2257/head:libxml-fix
git checkout libxml-fix

# Install PHP
brew install php55

# Add PHP extension to OSX Apache
sudo sed -i -- "s|#LoadModule php5_module libexec/apache2/libphp5.so|LoadModule php5_module /usr/local/opt/php55/libexec/apache2/libphp5.so|g" /etc/apache2/httpd.conf

# Restart Apache
sudo apachectl -e info -k restart

But I got the same error:

httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php55/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php55/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php55/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

**Comment by ablyler** [comment]
@andreij please open a new issue
