### ISSUE TITLE
php54-pcntl-Symbol not found: _zend_sigaction

### ISSUE THREAD

**Issue by future5985** [Homebrew/homebrew-php#2255]
OS X10.9.5
php.ini appeared：pcntl support	enabled

But when I try to launch something using php54-pcntl , I fetch this error message :

"
dyld: lazy symbol binding failed: Symbol not found: _zend_sigaction
  Referenced from: /usr/local/Cellar/php54/5.4.45/lib/php/extensions/no-debug-non-zts-20100525/pcntl.so
  Expected in: flat namespace

dyld: Symbol not found: _zend_sigaction
  Referenced from: /usr/local/Cellar/php54/5.4.45/lib/php/extensions/no-debug-non-zts-20100525/pcntl.so
  Expected in: flat namespace

Trace/BPT trap: 5
"

Is there a similar problem?

I have read this：https://github.com/Homebrew/homebrew-php/issues/1661
My pcntl install by make & make install, 1661 is not my solution.

**Comment by future5985** [comment]
The issue is solved，thanks all.

**Comment by yjm12321** [comment]
Hi, I also fetch this error message, how do you solve it?
