### ISSUE TITLE
Problems with libxml (10.10.5 (14F27))

### ISSUE THREAD

**Issue by frederikbosch** [Homebrew/homebrew-php#2256]
Since this morning we have problems with PHP and LibXML on OSX. We have a custom stream wrapper that we are using within a XSL file. Using those streams are failing now, with PHP complaining on `I/O warning : failed to load external entity`.

When I searched through the recent commits, I came across [this recent issue](https://github.com/Homebrew/homebrew-php/issues/1941). Maybe that fix is the source of this issue. In order to replicate behaviour.

In order to replicate the issue, use the following files.

[xsltest.php](https://gist.github.com/frederikbosch/f71c28398d355ae6d556)
[xsltest.xsl](https://gist.github.com/frederikbosch/1ab478e6c31ff8094a34)
[xsltest2.xsl](https://gist.github.com/frederikbosch/a0ff8043d6189d3a8c28)

Expected result:
<?xml version="1.0"?>
test

Actual result:
I/O warning : failed to load external entity "xsltpl://xsltest2.xsl"
PHP Warning:  XSLTProcessor::transformToXml(): No stylesheet associated to this object in /Users/Genkgo/xsltest.php on line 70

When switching to [this commit](https://github.com/Homebrew/homebrew-php/commits/aa0c970), it works from cli, but not from http. I am now trying to go back to the version where it works in both.

**Comment by frederikbosch** [comment]
Forget the remark that it works with cli and does not work with http. That was our own linking problem.

**Comment by frederikbosch** [comment]
The error starts from [this commit](https://github.com/Homebrew/homebrew-php/commit/3712fa222f4feb7de7acdd99fd4fa11097bf9b62). There is no problem with [this commit](https://github.com/Homebrew/homebrew-php/commit/80c84d71bc196d3b01f09b24b0b8d9dbba39920d).

**Comment by adriantombu** [comment]
Same problem... Can we use a previous version until this is fixed ? (and how to revert ?)

**Comment by frederikbosch** [comment]
@adriantombu You should switch back homebrew-php to [this commit](https://github.com/Homebrew/homebrew-php/commit/80c84d71bc196d3b01f09b24b0b8d9dbba39920d) and then install php 5.6.

**Comment by adriantombu** [comment]
@frederikbosch Sorry to ask, but how can I achieve to do that ? I've never done that before * feels nooby *

**Comment by tonijn** [comment]
You can go back to the latest working version of homebrew-php:

```bash
cd /usr/local/Library/Taps/homebrew/homebrew-php/Formula
git checkout 80c84d71bc196d3b01f09b24b0b8d9dbba39920d
brew reinstall php56
```

don't forget to restart apache afterwards

**Comment by adriantombu** [comment]
Works like a charm ! Thanks a lot :)

Any idea of what causes this problem ?

**Comment by frederikbosch** [comment]
@adriantombu We have no idea to be honest. I guess it has to with how to compile libxml. There is also [an issue with HHVM and `xsl:include`](https://github.com/facebook/hhvm/issues/2593), maybe it is related.

**Comment by ablyler** [comment]
@frederikbosch / @adriantombu should be fixed now, `brew update`

**Comment by adriantombu** [comment]
That's perfect ! Let me give you a virtual beer :beer:

**Comment by frederikbosch** [comment]
@ablyler Thanks for the quick fix!
