### ISSUE TITLE
Installing php55-memcache with --devel flag leads to: Error: SHA1 mismatch

### ISSUE THREAD

**Issue by jessegreathouse** [Homebrew/homebrew-php#2279]
I needed to install the 3.x+ version of php-memcache extension on my other dev machine. I did this with one dev machine a week ago, which had no trouble, and now when I'm trying to do it this week. I find that there is a sha1 mismatch in the downloaded tarball from pecl. I suspect that the tarball package changed without an according change to the recipe. It's repeatable so I know it's not a corrupted download.

jgreathouse-mbp:Formula jgreathouse$ brew install homebrew/php/php55-memcache --devel
==> Installing php55-memcache from homebrew/homebrew-php
==> Downloading https://pecl.php.net/get/memcache-3.0.8.tgz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 2cae5b423ffbfd33a259829849f6000d4db018debe3e29ecf3056f06642e8311
Actual: 681ece0258958d60902d6bbf0cf1f2171a0cc47c
Archive: /Library/Caches/Homebrew/php55-memcache-3.0.8.tgz
To retry an incomplete download, remove the file above.

**Comment by ablyler** [comment]
@jessegreathouse try to `brew update` and then install again. I just fixed that issue in commit 7d03c8a.

**Comment by jessegreathouse** [comment]
Thanks Ablyler works perfect now!
