### ISSUE TITLE
Installing composer tries to install php56 and fails even when you have other PHP versions installed

### ISSUE THREAD

**Issue by BrianGilbert** [Homebrew/homebrew-php#2437]
To my knowledge composer works fine with php53/54/55? 

Cause seems to be in https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb  I think line 4 may be forcing php56 as requirement?

```
==> Installing composer from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/composer: php56
==> Installing homebrew/php/composer dependency: php56
Error: Cannot install homebrew/php/php56 because conflicting formulae are installed.

  php55: because different php versions install the same binaries.

Please `brew unlink php55` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

**Comment by Zifius** [comment]
This is actually the same for all *.phar formulas. Reported this to @ablyler in the Codeception PR

**Comment by michaeljs1990** [comment]
experiencing same issue once I upgraded homebrew.... looks like default doesn't work properly.

**Comment by michaeljs1990** [comment]
https://github.com/Homebrew/homebrew-php/pull/2453 fixes this issue. Although a better solution will likely be needed this was just a quick fix so it's noticed.

**Comment by javian** [comment]
This should now have been fixed through https://github.com/Homebrew/homebrew-php/commit/113588af7f99cea480ff0932fc8b5575f8500137 and further updates of the meta requirements code.
