### ISSUE TITLE
php56 failed to build on 10.11

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-php#2439]
_From @jweaver60 on October 7, 2015 1:22_

php56 can't upgrade after updating to 10.11

https://gist.github.com/6c2d5157fb279fcd1ff8

_Copied from original issue: Homebrew/homebrew#44689_

**Comment by jweaver60** [comment]
I forgot to run `code-select --install` after upgrading to 10.11. Go ahead and close this.

**Comment by DomT4** [comment]
Thanks for following up! :smiley:
