### ISSUE TITLE
Every update of php56 force me to reinstall php56-intl and php56-mcrypt with --build-from-source

### ISSUE THREAD

**Issue by zoff** [Homebrew/homebrew-php#2440]
I'm using php56-intl and php56-mcrypt but every time I update php56 I get this message every time I use php:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php56-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php56-intl/intl.so in Unknown on line 0
PHP Warning:  PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,TS
These options need to match
 in Unknown on line 0
PHP 5.6.14 (cli) (built: Oct  7 2015 10:06:05) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```
To get rid of this I need to reinstall php56-intl and php56-mcrypt with --build-from-source.
A simple reinstallation doesn't work.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.5
**Homebrew Version:** | Homebrew 0.9.5 (git revision 7b25a; last commit 2015-10-07)
**PHP Version in use:** | 5.6
**Xcode Version:** | 7.0.1 (7A1001)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 7.0.0 (clang-700.0.72)
**Output of php -v:** | PHP 5.6.14 (cli) (built: Oct  7 2015 10:06:05)
**Output of brew doctor** | Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

**Comment by lslucas** [comment]
Same with me, but I also have problems with other modules: php56-mongo php56-memcached php56-memcache

I upgraded xcode and xcode command line tools to the last version and still have the same problem.

**Comment by ablyler** [comment]
@zoff @lslucas do you both have php installed with threading enabled?  I think that is what is causing the breakage with the bottles.

**Comment by zoff** [comment]
@ablyler I used default options. Is it enabled by default?

**Comment by lslucas** [comment]
@ablyler yes! I had problems trying install with threads and also without threads but with zts. Both ways had errors, then I let it go and installed php56 default way `brew install php56` only with that this works, but no threads :(

Note: I also tried php55 with threads and neither this way worked.

**Comment by 47ronin** [comment]
Btw if you're curious, this is also happening with Homebrew php70… gotta:
`brew reinstall php70-mcrypt --build-from-source`

**Comment by tixastronauta** [comment]
Same here!

**Comment by Pierstoval** [comment]
Same here for php 5.6 and php 7.0, and even the apache handler does not work anymore...

**Comment by chrisarusso** [comment]
Yes, I just did the same as @47ronin recommends with php 5.6 and it worked. Thanks!

**Comment by qidolihaku** [comment]
Same problem here, When can you fix it ?

**Comment by Pierstoval** [comment]
For the ones that can't install, most of the time a reinstall using `--build-from-source` will work, but its very strange :confused:

**Comment by ahmadrais** [comment]
i did same as @47ronin for php56 and it worked.

**Comment by josegonzalez** [comment]
Bottles are not compiled with any additional php options you might have so you need to install the formula with `brew install --build-from-source php56-WHATEVER` and then it should work.

**Comment by holtkamp** [comment]
Also mentioned here https://github.com/Homebrew/homebrew-php/issues/2544

**Comment by angelxaces** [comment]
I'm having this problem at the moment and I've found that `--build-from-source` works out and I think I know why.

If you installed something prior with `--build-from-source` or if that was active in your environment `HOMEBREW_BUILD_FROM_SOURCE` you'll likely have this problem. Everything has to be compiled the same way so there's a good chance different options would use different compilers.

Also, we've all been beginners before and probably remember at some point rushing through and copy/pasting thing stuff we should read aout, especially our flags...
did anyone copy/paste something like this, `$ brew install -s ...` by chance? 
Same thing as `$ brew install --build-from-source`

I hope it helps someone

**Comment by diazwatson** [comment]
@47ronin comment solved my problem
