### ISSUE TITLE
add AddType in httpd.conf

### ISSUE THREAD

**Issue by aoloe** [Homebrew/homebrew-php#2442]
when installing the latest php with the latest apache, the `.so` gets added to the `httpd.conf`

    LoadModule php5_module        /usr/local/Cellar/php56/5.6.14/libexec/apache2/libphp5.so

but since

    AddType application/x-httpd-php .php

is missing, php files are not recognized.

it would be helpful to add that line, too.

**Comment by aoloe** [comment]
#759 gives a solution and is closed... but has the line been added to the install process?

**Comment by javian** [comment]
According to the php documention http://php.net/manual/en/install.unix.apache2.php the sethandler should be used and as far as I can tell this is not added in the php tap so it must come from somewhere else.

**Comment by javian** [comment]
@aoloe Did you manage to resolve this ?

**Comment by aoloe** [comment]
@javian sorry, i cannot tell.

since i do not install php multiple times on this machine i cannot tell if it's solved or not.

**Comment by javian** [comment]
Thanks for your feedack. I will close this issue for now but feel free to reopen it if you bump into this again
