### ISSUE TITLE
PHP5.6 - APCU

### ISSUE THREAD

**Issue by razmo** [Homebrew/homebrew-php#2443]
I'm facing a problem with php56-apcu,
The installation of apcu for php56 (```brew install php56-apcu```) succeed but the extension is not installed.
Installation outputs:
```
==> Downloading https://homebrew.bintray.com/bottles-php/php56-apcu-4.0.7.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-apcu-4.0.7.mavericks.bottle.tar.gz
==> Pouring php56-apcu-4.0.7.mavericks.bottle.tar.gz
==> Caveats
To finish installing apcu for PHP 5.6:
  * /usr/local/etc/php/5.6/conf.d/ext-apcu.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the apcu module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the apcu module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php56-apcu/4.0.7: 6 files, 108K
```
But there is no ```ext-apcu.ini``` file in ```/usr/local/etc/php/5.6/conf.d/``` directory.
I tried to remove and reinstall but it didn't change anything.

**Comment by kynx** [comment]
I've had this one too. Manually creating the ext-acpu.ini file didn't work either - think the .so file is broken.

Worked around it by doing a `brew install --build-from-source php56-apcu` (uninstall the other one first).

**Comment by rained23** [comment]
Happen to me too, checking conf.d folder have no ext-apcu.ini included

**Comment by razmo** [comment]
I've fixed it by creating the ext-apcu.ini file and put this inside:
```
[apcu]
extension="/usr/local/opt/php56-apcu/apcu.so"
apc.enabled=1
apc.shm_size=64M
apc.ttl=7200
apc.mmap_file_mask=/tmp/apc.XXXXXX
apc.enable_cli=1
```

**Comment by ablyler** [comment]
@razmo odd, i just uninstalled, removed /usr/local/etc/php/5.6/conf.d/ext-apcu.ini, and installed again and the file was created just fine. if you follow those steps, do you get the file back?

**Comment by razmo** [comment]
@ablyler wired now it works

**Comment by Krinkle** [comment]
Same here. Latest homebrew and homebrew-php and after installing php56-apcu, the message claims to have created `/usr/local/etc/php/5.6/conf.d/ext-apcu.ini` but no such file exists. Other extensions (e.g. xdebug or xhprof) did not have any such problem and did create the file.

**Comment by 5t111111** [comment]
Same here too.

In my case, `/usr/local/etc/php/5.6/conf.d/ext-apcu.ini` is not created even when I pass `--enable-apc-bc` option to the install command.

**Comment by Sfynx** [comment]
Looks like it is not in the bottle then, because when building from source it works fine.

**Comment by x3ro** [comment]
Same issue here. When creating the config file manually, an error is thrown that apcu.so is not a valid zend extension. Thought this was related to #1654 but maybe its just the apcu recipe.

**Comment by d8bhatta** [comment]
I my case the ini file is created /usr/local/opt/php56-apcu/apcu.so but still I cannot see apcu in php.ini
$ ls -al /usr/local/etc/php/5.6/conf.d/
total 24
drwxr-xr-x  5 c_dbhatta  admin  170 Jun 13 16:36 .
drwxr-xr-x  7 c_dbhatta  admin  238 Mar 13 16:48 ..
-rw-r--r--  1 c_dbhatta  admin  149 Jun 13 16:36 ext-apcu.ini
-rw-r--r--  1 c_dbhatta  admin   62 Mar 13 16:48 ext-imagick.ini
-rw-r--r--  1 c_dbhatta  admin   59 Mar 13 16:58 ext-mcrypt.ini

**Comment by markcarver** [comment]
I suspect it may have something to do with newer operating systems too, none of the above solutions worked. However, I was able to get the following to work so it'd at least install the `.so` file. Then I just had to manually create the PHP ini file:

`brew install php56-apcu --with-apc-bc --without-config-file`
