### ISSUE TITLE
Os X 10.11 Incompatible library version: libphp5.so

### ISSUE THREAD

**Issue by andreij** [Homebrew/homebrew-php#2446]
I Did on Os X 10.11. I have Apache shipped with Os and tried to install PHP5.5 (actually I guess that a brew update broke the previous working configuration).

I uninstalled brew and tried:

> ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
> brew tap homebrew/php
> cd /usr/local/Library/Taps/homebrew/homebrew-php
> git fetch origin pull/2257/head:libxml-fix
> git checkout libxml-fix
> brew install php55
> sudo sed -i -- "s|#LoadModule php5_module libexec/apache2/libphp5.so|LoadModule php5_module > /usr/local/opt/php55/libexec/apache2/libphp5.so|g" /etc/apache2/httpd.conf
> sudo apachectl -e info -k restart

I also tried:

> brew install php55 --compile-from-source

But I got the same error:

httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php55/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php55/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php55/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

**Comment by bipinu** [comment]
Can confirm with php56.
Seems like a repeat offender #2059

**Comment by ablyler** [comment]
@andreij / @bipinu can you guys try: `xcode-select --install`?

**Comment by andreij** [comment]
On my side it was already installed. Btw I solved the issue by brew install httpd24 .

**Comment by bipinu** [comment]
@ablyler Yeah, we had xcode installed as well.
I haven't visited the machine again. I'll update in a couple of days.

**Comment by ablyler** [comment]
@bipinu okay, still try that command line snippet I provided.  It will install some core libraries that xcode doesn't always install by default.

**Comment by ddoonn** [comment]
@ablyler @bipinu trying: <code> xcode-select --install</code>produced: <code>  xcode-select: error: command line tools are already installed, use "Software Update" to install updates </code> 

I then removed libmxl2 and reinstalled:
<code>brew update </code>
<code>brew uninstall libxml2</code>
<code>brew install libxml2 --with-xml2-config</code>
<code>brew link --force libxml2  </code>

This seems to have fixed it, though the result of 
<code> ls -l /usr/lib/libxml* </code>
is:
<code>-rwxr-xr-x  1 root  wheel  2395024 Sep 17 09:07 /usr/lib/<strong>libxml2.2.dylib</strong></code>
<code>lrwxr-xr-x  1 root  wheel       15 Sep 30 21:57 /usr/lib/libxml2.dylib -> libxml2.2.dylib</code>

Seems to be the same version number in the original result from <code> apachectl -t </code>:

<code>httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but <strong>libxml2.2.dylib</strong> provides version 10.0.0</code>

Anyway this has seemed to fixed any issues I was having with OSX 10.11 and php56

**Comment by bipinu** [comment]
Just for the note, I was following on behalf of @ddoonn's machine. So you may consider this resolved.

Thanks for the good work.

**Comment by humblecoder** [comment]
Apologies for being late to the party and potentially beating a dead horse, but I'm still unable to successfully load libxml2.  I have the following configuration:

-Mac OS X 10.11.1
-Apache/2.4.16 (Unix) (Server built:   Aug 22 2015 16:51:57)
-PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:34)

I performed the following steps, to no avail:

```
brew uninstall libxml2
brew uninstall --force php56
brew install libxml2 --with-xml-config
brew link --force libxml2
brew install php56
```

Running `apachectl -t` still results in:

```
httpd: Syntax error on line 173 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so into server: dlopen(/usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

**Comment by nkalvi** [comment]
Seeing the same problem as @humblecoder on a similar setup - @ablyler could you please reopen the issue?

**Comment by cytopia** [comment]
I can also confirm the same issue today

**Comment by tarunhere** [comment]
I am facing the same problem: I updated the brew by: brew update. Also in morning I installed phpunit

httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so

I had reset all these, also tried installing brew install httpd24. But then my current sites were not working. I tried to set the necessary settings in httpd.conf file. But it was of no use.
Finally I uninstalled httpd24 and again I got my old syntax error on line 170.

Any help/suggestion would be highly appreciated. My work had stopped in between and I don't have any other system.

I have mac os 10.10.5

I also tried reinstalling php and all. but no luck!!
Please help.
