### ISSUE TITLE
Can't install php56-redis

### ISSUE THREAD

**Issue by dunpeal** [Homebrew/homebrew-php#2450]
Hello! I can't install php56-redis

tvildanov:/d$ brew install php56-redis
Error: Formulae found in multiple taps: 
 * homebrew/php/php56-redis
 * josegonzalez/php/php56-redis

Please use the fully-qualified name e.g. homebrew/php/php56-redis to refer the formula.

$ brew install homebrew/php/php56-redis
==> Installing php56-redis from homebrew/homebrew-php
Error: Formulae found in multiple taps: 
 * homebrew/php/php56
 * josegonzalez/php/php56

Please use the fully-qualified name e.g. homebrew/php/php56 to refer the formula.

$ brew install homebrew/php/php56
==> Installing php56 from homebrew/homebrew-php
Error: php56-5.6.12 already installed
To install this version, first `brew unlink php56'

$ sudo brew update
Already up-to-date.

$ sudo brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.5) is outdated
Please install XQuartz 2.7.7:
  https://xquartz.macosforge.org

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    mysql-connector-c
    nginx
    ossp-uuid
    php53
    php55
    phpunit
Error: Formulae found in multiple taps: 
 * homebrew/php/php55
 * josegonzalez/php/php55

Please use the fully-qualified name e.g. homebrew/php/php55 to refer the formula.

OS: 10.11 El Capitan

**Comment by ablyler** [comment]
@dunpeal please try: `brew untap josegonzalez/php`

**Comment by javian** [comment]
@dunpeal did you manage to resolve this issue ?

**Comment by dunpeal** [comment]
Yes, thanks!
