### ISSUE TITLE
Can't install php56-mcrypt

### ISSUE THREAD

**Issue by ellyliang** [Homebrew/homebrew-php#2452]
==> Installing php55-mcrypt from josegonzalez/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php55-mcrypt-5.5.30.el_capitan.bottle.

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php55-mcrypt"
Download failed: https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php55-mcrypt-5.5.30.el_capitan.bottle.2.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://php.net/get/php-5.5.30.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-mcrypt-5.5.30
==> /usr/local/opt/php55/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php55-mcrypt/5.5.30 --with-php-config=/usr/local/opt/php55/bin/php-config 
Last 15 lines from /Users/ellyliang/Library/Logs/Homebrew/php55-mcrypt/02.configure:

./configure
--prefix=/usr/local/Cellar/php55-mcrypt/5.5.30
--with-php-config=/usr/local/opt/php55/bin/php-config
--disable-dependency-tracking
--with-mcrypt=/usr/local/opt/mcrypt

configure: WARNING: unrecognized options: --disable-dependency-tracking
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking whether the C compiler works... no
configure: error: in `/private/tmp/php55-mcrypt20151012-7550-guywpz/php-5.5.30/ext/mcrypt':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/josegonzalez/homebrew-php/issues

Warning:

**Comment by brendo** [comment]
Also facing a similar issue:

==> Installing php56 from josegonzalez/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php56-5.6.14.el_capitan.bottle.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php56"
Download failed: https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php56-5.6.14.el_capitan.bottle.2.tar.gz

---

Perhaps it's a temporary server issue :)

**Comment by brunodias20** [comment]
+1

**Comment by javian** [comment]
@ellyliang did you manage to resolve this issue ?

**Comment by javian** [comment]
Closing issue due to no  response.
