### ISSUE TITLE
php 5.6 & pdo_oci

### ISSUE THREAD

**Issue by claudiu-cristea** [Homebrew/homebrew-php#2462]
After installed Instant Client 11.2.0.4 under `/usr/local/instantclient_11_2` and created all requested symlinks (see http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html), I ran:

```
$ export ORACLE_HOME="instantclient,/usr/local/instantclient_11_2,11.2.0.4"
$ brew reinstall php56 --with-pdo-oci
```

Here's the output:

```
==> Reinstalling homebrew/php/php56 with --with-pdo-oci
==> Downloading https://php.net/get/php-5.6.14.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.14
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.14 --localstatedir=/usr/loc
==> make
Last 15 lines from /Users/clau/Library/Logs/Homebrew/php56/02.make:
/private/tmp/php5620151014-62231-525ohl/php-5.6.14/ext/ldap/ldap.c:539:23: error: use of undeclared identifier 'LDAP_OPT_X_SASL_AUTHCID'
                ldap_get_option(ld, LDAP_OPT_X_SASL_AUTHCID, &ctx->authcid);
                                    ^
/private/tmp/php5620151014-62231-525ohl/php-5.6.14/ext/ldap/ldap.c:542:23: error: use of undeclared identifier 'LDAP_OPT_X_SASL_AUTHZID'
                ldap_get_option(ld, LDAP_OPT_X_SASL_AUTHZID, &ctx->authzid);
                                    ^
/private/tmp/php5620151014-62231-525ohl/php-5.6.14/ext/ldap/ldap.c:620:29: error: use of undeclared identifier 'LDAP_OPT_X_SASL_SECPROPS'
                ldap_set_option(ld->link, LDAP_OPT_X_SASL_SECPROPS, props);
                                          ^
/private/tmp/php5620151014-62231-525ohl/php-5.6.14/ext/ldap/ldap.c:623:77: error: use of undeclared identifier 'LDAP_SASL_QUIET'
        rc = ldap_sasl_interactive_bind_s(ld->link, binddn, ctx->mech, NULL, NULL, LDAP_SASL_QUIET, _php_sasl_interact, ctx);
                                                                                   ^
11 errors generated.
make: *** [ext/ldap/ldap.lo] Error 1
make: *** Waiting for unfinished jobs....
```
(removed the footer message)

Environment:

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.11
**Homebrew Version:** | Homebrew 0.9.5 (git revision bda0; last commit 2015-10-13)
**PHP Version in use:** | PHP 5.6.14
**Xcode Version:** | <your Xcode version>
**Output of gcc -v:** | Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1<br />Apple LLVM version 7.0.0 (clang-700.0.72)<br />Target: x86_64-apple-darwin15.0.0<br />Thread model: posix
**Output of php -v:** | PHP 5.6.14 (cli) (built: Oct  3 2015 14:54:13)<br />Copyright (c) 1997-2015 The PHP Group<br />Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies<br />    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/claudiu-cristea/a4d8c20bcb8f074b1676
**Output of brew doctor within a gist** | https://gist.github.com/claudiu-cristea/d2038224eb3968d27986

**Comment by claudiu-cristea** [comment]
Added the bug report to the description.

**Comment by TNAJanssen** [comment]
+1

**Comment by TNAJanssen** [comment]
@claudiu-cristea  did you already find a solution?

**Comment by javian** [comment]
There's seems to be a similar but not same issue described in https://github.com/Homebrew/homebrew-php/issues/543#issuecomment-73012945 with a proposed solution.

**Comment by javian** [comment]
Did you manage to resolve this issue @claudiu-cristea ?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update in 2+ weeks.
