### ISSUE TITLE
php 5.6.14 / mcrypt not playing nicely

### ISSUE THREAD

**Issue by stuntdawg** [Homebrew/homebrew-php#2464]
Running osx 10.11 (el capitan)
php 5.6.14
osx server app installed and running

when using the extension of mcrypt and running phpinfo() (specifically phpinfo(INFO_MODULES)), I get an:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.
Reason: Error reading from remote server

in the command line php -i, it stops at mcrypt:

mcrypt
Illegal instruction: 4

... once I remove the mcrypt extension, all errors are fixed and the php56 works normally (minus the mcrypt features)

if mcyrpt is installed, I can run php normally until I need to use mcrypt functions ... then I get the same 502 Proxy Error

i have installed and reinstalled, php56 and php56-mcrypt several times and have exceeded my ability as a noob to figure it out :(

**Comment by stuntdawg** [comment]
I finally resolved my issue and I feel stupid for not realizing it earlier.

I was focusing on uninstalling php56 and php56-mcrypt BUT I never thought of dealing with the main mcrypt install.

Once I did $ brew reinstall mcrypt everything was fine and dandy.

I'm guessing that the original mcrypt I had was for Yosemite and no el Capitan and therefore just needed to be updated!

**Comment by javian** [comment]
Glad you managed to solve it =) Closing issue.
