### ISSUE TITLE
php70-apcu

### ISSUE THREAD

**Issue by helmuthva** [Homebrew/homebrew-php#2465]
... any chance this is provided in the near future?

**Comment by ablyler** [comment]
@helmuthva currently it doesn't build for me

**Comment by sebastienbarre** [comment]
@abyler would [this](https://github.com/krakjoe/apcu/issues/129#issuecomment-138359217) or [this](https://github.com/krakjoe/apcu/issues/137#issuecomment-150760383) help? (there is a `seven` branch).
```
git checkout seven
make clean
phpize
make -j 4
sudo make install
```
