### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mgracer48** [Homebrew/homebrew-php#2471]
==> Reinstalling homebrew/php/php54 with --with-homebrew-apxs
Warning: homebrew/php/php54: --homebrew-apxs was deprecated; using --with-homebrew-apxs instead!
==> Downloading https://php.net/get/php-5.4.45.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.4.45.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php54/5.4.45_3 --localstatedir=/usr/l
Last 15 lines from /Users/mgracer48/Library/Logs/Homebrew/php54/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz
couldn't understand kern.osversion `15.0.0'

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

**Comment by jenkoian** [comment]
Run this: `xcode-select --install`
Try again
