### ISSUE TITLE
Upgrading php54 bottle error -- kernel 15.0.0 not recognized

### ISSUE THREAD

**Issue by weems** [Homebrew/homebrew-php#2479]
brew upgrade attempts to upgrade php54 bottle results in a ./configure error -- 'couldn't understand kern.osversion `15.0.0''

Thanks

**Comment by javian** [comment]
@weems is this still an issue ?

**Comment by cgardner** [comment]
I just ran across this error.

I went through the [Troubleshooting](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) directions and it started working after I installed the newest XCode Command Line Tools.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update in 2+ weeks.
