### ISSUE TITLE
phpunit 5.0.0 fails on php < 5.6

### ISSUE THREAD

**Issue by timheilig** [Homebrew/homebrew-php#2485]
phpunit 5 can be installed view homebrew when you have a php version installed that doesn't support it.

I don't know enough about packages to figure out how to do this myself at the moment, I may investigate and throw a PR up.

**Comment by nickjanus** [comment]
I'm not sure the best way to implement that sort of check (`conflicts_with 'php56', 'php57'`?), but here's some shameless self promotion: #2621

**Comment by josegonzalez** [comment]
If you need to install phpunit, please install it via composer as a development dependency for your application.
