### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-php#2487]
_From @thefirstjustin on October 29, 2015 17:57_

I received this error while running brew reinstall php55-xdebug --build-from-source

_Copied from original issue: Homebrew/homebrew#45475_

**Comment by bfontaine** [comment]
_From @apjanke on October 29, 2015 18:35_

Can we get some more info, like the `brew gist-logs` output, and a pointer to where the `php55-xdebug` formula is from? I don't see it in the core taps.

**Comment by DomT4** [comment]
Check `brew doctor`. There are instructions there for fixing this @thefirstjustin.
