### ISSUE TITLE
PHPMyAdmin 4.5.0.2 is bugged, formulae update needed!

### ISSUE THREAD

**Issue by renatoaraujoc** [Homebrew/homebrew-php#2496]
Hello,

After updating my version of PHPMyAdmin to 4.5.0.2, lots of bugs have shown up, specially those related to ForeignKey management.

Please, someone update this formula to 4.5.1.0 as these bugs seems to be fixed there.

I'd do it myself but I have no idea how to edit these formulas correctly.

Thank you,

Renato Carneiro

**Comment by renatoaraujoc** [comment]
For those who have updated to 4.5.0.2 and are experiencing the bugs, updating these lines will do:

issue on command-line: brew edit phpmyadmin

update with: 
sha256 "3a2a990690658aaa29077776dd4b0b208278c4d0f55e801680aa0d49f4dec94d"
url "https://files.phpmyadmin.net/phpMyAdmin/4.5.1/phpMyAdmin-4.5.1-english.zip"

**Comment by ablyler** [comment]
Updated, thanks!
