### ISSUE TITLE
php54-redis

### ISSUE THREAD

**Issue by mayliupeng** [Homebrew/homebrew-php#2499]
brew -v
Homebrew 0.9.5 (git revision a01b5; last commit 2015-11-04)

php -v
PHP 5.4.45 (cli) (built: Sep  9 2015 08:10:45)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologie

brew search redis
hiredis                        homebrew/versions/redis1310
homebrew/php/php53-redis       homebrew/versions/redis24
homebrew/php/php54-redis       homebrew/versions/redis26
homebrew/php/php55-redis       homebrew/versions/redis28
homebrew/php/php56-redis       redis (installed)
homebrew/php/php70-redis       redis-leveldb

brew install php54-redis
Installing php54-redis from homebrew/homebrew-php
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:826:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:133:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:133:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:111:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:146:in `<main>'

May someone help me?

My system is MAC OS 10.10.1

**Comment by javian** [comment]
Did you manage to resolve this @mayliupeng ?

**Comment by javian** [comment]
Closed due to no response.
