### ISSUE TITLE
php55 install php55-pthreads An error

### ISSUE THREAD

**Issue by v3u3i87** [Homebrew/homebrew-php#2505]
An error :
READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/josegonzalez/homebrew-php/issues

How to solve?

**Comment by byteh** [comment]
only php55, solved.
# brew install php55
And then individually install all other extensions


https://github.com/Homebrew/homebrew-php/issues/2513

**Comment by josegonzalez** [comment]
Closing as this issue is pretty ancient and didn't really have any stacktrace info to begin with.
