### ISSUE TITLE
configure: error: Cannot find libz

### ISSUE THREAD

**Issue by rodsimpson** [Homebrew/homebrew-php#2506]
I am getting this error:

checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

Full output:

brew install --without-apache --with-fpm --with-pgsql php56
==> Installing php56 from homebrew/homebrew-php
Warning: homebrew/php/php56: --with-pgsql was deprecated; using --with-postgresql instead!
==> Downloading https://php.net/get/php-5.6.15.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.15
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.15 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-scan-dir=/usr/local/etc/php/5.6/conf.d --mandir
Last 15 lines from /Users/rod/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... /usr/local/bin/pkg-config
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by rudeb0t** [comment]
Getting the same error. I upgraded to El Capitan recently. XCode is up to date at version 7.1 and after a bit of digging I found the solution in #2495 

```
xcode-select --install
```

Let it download the CLT and then you should be able to proceed to upgrade as usual.

**Comment by wembernard** [comment]
Thank you @rudeb0t , you saved me a lot of time :)
