### ISSUE TITLE
`$_SERVER['SCRIPT_NAME']` suddenly includes hostname

### ISSUE THREAD

**Issue by lukasbestle** [Homebrew/homebrew-php#2509]
This is rather off-topic, as it isn't (or does not seem like at least) an issue with `homebrew-php`. I'd still be really thankful if someone has a solution for this.

I'm using the PHP formulas of this repository, namely PHP 5.6.15, 5.5.30 and 5.4.45, on OS X 10.11.1 in a setup with the Homebrew `httpd24` and PHP-FPM as explained in your tutorial.

Since today (or maybe for a few days), the `$_SERVER['SCRIPT_NAME']` variable includes the hostname of the request. Before it was `/index.php`, now it is `http://localhost/index.php`. This should basically never ever happen and does not make any sense. Everything else works just fine BTW.

The reason could be that I upgraded Apache and/or PHP (I don't really remember anymore) a few days ago.

Did anyone have a similar problem? In the end it might be related to anything Homebrewy, but it could also be a totally different issue that is related to my setup.

(And yes, I did try turning it off and on again. Twice. :D)

**Comment by ablyler** [comment]
Can you search your apache config for SCRIPT_NAME?

**Comment by lukasbestle** [comment]
Thanks for your reply!

My Apache configuration does not set any header or env variable named `SCRIPT_NAME`, the string does not occur at all in my config. Also I haven't changed the configuration for a few months now and it worked just fine until last week.

**Comment by lukasbestle** [comment]
Apparently upgrading/reinstalling `httpd24` from `homebrew-apache` fixed it. \o/
