### ISSUE TITLE
OS X 10.11 install to  php55-pthreads installation failed

### ISSUE THREAD

**Issue by v3u3i87** [Homebrew/homebrew-php#2511]
Installation failed given as follows
brew install php55-pthreads
logs:
==> Installing php55-pthreads from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php55-pthreads: php55
==> Installing homebrew/php/php55-pthreads dependency: php55
==> Downloading https://php.net/get/php-5.5.30.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-5.5.30
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.30 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5 --with-
==> make
==> make install
Last 15 lines from /Users/xcvu/Library/Logs/Homebrew/php55/03.make:
2015-11-10 20:46:27 +0800

make install

Installing PHP SAPI module:       apache2handler
/usr/share/httpd/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1/build-1/libtool' libs/libphp5.so /usr/local/Cellar/php55/5.5.30/libexec/apache2
/usr/share/apr-1/build-1/libtool --mode=install install libs/libphp5.so /usr/local/Cellar/php55/5.5.30/libexec/apache2/
libtool: install: install libs/libphp5.so /usr/local/Cellar/php55/5.5.30/libexec/apache2/libphp5.so
Warning!  dlname not found in /usr/local/Cellar/php55/5.5.30/libexec/apache2/libphp5.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php55/5.5.30/libexec/apache2/libphp5.so
apxs:Error: Config file /private/etc/apache2/httpd.conf not found.
make: *** [install-sapi] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Already on （chmod 755 /usr/local/Cellar/php55/5.5.30/libexec/apache2/libphp5.so）Processed

**Comment by ablyler** [comment]
@v3u3i87 can you run `brew doctor` and provide the output?  also, if you could provide all the information detailed at https://github.com/Homebrew/homebrew-php#filing-bug-reports that would be great!

**Comment by javian** [comment]
@v3u3i87 did you manage to resolve this issue ?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update in 2+ weeks.
