### ISSUE TITLE
php55 failed to build on 10.11.1 (couldn't understand kern.osversion `15.0.0')

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-php#2513]
_From @aburakovskiy on November 10, 2015 13:47_

I am trying to install php55:
`brew install php55 --with-apache --with-mysql --with-postgresql --with-intl`
I get the error: *couldn't understand kern.osversion `15.0.0'*
https://gist.github.com/aburakovskiy/889262aad6984f69112d

_Copied from original issue: Homebrew/homebrew#45858_

**Comment by ablyler** [comment]
@aburakovskiy, I think this might be causing the issue:

```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.
```

**Comment by javian** [comment]
@aburakovskiy did you manage to resolve this issue ?

**Comment by aburakovskiy** [comment]
My solution to the problem was to install packages without any keys
`brew install php55`
And then individually install all other extensions
