### ISSUE TITLE
xdebug install on php70

### ISSUE THREAD

**Issue by craigcarnell** [Homebrew/homebrew-php#2518]
brew install php70-xdebug
```
==> Installing php70-xdebug from homebrew/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-php/php70-xdebug-2.4.0beta1.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring php70-xdebug-2.4.0beta1.el_capitan.bottle.1.tar.gz
==> Caveats
To finish installing xdebug for PHP 7.0:
  * /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the xdebug module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the xdebug module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php70-xdebug/2.4.0beta1: 4 files, 240K
```

Restart php70-fpm:

```
Failed loading /usr/local/opt/php70-xdebug/xdebug.so:  dlopen(/usr/local/opt/php70-xdebug/xdebug.so, 9): Symbol not found: _basic_globals_id
  Referenced from: /usr/local/opt/php70-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php70-xdebug/xdebug.so
PHP 7.0.0RC7 (fpm-fcgi) (built: Nov 12 2015 06:46:59)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by ablyler** [comment]
@craigcarnell does `brew install --build-from-source php70-xdebug` fix it?

**Comment by craigcarnell** [comment]
@ablyler Works thanks

**Comment by abelardolg** [comment]
Hi, @ablyler 
For me, that command doesn't work.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.8_20/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.8_20/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0

Osx El Gran Capitan
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

Any help would be welcome.

Best regards,
Abelardo.

**Comment by sensorario** [comment]
Have you checked that `brew install --build-from-source php70-xdebug` is for 7.0 but your php version is 7.1.

**Comment by abelardolg** [comment]
@sensorario , I run that command by replacing 70 by 71 but it didn't work.

**Comment by wonder95** [comment]
I'm dealing with this same issue. I have installed php70 and php70-xdebug using `brew install --build-from-source php70-xdebug`, and created my xdebug.ini file. PHPInfo shows the .ini file being read, but the XDebug data does not show up.

**Comment by msypes** [comment]
Using php71-xdebug. Have tried both with and without the `--build-from-source` flag.

The .ini file is being read, but my apache error log is showing problems reading the referenced `.so` file: `Failed loading /usr/local/opt/php71-xdebug/xdebug.so: dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): Symbol not found: _compiler_globals in /usr/local/opt/php71-xdebug/xdebug.so`

**Comment by chakzefir** [comment]
If you got an error with installing `php71-xdebug` with error in ruby Abstract modules, try to update your brew this way: https://github.com/Homebrew/brew/issues/2087
