### ISSUE TITLE
gdb debugging php appear "no core file handler recognizes format"

### ISSUE THREAD

**Issue by longxinH** [Homebrew/homebrew-php#2525]
MacBook:test lxh$ gdb /usr/local/php/bin/php -c /cores/core.80164 
GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin15.0.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/php/bin/php...done.
"/cores/core.80164": no core file handler recognizes format
(gdb) bt
No stack.
(gdb) q

**Comment by javian** [comment]
As far as I can tell this has nothing to do with php but is a gdb problem. This stackoverflow article tells you more http://stackoverflow.com/questions/27680712/homebrew-gdb-cant-open-core-file-on-yosemite-10-10 but doesn't give a solution for homebrew. There als some notes in the caveats section of gdb which might help you move in the right direction.
