### ISSUE TITLE
Installing php56-memcached

### ISSUE THREAD

**Issue by sergiu-popa** [Homebrew/homebrew-php#2529]
Hello,
I can install correctly php-memcached using `brew install php56-memcached` but it install version 2.2.0. I want version 3.0.8 so I tried `brew install --devel php56-memcached`. Same version gets installed. The formula has the devel option, right? https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56-memcache.rb. How can I install it?

I also tried using `pecl install memcached-3.0.8` but it cannot be found. I also tried download manually from PECL page and running `phpize && ./configure && make && sudo make install` but it gives no errors during the installation although the extension doesn't get loaded (cannot find message; memcached.so it's in the extension directory).

Please help. Thanks

**Comment by sergiu-popa** [comment]
The error I got when trying `pecl install memcached-3.0.8` is this: `Failed to download pecl/memcached, version "3.0.8", latest release is version 2.2.0, stability "stable", use "channel://pecl.php.net/memcached-2.2.0" to install
install failed`.

So I found a way around: I downloaded the package manually using wget and after that I installed it using `pear install memcached-3.0.8.tgz`. The extension is now correctly loaded, version 3.0.8.

**Comment by sergiu-popa** [comment]
I had to edit the formula manually for force downloading the version 3.0.8.

```
require File.expand_path("../../Abstract/abstract-php-extension", __FILE__)

class Php56Memcache < AbstractPhp56Extension
  init
  homepage "https://pecl.php.net/package/memcache"
  url "https://pecl.php.net/get/memcache-3.0.8.tgz"
  sha256 "2cae5b423ffbfd33a259829849f6000d4db018debe3e29ecf3056f06642e8311"
  head "https://svn.php.net/repository/pecl/memcache/trunk/"

  bottle do
    cellar :any_skip_relocation
    sha256 "a869f9bd49a8d975a7b2f836784f6d6a1a05135562fc2b42e5dff0315902b2ce" => :el_capitan
    sha256 "e876c59029000634519f46375fbbc37fb6f339bcedc81dc0ee40070577b284c6" => :yosemite
    sha256 "34445de0a6b7c486ef2cd0289b37ca3519a7530c488c43e82c4ec91fdbc09b7b" => :mavericks
  end

  def install
    Dir.chdir "memcache-#{version}" unless build.head?

    ENV.universal_binary if build.universal?

    safe_phpize

    ENV['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    ENV['CFLAGS'] = '-fgnu89-inline'
    ENV['LDFLAGS'] = '-fgnu89-inline'
    ENV['CXXFLAGS'] = '-fgnu89-inline'

    system "./configure", "--prefix=#{prefix}",
                          phpconfig
    system "make"
    prefix.install "modules/memcache.so"
    write_config_file if build.with? "config-file"
  end
end
```
Also, I set **some flags** if anyone gets this error on Yosemite 10.10:
```
dyld: lazy symbol binding failed: Symbol not found: _mmc_queue_free
  Referenced from: /usr/local/Cellar/php56/5.6.15/lib/php/extensions/no-debug-non-zts-20131226/memcache.so
  Expected in: flat namespace

dyld: Symbol not found: _mmc_queue_free
  Referenced from: /usr/local/Cellar/php56/5.6.15/lib/php/extensions/no-debug-non-zts-20131226/memcache.so
  Expected in: flat namespace

/usr/local/bin/phpunit: line 3:  6328 Trace/BPT trap: 5       /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/phpunit/5.0.0/libexec/phpunit-5.0.0.phar $*
```

**Comment by thierrymarianne** [comment]
@sergiu-popa Thank you!
