### ISSUE TITLE
CLI config

### ISSUE THREAD

**Issue by loranger** [Homebrew/homebrew-php#2536]
Hello,

My composer now reports I should disable my xdebug extension.
I do agree, but I still need it (a lot) for debugging my PHP scripts.
So in order to disable xdebug only in cli mode, I tried to reach the cli's php.ini file... and failed.

I tried to created a php.cli.ini and a cli/php.ini but cli is still using the default php.ini file.

What is the solution to use a separated php.ini file for cli ?

**Comment by bytehead** [comment]
Same here... :+1:

**Comment by frostealth** [comment]
i've the same problem

**Comment by dalin-** [comment]
AFAICT homebrew has no separate .ini for CLI.  It would be great to be able to disable it.

**Comment by josegonzalez** [comment]
Disabling it in CLI mode will also disable it for stuff like PHPUnit, which affects code coverage use.

**Comment by gharlan** [comment]
> What is the solution to use a separated php.ini file for cli ?

name it `php-cli.ini`.

**Comment by apfelbox** [comment]
@gharlan that works!

Keep in mind though, that the `/conf.d/` directory is automatically loaded, so what you need to do is copy the content of `conf.d/ext-xdebug.ini` to the end of your main `php.ini` and comment everything in `conf/ext-xdebug.ini` (or just remove the file).

**Comment by bytehead** [comment]
Works for me as well :+1: Thanks to @gharlan and @apfelbox!

**Comment by nesl247** [comment]
This is why I recommend commenting out the `zend_extension` line in `conf.d/ext-xdebug.ini`. I then create a shell alias. `alias xphp "php -dzend_extension=/usr/local/opt/php70-xdebug/xdebug.so"`. When you need xdebug, you run `xphp bin/phpunit` for example.

**Comment by TomK** [comment]
Just to keep this issue updated. #3174 has been merged which adds code to the composer wrapper effectively disabling xdebug for composer only.
