### ISSUE TITLE
php**-intl broken after ﻿﻿icu4c upgrade

### ISSUE THREAD

**Issue by derrabus** [Homebrew/homebrew-php#2544]
I've upgraded my homebrew packages today and got an update for icu4c from 55.1 to 56.1. After that upgrade, php fails to load its intl extension:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.55.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
```

The output above is from php 7.0 RC7, but I can also reproduce this with the corresponding php 5.6 and 5.3 packages. I assume that 5.4 and 5.5 are also affected, but I don't have those packages installed at the moment. Running `brew reinstall php70-intl` does not fix the problem.

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    php53
    php56
```

**Comment by derrabus** [comment]
If I reinstall the package from source, the errors are gone:
```bash
brew reinstall --build-from-source php70-intl
```

**Comment by timwangdev** [comment]
Same issues here.
```
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.55.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
```

**Comment by DomT4** [comment]
[Self-reference](https://github.com/Homebrew/homebrew-php/issues/1701#issuecomment-160036522): Someone needs to submit a PR to bump the revisions of the formulae involved and then merge that PR with the revision bump and new bottles.

**Comment by derrabus** [comment]
php56-intl and php70-intl have been fixed with upstream version bumps (5.6.16 and 7.0 RC8). Other php branches (5.3, 5.4, 5.5) might still be broken.

**Comment by bskendig** [comment]
php54 is still broken.

**Comment by ilhnctn** [comment]
`brew reinstall --build-from-source php56-intl` worked for PHP56(OS 10.10.5)
Thanks @derrabus

**Comment by ryantfowler** [comment]
@ilhnctn Thanks! That worked like a charm ;)

**Comment by derrabus** [comment]
It's the same issue again for all php**-intl package after the release of icu4c 57.1. You guys somehow need a process of pushing new releases oh php**-intl after an icu4c release. :-/

**Comment by javian** [comment]
This should be resolved now by the closing of #3090 . @derrabus I hear your frustration - just keep in mind this is a volunteer project and a workaround was available so it can't be that big of a deal.

**Comment by derrabus** [comment]
You hear a frustration where there is none. I just wanted to point out that this will be a continuous problem. I am very thankful for what this project is doing.

**Comment by holtkamp** [comment]
Same comment as https://github.com/Homebrew/homebrew-php/issues/2544#issuecomment-160141981 applies for PHP71:

```
~ brew upgrade
==> Upgrading 2 outdated packages, with result:
icu4c 58.1, libpng 1.6.26
==> Upgrading icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-58.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring icu4c-58.1.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/icu4c/58.1: 242 files, 65M
```

now PHP is 'broken', this can be fixed with:

```
brew reinstall php71-intl --build-from-source
```

**Comment by carolinachkpp** [comment]
No available formula with the name "php71-intl"

**Comment by javian** [comment]
@carolinachkpp please open up a new issue since its not related to this topic
