### ISSUE TITLE
Update to PHP 7.0

### ISSUE THREAD

**Issue by Konafets** [Homebrew/homebrew-php#2552]
It seems like PHP 7.0 came out [an hour ago](https://github.com/php/php-src/releases/tag/php-7.0.0). Can you update the formula?

**Comment by veewee** [comment]
+1

**Comment by ablyler** [comment]
The current version of php70 is RC8. That is the current release.

**Comment by nesl247** [comment]
PHP 7.0 final has been released.

**Comment by Konafets** [comment]
Sorry for beeing annoying but @nesl247 is right. Can you reopen the issue and adjust the formula to the stable version of PHP 7

**Comment by nesl247** [comment]
@Konafets It's already done.
