### ISSUE TITLE
php70-snmp build failed on mac

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-php#2629]
_From @lscgzwd on December 4, 2015 6:41_

ops git:(crm) ✗ brew install php70-intl php70-snmp
Warning: homebrew/php/php70-intl-7.0.0 already installed
==> Installing php70-snmp from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php70-snmp: net-snmp
==> Installing homebrew/php/php70-snmp dependency: net-snmp
==> Downloading https://downloads.sourceforge.net/project/net-snmp/net-snmp/5.7.3/net-snmp-5.7.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/net-snmp-5.7.3.tar.gz
==> ./configure --disable-debugging --prefix=/usr/local/Cellar/net-snmp/5.7.3 --enable-ipv6 --with-defaults --with-persistent-directory=/usr/local/var/db/net-snmp --with-logfile=/us
==> make
Last 15 lines from /Users/lushuncheng/Library/Logs/Homebrew/net-snmp/02.make:
        ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openssl/openssl_md5_local.h:118:11: note: expanded from macro 'R1'
        a=ROTATE(a,s); \
                 ^
openssl/openssl_md32_common.h:168:19: note: expanded from macro 'ROTATE'
                                : "I"(n), "0"(a)        \
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
20 errors generated.
make[1]: *** [openssl/openssl_sha1.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [openssl/openssl_md5.lo] Error 1
libtool: compile:  clang -I../include -I. -I../snmplib -I/usr/local/ssl/include -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2 -Udarwin15 -Ddarwin15=darwin15 -c snmpusm.c -o snmpusm.o >/dev/null 2>&1
make: *** [subdirs] Error 1

READ THIS: https://git.io/brew-troubleshooting

_Copied from original issue: Homebrew/homebrew#46653_

**Comment by DomT4** [comment]
Whoops, I can't read. The failure was on the dependency rather than the non-core formula, Sorry!

**Comment by lscgzwd** [comment]
➜  swooleframework git:(master) brew gist-logs net-snmp




https://gist.github.com/cda402230c2f852159ae
