### ISSUE TITLE
You should not run buildconf in a release package

### ISSUE THREAD

**Issue by JoyceBabu** [Homebrew/homebrew-php#2642]
When I try to install php from HEAD `brew reinstall --HEAD php70`, it is failing with 

> warning: refname 'PHP-7.0.0' is ambiguous.
> You should not run buildconf in a release package.
> use buildconf --force to override this check.

There is a tag and a branch with the same name. I think the tag is being checked out instead of the branch.

**Comment by tafarifilho** [comment]
+1

**Comment by Pines-Cheng** [comment]
+1

**Comment by javian** [comment]
This should have been corrected now, can you confirm ?

**Comment by JoyceBabu** [comment]
It is fixed. Thank you.
