### ISSUE TITLE
No formula for php70-imagick

### ISSUE THREAD

**Issue by ChuckHeintzelman** [Homebrew/homebrew-php#2643]
~  ᐅ brew search imagick
homebrew/php/php53-imagick
homebrew/php/php54-imagick
homebrew/php/php55-imagick
homebrew/php/php56-imagick (installed)
~  ᐅ brew search php70
homebrew/php/php70 (installed)
homebrew/php/php70-amqp
homebrew/php/php70-apcu
homebrew/php/php70-ast
homebrew/php/php70-gmp
homebrew/php/php70-intl
homebrew/php/php70-kafka
homebrew/php/php70-libsodium
homebrew/php/php70-lzf
homebrew/php/php70-mcrypt
homebrew/php/php70-memcached
homebrew/php/php70-msgpack
homebrew/php/php70-mustache
homebrew/php/php70-opcache
homebrew/php/php70-pcntl
homebrew/php/php70-pdo-dblib
homebrew/php/php70-pdo-pgsql
homebrew/php/php70-pspell
homebrew/php/php70-pthreads
homebrew/php/php70-redis
homebrew/php/php70-snmp
homebrew/php/php70-tidy
homebrew/php/php70-xdebug
homebrew/php/php70-yaml

**Comment by ablyler** [comment]
Thanks, I just created a formula for their beta in PR #2655.

**Comment by ChuckHeintzelman** [comment]
Thanks, works perfectly!
