### ISSUE TITLE
Adding DrupalConsole to homebrew-php

### ISSUE THREAD

**Issue by darol100** [Homebrew/homebrew-php#2665]
How can we integrate [DrupalConsole](https://github.com/hechoendrupal/DrupalConsole/) with homebrew?

DrupalConsole is a new command line tool for Drupal 8 developers and we will like to add the ability of user downloading using homebrew.

Here is the instruction on how to install DrupalConsole:

```````
php -r "readfile('http://drupalconsole.com/installer');" > drupal.phar

# Accessing from anywhere on your system:
mv drupal.phar /usr/local/bin/drupal
````````````````

If someone can point me to a direction (documentation) on how to write an integration to support DrupalConsole that will be nice.

**Comment by darol100** [comment]
Looking at the formulas from `Composer` and `Drush` which are very similar tools I ended up came up with.

````````
require File.expand_path("../../Abstract/abstract-php-phar", __FILE__)

class drupalconsole < Formula
  desc "The Drupal Console is a command line interface tool, to generate boilerplate code and interact with a Drupal 8 installation."
  homepage "https://github.com/drush-ops/drush"
  url "https://github.com/hechoendrupal/DrupalConsole/releases/download/0.9.9/drupal.phar"
  version "0.9.9"

  head do
    url "https://github.com/hechoendrupal/DrupalConsole.git"
  end
    test do
    system "drupal", "--version"
  end
end
````````
Can someone explain me if this is right ?

The only thing that I believe is missing is the   `bottle do` command with the sha256. Can someone explain me base on what I need to generate this sha? And what is for ?

**Comment by javian** [comment]
It is not quite right but you are moving in the right direction. Most of your questions can be answered by reading the homebrew Formula cookbook

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

but there are some additions for the homebrew-php tap that are required so you need to look at the differences between regular hb and hb-php formulas. I think the composer formula is closer to what's needed than drush which is installed with composer.

**Comment by darol100** [comment]
Hey guys, great work in here. But there is something that I'm kinda concern. DrupalConsole have release at least every two weeks and sometimes even weekly. This implementation is spefic to one version of DrupalConsole.

 My question is... do we need to add a PR every time we have a DrupalConsole new release ? Or do we have a better way to handle this ?

**Comment by darol100** [comment]
Just in case we need to change it every time, I have send  PR with the latest DrupalConsole version https://github.com/Homebrew/homebrew-php/pull/2872

**Comment by javian** [comment]
I think that in general you want versioned handling through homebrew so even if a software updates frequently we would still need to submit a PR every time a new version is out. It would also be possibled to add the HEAD version so it can be installed but that doesn't update automatically when a new commit is pushed to the repository so it doesn't solve the issue. Also, if the updates are so frequent there's not a big point in using the HEAD formula.

**Comment by darol100** [comment]
@javian , What about update path using Homebrew ? Does this will automatically remove the latest `.phar` and replace it with the new one ?

**Comment by javian** [comment]
@darol100 are you referring to `drupal self-update` ? I have not tested that so it might or might not work. I think when using it with phpunit and composer it worked but I didn't look into the details. The update will however be overwritten if a "new" PR towards the software is made so the best thing would be to have someone keep an eye on it and submit timely PRs =) The main homebrew repo is a big no-no clause towards self updating software but this does not seem to apply to the php tap.

**Comment by darol100** [comment]
@javian, I test `drupal self-update` and it fail, However using `composer update`  will update DrupalConsole. In my previous comment, I was referring `brew update`, which I thought will be able to update to my latest formula.

**Comment by javian** [comment]
Ah yes, once the PR has been merged `brew update` will replace the phar with the version specified in the Formula.
