### ISSUE TITLE
My project is listed here : How can I help to notify for updates ?

### ISSUE THREAD

**Issue by Halleck45** [Homebrew/homebrew-php#2666]
Hi,

first: a big thank you for your work !

I'm the author of [phpmetrics](http://phpmetrics.org), a code analyzer for PHP. This tool can be installed with hombrew-php thanks to [this file](https://github.com/Homebrew/homebrew-php/blob/master/Formula/phpmetrics.rb).

+ Is there a webhook where I can notify you that a new version is available ?
+ Do you have a automatic way (Makefile...) to generate all these ruby files ?

Thanks

**Comment by lucasmichot** [comment]
Hi @Halleck45 thanks for that
We don't have at the moment any webhook system, neither a makefile
We love hand-crafted formulae!

Feel free to submit a PR
