### ISSUE TITLE
cannot find libz when using brew install php56 --with-imap

### ISSUE THREAD

**Issue by robinclark007** [Homebrew/homebrew-php#2667]
RdeMacBook:web deng$ brew install php56 --with-imap
==> Installing php56 from homebrew/php
==> Installing dependencies for homebrew/php/php56: imap-uw
==> Installing homebrew/php/php56 dependency: imap-uw
==> Downloading https://homebrew.bintray.com/bottles/imap-uw-2007f.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring imap-uw-2007f.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/imap-uw/2007f: 150 files, 9.5M
==> Installing homebrew/php/php56
==> Downloading https://php.net/get/php-5.6.16.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.6.16.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.16 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-p
Last 15 lines from /Users/deng/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/php/issues

what's the problem ???

**Comment by peckrob** [comment]
Just had this issue. The solution in #1946 worked for me.

**Comment by robinclark007** [comment]
@peckrob xcode-select --install work for me....c

**Comment by adrazich** [comment]
Thanks. This worked for me too.

```
xcode-select --install
```

**Comment by reatang** [comment]
![Uploading image.png…]()
I can't use...QAQ

**Comment by shamsmali** [comment]
Thanks. Worked for me as well.
