### ISSUE TITLE
PHP7.0-apcu Problem

### ISSUE THREAD

**Issue by adlermedrado** [Homebrew/homebrew-php#2668]
I'm trying to use APC but, even with the php7.0-apcu formulae installed, I got the following error:
<img width="926" alt="captura de tela 2015-12-10 as 08 58 30" src="https://cloud.githubusercontent.com/assets/172623/11713996/fcbd688e-9f1d-11e5-819b-44ef472ee8a5.png">

Below is the phpinfo's screenshot showing that APC is enabled:

<img width="941" alt="captura de tela 2015-12-10 as 09 03 07" src="https://cloud.githubusercontent.com/assets/172623/11714005/118df2c4-9f1e-11e5-88a3-d97338911ffd.png">

**Comment by juizmill** [comment]
I am having the same problem!

**Comment by lucasmichot** [comment]
Then you should probably call `apcu_store` instead of `apc_store` then ;-)

**Comment by juizmill** [comment]
I'm using ApcCache Doctrine and it uses the APC, I think we should have a formula for APC.

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/caching.html

**Comment by adlermedrado** [comment]
You are right :|

Thanks.

**Comment by lucasmichot** [comment]
It's more than 3 years than the development of apc has stoped, and the PECL extension is not even done to be compatible with PHP>=5.5

It's not an extension, please report upsteam : https://github.com/doctrine/cache/pull/112

**Comment by juizmill** [comment]
@lucasmichot @adlermedrado  Doctrine implements Apcu Cache [ApcuCache.php](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/ApcuCache.php)

Thanks.

**Comment by lucasmichot** [comment]
Great. You guys can include this development branch to your composer.json or wait for a new doctrine/cache release > 1.5.2
https://github.com/doctrine/cache/releases
