### ISSUE TITLE
Request update on phpmyadmin formulae

### ISSUE THREAD

**Issue by renatoaraujoc** [Homebrew/homebrew-php#2669]
Hello folks,

I'd do it myself but I have no idea how to.

PHPMyAdmin 4.5.2 comes with a variety of bug fixes, specially those regarding their syntax checker.

Could anyone update the formula to the latest version?

Thanks,

Renato Carneiro

**Comment by alcaeus** [comment]
Shouldn't this be closed as well since #2677 is merged?
