### ISSUE TITLE
install php70-kafka on OSX10.11 occur an error

### ISSUE THREAD

**Issue by IanGely** [Homebrew/homebrew-php#2691]
➜  Cellar git:(master) brew install homebrew/php/php70-kafka
==> Installing php70-kafka from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php70-kafka: lzlib, librdkafka
==> Installing homebrew/php/php70-kafka dependency: lzlib
==> Downloading https://homebrew.bintray.com/bottles/lzlib-1.7.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lzlib-1.7.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/lzlib/1.7: 9 files, 152K
==> Installing homebrew/php/php70-kafka dependency: librdkafka
==> Downloading https://github.com/edenhill/librdkafka/archive/0.8.6.tar.gz
==> Downloading from https://codeload.github.com/edenhill/librdkafka/tar.gz/0.8.6
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/librdkafka/0.8.6
==> make
==> make install
🍺  /usr/local/Cellar/librdkafka/0.8.6: 9 files, 660K, built in 12 seconds
==> Installing homebrew/php/php70-kafka
==> Downloading https://github.com/EVODelavega/phpkafka/archive/6a0908803ab6e9d862097e99f84aeb0fff9ecf03.tar.gz
==> Downloading from https://codeload.github.com/EVODelavega/phpkafka/tar.gz/6a0908803ab6e9d862097e99f84aeb0fff9ecf03
######################################################################## 100.0%
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-kafka/rev-6a09088 --with-php-config=/usr/local/opt/php70/bin/php-config --enable-kafka
==> make
Last 15 lines from /Users/angl/Library/Logs/Homebrew/php70-kafka/03.make:
        ^
/private/tmp/php70-kafka20151221-88965-1i47d1w/phpkafka-6a0908803ab6e9d862097e99f84aeb0fff9ecf03/php_kafka.c:694:5: error: use of undeclared identifier 'RETURN_STRING'
    RETURN_STRING(connection->compression, 1);
    ^
/private/tmp/php70-kafka20151221-88965-1i47d1w/phpkafka-6a0908803ab6e9d862097e99f84aeb0fff9ecf03/php_kafka.c:1125:76: error: too many arguments to function call, expected 2, have 3
    while (zend_hash_get_current_data_ex(Z_ARRVAL_P(arr), (void **)&entry, &pos) == SUCCESS)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                   ^~~~
/usr/local/Cellar/php70/7.0.0/include/php/Zend/zend_hash.h:171:1: note: 'zend_hash_get_current_data_ex' declared here
ZEND_API zval* ZEND_FASTCALL zend_hash_get_current_data_ex(HashTable *ht, HashPosition *pos);
^
/usr/local/Cellar/php70/7.0.0/include/php/main/php_config.h:6:19: note: expanded from macro 'ZEND_API'
# define ZEND_API __attribute__ ((visibility("default")))
                  ^
18 errors generated.
make: *** [php_kafka.lo] Error 1

**Comment by javian** [comment]
@IanGely did you manage to resolve this issue ?

**Comment by javian** [comment]
Closing due to no response. Feel free to repopen the issue if you still are experiencing problems.

**Comment by srigi** [comment]
I got exactly the same probl. Please reopen @javian. To be sure:

```
$ brew install homebrew/php/php70-kafka
==> Installing php70-kafka from homebrew/php
==> Downloading https://github.com/EVODelavega/phpkafka/archive/6a0908803ab6e9d862097e99f84aeb0fff9ecf03.tar.gz
Already downloaded: /Users/srigi/Library/Caches/Homebrew/php70-kafka-rev-6a09088.tar.gz
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-kafka/rev-6a09088 --with-php-config=/usr/local/opt/php70/bin/php-config --enable-kafka
==> make
Last 15 lines from /Users/srigi/Library/Logs/Homebrew/php70-kafka/03.make:
        ^
/private/tmp/php70-kafka-20161122-78207-106yrvn/phpkafka-6a0908803ab6e9d862097e99f84aeb0fff9ecf03/php_kafka.c:694:5: error: use of undeclared identifier 'RETURN_STRING'
    RETURN_STRING(connection->compression, 1);
    ^
/private/tmp/php70-kafka-20161122-78207-106yrvn/phpkafka-6a0908803ab6e9d862097e99f84aeb0fff9ecf03/php_kafka.c:1125:76: error: too many arguments to function call, expected 2, have 3
    while (zend_hash_get_current_data_ex(Z_ARRVAL_P(arr), (void **)&entry, &pos) == SUCCESS)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                   ^~~~
/usr/local/Cellar/php70/7.0.13_6/include/php/Zend/zend_hash.h:171:1: note: 'zend_hash_get_current_data_ex' declared here
ZEND_API zval* ZEND_FASTCALL zend_hash_get_current_data_ex(HashTable *ht, HashPosition *pos);
^
/usr/local/Cellar/php70/7.0.13_6/include/php/main/php_config.h:6:19: note: expanded from macro 'ZEND_API'
# define ZEND_API __attribute__ ((visibility("default")))
                  ^
18 errors generated.
make: *** [php_kafka.lo] Error 1

READ THIS: https://git.io/brew-troubleshooting
```

**Comment by srigi** [comment]
No problems with installing the `homebrew/php/php56-kafka`

**Comment by srigi** [comment]
It looks like for PHP 7.0 only the [v2.0.0](https://pecl.php.net/package-changelog.php?package=rdkafka&release=2.0.0) is intended.

Please make this change.
