### ISSUE TITLE
php -v

### ISSUE THREAD

**Issue by kernel-task** [Homebrew/homebrew-php#2696]
Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n  Reason: Incompatible library version: libphp7.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

**Comment by yuqiangit** [comment]
hello,I have encountered this problem, what solutions do you have？

**Comment by kernel-task** [comment]
no solution yet.

----- Original Message -----

**Comment by josegonzalez** [comment]
Upgrade your libxml as well.

**Comment by kernel-task** [comment]
Have done so.
Currently situation - libxml2 2.9.3 (create date 24/11/2015)
phpinfo() 
--with-libxml-dir=/usr/local/opt/libxml2 
and later in the report it seems to indicate the libxml is active
libXML support                   activelibXML Compiled
Version  2.9.3libXML Loaded Version     20903libXML streams    
             enabled
XML Support                      activeXML Namespace
Support activelibxml2 Version                  2.9.3

despite this "apachectl configtest" throws up the 'Incompatible
Library Version:' error.
Regards
FC

----- Original Message -----
