### ISSUE TITLE
php7 libxml2 weirdness

### ISSUE THREAD

**Issue by kernel-task** [Homebrew/homebrew-php#2697]
Environment - OSX 10.11.2 (15C50)/Apache2.4.16/PHP7.0.1 + loads of other irrelevant stuff.

Following last brewup apachectl configtest yields this technological ode:

httpd: Syntax error on line 173 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so
Reason: Incompatible library version: libphp7.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

Yet system operating OK so hardly in crisis or anything! (at least no project is presenting as compromised)
So apparently  'libphp7.so'  is loaded?  Observations?

Regards.
Frank C.

**Comment by javian** [comment]
You could check with phpinfo(); just to verify your thoughts. It sounds strange.

The latest version of php posted is 7.0.2, can you update and try again ?
Can you verify that the installed libxml2 version is 2.9.3 (brew info libxml2) ?

**Comment by sandersturing** [comment]
I have the exact same issue. Instead I'm using PHP7.0.2, but I got the same error (installed PHP7 with homebrew + dupes).

When I check which libxml-version is installed with brew info libxml2, it says:
```
libxml2: stable 2.9.3 (bottled), HEAD [keg-only]
GNOME XML library
http://xmlsoft.org
/usr/local/Cellar/libxml2/2.9.3 (275 files, 9.8M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libxml2.rb
```

Does anyone have any idea how to fix this?

**Comment by kernel-task** [comment]
Never did figure this out. Message only occurred on 1 out of 3 (identical?) workstations.
Decided on on a fresh start with the offending system.
Removed all packages + Homebrew then fresh install everything.
Weirdness ended. No idea what the basis to the issue was - some "software thing" will have to suffice.

In the end I tend to view it as more testimony of the elegance of Homebrew as a system rather than an example of a bug. Rebuilding was straightforward with minimum time and effort.

Regards.

**Comment by javian** [comment]
It seems that this is related to a script bundled with Apache which makes the wrong dylib load at runtime - see https://github.com/Homebrew/homebrew-php/issues/2508#issuecomment-205896684
