### ISSUE TITLE
Fails to Install Php56 with Imap Extensiton

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew-php#2703]
_From @Abhi150688 on December 26, 2015 6:32_

Hi,
I am trying to install PHP56 with Imap extension however, whenever I run the command brew install php56 --with-imap...the process fails at the last step. 

The error message shown is: 
Warning!  dlname not found in /usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so
Died at /usr/sbin/apxs line 558.
make: *** [install-sapi] Error 13

The snapshot of the terminal has been attached for your reference. 
Thanks. 
![screen shot 2015-12-26 at 11 56 45 am](https://cloud.githubusercontent.com/assets/9885740/12005389/5be68b18-abc8-11e5-9a47-bd0f3859f172.png)

_Copied from original issue: Homebrew/homebrew#47384_

**Comment by Abhi150688** [comment]
any update?

**Comment by dunn** [comment]
Should've asked earlier; can you post the full `brew gist-logs php56`?

**Comment by Abhi150688** [comment]
there is no response..the terminal just goes dead. Snapshot attached. 
![screen shot 2015-12-29 at 12 39 44 am](https://cloud.githubusercontent.com/assets/9885740/12023920/b4468828-adc4-11e5-9fe6-ef3a9236caef.png)

**Comment by Abhi150688** [comment]
it gives a link. I have pasted it below: 
https://gist.github.com/e99fdb8c1b998bc12c04

**Comment by javian** [comment]
@Abhi150688 did you manage to resolve this issue ?

**Comment by ElliottLandsborough** [comment]
I also get this issue when trying to install php70 on mint/ubuntu. I have provided gist logs: https://gist.github.com/anonymous/d9eba19e3214dc5303a717d2e9960b22

**Comment by josegonzalez** [comment]
Since there hasn't been an update in 2+ weeks and this repo is for OS X - not Linux - I'll be closing this.
