### ISSUE TITLE
fails installing brew install php56

### ISSUE THREAD

**Issue by taalayuulu** [Homebrew/homebrew-php#2704]
Sorry, I cannot run apxs.  Possible reasons follow:

1. Perl is not installed
2. apxs was not found. Try to pass the path using --with-apxs2=/path/to/apxs
3. Apache was not built using --enable-so (the apxs usage page is displayed)

The output of /usr/sbin/apxs follows:
./configure: line 8417: /usr/sbin/apxs: No such file or directory
configure: error: Aborting

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues
![image](https://cloud.githubusercontent.com/assets/9998956/12009578/481f43a0-aca8-11e5-8e88-9684415be8c0.png)

**Comment by javian** [comment]
Do you have apache installed ? If you don't need apache then you could try 
`brew install php56 --without-apache`

**Comment by taalayuulu** [comment]
Thank you for responding to my problem. But I have solved this problem

**Comment by mohamdio** [comment]
Hi @taalayuulu please can you share the solution for this issue ? i have this error too and this
`brew install php56 --without-apache` not solved it

**Comment by lewisflude** [comment]
@mohamdio @taalayuulu https://xkcd.com/979/
