### ISSUE TITLE
I can't find php56_pdo!

### ISSUE THREAD

**Issue by chen3jian** [Homebrew/homebrew-php#2706]
Hello,
I am trying to install PHP56 with pdo_mysql extension however,I run the command brew search php56,I can't find php56_pdo_mysql  or php56_pdo. just find this,see the picture.

https://cloud.githubusercontent.com/assets/9714937/12022155/19b3290c-adc8-11e5-9158-3a981f2277c6.png

why don't support it!

**Comment by alcaeus** [comment]
Have you checked the installed modules with `php -m`?

**Comment by javian** [comment]
@chen3jian did you manage to solve this issue ?

**Comment by javian** [comment]
Closing issue due to no response.
