### ISSUE TITLE
Using AMPPS phpize for home-brew php installs

### ISSUE THREAD

**Issue by Joseffb** [Homebrew/homebrew-php#2707]
is there a way to tell home-brew that my php install is in /Applications/AMPPS/php/bin and to use it for all php related installs/compiles?

right now I have the .bash_profile setup with:
export PATH="/Applications/AMPPS/php/bin:/Applications/AMPPS/php/pear/bin:/Applications/AMPPS/mysql/bin:/usr/local/opt/php56/bin:/usr/local/opt:$PATH"

but when I do a be install php56-memcached I get the following error.

Already downloaded: /Library/Caches/Homebrew/php56-memcached-2.2.0.tgz
==> /usr/local/opt/php56/bin/phpize
Error: No such file or directory - /usr/local/opt/igbinary/include/igbinary.h

**Comment by javian** [comment]
Not that I'm aware of. Why can't you just brew the php version you need and use that ?

**Comment by javian** [comment]
There was a dependency added to the formula to igbinary in commit https://github.com/Homebrew/homebrew-php/commit/d1b67ac2708e9c472c6c30b77744739386b00b80#diff-c8f15fc8ad86a9576437a74fc45ea511  so if you build it from source it will at least not throw an error on the header include.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in 2+ weeks.
