### ISSUE TITLE
10.6.8 "brew install php70" failed with Error 139

### ISSUE THREAD

**Issue by billyjho** [Homebrew/homebrew-php#2708]
Hello, Please help
==> Installing php70 from homebrew/php
==> Downloading https://php.net/get/php-7.0.1.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php70-7.0.1
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.1 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/etc/php/7.0 --with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d --mandir=/usr/local/Cellar/php70/7.0.1/share/man --enable-bcmath --enable-calendar --enable-dba --enable-exif --enable-ftp --enable-gd-native-ttf --enable-mbregex --enable-mbstring --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip --with-freetype-dir=/usr/local/opt/freetype --with-gd --with-gettext=/usr/local/opt/gettext --with-iconv-dir=/usr --with-icu-dir=/usr/local/opt/icu4c --with-jpeg-dir=/usr/local/opt/jpeg --with-kerberos=/usr --with-libedit --with-mhash --with-ndbm=/usr --with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc --with-png-dir=/usr/local/opt/libpng --with-unixODBC=/usr/local/opt/unixodbc --with-xmlrpc --with-zlib=/usr --with-readline=/usr/local/opt/readline --without-gmp --without-snmp --with-libxml-dir=/usr/local/opt/libxml2 --with-apxs2=/usr/sbin/apxs --libexecdir=/usr/local/Cellar/php70/7.0.1/libexec --with-bz2=/usr --with-openssl=/usr/local/opt/openssl --enable-fpm --with-fpm-user=_www --with-fpm-group=_www --with-curl=/usr/local/opt/curl --with-xsl=/usr --with-ldap --with-ldap-sasl=/usr --with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-mysql=mysqlnd --with-pdo-mysql=mysqlnd --disable-opcache --enable-pcntl --without-pear --enable-dtrace --disable-phpdbg --enable-zend-signals
==> make
Last 15 lines from /Users/photoshop/Library/Logs/Homebrew/php70/02.make:
......
......-licucore -lm -lstdc++  -o sapi/cgi/php-cgi
Generating phar.php
/bin/sh: line 1: 20047 Segmentation fault      ` if test -x "/private/tmp/php7020151228-1275-b40f99/php-7.0.1/sapi/cli/php"; then /private/tmp/php7020151228-1275-b40f99/php-7.0.1/build/shtool echo -n -- "/private/tmp/php7020151228-1275-b40f99/php-7.0.1/sapi/cli/php -n"; if test "x" != "x"; then /private/tmp/php7020151228-1275-b40f99/php-7.0.1/build/shtool echo -n -- " -d extension_dir=/private/tmp/php7020151228-1275-b40f99/php-7.0.1/modules"; for i in bz2 zlib phar; do if test -f "/private/tmp/php7020151228-1275-b40f99/php-7.0.1/modules/$i.la"; then . /private/tmp/php7020151228-1275-b40f99/php-7.0.1/modules/$i.la; /private/tmp/php7020151228-1275-b40f99/php-7.0.1/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /private/tmp/php7020151228-1275-b40f99/php-7.0.1/build/shtool echo -n -- "/private/tmp/php7020151228-1275-b40f99/php-7.0.1/sapi/cli/php"; fi;` -n -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /private/tmp/php7020151228-1275-b40f99/php-7.0.1/ext/phar/build_precommand.php > ext/phar/phar.php
make: *** [ext/phar/phar.php] Error 139

**Comment by javian** [comment]
@billyjho Did you manage to resolve this issue ?

**Comment by theofidry** [comment]
Got the same issue with: `brew install php70 --with-phpdbg`

I'm running on OSX 10.9.5 and I uninstall all previous versions of PHP. If I do `brew list | grep php` the list is empty.

I made sure that homebrew is update to date and all packages too.

**Comment by ghostfreeman** [comment]
Same issues compiling but I got the following error in situ:

```
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.7 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-fi
Last 15 lines from /Users/ckilgore/Library/Logs/Homebrew/php70/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz
READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues
```

```
php70-pspell: update bottle https://github.com/Homebrew/homebrew-php/pull/3201
php70-pcntl: update bottle https://github.com/Homebrew/homebrew-php/pull/3198
php70-opcache: update bottle https://github.com/Homebrew/homebrew-php/pull/3197
php70-mcrypt: update bottle https://github.com/Homebrew/homebrew-php/pull/3196
php70-intl: update bottle https://github.com/Homebrew/homebrew-php/pull/3195
php70-gmp: update bottle https://github.com/Homebrew/homebrew-php/pull/3194
php70-pdo-pgsql: update bottle https://github.com/Homebrew/homebrew-php/pull/3200
php70-pdo-dblib: update bottle https://github.com/Homebrew/homebrew-php/pull/3199
php70-imagick has warnings https://github.com/Homebrew/homebrew-php/issues/2766
brew install php70-redis https://github.com/Homebrew/homebrew-php/issues/2762
Add head formula for php70-uploadprogress https://github.com/Homebrew/homebrew-php/pull/3178
Why does wp-cli formula try to install php56 if php70 is already there? https://github.com/Homebrew/homebrew-php/issues/3179
Adds a new php70-gearman formula that updates php56-gearman https://github.com/Homebrew/homebrew-php/pull/3120
"brew upgrade" fails: php56 conflicting with php70 when upgrading phpmyadmin https://github.com/Homebrew/homebrew-php/issues/2945
install php70-kafka on OSX10.11 occur an error https://github.com/Homebrew/homebrew-php/issues/2691
10.6.8 "brew install php70" failed with Error 139 https://github.com/Homebrew/homebrew-php/issues/2708
```

There is no libz but there is a libzip. Installing libzip or zlib does not change the outcome.

**Comment by javian** [comment]
@ghostfreeman that's a different issue should be a seperate issue. The solution to that is `xcode-select --install` which will reinstall the Apple headers and then it will compile.

**Comment by javian** [comment]
@theofidry did you manage to resolve your issue with phpdbg ?

**Comment by javian** [comment]
Closing due to no response.
