### ISSUE TITLE
brew install --HEAD homebrew/php/php70-memcached come across a problem

### ISSUE THREAD

**Issue by naffan2014** [Homebrew/homebrew-php#2710]
when i want  to install php70-memcached ,i came across  a  problem.
he told me require ZLIB. but my mac have ZLIB.so i don't know exactly what problem it is ~

yifandeMacBook-Pro:www naffan$ brew install --HEAD homebrew/php/php70-memcached
==> Installing php70-memcached from homebrew/php
==> Cloning https://github.com/php-memcached-dev/php-memcached.git
Updating /Library/Caches/Homebrew/php70-memcached--git
==> Checking out branch php7
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-memcached/HEAD --with-php-config=/usr/
Last 15 lines from /Users/yifanzhang/Library/Logs/Homebrew/php70-memcached/02.configure:
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable memcached support... yes, shared
checking for libmemcached... yes, shared
checking whether to enable memcached session handler support... yes
checking whether to enable memcached igbinary serializer support... no
checking whether to enable memcached json serializer support... no
checking whether to enable memcached msgpack serializer support... no
checking whether to enable memcached sasl support... yes
checking whether to enable memcached protocol support... no
checking whether to use system FastLZ bibrary... no
checking for ZLIB... yes, shared
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking for zlib location... configure: error: memcached support requires ZLIB. Use --with-zlib-dir=

to specify the prefix where ZLIB headers and library are located

**Comment by naffan2014** [comment]
glist log
https://gist.github.com/d309aeeb30c939236153

**Comment by bfontaine** [comment]
Seems like this could be fixed by running `xcode-select --install`. See https://github.com/Homebrew/homebrew-php/issues/2029.

**Comment by naffan2014** [comment]
thanks a lot ,it really help me a lot. 
thank you for your replying .and i will ask quesion after take a look at issues.
it is a good behavior before asking . thank you for your patience
