### ISSUE TITLE
Php 7 extensions not working

### ISSUE THREAD

**Issue by mcfedr** [Homebrew/homebrew-php#2712]
I have used brew to install php 7 and then a number of extensions, including apcu, using the brew packages php70-apcu.

Neither of these extensions are working.

But in weird ways!

The confs are loaded - `php --ini` shows this:

    Configuration File (php.ini) Path: /usr/local/etc/php/7.0
    Loaded Configuration File:         /usr/local/etc/php/7.0/php.ini
    Scan for additional .ini files in: /usr/local/etc/php/7.0/conf.d
    Additional .ini files parsed:      /usr/local/etc/php/7.0/conf.d/ext-apcu.ini

And phpinfo `php -i` - shows that the modules are loaded:

    phpinfo()
    PHP Version => 7.0.1

    System => Darwin caesar.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
    Build Date => Dec 18 2015 19:19:19
    Configure Command =>  './configure'  '--prefix=/usr/local/Cellar/php70/7.0.1' '--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/7.0' '--with-config-file-path=/usr/local/etc/php/7.0' '--with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d' '--mandir=/usr/local/Cellar/php70/7.0.1/share/man' '--enable-bcmath' '--enable-calendar' '--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' '--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' '--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-libedit' '--with-mhash' '--with-ndbm=/usr' '--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc' '--with-png-dir=/usr/local/opt/libpng' '--with-unixODBC=/usr/local/opt/unixodbc' '--with-xmlrpc' '--with-zlib=/usr' '--with-readline=/usr/local/opt/readline' '--without-gmp' '--without-snmp' '--with-libxml-dir=/usr/local/opt/libxml2' '--with-apxs2=/usr/sbin/apxs' '--libexecdir=/usr/local/Cellar/php70/7.0.1/libexec' '--with-bz2=/usr' '--disable-debug' '--with-openssl=/usr/local/opt/openssl' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' '--with-curl' '--with-xsl=/usr' '--with-ldap' '--with-ldap-sasl=/usr' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-mysql=mysqlnd' '--with-pdo-mysql=mysqlnd' '--disable-opcache' '--enable-pcntl' '--without-pear' '--enable-dtrace' '--disable-phpdbg' '--enable-zend-signals' 'CC=clang' 'CXX=clang++'
    Server API => Command Line Interface
    Virtual Directory Support => disabled
    Configuration File (php.ini) Path => /usr/local/etc/php/7.0
    Loaded Configuration File => /usr/local/etc/php/7.0/php.ini
    Scan this dir for additional .ini files => /usr/local/etc/php/7.0/conf.d
    Additional .ini files parsed => /usr/local/etc/php/7.0/conf.d/ext-apcu.ini,
    /usr/local/etc/php/7.0/conf.d/ext-memcached.ini

    PHP API => 20151012
    PHP Extension => 20151012
    Zend Extension => 320151012
    Zend Extension Build => API320151012,NTS
    PHP Extension Build => API20151012,NTS
    Debug Build => no
    Thread Safety => disabled
    Zend Signal Handling => enabled
    Zend Memory Manager => enabled
    Zend Multibyte Support => provided by mbstring
    IPv6 Support => enabled
    DTrace Support => enabled

    Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
    Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
    Registered Stream Filters => zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

    This program makes use of the Zend Scripting Language Engine:
    Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

     _______________________________________________________________________

    Configuration

    apcu

    APCu Support => Enabled
    Version => 5.1.0
    APCu Debugging => Disabled
    MMAP Support => Enabled
    MMAP File Mask => /tmp/apc.MFDwZB
    Serialization Support => php
    Build Date => Dec  3 2015 17:25:24

    Directive => Local Value => Master Value
    apc.coredump_unmap => Off => Off
    apc.enable_cli => On => On
    apc.enabled => On => On
    apc.entries_hint => 4096 => 4096
    apc.gc_ttl => 3600 => 3600
    apc.mmap_file_mask => /tmp/apc.MFDwZB => /tmp/apc.MFDwZB
    apc.preload_path => no value => no value
    apc.serializer => php => php
    apc.shm_segments => 1 => 1
    apc.shm_size => 64M => 64M
    apc.slam_defense => On => On
    apc.smart => 0 => 0
    apc.ttl => 7200 => 7200
    apc.use_request_time => On => On
    apc.writable => /tmp => /tmp

But when i try to use either of them it crashes php

    caesar~$ php -a
    Interactive shell

    php > $a = apc_fetch('a');
    PHP Warning:  Uncaught Error: Call to undefined function apc_fetch() in php shell code:1
    Stack trace:
    #0 {main}
      thrown in php shell code on line 1

I also have xdebug installed and it wont work.

*Updated because i think i made a mistake with memcached, but still having problems with apcu*

**Comment by alcaeus** [comment]
`apc_fetch` is provided by `ext-apc`. Since you installed `ext-apcu` you want to use the `apcu_*` methods: https://secure.php.net/apcu.

As for memcached, are you sure you want to use [memcached](https://secure.php.net/memcached) and not [memcache](https://secure.php.net/memcache)? Same thing as with apcu - use the appropriate classes/methods.

**Comment by mcfedr** [comment]
I thought apcu was supposed to replace the old apc extension? I have installed it using `brew install php70-apcu --with-apc-bc` but there are only `apcu_*` functions, no `apc_*`

**Comment by alcaeus** [comment]
Oh, you're right, I didn't see that. I've just noticed the warning in [the docs](https://secure.php.net/manual/en/apcu.installation.php):
> PHP 7 has a separate module (» apc.so) for backwards compatibility with APC.

Could it be that if `--with-apc-bc` is set the `apc.so` module needs to be registered as well?

**Comment by mcfedr** [comment]
Uninstalled and reinstalled with `--with-apc-bc` which would appear to be whats needed, but no luck, still no `apc_*` functions. The full set of `apcu_*` functions are available, but the bc side of this is somewhat important.

**Comment by mcfedr** [comment]
It seems that apcu has since split out backwards compatibility into a separate repo/module, that also need to be built and installed, https://github.com/krakjoe/apcu-bc

Seems we need to add a new package for apcu-bc

**Comment by mcfedr** [comment]
Make a pull request that fixes this problems https://github.com/Homebrew/homebrew-php/pull/2719

**Comment by tuliomarchetto** [comment]
`brew install php71-apcu-bc` worked for me
