### ISSUE TITLE
php70-tidy (El Capitan): Unable to load dylib

### ISSUE THREAD

**Issue by yaykyle** [Homebrew/homebrew-php#2720]
Freshly installed php70 today, but Tidy is throwing errors. Have tried reinstalling a few times.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.11.2 (15C50)
**Homebrew Version:** | Homebrew 0.9.5 (git revision b6f9d; last commit 2016-01-06)
**PHP Version in use:** | PHP 7.0.1 (cli) (built: Dec 18 2015 19:20:08) ( NTS )
**Xcode Version:** | Version 7.2 (7C68)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 <br> Apple LLVM version 7.0.2 (clang-700.1.81) <br> Target: x86_64-apple-darwin15.2.0 <br> Thread model: posix
**Output of php -v:** | https://gist.github.com/yaykyle/57add42a061cb0566845
**Output of brew install -v /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php70-tidy.rb within a gist** | https://gist.github.com/yaykyle/61809833b6204e4d9796
**Output of brew doctor within a gist** | https://gist.github.com/yaykyle/b82f2911546d6fad39fd

**Comment by javian** [comment]
What does php -i output ?

**Comment by javian** [comment]
Did you manage to solve this @yaykyle ?

**Comment by yaykyle** [comment]
Hi! Sorry for the delay, I missed the notice. I tried reinstalling today and it worked fine. Something must have been changed! :)
