### ISSUE TITLE
brew install php56

### ISSUE THREAD

**Issue by magicians** [Homebrew/homebrew-php#2760]
==> Installing dependencies for homebrew/php/php56-mcrypt: php56
==> Installing homebrew/php/php56-mcrypt dependency: php56
==> Downloading https://php.net/get/php-5.6.17.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.17
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.17 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-conf
Last 15 lines from /Users/meilunzhi/Library/Logs/Homebrew/php56/01.configure:
--enable-zend-signals

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking build system type... x86_64-apple-darwin15.2.0
checking host system type... x86_64-apple-darwin15.2.0
checking target system type... x86_64-apple-darwin15.2.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/php5620160109-31032-1ufcvzm/php-5.6.17':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by magicians** [comment]
☁  tmp  brew install php56
==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.17.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.17
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.17 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-conf
Last 15 lines from /Users/meilunzhi/Library/Logs/Homebrew/php56/01.configure:
--enable-zend-signals

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking build system type... x86_64-apple-darwin15.2.0
checking host system type... x86_64-apple-darwin15.2.0
checking target system type... x86_64-apple-darwin15.2.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/php5620160109-32493-1nzt04c/php-5.6.17':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues

**Comment by ablyler** [comment]
@magicians can you run `brew update` and then try again?

**Comment by magicians** [comment]
yes I first performed the update but there was an error when I installed the program！

**Comment by christig** [comment]
I encountered the same error while attempting to install a different formula. I followed @ablyler and ran brew update and reinstalled the formula. This fixed my issue. Thanks @ablyler

**Comment by javian** [comment]
@magicians did you manage to resolve this issue ?

**Comment by javian** [comment]
Closing issue due to no response.
