### ISSUE TITLE
brew install php54 is error !

### ISSUE THREAD

**Issue by magicians** [Homebrew/homebrew-php#2761]
==> Summary
🍺  /usr/local/Cellar/php54-igbinary/1.2.1: 6 files, 50.4K
==> Installing homebrew/php/php54-redis
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.7.tar.gz
==> Downloading from https://codeload.github.com/phpredis/phpredis/tar.gz/2.2.7
######################################################################## 100.0%
==> /usr/local/opt/php54/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php54-redis/2.2.7_1 --with-php-config=/usr/local/opt/php54/bin/php-config --enable-redis-igbinary
Last 15 lines from /Users/meilunzhi/Library/Logs/Homebrew/php54-redis/02.configure:
./configure
--prefix=/usr/local/Cellar/php54-redis/2.2.7_1
--with-php-config=/usr/local/opt/php54/bin/php-config
--enable-redis-igbinary

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/php54-redis20160109-36908-osiclv/phpredis-2.2.7':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues

**Comment by ablyler** [comment]
@magicians what does `brew doctor` output?

**Comment by javian** [comment]
@magicians did you manage to resolve this issue ?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in 2+ weeks.
