### ISSUE TITLE
brew install php70-redis

### ISSUE THREAD

**Issue by magicians** [Homebrew/homebrew-php#2762]
☁  homestead  brew install php70-redis
Error: homebrew/php/php70-redis is a head-only formula
Install with `brew install --HEAD homebrew/php/php70-redis`
☁  homestead  brew install --HEAD homebrew/php/php70-redis
==> Installing php70-redis from homebrew/php
==> Cloning https://github.com/phpredis/phpredis.git
Cloning into '/Library/Caches/Homebrew/php70-redis--git'...
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 53 (delta 1), reused 16 (delta 0), pack-reused 0
Unpacking objects: 100% (53/53), done.
Checking connectivity... done.
==> Checking out branch php7
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-redis/HEAD --with-php-config=/usr/local/opt/php70/bin/php-config
Last 15 lines from /Users/meilunzhi/Library/Logs/Homebrew/php70-redis/02.configure:

./configure
--prefix=/usr/local/Cellar/php70-redis/HEAD
--with-php-config=/usr/local/opt/php70/bin/php-config

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/php70-redis20160109-39148-1sqqphg':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues

**Comment by ablyler** [comment]
@magicians what does `brew doctor` output?

**Comment by javian** [comment]
@magicians Did you manage to resolve this issue ?

**Comment by magicians** [comment]
@ablyler  No I try to go in the way you speak

**Comment by christoph-daehne** [comment]
The following hack made the install pass on my machine (but it is a hack).

```
which -a sed
mkdir -p /usr/local/Library/ENV/4.3
ln -s /usr/local/bin/sed /usr/local/Library/ENV/4.3/sed
```

**Comment by javian** [comment]
@christoph-daehne that was a different issue with bottles that needed to be rebuilt. @magicians did you need any further help or can we close the issue ?
