### ISSUE TITLE
mcrypt php extension required

### ISSUE THREAD

**Issue by churmi** [Homebrew/homebrew-php#2764]
I'm having a bit of an issue with install the mcrypt on my mac server. I have installed homebrew-php and installed the mcyrpt. Now, if I run php -i  i shows me that it's running. I have restarted my apache server. 

The problem is that I'm still getting "mcrypt php extension required" from my web browser.  I'm just wondering  what I'm doing wrong. I'm at a loss here.

**Comment by javian** [comment]
Is your apache config loading the homebrew-php module or the system one ? 

php -i only shows you the config for the command line tool.

**Comment by churmi** [comment]
Ok so how would I know which one  is running?

**Comment by javian** [comment]
In your apache config its defined which php module to load. In my stock osx apache config there's a line 

`LoadModule php5_module libexec/apache2/libphp5.so`

This configuration in apache needs to point to the php module in your homebrew installation.

**Comment by javian** [comment]
Did you find the setting ?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in 2+ weeks.
