### ISSUE TITLE
failed to install php56-pthreads

### ISSUE THREAD

**Issue by lly365** [Homebrew/homebrew-php#2768]
$ brew install php56-pthreads
==> Installing php56-pthreads from homebrew/php
==> Installing dependencies for homebrew/php/php56-pthreads: php56
==> Installing homebrew/php/php56-pthreads dependency: php56
==> Downloading https://php.net/get/php-5.6.17.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.17
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.17 --localstatedir=/usr/loc
Last 15 lines from /Users/ling/Library/Logs/Homebrew/php56/01.configure:
checking for uint32_t... yes
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for strtoll... no
checking for atoll... no
checking for strftime... (cached) no
checking which regex library to use... php
checking whether to enable LIBXML support... yes
checking libxml2 install dir... /usr/local/opt/libxml2
checking for xml2-config path... /usr/local/opt/libxml2/bin/xml2-config
checking whether libxml build works... no
configure: error: build test failed.  Please check the config.log for details.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues

**Comment by javian** [comment]
Did you go through the troubleshooting guide linked to at the end of the text you pasted ?

**Comment by javian** [comment]
@lly365 did you manage to resolve this issue ?

**Comment by lly365** [comment]
No



 
From: Jan Viljanen
Date: 2016-04-06 12:14
To: Homebrew/homebrew-php
CC: lly365
Subject: Re: [Homebrew/homebrew-php] failed to install php56-pthreads (#2768)
@lly365 did you manage to resolve this issue ?
