### ISSUE TITLE
travis-ci: public token

### ISSUE THREAD

**Issue by denji** [Homebrew/homebrew-php#2786]
We can use public `HOMEBREW_GITHUB_API_TOKEN` to suppress the limit for travis-ci?
* https://github.com/settings/tokens/new?scopes=&description=homebrew-php
* https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

```
==> brew audit homebrew/php/php70-… --strict --online
==> brew style php70-…
…
1 file inspected, no offenses detected
Error: GitHub API rate limit exceeded for 208.78.110.199.
(But here's the good news:
   Authenticated requests get a higher rate limit.
    Check out the documentation for more details.
)
Try again in 4 minutes 44 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: HOMEBREW_GITHUB_API_TOKEN
==> FAILED
```

![settings-env-vars](https://cloud.githubusercontent.com/assets/3759759/12523425/7d7bf306-c15f-11e5-97df-e8fbde81a73f.png)

**Comment by javian** [comment]
This also made commit #2806 fail (in 2/3) so it would be a good idea if its possible.

**Comment by javian** [comment]
@ablyler can you address this ?

**Comment by javian** [comment]
This has now been resolved - sorry for the long wait =)
