### ISSUE TITLE
PHP56 required for composer

### ISSUE THREAD

**Issue by michaeljs1990** [Homebrew/homebrew-php#2796]
This was a bug a while ago and now it seems to be back. Why is php56 a dependency for composer? I am perfectly happy with using the builtin php version from OSX.

**Comment by michaeljs1990** [comment]
I'll dig up the history later.

**Comment by javian** [comment]
It's been programmed like that and it doesn't check for the built in php as far as I can see. Don't know the reasoning behind that but maybe someone else can shine a light on the topic.

**Comment by michaeljs1990** [comment]
The thing was this was fixed momentarily at least but is now broken again. The maintainers of this repository seem to have very poor communication or short memories. I have had to come back to this repository server time for fixes that get reverted. This is a heavily used repository that requires a little more caution in updating then it currently is getting.

**Comment by javian** [comment]
@ablyler made the change, can you shine some light on this ?

**Comment by alcaeus** [comment]
> The maintainers of this repository seem to have very poor communication or short memories.

How about dialing it down a bit? There's an issue and people will help you getting it fixed if they can find out what's going on.

Now, I've done a quick checked and unlinked my PHP version from brew, with the result that I could install composer without any trouble:

```
alcaeus at hephaestus in ~ on master
$ which php
/usr/bin/php

alcaeus at hephaestus in ~ on master
$ brew install composer
==> Installing composer from homebrew/php
==> Installing dependencies for homebrew/php/composer: freetype
==> Installing homebrew/php/composer dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.6.3.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring freetype-2.6.3.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.6.3: 60 files, 2.5M
==> Installing homebrew/php/composer
==> Downloading https://homebrew.bintray.com/bottles-php/composer-1.0.0-alpha11.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/composer-1.0.0-alpha11.el_capitan.bottle.tar.gz
==> Pouring composer-1.0.0-alpha11.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/composer/1.0.0-alpha11: 3 files, 1.1M
```

I'm not keen on completely uninstalling PHP just to check this, could you provide an error message? I'll try to figure out what's going on - the history doesn't give away much at this point.

**Comment by javian** [comment]
@alcaeus the answer is in

https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb#L8-L20

currently its php70 (this changed from php56) that will be installed and it doesn't take into account any php versions provided by the os.

**Comment by alcaeus** [comment]
@javian Thanks - I was afraid that might have to do with it. Maybe this is a documentation issue? Installing any other package (e.g. `php**-*`) here will require a brew PHP package, so why shouldn't composer?

**Comment by javian** [comment]
@alcaeus possibly - I'm not sure if that was the afterthought but I agree. Technically some of the packages might do just fine with the stock php but then it needs to be designed for that and its easier to not take that into account. iirc listening to mcquaid homebrew tries not to have external dependencies and everything should be provided within its own Formulas so along that thought php also needs to be provided to fully support the package.

**Comment by alcaeus** [comment]
> iirc listening to mcquaid homebrew tries not to have external dependencies and everything should be provided within its own Formulas

I absolutely agree with that. When you assume that composer should be able to use stock PHP, why can't `php55-redis`? As such, I'd say leave the dependency resolution as is and recommend people install PHP using brew.

**Comment by josegonzalez** [comment]
@alcaeus This tap can be used with many different OS X versions, and thus the default PHP is not always the same. As well, this tap is meant to be used with the PHP *it* provides, not some random one installed via any other method, so while technically we could drop the requirements, in the interest of not making more work for volunteer maintainers, I'm 👎 on changing requirements.

If you have different installation requirements, please either contribute a patch, sponsor the work necessary to make your environment work with homebrew-php, or find another solution.

**Comment by alcaeus** [comment]
@josegonzalez I get your point, I'm all in favour of keeping the php-* requirement and force an install of a brew PHP package when installing the brew composer package. Could it be that your comment was directed at the OP? Either way, good to have this resolved.

**Comment by josegonzalez** [comment]
It's a general comment to anyone who might wonder why we made this decision and would potentially be upset at homebrew-php in the future.
