### ISSUE TITLE
error: Cannot find libz (while upgrading)

### ISSUE THREAD

**Issue by sunel** [Homebrew/homebrew-php#2807]
==> Installing homebrew/php/php56
==> Downloading https://php.net/get/php-5.6.17.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.6.17.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.17 --localstatedir=/usr/loc
Last 15 lines from /Users/sunel/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by javian** [comment]
Do you have the header file /usr/include/zlib.h on your machine ? Otherwise you need to install it through
 
`xcode-select --install`

**Comment by sunel** [comment]
Yep that worked.
