### ISSUE TITLE
<php with pthreads> failed build on 10.11.2

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-php#2810]
_From @Frozen-Shadow on January 23, 2016 13:21_

Hello !
Once I was used php with none threads safe.Now I need php with threads safe.
So,I use ``` brew install php56 --with-thread-safety``` 
Then  MySQL will report some error:
```
configure: error: Cannot find libmysqlclient_r under /usr/local.
Note that the MySQL client library is not bundled anymore!
```
I found ```libmysqlclient_r.dylib```  in ```/usr/local/lib/```,I don't know why MySQL will scanning this directory.When I reinstall php with out thread safe ,everything is ok  !!

So,I want reinstall them(redis php mysql ...),after ```brew uninstall php-xxx``` and ```brew install php-xxx```
php report some warning like this: 
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): image not found in Unknown on line 0
```
I fund all the config file in ```/usr/local/etc/php``` *were didn't remove* after ```brew uninstall```

I don't know whether you keep it for some reason or not.

My english is so poor ,I wish you can understand what I mean.Sorry to bother you.

Best Wishes!

_Copied from original issue: Homebrew/homebrew#48392_

**Comment by Frozen-Shadow** [comment]
Option ```--build-from-source``` save me.
Just ```brew reinstall php56-xxxx --build-from-source```,everything is ok.

**Comment by DomT4** [comment]
Great! Thanks for letting us know @Frozen-Shadow. Please shout if you run into any other issues :)
