### ISSUE TITLE
not able to configure oci8

### ISSUE THREAD

**Issue by rahthakor** [Homebrew/homebrew-php#2826]
<problem description>

Parameter | Value
------------------ | ------------------
**OS X Version:** | <10.11.2>
**Homebrew Version:** | Homebrew 0.9.5
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
**Output of php -v:** | PHP 5.6.17 (cli) (built: Jan  8 2016 10:27:48) 
**Output of brew doctor within a gist** | Your system is ready to brew.

Check things i have done https://gist.github.com/rahthakor/00206751d1acab953cf8
only thing coming to my mind is php -v cli is 5.6.17 and pear version cli php version is 5.6.14
i don't get it how that happened.

if any other stuff required than let me know.

**Comment by javian** [comment]
It could be that you have at least 2 different php versions installed and that pear uses the old one. Did you install 5.6.17 using

`brew install --with-pear php56` ?

**Comment by javian** [comment]
Reading through the options again there's a switch on the php56 formula called

`--with-pdo-oci`

can't you just use that ?

**Comment by rahthakor** [comment]
i tried after removing all versions.. but didn't work..

usually i do brew update followed by brew upgrade which downloads newer version of php when it is available. now i do have 5.6.18 and i have removed all other previous installed versions
because of brew upgrade multiple php versions are there. and whenever i enable extension=oci.so in php.ini file i get dynamic linking warning

**Comment by javian** [comment]
@rahthakor did you manage to resolve this issue ?

**Comment by rahthakor** [comment]
@javian no, I was not able to solve this issue.
I had done some search on that and it says that while upgrading PHP through brew oracle instant library should not be symlinked as mention in oracle client installation that is in usr/lib.

**Comment by javian** [comment]
@rahthakor and you still have different php versions when using pear and regular cli do you ?
Can you post the output of php -i ?

**Comment by rahthakor** [comment]
no, actually I have removed all php version 
I only have inbuilt version of php
php --version output
PHP 5.5.30 (cli) (built: Oct 23 2015 17:21:45)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by javian** [comment]
@rahthakor so does that mean you issue is resolved since you are no longer using the brewed php ?

**Comment by rahthakor** [comment]
@javian yeah. I have started using Oracle NodeJS Module(node-oracledb).
which is satisfying my current need and I'm sure for future needs also.
I have tried my best to resolve PHP issue but couldn't succeed

**Comment by javian** [comment]
Since you've moved on I'm going to close this issue since I don't have any way of testing this at the moment. Feel free to reopen the issue at a later stage if you want us to have another go at this.
