### ISSUE TITLE
homebrew/php/php55 5.5.32 upgrade: configure: error: Cannot find libz 

### ISSUE THREAD

**Issue by thorstensiefert** [Homebrew/homebrew-php#2853]
While brew upgrade got the following message (https://gist.github.com/2a87c993cdb327aecf55):
==> Upgrading homebrew/php/php55
==> Downloading https://php.net/get/php-5.5.32.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.5.32.tar.bz2
######################################################################## 100.0%
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.32 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.5 --with-config-file-path=/usr/local/etc/php/5.5 --with-config-file-scan-dir=/usr/local/etc/php/5.5/conf.d --mandir=/usr/local/Cellar/php55/5.5.32/share/man --enable-bcmath --enable-calendar --enable-dba --enable-exif --enable-ftp --enable-gd-
Last 15 lines from /Users/thorstensiefert/Library/Logs/Homebrew/php55/01.configure:
checking for Kerberos support... /usr
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by awesomebing1** [comment]
I'm getting the same error.

**Comment by AbeEstrada** [comment]
Run `xcode-select --install` to fix this, I guess this happens after every Xcode update

Source: https://github.com/Homebrew/homebrew-php/issues/1946

**Comment by thorstensiefert** [comment]
Great! Works fine now! 
Thx!
