### ISSUE TITLE
php55-redis

### ISSUE THREAD

**Issue by elmosgot** [Homebrew/homebrew-php#2878]
Failing installation when running on a clean brew environment:
`# brew install php55-redis`

I got the following error message:
`Error: No such file or directory - /usr/local/opt/igbinary/include/igbinary.h`

Solution
The php55-igbinary depends on igbinary and that wasn't installed:
`# brew install homebrew/php/igbinary`

After installing the 'igbinary', I tried again to install 'php55-redis' and this time I didn't receive any error and the redis extension got installed properly.

**Comment by javian** [comment]
I can replicate this in my environment. Might have something to do with the build only dependency that php55-igbinary has to igbinary that then gets lost when its bottled but I haven't had time to verify this.

**Comment by javian** [comment]
This should have been fixed now.
