### ISSUE TITLE
phpmyadmin 4.5.5 fails to check php dependency correctly

### ISSUE THREAD

**Issue by dorapen** [Homebrew/homebrew-php#2905]
When I try to update/upgrade phpmyadmin to 4.5.5, it tries to install lower version of php than currently installed version.
For example, I have php70 installed, and phpmyadmin tries to install php56 (which doesn't proceed as it conflicts with php70).

> ==> Upgrading homebrew/php/phpmyadmin
> ==> Installing dependencies for homebrew/php/phpmyadmin: php56
> ==> Installing homebrew/php/phpmyadmin dependency: php56
> Error: Cannot install homebrew/php/php56 because conflicting formulae are installed.
> 
>   php70: because different php versions install the same binaries.
> 
> Please `brew unlink php70` before continuing.
> 
> Unlinking removes a formula's symlinks from /usr/local. You can
> link the formula again after the install finishes. You can --force this
> install, but the build may fail or cause obscure side-effects in the
> resulting software.

If I unlink php70 and try again, it will install php56, and it again fails complaining php56-mcrypt is missing.

> ==> Installing homebrew/php/phpmyadmin
> Error: /usr/local/opt/php56-mcrypt not present or broken
> Please reinstall homebrew/php/php56-mcrypt. Sorry :(

So I also manually installed php56-mcrypt and gave another try, but now it tried to install php55, complaining it's conflicting with php56, and so on.
I also tried reinstalling php70 but same thing happened again.

Seems like formula for dependency check has a problem?

**Comment by dorapen** [comment]
Update:
Upgrading didn't work, but uninstalling phpmyadmin and reinstalling with brew install phpmyadmin worked.

**Comment by BarbUk** [comment]
I have the same problem with multiple php formulas.

If I brew upgrade like this:
`brew update && brew upgrade --all`

> ==> Upgrading homebrew/php/psysh
> ==> Installing dependencies for homebrew/php/psysh: php70
> ==> Installing homebrew/php/psysh dependency: php70
> Error: Cannot install homebrew/php/php70 because conflicting formulae are installed.
> 
>   php56: because different php versions install the same binaries.
> 
> Please `brew unlink php56` before continuing.

But if I upgrade the formulae directly, It works
`brew upgrade homebrew/php/psysh`
