### ISSUE TITLE
homebrew/php/php70

### ISSUE THREAD

**Issue by ycxfuture** [Homebrew/homebrew-php#2925]
details

`
xxxxx-Pro:~ xxxxx $ brew upgrade
==> Upgrading 2 outdated packages, with result:
homebrew/php/composer 1.0.0-beta1, homebrew/php/php70 7.0.4
==> Upgrading homebrew/php/composer
==> Installing dependencies for homebrew/php/composer: php70
==> Installing homebrew/php/composer dependency: php70
==> Downloading https://php.net/get/php-7.0.4.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php70-7.0.4
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.4 --localstatedir=/usr/loca
Last 15 lines from /Users/xxxxx/Library/Logs/Homebrew/php70/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues

`

**Comment by MikeCoder** [comment]
Same situation, Here is my detail output.
```
==> Upgrading homebrew/php/composer
==> Installing dependencies for homebrew/php/composer: php70
==> Installing homebrew/php/composer dependency: php70
==> Downloading https://php.net/get/php-7.0.4.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php70-7.0.4
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.4 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/etc/php/7.0 --with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d --mandir=/u
Last 15 lines from /Users/Mike/Library/Logs/Homebrew/php70/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
```

**Comment by javian** [comment]
You need to run

`xcode-select --install`

and try it again.

**Comment by ntwb** [comment]
I just arrived at this whilst `php70` was needed as a dependancy for `phpbrew`

Any way of having that `xcode-select --install` be displayed as a notice when `php70` install fails?
