### ISSUE TITLE
brew upgrade :: homebrew/php/composer :: Cannot find libz

### ISSUE THREAD

**Issue by walterdolce** [Homebrew/homebrew-php#2932]
Hi all,

Something unusual happened today when I did my `brew doctor; brew update; brew upgrade` routine.
While upgrading, this happened at some point:

```
$ brew upgrade
==> Upgrading 2 outdated packages, with result:
homebrew/php/composer 1.0.0-beta1, homebrew/php/php56 5.6.19
==> Upgrading homebrew/php/composer
==> Installing dependencies for homebrew/php/composer: php56
==> Installing homebrew/php/composer dependency: php56
==> Downloading https://php.net/get/php-5.6.19.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.19
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.19 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-conf
Last 15 lines from /Users/{MYUSER}/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues
```
Note that `{MYUSER}` in the output above is a substitution I made.

This causes `brew upgrade` to always try to update the packages above without success. Any further info you need please let me know. :beers:

**Comment by walterdolce** [comment]
Ah, before you ask, `brew doctor` is happy while the above happens.

**Comment by bjornpost** [comment]
See: https://github.com/Homebrew/homebrew-php/issues/2929

**Comment by walterdolce** [comment]
Thanks. I did the installation through the UI, still having the issue.

**Comment by walterdolce** [comment]
I did `brew gist-logs php56` in the mean time - https://gist.github.com/anonymous/96c189a43ccd4983397d

**Comment by javian** [comment]
could you try re-running

`xcode-select --install`

I haven't been able to verify it but I think I've had instances where running it once was not enough.

**Comment by walterdolce** [comment]
Hi @javian, I can't. The command suggests to install via Apple's developer portal. I installed the latest (beta) version of Xcode, but I'm still getting the same error.

**Comment by javian** [comment]
@walterdolce does /usr/include/zlib.h exists on your machine ?
Which OS version are you on ?

**Comment by walterdolce** [comment]
@javian nope. I'm on OS X El Capitan 10.11.3.

**Comment by javian** [comment]
That's really weird. The /usr/include directory comes with the CLT (command line tools) which according to the gist logs is not installed. I think the only way for you to solve it is to solve why the CLT can't be installed.

**Comment by ghkdev** [comment]
Having same problem, so reran
   xcode-select --install
and all appears to now work,

**Comment by edi-design** [comment]
confirmed, rerun
`xcode-select --install`
solved the problem

**Comment by louisroy** [comment]
Manually downloading the [CLT from Apple Developers website](https://developer.apple.com/downloads/?name=command%20line) did the trick for me.

CLT wouldn't download or install with ``xcode-select --install``, but the rest of Xcode did for some reason.

**Comment by Kjir** [comment]
I had the same issue since I had Xcode installed. I then also installed the CLT and it solved the issue.
Please refer to this: http://superuser.com/questions/995360/missing-usr-include-in-os-x-el-capitan (note that the correct answer is not the accepted one, as stated in the update)

**Comment by walterdolce** [comment]
By installing CLT from the Apple Developer portal, as mentioned by @louisroy, the issue resolved for me. Closing the case. Thank you all :beers:
