### ISSUE TITLE
Composer XDebug

### ISSUE THREAD

**Issue by TomK** [Homebrew/homebrew-php#2937]
I replace my `/usr/local/bin/composer` with the following to discover all ini files and sed out any xdebug lines.  It's a bit rough and still needs to execute some php to get the loaded ini files, but it seems to work.  Perhaps someone else can refine it, `php --ini` maybe?

It is homebrew which creates `/usr/local/bin/composer` isn't it?

```
#!/usr/bin/env bash

TEMP_PATH="$( mktemp -t php-no-debug )"
FILES="$( php -r 'echo php_ini_loaded_file() . "\n" . str_replace(",","", php_ini_scanned_files());' )"
cat $FILES | sed '/xdebug/d' > "$TEMP_PATH"

/usr/bin/env php -n -c "$TEMP_PATH" -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.0.0-beta1/libexec/composer.phar "$@"

rm -f "$TEMP_PATH"
```

**Comment by javian** [comment]
There's a similar PR in #2536 for phpunit - something similar could be done for composer.

**Comment by TomK** [comment]
Closing.  Thank you for merging #3174

**Comment by javian** [comment]
We need to rethink how to do this and not make it mandatory since in some use cases it is useful as pointed out in #3230 .

**Comment by TomK** [comment]
I believe @sharpner is using "ext-xdebug" in his require-dev section to ensure his collaborators have xdebug installed.  I'm not sure why else he would need it in there, perhaps he can clarify this?

Regardless, it's a fair point that basic execution should match the original release.
We could add an argument to the wrapper for disabling xdebug, but that's not very usable.  Alternatively a build flag on the formula to reinstate this (or equivalent) method as @sharpner suggested.

Many people are looking for a way to disable xdebug under composer in order to avoid the performance hit (see linked issues). Which is why composer give instructions on doing so https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer.  It is my understanding that there is no advantage to running composer with xdebug, unless you are debugging composer itself.

This may turn out to be a situation where we cannot please 100% of people 100% of the time.

**Comment by sharpner** [comment]
true, we use debugging in our development environment. Therefore xdebug is mandatory. Thanks for looking into this issue.

**Comment by josegonzalez** [comment]
I'm going to close this. If you want to run composer without xdebug, uninstall xdebug or disable it manually.
