### ISSUE TITLE
Upgrade from PHP 5.6.18 to 5.6.19 - make: *** [install-sapi] Error 1

### ISSUE THREAD

**Issue by markhilton** [Homebrew/homebrew-php#2938]
To be clear I use Nginx, no Apache. 

bash-3.2$ brew upgrade
==> Upgrading 3 outdated packages, with result:
homebrew/php/composer 1.0.0-beta1, homebrew/php/php56 5.6.19, homebrew/php/php56-mcrypt 5.6.19
==> Upgrading homebrew/php/composer
==> Installing dependencies for homebrew/php/composer: php56
==> Installing homebrew/php/composer dependency: php56
==> Downloading https://php.net/get/php-5.6.19.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.6.19.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.19 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-scan-dir=/usr/local/etc/php/5.6/conf.d --mandir=/usr/local/Cellar/php56/5.6.19/share/man --e
==> make
==> make install
Last 15 lines from /Users/username/Library/Logs/Homebrew/php56/03.make:
2016-03-07 15:19:37 -0500

make install

Installing PHP SAPI module:       apache2handler
/usr/share/httpd/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1/build-1/libtool' libs/libphp5.so /usr/local/Cellar/php56/5.6.19/libexec/apache2
/usr/share/apr-1/build-1/libtool --mode=install install libs/libphp5.so /usr/local/Cellar/php56/5.6.19/libexec/apache2/
libtool: install: install libs/libphp5.so /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so
Warning!  dlname not found in /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so
apxs:Error: Config file /private/etc/apache2/httpd.conf not found.
make: *** [install-sapi] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues

==> Upgrading homebrew/php/php56-mcrypt
==> Installing dependencies for homebrew/php/php56-mcrypt: php56
bash-3.2$ php -v
PHP 5.6.18 (cli) (built: Feb  6 2016 06:53:53)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader v5.0.17, Copyright (c) 2002-2015, by ionCube Ltd.
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

**Comment by javian** [comment]
In that case you should use the option `--without-apache` option and it won't try to install the apache module.

**Comment by javian** [comment]
@markhilton did you manage to resolve this issue ?

**Comment by Rocketship1** [comment]
@javian I cannot remember now exactly, but I think the issue was symlinks to php.ini, which point to single file for all environments: CLI, web etc. Once I removed symlinks and created individual php.ini for each upgrade went through without the problem.

**Comment by javian** [comment]
@Rocketship1 are you and the op the same person ?

**Comment by javian** [comment]
Closing due to no response.
