### ISSUE TITLE
GearmanWorker automatic recovery a fail server bug

### ISSUE THREAD

**Issue by breath-co2** [Homebrew/homebrew-php#2943]
code:
```php
$gmWorker = new GearmanWorker();
$gmWorker->setId("myid");
$gmWorker->addServers('192.168.1.2,192.168.1.3');
$gmWorker->addFunction('test', function() {
//...
});
while (@$gmWorker->work()) {
    if ($gmWorker->returnCode() !== GEARMAN_SUCCESS) {
        break;
    }
}
```

bugs:

1. when I stop and start 192.168.1.2's gearmand server, I found in 192.168.1.2 don't have any worker.
2. Then next if I restart 192.168.1.3's gearmand server, 192.168.1.2 have found the test worker, but lost "myid", and 192.168.1.3 don't have any worker.

**Comment by ablyler** [comment]
@breath-co2 please open this issue with the gearman project @ https://groups.google.com/forum/#!forum/gearman
