### ISSUE TITLE
"brew upgrade" fails: php56 conflicting with php70 when upgrading phpmyadmin

### ISSUE THREAD

**Issue by DiesIrae** [Homebrew/homebrew-php#2945]
`brew upgrade` failed, but `brew upgrade phpmyadmin` worked though, which is quite strange. So everything was fine at the end, but I wanted to report this error because it arrives at every phpmyadmin new update, and maybe it affects other brew-lovers.

Here is my brew upgrade fail:

```
==> Upgrading 1 outdated package, with result:
josegonzalez/php/phpmyadmin 4.5.5.1
==> Upgrading josegonzalez/php/phpmyadmin
==> Installing dependencies for josegonzalez/php/phpmyadmin: php56
==> Installing josegonzalez/php/phpmyadmin dependency: php56
Error: Cannot install josegonzalez/php/php56 because conflicting formulae are installed.

  php70: because different php versions install the same binaries.

Please `brew unlink php70` before continuing.
```

Before you ask, `brew doctor` is fine and the relevant part of my `brew info` is:
`php70-mcrypt phpmyadmin mcrypt mysql php70`

**Comment by ablyler** [comment]
@DiesIrae what if you run: `brew unlink php70` and `brew link php56`?

**Comment by DiesIrae** [comment]
I did not try this actually (insubordination ?). I'm not at ease with these brew functions, and it did not felt right. Woudn't I have to install php56 first ?

And by the way, what I would like to point here, is the incoherence between `brew upgrade phpmyadmin`, and a simple `brew upgrade`, which, in that case where only phpmyadmin should be updated, should exactly produce the same result. Shouldn't it ?

**Comment by dorapen** [comment]
I had same issue and indeed submitted issue [#2905](https://github.com/Homebrew/homebrew-php/issues/2905).
brew reinstall phpmyadmin worked for me, but it definitely needs to be fixed.

**Comment by m-urban** [comment]
Same here. @dorapen's suggestion fixed it for me, too.

**Comment by CFXd** [comment]
`brew reinstall phpmyadmin` helped thanks to @dorapen but this is still an issue.

**Comment by javian** [comment]
This issue should be fixed now with a recent commit https://github.com/Homebrew/homebrew-php/commit/9ffa02f3e22edcaaca48475e56cd62134dbb410f
