### ISSUE TITLE
homebrew/php/php53 failed to build on Ubuntu 15.10

### ISSUE THREAD

**Issue by mosgjig** [Homebrew/homebrew-php#2946]
https://gist.github.com/bdb38fece2f50a896013

**Comment by javian** [comment]
There's a configure error in those logs

`configure: error: can only configure for one host and one target at a time`

google suggests that's its unlikely that it has anything to do with homebrew and you need to look closer at your system compiling.

**Comment by mosgjig** [comment]
@javian Thanks for your response.  
My apologies for the vague issue description, but yes i'm aware of the error and did research prior to opening the issue.  Was hoping somebody with more knowledge could shed some light for I'm a novice when it comes to php and homebrew / linuxbrew.

**Comment by javian** [comment]
@mosgjig if you add --verbose to the install command - do you get any additional clues ?

**Comment by mosgjig** [comment]
@javian we moved to a different approach.  A colleague of mine successfully installed php53 on centOS 6.7 and has it setup via vagrant.

Thanks for your help!

**Comment by javian** [comment]
@mosgjig ok! can you please close the issue if you if you don't require further help =)
