### ISSUE TITLE
fatal error: 'tidybuffio.h' file not found when trying to install php55-tidy

### ISSUE THREAD

**Issue by Jacketbg** [Homebrew/homebrew-php#2958]
I just upgraded my `php55` version to `5.5.33` and when trying to install `php55-tidy` I get this error:

```
==> Installing php55-tidy from homebrew/php
==> Downloading https://php.net/get/php-5.5.33.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-tidy-5.5.33
==> /usr/local/opt/php55/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php55-tidy/5.5.33 --with-php-config=/usr/local/opt/php55/bin/php-config --with-tidy=/usr/local/opt/tidy-html5
==> make
Last 15 lines from /Users/Jacket/Library/Logs/Homebrew/php55-tidy/03.make:
2016-03-12 16:40:18 +0200

make

/bin/sh /private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/libtool --mode=compile clang  -I. -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy -DPHP_ATOM_INC -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/include -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/main -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy -I/usr/local/Cellar/php55/5.5.33/include/php -I/usr/local/Cellar/php55/5.5.33/include/php/main -I/usr/local/Cellar/php55/5.5.33/include/php/TSRM -I/usr/local/Cellar/php55/5.5.33/include/php/Zend -I/usr/local/Cellar/php55/5.5.33/include/php/ext -I/usr/local/Cellar/php55/5.5.33/include/php/ext/date/lib -I/usr/local/opt/tidy-html5/include  -DHAVE_CONFIG_H  -g -O0   -c /private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/tidy.c -o tidy.lo
mkdir .libs
 clang -I. -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy -DPHP_ATOM_INC -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/include -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/main -I/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy -I/usr/local/Cellar/php55/5.5.33/include/php -I/usr/local/Cellar/php55/5.5.33/include/php/main -I/usr/local/Cellar/php55/5.5.33/include/php/TSRM -I/usr/local/Cellar/php55/5.5.33/include/php/Zend -I/usr/local/Cellar/php55/5.5.33/include/php/ext -I/usr/local/Cellar/php55/5.5.33/include/php/ext/date/lib -I/usr/local/opt/tidy-html5/include -DHAVE_CONFIG_H -g -O0 -c /private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/tidy.c  -fno-common -DPIC -o .libs/tidy.o
/private/tmp/php55-tidy20160312-55957-webj5f/php-5.5.33/ext/tidy/tidy.c:34:10: fatal error: 'tidybuffio.h' file not found
#include "tidybuffio.h"
         ^
1 error generated.
make: *** [tidy.lo] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-php/issues
```

I did `brew update && brew update && brew doctor`, no luck.

I've found a similar issue for `php56` - #2060. Not sure if it's related.

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.11.3
**Homebrew Version:** | 0.9.5 (git revision 569c4; last commit 2016-03-11)
**PHP Version in use:** | 5.5.33
**Xcode Version:** | 7.2.1
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 7.0.2 (clang-700.1.81) Target: x86_64-apple-darwin15.3.0 Thread model: posix
**Output of php -v:** | PHP 5.5.33 (cli) (built: Mar 12 2016 16:33:41) (DEBUG) Copyright (c) 1997-2015 The PHP Group Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/Jacketbg/bd74c97aa0e8a9a9ef2f
**Output of brew doctor within a gist** | https://gist.github.com/Jacketbg/eee737c721fe7ce9382a

**Comment by javian** [comment]
Can you check if you have the tidybuffio.h file in /usr/local/opt/tidy-html5/include ?

**Comment by Jacketbg** [comment]
Just checked, but it's not there:

`ls: /usr/local/opt/tidy-html5/include/tidybuffio.h: No such file or directory`

**Comment by javian** [comment]
Ok can you also do

`brew info html5-tidy`

the package seems to be installed since the formula would have complained otherwise but since the file is missing then I'm not sure what is up.

**Comment by Jacketbg** [comment]
Hm, this is what I'm getting:

```
$ brew info html5-tidy
Error: No available formula with the name "html5-tidy"
```

Interestingly I had a fully working setup before I upgraded to php `5.5.33`. Somehow `php55-tidy` was installed.

**Comment by Jacketbg** [comment]
OK I noticed that I have 3 versions of `tidy-html5` lying around. Uninstalled it and installed again and this seems to have fixed it :+1:

Thanks for the pointers! I wonder why this happens. I don't do anything funny with homebrew, just the normal install/upgrade.

**Comment by javian** [comment]
You're welcome. Yes it does sound strange but now that you're corrected everything it might be difficult to find out why =). Please close the issue if you feel its resolved.

**Comment by Jacketbg** [comment]
Ah sorry, I needed to get my environment up and running yesterday, that's why I rushed to try this solution.
Thanks for your help!
