### ISSUE TITLE
composer.phar symlink missing

### ISSUE THREAD

**Issue by kliker** [Homebrew/homebrew-php#2959]
Upon installation, the composer.phar file is not symlinked from /usr/local/bin

$ ls -ll /usr/local/bin/composer*

`lrwxr-xr-x  1 aleks  wheel  43 Mar 13 21:14 /usr/local/bin/composer -> ../Cellar/composer/1.0.0-beta1/bin/composer`

$ ls -ll /usr/local/Cellar/composer/1.0.0-beta1/libexec
```
-rwxr-xr-x  1 aleks  staff      147 Mar 13 21:14 composer
-rw-r--r--  1 aleks  staff  1576717 Mar 13 21:14 composer.phar
```

**Comment by javian** [comment]
This is normal behaviour since every phar is installed with a wrapper. See https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php-phar.rb#L25-L30 for further details.

**Comment by kliker** [comment]
Sure but there should be an exception for `composer.phar` like we had [before](https://github.com/Homebrew/homebrew-php/commit/cea7de9ae92d6b6603ea52accbef5c50ddaf6d72) phar logic was abstracted. 

A common case for this is running Composer via HHVM which requires Composer PHP archive:

`$ hhvm /usr/local/bin/composer.phar update`

**Comment by javian** [comment]
True. I'm not sure what the logic design was intended to support though. You can work around it by making an alias doing something like

```hhvm `brew list composer | grep composer.phar` update```

**Comment by kliker** [comment]
This will do it, thanks!

**Comment by javian** [comment]
Please close the issue if you feel it has been resolved =)
