### ISSUE TITLE
Symbol not found: _ap_unixd_config\n  Referenced from: /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so

### ISSUE THREAD

**Issue by afarber** [Homebrew/homebrew-php#3008]
Hello,

I am trying to use brew on Mac OSX 10.11.3 and have installed:

```
# brew list
apr		autoconf	gettext		icu4c		libpng		openssl		php56-pdo-pgsql	readline	zlib
apr-util	freetype	httpd22		jpeg		libxml2		php56		postgresql	unixodbc
# brew services list
Name       Status  User    Plist
httpd22    started afarber /Users/afarber/Library/LaunchAgents/homebrew.mxcl.httpd22.plist
php56      started afarber /Users/afarber/Library/LaunchAgents/homebrew.mxcl.php56.plist
postgresql started afarber /Users/afarber/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

```
The Apache runs okay, I am able to open http://127.0.0.1:8080

However then I try to activate php by add the following line to the file /usr/local/etc/apache2/2.2/httpd.conf:

`LoadModule php5_module /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so
`

And then Apache fails to start and I see the error:

```
 # ll /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so
-rwxr-xr-x  1 afarber  admin  11447232 13 Mär 19:36 /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so
# apachectl configtest
httpd: Syntax error on line 117 of /usr/local/etc/apache2/2.2/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so into server: dlopen(/usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so, 10): Symbol not found: _ap_unixd_config\n  Referenced from: /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so\n  Expected in: /usr/local/Cellar/httpd22/2.2.31/bin/httpd\n in /usr/local/Cellar/php56/5.6.19/libexec/apache2/libphp5.so
```

I have tried "brew update", "brew doctor", Xcode CLI update and reboot several times.

Any help please?

Thank you
Alex

**Comment by afarber** [comment]
Updating to httpd24 has helped, now Apache + PHP 5.6 work

**Comment by javian** [comment]
I think this is because El Capitan is bundled with Apache 2.4 and if you use apache 2.2 then you need to install php with `--with-homebrew-apxs` otherwise it will compile the module for apache 2.4 instead of 2.2 and that's why you get the error.

**Comment by coredumperror** [comment]
Sadly, the `--with-homebrew-apxs` flag causes a compile error regarding freetype.h, as mentioned in several other issues on here. I've yet to find a working solution to that compile error.

**Comment by javian** [comment]
@coredumperror I don't get that error myself. Which version of PHP are you compiling and where is your freetype.h file located ?

**Comment by coredumperror** [comment]
I was trying to install php53, and my freetype.h is at `/usr/local/include/freetype2/freetype/freetype.h `

I ultimately gave up on php53 and installed php56 without issue.

**Comment by javian** [comment]
Ah yes, I saw you commented on #3014 which needs to be resolved for php53 to compile. I do see the compilation error with php53.

**Comment by javian** [comment]
@afarber did you manage to solve this issue ?

**Comment by josegonzalez** [comment]
@javian I've added you as a collaborator on this repo.

**Comment by afarber** [comment]
I have installed httpd2.4

**Comment by javian** [comment]
@josegonzalez thanks! I'll make the best of it =)
