### ISSUE TITLE
freetype not working on php55

### ISSUE THREAD

**Issue by pmartens** [Homebrew/homebrew-php#3010]
We are using php55 and in the PHP GD library, freetype isn't supported. When I run var_dump(gd_info()); It gives the following info:

array(11) { ["GD Version"]=> string(26) "bundled (2.1.0 compatible)" ["FreeType Support"]=> bool(false) ["T1Lib Support"]=> bool(false) ["GIF Read Support"]=> bool(true) ["GIF Create Support"]=> bool(true) ["JPEG Support"]=> bool(true) ["PNG Support"]=> bool(true) ["WBMP Support"]=> bool(true) ["XPM Support"]=> bool(false) ["XBM Support"]=> bool(true) ["JIS-mapped Japanese Font Support"]=> bool(false) }

Where you can see that FreeType support has the value false. 

what we are doing wrong or is this a bug!?

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.11.3
**Homebrew Version:** | Homebrew 0.9.5 (git revision 2fd40; last commit 2016-03-22)
**PHP Version in use:** | pphp55
**Xcode Version:** | <your Xcode version>
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
**Output of php -v:** | PHP 5.5.30 (cli) (built: Oct 23 2015 17:21:45) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
**Output of brew doctor within a gist** | Your system is ready to brew.

**Comment by pmartens** [comment]
We already reinstall php55 with freetypes version 2.6.3, 2.6.1 and 2.5.1. But nothing helped..

**Comment by javian** [comment]
The latest php55 version in homebrew is 5.5.33 and your cli indicates that you are using 5.5.30 which is what comes with El Capitan. It seems that your path is not picking up the right php version which would explain why the freetype module is not there.

**Comment by javian** [comment]
@pmartens did you manage to solve your problem ?

**Comment by pmartens** [comment]
Today I have reinstall php55 again on my machine and when I now check my php version in console, the following error I get on screen:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll' - dlopen(/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll' - dlopen(/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll, 9): image not found in Unknown on line 0
PHP 5.5.34 (cli) (built: Mar 31 2016 14:37:20) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by pmartens** [comment]
On apache the freetype font still isn't supported:
`ray(11) { ["GD Version"]=> string(26) "bundled (2.1.0 compatible)" ["FreeType Support"]=> bool(false) ["T1Lib Support"]=> bool(false) ["GIF Read Support"]=> bool(true) ["GIF Create Support"]=> bool(true) ["JPEG Support"]=> bool(true) ["PNG Support"]=> bool(true) ["WBMP Support"]=> bool(true) ["XPM Support"]=> bool(false) ["XBM Support"]=> bool(true) ["JIS-mapped Japanese Font Support"]=> bool(false) }`

**Comment by javian** [comment]
@pmartens can you do `php -i | grep FreeType` and check the output ?
If it says `FreeType Support => enabled` Apache is not loading the right php module and you have to adjust the path in the apache config. 

As for your dynamic load library problem you are trying to load a windows DLL on OSX which won't work since it is incompatible and you need to comment those rows out in the php config.

**Comment by javian** [comment]
@pmartens any progress on this issue ?

**Comment by pmartens** [comment]
Hi Jan,

I have it worked now! After reinstall of php55 with new version 5.5.40. Everything works fine with freetype.
Only when I asked the php version the following windows dll’s still appears.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll' - dlopen(/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll' - dlopen(/usr/local/Cellar/php55/5.5.34/lib/php/extensions/no-debug-non-zts-20121212/php_gd2.dll, 9): image not found in Unknown on line 0
PHP 5.5.34 (cli) (built: Mar 31 2016 14:37:20) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by javian** [comment]
Glad to hear its working! You must have editied your config and removed a comment or added that line about the gd2 dll when troubleshooting so just edit that out and the error message should go away. /usr/local/etc/php/5.5/... it should in there.

**Comment by pmartens** [comment]
Thank Jan!! I overlooked it. The problem is fully resolver.

Greetings
