### ISSUE TITLE
php53: multi-sapi patch wrecks the formerly correct freetype path in configure script

### ISSUE THREAD

**Issue by pschulz** [Homebrew/homebrew-php#3014]
@ablyler 
https://gist.githubusercontent.com/ablyler/c0264742cc1cca84b708/raw/a5c5c5c689acc003b5db6a9703b4f7d1d586a593/multi-sapi-5.3.29-homebrew.patch around line 10600 the path is set to the wrong location. 

The latest freetype 2.6.3 places freetype.h in $i/include/freetype2/freetype/freetype.h, so there is no need to change that.

**Comment by pschulz** [comment]
Found the solution on https://bugs.php.net/bug.php?id=66328

> Description:
------------
PROBLEM:
When compiling against freetype 2.5.1 it searchs for freetype.h on "$i/include/freetype2/freetype/freetype.h" when the newest version has this file on "$i/include/freetype2/freetype.h".

> SOLUTION:
Let's search for the file on both directories replacing (on PHP "configure" file):
if test -f "$i/include/freetype2/freetype/freetype.h"; then

> For:
if test -f "$i/include/freetype2/freetype/freetype.h" || test -f "$i/include/freetype2/freetype.h";  then


This should be the solution for all other PHP versions / Formulae as well.

**Comment by coredumperror** [comment]
Where do I go to find the configure file that needs this change? I'm new to Homebrew, and have no idea where to look.

**Comment by pschulz** [comment]
Just enter ```brew unpack --patch php53```and you'll find a folder with the name php53-5.3.29 (depending on the PHP version) in your current working directory, that has all the patches applied that belong to the php53 formula. Without the ```--patch``` option, you can get the unpatched sources.

The file you're asking for is in ./php53-5.3.29/configure.
If you're in that folder and after you applied the required changes, a simple ```./configure && make && make install``` should do the trick, if I am right.

**Comment by coredumperror** [comment]
I got an error when I tried that `./configure && make && make install` command with the edited `configure` script:

```
/bin/sh /tmp/php53-5.3.29/libtool --silent --preserve-dup-deps --mode=compile gcc  -Iext/standard/ -I/tmp/php53-5.3.29/ext/standard/ -DPHP_ATOM_INC -I/tmp/php53-5.3.29/include -I/tmp/php53-5.3.29/main -I/tmp/php53-5.3.29 -I/tmp/php53-5.3.29/ext/date/lib -I/tmp/php53-5.3.29/ext/ereg/regex -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -I/tmp/php53-5.3.29/ext/sqlite3/libsqlite -I/tmp/php53-5.3.29/TSRM -I/tmp/php53-5.3.29/Zend  -I/usr/local/include -I/usr/local/include/sasl -I/usr/X11/include -I/usr/local/include/sasl -no-cpp-precomp  -I/usr/include -g -O2 -fvisibility=hidden  -c /tmp/php53-5.3.29/ext/standard/base64.c -o ext/standard/base64.lo 
/tmp/php53-5.3.29/Zend/zend_language_parser.y:48.1-5: invalid directive: `%code'
/tmp/php53-5.3.29/Zend/zend_language_parser.y:48.7-14: syntax error, unexpected identifier
make: *** [/tmp/php53-5.3.29/Zend/zend_language_parser.c] Error 1
```

I have no idea how to deal with this.

**Comment by javian** [comment]
If you add `--debug` to the command line it will show you full failing configure command.

**Comment by pschulz** [comment]
@coredumperror I'm sorry to say, but this is not the right thread to support your installation problem. I just tried to solve the problem why the configure command fails and that's pretty much it. The patch file from @ablyler I refer to in my first post does something wrong and it should use the solution instead, that I mentioned in [my second post](#issuecomment-201597610). After that, it should be possible for homebrew to compile php53 with the latest freetype version.

Nevertheless, @javian is right. You can use ```--debug```, you can also use ```-v``` for verbose output.
Eg. ```brew -v install php53``` will show up a lot of things and somewhere in the middle of all the output you'll find the configure command.

**Comment by javian** [comment]
The freetype path problem should be resolved now @pschulz

**Comment by coredumperror** [comment]
Great!
