### ISSUE TITLE
php7 geoip support

### ISSUE THREAD

**Issue by Shaked** [Homebrew/homebrew-php#3066]
Hey,

Is there a plan to add support for php7 geoip module? I see that the pecl repository is not updated but have found this: https://github.com/Zakay/geoip 

Thanks!

**Comment by ablyler** [comment]
@Shaked i'd be interesting in adding it in, if at a minimum it had a tagged release.

**Comment by Shaked** [comment]
@ablyler sounds great! I have opened an issue there: https://github.com/Zakay/geoip/issues/8

**Comment by javian** [comment]
There doesn't seem to be any kind of response from the maintainer so the future for this addition seem bleak at the moment.

**Comment by lferro9000** [comment]
geoip was replaced with homebrew/php/php70-maxminddb

The library was replaced with a pure php implementation and the hard / slow part of it, the access / search of the ip database was implemented by that module.

Is the php70-geoip still needed?

**Comment by javian** [comment]
If there's a replacement I would say its not needed. Unmaintained software leads to problems further down the line so an active project is always preferred.

**Comment by javian** [comment]
I've updated to the latest version now from pecl so this has can be used for php7.
