### ISSUE TITLE
php56 build with OpenSSL

### ISSUE THREAD

**Issue by Muffinman** [Homebrew/homebrew-php#3070]
Hi,

I'm wondering if it's still possible to build php56 with OpenSSL rather than SecureTransport? A few guides I've found on the issue say to use something like:

    $ brew install php56 --with-apache --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl --without-snmp

But this `---with-homebrew-openssl` flag doesn't seem to be valid any more?

````
➤ brew options php56
--with-cgi
	Enable building of the CGI executable (implies --without-fpm)
--with-debug
	Compile with debugging symbols
--with-enchant
	Build with enchant support
--with-gmp
	Build with gmp support
--with-homebrew-apxs
	Build against apxs in Homebrew prefix
--with-homebrew-curl
	Include Curl support via Homebrew
--with-homebrew-libressl
	Include LibreSSL instead of OpenSSL via Homebrew
--with-homebrew-libxml2
	Include Libxml2 support via Homebrew
--with-homebrew-libxslt
	Include LibXSLT support via Homebrew
--with-imap
	Include IMAP extension
--with-libmysql
	Include (old-style) libmysql support instead of mysqlnd
--with-mssql
	Include MSSQL-DB support
--with-pdo-oci
	Include Oracle databases (requries ORACLE_HOME be set)
--with-pear
	Build with PEAR
--with-phpdbg
	Enable building of the phpdbg SAPI executable (PHP 5.4 and above)
--with-postgresql
	Build with postgresql support
--with-thread-safety
	Build with thread safety
--without-apache
	Disable building of shared Apache 2.0 Handler module
--without-bz2
	Build without bz2 support
--without-fpm
	Disable building of the fpm SAPI executable
--without-ldap
	Build without LDAP support
--without-legacy-mysql
	Do not include the deprecated mysql_ functions
--without-mysql
	Remove MySQL/MariaDB support
--without-pcntl
	Build without Process Control support
--HEAD
	Install HEAD version
````

After building with the above options:

    $ php -i | grep "SSL Version"
    SSL Version => SecureTransport

:(

**Comment by Muffinman** [comment]
Oh my bad, I forgot to run a `brew update` before building.

Still, it may be nice to have a `--without` flag for this, as it would be more obvious that a default had been changed. I'm sure there may also be cases where someone doesn't want to build with brew's openssl.

**Comment by javian** [comment]
This is what I get on my machine
```
➜  2.4 git:(master) php -i | grep "SSL"
SSL => Yes
SSL Version => SecureTransport
SSL => supported
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2g  1 Mar 2016
OpenSSL Header Version => OpenSSL 1.0.2g  1 Mar 2016
OpenSSL support => enabled
```
don't know how to manipulate the `SSL Version` line though

**Comment by javian** [comment]
I figured it out @Muffinman - The line "SSL Version" comes from the curl section in the php information output so it says nothing but php but curl! After I compiled curl with OpenSLL my output now looks like this

```
cURL support => enabled
cURL Information => 7.48.0
... (removed lines)
SSL Version => OpenSSL/1.0.2g
```

**Comment by Muffinman** [comment]
Interesting! Thanks. I'll give this a go.
