### ISSUE TITLE
Remove php*-tokyotyrant?

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-php#3072]
The Tokyo Tyrant upstream is unresponsive and we're considering removing the tokyo-tyrant package from Homebrew/homebrew-core in Homebrew/legacy-homebrew#37707. We see about 30 bottle downloads a month. Please comment there if you have any thoughts. Thanks!

**Comment by javian** [comment]
Do we have any data on the bottle downloads for the php tap or was that included in the 30 ?

**Comment by tdsmith** [comment]
They've each been downloaded a few times:

https://bintray.com/homebrew/bottles-php/php53-tokyotyrant/view#statistics (10)
https://bintray.com/homebrew/bottles-php/php54-tokyotyrant/view#statistics (4)
https://bintray.com/homebrew/bottles-php/php55-tokyotyrant/view#statistics (16)
https://bintray.com/homebrew/bottles-php/php56-tokyotyrant/view#statistics (16)

The download patterns make me think there are only a couple of users.

**Comment by javian** [comment]
I would vote to take it out. Not sure what the process would be for such a thing though but I guess we have a few options

- Delete formula without notification
- Add a caveat and "upgrade" the formula to display the notice and then delete it after x amount of time
- Keep it but remove the dependency and add a caveat
- Some other way I'm not aware of (I'm the new guy =))

Any suggestions from other people ?

**Comment by josegonzalez** [comment]
While we're doing this, are there other such formula where 20 or fewer users are downloading them?

**Comment by javian** [comment]
We can try and find out but the rest api is not publicly accessible so it would probably have to be manual

**Comment by javian** [comment]
perhaps making that a seperate issue would make most sense.

**Comment by josegonzalez** [comment]
Gotcha, makes sense to me.

FWIW I'm +1 on removing them, and potentially moving them to whatever homebrew graveyard there is.

**Comment by ablyler** [comment]
@tdsmith is there a way to deprecate formula's in homebrew, to warn users of formula's being removed? what are you planning on doing with the tokyotyrant formula?

**Comment by tdsmith** [comment]
> @tdsmith any reason why you removed your initial comment?

Nope; no idea how that happened!

**Comment by tdsmith** [comment]
> @tdsmith is there a way to deprecate formula's in homebrew, to warn users of formula's being removed? what are you planning on doing with the tokyotyrant formula?

We tend to move formulas to the homebrew/homebrew-boneyard repo and add a tap_migrations.json entry pointing there so that current installations don't break, but `brew install foo` stops working for new users immediately. We don't tend to announce deprecations.

**Comment by ablyler** [comment]
@tdsmith do any taps have bone yards?

**Comment by josegonzalez** [comment]
@tdsmith re-added your comment.

**Comment by tdsmith** [comment]
@ablyler Not afaik, but I think it's fine to move homebrew-php stuff there. We tend to just copy files over without worrying about git history.

Thanks @josegonzalez!

**Comment by javian** [comment]
The formulas have now been deleted from the tap.
