### ISSUE TITLE
PHP 7.0.5 on Yosemite: not working - symbol not found: _ldap_control_find

### ISSUE THREAD

**Issue by mezklador** [Homebrew/homebrew-php#3073]
Hi,

As I've just upgrade all my taps tonight, it comes that php 7.0.5 has update my server engine.
My laptop runs Apache 2.4 (I think it's native to this version of Mac OS X?)
But, as I ran `sudo apachectl configtest` then... A big giant syntax error that cannot load libphp7.so because : "symbol not found: _ldap_control_find"...
I tried several rewriting ($PATH, point straight to the Cellar, etc.), and still the same error, with my internal server dead!
So I'm running back 7.0.4 at this time and - magically! - everything's back to normal with no error. I'm hoping for a fix anytime, or maybe any advices concerning a new fresh and complete install of apache/php/mysql on Yosemite?

**Comment by javian** [comment]
Could you provide some more information as outlined in https://github.com/Homebrew/homebrew-php#filing-bug-reports ?

Do you see the same error when executing php on the command line ?

**Comment by mezklador** [comment]
@javian I'll do my best to outline the issue as soon as I can...
Strangely, no: in CLI, there's no issue with PHP 7.0.5. It's Apache 2.4 server that hangs on this issue. I also use php-fpm to run with Apache, with a little configuration with workers...
It seems obvious that this release of Php 7.0.5 has some bugs, because nothing happened with 7.0.4 and the same settings...

**Comment by mezklador** [comment]
<PHP 7.0.5 not working on Yosemite syntax error on Apache LoadModule>

Parameter | Value
------------------ | ------------------
**OS X Version:** | OS X Yosemite 10.10.5
**Homebrew Version:** | 0.9.9
**PHP Version in use:** | 7.0.4
**Xcode Version:** | 7.2.1
**Output of gcc -v:** | 4.2.1
**Output of php -v:** | 7.0.5
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | <result of the CLI output>
**Output of brew doctor within a gist** | https://gist.github.com/mezklador/bff59e532ae790855bed64ffdc4bb1e0

**Comment by javian** [comment]
Can you paste the whole text containing the error ?
Did you try building it from source instead of using the bottled version ?
Does it work if you use the `--without-ldap` option ?

**Comment by no81no** [comment]
Hi,
I have the same issue. When I run "sudo apachectl configtest" I get the following error:
httpd: Syntax error on line 173 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/lib/libphp7.so into server: dlopen(/usr/local/lib/libphp7.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/lib/libphp7.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/lib/libphp7.so

Thanks,

**Comment by no81no** [comment]
If I try "brew install php70 --without-ldap"
and get the following error:

checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

When I run "sudo xcode-select --install"
I get:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by javian** [comment]
@no81no the xcode-select problem has a solution here https://github.com/Homebrew/legacy-homebrew/issues/50334

**Comment by no81no** [comment]
I don't think It's an Xcode problem:

brew config:
https://gist.github.com/no81no/3383cf8b8b36b1c259fec133283a37f1

Also xcrun --show-sdk-path result:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk

**Comment by javian** [comment]
@no81no it is xcode related since you don't have the zlib headers on your machine which are installed when you install the command line tools through xcode-select or downloading them. Anyhow you should open a new issue and not hijack this one since this is about a different issue.

**Comment by mezklador** [comment]
@javian Ok, Apache 2.4 doesn't complain anymore after this line:

`brew reinstall php70 --without-ldap`

Is there any issue between LDAP, Apache & new version of PHP on Mac OS X? Especially on Yosemite?
Because I had to update the OS for security reasons recently, and I'm wondering if it could be responsible of that issue?

Anyway: thank you.

**Comment by javian** [comment]
It could be an upstream issue but that's not been confirmed but if it is then a bug should be filed with the appropriate project.

**Comment by javian** [comment]
It looks very similar to this thread posted in 2015 http://www.serverphorums.com/read.php?7,1242689 but I don't have time to research it now.

**Comment by msypes** [comment]
Is there another work-around in the meantime besides `--without-ldap`? I've got Yosemite + php5.6 and need LDAP for some apps. Is there a way to install php5.6.19 again?

**Comment by javian** [comment]
@msypes you could revert the repo to the point in time where 5.6.19 was the active version or change the abstract-php-version.rb locally on your machine. Not saying they are good options but it should work. 

The other thing that you could try is to make an ldap formula locally (base it on something like php56-mcrypt.rb), install it, load it, and then see if the problem still occurrs when ldap is loaded through an so rather than being embeeded in the php binary.

**Comment by bluebinary** [comment]
I found that simply reinstalling PHP 5.6 via Homebrew and getting Homebrew to rebuild PHP from source, that the LDAP issue was resolved – and I can confirm that I now have PHP 5.6.20 running on OS X 10.10.5 with LDAP support enabled (and the LDAP module was compiled into the PHP binary as per the original Homebrew php56/abstract-php formula).

To reinstall from source use (you may need to `brew uninstall php56` first), and you may need to reinstall other PHP extension modules after you rebuild PHP from source:

`brew reinstall php56 --build-from-source`

See this StackOverflow post I wrote regarding the issue, that covers the reinstallation of PHP itself as well as notes regarding the reinstallation of any other PHP extensions that may be installed (which may need to be reinstalled if there are any incompatibilities with the rebuilt version of PHP): 

http://stackoverflow.com/a/36635066/1914455

**Comment by sebastianhegge** [comment]
@bluebinary worked for me with php56 and php70, thx!

**Comment by javian** [comment]
The bottle has now been updated - can someone with Yosemite check if the problem now is resolved ?

**Comment by gigmaps** [comment]
php56 and php70 did not work for me in Yosemite...
php55 did however (5.5.35 I believe)

I tried @bluebinary 's `--build-from-source` solution (on pretty much every bottle I had installed) but that didn't seem to help

Have not yet tried reinstalling using `--without-ldap`

**Comment by chorajunior** [comment]
Installing with `--without-ldap` option worked for me! (PHP 5.6.21)

**Comment by nisbeti** [comment]
I have Yosemite and just now the ```brew install php70``` did not work, although php56 had worked previously. I then tried ```brew install php70 --without-ldap``` (after uninstall, cleanup, update etc.) and the result is... that it worked fine.

**Comment by javian** [comment]
If you want to use `--without-ldap` you can but it just requires you to `--build-from-source` to make it work which is done when you give the ldap option. The cause for this issue is the bottling on Yosemite specifically which is due to brew bug.

**Comment by Serhioromano** [comment]
I have exact the same error

```
httpd: Syntax error on line 117 of /usr/local/etc/apache2/2.2/httpd.conf: Cannot load /usr/local/Cellar/php70/7.0.8/libexec/apache2/libphp7.so into server: dlopen(/usr/local/Cellar/php70/7.0.8/libexec/apache2/libphp7.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/Cellar/php70/7.0.8/libexec/apache2/libphp7.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/Cellar/php70/7.0.8/libexec/apache2/libphp7.so
```

`--without-ldap` solved this error. But somehow it continue to load php5 and not php7

**Comment by javian** [comment]
@Serhioromano you need to check your httpd.conf to verify which php version is loaded

**Comment by Serhioromano** [comment]
@javian Yes I do have line

```
LoadModule php7_module /usr/local/Cellar/php70/7.0.8/libexec/apache2/libphp7.so
```

May be not exactly I typed by memory. But error goes away if I comment this line.

**Comment by mezklador** [comment]
This mess is still poped today as I update php70 to version 7.0.15
I have to reinstall php70 without ldap... What's the fuss around ldap in php7's world? Relevant in 2017?

**Comment by tfe2012** [comment]
I have same problem with php71

and in /usr/local/Cellar/php71/7.1.1_12/ does not exist folder libexec

**Comment by mack-wang** [comment]
I have the same problem. And I have solved the problem by 
`brew install php70 --with-apxs2  --with-apache --with-gmp --with-imap --with-tidy --with-debug`

**Comment by tfe2012** [comment]
does not help
