### ISSUE TITLE
Managing pull requests ?

### ISSUE THREAD

**Issue by javian** [Homebrew/homebrew-php#3081]
@ablyler how do you manage pull requests to this repo when applying them to the master branch ?

**Comment by javian** [comment]
I think I found the docs - https://github.com/Homebrew/homebrew-php/wiki/Bottles

**Comment by lucasmichot** [comment]
Cherry-picking !

**Comment by javian** [comment]
How does bottles work then since the cherry picking doesn't solve that ?

**Comment by javian** [comment]
@josegonzalez do you know how it works ?

**Comment by josegonzalez** [comment]
I actually don't, that was a new thing since I stepped away from maintaining homebrew-php and I believe maybe @ablyler might know.

**Comment by javian** [comment]
He does but he's been gone for two weeks now and hasn't seen the issue I posted already in April =)

**Comment by josegonzalez** [comment]
Looks like he just adds whitespace :P https://github.com/Homebrew/homebrew-php/pull/3148

**Comment by josegonzalez** [comment]
We may need to rethink our workflow. What does upstream homebrew/homebrew do?

**Comment by javian** [comment]
I'm trying to find out

**Comment by dunn** [comment]
There's a `brew pull` command:
```
brew pull --bottle https://github.com/Homebrew/homebrew-php/pull/3175
```
Will cherry-pick the commit, amend the message with "Closes #3175.", and publish the bottles to Bintray then cherry-pick the bottle commit.

**Comment by javian** [comment]
@dunn Thanks! Will the bot publish to bintray or do I need some kind of access to do that ?

**Comment by javian** [comment]
So this is also what Mike shows in this video https://www.youtube.com/watch?v=dBUghGQ8-xI

**Comment by josegonzalez** [comment]
@javian mind documenting this for us?

**Comment by javian** [comment]
@josegonzalez Sure, I'll place it somewhere

**Comment by javian** [comment]
Yes authentication is required
`bintray_creds = { :user => ENV["BINTRAY_USER"], :key => ENV["BINTRAY_KEY"] }`

`Security: When publishing a version, authenticated user with 'publish' permission, or version read/write entitlement.``

So permission is required so the question is who can grant that.

**Comment by josegonzalez** [comment]
@mikemcquaid ?

**Comment by javian** [comment]
https://github.com/Homebrew/homebrew-php/wiki/Merging-Pull-Requests I will flesh it out a bit more once I get some experience and can describe it better

**Comment by DomT4** [comment]
Anyone who has admin rights over a repo should have permission to push to Bintray. For obvious enough reasons, that permission to-date hasn't been extended beyond organisation or repo maintainers.

**Comment by mikemcquaid** [comment]
@josegonzalez is @javian a new homebrew-php maintainer? @javian If so, sign up for Bintray and post your username here and I'll add you to the Homebrew org.

**Comment by javian** [comment]
@mikemcquaid I signed up with my github account https://bintray.com/javian so I have the same username on bintray.

**Comment by josegonzalez** [comment]
Yes, he is. I added him a few weeks ago :)

**Comment by mikemcquaid** [comment]
@josegonzalez Ok, cool. In future make sure to add folks here: https://github.com/orgs/Homebrew/teams/php (and let me know if there's folks that can/should be removed).

**Comment by mikemcquaid** [comment]
@javian You're invited to that team.
