### ISSUE TITLE
Can't install APC on PHP 5.6.20

### ISSUE THREAD

**Issue by ve3** [Homebrew/homebrew-php#3092]
This install command `phpbrew ext install APC`

It show me error.

> Exception: Command failed: make -C /opt/phpbrew/build/php-5.6.20/ext/apc  all  >> /opt/phpbrew/build/php-5.6.20/ext/apc/build.log 2>&1 returns

**Comment by javian** [comment]
@ve3 You would have to ask the phpbrew project since that has nothing to do with the homebrew php tap.

**Comment by ve3** [comment]
Opps :P
