### ISSUE TITLE
php55-intl can't load dynamic libraries from icu4c

### ISSUE THREAD

**Issue by damiandziaduch** [Homebrew/homebrew-php#3093]
Hello.

New version of icu4c has been release (57.1). I've today upgraded by now my php is failing.
When I try to run any php code or command I got

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-intl/intl.so' - dlopen(/usr/local/opt/php55-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.56.dylib
>  Referenced from: /usr/local/opt/php55-intl/intl.so
>  Reason: image not found in Unknown on line 0
> Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-intl/intl.so' - dlopen(/usr/local/opt/php55-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.56.dylib
>  Referenced from: /usr/local/opt/php55-intl/intl.so
> /usr/local/etc/php/5.5/conf.d/ext-intl.ini

Parameter | Value
---------------|--------
OS X version: | 10.11.4
homebrew version: | 0.9.9
php version: | 5.5.34
php-intl version: | 5.5.34
icu4c version: | 57.1
brew doctor output | Your system is ready to brew.

From the output seems that php-intl need to rebuild to support new version. Am I right?

**Comment by pamil** [comment]
Same for the latest `php56-intl` and `php70-intl` packages.

**Comment by damiandziaduch** [comment]
I've managed to fix this by doing `brew switch icu4c 56.1`.

**Comment by javian** [comment]
Until the bottles are updated then you can `brew reinstall --build-from-source php70-intl` for the respective php version you are using.

**Comment by javian** [comment]
This should now have been resolved by the #3090 PR .

**Comment by puckbag** [comment]
OS X El Capitan - 10.11.6

**`$ php --version`**
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 7.0.13 (cli) (built: Nov 15 2016 23:48:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
```

**`$ brew switch icu4c 57.1`**
```
Cleaning /usr/local/Cellar/icu4c/57.1
Cleaning /usr/local/Cellar/icu4c/58.1
Opt link created for /usr/local/Cellar/icu4c/57.1
```

**`$ php --version`**
```
PHP 7.0.13 (cli) (built: Nov 15 2016 23:48:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
```

**`$ brew --version`**
```
Homebrew 1.1.2
Homebrew/homebrew-core (git revision e34b; last commit 2016-12-07)
```

**Comment by davewallace** [comment]
@javian fixes the issue for me when again broken after macos 10.12.2 update.

**Comment by javian** [comment]
@davewallace since this issue is old and closed its better if you post a new one so that it will be seen and not buries in an old issue. I'm assuming the resolution would be to rebuild the packages that are dependent on icu4c.
