### ISSUE TITLE
Should we disable bottling on pure phar archives ?

### ISSUE THREAD

**Issue by javian** [Homebrew/homebrew-php#3096]
Should we disable the bottling process on the Formulas that are pure phar archives (like phpunit) ?
Using bottles adds some maintenance but it provides download statistics from bintray.

**Comment by josegonzalez** [comment]
Personally I'm of the opinion that we shouldn't have phars here. Those should be managed by some other tool, not homebrew, or by the upstream maintainers.

**Comment by javian** [comment]
Are you saying that the packages using phar does not have a place in homebrew-php or that they should be "compiled" by the tap when installed ?

**Comment by josegonzalez** [comment]
The former.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
