### ISSUE TITLE
I can't make php55 connect to IBM DB2 server because of unixodbc dependency (El Capitan)

### ISSUE THREAD

**Issue by mikekamornikov** [Homebrew/homebrew-php#3097]
It works just fine with default osx php:
```txt
PHP 5.5.31 (cli) (built: Feb 20 2016 20:33:10)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
```sh
Configure Command =>  '/Library/Caches/com.apple.xbs/Binaries/apache_mod_php/apache_mod_php-102.1~27/TempContent/Objects/php/configure'  
'--prefix=/usr' '--mandir=/usr/share/man' '--infodir=/usr/share/info' 
'--disable-dependency-tracking' '--sysconfdir=/private/etc' 
'--with-libdir=lib' '--enable-cli' 
'--with-iconv=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr' 
'--with-config-file-path=/etc' 
'--with-config-file-scan-dir=/Library/Server/Web/Config/php' 
'--with-libxml-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr' 
'--with-openssl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/local
```

And does absolutely nothing with brew version:
```sh
Configure Command =>  './configure'  '--prefix=/usr/local/Cellar/php55/5.5.34' 
'--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/5.5' 
'--with-config-file-path=/usr/local/etc/php/5.5' '--with-config-file-scan-dir=/usr/local/etc/php/5.5/conf.d' 
'--mandir=/usr/local/Cellar/php55/5.5.34/share/man' '--enable-bcmath' '--enable-calendar' 
'--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' 
'--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' 
'--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' 
'--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' 
'--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-libedit' '--with-mhash' '--with-ndbm=/usr' 
'--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc' '--with-png-dir=/usr/local/opt/libpng' 
'--with-unixODBC=/usr/local/opt/unixodbc' '--with-xmlrpc' '--with-zlib=/usr' 
'--with-readline=/usr/local/opt/readline' '--without-gmp' '--without-snmp' 
'--with-libxml-dir=/usr/local/opt/libxml2' '--with-apxs2=/usr/sbin/apxs' 
'--libexecdir=/usr/local/Cellar/php55/5.5.34/libexec' '--with-bz2=/usr' '--enable-debug' 
'--with-openssl=/usr/local/opt/openssl' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' 
'--with-curl' '--with-xsl=/usr' '--with-ldap' '--with-ldap-sasl=/usr' '--with-mysql-sock=/tmp/mysql.sock' 
'--with-mysqli=mysqlnd' '--with-mysql=mysqlnd' '--with-pdo-mysql=mysqlnd' '--disable-opcache' 
'--enable-pcntl' '--without-pear' '--enable-dtrace' '--enable-zend-signals'
```

To build `ibm_db2.so` install dsdriver package (or full db2 server for mac) and source `db2profile`. After that `pecl install ibm_db2` should work just fine. Alternatively you can download the sources and build `so` file manually. The procedure is very simple: `phpize`, `configure`, `make`, `make install` 

I use the following code for testing:
```php
// ... some variables
$conn_string = "DATABASE=$database;HOSTNAME=$hostname;PORT=$port;PROTOCOL=TCPIP;UID=$user;PWD=$password;";
$conn = db2_connect($conn_string,'','');
if ($conn) {
    echo "Connection succeeded.", PHP_EOL;
    db2_close($conn);
} else {
    echo "CONN_ERROR: " . db2_conn_error(), PHP_EOL;
    echo "ERRORMSG: ".db2_conn_errormsg(), PHP_EOL;
}
```
In case of `brew` php i get absolutely nothing (no errors):
```txt
CONN_ERROR: 
ERRORMSG: 
```
I'm pretty sure these lines make driver package not usable:
```sh
'--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc'
'--with-unixODBC=/usr/local/opt/unixodbc'
```
I verified that with several `sudo dtruss php test_db2.php` calls:
```sh
open_nocancel("/usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini\0", 0x0, 0x1B6)		 = 3 0
...
open_nocancel("/Users/<myuser>/.odbcinst.ini\0", 0x0, 0x1B6)		 = 3 0
...
write(0x1, "CONN_ERROR value: \0", 0x12)		 = 18 0
write(0x1, "\n\0", 0x1)		 = 1 0
write(0x1, "ERRORMSG : \0", 0xB)		 = 11 0
write(0x1, "\n\0", 0x1)		 = 1 0
close_nocancel(0x0)		 = 0 0
```
- Is there any reason to hardcode `unixodbc`?
- Can you make it optional?
- Alternatively can you add anything like `--without-unixodbc`?

| Parameter | Value |
| --- | --- |
| OS X version: | 10.11.4 |
| homebrew version: | 0.9.9 |
| php version: | 5.5.34 |
| brew doctor output | Warning: You have unlinked kegs in your Cellar
| | Leaving kegs unlinked can lead to build-trouble and cause brews that depend on those kegs to fail to run properly once built. Run `brew link` on these: |  
| |    php70 |

**Comment by javian** [comment]
The `--with-pdo-odbc` option has a ibm-db2 flavour that I think needs to be there for it to work. I can't say why the default works like you say. I also think that the hardcoding of unixodbc could be change but there just hasn't been a demand to do it or someone that submitted a PR to make it work.

One option would be to manually download the php source and check which command line options that would make this work. If you look at https://github.com/php/php-src/search?utf8=%E2%9C%93&q=db2 you will see which options control the db2 functionality. 

Also stock php looks for libraries in /usr/lib which the brewed one doesn't which might make a difference.

**Comment by mikekamornikov** [comment]
I do have `ibm_db2.so` installed. It provides native IBM DB2 driver. So i don't need neither PDO nor ODBC. And that is the main problem as i understand. With php compiled this way my requests go through unixODBC. In theory it's possible to successfully connect even this way. But i haven't managed to do it playing with configs for a whole day. And working with ODBC directly is .. not flexible (actually annoying).

I'll try to compile php tomorrow and check if `--with-unixODBC=/usr/local/opt/unixodbc` is the problem. Regarding `--with-pdo-odbc`, as `unixODBC` is not the only option it should be configurable.

`unixODBC` was made "required" here - https://github.com/Homebrew/homebrew-php/pull/597#issuecomment-22066050

**Comment by javian** [comment]
You could try taking the 2 odbc options out of your local abstract-php.rb file and check if it works then to make sure that would be sufficient.

**Comment by mikekamornikov** [comment]
It works without `--with-unixODBC` and `--with-pdo-odbc`
```sh
php -i | grep with
Configure Command =>  './configure'  '--prefix=/usr/local/Cellar/php55/5.5.34' '--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/5.5' '--with-config-file-path=/usr/local/etc/php/5.5' '--with-config-file-scan-dir=/usr/local/etc/php/5.5/conf.d' '--mandir=/usr/local/Cellar/php55/5.5.34/share/man' '--enable-bcmath' '--enable-calendar' '--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' '--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' '--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-libedit' '--with-mhash' '--with-ndbm=/usr' '--with-png-dir=/usr/local/opt/libpng' '--with-xmlrpc' '--with-zlib=/usr' '--with-readline=/usr/local/opt/readline' '--without-gmp' '--without-snmp' '--with-libxml-dir=/usr/local/opt/libxml2' '--with-apxs2=/usr/sbin/apxs' '--libexecdir=/usr/local/Cellar/php55/5.5.34/libexec' '--with-bz2=/usr' '--disable-debug' '--with-openssl=/usr/local/opt/openssl' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' '--with-curl' '--with-xsl=/usr' '--with-ldap' '--with-ldap-sasl=/usr' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-mysql=mysqlnd' '--with-pdo-mysql=mysqlnd' '--disable-opcache' '--enable-pcntl' '--enable-dtrace' '--enable-zend-signals'
```

**Comment by javian** [comment]
Perfect - then all we would need is a PR adding code to the php setup enabling as you suggested `--without-unixodbc` to make it optional.

**Comment by mikekamornikov** [comment]
@javian ping

**Comment by javian** [comment]
Looks great! Someone else will have to review and commit it though so you need to wait for that. I read up on the database support for PHP and it seems its a little bit more complex than I first thought. Did you ever try just removing --with-unixodbc and kept the pdo option or vice versa ?

**Comment by mikekamornikov** [comment]
nope, i'll try tomorrow

**Comment by javian** [comment]
Ok so then both must be off in this case.

**Comment by javian** [comment]
The PR to support this has now been merged.
