### ISSUE TITLE
brew install php56  on Mac

### ISSUE THREAD

**Issue by singleHappy** [Homebrew/homebrew-php#3099]
Last 15 lines from /Users/duhui/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

**Comment by javian** [comment]
This is a known issue - you need to run `xcode-select --install` to install the libraries that comes with OSX and it should work.

**Comment by singleHappy** [comment]
thank you very much! it works!

**Comment by singleHappy** [comment]
And then, it comes like this:

==> Caveats
The php.ini file can be found in:
    /usr/local/etc/php/5.6/php.ini

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP56 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

✩✩✩✩ FPM ✩✩✩✩

To launch php-fpm on startup:
    mkdir -p ~/Library/LaunchAgents
    cp /usr/local/opt/php56/homebrew.mxcl.php56.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php56.plist

The control script is located at /usr/local/opt/php56/sbin/php56-fpm

OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:

  PATH="/usr/local/sbin:$PATH"

You may also need to edit the plist to use the correct "UserName".

Please note that the plist was called 'homebrew-php.josegonzalez.php56.plist' in old versions
of this formula.

To have launchd start homebrew/php/php56 at login:
  ln -sfv /usr/local/opt/php56/*.plist ~/Library/LaunchAgents
Then to load homebrew/php/php56 now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php56.plist
==> Summary
🍺  /usr/local/Cellar/php56/5.6.20: 330 files, 43.1M, built in 5 minutes 49 seconds


how can I fix the problem ?

**Comment by javian** [comment]
That's the normal output - I don't see a problem in that text.

**Comment by singleHappy** [comment]
You are right, but what's the matter with this:

[13-Apr-2016 16:14:58] NOTICE: PHP message: PHP Warning:  PHP Startup: memcache: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: memcache: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: memcache: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match

[13-Apr-2016 16:14:58] NOTICE: PHP message: PHP Warning:  PHP Startup: mongo: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: mongo: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: mongo: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match

[13-Apr-2016 16:14:59] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address already in use (48)
[13-Apr-2016 16:14:59] ERROR: FPM initialization failed

**Comment by javian** [comment]
Did you use the `--with-debug` option when installing php ?

**Comment by singleHappy** [comment]
Yes，I used the --with-debug option when installing php. And what can I do to fix the "Warning"?

**Comment by javian** [comment]
It's the same solution as #3101 , reinstall the module from source.
