### ISSUE TITLE
issue of php-fpm starting 

### ISSUE THREAD

**Issue by singleHappy** [Homebrew/homebrew-php#3101]
NOTICE: PHP message: PHP Warning:  PHP Startup: mongo: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: mongo: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: mongo: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match

**Comment by singleHappy** [comment]
Is anyone knows how to fix the issue?

**Comment by ablyler** [comment]
@singleHappy it looks like you need to reinstall the mongo module.

**Comment by singleHappy** [comment]
What's the command of reinstalling the mongo module ?

**Comment by javian** [comment]
`brew reinstall <formulaname> --build-from-source` where you replace the <formulaname> with the formula you want to reinstall.

**Comment by singleHappy** [comment]
# I did executive command - "brew reinstall modules --build-from-soruce" ,and then it comes like this:

[14-Apr-2016 13:49:53] NOTICE: PHP message: PHP Warning:  PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match

[14-Apr-2016 13:49:53] NOTICE: PHP message: PHP Warning:  PHP Startup: memcache: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: memcache: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: memcache: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match

[14-Apr-2016 13:49:53] NOTICE: PHP message: PHP Warning:  PHP Startup: memcached: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: memcached: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: memcached: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match


what can I do next ?

**Comment by javian** [comment]
Yes you need to rebuild all the modules you are using since you enabled the PHP debug mode. In this output I can see, memcached and igbinary in addition to the mongo problem you had before which now seems to be gone.

**Comment by singleHappy** [comment]
I have tried what you said , and it comes like this 👍

[15-Apr-2016 11:46:10] NOTICE: PHP message: PHP Warning:  PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug
These options need to match
 in <b>Unknown</b> on line <b>0</b><br />
Unknown(0) : Warning - PHP Startup: igbinary: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,NTS,debug

**Comment by javian** [comment]
Does this mean that the memcached problem went away and igbinary still is having issue despite being reinstalled ?

**Comment by singleHappy** [comment]
Yes,it is the problem what you said. And what can I do next ?

**Comment by javian** [comment]
I don't get that behaviour on my machine. After I executed

`brew reinstall -v php56-igbinary --build-from-source`

it no longer complains about it missing debug.

**Comment by singleHappy** [comment]
OK! It works! Thank you very much!

**Comment by javian** [comment]
That's what I thought! Glad we could get it going =)

**Comment by hecomwufenyao** [comment]
That's what I thought! Glad we could get it going =)
