### ISSUE TITLE
Option --enable-opcache is ignored for php56.

### ISSUE THREAD

**Issue by kenorb** [Homebrew/homebrew-php#3104]
I did run:

```
$ brew reinstall php56 --with-pear --with-debug --with-phpdbg --enable-opcache
==> Reinstalling homebrew/php/php56 with --with-pear, --with-debug, --with-phpdbg
```

but it seems `--enable-opcache` option has been ignored and I've got still `--disable-opcache'` when checking via `php -i`. Is that should work?

I've installed `php56-opcache` separately, but it didn't help.

Related: #1320

**Comment by javian** [comment]
`--enable-opcache` is a deprecated option and the php56-opcache formula is how to install it nowadays. The opcache config contains this line https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56-opcache.rb#L46-L49 which disables opcache from the cli so if you change that setting it ought to work.

**Comment by javian** [comment]
Closing this issue since I'm assuming your thumbs up means it solved your problem =)

**Comment by kenorb** [comment]
Thanks. I think it works. It's still confusing since `php -i` is showing that it was compiled with `--disable-opcache`, however further down `opcache.enable` is On, so I'm assuming it's working fine.
