### ISSUE TITLE
PHP 7 - Installation error 

### ISSUE THREAD

**Issue by ddagone** [Homebrew/homebrew-php#3107]
So I try to install PHP 7 with Brew

when I try to type brew install homebrew/php/php70 it executes but at the end it says

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
    from /usr/local/Library/Homebrew/utils.rb:472:in `open'
    from /usr/local/Library/Homebrew/utils.rb:502:in `issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:534:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:261:in `dump'
    from /usr/local/Library/brew.rb:195:in `rescue in <main>'
    from /usr/local/Library/brew.rb:79:in `<main>'
Can anyone help me ? Please 🔴

**Comment by javian** [comment]
Can you follow the guides in the troubleshooting document to provide some more information ?

**Comment by javian** [comment]
@ddagone any update on this issue ?

**Comment by ddagone** [comment]
No man, I try but nothing comes out, I've been trying since Wednesday, can
you imagine ?

2016-04-26 5:20 GMT+02:00 Jan Viljanen <notifications@github.com>:

**Comment by jt3k** [comment]
+1

**Comment by ddagone** [comment]
Why "+1" ?

**Comment by javian** [comment]
Can you install other formula without issues ?

**Comment by ddagone** [comment]
I already installed it ! it's OK by now thanks

**Comment by jt3k** [comment]
@ddagone I wrote because I had the same problem in May

now i fix all. thx

**Comment by ddagone** [comment]
I have a little problem : my phpinfo(); shows php7, but my terminal show php5.5 where do I need to change it ? 



Envoyé par myMail pour iOS


samedi 3 septembre 2016 à 07:36 +0300 de Andrey Gurtovoy  <notifications@github.com>:

**Comment by jt3k** [comment]
@ddagone try turning it off and on again ?

**Comment by javian** [comment]
@ddagone phpinfo() is run through the webserver so you need to check your apache/nginx config and change it there.

**Comment by ddagone** [comment]
Done, thanks 



samedi 3 septembre 2016 à 17:04 +0300 de Jan Viljanen  <notifications@github.com>:
