### ISSUE TITLE
Can we get php70-stats added?

### ISSUE THREAD

**Issue by sporchia** [Homebrew/homebrew-php#3160]
Can we get php70-stats added?

we have:

homebrew/php/php53-stats
homebrew/php/php54-stats
homebrew/php/php55-stats
homebrew/php/php56-stats

hoping we can get the 70 as well

**Comment by javian** [comment]
Added

**Comment by javian** [comment]
Added - please test it if you have the possibility.

**Comment by sporchia** [comment]
my initial tests are good, thanks so much
