### ISSUE TITLE
php**-imagick needs to be rebottled

### ISSUE THREAD

**Issue by mcdado** [Homebrew/homebrew-php#3166]
## Description

php**-imagick needs to be rebottled

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.4
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | any
**imagemagick installed:** | 6.9.4-1

**Output of php -v:**
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1683 but version 1684 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

**Fix**
I manually fixed the issue by building from source: <s>`brew install --build-from-source php56-imagick`</s>
```
brew reinstall --build-bottle php56-imagick
```

**Comment by ChuckHeintzelman** [comment]
+1

**Comment by mcdado** [comment]
Better yet:
```
brew reinstall --build-bottle php56-imagick
```

**Comment by darkwinternight** [comment]
👍

**Comment by franz-josef-kaiser** [comment]
This is what I have as output for a `php -v` now after the reinstall:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.56.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0
```

**Comment by Artistan** [comment]
I had similar happening for php71
FYI for others.... make sure your call REinstall....

brew **reinstall** --build-bottle php71-imagick
