### ISSUE TITLE
Add php70-maxminddb

### ISSUE THREAD

**Issue by tpetry** [Homebrew/homebrew-php#3172]
## Description

On 4th January the maxminddb extension has been updated to version 1.1.0 (still not updated in homebrew-php) which is [compatible with PHP 7.0](https://github.com/maxmind/MaxMind-DB-Reader-php/releases/tag/v1.1.0). It would be nice to have the new version included for PHP 7.0, and (maybe) the other formulas updated to the new version.

## Context and Logs

Not needed as it's not a bug report.

**Comment by javian** [comment]
Merged.
