### ISSUE TITLE
Why does wp-cli formula try to install php56 if php70 is already there?

### ISSUE THREAD

**Issue by ssteinerx** [Homebrew/homebrew-php#3179]
## Description
==> Upgrading homebrew/php/wp-cli
==> Installing dependencies for homebrew/php/wp-cli: php56
==> Installing homebrew/php/wp-cli dependency: php56
Error: Cannot install homebrew/php/php56 because conflicting formulae are installed.

  php70: because different php versions install the same binaries.

Please `brew unlink php70` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.10.5
**Homebrew Version:**   | Homebrew 0.9.9 (git revision b8e5f; last commit 2016-05-19)
Homebrew/homebrew-core (git revision 2952; last commit 2016-05-19)
**PHP Version in use:** | PHP 7.0.6 (cli) (built: Apr 28 2016 20:23:54) ( NTS )

**Comment by javian** [comment]
I've seen this before but there's currently no fix for it nor have I figured out why it happens. The code that is supposed to manage it is here https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb#L3-L20 but something causes it to pick the incorrect version that's currently in use and linked.

**Comment by HongPong** [comment]
Also having this issue.

**Comment by javian** [comment]
@HongPong are you also using Yosemite ?

**Comment by HongPong** [comment]
That is true @javian .

**Comment by javian** [comment]
This should be fixed now through https://github.com/Homebrew/homebrew-php/commit/9ffa02f3e22edcaaca48475e56cd62134dbb410f - closing the issue.
