### ISSUE TITLE
Separate php.ini and conf.d for PHP CLI and FPM?

### ISSUE THREAD

**Issue by Einkoro** [Homebrew/homebrew-php#3180]
Main use case for this would be to configure memory usage, execution time etc. and which modules are loaded between the two much like in production environments. For example during local development and testing I would normally have xdebug enabled for FPM but disabled for CLI as it slows composer down dramatically.

Example directory structure:
/usr/local/etc/php/7.0/cli
/usr/local/etc/php/7.0/cli/conf.d
/usr/local/etc/php/7.0/fpm
/usr/local/etc/php/7.0/fpm/conf.d
/usr/local/etc/php/7.0/mods-available

Then symlink the available mods under cli and fpm's conf.d to the relevant files in mods-available.

**Comment by javian** [comment]
How would this be different from just using separate config files for cli and fpm ?

http://php.net/manual/en/configuration.file.php

**Comment by Einkoro** [comment]
It would allow configuring separate modules without using the PHP_INI_SCAN_DIR env variable which would end up the same across fpm and cli under the same user unless you pass it for every fastcgi directive in nginx or caddy etc. In my opinion it would also be cleaner, more modular and closer to how one configures staging/production in my experience. Thinking more about that it would probably make even more sense to split out cli and fpm into two formulas as well as thats how its usually handled in most package managers I've come across (except FreeBSD's ports where its a option during configure)  and would be consistent with such a configuration directory layout.

**Comment by javian** [comment]
I see. I believe @ablyler was working on splitting the formulas up in #2122 but I don't think that PR has moved in a while.

**Comment by Einkoro** [comment]
Looks like there are a few other issues that would be resolved by such a split for the confs:
https://github.com/Homebrew/homebrew-php/issues/2536
https://github.com/Homebrew/homebrew-php/issues/2937

I'd imagine that PR would need to be rebased against master at this point?

**Comment by javian** [comment]
Yes indeed it would have to be. I'm not however sure why it was not merged at the time of creation and maybe he waited for a reason.

**Comment by frodeknutsen** [comment]
Someone please do something about this. The most common problem with this is using the Xdebug extension for php-fpm only and leave it disabled to cli.

**Comment by josegonzalez** [comment]
@frodeknutsen If you are interested in working on this, here is our [contribution](https://github.com/Homebrew/homebrew-php/blob/master/CONTRIBUTING.md) doc, which should help get you started on the problem.

**Comment by javian** [comment]
Perhaps we should merge @ablyler s WIP and create a new branch for it in here so that we can more easily do testing and collaboration through PRs to the development branch ?
