### ISSUE TITLE
PHP debug separate install

### ISSUE THREAD

**Issue by abiusx** [Homebrew/homebrew-php#3185]
## Description

Many PHP developers, especially PHP extension developers, need a debug PHP compilation (--with-debug) that has all other features enabled, just like regular PHP. However, the current homebrew debug option does not support that, and also is not a separate install.

I think having a separate php70-debug that installs in a separate folder, with a separate php.ini that links to all modules of the other php installed on the system, while exposing php-debug and php-config-debug binaries would be an excellent idea. This way we could have both a native PHP and a debug version for development and testing.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11
**PHP Version in use:** | 7.0

**Comment by javian** [comment]
Thank you for the feedback @abiusx . Your request is similar to #3180 and @ablyler started working towards that in oldest of the exisiting PRs but I'm unsure as to what the current status is of that work.

**Comment by abiusx** [comment]
Separating the PHP.ini is not the major issue, but having the separate set of binaries/modules in debug/release modes, I believe.

**Comment by javian** [comment]
I think I was more referring to #2122 which was linked to in that response. It doesn't add a debug version but splits the php formulas to specific functions like cli, fpm and apache and debug could be added as another option.

**Comment by abiusx** [comment]
Good!
It’s just that I couldn’t find the Formulae that compiled PHP, all availables grab binaries. If I could find that, I could probably fork a debug from it and PR.

**Comment by javian** [comment]
The core php files are in php70.rb for instance and the Abstract directory contains the skeleton code that does the heavy lifting currently.

**Comment by ablyler** [comment]
@javian the work in the PR just needs to be rebased and tested again. I'd also like to have a few more eyes on it, as it is a pretty major change. /cc @JohnMaguire who also offered to help with the massive PR.

**Comment by abiusx** [comment]
I’m willing to help! Where is the PR?

**Comment by javian** [comment]
It's #2122

**Comment by josegonzalez** [comment]
Closing in favor of #2122.
