### ISSUE TITLE
Installing multiple versions isn't straightforward, and could use some examples

### ISSUE THREAD

**Issue by ezzatron** [Homebrew/homebrew-php#3236]
I'm trying to create a script to set up a new dev machine in a semi-automated fashion. I need multiple versions of PHP with some extensions, and it needs to be safe to re-run the script if an error occurs.

I'm brand new to brew, so forgive me if I'm missing something fundamental here.

The first thing I tried was:

```
brew tap homebrew/homebrew-php
brew install \
    php53 php53-intl \
    php54 php54-intl \
    php55 php55-intl \
    php56 php56-intl \
    php70 --with-phpdbg php70-intl
```

This fails because `--with-phpdbg` gets applied to _all_ versions, and phpdbg isn't available for all versions. Fair enough, so I need to call `brew install` separately for phpdbg versions:

```
brew tap homebrew/homebrew-php
brew install \
    php53 php53-intl \
    php54 php54-intl \
    php55 php55-intl \
    php56 php56-intl 
brew install \
    php70 --with-phpdbg php70-intl
```

This fails because `brew` complains that `php53` needs to be unlinked before `php54` can be installed. Okay, so now I need to unlink before each new version I'm installing. I'll move the extensions into a separate install command for easy maintenance too:

```
brew tap homebrew/homebrew-php
brew install php53
brew unlink php53
brew install php54
brew unlink php54
brew install php55
brew unlink php55
brew install php56
brew unlink php56
brew install php70
brew install \
    php53-intl \
    php54-intl \
    php55-intl \
    php56-intl \
    php70-intl
```

But wait, that doesn't work either, because in order to install `php53-intl`, you have to link `php53` first (what?). On top of that, if you `brew install` a version of PHP you've already installed, it doesn't automatically link it for you. Also, since this script is designed to be re-run, I need to write a catch-all unlink before I start:

```
brew tap homebrew/homebrew-php
brew unlink php53 php54 php55 php56 php70 || true
brew install php53
brew link --overwrite php53
brew install php53-intl
brew unlink php53
brew install php54
brew link --overwrite php54
brew install php54-intl
brew unlink php54
brew install php55
brew link --overwrite php55
brew install php55-intl
brew unlink php55
brew install php56 --with-phpdbg
brew link --overwrite php56
brew install php56-intl
brew unlink php56
brew install php70 --with-phpdbg
brew link --overwrite php70
brew install php70-intl
```

Finally, it's actually working, but the end result is pretty ridiculous, and it's only going to get worse as I add new versions of PHP, and new extensions. Given that the equivalent script for a Macports install (excluding phpdbg, which isn't available) is as simple as:

```
sudo port install \
    php53 \
    php53-intl \
    php54 \
    php54-intl \
    php55 \
    php55-intl \
    php56 \
    php56-intl \
    php70 \
    php70-intl
sudo port select php php70
```

It feels pretty gross.

Some things I feel could help this situation:
- Examples in the README under the "Installing Multiple Versions" heading. Right now it's a bunch of stuff about Apache config, with nothing about actually installing anything.
- Allow installation of extensions without the main PHP package needing to be linked.
- Don't automatically link the package on installation. That's essentially how port gets around the issue of installing multiple versions simultaneously. I'm guessing that could be outside the scope of homebrew-php, though.
- `brew unlink` could really use a `--force` flag to avoid it complaining about packages you've never installed. Once again, more of a general brew problem.

**Comment by javian** [comment]
@ezzatron thank you for your feedback. I agree that the current setup does not really support this scenario. You will also run into problems as soon as the versions are updated since they don't really play nicely together. I agree that this is something we need to take a closer look at so it doesn't get in the way but I can't promise when it will happen. If you have any further suggestions or a possible change that can be put into a PR then that would be most welcome. @ablyler have you by any chance had a look at this problem before ?

**Comment by javian** [comment]
One of the current blockers is that the different versions installs binaries with the same name.

**Comment by ezzatron** [comment]
Thanks. If I get a chance to do some digging, I might submit a PR, but I have no Ruby experience to speak of unfortunately. The main frustration is really the fact that the README says:

> Using multiple PHP versions from homebrew-php is pretty straightforward.

Which just isn't true at the moment.

**Comment by tdsmith** [comment]
A couple notes on things that could change in core to make this story more tenable:

> * Allow installation of extensions without the main PHP package needing to be linked.

It should be possible to treat unlinked dependencies like keg-only dependencies in superenv, which would resolve this and improve UX in a few other situations.

> * Don't automatically link the package on installation.

Adding a `--no-link` option to `brew install` should be possible but I'm not sure what the right way to handle dependencies is. I would probably favor the same (slightly weird but usually helpful) behavior that --build-from-source has, which only applies to packages specified on the command line.

**Comment by tdsmith** [comment]
Meant to add: the best way to make any of these things actually happen is probably a proposal PR against Homebrew/brew-evolution. I'll put these on my to-do list but it's pretty clogged right now; if anyone's eager to see these adopted, please go ahead!

**Comment by ezzatron** [comment]
@tdsmith Thanks man, I really appreciate you taking the time to read it through and get where I'm coming from.

**Comment by josegonzalez** [comment]
Has anyone made pull requests to clarify the documentation?

**Comment by iandouglas** [comment]
@josegonzalez I just tried following the docs and still get errors about unlinking previous versions. In the meantime, I just install a version I want, unlink it, install the next version, unlink it, etc., and then wrote some bash aliases to unlink all versions (just in case) and then link up whichever one I want to use for now. Not at ALL elegant, but it's functional.

**Comment by javian** [comment]
@iandouglas there's also the `homebrew/php/brew-php-switcher` formula that also does something similar.

**Comment by javian** [comment]
@josegonzalez no there's been no update to the documentation as far as I can see.

**Comment by ezzatron** [comment]
I should mention that I managed to solve the problems I was having with multiple concurrent PHP installations by writing my own brew [external command](https://docs.brew.sh/External-Commands). The basic approach needed is something like this:

1. If there is a "currently linked" PHP version, remember which version, then unlink it.
2. Do the actual brew operation (installing something, upgrading something).
3. Re-link the remembered version of PHP if necessary.

This works for installing new PHP versions, and for doing system-wide brew upgrades, which is where the real pain points were.

If anyone is interested, you can find my implementation at [ezzatron/brew-php](https://github.com/ezzatron/brew-php). It's definitely not perfect (no error handling etc.) but it should work well *enough* for you if you're having similar problems. For reference, here's the current usage:

```
brew php
    Manage multiple PHP installations

    brew php help
    Outputs this usage information

    brew php install [...]
    Unlink the current PHP package, install a package, then restore the linked PHP package

    brew php installed
    Output the currently installed PHP packages

    brew php link package
    Unlink the current PHP package, then link the requested package

    brew php linked
    Output the currently linked PHP package

    brew php upgrade [...]
    Unlink the current PHP package, perform an upgrade, then restore the linked PHP package
```

**Comment by ezzatron** [comment]
@javian @tdsmith Any interest in adding [brew-php](https://github.com/ezzatron/brew-php) to the official PHP repository? It's a pretty effective workaround for the issues raised here.

**Comment by SMillerDev** [comment]
Seems to do a lot of the things brew-php-switcher does.

**Comment by ezzatron** [comment]
Unfortunately `brew-php-switcher` doesn't solve one of the biggest pain points of having multiple PHP versions installed, which is that `brew upgrade` will fail any time there's an update to a version of PHP you don't currently have linked.

The `brew-php` command actually "manages" the linked PHP package for you, which means you can safely run, for example, `brew php upgrade` to upgrade all packages - a massive time saver.

So essentially, the difference is that `brew-php` helps you manage having multiple PHP installations, whereas `brew-php-switcher` is *only* for switching between already installed versions.

**Comment by javian** [comment]
There's not much we can do about that now. There's a `keg_only` option that could be explored and then we can put the core modules (or potentially all extensions) as keg_only so they wouldn't be linked. This could potentially solve the upgrade issue.

**Comment by ezzatron** [comment]
@javian In that scenario, how would you select/activate/link a particular PHP version? Would it require a custom application for managing the PHP-related symlinks?
