### ISSUE TITLE
Runtime error after installing php56-http

### ISSUE THREAD

**Issue by elazar** [Homebrew/homebrew-php#3243]
php56-http installs with no obvious issue. However, upon attempting to use any classes it defines, this runtime error is the result:

```
dyld: lazy symbol binding failed: Symbol not found: _uidna_IDNToASCII_56
  Referenced from: /usr/local/opt/php56-http/http.so
  Expected in: flat namespace

dyld: Symbol not found: _uidna_IDNToASCII_56
  Referenced from: /usr/local/opt/php56-http/http.so
  Expected in: flat namespace

Trace/BPT trap: 
```

However, uninstalling the recipe through Homebrew and then manually installing the pecl_http extension per commands from [this blog post](https://simukti.net/blog/2015/12/30/php-osx-ext-http-fix-error-dyld-lazy-symbol-binding-failed.html) works without issue.

These lines from the output of `./configure` when manually installing the extension appear relevant:

```
checking unicode/uidna.h usability... no
checking unicode/uidna.h presence... no
checking for unicode/uidna.h... no
checking for uidna_IDNToASCII... no
checking for __uidna_IDNToASCII... no
checking for uidna_IDNToASCII in -licucore... yes
```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.5
**Homebrew Version:**   | 0.9.9 (git revision 14657; last commit 2016-06-05)
**PHP Version in use:** | 5.6.22
**Xcode Version:**      | 7.3.1

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 5.6.22 (cli) (built: May 27 2016 12:20:55)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** No logs

**Comment by javian** [comment]
This is not a direct answer to your question but it looks like were not using the latest version on the http module so I would suggest we upgrade to 2.5.6 which is the latest one.

**Comment by elazar** [comment]
@javian [Indeed](https://github.com/Homebrew/homebrew-php/blob/a639d7f51a19eb718d5a2a12063e36363a324ed1/Formula/php56-http.rb#L7). Good call.

**Comment by javian** [comment]
I also noticed that the dependencies are a little bit out of date and also needs an update.

**Comment by javian** [comment]
Can you check now? I've updated all the components for php56.

**Comment by elazar** [comment]
@javian I'm still receiving a similar error.

```
$ cat test.php
<?php
$request = new \http\Client\Request('GET', 'http://localhost.example');
$client = new \http\Client;
$client->enqueue($request, function(\http\Client\Response $response) {
        var_dump(
            $response->getResponseCode(),
            $response->getHeaders(),
            (string) $response->getBody()
        );
    });
$client->send();

$ php test.php
dyld: lazy symbol binding failed: Symbol not found: _uidna_IDNToASCII_57
  Referenced from: /usr/local/opt/php56-http/http.so
  Expected in: flat namespace

dyld: Symbol not found: _uidna_IDNToASCII_57
  Referenced from: /usr/local/opt/php56-http/http.so
  Expected in: flat namespace

[1]    14943 trace trap  php test.php
```

Some potentially relevant console output:

```
$ brew --version
Homebrew 0.9.9 (git revision 3f7f; last commit 2016-06-12)
Homebrew/homebrew-core (git revision f8b0; last commit 2016-06-12)

$ php -i | less
<snip>
http

HTTP Support => enabled
Extension Version => 2.5.6

Used Library => Compiled => Linked
libz => 1.2.5 => 1.2.5
libcurl => 7.49.1 => 7.49.1
libevent => 2.0.22-stable => 2.0.22-stable
<snip>
```

**Comment by javian** [comment]
I think I found the issue. There's a missing dependency to the intl library so if you `brew install php56-intl` it will work (at least it did for me). I will update the formula and add the dependency.

**Comment by javian** [comment]
Or just upgrade =) Thanks for the report @elazar !

**Comment by elazar** [comment]
@javian That has definitely fixed my original issue, thank you! :) I did happen across a separate less critical issue, but I'll file it separately.
