### ISSUE TITLE
No available formula with the name "judy"

### ISSUE THREAD

**Issue by lecktor** [Homebrew/homebrew-php#3246]
## Description

I'm trying to install homebrew/php/php56-judy and receiving the error, that dependency could not be found. Is it a known issue or I'm making something wrong?

## Context and Logs

brew install homebrew/php/php56-judy
==> Installing php56-judy from homebrew/php
Error: No available formula with the name "judy" (dependency of homebrew/php/php56-judy)
==> Searching for similarly named formulae...
These similarly named formulae were found:
homebrew/php/php53-judy homebrew/php/php54-judy homebrew/php/php55-judy                             homebrew/php/php56-judy                               
To install one of them, run (for example): brew install homebrew/php/php53-judy
==> Searching taps...
Error: No formulae found in taps.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.10.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 5.6.17
**Xcode Version:**      | 7.2.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Output of php -v:**
PHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

**Build logs:** No logs.

**Comment by javian** [comment]
Thanks for your report. It seems that the upstream project is dead and the brew formula retired https://github.com/Homebrew/homebrew-core/issues/1562 and we should remove judy from the php tap completely.

**Comment by javian** [comment]
Alternatively it can be added as an additional resource like https://github.com/Homebrew/homebrew-core/pull/1680/files

**Comment by javian** [comment]
I've decided to go for the former and take the extension out of homebrew-php - you can see a longer thread on the issue here https://github.com/Homebrew/homebrew-core/issues/1562 . If the project gets under new maintenance and gets reinstated we can easily add it back in.
