### ISSUE TITLE
fail install php6 --with-imap --with-pear

### ISSUE THREAD

**Issue by pinouf** [Homebrew/homebrew-php#3247]
## Description

hi, I cant't install php56 with imap =((

help plz !!

brew install php56 --with-imap 
==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.22.tar.bz2/from/this/mirror
Already downloaded: /Users/pinouf/Library/Caches/Homebrew/php56-5.6.22
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.22 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-sc
Last 15 lines from /Users/pinouf/Library/Logs/Homebrew/php56/01.configure:
checking for mknod... yes
checking for getrlimit... yes
checking for getlogin... (cached) yes
checking for getgroups... yes
checking for makedev... no
checking for initgroups... yes
checking for getpwuid_r... (cached) yes
checking for getgrgid_r... yes
checking for working ttyname_r() implementation... no, posix_ttyname() will be thread-unsafe
checking for utsname.domainname... no
checking for PSPELL support... no
checking for libedit readline replacement... yes
checking for tgetent in -lncurses... yes
checking for readline in -ledit... no
configure: error: edit library required by readline not found

| Parameter | Value |
| --- | --- |
| **OS X Version:** | OS X El capitan  10.11.15 |
| **Homebrew Version:** | Homebrew 0.9.9 (git revision 11d47; last commit 2016-06-08) |
| **PHP Version in use:** | php 5.6 |
| **Xcode Version:** | Version 7.3.1 (7D1014) |

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.5.34 (cli) (built: Apr 22 2016 19:16:58) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by javian** [comment]
Does `brew doctor` tell you that anything is wrong ? The php formula should require the readline formula to support the build (see `brew info php56`).

**Comment by pinouf** [comment]
hello @javian -)

Everythings seems ok to my brew doctor

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install php56

Run `brew missing` for more details.



brew info readline
readline: stable 6.3.8 (bottled) [keg-only]
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/usr/local/Cellar/readline/6.3.8 (46 files, 2.0M)
  Poured from bottle on 2016-06-10 at 00:05:38
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/readline.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.


Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

**Comment by javian** [comment]
Could you try `brew install php56 --build-from-source` without the imap option and see if that works ?

 I can't reproduce the error on my machine.

**Comment by pinouf** [comment]
@javian same problem =(

brew install php56 --build-from-source
==> Installing php56 from homebrew/php
==> Installing dependencies for homebrew/php/php56: pkg-config, makedepend
==> Installing homebrew/php/php56 dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.1.el_capitan.bottle.tar.gz
######################################################################## 100,0%
==> Pouring pkg-config-0.29.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.1: 10 files, 627.2K
==> Installing homebrew/php/php56 dependency: makedepend
==> Downloading https://homebrew.bintray.com/bottles/makedepend-1.0.5.el_capitan.bottle.1.tar.gz
######################################################################## 100,0%
==> Pouring makedepend-1.0.5.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/makedepend/1.0.5: 7 files, 72.6K
==> Installing homebrew/php/php56
==> Downloading https://php.net/get/php-5.6.22.tar.bz2/from/this/mirror
Already downloaded: /Users/pinouf/Library/Caches/Homebrew/php56-5.6.22
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.22 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-sc
Last 15 lines from /Users/pinouf/Library/Logs/Homebrew/php56/01.configure:
checking for mknod... yes
checking for getrlimit... yes
checking for getlogin... (cached) yes
checking for getgroups... yes
checking for makedev... no
checking for initgroups... yes
checking for getpwuid_r... (cached) yes
checking for getgrgid_r... yes
checking for working ttyname_r() implementation... no, posix_ttyname() will be thread-unsafe
checking for utsname.domainname... no
checking for PSPELL support... no
checking for libedit readline replacement... yes
checking for tgetent in -lncurses... yes
checking for readline in -ledit... no
configure: error: edit library required by readline not found

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
Update php56-apcu.rb https://github.com/Homebrew/homebrew-php/pull/3242
Runtime error after installing php56-http https://github.com/Homebrew/homebrew-php/issues/3243
brew install php56 https://github.com/Homebrew/homebrew-php/issues/2760
Make error php56 https://github.com/Homebrew/homebrew-php/issues/1842
PHP56 required for composer https://github.com/Homebrew/homebrew-php/issues/2796
failed to install php56-pthreads https://github.com/Homebrew/homebrew-php/issues/2768
Can't install php56-mcrypt https://github.com/Homebrew/homebrew-php/issues/2452
Every update of php56 force me to reinstall php56-intl and php56-mcrypt with --build-from-source https://github.com/Homebrew/homebrew-php/issues/2440
Failed to install/reinstall php56-http https://github.com/Homebrew/homebrew-php/issues/2711
Fails to Install Php56 with Imap Extensiton https://github.com/Homebrew/homebrew-php/issues/2703
I can't find php56_pdo! https://github.com/Homebrew/homebrew-php/issues/2706
"brew upgrade" fails: php56 conflicting with php70 when upgrading phpmyadmin https://github.com/Homebrew/homebrew-php/issues/2945
Adds a new php70-gearman formula that updates php56-gearman https://github.com/Homebrew/homebrew-php/pull/3120
Why does wp-cli formula try to install php56 if php70 is already there? https://github.com/Homebrew/homebrew-php/issues/3179
PHP56 can't launch as root, with nginx 500 Internal Server Error? https://github.com/Homebrew/homebrew-php/issues/2709

**Comment by javian** [comment]
Could you try manually removing and reinstalling readline ?

**Comment by pinouf** [comment]
@javian already try =/ 
same errors .. i am desparate.

**Comment by javian** [comment]
Can you try `brew uses readline` to list other packages and install one of the other packages from source there that depends on readline to see if they compile ?

**Comment by pinouf** [comment]
hello,
I tried brew uses readline
and tried to install ruby, that's work..


brew install php56  ===> work
brew install php56 --with-pear ==> dont work =(

**Comment by alexcroox** [comment]
I too am failing to install with the `--with-pear` option

```
bash-3.2$ brew install php71 --with-pear
==> Installing php71 from homebrew/php
==> Downloading https://php.net/get/php-7.1.0.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-7.1.0.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php71/7.1.0_11 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --with-config-file-path=/usr/local/etc/php/7.
==> make
==> make install
==> /usr/local/Cellar/php71/7.1.0_11/bin/pear config-set php_ini /usr/local/etc/php/7.1/php.ini system
Last 15 lines from /Users/alex/Library/Logs/Homebrew/php71/04.pear:
2017-01-18 11:34:57 +0000

/usr/local/Cellar/php71/7.1.0_11/bin/pear
config-set
php_ini
/usr/local/etc/php/7.1/php.ini
system


READ THIS: http://docs.brew.sh/Troubleshooting.html
```
