### ISSUE TITLE
PHP Notice: http\Client::enqueue(): Could not set option proxy_service_name (An unknown option was passed in to libcurl)

### ISSUE THREAD

**Issue by elazar** [Homebrew/homebrew-php#3270]
## Description

/cc @javian 

I'm receiving the error in the description of this issue after installing php56-http and running the following script:

``` php
<?php
$request = new \http\Client\Request('GET', 'https://www.google.com');
$client = new \http\Client;
$client->enqueue($request, function(\http\Client\Response $response) {
        var_dump(
            $response->getResponseCode(),
            $response->getHeaders(),
            (string) $response->getBody()
        );
    });
$client->send();
```

The script is able to make the request and receive a response, so the notice is more of a nuisance than anything else.

However, if I install the pecl_http extension manually, I don't receive this notice. It looks like this may be related to m6w6/ext-http#39.
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.11.5 |
| **Homebrew Version:** | 0.9.9 (git revision cc10c6; last commit 2016-06-14) |
| **PHP Version in use:** | 5.6.22 |
| **Xcode Version:** | 7.3.1 |

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 5.6.22 (cli) (built: May 27 2016 12:20:55)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** No logs

**Comment by javian** [comment]
The linked issue in the ext-http repo suggest installing curl with gssapi support `brew reinstall curl --with-gssapi` and this made the error go away for me. The reason it works with pecl is that the bundled curl that comes with OSX/macOS includes GSSAPI support already.

```
➜  Trash curl -V
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
➜  Trash /usr/local/Cellar/curl/7.49.1/bin/curl -V
curl 7.49.1 (x86_64-apple-darwin15.5.0) libcurl/7.49.1 OpenSSL/1.0.2h zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
➜  Trash
```

At the top you see the bundled curl with GSS-API support built in and below is the homebrew compiled curl that does not include it unless explicitly stated when installing.

**Comment by elazar** [comment]
@javian Confirmed, I was able to reproduce your result. I'm guessing it's not feasible to make the php56-http recipe do this? Or to have it output something to the console warning the user that they may need to run the command you included above to avoid this issue?

**Comment by javian** [comment]
The best way might be to remove the curl dependency since I don't think its required at least in the later versions of macOS. We could make it an option to use --with-homebrew-curl which would then depend on the curl formula requiring the gssapi flag.
