### ISSUE TITLE
What is PHP 7.1 support roadmap

### ISSUE THREAD

**Issue by pinepain** [Homebrew/homebrew-php#3271]
Subj. What is the roadmap for PHP 7.1 support?

**Comment by javian** [comment]
I don't think anyone is working on it yet. Now that the 7.1 alpha is out we could do a release version based on that and looking at the changes I couldn't see anything major that changed that would affect using what's already there for 7.0. If you would be interested to submit a PR then you are more than welcome to do so.

**Comment by pinepain** [comment]
Thanks. I also can't recall any major or internals changes that will break extension or requires some special handling. 

If no one already on it, I will do some more testing locally and provide a PR.

**Comment by javian** [comment]
Thank you that would be much appreciated!

**Comment by pinepain** [comment]
PR https://github.com/Homebrew/homebrew-php/pull/3273 submitted. PTAL & try someone.

**Comment by pinepain** [comment]
PR https://github.com/Homebrew/homebrew-php/pull/3276 with formulae submitted.

**Comment by javian** [comment]
Closing this now since support for 7.1 has been merged and actively monitored.
