### ISSUE TITLE
Update codesniffer to latest version

### ISSUE THREAD

**Issue by designermonkey** [Homebrew/homebrew-php#3275]
Can this be done asap? There are important fixes in there that aren't available here.

**Comment by javian** [comment]
Are you referring to the drupal code sniffer ?

**Comment by javian** [comment]
This update has now been merged through #3233

**Comment by designermonkey** [comment]
Sorry! I completely intended to respond today, it's been so hectic I forgot!

Thanks for updating that, much appreciated.

**Comment by javian** [comment]
You're welcome and thanks for pointing it out =)
