### ISSUE TITLE
Update php-libsodium (1.0.6)

### ISSUE THREAD

**Issue by stevendesu** [Homebrew/homebrew-php#3330]
## Description

Not familiar with the PR process, so I hope it's not rude to make an issue and a PR simultaneously.

php-libsodium >= 1.0.3 is required to take advantage of the `crypto_pwhash_str` function which uses Argon2i for password hashing

I already created PR https://github.com/Homebrew/homebrew-php/pull/3327 to address this

**Comment by javian** [comment]
Merged! Thank you for your submission @stevendesu and if you do a PR you don't have to post an issue as well - just putting the PR in there is enough =)
