### ISSUE TITLE
phpunit 5.4.6 depending on php7.1

### ISSUE THREAD

**Issue by MikeLund** [Homebrew/homebrew-php#3335]
## Description

Upgrading to phpunit 5.4.6 is requiring php 7.1 for some reason.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | El Capitan 10.11.5
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | php 7.0.8
**Xcode Version:**      | 7.3.1.0.1.1461711523

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 7.0.8 (cli) (built: Jun 23 2016 16:32:40) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** 
> ~$ brew upgrade
> ==> Upgrading 3 outdated packages, with result:
> homebrew/php/phpunit 5.4.6, syncthing 0.13.10, youtube-dl 2016.07.03.1
> ==> Upgrading homebrew/php/phpunit
> ==> Installing dependencies for homebrew/php/phpunit: php71
> ==> Installing homebrew/php/phpunit dependency: php71
> Error: Cannot install homebrew/php/php71 because conflicting formulae are installed.
>
>  php70: because different php versions install the same binaries.
>
> Please `brew unlink php70` before continuing.
>
> Unlinking removes a formula's symlinks from /usr/local. You can
> link the formula again after the install finishes. You can --force this
> install, but the build may fail or cause obscure side-effects in the
> resulting software.

phpunit requires php ^5.6 || ^7.0. So my php70 package should still work fine, no?

This seems to be a bug similar to https://github.com/Homebrew/homebrew-php/issues/2945 . I imagine this isn't normal functionality, but if it is, it should really be explained better I think. Especially because if I ``brew install phpunit`` it goes fine, even without unlinking php70.

Thanks!

**Comment by javian** [comment]
This should be fixed now through https://github.com/Homebrew/homebrew-php/commit/9ffa02f3e22edcaaca48475e56cd62134dbb410f - closing issue.
