### ISSUE TITLE
poser

### ISSUE THREAD

**Issue by Blondas** [Homebrew/homebrew-php#3350]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _your OS X version_
**Homebrew Version:**   | _your Homebrew version_
**PHP Version in use:** | _your PHP version_
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
_result of the CLI output_

**Output of php -v:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by josegonzalez** [comment]
There doesn't seem to be any issue posted here, so closing.
