### ISSUE TITLE
configure: error: Aborting

### ISSUE THREAD

**Issue by oytunistrator** [Homebrew/homebrew-php#3353]
## Description
Cant compile with
```
brew install php70
brew install php71
```
## Context and Logs
```
The output of /private/tmp/php70-20160718-53416-eain63/php-7.0.8/["sbin", "bin"] follows:
./configure: line 6213: /private/tmp/php70-20160718-53416-eain63/php-7.0.8/["sbin",: No such file or directory
configure: error: Aborting
```
Parameter | Value
--------- | ------------------
**OS X Version:**       |  10.12
**Homebrew Version:**   | Homebrew 0.9.9
**PHP Version in use:** | 7
**Xcode Version:**      | 73.1
**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.5.36 (cli) (built: Jun 26 2016 22:20:56) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by javian** [comment]
You say you "can't compile with" @oytunistrator - what are you trying to compile? Are you trying to install php7 from source ?

**Comment by javian** [comment]
@oytunistrator any update you can give - if not then I will close the issue.

**Comment by javian** [comment]
Just a note that you are using 10.12 which is still in beta so I would expect there to be some issues.

**Comment by javian** [comment]
Closing issue due to no response.
