### ISSUE TITLE
phpMyAdmin Permission denied - Mac OS X 10.11.5

### ISSUE THREAD

**Issue by jbouhier** [Homebrew/homebrew-php#3386]
## Installed latest phpMyAdmin with brew

[http://localhost/phpmyadmin](http://localhost/phpmyadmin) started returning:

> Forbidden
> You don't have permission to access /phpmyadmin/ on this server.

Since OS X 10.11.5 is now running Apache 2.4, Access Control needs to be

> Require all granted  

inside `<IfModule !mod_authz_core.c>` block instead of  

> Order allow,deny
> Allow from all

Here is the formula that needs to be updated:
[https://github.com/Homebrew/homebrew-php/blob/master/Formula/phpmyadmin.rb](https://github.com/Homebrew/homebrew-php/blob/master/Formula/phpmyadmin.rb)

--------- | ------------------
**OS X Version:**       | _10.11.5_
**Homebrew Version:**   | _0.9.9_
**PHP Version in use:** | _7.0.9_
**Xcode Version:**      | _ 7.3.1_

**Output of gcc -v:**
_Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin_

**Output of php -v:**
_PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies_

**Build logs:** _Error: No logs._

**Comment by javian** [comment]
@jbouhier I think that line is mentioned already but it could be made clearer if it is 2.4 specific.

**Comment by jbouhier** [comment]
Hey @javian,

It was indeed already mentioned but not in every IfModule block, 
which is precisely why I have open this issue since It trigger an error on my env.

Hope you have all the infos you need.
Feel free to ask if you need additional details.

**Comment by javian** [comment]
Would it be possible for you to put the change you are outlining in a PR ?

**Comment by jbouhier** [comment]
Sure, what is the procedure to do so ?
I've clone the project and tried to push my branch to this repo but to no avail.

**Comment by javian** [comment]
You push the branch to your fork, then you when you go to the main repo page of this repo then it will ask you if you want to submit a PR for your updated branch.

**Comment by javian** [comment]
There's a slightly more visual explanation here - https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

**Comment by jbouhier** [comment]
Thanks. Will do tomorrow during lunch break :)
Good night Jan.

**Comment by javian** [comment]
I just thought about this a little more and I think the two clauses represent 2.2 vs 2.4 config since the mod_authz_core module doesn't exist in 2.2 so it looks ok as far as I can tell.

**Comment by jbouhier** [comment]
I've been [looking into it ](http://httpd.apache.org/docs/2.2/en/mod/) myself and I think you're right.
On the other hand I can't explain why on my env Apache wouldn't run even though mod_authz_core is enabled. I guess this issue is closed.

Take care

**Comment by javian** [comment]
No I can't explain that either. Would it work if you removed the section that covers 2.2 and just kept the 2.4 one ?

**Comment by jbouhier** [comment]
Just deleted the 2.2 block:

```
<IfModule !mod_authz_core.c>
	Require all granted
</IfModule>
```

At first the page didn't' run anything and after a couple of minutes while investigation the
httd.conf and extra/http-vhost.conf it now work.

I've tried once more to add / remove the block and all seems ok now.
Apache just seems to take a few seconds to restart which might explain why I had a page error when refreshing right after the restart.

**Comment by javian** [comment]
Thanks for looking into it @jbouhier !
