### ISSUE TITLE
php56 is looking for mongo.so right out of the box? 

### ISSUE THREAD

**Issue by ncgreco1440** [Homebrew/homebrew-php#3401]
## Description

I've created a neat script to set up a development environment using Homebrew and part of that script installs php. I've had no issues with this script until mongo happened. I recall doing something along the lines of a 
brew install mongodb 
a few weeks ago but then gave up on it not working so I did a composer install and used the library with php. 

I have an uninstall option in this script to remove all brew services and homebrew itself. Which I ran and did a brand new install and upon completion php56 is complaining about mongo!! Despite the fact that I never installed it after uninstalling it. 

I've ran...
brew rm mongodb 
brew uninstall mongodb 

I've even checked the folders to see that mongodb is completely gone, and it seems to be. But I'm baffled as to why php56 is still looking for it. 

On top of this there is a change that it complains about mcrypt dynamic libraries too, and as of a few weeks ago it NEVER complained about them. Did something change in --build-from-source regarding the mcrypt extension? 

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6 El Capitan
**Homebrew Version:**   | 0.9.9 
**PHP Version in use:** | php56
**Xcode Version:**      | N/A

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-mongo/mongo.so' - dlopen(/usr/local/opt/php56-mongo/mongo.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-mongo/mongo.so' - dlopen(/usr/local/opt/php56-mongo/mongo.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-mongodb/mongodb.so' - dlopen(/usr/local/opt/php56-mongodb/mongodb.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-mongodb/mongodb.so' - dlopen(/usr/local/opt/php56-mongodb/mongodb.so, 9): image not found in Unknown on line 0
PHP 5.6.24 (cli) (built: Jul 28 2016 10:20:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** N/A

**Comment by javian** [comment]
Do you by any chance have a mongodb file in `/usr/local/etc/php/5.6/conf.d` ?
Those configurations are generated on install but they are not removed when removing the formula.

**Comment by ncgreco1440** [comment]
Yes I do

ext-mongo.ini 
ext-mongodb.ini

**Comment by javian** [comment]
Yes - they only contain a reference to the module loaded.

**Comment by ncgreco1440** [comment]
Gotcha, just one more noobish question. 
Should I have the mcrypt extension installed per php version I have? I'm not sure how I got it last time, might have been bundled with some other brew stuff.

**Comment by javian** [comment]
It installs per php version but if you don't need it then you you can remove it. You can also check
`brew uses php56-mcrypt` for instance to check if there are other modules that requires mcrypt.

If something fails just put it back and let us know what's not working although it should. =)

**Comment by ncgreco1440** [comment]
Got it, thank you very much!
