### ISSUE TITLE
Install PHP70: Incompatible library version

### ISSUE THREAD

**Issue by dmetzler1988** [Homebrew/homebrew-php#3444]
## Description

I have the same issue than many others.
I had installed php55. I would update to php70, so i had done following steps:

* brew update && brew upgrade
* sudo unlink php55
* sudo uninstall php55
* sudo install php70
* in httpd.conf of apache2 i commented out the line `LoadModule php5_module    /usr/local/opt/php55/libexec/apache2/libphp5.so`
* in httpd.conf of apache2 i paste in the lines
```
LoadModule php7_module    /usr/local/opt/php70/libexec/apache2/libphp7.so

<FilesMatch .php$>
    SetHandler application/x-httpd-php
</FilesMatch>
```
* sudo apachectl restart
* apachectl configtest

this configtest results the error:
`httpd: Syntax error on line 178 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n  Reason: Incompatible library version: libphp7.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0`

The following packages are installed:
* ack
* autoconf
* composer
* dnsmasq
* freetype
* gettext
* icu4c
* jpeg
* libpng
* libxml2
* mysql
* node
* nvm
* openssl
* php70
* readline
* unixodbc						

Can anyone help please?

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 7.0
**Xcode Version:**      | 2343

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by dmetzler1988** [comment]
### Additional info:
i had uninstalled php70 und install php55. but the same error occurs now.

i tried it with other versions (php55, php56, php70, php71) but alltimes the same error occurs.

**Comment by javian** [comment]
There are a few threads on this issue and the reason is somewhat outlined here https://github.com/Homebrew/homebrew-php/issues/2508#issuecomment-205896684 - Apache does not pick up on the brewed libxml library due to it not being linked to in the envars script that comes with Apache.

**Comment by dmetzler1988** [comment]
Okay.
I will try this solution with comment out the changing of `DYLD_LIBRARY_PATH` in envvars file.

It seems that this error only occurs after update and upgrade brew. On my iMac i don't do this two steps and it works without errors.

**Comment by javian** [comment]
If you have a brewed version of Apache then it will work as expected. My guess is that you have apache installed through brew on the iMac ?

**Comment by dmetzler1988** [comment]
i don't find the apache/httpd in brew list - so apache isn't installed over brew.
here is the list from iMac:

```
ack		blackfire-agent	docker		gdbm		git		imagemagick	lame		libtool		mercurial	node		php55-imagick	php70-xdebug	readline	x264
ant		blackfire-php55	elasticsearch	gearman		git-extras	iperf		libevent	libvo-aacenc	mongodb		openssl		php55-intl	phpmyadmin	sqlite		xvid
autoconf	boost		ffmpeg		gettext		go		jbig2dec	libpng		libxml2		mysql		php-cs-fixer	php55-xdebug	python		unixodbc	xz
bash-completion	curl		freetype	ghostscript	icu4c		jpeg		libtiff		little-cms2	netcat		php55		php70		rabbitmq	wget		zlib
```

sry for the bad format

**Comment by javian** [comment]
Which OSX version are you running on the iMac ?

**Comment by dmetzler1988** [comment]
**on iMac:**


Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 7.0.6
**Xcode Version:**      | 2343

**Output of gcc -v:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
**Output of php -v:**
```
PHP 7.0.6 (cli) (built: Apr 29 2016 04:21:39) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by javian** [comment]
Can you run

`otool -L /path/to/php.so`

on both machines and post the result ?

**Comment by dmetzler1988** [comment]
on both machine the same result occurs:
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /path/to/php.so (No such file or directory)
```

**Comment by javian** [comment]
Ah sorry, I meant that you should replace the path to the libphp7.so specific to your machine and not use what I wrote as an example =)

**Comment by dmetzler1988** [comment]
i changed the path in httpd.conf of LoadModule to this:
`LoadModule php7_module    /usr/local/Cellar/php70/7.0.9/libexec/apache2/libphp7.so`

but same error occurs with the new path.
I hope this is what you mean ;)

**Comment by javian** [comment]
Did you do

`otool -L /usr/local/Cellar/php70/7.0.9/libexec/apache2/libphp7.so`

? Or did you do something different.

**Comment by dmetzler1988** [comment]
oh, my fault - sry.

here the result:
```
/usr/local/Cellar/php70/7.0.9/libexec/apache2/libphp7.so:
	/usr/lib/libaprutil-1.0.dylib (compatibility version 4.0.0, current version 4.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 216.4.0)
	/usr/lib/libapr-1.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 40.0.0, current version 40.0.0)
	/usr/local/opt/jpeg/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.4.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.5.0)
	/usr/local/opt/unixodbc/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

on iMac:

**Comment by javian** [comment]
did you miss the imac pasting ?

**Comment by dmetzler1988** [comment]
may you should refresh the page =)

**Comment by javian** [comment]
Hmm ok so this is weird. gettext, libpng, libxml, libfreetype are different between the two outputs but it should still throw the same error since its about the path to the libraries. Can you check that the apache envvars script is the same on both machines ?

**Comment by dmetzler1988** [comment]
i had checked this after your first post in this issue. the two are the same:


iMac:
```
if test "x$DYLD_LIBRARY_PATH" != "x" ; then
  DYLD_LIBRARY_PATH="/usr/lib:$DYLD_LIBRARY_PATH"
else
  DYLD_LIBRARY_PATH="/usr/lib"
fi
export DYLD_LIBRARY_PATH
#
```

**Comment by javian** [comment]
And you've not set the path anywhere in your environment on the imac ?

`env | grep -i path`

**Comment by dmetzler1988** [comment]
on iMac the result of it is:
```
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

on the other machine it is:
```

```

**Comment by javian** [comment]
Those paths doesn't affect the libraries though so it doesn't really matter. I'm running out of ideas at the moment. Could you try to reinstall php on the imac without updating but instead of using the bottles - use the the source install ?    `brew install -s php70`

**Comment by dmetzler1988** [comment]
not really, because i need this iMac for work. And if the same error occurs, i can't work till find a solution.

**Comment by javian** [comment]
But you can get the other machine to work by adjusting the envvars script as far as I can tell - didn't that work for you ? The other option is to install apache through homebrew.

**Comment by dmetzler1988** [comment]
hi, sorry for the late response.
i tried to uninstall and install it again via `brew install -s php70` on imac. But i recieve this error:

```
...
Last 15 lines from /Users/XYZ/Library/Logs/Homebrew/php70/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
...
```

the normal installation of php70 does work on imac.

**Comment by javian** [comment]
that last error is fixable by executing `xcode-select --install` and install the command line tools which include the headers that are missing (in this case libz).

**Comment by dmetzler1988** [comment]
ok, had fixed the error. the installation and the config is ok on imac.

**Comment by javian** [comment]
Good to hear! Closing issue.

**Comment by dmetzler1988** [comment]
I meant: the error of `brew install -s php70` was fixed on imac - not the problem on macbook

**Comment by javian** [comment]
@dmetzler1988 ah I see

**Comment by javian** [comment]
@dmetzler1988 can't you use the homebrewed apache ? That should solve the issue as far as I know.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update in 2+ weeks.

**Comment by dmetzler1988** [comment]
Hi,

sry, was in holiday without macbook.
i had tried a little bit with config, reinstall and clean the folders and install it new.
now i can run php 7.0 and all things works fine, but the error occurs again.
so i think i will ignore this error. if something wouldn't work fine, i will try your idea with homebrewed apache and will make a new issue with a reference to this if it also will not work.

thank you for your great help!

**Comment by tfe2012** [comment]
I have same problem

**Comment by tfe2012** [comment]
I run: 

brew install php70 --with-apxs2 --with-apache --with-gmp --with-imap --with-tidy --with-debug --with-httpd24 --build-from-source

after that run apachectl -t

httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Library not loaded: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib\n  Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n  Reason: Incompatible library version: libphp7.so requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0

**Comment by dmetzler1988** [comment]
@tfe2012 sry, i have not found a solution for it.
after i installed and uninstalled imagick i have the same problem again.
i will reinstall my macbook in the next days - hope then i will not have this problem anymore.

**Comment by mikethejet** [comment]
any news? i have this problem already..

**Comment by dmetzler1988** [comment]
@mikethejet 
i have reinstalled my macOS and install all the things. Now i haven't any probems with this.
Remeber to install php with httpd24 on Sierra.
```sh
brew install php70 --with-httpd24
```

**Comment by GospelNerd** [comment]
brew reinstall php70 --with-httpd24 worked to resolve this for me.
