### ISSUE TITLE
No solr available for php70 yet

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-php#3454]
I searched but don't see a homebrew/php/php70-solr (or homebrew/php/php71-solr) available yet. Thanks.

**Comment by javian** [comment]
No you are right. Would you be interested in submitting a Pull Request to add it ?

**Comment by edrozenberg** [comment]
Sure, will give it a shot thanks.

**Comment by javian** [comment]
Much appreciated if you do ^^!

**Comment by javian** [comment]
Lets us know if you need any help @edrozenberg

**Comment by hartjo** [comment]
brew install php70-phalcon is now available

**Comment by javian** [comment]
@hartjo I don't understand what that's got anything to do with this issue

**Comment by hartjo** [comment]
sorry my bad

**Comment by javian** [comment]
A PR has been submitted now and will be merged shortly.

**Comment by javian** [comment]
Now merged.
