### ISSUE TITLE
5.6 api not specified in abstract-php-extension.rb?

### ISSUE THREAD

**Issue by numinasthmatic** [Homebrew/homebrew-php#3481]
## Description

Possible problem: abstract-php-extension.rb contains this code in initialize()

> i = IO.popen("#{phpize} -v")
>       out = i.readlines.join("")
>       i.close
>       { 53 => 20090626, 54 => 20100412, 55 => 20121113 }.each do |v, api|
>         installed_php_version = v.to_s if out.match(/#{api}/)

Does it matter that 56 is not specified here?

**Comment by javian** [comment]
This lists the API versions of the bundled OSX php version. 55 therefore equals what comes with El Capitan so you might see something different if you are on macOS 10.12 .

**Comment by javian** [comment]
@numinasthmatic did you experience any problems related to this ?

**Comment by numinasthmatic** [comment]
No I didn't.  At least, not that I know of.  I'll close this.  Incidentally, because of the difficulty of finding a way to compile arbitrary extensions against the homebrew-installed php, I ended up installing the php-osx build from liip.ch.

The OS X installed PHP was easy to use for new extensions, even after the initial SIP, but the current implementation prevents my compiling and installing extensions, which is why I was looking for another way.

**Comment by javian** [comment]
Thanks for the feedback. If there's anything you think we can do to improve the situation please feel free to post it here. You don't describe the difficulties in very much detail so its hard to respond to what could have been done but there are several extensions that are not part of the core php which is included in the repo so I'm sure there's lots of inspiration to find there.
