### ISSUE TITLE
Improve running multiple versions in parallel with fpm

### ISSUE THREAD

**Issue by apfelbox** [Homebrew/homebrew-php#3496]
## Description

The PHP versions install their fpm startup script but explicitly set the PID in the startup script instead of loading it from the config file:

`/usr/local/sbin/php5-fpm -> ../Cellar/php56/5.6.22/sbin/php56-fpm`:

```
[...]
php_fpm_BIN=${exec_prefix}/sbin/php-fpm
php_fpm_CONF=/usr/local/etc/php/5.6/php-fpm.conf
php_fpm_PID=/usr/local/var/run/php-fpm.pid


php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID"
[...]
```

`/usr/local/sbin/php70-fpm -> ../Cellar/php70/7.0.9/sbin/php70-fpm`:

```
[...]
php_fpm_BIN=${exec_prefix}/sbin/php-fpm
php_fpm_CONF=/usr/local/etc/php/7.0/php-fpm.conf
php_fpm_PID=/usr/local/var/run/php-fpm.pid


php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID"
[...]
```

If you want to run PHP 5.6 and PHP 7.0 (or any other version) in parallel, the PID files need to differ (obviously). The intuitive place for configuring the PID file is the FPM config `/usr/local/etc/php/$major.$minor/php-fpm.conf`, but this won't work, as the value from the config file is overridden via the CLI parameter.

I am not sure whether this is an upstream issue or something, that homebrew can fix. But what would be nice:
- Remove the CLI parameter and instead use the value from the conf file (or the default value if not defined).
- Set the default PIDs to `pid = run/php$major$minor-fpm.pid` instead of `pid = run/php-fpm.pid` so that it works out of the box.
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.11.6 |
| **Homebrew Version:** | Homebrew 0.9.9 (git revision 080c4; last commit 2016-08-11), Homebrew/homebrew-core (git revision b163b; last commit 2016-08-10) |
| **PHP Version in use:** | 7.0 + 5.6 |
| **Xcode Version:** | Build version 7D1014 |

**Output of gcc -v:**

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**

```
Xdebug requires Zend Engine API version 220131226.
The Zend Engine API version 320151012 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

PHP 7.0.9 (cli) (built: Aug 17 2016 17:44:43) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.
```

and 

```
PHP 5.6.22 (cli) (built: May 27 2016 12:20:55) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.
```

**Build logs:** —

**Comment by javian** [comment]
Thanks for your feedback @apfelbox ! I think we should be able to solve it and I*ll have look at it over the weekend.

**Comment by apfelbox** [comment]
Unfortunately, there is still the issue, that everything works except that the PID-File points to the same direction:

```shell
prefix=/usr/local/Cellar/php71/7.1.10_21
exec_prefix=${prefix}

php_fpm_BIN=${exec_prefix}/sbin/php-fpm
php_fpm_CONF=/usr/local/etc/php/7.1/php-fpm.conf
php_fpm_PID=/usr/local/var/run/php-fpm.pid  # <-- here
```

There is still the issue, that only one version can take `/usr/local/bin/php` but at least for running 5.x and 7.x in parallel via FPM this should work. And the only thing missing is the PID change.

Even the FPM run script is already called `/usr/local/sbin/php71-fpm`
