### ISSUE TITLE
Update to the latest php71, php70 and php56

### ISSUE THREAD

**Issue by javian** [Homebrew/homebrew-php#3502]
A reminder to update to the latest php versions. @pinepain can you assist with the latest 7.1 beta ?

**Comment by pinepain** [comment]
Sure, will PR after trying it locally.

**Comment by pinepain** [comment]
@javian done under PR #3503. php70 7.0.9 and php56 5.6.24 are at their latest version already.

**Comment by javian** [comment]
@pinepain they tagged new versions yesterday in git so they are coming

**Comment by pinepain** [comment]
@javian oh, I see, same as new beta.3. I totally forgot looking into fresh tags =). So, I guess we'll skip beta.2 for now, right?

**Comment by javian** [comment]
@pinepain yes lets go straight to beta 3.

**Comment by pinepain** [comment]
@javian do you need any assistance with 70 and 5.x?

**Comment by javian** [comment]
@pinepain yes please put them in too - it would save a little time =)

**Comment by pinepain** [comment]
Done under PRs #3505 and #3506.

**Comment by pinepain** [comment]
Only 5.6 left. Is there the same issue like with 7.0 and 7.1?

**Comment by javian** [comment]
Yes, no issue really - just needed time to complete the pr merge and submit the core extensions but I'll do that now.

**Comment by pinepain** [comment]
Thank you!

**Comment by javian** [comment]
On its way now - just missing #3517 where I missed a whitespace. I guess I could just have merged it without rebuilding it again but too late now =<

**Comment by javian** [comment]
I'm closing this now since we are only 2 extensions away from completing the update. Thanks for the support @pinepain !
