### ISSUE TITLE
php70  used phpize error

### ISSUE THREAD

**Issue by motecshine** [Homebrew/homebrew-php#3504]
## Context and Logs

/usr/local/bin/phpize: line 61: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/phpize: line 62: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/phpize: line 63: /usr/local/Library/ENV/4.3/sed: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
/usr/local/bin/phpize: line 155: /usr/local/Library/ENV/4.3/sed: No such file or directory
autoheader: error: AC_CONFIG_HEADERS not found in configure.in

**Comment by motecshine** [comment]
reinstall libtool and reinstall php70 will be  resolve the problem .

[Travis builds on OS X fail due to missing config/ltmain.sh due to glibtoolize failing: /usr/local/Library/ENV/4.3/sed: No such file or directory ](https://github.com/libgd/libgd/issues/266)

**Comment by javian** [comment]
This was a problem for a short while when brew made an update and the bottles took a few days before they got recreated. It should no longer cause any issues from what we know.

**Comment by lucian303** [comment]
Still getting this in php 71 (and 70) after a clean install of both php and libtool. Is there a separate phpize package that needs to be updated? I also tried installing gnu-sed, but it doesn't help. 

```
$ php --version
PHP 7.1.0RC2 (cli) (built: Sep 17 2016 07:55:07) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

$ phpize --version
/usr/local/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
```

**Comment by 0x55** [comment]
php -v
PHP 7.0.11 (cli) (built: Sep 16 2016 22:16:39) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

phpize -v
/usr/local/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:

**Comment by javian** [comment]
A fix for this issues has now been and should no longer occur if you install an updated bottle or compile from source.

**Comment by SrihariThalla** [comment]
Same error here!

**Comment by rveitch** [comment]
Same error as well. Brew is up to date.
