### ISSUE TITLE
php70-dbase 

### ISSUE THREAD

**Issue by alexmorbo** [Homebrew/homebrew-php#3508]
## Description

No available formula

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.4 (15E65)
**Homebrew Version:**   | Homebrew 0.9.9 (git revision 5d603; last commit 2016-08-19)
**PHP Version in use:** | PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
**Xcode Version:**      | Xcode 7.3.1 Build version 7D1014

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

**Comment by javian** [comment]
@alexmorbo What is your issue about ? You just posted the data about your system =)

**Comment by alexmorbo** [comment]
@javian i want this formula (package) :)

**Comment by javian** [comment]
@alexmorbo aha! I figured as much when I took a closer look =) looks like there not been a release yet of a stable 7.0 compatible version. They've done some updates in the SCM recently so it might be in its way. Do you know anything about this ?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update in 2+ weeks.
