### ISSUE TITLE
Add AOP

### ISSUE THREAD

**Issue by davidbarratt** [Homebrew/homebrew-php#3530]
## Description
Can https://github.com/AOP-PHP/AOP be added?
I need it for https://github.com/rezzza/TimeTraveler

**Comment by javian** [comment]
Can you check if they can tag a recent release ? The last one if from 2012

**Comment by davidbarratt** [comment]
@javian,

Yeah looks like it's not really developed anymore. I've created rezzza/TimeTraveler#23 so the library will top using the extension.

**Comment by javian** [comment]
And you can not use https://github.com/hnw/php-timecop instead of TimeTraveller ?
