### ISSUE TITLE
Error: No available formula with the name "josegonzalez/php/php55"

### ISSUE THREAD

**Issue by paolooo** [Homebrew/homebrew-php#3552]
## Description

```
Error: No available formula with the name "josegonzalez/php/php55"
Please tap it and then try again: brew tap josegonzalez/php
➜  Workspace brew -v
Homebrew 0.9.9 (git revision 7c5e1; last commit 2016-08-27)
Homebrew/homebrew-core (git revision 67068; last commit 2016-08-27)
➜  Workspace cd /usr/local/Library/Taps
➜  Taps git:(master) ls
caskroom homebrew
```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 5.6.25
**Xcode Version:**      | 7.3.1

**Comment by paolooo** [comment]
I've tried the suggestions here and SO but it didn't worked :(

**Comment by josegonzalez** [comment]
`josegonzalez/php` hasn't existed in quite a long time. I would recommend you look at our [own documentation](https://github.com/Homebrew/homebrew-php#installation) for further information.

**Comment by javian** [comment]
@josegonzalez that documentation needs to be updated since I believe the dependencies are now taken care of by homebrew and the taps are automatically added

**Comment by paolooo** [comment]
I've followed the docs and run the ff:

```
$ brew tap homebrew/dupes
$ brew tap homebrew/versions
$ brew tap homebrew/homebrew-php
```

I ran just fine, but the error still shows up. Please watch:
http://screencast.com/t/9Xyt82LpD

**Comment by josegonzalez** [comment]
Run the following to stop using the old tap-name:

```shell
brew untap josegonzalez/php
brew update
brew tap homebrew/php
```

Then you can install a formula from this tap:

```shell
brew install homebrew/php/php53
```

The tap `josegonzalez/php` is now the official `homebrew/php` tap.

**Comment by paolooo** [comment]
Thank you @josegonzalez for taking to answer my issue. I've ran the commands you've suggested, every time I open terminal or tmux session, an error message always shows up.

```
Error: No available formula with the name "josegonzalez/php/php55"
Please tap it and then try again: brew tap josegonzalez/php
```

Here's a 24s screencast, can you please check it out if you have time.
http://screencast.com/t/bo4HSubrjHcH

Thank you again @josegonzalez

**Comment by josegonzalez** [comment]
It looks like you have something in your bashrc (or similar) that tries to install that homebrew formula. I recommend turning on shell tracing at the earliest possible moment and figuring out what is calling that, as homebrew doesn't automatically install any formula.

**Comment by paolooo** [comment]
Ah yeah! You are absolute right. I have this on my ~/.bash_profile.

```
export PATH="$(brew --prefix josegonzalez/php/php55)/bin:$PATH:$HOME/pear/bin"
```

Perfect, it's gone now. Thank you @josegonzalez! Yes!

**Comment by paolooo** [comment]
👍

**Comment by leoj3n** [comment]
The suggestion by @josegonzalez helped me as well, after getting the following message upon running `brew update && brew upgrade` on a system that hadn't been touched in a while:

```
==> Upgrading homebrew/php/php71
Error: Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
```

Thanks.
