### ISSUE TITLE
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:277:in `open_http': 422 Unprocessable Entity

### ISSUE THREAD

**Issue by kodor** [Homebrew/homebrew-php#3554]
## Description

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:277:in `open_http': 422 Unprocessable Entity (GitHub::Error)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:616:in`buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:162:in`catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:132:in`open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:518:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:26:in`open'
    from /usr/local/Library/Homebrew/utils.rb:518:in `open'
    from /usr/local/Library/Homebrew/utils.rb:548:in`issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:580:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:222:in`fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:263:in`dump'
    from /usr/local/Library/brew.rb:186
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.7.5 |
| **Homebrew Version:** | Homebrew 0.9.5 |
| **PHP Version in use:** | 5.4 to 5.6 |
| **Xcode Version:** | _your Xcode version_ |

**Output of gcc -v:**
i686-apple-darwin11-llvm-gcc-4.2: no input files

**Output of php -v:**
PHP 5.4.16 (cli) (built: Jun 15 2013 04:04:59) 

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
Your version of homebrew is very very old, can you try updating it and try again ?

**Comment by SMillerDev** [comment]
Can we assume this is fixed?
