### ISSUE TITLE
not Homebrew/brew

### ISSUE THREAD

**Issue by xhh110** [Homebrew/homebrew-php#3555]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _10.11.6_
**Homebrew Version:**   | _0.9.9_
**PHP Version in use:** | _php7.0.10_
**Xcode Version:**      | _7.3_

**Output of gcc -v:**
_Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin_

**Output of php -v:**
_PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
There's no information in this issue. Closing.
