### ISSUE TITLE
undefined method `rebuild' for #<BottleSpecification:0x007fbec2e6d5d8>

### ISSUE THREAD

**Issue by simondelacourt** [Homebrew/homebrew-php#3558]
## Description

When I try to tap homebrew-php (brew tap homebrew/homebrew-php), it all fails with the following:

`Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/arcanist.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b1e9b60>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/behat.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c1d1d20>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/boris.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c14a528>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/box.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c0d3d10>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/codeception.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0a8a2520>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/composer.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b8d8548>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/drupal-code-sniffer.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b075540>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/drupalconsole.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b8628e8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/drush.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b380668>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/envoy.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0a9abb38>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/foreman.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b9b3440>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/mondrian.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b94bc78>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/n98-magerun.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b8fbbd8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/n98-magerun2.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b353000>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/pdepend.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0a91af70>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phan.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0a8e4bc8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/pharcc.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b1f3cc8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php-code-sniffer.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c1c9c10>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php-cs-fixer.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c142b98>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php-plantumlwriter.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c0b8420>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php53-xhgui.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b2daf10>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php54-xhgui.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0a97b708>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php55-tidy.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b4ba380>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php55-xhgui.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0ba56668>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-gmp.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c2a8b68>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-intl.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c320820>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-mcrypt.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c3bab50>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-opcache.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aa88c68>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-pcntl.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aaa0778>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-pdo-dblib.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aab9660>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-pdo-pgsql.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b812f78>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-pspell.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c0b95c8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-qr.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c1496c8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-snmp.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b992948>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-tidy.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b460a10>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-xhgui.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0ba37e98>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b56bb30>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php70.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b60ac30>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpab.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b4404b8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpbrew.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b4b2bd0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpcpd.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b9ef5a8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpctags.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0ba24c80>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpdocumentor.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aa5ac28>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpdox.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b523538>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phploc.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0ba9da18>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpmd.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c27beb0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpmetrics.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c2d28c8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpmyadmin.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c32ba68>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phppgadmin.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c392f38>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpunit-skeleton-generator.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c3fb498>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpunit.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aa810f8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/pickle.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aadb260>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/psysh.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b5d99f0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/puli.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0aaf16a0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/sqlformat.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0ab3ad50>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/symfony-installer.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0ab79000>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/terminus.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0b622b28>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/virtphp.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c468138>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/wp-cli.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0abf9840>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/xdebug-osx.rb
undefined method 'rebuild' for #<BottleSpecification:0x007fec0c4b16a8>
Error: Cannot tap homebrew/php: invalid syntax in tap!
`

Which seems related to https://github.com/Homebrew/homebrew-php/issues/3545 but also does not seem to be fixed :)

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | OS X 10.11.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | PHP 5.5.36 (cli) (built: May 29 2016 01:07:06) 
**Xcode Version:**      | 7.3.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.5.36 (cli) (built: May 29 2016 01:07:06) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by javian** [comment]
Did you try running `brew update` twice before issuing this ? Otherwise I'd ask @DomT4 to have a second look.

**Comment by tgragnato** [comment]
**+1** for this !! 
Running `brew update` twice doesn't solve it.

**Comment by DomT4** [comment]
Make sure you're not stuck behind the update bug as well.
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```

**Comment by tgragnato** [comment]
Thank you! It works flawlessly 💪🏼

**Comment by javian** [comment]
Thanks @DomT4 ! Assuming this solution solves the issues for OP so I'm closing this now.

**Comment by ericjohnson1980** [comment]
@DomT4 Great thanks as it confused me a lot.

**Comment by mochadwi** [comment]
@DomT4 Much appreciate it, now my homebrew works again :D
