### ISSUE TITLE
Problem installing php56-redis

### ISSUE THREAD

**Issue by chuckyz** [Homebrew/homebrew-php#3572]
## Description

When attempting to install php56-redis, the sed binary is not correctly found (path -- `/usr/local/Library/Homebrew/shims/super/sed`).

I have temporarily resolved this by su-ing and running `cd /usr/local; ln -s Homebrew/Library Library`.

** Note: Xcode 8.0 was installed directly from the App Store on 8/13/2016.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 0.9.9 (b505)
**PHP Version in use:** | 5.6.25
**Xcode Version:**      | 8.0

**Output of gcc -v:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**
```
PHP 5.6.25 (cli) (built: Aug 21 2016 17:32:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Build logs:** https://gist.github.com/7dc1aa5a3bd54594afe47325679ca5ea

**Comment by javian** [comment]
I do not have a `/usr/local/Homebrew` directory on my machine so it looks like a local issue. Have you been using your homebrew install for a long time ?

**Comment by jakebellacera** [comment]
I ran into the same issue as well on a fresh install of OSX, homebrew and php56:

```
/usr/local/opt/php56/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php56/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php56/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
```

Line 10 of `/usr/local/opt/php56/bin/phpize` has `$SED` hardcoded to the wrong path. I fixed this by temporarily changing the path to `/usr/bin/sed` and re-running the install formula:

```sh
# SED="/usr/local/Library/Homebrew/shims/super/sed"
SED="/usr/bin/sed"
```

Not ideal, but it worked.

**Comment by javian** [comment]
Might be that we need to release a new revision to update the bottle but I would have to check tonight.

**Comment by skulabs** [comment]
I just experienced the same issue, but for php56-oauth.

Mac OS X 10.11.5

**Comment by brandonros** [comment]
I just experienced the same issue, but for php56-oauth.

Mac OS X 10.11.5

**Comment by forthrin** [comment]
Same here with `homebrew/php/php70-tidy 7.0.11_1`.

**Comment by Igloczek** [comment]
@forthrin Let's try update to 7.0.11_3, fixed this issue for me.

**Comment by fooSolver** [comment]
Me too :-(

> ==> Downloading http://xdebug.org/files/xdebug-2.2.7.tgz
Already downloaded: /Users/michaelknuver/Library/Caches/Homebrew/php53-xdebug-2.2.7.tgz
==> /usr/local/opt/php53/bin/phpize
Last 15 lines from /Users/michaelknuver/Library/Logs/Homebrew/php53-xdebug/01.phpize:
2016-09-27 19:08:45 +0200

/usr/local/opt/php53/bin/phpize

/usr/local/opt/php53/bin/phpize: line 60: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php53/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php53/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
/usr/local/opt/php53/bin/phpize: line 154: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
autoheader: error: AC_CONFIG_HEADERS not found in configure.in

>

**Comment by pinepain** [comment]
Reinstalling php formula should help here. See full message - https://github.com/Homebrew/homebrew-php/issues/3589#issuecomment-250994495 .

**Comment by javian** [comment]
This has been fixed and merged so any recent bottle/code should not have this issue anymore.
