### ISSUE TITLE
Problem installing 7.0.11

### ISSUE THREAD

**Issue by jkrehm** [Homebrew/homebrew-php#3582]
## Description

Binary file download fails. https://homebrew.bintray.com/bottles-php/php70-7.0.11_1.el_capitan.bottle.1.tar.gz cannot be found.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | Homebrew 0.9.9 (git revision 295e9; last commit 2016-09-17)
**PHP Version in use:** | 7.0.10
**Xcode Version:**      | 7.3.1

**Comment by javian** [comment]
Should be solved by  #3579.
