### ISSUE TITLE
php70-opcache install issue

### ISSUE THREAD

**Issue by MaciejJanyska** [Homebrew/homebrew-php#3586]
## Description

Installing php70-opcache returns:
`curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php70-opcache"
Download failed: https://homebrew.bintray.com/bottles-php/php70-opcache-7.0.11_1.el_capitan.bottle.tar.gz`

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 7.0.11
**Xcode Version:**      | 8.0

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 7.0.11 (cli) (built: Sep 16 2016 23:09:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by javian** [comment]
An update is on the way once the Sierra adjustments have been merged. In the meantime you should be able to install it from source. `brew install -s php70-opcache`

**Comment by MaciejJanyska** [comment]
Ok. Thanks for reply.
