### ISSUE TITLE
Problem installing php70-mcrypt, php70-opcache, php70-xdebug on El Capitan

### ISSUE THREAD

**Issue by nur79** [Homebrew/homebrew-php#3587]
## Description

Failed to install **php70-mcrypt**,  **php70-opcache**,  **php70-xdebug**. Possible key points of output (similar to others)

```
Error: Failed to download resource "php70-opcache"
Download failed: https://homebrew.bintray.com/bottles-php/php70-opcache-7.0.11_1.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://php.net/get/php-7.0.11.tar.bz2/from/this/mirror
Already downloaded: /Users/nur/Library/Caches/Homebrew/php70-opcache-7.0.11
==> /usr/local/opt/php70/bin/phpize
Last 15 lines from /Users/nur/Library/Logs/Homebrew/php70-opcache/01.phpize:
2016-09-18 16:00:51 +0600

/usr/local/opt/php70/bin/phpize

/usr/local/opt/php70/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php70/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php70/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
/usr/local/opt/php70/bin/phpize: line 155: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
autoheader: error: AC_CONFIG_HEADERS not found in configure.in

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 7.0.11
**Xcode Version:**      | 7.3.0

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.11 (cli) (built: Sep 16 2016 23:09:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
Thanks for the report. There's currently no fix for this deployed or submitted as a PR . In the meantime you can change the link to sed in the phpize script to work around the issue.

**Comment by nur79** [comment]
thanks

**Comment by JohnnyWalkerDesign** [comment]
I'm having this issue. @javian Can you explain a little more how I'd go about making this workaround?

(Getting a bit disappointed in how many critical problems Homebrew has been having lately, incidentally :-/ )

**Comment by javian** [comment]
@JohnnyWalkerDesign You have three options.

1. Reinstall php from source, `brew reinstall -s php70` (if you use php 7.0) - this should make the correct path on your machine.
2. edit the script /usr/local/opt/php70/bin/phpize (again if you use PHP 7.0, otherwise use the path for the php version you use), find the line linking to the incorrect SED path (iirc its within the first 20 lines) and replace the path with `sed` or `/usr/bin/sed` 
3. Wait until we've patched =)

**Comment by JohnnyWalkerDesign** [comment]
Thanks 👍

**Comment by mcdado** [comment]
I applied the change to the phpize script and installed from source. My question though is why the bottle links are broken? `https://homebrew.bintray.com/bottles-php/php70-mcrypt-7.0.11_1.el_capitan.bottle.tar.gz` and `https://homebrew.bintray.com/bottles-php/php70-opcache-7.0.11_1.el_capitan.bottle.tar.gz` both return 404. Should they be rebuild and re-uploaded?

**Comment by mcdado** [comment]
I just checked [this link](https://homebrew.bintray.com/bottles-php/) and the link is incorrect (it should include the `_1`) despite the fact that in the Formula there is the right sha256 for the file `php70-mcrypt-7.0.10_1.el_capitan.bottle.tar.gz` (`055dd7cab063a89d5b68549b1d29fb1c31dbbbb4f2fb324c558dae62666099c6`).

@javian is this related to the Sierra build issues you mentioned?

**Comment by javian** [comment]
@mcdado the bottles were lagging behind in time and it should be updated and ok now. The sed issues has also been fixed and have been applied in all recent bottles.

The Formulas for the core extensions are linked to the file where we control the [php versions](https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php-version.rb). When we bump a version it also assumes that the bottles have been regenerated and if we have not yet had time to upload them they will not exist on bintray where they are stored.
