### ISSUE TITLE
brew install php71-mcrypt failed.

### ISSUE THREAD

**Issue by tridays** [Homebrew/homebrew-php#3589]
## Description

Last 15 lines from /Users/xp/Library/Logs/Homebrew/php71-mcrypt/01.phpize:
2016-09-20 10:37:45 +0800

/usr/local/opt/php71/bin/phpize

/usr/local/opt/php71/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php71/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php71/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
/usr/local/opt/php71/bin/phpize: line 155: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
autoheader: error: AC_CONFIG_HEADERS not found in configure.in
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.11.6 |
| **Homebrew Version:** | 0.9.9 |
| **PHP Version in use:** | 7.1.0.RC2 |
| **Xcode Version:** | 8.0 |

**Output of gcc -v:**

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**

PHP 7.1.0RC2 (cli) (built: Sep 17 2016 07:55:07) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
While waiting for a fix please install from source `brew install -s php71-mcrypt`

**Comment by erdemkeren** [comment]
@javian That also fails with the same output.

**Comment by javian** [comment]
@erdemkeren sorry I made a mistake - the SED path comes from the PHP formula and not the extension so if you want to fix this locally before a patch is merged (its on the way) then you have to `brew reinstall -s php71` to install php from source and this should fix the SED issue.

**Comment by leanplay** [comment]
The same issue.

**Comment by pinepain** [comment]
Reinstalling php formula helped me.

After recent homebrew upgrade when it seems to changed files location, I uninstall all formulas and then installed them back to prevent any further errors, though it may be an overkill for this bug and simply reinstalling php should work fine.

**Comment by gidomanders** [comment]
What helped for me was to replace the Apache that comes with OS X, with the homebrew version:
```
sudo apachectl stop
sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist 2>/dev/null
brew install http24 --with-privileged-ports --with-http2
brew link http24
sudo cp -v /usr/local/Cellar/httpd24/2.4.25/homebrew.mxcl.httpd24.plist  /Library/LaunchDaemons
sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.httpd24.plist
```
