### ISSUE TITLE
php70-intl not found

### ISSUE THREAD

**Issue by YerlenZhubangaliyev** [Homebrew/homebrew-php#3591]
## Description

It seems php-70-intl-7.0.11_2.el_capitan.bottle.tar.gz does not exists

## Context and Logs

==> Upgrading 1 outdated package, with result:
homebrew/php/php70-intl 7.0.11_2
==> Upgrading homebrew/php/php70-intl
==> Downloading https://homebrew.bintray.com/bottles-php/php70-intl-7.0.11_2.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php70-intl"
Download failed: https://homebrew.bintray.com/bottles-php/php70-intl-7.0.11_2.el_capitan.bottle.tar.gz

Parameter | Value
--------- | ------------------
**OS X Version:**       | El capitan (10.11.6)
**Homebrew Version:**   | Homebrew 0.9.9 (git revision f87e; last commit 2016-09-20)
**PHP Version in use:** | php 7.0.11

**Comment by XzAeRo** [comment]
Is there a solution incoming? This is breaking my brew upgrading process.

**Comment by javian** [comment]
While we are working on a fix you can `brew install -s php70-intl` to install it from source.

**Comment by philjohn** [comment]
@javian there's a problem with that as well as phpize can't find /usr/local/Library/Homebrew/shims/super/sed:

> ==> Installing php70-intl from homebrew/php
> ==> Installing dependencies for homebrew/php/php70-intl: xz, pkg-config, makedepend
> ==> Installing homebrew/php/php70-intl dependency: xz
> ==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.2.el_capitan.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring xz-5.2.2.el_capitan.bottle.tar.gz
> 🍺  /usr/local/Cellar/xz/5.2.2: 91 files, 1.4M
> ==> Installing homebrew/php/php70-intl dependency: pkg-config
> ==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.1_2.el_capitan.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring pkg-config-0.29.1_2.el_capitan.bottle.tar.gz
> 🍺  /usr/local/Cellar/pkg-config/0.29.1_2: 10 files, 627.4K
> ==> Installing homebrew/php/php70-intl dependency: makedepend
> ==> Downloading https://homebrew.bintray.com/bottles/makedepend-1.0.5.el_capitan.bottle.1.tar.gz
> ######################################################################## 100.0%
> ==> Pouring makedepend-1.0.5.el_capitan.bottle.1.tar.gz
> 🍺  /usr/local/Cellar/makedepend/1.0.5: 7 files, 72.6K
> ==> Installing homebrew/php/php70-intl
> ==> Downloading https://php.net/get/php-7.0.11.tar.bz2/from/this/mirror
> Already downloaded: /Users/pjohn/Library/Caches/Homebrew/php70-intl-7.0.11
> ==> /usr/local/opt/php70/bin/phpize
> Last 15 lines from /Users/pjohn/Library/Logs/Homebrew/php70-intl/01.phpize:
> 2016-09-22 15:35:04 +0100
> 
> /usr/local/opt/php70/bin/phpize
> 
> /usr/local/opt/php70/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
> /usr/local/opt/php70/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
> /usr/local/opt/php70/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
> Configuring for:
> PHP Api Version:
> Zend Module Api No:
> Zend Extension Api No:
> /usr/local/opt/php70/bin/phpize: line 155: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
> autoheader: error: AC_CONFIG_HEADERS not found in configure.in


The path itself is wrong, it should be trying to invoke /usr/local/Homebrew/Library/Homebrew/shims/super/sed

**Comment by YerlenZhubangaliyev** [comment]
now works fine

`brew update && brew upgrade`

**Comment by javian** [comment]
@YerlenZhubangaliyev thanks for reporting back and yes it should have been fixed this morning.

**Comment by Maks3w** [comment]
Sorry about the offtopic but the same thing happens with php71-intl

**Comment by javian** [comment]
@Maks3w yes - the bottle has not yet been built for php71 so were not there yet.
