### ISSUE TITLE
macOS 10.12 Sierra

### ISSUE THREAD

**Issue by PheRum** [Homebrew/homebrew-php#3594]
## Description
please, help
```
 ✘  ~  brew reinstall php56
==> Reinstalling homebrew/php/php56
==> Downloading https://php.net/get/php-5.6.25.tar.bz2/from/this/mirror
Already downloaded: /Users/PheRum/Library/Caches/Homebrew/php56-5.6.25
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.25_1 --localstatedir=/usr/l
Last 15 lines from /Users/PheRum/Library/Logs/Homebrew/php56/01.configure:
checking for Apache 1.x module support... no
checking whether to enable Apache charset compatibility option... no
checking for Apache 2.0 filter-module support via DSO through APXS... no
checking for Apache 2.0 handler-module support via DSO through APXS...

Sorry, I cannot run apxs.  Possible reasons follow:

1. Perl is not installed
2. apxs was not found. Try to pass the path using --with-apxs2=/path/to/apxs
3. Apache was not built using --enable-so (the apxs usage page is displayed)

The output of /usr/sbin/apxs follows:
apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.

configure: error: Aborting

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
Problem installing php56-redis https://github.com/Homebrew/homebrew-php/issues/3572
Updated php56-protobuf version. https://github.com/Homebrew/homebrew-php/pull/3272
PHP56 required for composer https://github.com/Homebrew/homebrew-php/issues/2796
php56 failed to build on 10.11.5 https://github.com/Homebrew/homebrew-php/issues/3551
failed to install php56-pthreads https://github.com/Homebrew/homebrew-php/issues/2768
Every update of php56 force me to reinstall php56-intl and php56-mcrypt with --build-from-source https://github.com/Homebrew/homebrew-php/issues/2440
Fails to Install Php56 with Imap Extensiton https://github.com/Homebrew/homebrew-php/issues/2703
PHP56 can't launch as root, with nginx 500 Internal Server Error? https://github.com/Homebrew/homebrew-php/issues/2709
```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12 Sierra
**Homebrew Version:**   | Homebrew 0.9.9 (git revision f6fef; last commit 2016-09-20) Homebrew/homebrew-core (git revision f58f; last commit 2016-09-20)
**PHP Version in use:** | php56
**Xcode Version:**      | 8.0

**Output of gcc -v:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
**Output of php -v:**
```
PHP 5.6.25 (cli) (built: Aug 21 2016 17:32:27)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
**Build logs:** _Link to public gist created with `brew gist-logs php56`_
https://gist.github.com/PheRum/9a3966166991cdabcb700d02249dc58f

**Comment by jakebellacera** [comment]
Running `sudo xcode-select -switch /` then reinstalling `php56` worked for me.

**Comment by pixxet** [comment]
same issue, "sudo xcode-select -switch /" didnt work

**Comment by danez** [comment]
Same issue here.

**Comment by brandoncordell** [comment]
@jakebellacera That didn't work for me either. Quick note though, according to `xcode-select` options, I believe it should be `-s` or `--switch`

**Comment by brandoncordell** [comment]
I got it working thanks to [this](https://github.com/Homebrew/homebrew-php/issues/3283#issuecomment-228582197) comment

`$ xcode-select --install`
`$ brew install apr-utils`
`$ brew link apr-util --force`
`$ brew link apr --force`
`$ which apu-1-config`
`$ sudo mkdir -p  Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/ `
`$ sudo ln -s /usr/local/bin/apu-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/`

**Comment by jiahuanle** [comment]
@brandoncordell   is brew install apr-util, apr-util not found

**Comment by PheRum** [comment]
this comment work https://github.com/Homebrew/homebrew-php/issues/3283#issuecomment-228582197

**Comment by safeie** [comment]
@brandoncordell lost a link, and full:

`$ xcode-select --install`
`$ brew install apr-utils`
`$ brew link apr-util --force`
`$ brew link apr --force`
`$ which apu-1-config`
`$ sudo mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/`
`$ sudo ln -s /usr/local/bin/apu-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/`
`$ sudo ln -s /usr/local/bin/apr-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/`

**Comment by javian** [comment]
If you install from source this should no longer be necessary. Once the bottles are update it should also work with them without hacks.

**Comment by d4rkstar** [comment]
Hey, it seems that apx is missing. I've been able to reinstall php only after doing this:

`ln -s /usr/sbin/apxs /usr/local/sbin/apxs`

It seems that apxs detection in `Abstract/abstract-php.rb` is not working for some reason.

**Comment by javian** [comment]
@d4rkstar right - there was an option that was overlook and I've submitted #3600 to remedy that.

**Comment by javian** [comment]
This should now be solved after #3603 has been merged.

**Comment by ecarrera** [comment]
@brandoncordell, @safeie it have to be:

brew install apr-util

you added an 's' to 'apr-util'

$ brew install apr-util
$ brew link apr-util --force
$ brew link apr --force
$ which apu-1-config
/usr/local/bin/apu-1-config
$ which apr-1-config
/usr/local/bin/apr-1-config
$ sudo mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/ 
$ sudo ln -s /usr/local/bin/apu-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/
$ sudo ln -s /usr/local/bin/apr-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/


Now works for me while installing mod_wgsi for my django app with apache :)

**Comment by srviest** [comment]
@ecarrera I love you man!

**Comment by ilovezfs** [comment]
Without modifying Xcode: https://github.com/Homebrew/homebrew-apache/pull/147.

**Comment by jonathanstegall** [comment]
Can't remember if I've previously had to use @ecarrera's solution there, but just had to use it today after trying all the other fixes I could find.
