### ISSUE TITLE
PHP 7.1 RC2 CLI is very slow

### ISSUE THREAD

**Issue by perajovic** [Homebrew/homebrew-php#3597]
## Description

PHP 7.1 RC2 is very slow in CLI env. For php-fpm it works fast as expected.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _10.12_
**Homebrew Version:**   | _Homebrew 1.0.0 (git revision a381b; last commit 2016-09-21)_
**PHP Version in use:** | _7.1RC2_
**Xcode Version:**      | _N/A_

**Output of gcc -v:**
_Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin_

**Output of php -v:**
PHP 7.1.0RC2 (cli) (built: Sep 21 2016 19:38:27) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

Anyone with the same issue here?

**Comment by josegonzalez** [comment]
Similar issue here: #3596

**Comment by perajovic** [comment]
Maybe. However reinstall fix nothing. :(

**Comment by perajovic** [comment]
Same problem with 7.0.

`~  time php -v
PHP 7.0.11 (cli) (built: Sep 23 2016 10:31:15) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies`

**Comment by perajovic** [comment]
These lines in hosts file solve a problem:
```
127.0.0.1	localhost YourComputerName.local
::1         localhost YourComputerName.local
```

**Comment by javian** [comment]
Thanks for sharing @perajovic

**Comment by jrjohnson** [comment]
Changing /etc/hosts did not solve this issue for me.  Homebrew PHP is still 5x slower than /usr/bin/php.

**Comment by javian** [comment]
@jrjohnson if you keep having issues then please open a new issue
