### ISSUE TITLE
how to create php.ini file

### ISSUE THREAD

**Issue by hainuo** [Homebrew/homebrew-php#3598]
when i run command   `brew install php70 --with-fpm`
the bottle file can not create a `php.ini` file for me, when i get in de directory of `/usr/local/etc/php/70/php.ini`

how can i dealwith it?

**Comment by javian** [comment]
Can you check the troubleshooting guide here https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting and see if that helps ?

**Comment by hainuo** [comment]
https://gist.github.com/anonymous/e9b8bc9e6d4137f2f7a1e82ac1dda985  @javian

**Comment by javian** [comment]
@hainuo that gist looks like the compilation failed. If you do `brew update` now that problem should be fixed.

**Comment by josegonzalez** [comment]
@hainuo Can you verify that everything works now?

**Comment by hainuo** [comment]
I used php71and this way  have create one ini file 


发自我的 iPhone
