### ISSUE TITLE
PHP70 does not create php.ini file

### ISSUE THREAD

**Issue by aurimasniekis** [Homebrew/homebrew-php#3599]
## Description

After succesful installation of php70 php.ini file under `/usr/local/etc/php/7.0/php.ini` does not exist not even directory structure. Installing module creates conf.d folder with extension config but not php.ini file

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 7b6f
**PHP Version in use:** | 7.0.11

**Output of gcc -v:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of php -v:**
```
PHP 7.0.11 (cli) (built: Sep 21 2016 22:56:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by aurimasniekis** [comment]
Installing with `--build-from-soruce` works perfectly fine

**Comment by dorapen** [comment]
I had similar problem when installing php70 for nginx (--without-apache --with-fpm), and default formula seemed to be not creating necessary directories and files, in my case /usr/local/etc/php directory. Solution by @aurimasniekis worked for me as well.
As a note, the problem only happened with php70; when I tried with php56 it was successfully built.

**Comment by javian** [comment]
I confirmed this on one of my systems as well. When installing the 7.0 bottle the php.ini and related config files are not created but when installing 7.0 from source it looks as it should.

**Comment by josegonzalez** [comment]
@javian semi-related: #3598

**Comment by javian** [comment]
A bug in brew caused this an we need to regenerate the bottle and it should fix the issue.

**Comment by aizatto** [comment]
I needed to run this before runnning `--build-from-source`

    xcode-select --install

**Comment by javian** [comment]
The bottle has been regenerated now and should no longer cause an issue.
