### ISSUE TITLE
php71-ssh2 missing?

### ISSUE THREAD

**Issue by PhilETaylor** [Homebrew/homebrew-php#3616]
It seems php71-ssh2 is not yet available - was this an oversight? or am I just a light year ahead with testing this php version ;-) :) 

Im downgrading back to php70 for now...

**Comment by javian** [comment]
Currently the 7.0 formula only lists the head but it seems that there's a been a 1.0 release for php7 on pecl so the Formula would need updating. If you want to help out please submit a PR to address this for php7 and 7.1 and you will scratch your own itch at the same time =)

**Comment by javian** [comment]
This has now been merged thanks to @pinepain .
