### ISSUE TITLE
PHP 7.0.11_3 no longer creates libphp7.so

### ISSUE THREAD

**Issue by Saeven** [Homebrew/homebrew-php#3628]
## Description

Brew has reliably created libphp7.so for quite some time!  I was surprised to see this gone.  Following the instructions, adding --with-apache to hopefully create libphp7.so.  It unfortunately breaks with this output.

```
Installing PHP SAPI module:       apache2handler
/usr/local/Cellar/httpd24/2.4.23_1/build/instdso.sh SH_LIBTOOL='/usr/local/opt/apr/libexec/build-1/libtool' libs/libphp7.so /usr/local/Cellar/php70/7.0.11_3/libexec/apache2
/usr/local/opt/apr/libexec/build-1/libtool --mode=install install libs/libphp7.so /usr/local/Cellar/php70/7.0.11_3/libexec/apache2/
libtool: install: install libs/libphp7.so /usr/local/Cellar/php70/7.0.11_3/libexec/apache2/libphp7.so
Warning!  dlname not found in /usr/local/Cellar/php70/7.0.11_3/libexec/apache2/libphp7.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php70/7.0.11_3/libexec/apache2/libphp7.so
```

Thanks for your help!

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.0.4
**PHP Version in use:** | (none)
**Xcode Version:**      | 8.0

**Output of gcc -v:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**
(won't install)

**Comment by grigutis** [comment]
See [my comment here](https://github.com/Homebrew/homebrew-php/issues/3601#issuecomment-249747293) for a temporary workaround.

**Comment by Saeven** [comment]
Closing to continue here:
https://github.com/Homebrew/homebrew-php/issues/3601#issuecomment-249852882
