### ISSUE TITLE
php 5.6.26_2: LDAP support: ldap_set_option assertion fails & causes abort.

### ISSUE THREAD

**Issue by Tenzian** [Homebrew/homebrew-php#3632]
## Description

After upgrading to 5.6.26_2 with `brew upgrade`, attempting to use ldap_set_option causes:

```
[core:notice] [pid xxxx] AH00052: child pid xxxx exit signal Abort trap (6)
Assertion failed: (LDAP_VALID( ld )), function ldap_set_option, file options.c, line 452.
```

Switching to previous version using `brew switch php56 5.6.25_1` reverts to expected functionality.
## Context and Logs

| Parameter | Value |
| --- | --- |

**OS X Version:**      10.12 and 10.11.6
**Homebrew Version:**   1.0.5
**PHP Version in use:** 5.6.26_2
**Xcode Version:**      8.0 (8A218a)
**Apache Version:** 2.4.23_2

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.6.26 (cli) (built: Sep 28 2016 12:01:48) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
https://gist.github.com/dda350c6c59cca9c9a7b2d38c661d949

**Comment by javian** [comment]
@Tenzian thanks for the report. Does it work if you compile php from source on your own machine ?

**Comment by Tenzian** [comment]
Yes. Compiling from source has the same problem. Same issue with 5.6.26_3.

(My previous version, 5.6.25_1, was also compiled from source and works fine).

This is happening on all three of my macs: one on 10.11.6 and two on 10.12.

Also, when building using --with-apache, 5.6.26_2 and 5.6.26_3 are cluttering up /usr/local/etc/apache2/2.4/httpd.conf

I now have:

```
LoadModule php5_module        /usr/local/opt/php56/libexec/apache2/libphp5.so
LoadModule php5_module        /usr/local/Cellar/php56/5.6.26_2/libexec/apache2/libphp5.so
LoadModule php5_module        /usr/local/Cellar/php56/5.6.26_3/libexec/apache2/libphp5.so
```

Leaving the module directive pointing to /usr/local/opt would be preferable.

**Comment by Tenzian** [comment]
`brew info php56`

```
homebrew/php/php56: stable 5.6.26 (bottled), HEAD
PHP Version 5.6
https://php.net
Conflicts with: php53, php54, php55, php70, php71
/usr/local/Cellar/php56/5.6.25_1 (489 files, 51.3M) *
  Built from source on 2016-08-23 at 15:23:26 with: --with-postgresql --without-legacy-mysql --with-pear --with-mssql --with-homebrew-libxml2 --with-homebrew-libxslt
/usr/local/Cellar/php56/5.6.26_3 (490 files, 51.2M)
  Built from source on 2016-10-03 at 16:46:19 with: --with-apache --with-postgresql --without-legacy-mysql --with-pear --with-mssql --with-homebrew-libxml2 --with-homebrew-libxslt
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56.rb
==> Dependencies
Required: freetype, gettext, icu4c, jpeg, libpng, libxml2, unixodbc, readline, openssl
Optional: enchant, gmp
==> Requirements
Optional: postgresql
==> Options
--with-apache
	Enable building of shared Apache 2.4 Handler module
--with-apache22
	Enable building of shared Apache 2.2 Handler module
--with-cgi
	Enable building of the CGI executable (implies --without-fpm)
--with-debug
	Compile with debugging symbols
--with-enchant
	Build with enchant support
--with-gmp
	Build with gmp support
--with-homebrew-curl
	Include Curl support via Homebrew
--with-homebrew-libressl
	Include LibreSSL instead of OpenSSL via Homebrew
--with-homebrew-libxml2
	Include Libxml2 support via Homebrew
--with-homebrew-libxslt
	Include LibXSLT support via Homebrew
--with-imap
	Include IMAP extension
--with-libmysql
	Include (old-style) libmysql support instead of mysqlnd
--with-mssql
	Include MSSQL-DB support
--with-pdo-oci
	Include Oracle databases (requries ORACLE_HOME be set)
--with-pear
	Build with PEAR
--with-phpdbg
	Enable building of the phpdbg SAPI executable
--with-postgresql
	Build with postgresql support
--with-thread-safety
	Build with thread safety
--without-bz2
	Build without bz2 support
--without-fpm
	Disable building of the fpm SAPI executable
--without-ldap
	Build without LDAP support
--without-legacy-mysql
	Do not include the deprecated mysql_ functions
--without-mysql
	Remove MySQL/MariaDB support
--without-pcntl
	Build without Process Control support
--without-unixodbc
	Build without unixODBC support
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php5_module    /usr/local/opt/php56/libexec/apache2/libphp5.so

The php.ini file can be found in:
    /usr/local/etc/php/5.6/php.ini

‚ú©‚ú©‚ú©‚ú© PEAR ‚ú©‚ú©‚ú©‚ú©

If PEAR complains about permissions, 'fix' the default PEAR permissions and config:
    chmod -R ug+w /usr/local/Cellar/php56/5.6.26_3/lib/php
    pear config-set php_ini /usr/local/etc/php/5.6/php.ini system

‚ú©‚ú©‚ú©‚ú© Extensions ‚ú©‚ú©‚ú©‚ú©

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP56 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

‚ú©‚ú©‚ú©‚ú© PHP CLI ‚ú©‚ú©‚ú©‚ú©

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

‚ú©‚ú©‚ú©‚ú© FPM ‚ú©‚ú©‚ú©‚ú©

To launch php-fpm on startup:
    mkdir -p ~/Library/LaunchAgents
    cp /usr/local/opt/php56/homebrew.mxcl.php56.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php56.plist

The control script is located at /usr/local/opt/php56/sbin/php56-fpm

OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:

  PATH="/usr/local/sbin:$PATH"

You may also need to edit the plist to use the correct "UserName".

Please note that the plist was called 'homebrew-php.josegonzalez.php56.plist' in old versions
of this formula.

With the release of macOS Sierra the Apache module is now not built by default. If you want to build it on your system
you have to install php with the --with-apache option. See  brew options php56  for more details.

To have launchd start homebrew/php/php56 now and restart at login:
  brew services start homebrew/php/php56
```

**Comment by javian** [comment]
@Tenzian that doesn't help though I'm afraid because the problem goes beyond build options. The thing is that we've seen issues that could be traced back to the building of the bottles and to know if that is the cause you need to build php on your device.

If that works I would probably remove ldap from the default configuration and make it optional meaning that if you need it you need to compile it on your own system.

**Comment by javian** [comment]
@Tenzian did you have another look at this ?

**Comment by Tenzian** [comment]
I've rebuilt uising 5.6.27_4 and --build-from-source.

LDAP works fine using PHP CLI but the apache module still has the same failed assertion and abort:

```
Assertion failed: (LDAP_VALID( ld )), function ldap_set_option, file options.c, line 452.
[Mon Oct 17 12:21:06.586622 2016] [core:notice] [pid 48903] AH00052: child pid 50850 exit signal Abort trap (6)
```

So, it looks like the issue is with building libphp5.so --with-apache

in
[01.configure.txt](https://github.com/Homebrew/homebrew-php/files/533301/01.configure.txt)
I can see a warning:

 You have built PHP for Apache's current non-threaded MPM.          
 If you change Apache to use a threaded MPM you must reconfigure    
 PHP with --enable-maintainer-zts 

Does that shed any light?

**Comment by Tenzian** [comment]
Found the problem: It's with the apache install & not PHP's libhp5.so.

The brewed version of openldap needs to be installed `--with-sssvlv` before httpd24 is brew installed `--with-ldap`.

If `brew install httpd24 --with-ldap` does the initial install of openldap as a dependency it misses this out.

**Comment by javian** [comment]
@Tenzian if that's the case we should add it into the dependency code for the respective formulas. Feel free to submit a PR for it.
