### ISSUE TITLE
Cannot use php56 or php55 with system Apache

### ISSUE THREAD

**Issue by brummbar** [Homebrew/homebrew-php#3633]
## Description

I am not able to use anymore php55 and php56 packages with the builtin Apache. I get this error when using `sudo apachectl -k restart`:

> > sudo apachectl -k restart
> httpd: Syntax error on line 174 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0

I am installing the php56 with `--without-ldap --with-apache` for both 5.6 and 5.5.
I'm not using the brewed apache so I am running `brew unlink apache24` afterwards. Same results with `uninstall`.
It does work fine for old builds (I have a 5.6.25_1 installed). When I switch to that, it works ok.
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.10.5 |
| **Homebrew Version:** | Homebrew 1.0.5 |
| **PHP Version in use:** | PHP 5.6.26 |
| **Xcode Version:** | Xcode 7.2.1<br>Build version 7C1002 |

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Output of php -v:**
PHP 5.6.26 (cli) (built: Sep 28 2016 14:53:01)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** https://gist.github.com/anonymous/398c554880e6ec813cad13c79c62f2de

**Comment by atsimerman** [comment]
I have same problem. I run on OS X 10.11.6 El Capitan with pre-installed apache. When i install php56 with brew i have same error. Can you suggest any decisions ?

**Comment by kloneets** [comment]
Same here. Installed php 5.6 and it drew in brew's httpd24. apachectl starts both system and brewed httpd services.
My quick fix fas `brew uninstall httpd24` but it breaks brew upgrade, if php56 needs to be updated.

**Comment by brummbar** [comment]
For me it doesn't work at all with the system apache.
Since I didn't yet upgraded my system (I should, really), I temporarily fixed the issue by commenting out the dependency on apache24 and the code that is defining `apache_apxs`, hardcoding the `/usr/sbin/apxs` path.
By doing this the system apache works fine. The proper approach should be to use the default apxs for older operative systems if brewed apache is not installed.

**Comment by eppfel** [comment]
I think it is still related to the changes discussed in this issue: #3601

**Comment by Kyslik** [comment]
same problem
-- installed `without-ldap`, trying to use built in Apache.

**Comment by niksy** [comment]
Same here, I’ve used `libphp5.so` from older PHP 5.6 build for now.

**Comment by eppfel** [comment]
As I still have this problem, could you share how you got the older version @niksy ?

**Comment by ernani** [comment]
It seems there is no route other than use httpd24 from brew and inactivate the system's Apache.

The dylib from system's apache uses apr util v6 where httpd24's uses v4

dyld: Library not loaded: /usr/local/opt/apr-util/lib/libaprutil-1.0.dylib
Reason: Incompatible library version: httpd requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0

**Comment by niksy** [comment]
@eppfel since that problem was showing to a colleague of mine, I’ve used my older version .so file to get desired behavior.

**Comment by drblue** [comment]
I had the same problem last week when I was trying to get xdebug installed, but after a few hours of struggling I have homebrew/php56 (v5.6.26_3) running with El Capitan apache 2.4. Had to install php56 with the apache option (took a while as it had to compile the so), my `.bash_history` doesn't contain the exact commands but if my memory doesn't fail me I ended up with `brew install homebrew/php56 --with-apache` (at least according to the `INSTALL_RECEIPT.json` for the package).

Also had to edit my `PATH` environment variable and prefix it with "/usr/local/bin" as "/usr/bin" had precedence on my system and it contained the os-x version of PHP.

Here's my `INSTALL_RECEIPT.json` if anyone is interested:

```json
{
  "used_options": [
    "--with-apache"
  ],
  "unused_options": [
    "--with-enchant",
    "--with-gmp",
    "--with-postgresql",
    "--with-apache22",
    "--with-cgi",
    "--with-debug",
    "--with-homebrew-curl",
    "--with-homebrew-libressl",
    "--with-homebrew-libxslt",
    "--with-homebrew-libxml2",
    "--with-imap",
    "--with-libmysql",
    "--with-mssql",
    "--with-pear",
    "--with-pdo-oci",
    "--with-phpdbg",
    "--with-thread-safety",
    "--without-bz2",
    "--without-fpm",
    "--without-ldap",
    "--without-mysql",
    "--without-legacy-mysql",
    "--without-pcntl",
    "--without-unixodbc"
  ],
  "built_as_bottle": false,
  "poured_from_bottle": false,
  "time": 1475503469,
  "source_modified_time": 1473975832,
  "HEAD": "1e1903e4cc0ef928081ebab6b7a8e478de493b2a",
  "stdlib": "libcxx",
  "compiler": "clang",
  "runtime_dependencies": [
    {
      "full_name": "libpng",
      "version": "1.6.25"
    },
    {
      "full_name": "freetype",
      "version": "2.7"
    },
    {
      "full_name": "gettext",
      "version": "0.19.8.1"
    },
    {
      "full_name": "icu4c",
      "version": "57.1"
    },
    {
      "full_name": "jpeg",
      "version": "8d"
    },
    {
      "full_name": "libxml2",
      "version": "2.9.4"
    },
    {
      "full_name": "unixodbc",
      "version": "2.3.4"
    },
    {
      "full_name": "readline",
      "version": "7.0"
    },
    {
      "full_name": "openssl",
      "version": "1.0.2j"
    },
    {
      "full_name": "pcre",
      "version": "8.39"
    },
    {
      "full_name": "homebrew/dupes/zlib",
      "version": "1.2.8"
    },
    {
      "full_name": "apr",
      "version": "1.5.2"
    },
    {
      "full_name": "apr-util",
      "version": "1.5.4"
    },
    {
      "full_name": "homebrew/apache/httpd24",
      "version": "2.4.23"
    }
  ],
  "source": {
    "path": "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php56.rb",
    "tap": "homebrew/php",
    "spec": "stable",
    "versions": {
      "stable": "5.6.26",
      "devel": null,
      "head": "HEAD",
      "version_scheme": 0
    }
  }
}
```

**Comment by biojazzard** [comment]
For me the latest working version in OSX 1.0.9  is php55 5.5.32. Personally I had to switch back.

brew switch php55 5.5.32 

;-(

**Comment by abedzilla** [comment]
I experienced the same issue.

**Comment by ruho** [comment]
I've also got this problem

**Comment by julianstefanov** [comment]
Just run:
xcode-select --install
and then everything will be fine
At least for me, that was the problem. I forgot to install the command tools.

**Comment by saideldah** [comment]
@julianstefanov 
`xcode-select --install`
solve the problem 
thank you

**Comment by bkdotcom** [comment]
@julianstefanov @saideldah 
what do you do after installing/updating xcode?

`Warning: homebrew/php/php56: --with-apache was deprecated; using --with-httpd24 instead!`
`Warning: homebrew/php/php56: this formula has no --with-apache24 option so it will be ignored!`

&hellip;
`apachectl -checkconfig`
`Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server`
