### ISSUE TITLE
Installation not actually successful

### ISSUE THREAD

**Issue by kirkbushell** [Homebrew/homebrew-php#3642]
## Description

After installing php70-mcrypt, it says the following:

To finish installing mcrypt for PHP 7.0:
  * /usr/local/etc/php/7.0/conf.d/ext-mcrypt.ini was created,
    do not forget to remove it upon extension removal.

The problem is, no such file is actually created meaning that mcrypt won't be loaded by PHP.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.0.5
**PHP Version in use:** | 7.0.11
**Xcode Version:**      | 

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 7.0.11 (cli) (built: Sep 26 2016 23:04:48) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
Error: No logs

**Comment by javian** [comment]
Until the fix is merged you can do `brew install -s php70-mcrypt` and compile it on your own machine. The fix will be merged later today.

**Comment by kirkbushell** [comment]
@javian awesome, thanks so much. What exactly is/was the issue?

**Comment by javian** [comment]
@kirkbushell there was a bug in brew that cause the config file for the extension to not be created in the php config directory. The bottle had to be regenerated which took a little while but since the big was fixed in code you did no longer see the issue if you installed it from source.
