### ISSUE TITLE
Error updating php56 on macOS Sierra

### ISSUE THREAD

**Issue by rafaga** [Homebrew/homebrew-php#3655]
## Description

When i execute `brew upgrade` over a php56 instalation on macOS Sierra, the setup throws a exception

## Context and Logs

```
Last 15 lines from /Users/Rafael/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz
```

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12
**Homebrew Version:**   | 1.0.5
**PHP Version in use:** | 5.6.25
**Xcode Version:**      | Xcode 8.0 Build version 8A218a

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.6.25 (cli) (built: Aug 24 2016 11:55:33) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** 
https://gist.github.com/a10a5ab4069cc28570e97a5d22decbbb

**Comment by demon** [comment]
Exact same problem with me and php70

**Comment by malte-schlueter** [comment]
I tried to reinstall php but i get the same exception.

**Comment by demon** [comment]
Ah, duh, I figured it out. Forgot to update the xcode command line tools after OS upgrade.

`sudo xcode-select --install`

**Comment by rafaga** [comment]
Lol, that works ...

**Comment by oliver507** [comment]
Awesome dude !
