### ISSUE TITLE
postgresql 9.6 revisions needed

### ISSUE THREAD

**Issue by JLHwung** [Homebrew/homebrew-php#3656]
revisions needed after [postgresql 9.6](https://github.com/Homebrew/homebrew-core/pull/5381) is merged.
- [ ] php54-pdo-pgsql
- [ ] php55-pdo-pgsql
- [ ] php56-pdo-pgsql
- [x] php70-pdo-pgsql
- [x] php71-pdo-pgsql

**Comment by javian** [comment]
The postgres merge is awaiting Formula dependency updates before it can be merged.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
