### ISSUE TITLE
Missed bottles for Sierra

### ISSUE THREAD

**Issue by pinepain** [Homebrew/homebrew-php#3665]
I see many formulas has no bottle for Sierra. Is it intended or it just hasn't been done yet and could be easily achieved by touching formula or incrementing it revision id?

**Comment by javian** [comment]
It hasn't been done yet. There is a way to do it without bumping the revision but I have not time to look at it yet but you need special permissions in the brew-bot to make it work.

**Comment by pinepain** [comment]
I'm curious what is the supposed way to handle this without bumping revision? While I'm not in hurry and totally fine with building formulas locally, is there anything I can help with?

**Comment by javian** [comment]
Could you highlight the most popluar packages and we can start with those ?

**Comment by pinepain** [comment]
All formulas which has been updated before sierra target was added to BrewTestBot needs to be regenerated. I'm not sure where to look when that change was performed, but apparently we can regenerate all bottles which has not been updated within past 1 week or 10 days. Or I can bump all formulas which has not sierra target, which looks like a more cleaner approach (though, not sure how to PR all that changes as I remember that CI doesn't handle well mass formula changes).

**Comment by javian** [comment]
Yeah, I did `grep -L ':sierra' *` to list them so I'll start going through them.

**Comment by pinepain** [comment]
Thank you very much!

**Comment by javian** [comment]
Its over 550 Formulas so its going to take a while.

**Comment by pinepain** [comment]
Closing is it should be probably fixed directly or indirectly.
