### ISSUE TITLE
php56-mcrypt bottle 404's

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-php#3670]
## Description

`php56-mcrypt`''s bottle URL currently returns a 404. The problem appears to be that `php56` is currently at 5.6.26, but the latest available bottle version for `php56-mcrypt` is 5.6.25 (see https://bintray.com/homebrew/bottles-php/php56-mcrypt).

The URL is https://homebrew.bintray.com/bottles-php/php56-mcrypt-5.6.26.el_capitan.bottle.13.tar.gz

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       El Capitan
**Homebrew Version:**   | 1.0.5
**PHP Version in use:** | 5.6.26
**Xcode Version:**      |  I only use the command-line tools

**Comment by javian** [comment]
Thanks for the report! I submitted it as #3671 but next time you can bump the revision and submit a PR to shorten the response time. Thanks!

**Comment by javian** [comment]
Merged.
