### ISSUE TITLE
 ..

### ISSUE THREAD

**Issue by bookishgirl** [Homebrew/homebrew-php#3673]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _your OS X version_
**Homebrew Version:**   | _your Homebrew version_
**PHP Version in use:** | _your PHP version_
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
_result of the CLI output_

**Output of php -v:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by josegonzalez** [comment]
@bookishgirl Did you forget to fill out the issue?

**Comment by bookishgirl** [comment]
I didn't mean to open an issue as I'm having an issue that I already see mentioned here (missing libexec directory). Sorry about that!
