### ISSUE TITLE
Error while installing php54

### ISSUE THREAD

**Issue by aagasi** [Homebrew/homebrew-php#3676]
## Description

Environment: macOS **Sierra** 10.12

The thing is that i need to install (brew install) **php54**.
While installing, suddenly an error uccur: 

Sorry, I cannot run apxs.  Possible reasons follow:

1. Perl is not installed
2. apxs was not found. Try to pass the path using --with-apxs2=/path/to/apxs
3. Apache was not built using --enable-so (the apxs usage page is displayed)

The output of /usr/sbin/apxs follows:
apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.

configure: error: Aborting

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages. 

So i googled a bit but didn't find any clue on what's happening rather than "macOS Sierra fault".

So, one more time i'm having trouble with macOS upgrades. It's a pain to deal with this major upgrades.

Need some workaround here please. Thanks!

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _your OS X version_
**Homebrew Version:**   | _your Homebrew version_
**PHP Version in use:** | _your PHP version_
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
_result of the CLI output_

**Output of php -v:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
@aagasi you need to provide more information about your system since you don't leave much to understand your brew environment. Looking at the error "Warning: You are using OS X 10.12." you seem to be using an old version of brew - could you be affected by the *update bug* that outlined on the brew page https://github.com/Homebrew/brew ?

**Comment by aagasi** [comment]
Thanks @javian, just made brew update & upgrade and now it works.
