### ISSUE TITLE
Problem installing php71-intl

### ISSUE THREAD

**Issue by jkrehm** [Homebrew/homebrew-php#3677]
## Description

Binary file download fails. https://homebrew.bintray.com/bottles-php/php71-intl-7.1.0-rc.3_3.el_capitan.bottle.tar.gz cannot be found.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.0.6 (git revision 5b5171; last commit 2016-10-06)
**PHP Version in use:** | 7.1.0RC3
**Xcode Version:**      | 8.0 (8A218a)

**Comment by javian** [comment]
This should be resolved now after I updated the bottles.
