### ISSUE TITLE
Not include 'usr/local/Cellar/php71/libexec/apache2/libphp7.so

### ISSUE THREAD

**Issue by JuanLuisGarciaBorrego** [Homebrew/homebrew-php#3678]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.0.6
**PHP Version in use:** | PHP 7.1.0RC3 (cli)
**Xcode Version:**      |  8.0
**Output of gcc -v:**

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**

PHP 7.1.0RC3 (cli) (built: Oct  2 2016 01:09:07) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
Error: No logs

I installed php 71 but, does not include 'usr/local/Cellar/php71/libexec/apache2/libphp7.so' 
Can you help me?
Thanks!

**Comment by cristinallamas** [comment]
same here, any solutions?

**Comment by SMillerDev** [comment]
Did you install using `--with-httpd` to add apache support?
