### ISSUE TITLE
how to use mac apache with php56

### ISSUE THREAD

**Issue by y284663247** [Homebrew/homebrew-php#3688]
## Description

how to use mac apache with php56 not brew http24
_Problem description goes here_
i user "brew install php56" but don't have libphp5.so file,so i use "brew install php56 --with-apache",but brew install http24 in my mac,i don't want it ,i only want to use mac apache,how can i do it??
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | macos Sierra |
| **Homebrew Version:** | Homebrew 1.0.6 |
| **PHP Version in use:** | php56 |
| **Xcode Version:** | 8.0 |

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.6.26 (cli) (built: Sep 30 2016 21:05:58)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

**Comment by JuanLuisGarciaBorrego** [comment]
I have the same problem

**Comment by javian** [comment]
You can not install php on macOS sierra since Apple has removed the tools necessary to do so. Therefore we need to install the httpd package to make the apache module compile and as far as I know this compiled version is not compatible with the system apache.

**Comment by y284663247** [comment]
have can I stop Mac self apache on start,i can use homebrew apache,but restart computer,mac apache is also start

**Comment by justinlevi** [comment]
I believe Sierra now comes with php5.6 so for me I just had to remove this from my `/etc/apache2/httpd.conf`

`LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so`

Then restart apache with 

```
$ sudo apachectl stop
$ sudo apachectl start
```

**Comment by javian** [comment]
@y284663247 you can find that info on this page http://osxdaily.com/2015/08/30/automatically-start-apache-mac-os-x-boot/ and a lot of other websites.

**Comment by darronz** [comment]
Try unlink homebrew apache `brew unlink httpd24`. Then add `LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so` to `/etc/apache2/apache.conf` and comment out `LoadModule php5_module libexec/apache2/libphp5.so`. After a restart you should be able to use `sudo apachectl start|stop` from the terminal. As @javian pointed out you can control the startup behaviour using `launchctl`. I've got php70 running like this without any issues (so far)

**Comment by javian** [comment]
@darronz so you can compile with the brewed httpd24 and use it with the system apache ?

**Comment by darronz** [comment]
@javian getting it set up initially was a bit of a headache which is why I edited my previous comment with the note about 3283. To update php I have to relink httpd24 then unlink it again, but yes I am running it with the system apache.
