### ISSUE TITLE
Build fails when using --with-postgresql

### ISSUE THREAD

**Issue by aberenyi** [Homebrew/homebrew-php#3690]
## Description

I've tried to build multiple versions (`php56`, `php70`, `php71`) with `--with-postgresql`, unfortunately every single one of them failed with
```
dtrace: failed to compile script /private/tmp/php70-20161011-<randomStuff>/php-<version>/Zend/zend_dtrace.d: Preprocessor not found
```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.0.7
**PHP Version in use:** | 5.5.36
**Xcode Version:**      | 8.0 (8A218a)

**Output of gcc -v:**
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/6.2.0/libexec/gcc/x86_64-apple-darwin15.6.0/6.2.0/lto-wrapper
Target: x86_64-apple-darwin15.6.0
Configured with: ../configure --build=x86_64-apple-darwin15.6.0 --prefix=/usr/local/Cellar/gcc/6.2.0 --libdir=/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-6 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 6.2.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 6.2.0 (Homebrew gcc 6.2.0)
```

**Output of php -v:**
```
PHP 5.5.36 (cli) (built: May 29 2016 01:07:06)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Build logs:** 
[Here](https://gist.github.com/anonymous/37c7b2deeddbc4320c5abfc8e16a541e)

**Comment by aberenyi** [comment]
**UPDATE** I've just updated to Sierra and it compiles just fine.

I'll leave this open in case someone else is facing this.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12
**Homebrew Version:**   | 1.0.7
**PHP Version in use:** | 5.6.24 / 7.0.11
**Xcode Version:**      | N/A

**Output of gcc -v:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of php -v:**
_before_
```
PHP 5.6.24 (cli) (built: Aug  8 2016 16:58:37)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
_after_
```
PHP 7.0.11 (cli) (built: Oct 11 2016 07:01:45) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by javian** [comment]
I'm not sure what could be the problem here. In your first post it seems to detect postgres just fine
```
+checking for PostgreSQL support for PDO... yes
+checking for pg_config... /usr/local/opt/postgresql/bin/pg_config
```
It might be that this is a leftover that was supposed to be removed since the code has moved into a seperate module called php70-pdo-pgsql

**Comment by javian** [comment]
It seems that there are several people that have had your issue previously that you mentioned at the top but I could not find a solution for it.

**Comment by aberenyi** [comment]
@javian I had the same thought, so I've also tried to uninstall PostgreSQL with all its deps, reinstall it and give php7 another try. Same result. Quite weird.

**Comment by javian** [comment]
Could this explain it ? http://stackoverflow.com/questions/23918889/trying-to-install-ruby-2-1-2-with-rbenv-on-osx-build-failed

**Comment by javian** [comment]
Since the issues is resolved I'm going to close the issue.
