### ISSUE TITLE
homebrew php70 linking error... directory not empty

### ISSUE THREAD

**Issue by diwao11** [Homebrew/homebrew-php#3703]
## Description
When I try to switch to php70, I get this...
_Problem description goes here_
Linking /usr/local/Cellar/php70/7.0.11_5... Error: Directory not empty - /usr/local/opt/php70
## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12
**Homebrew Version:**   | 1.0.7-44-gbad1483
**PHP Version in use:** | 7
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
_result of the CLI output_

**Output of php -v:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
Can you check what's in the /usr/local/opt/php70 directory ?

**Comment by diwao11** [comment]
Hi javian, there is a /var directory which includes an /log directory which has a php-fpm.log file.

**Comment by javian** [comment]
If that file is not important to you then delete or try to `brew link --force` and see if that works.

**Comment by diwao11** [comment]
Thank you. All fixed. I deleted the entire folder, not sure why php70 came as a directory and then re-installed through brew. Thanks!
