### ISSUE TITLE
mcrypt extension requires libtool

### ISSUE THREAD

**Issue by shadowhand** [Homebrew/homebrew-php#3711]
## Description

When installing `php71-mcrypt` from a fresh installation, the following error will be presented:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php71-mcrypt/mcrypt.so, 9): Library not loaded: /usr/local/opt/libtool/lib/libltdl
.7.dylib
  Referenced from: /usr/local/opt/php71-mcrypt/mcrypt.so
  Reason: image not found in Unknown on line 0
```

The error goes away after installing libtool with `brew install libtool`.
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.12 (16A323) |
| **Homebrew Version:** | 1.0.7 |
| **PHP Version in use:** | PHP 7.1.0RC3 |
| **Xcode Version:** | 8.0 (8A218a) |

**Output of gcc -v:**

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**

```
PHP 7.1.0RC3 (cli) (built: Oct  2 2016 01:05:16) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
```

**Build logs:** 

_None available, installed using bottle._

**Comment by javian** [comment]
Is there someone else that can verify this behaviour ?

**Comment by javian** [comment]
I can reproduce this on my system. It also seems to happen for php70-imagick and there might be others.

**Comment by enderandpeter** [comment]
Yes! This very same thing happened to me after installing homebrew's php71-mcrypt on MacOS Sierra. `brew install libtool` fixed it for me, too. Glad I didn't have to search too far and wide.

**Comment by parkertr** [comment]
This just happened to me yesterday with php70

```
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php70-mcrypt/mcrypt.so, 9): Library not loaded: /usr/local/opt/libtool/lib/libltdl.7.dylib
  Referenced from: /usr/local/opt/php70-mcrypt/mcrypt.so
  Reason: image not found in Unknown on line 0
```

`brew install libtool` also fixed it.

Specs:
> Homebrew 1.1.9
> Homebrew/homebrew-core (git revision 58b8; last commit 2017-01-30)
> macOS Sierra 10.12.3
>
