### ISSUE TITLE
Ioncube for php 7

### ISSUE THREAD

**Issue by marcvdm** [Homebrew/homebrew-php#3713]
The Ioncube loaders for php7 where released on 26th september, could they be added here so we can use php7 with ioncube?

**Comment by javian** [comment]
Can you submit a PR for it and I will gladly merge it ?

**Comment by Zifius** [comment]
PR #3719 submitted

**Comment by javian** [comment]
This has now been merged.

**Comment by marcvdm** [comment]
Awesome. Many thanks @Zifius and @javian
