### ISSUE TITLE
where is libphp5.so on latest php56?

### ISSUE THREAD

**Issue by waltercruz** [Homebrew/homebrew-php#3714]
## Description

Upgraded my php56, but now, there's no apache module. Something changed?
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.11.6 |
| **Homebrew Version:** | 1.0.8 |
| **PHP Version in use:** | 5.6 |
| **Xcode Version:** | _your Xcode version_ |

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 5.6.27 (cli) (built: Oct 15 2016 09:29:55)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by hoshi-takanori** [comment]
I installed httpd22 and php56 --with-apache22. libphp5.so is at /usr/local/Cellar/httpd22/2.2.31/libexec/libphp5.so (/usr/local/opt/httpd22/libexec/libphp5.so).
 It this a correct behavior?

**Comment by niksy** [comment]
This is related to https://github.com/Homebrew/homebrew-php/issues/3633

**Comment by javian** [comment]
@waltercruz yes, the apache module is no longer built by default so you need to use the new command line options (see `brew options php56`) to make it work.

**Comment by niksy** [comment]
@javian so basically PHP should be installed with `brew install php56 --with-apache24`? Wouldn’t that install Homebrew Apache which is not compatible with system Apache (as seen here https://github.com/Homebrew/homebrew-php/issues/3688#issuecomment-253414766)?

**Comment by javian** [comment]
@niksy It is compatible it just doesn't work out of the box like the system apache does. In what way would you see its not compatible ?

**Comment by niksy** [comment]
@javian correction: I meant that .so file which is created is not compatible with system Apache. Am I right?

**Comment by javian** [comment]
@niksy yes

**Comment by javian** [comment]
@niksy actually, some people in here are compiling it and using it with the macOS apache but I've not tested it. Maybe you can try and see if it works for you.

**Comment by niksy** [comment]
@javian I could try, yes. But what I'm interested in is what actually changed between version so we don't get compiled .so from the start? Is it something Sierra related? Can the default behavior be returned with something like flag `--with-system-apache`?

**Comment by javian** [comment]
@niksy For sierra that is not possible unless you make manual changes to your own system (this is due to changes by Apple). For older versions of macOS it could be returned to how it worked previously.

**Comment by niksy** [comment]
@javian Is this too much work? Can we somehow help in making that possible?

**Comment by isrd1** [comment]
I've just upgraded to Sierra and have reinstalled php56 --with-apache but can't find libphp5.so, I've using 'find' with no luck.  There is no /usr/local/opt/php56/libexec directory, nor is it found, as suggested above, in /usr/local/Cellar/httpd24/VERSION/libexec/ there are only mod_ files in there no libs.  Any ideas?

**Comment by concept47** [comment]
can someone shed light on why this decision was made?

This breaks lots of, hitherto, stable OSX setups and I'd like to think there was a good reason for it?

**Comment by concept47** [comment]
@isrd1 try running `mdfind libphp5.so`
what do you get?

**Comment by javian** [comment]
@isrd1 any comments about the apache install should go into the apache repo, its seperate from the PHP one.

@concept47 what decision are you referring to ? If its' about requiring brewed apache then Apple has removed the tools to be able to compile it. It is possible to work around it if you search in the issues but I've not wanted to implement that in brew since it modifies stuff outside of the homebrew realm. It could potentially be put it with a manual on what to do to make it work.

**Comment by isrd1** [comment]
There was no libphp5.so, I'd searched before posting in case I could just change the path in the apache.conf file, but it wasn't there, nor any libexec directory.  In the end I uninstalled everything and reinstalled it all, installing php with the --with-apache option (which I had done before) and this second time it worked.

**Comment by niksy** [comment]
@javian So as I see it, these are the options:

* For Sierra (and later), install with only brewed Apache
* For everything else, provide option for previous version where you coudl do install with system Apache

Am I right?

**Comment by concept47** [comment]
@javian okay cool. I figured there was a good reason. Thanks.

**Comment by concept47** [comment]
@niksy you can already see the added complexity with that approach. And eventually users would have to use the brewed Apache anyway. I think the communication could be better but this is a sound approach. 

Maybe add a warning or notice in the install @javian?

Thanks for all the hard work regardless.

**Comment by javian** [comment]
@niksy See for example https://github.com/Homebrew/homebrew-php/issues/3283#issuecomment-228582197 - the workaround also works for Sierra.

**Comment by josegonzalez** [comment]
@niksy pull requests welcome :)

**Comment by ptica** [comment]
I've stayed away from sierra specifically for not falling into problems like this,
but brew did an upgrade of php56 and here I am, configuring php once again

-- version 5.6.30_6 has broken existing setup with system apache on el capitan

if you have client work to do, just point your system apache to old module located by
```
mdfind libphp5.so
sudo vim /private/etc/apache2/httpd.conf
# in my case I've used
/usr/local/Cellar/php56/5.6.24/libexec/apache2/libphp5.so
```
and properly resolve the issue later

**Comment by YvesLeBorg** [comment]
@ptica yep ... exactly my approach on this. Too many moving targets, stayed with El Capital till i deploy current project and can afford some down time.

**Comment by bytehead** [comment]
`brew reinstall php56 --with-httpd24` solves the problem as there is a `libphp5.so` in `/usr/local/Cellar/php56/5.6.31_7/libexec/apache2` after the install.
