### ISSUE TITLE
PHP 7.1 RC5

### ISSUE THREAD

**Issue by bradynpoulsen** [Homebrew/homebrew-php#3733]
## Description

Importing issue from homebrew/brew#1378

Release Candidate 5 is set to be public on the 27th. We have not yet updated to RC4, and I feel it would be pointless to update to it to be out of date in 36 hours.

This issue is for tracking purposes and I am working on a PR right now

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | macOS 10.12
**Homebrew Version:**   | 1.0.8-133-g84d1661
**PHP Version in use:** | PHP 7.1 RC3

**Comment by javian** [comment]
I agree, lets deploy the latest version which I will merge shortly.
