### ISSUE TITLE
Can not install old formulae

### ISSUE THREAD

**Issue by GinoPane** [Homebrew/homebrew-php#3734]
Hello!
Is there any way to install PHP 7.0.2? 
Can not find it anywhere. Tried to use homebrew/boneyard, homebrew/versions with no luck.

**Comment by javian** [comment]
Not easily. We don't keep the version numbers in the code so if its updated then that information only lies in the git history so it might be possible to dig it up from there. The easiest way might be to create your own formula based on the php70.rb and add the version manually to it replacing the variables currently used in the Formula.

**Comment by GinoPane** [comment]
So, if I understand correctly, I can, for example, fork the repo, update php70.rb and then do something like that:

```
$ brew tap github-username/extended-homebrew-php
$ brew install php70
```

I this somehow correct?

**Comment by javian** [comment]
That's one way of doing it but its probably easier to copy the php70.rb file to php702.rb in your Formula directory and make the appropriate changes to it then you can choose if you want to have the latest 7 version installed as well and don't have to mess with another repo.

**Comment by GinoPane** [comment]
Yes, it was the most straightforward solution.
Thank you, I'll try it out.

**Comment by GinoPane** [comment]
It worked, thanks.
