### ISSUE TITLE
Can't compile php70 using '--with-apache'; unrecognized options: --with-mysql

### ISSUE THREAD

**Issue by jameslbrown** [Homebrew/homebrew-php#3736]
## Description

Need libphp70.so so Apache 2.4 can use PHP, but when I try to install PHP70 using '--with-apache' option I get:

```
brew reinstall php70 --with-apache
==> Reinstalling homebrew/php/php70 with --with-apache
==> Downloading https://php.net/get/php-7.0.12.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-7.0.12.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.12_5 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/etc/php
Last 15 lines from /Users/jlbrown/Library/Logs/Homebrew/php70/01.configure:
--enable-dtrace
--disable-phpdbg
--enable-zend-signals

configure: WARNING: unrecognized options: --with-mysql
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... (cached) sed
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
checking whether the C compiler works... no
configure: error: in `/private/tmp/php70-20161026-32731-ojny4g/php-7.0.12':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.11.6 |
| **Homebrew Version:** | 1.0.8 |
| **PHP Version in use:** | 7.0.12 |
| **Xcode Version:** | 8.0 (8A218a) |

**Output of gcc -v:**
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
_result of the CLI output_

**Build logs:** https://gist.github.com/ef36fb2b2e2520fc659c75e402233931

**Comment by javian** [comment]
@jameslbrown would the "fix" in this issue help you https://github.com/Homebrew/legacy-homebrew/issues/44405 ? Same error so its a wild guess.

**Comment by jameslbrown** [comment]
Thanks javin, but that was not the issue - Xcode CLI Tools were installed.

This is the problem:

unrecognized options: --with-mysql

This is not a valid configure option with PHP 7.x

I found out what the configure command it was using was, then ran it manually after deleting that option. Ie I used:

`./configure --prefix=/usr/local/Cellar/php71/7.1.0-rc.5_9 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --with-config-file-path=/usr/local/etc/php/7.1 --with-config-file-scan-dir=/usr/local/etc/php/7.1/conf.d --mandir=/usr/local/Cellar/php71/7.1.0-rc.5_9/share/man --enable-bcmath --enable-calendar --enable-dba --enable-exif --enable-ftp --enable-gd-native-ttf --enable-mbregex --enable-mbstring --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip --with-freetype-dir=/usr/local/opt/freetype --with-gd --with-gettext=/usr/local/opt/gettext --with-iconv-dir=/usr --with-icu-dir=/usr/local/opt/icu4c --with-jpeg-dir=/usr/local/opt/jpeg --with-kerberos=/usr --with-libedit --with-mhash --with-ndbm=/usr --with-png-dir=/usr/local/opt/libpng --with-xmlrpc --with-zlib=/usr --with-readline=/usr/local/opt/readline --without-gmp --without-snmp --with-libxml-dir=/usr/local/opt/libxml2 --with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc --with-unixODBC=/usr/local/opt/unixodbc --with-apxs2=/usr/local/bin/apxs --libexecdir=/usr/local/Cellar/php71/7.1.0-rc.5_9/libexec --with-bz2=/usr --with-openssl=/usr/local/opt/openssl --enable-fpm --with-fpm-user=_www --with-fpm-group=_www --with-curl --with-xsl=/usr --with-ldap --with-ldap-sasl=/usr --with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --disable-opcache --enable-pcntl --without-pear --enable-dtrace --disable-phpdbg --enable-zend-signals`

then
```
make
make test
sudo make install
```
which worked.

James.

**Comment by javian** [comment]
It sounds unlikely that the additional option is related to me. Did you try and add it again after you compiled successfully to confirm this ?

**Comment by FGM** [comment]
FWIW, same `--with-mysql` error when installing with the `--with-pear` option (without the `--with-apache`).

**Comment by javian** [comment]
@FGM do you mean the warning ? The error above is that the C compiler can not create executeables - are you seeing that too ?

**Comment by henrypenny** [comment]
I have been trying for days to install php7.0 with apache support. @jameslbrown 's approach was the only way that worked for me.

@javian Yes it looked to me like the C complier can't create the executables.

**Comment by javian** [comment]
@henrypenny did you try to run `xcode-select --install` to see if that would have fixed the problem ?

**Comment by henrypenny** [comment]
@javian 
I already had xcode 8.0 installed so I get:

```

hpenny$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

```

I've had a lot of trouble getting 8.1 to update and I'm on limited data right now, so I can't afford to continue to download 4.6 GB and have it fail at 99% over and over :) So - I'm not sure I can answer that right now.

I think it's the --with-mysql option that's causing the problem. But I don't know much about the inner workings of homebrew and I'm not usually a do-my-own-php-compile guy either...

I hope that's some help at least.

**Comment by xiaofuyesnew** [comment]
I have had xcode 8.1 already
then after running 
```
xcode-select --install
```
and then
```
brew install php70 --with-apache
```
worked.

It happened just last night.

**Comment by madouidesign** [comment]
`brew install php70 --with-apache24`

Have fixed the problem

**Comment by henrypenny** [comment]
Awesome. Thanks @madouidesign

**Comment by madouidesign** [comment]
You're welcome @henrypenny

**Comment by cschorr** [comment]
@madouidesign: the correct option name seams to be --with-httpd24
`brew install php70 --with-httpd24`

but it doesn't compile anyway for me #3846

**Comment by javian** [comment]
@cschorr it changed recently so any old info will be incorrect.

**Comment by madouidesign** [comment]
Hi @cschorr

1 - uninstall xcode 8 with [AppCleaner](https://freemacsoft.net/appcleaner/)
2 - install last version [xcode 8.2](https://itunes.apple.com/us/app/xcode/id497799835?ls=1&mt=12) to fix **C compilation error**
3 - install or reinstall php70

brew install php70 --with-httpd24  
or 
brew reinstall php70 --with-httpd24 if it's already installed

4 - Now  your php module is in  /usr/local/opt/php70/libexec/apache2/libphp7.so

5 - Add this line in your httpd.conf
LoadModule php7_module    /usr/local/opt/php70/libexec/apache2/libphp7.so

And it's done

**Comment by cordominic** [comment]
On MacOS Sierra 10.12.2, if you are using the --with-httpd24 option, but for some reason still getting the Compiling error: Can't compile php70 using '--with-apache'; unrecognized options.

Try again with more options:
brew reinstall php70 --with-httpd24 --with-mysql

**Comment by scottgutman** [comment]
Hi! Have you run:

`xcode-select --install`

it should remedy the problem. See #1946 .

See: https://github.com/Homebrew/homebrew-php/issues/2929
