### ISSUE TITLE
php56-mongodb _clock_gettime error at runtime

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-php#3737]
_From @ABXAdmin on October 24, 2016 20:51_

If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

---

**The error:** 

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php56-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php56-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

I followed the troubleshooting instructions, uninstalled and reinstalled php56 and php56-mongodb and am still getting this error. I know this is related to many other tickets, but the methods shown in the other tickets to fix the issue didn't help.

I've got xcode v8 installed with the v7.3x CLT.

I am unsure as to the brew doctor results. I get many warnings, but they appear to be due to having installed quite a bit outside of homebrew. Everything seems to work correctly except for the php56-mongodb driver. The legacy php56-mongo driver continues to work. I do have unbrewed dylibs but am unsure if one, or many of them may be causing an issue here:

```
Unexpected delis:

  /usr/local/lib/dccmtr.dylib
  /usr/local/lib/libCalibrationHandler.dylib
  /usr/local/lib/libCIEHandler.dylib
  /usr/local/lib/libCompression.dylib
  /usr/local/lib/libcurl.4.dylib
  /usr/local/lib/libDeviceManager.dylib
  /usr/local/lib/libErrorHandler.dylib
  /usr/local/lib/libICMManager.dylib
  /usr/local/lib/libMCCAppManager.dylib
  /usr/local/lib/libMCCEngineWrapper.dylib
  /usr/local/lib/libmcrypt.4.4.8.dylib
  /usr/local/lib/libMonitorDDCCISDK.dylib
  /usr/local/lib/libProtocolEngine.dylib
  /usr/local/lib/libQM2Lib.dylib
  /usr/local/lib/libssh2.1.dylib
  /usr/local/lib/Spyder.dylib
  /usr/local/lib/Spyder3.dylib
```

_Copied from original issue: Homebrew/homebrew-core#6236_

**Comment by javian** [comment]
@ABXAdmin which OS are you on ? El Cap ?
Are you installing from bottle or compiling from source ?

**Comment by ABXAdmin** [comment]
El Cap

Installing via: 
```
brew install php56 —with-apache
brew install php56-mongodb
```

**Comment by ABXAdmin** [comment]
El Cap

Installing via: 
brew install php56 —with-apache
brew install php56-mongodb

**Comment by javian** [comment]
@ABXAdmin I've been reading about a similar error in https://github.com/mobile-shell/mosh/issues/807 which seems to be the root cause of this issue.

Have you tried to reinstall from source on your machine ?
Have you tried to rerun `xcode-select --install` and then try to install the bottle again ?
If that doesn't work, try once more to install mongodb from source

**Comment by ABXAdmin** [comment]
@javian 

got busy for a little while...

I did run `xcode-select --install`, but got the message that everyone else reports that 

> command line tools are already installed, use Software Update to install updates.

I took a look at the external issue and it appears to be an environment issue there. 

I'm hoping not to have to install from source as I'm trying to keep several php environments in brew and to switch back and forth. FYI, the php70-mongodb driver has the same issue. I'd like to have to keep from messing with the apache configs for each environment as I can get by with the legacy driver for a while.

**Comment by javian** [comment]
@ABXAdmin It seems that clock_gettime has seen several issues since the introduction of XCode 8, as an example you can look at this formula - https://github.com/Homebrew/homebrew-core/pull/6118 and there's plenty more to find in the homebrew-core repo. Not sure what to do about it at this stage though.

**Comment by cdekok** [comment]
I am getting the same error on PHP 7 with mongo.

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dyli
```

**Comment by javian** [comment]
@cdekok @ABXAdmin I would still ask you to test `brew reinstall -s php70-mongodb` if you are using 7.0 just to see if its a build problem with the bottles.

**Comment by cdekok** [comment]
@javian Still the same error, i have tried uninstall / install / doctor also but nothing seemed to work.

**Comment by javian** [comment]
@cdekok thanks for checking. It needs to be raised with the mongodb maintainers since it needs to be updated in the source as far as I can tell - can one of you open a ticket in the php mongodb repo?

**Comment by javian** [comment]
Have any of you tried the devel version ?

**Comment by cdekok** [comment]
@javian how can i install the devel version? I tried to install it with pecl itself but get a few errors on openssl. (openssl is installed with brew)

**Comment by javian** [comment]
@cdekok use  `brew install --devel formulaname`  or  `brew install --head formulaname`

**Comment by cdekok** [comment]
thx it didn't work either, I have added a bug report on the mongo tracker: https://jira.mongodb.org/browse/PHPC-836

**Comment by javian** [comment]
@cdekok after you install from source - can you run `brew gist-logs php56-mongodb` and share the logs ?

**Comment by javian** [comment]
@cdekok another thing to test would be to install  php56 from source first  `brew reinstall -s php56` and then try to install mongodb from source again.

**Comment by javian** [comment]
@cdekok can you also do `otool -L /usr/local/opt/php56-mongodb/mongodb.so`

**Comment by cdekok** [comment]
@javian here is the log: https://gist.github.com/cdekok/4ede3d063678eb35a8d7af687f0ab467

Reinstalled PHP 7 and Mongo didn't work.
Here is the output from otool:

```
▶ otool -L /usr/local/opt/php70-mongodb/mongodb.so
/usr/local/opt/php70-mongodb/mongodb.so:
	/usr/lib/libsasl2.2.dylib (compatibility version 3.0.0, current version 3.15.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
According to feedback from Mongo it should work without brew: https://jira.mongodb.org/browse/PHPC-836

**Comment by javian** [comment]
@cdekok I saw that feedback as well - the problem here is that it seems that it doesn't happen on all machines. Just to verify, you see the error if you for example list the modules with `php -m` do you not ?

**Comment by cdekok** [comment]
The error will only show when executing a query:
```
$query = new MongoDB\Driver\Query($filter, $options);
$cursor = $manager->executeQuery('db.something', $query); // triggers the error
```

**Comment by javian** [comment]
@cdekok can you post that in the jira ticket ? It seems that the test he made only listed the module so it is not clear if he tried to execute a query on a db.

**Comment by javian** [comment]
@cdekok in the Jira ticket you reported that you were using Sierra but according to your gist you are on El Capitan - is that correct ?

**Comment by cdekok** [comment]
@javian yes that is correct I just noticed it the update was not installed correctly, I will try to run it again tonight see if it changes anything.

**Comment by guiassemany** [comment]
I am with the same problem. Using El Cap.
Any news on this?

**Comment by javian** [comment]
@guiassemany no, there's currently no published solution if you want to stick with El Cap.

**Comment by why973828939** [comment]
Same problem here, on 10.11.6. `Xcode-select --version` shows 2343.

```
Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php56-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib
```

Really frustrated...

**Comment by josegonzalez** [comment]
@why973828939 Yep, sucks when free software doesn't work as desired.

We'll definitely keep everyone posted here in terms of any possible solutions. At the moment, it seems like the latest version of XCode updated some libraries/headers that are missing a symbol needed for the mongodb extension to work.

I'm pretty sure the mongodb php extension maintainers are hard at work on a fix, but if anyone here has any information on how we might be able to fix it, please do contribute it. Being negative doesn't really help anyone, and mostly just demoralizes the maintainers and makes it less likely that we'll contribute.

@javian could we try the hack mentioned in [this comment](https://github.com/Homebrew/homebrew-core/issues/2674#issuecomment-250896730) regarding `std_cmake_args`? I'll admit I have no idea what that means, but if someone wants to investigate, it's worth a shot.

**Comment by guiassemany** [comment]
@javian If I change to Sierra and xcode 8,  would it be fixed? Or the solution is using another OS like Windows or Ubuntu? Thank you!

**Comment by cdekok** [comment]
Ok so i finally updated to Sierra and compiled it again the error seems to be gone now 👍 
Atleast on 1.2.0alpha3

**Comment by javian** [comment]
@cdekok would it be possible for you to also test the non-alpha version ?

**Comment by cdekok** [comment]
@javian I have just tried it, it seems to work fine now.

**Comment by Suhkha** [comment]
Same problem with Capitan... :(
any solution??
Thanks a lot!!

**Comment by guiassemany** [comment]
@Suhkha The solution for me was to update to Sierra with xCode 8.1 and use latest mongodb extension. I needed to keep working on it, so I decided to do it.

**Comment by Suhkha** [comment]
@guiassemany thanks! The problem is... I can't for now do that update...it's not up to me to make the change. :(
Thanks.

**Comment by dmaciej** [comment]
I run El Captain too, but I updated XCode Command Line Tools to the version 2343 (`xcode-select --version`):
```
softwareupdate --install -a
```
(it installs all software updates)
and next I installed the extension with the `--build-from-source` flag:
```
brew install --build-from-source php70-mongodb
```
the issue seems to be gone now.

**Comment by jgrossi** [comment]
@dmaciej It worked for me as well, same env, but I'm using php 5.6! Really thanks!

**Comment by javian** [comment]
@dmaciej @jgrossi I've regenereated the bottles so they should be built with the latest setup - can you confirm that the bottles now work without having to install from source ?

**Comment by javian** [comment]
According to https://github.com/Homebrew/homebrew-php/pull/3890#issuecomment-271078815 this has not been resolved.

**Comment by lenyapugachev** [comment]
@javian is there some workaround for now? Already a week of deploying to server for test, instead of local, wasting time :(

**Comment by jgrossi** [comment]
@javian thanks for the effort, but it's not working yet, just with `-build-from-source` flag :-(

**Comment by lenyapugachev** [comment]
@jgrossi strange that for me it's still fails even if I'm unlink, uninstall and then `brew install --build-from-source php56-mongodb`

**Comment by jgrossi** [comment]
@lenyapugachev maybe you need to install some dependency by hand

**Comment by lenyapugachev** [comment]
@jgrossi what dependencies you mean?

**Comment by jgrossi** [comment]
@lenyapugachev I had to install `cmake`

**Comment by javian** [comment]
@jgrossi that's strange if that works since the module does not seem to require cmake.

**Comment by jmikola** [comment]
Perhaps the [patch for ffmpeg's forumla](https://github.com/Homebrew/homebrew-core/commit/4ae579c3c830f7febf6c1098d241c77e90066274) can be adapted from the `phpXX-mongodb` formulae:

```diff
   def install
+    # Fixes "dyld: lazy symbol binding failed: Symbol not found: _clock_gettime"
+    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
+      inreplace %w[src/libbson/src/bson/bson-clock.c], "HAVE_CLOCK_GETTIME", "UNDEFINED_GIBBERISH"

     Dir.chdir "mongodb-#{version}" unless build.head?
```

**Comment by lenyapugachev** [comment]
@jmikola @javian @jgrossi any updates on these?

**Comment by adocwang** [comment]
@lenyapugachev @jmikola jmikola's solution works find. I have meet the error under php71-mongodb.
i think the issue can be explained clearly [here](https://github.com/tarantool/tarantool/issues/1777)
i just telling the detail operation steps about jmikola's solution.

- [ ] `brew edit {fomula} #like php71-mongodb`

- [ ] edit it，add lines after “install”, may like this 
`  def install
    Dir.chdir "mongodb-#{version}" unless build.head?
    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
      inreplace %w[src/libbson/src/bson/bson-clock.c], "HAVE_CLOCK_GETTIME", "UNDEFINED_GIBBERISH"
    end`

- [ ] reinstall php71-mongodb from source `brew reinstall -s php71-mongodb`

**Comment by lenyapugachev** [comment]
@adocwang Hooray! 👌

**Comment by islamz** [comment]
@adocwang you the best

**Comment by javian** [comment]
Feel free to submit a PR that does this.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
