### ISSUE TITLE
php7x-twig is missing

### ISSUE THREAD

**Issue by Drarok** [Homebrew/homebrew-php#3741]
## Description

The Twig extension is available for PHP 5.3 through 5.6, but is missing for the 7.x branches.

**Comment by javian** [comment]
Thanks for your feedback and feel free to scratch your own itch and submit a PR to have it added.

**Comment by andrewtch** [comment]
Twig extension will not be upgraded to 7.0 as it renders zero to none performance impact with phpng.

**Comment by javian** [comment]
Thanks for the feedback @andrewtch . With that said I will close the issue and not merge any twig PRs for php7+. You can read more about it here https://github.com/twigphp/Twig/issues/1695 .
