### ISSUE TITLE
Installing php70-pthreads breaks built-in webserver

### ISSUE THREAD

**Issue by sjelfull** [Homebrew/homebrew-php#3742]
## Description

Installing php70-threads together with php70 breaks the built-in webserver, and causes the error under _Context and logs_

It should only be enabled for php-cli?
## Context and Logs

```
<b>Fatal error</b>:  The cli-server SAPI is not supported by pthreads in <b>Unknown</b> on line <b>0</b><br />
[Fri Oct 28 15:43:09 2016] PHP Fatal error:  Unable to start pthreads module in Unknown on line 0
<br />
<b>Fatal error</b>:  Unable to start pthreads module in <b>Unknown</b> on line <b>0</b><br />
```

| Parameter | Value |
| --- | --- |
| **OS X Version:** | macOS Sierra 10.12 (16A323) |
| **Homebrew Version:** | 1.0.8 |
| **PHP Version in use:** | 7.0.12 |
| **Xcode Version:** | 8.0 |

**Output of gcc -v:**

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**

```
PHP 7.0.12 (cli) (built: Oct 28 2016 11:21:33) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Build logs:** https://gist.github.com/edtwist-readonly/28715380b86417955a3f49cdfb7debe6

**Comment by javian** [comment]
Thanks for the feedback. This is not taken into account at the moment since the php.ini is shared between all the different sapi. You should be able to create a seperate cli-server.ini to use just for this purpose. See http://php.net/manual/en/configuration.file.php .
