### ISSUE TITLE
Obsolete non-working version 0.9.1 of php70-rdkafka

### ISSUE THREAD

**Issue by FGM** [Homebrew/homebrew-php#3743]
## Description

When installing php70-rdkafka, one gets the 0.9.1 extension. 
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.2.1 |
| **Homebrew Version:** | Homebrew 1.0.8 / Homebrew/homebrew-core (git revision 516f; last commit 2016-10-28) |
| **PHP Version in use:** | 7.0.12 |
| **Xcode Version:** | Version 8.1 (8B62) |

**Output of gcc -v:**
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`
**Output of php -v:**
`PHP 7.0.12 (cli) (built: Oct 14 2016 09:56:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans`
**Build logs:** https://gist.github.com/8539a3830bcaf8606dfaa94c7a20b2ff
**`brew list php70-rdkafka`** /usr/local/Cellar/php70-rdkafka/0.9.1-52efa23813ccc8b524c10cd4239338175ef4a6d6/rdkafka.so

**Comment by FGM** [comment]
* The current version for PHP 7.0 is 2.0: https://pecl.php.net/package-info.php?package=rdkafka&version=2.0.0
* The current version for PHP 5.x is 1.0

**Comment by javian** [comment]
@FGM Can you please submit a PR to correct this and support the tap ? Let us know if you need any support.

**Comment by FGM** [comment]
@javian I'd be glad to, but I haven't the faintest idea where to start to do this. Is there a contributor guide somewhere ?

**Comment by javian** [comment]
@FGM You can find some Formula specific information here https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#updating-formulae on how to make updates to an exisiting formula. 

There's a quick mention on how to create the sha here https://github.com/Homebrew/homebrew-php/blob/master/CONTRIBUTING.md . I don't know if that's sufficient information for you to proceed but just ask if you have any further questions or don't understand what's going on. This also doesn't mention anything about github and how to handle pull requests to submit the change - are you familiar with that ?

**Comment by alcaeus** [comment]
@javian this can be closed since you merged my PR.

**Comment by javian** [comment]
@alcaeus thanks for the reminder ^^ and thanks @FGM for giving it a shot.
