### ISSUE TITLE
Boneyard phpenv recipe

### ISSUE THREAD

**Issue by josegonzalez** [Homebrew/homebrew-php#3746]
The [upstream repository](https://github.com/CHH/phpenv) has not been updated in 2 years. While there is an [alternative](https://github.com/phpenv/phpenv), we need to first boneyard the existing one.

What is the usage of our `CHH/phpenv` formula?

**Comment by javian** [comment]
There's been 109 install over the past month for the current phpenv package. The projects seems equally stale to me more or less so replacing it with the other one might not be a good idea. phpbrew seems to be a lot more currently active (200 installs over the last month).

**Comment by josegonzalez** [comment]
I'm not saying we replace, just boneyard. None of the "install a bunch of different PHP" projects seem to be working out so well, but I would rather not push people to dead projects if at all possible.
