### ISSUE TITLE
php-build version is outdated

### ISSUE THREAD

**Issue by joshuap** [Homebrew/homebrew-php#3750]
Before we can update the target version of the [php-build Formula](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php-build.rb) we need a new tag/release on the php-build/php-build repo. I have submitted an issue to them for that [here](https://github.com/php-build/php-build/issues/407).

I'm creating this issue to track it on your end; hopefully that's copacetic. :)

**Comment by javian** [comment]
Thanks - seems like there's been no answer yet so we'll hold on to this issue for a while.

**Comment by javian** [comment]
Still no tagged release available upstream.
