### ISSUE TITLE
Apache module for PHP7.1 RC5 is showing RC3

### ISSUE THREAD

**Issue by moderndeveloperllc** [Homebrew/homebrew-php#3751]
## Description

I've done a `brew upgrade` which pull in RC5. It shows that for the cli version, but the Apache module shows RC3 via `phpinfo()`. Not sure if this is a PHP issue, or a brew issue.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | Homebrew 1.0.9
**PHP Version in use:** | 7.1 RC(?)
**Xcode Version:**      | 8.1
**Output of gcc -v:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**
```
PHP 7.1.0RC5 (cli) (built: Oct 27 2016 07:54:28) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0RC5, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
```

**Build logs:** https://gist.github.com/anonymous/8a21f2c397f12537e5eb1e061f814381

<img width="959" alt="screenshot 2016-11-01 at 10 50 02 am" src="https://cloud.githubusercontent.com/assets/1920405/19896041/fed44c5a-a020-11e6-8ab6-5a5f70132179.png">

**Comment by moderndeveloperllc** [comment]
I just tried to do a `brew reinstall php71 --with-apache`, but that did not solve the issue. Looking at the above screen show, it looks like PHP is building the module off the old version.

**Comment by javian** [comment]
@moderndeveloperllc if you check your apache config its likely that the path has not been updated to the new php version. Can you confirm that ?

**Comment by moderndeveloperllc** [comment]
It's actually showing the RC5 module path: 
```LoadModule php7_module        /usr/local/Cellar/php71/7.1.0-rc.5_9/libexec/apache2/libphp7.so```

I've definitely restarted Apache - even restarted my machine. I haven't had this issue going along the RC updates to this point.

**Comment by moderndeveloperllc** [comment]
Dang it. I double checked the httpd.conf file and saw that `LoadModule php7_module` was in there twice - once for RC3, then for RC5. I removed the old one and it worked fine.
