### ISSUE TITLE
Unable to install php56 with apache

### ISSUE THREAD

**Issue by murraycollingwood** [Homebrew/homebrew-php#3756]
## Description

I recently upgraded to Sierra.  I managed to get Apache2 and MySQL working again, however PHP56 is giving me grief.
The built in version was not working so I began brewing my own copy.
I have previously brewed php53 and php55, so I tried php56.  I kept getting errors in the compilation and/or linking - to do with missing or incompatible libraries (like iconv and libpng)

So I went through the helpful instructions on this page (https://github.com/Homebrew/homebrew-php#common-upgrade-issues) which took me through the process of removing the old php53 and 55 versions, and also removing the php56.  Cleaning and pruning, even the dependencies.  Also updating and upgrading.
Then a nice clean: brew install php56 
This appeared to work but my Apache2 was still reporting an older version (5.6.25 as opposed to 5.6.27 - the version brewing)  So I knew I hadn't picked up the correct version.

I then uninstalled this version: brew uninstall php56
And installed with the apache option: brew install php56 --with-apache
This failed - the output on the screen is next.

## Context and Logs

rata:Caches murray$ brew install php56 --with-apache
==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.27.tar.bz2/from/this/mirror
Already downloaded: /Users/murray/Library/Caches/Homebrew/php56-5.6.27
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.27_4 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-f
Last 15 lines from /Users/murray/Library/Logs/Homebrew/php56/01.configure:
checking for dngettext in -lintl... yes
checking for dcngettext in -lintl... yes
checking for bind_textdomain_codeset in -lintl... yes
checking for GNU MP support... no
checking for mhash support... yes
checking whether to enable hash support... yes
checking whether byte ordering is bigendian... (cached) no
checking size of short... (cached) 2
checking size of int... (cached) 4
checking size of long... (cached) 8
checking size of long long... (cached) 8
checking for iconv support... yes
checking for iconv... no
checking for libiconv... no
configure: error: Please reinstall the iconv library.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
Update php56-ioncubeloader.rb https://github.com/Homebrew/homebrew-php/pull/3753
php56-mongodb _clock_gettime error at runtime https://github.com/Homebrew/homebrew-php/issues/3737
Updated php56-protobuf version. https://github.com/Homebrew/homebrew-php/pull/3272
where is libphp5.so on latest php56? https://github.com/Homebrew/homebrew-php/issues/3714
how to use mac apache with php56 https://github.com/Homebrew/homebrew-php/issues/3688
Cannot use php56 or php55 with system Apache https://github.com/Homebrew/homebrew-php/issues/3633
failed to install php56-pthreads https://github.com/Homebrew/homebrew-php/issues/2768
php56 failed to build on 10.11.5 https://github.com/Homebrew/homebrew-php/issues/3551
php56 failing with Incompatible library version: libphp5.so requires version 41.0.0 or later, but libpng16.16.dylib provides version 38.0.0 https://github.com/Homebrew/homebrew-php/issues/3602

Parameter | Value
--------- | ------------------
**OS X Version:**       | OSX Sierra 10.12.1
**Homebrew Version:**   | Homebrew >1.0.0 (no git repository) Homebrew/homebrew-core (git revision cf02; last commit 2016-11-04)
**PHP Version in use:** | I'm trying to get 5.6.27 (the latest 5.6 version)
**Xcode Version:**      | Xcode 8.1 Build version 8B62

**Output of gcc -v:**
rata:share murray$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
rata:share murray$ php -v

Warning: PHP Startup: memcached: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/mcrypt.so' - dlopen(/usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/mcrypt.so, 9): Library not loaded: /usr/local/lib/libmcrypt.4.dylib
  Referenced from: /usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/mcrypt.so
  Reason: image not found in Unknown on line 0
PHP 5.6.25 (cli) (built: Sep  6 2016 16:37:16) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
rata:Caches murray$ brew gist-logs my-formula
Error: No available formula with the name "my-formula" 

(Not sure what you meant by this one)

** Last comments **
As you can see, I have a number of problems going on.
a) How to uninstall php5.6.25?
b) How to get php5.6.27 compiling and installing?
c) My memcached library is the wrong version - but I brewed this one just recently, supposedly with the correct interface version, but clearly it didn't work.
d) I'm also missing mcrypt - which is the library I needed to get working from the very beginning.  This was working on El Capitan but hasn't worked since the upgrade.

I'm still learning to brew properly, so please be clear with any instructions you think I should try.

**Comment by murraycollingwood** [comment]
I'm now looking for somebody who has the skills to fix this for me.

**Comment by javian** [comment]
What does `brew doctor` output ?

With brew gist-logs you need to replace `my-formula` with `php56` which is the formula you are having problems with.

**Comment by murraycollingwood** [comment]
Solved with the help of this article:
https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions
Also, I added comments to the article for some specific things I had to do.
