### ISSUE TITLE
The latest php packages intl and gmp are broken.

### ISSUE THREAD

**Issue by cyberpower678** [Homebrew/homebrew-php#3762]
## Description

The newest brew tap php packages don't seem to be properly set up.  For all available PHP versions php-intl successfully downloads, compiles, and installs but PHP reports that it cannot load the extension.  Formerly only affecting php56 and php70, executing brew update and upgrade, which I did 30 minutes ago, broke every intl extension for all php versions available.  Unloading the extension in the ini file has the PHP installation working correctly again.  The problem is, I'm dependent on the gmp and intl extensions.  The php-gmp extensions do not work on the php56 and php70 installations.

For php55 when starting it up returns:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-intl/intl.so' - dlopen(/usr/local/opt/php55-intl/intl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php55-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php55-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-intl/intl.so' - dlopen(/usr/local/opt/php55-intl/intl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php55-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php55-intl/intl.so in Unknown on line 0
`

For php56 when starting it up returns:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-gmp/gmp.so' - dlopen(/usr/local/opt/php56-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php56-gmp/gmp.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-gmp/gmp.so' - dlopen(/usr/local/opt/php56-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php56-gmp/gmp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0
`

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | 1.0.9-20-gf14a3a1
**PHP Version in use:** | all
**Xcode Version:**      | 8.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-gmp/gmp.so' - dlopen(/usr/local/opt/php56-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php56-gmp/gmp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-gmp/gmp.so' - dlopen(/usr/local/opt/php56-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php56-gmp/gmp.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 5.6.27 (cli) (built: Nov  2 2016 00:57:14) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** Error: No logs.

**Comment by alcaeus** [comment]
Can you try `brew update && brew upgrade`? This should have been fixed by #3760.

**Comment by cyberpower678** [comment]
Nope it's even worse now.
PHP53 gives me:
'PHP Warning:  PHP Startup: intl: Unable to initialize module
Module compiled with build ID=API20090626,NTS
PHP    compiled with build ID=API20090626,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: intl: Unable to initialize module
Module compiled with build ID=API20090626,NTS
PHP    compiled with build ID=API20090626,TS
These options need to match
 in Unknown on line 0
PHP 5.3.29 (cli) (built: Nov  1 2016 23:40:30) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans'

php54 returns:
'PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php54-intl/intl.so' - dlopen(/usr/local/opt/php54-intl/intl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php54-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php54-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php54-intl/intl.so' - dlopen(/usr/local/opt/php54-intl/intl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php54-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php54-intl/intl.so in Unknown on line 0
PHP 5.4.45 (cli) (built: Nov  1 2016 23:55:51) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans'

php55 returns:
'PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-intl/intl.so' - dlopen(/usr/local/opt/php55-intl/intl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php55-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php55-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-intl/intl.so' - dlopen(/usr/local/opt/php55-intl/intl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php55-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php55-intl/intl.so in Unknown on line 0
PHP 5.5.38 (cli) (built: Nov  2 2016 10:41:20) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans'

php56 returns:
'PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-gmp/gmp.so' - dlopen(/usr/local/opt/php56-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php56-gmp/gmp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-gmp/gmp.so' - dlopen(/usr/local/opt/php56-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php56-gmp/gmp.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php56-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php56-intl/intl.so in Unknown on line 0
PHP 5.6.27 (cli) (built: Nov  2 2016 00:57:14) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans'

php70 returns:
'PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gmp/gmp.so' - dlopen(/usr/local/opt/php70-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gmp/gmp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gmp/gmp.so' - dlopen(/usr/local/opt/php70-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gmp/gmp.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php70-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php70-intl/intl.so in Unknown on line 0
PHP 7.0.12 (cli) (built: Nov  2 2016 01:25:40) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans'

php71 returns:
'PHP 7.1.0RC5 (cli) (built: Oct 25 2016 20:31:50) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans'

I find it somewhat sad that brew can't link and unlink the packages automatically when upgrading forcing me to do it manually, and run the upgrade process again.

**Comment by javian** [comment]
This error
```
Module compiled with build ID=API20090626,NTS
PHP compiled with build ID=API20090626,TS
```
Indicates that php is configured with `thread safety` whereas the module is not. As far as I can see there's no support to install the module with thread safety enabled.

For you second post did you install the bottles of the intl and gmp formulas ? If you did, can you try compiling them on your system to see if that solves the issue ? `brew reinstall -s php70-intl`

**Comment by cyberpower678** [comment]
How odd, it worked when I installed it initially.  All of my PHP installations have pthreads installed, except 71, which has no support for it yet.

All extensions have been installed using Homebrew.

**Comment by cyberpower678** [comment]
Oh yea, that fixed it.  All versions including php53 and all mentioned packages work now.  Was this simply a brew upgrade gone wrong, or do I have to always reinstall the packages?

**Comment by javian** [comment]
@cyberpower678 Not sure right now since I've not tested that scenario so it might be that they need to be reinstalled. Feel free to submit another issue on that specifically if it happends.

 Also if pthreads works for 7.1 feel free to submit a PR to add it to the formula collection.

**Comment by kyawkyawsoezhu** [comment]
**fixed for me**
brew unlink php56-intl
brew install php56-intl

**Comment by inoas** [comment]
So what helped me is:

```
brew reinstall --build-from-source php71-intl
brew reinstall --build-from-source php72-intl
```
... unlinking or otherwise reinstalling would not help.
