### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by 18618461139** [Homebrew/homebrew-php#3768]
## Description
Downloading https://php.net/get/php-5.4.45.tar.bz2/from/this/mirror
Already downloaded: /Users/zhangxiaotian/Library/Caches/Homebrew/php54-5.4.45
==> ./configure --prefix=/usr/local/Cellar/php54/5.4.45_6 --localstatedir=/usr/l
==> make
Last 15 lines from /Users/zhangxiaotian/Library/Logs/Homebrew/php54/02.make:
      _php_openssl_sockop_set_option in xp_ssl.o
  "_SSLv3_server_method", referenced from:
      _php_openssl_sockop_set_option in xp_ssl.o
  "_SSLv3_server_method", referenced from:
      _php_openssl_sockop_set_option in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
make: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/fpm/php-fpm] Error 1
make: *** [sapi/cli/php] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/josegonzalez/homebrew-php/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': Validation Failed (GitHub::Error)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:323:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:319:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:381:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _10.12_
**Homebrew Version:**   | _1.1.0_
**PHP Version in use:** | _5.4_
**Xcode Version:**      | _none_

**Output of gcc -v:**
_result of the CLI output_

**Output of php -v:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
Can you do `brew gist-logs php54` and paste the link here ?

**Comment by javian** [comment]
@18618461139 any update on this issue ?
