### ISSUE TITLE
How to specify minimum version of PHP required within a formula

### ISSUE THREAD

**Issue by anthonysomerset** [Homebrew/homebrew-php#3772]
I'm hoping to have deployer added to the homebrew-php repo current PR: #3771 

Deployer requires a minimum of PHP 5.5.x for obvious reasons and while i suspect most people will be aware of this i wouldn't want someone to unsuspectingly install it with only PHP 5.4.x

how can one specify the minimum PHP version as a dependency in the formula?

**Comment by javian** [comment]
There's no good and easy way to do this at the moment I'm afraid.
