### ISSUE TITLE
PHP 5.6 with Apache does not run PHP code, serves the PHP source instead.

### ISSUE THREAD

**Issue by edgework** [Homebrew/homebrew-php#3776]
## Description

After brew install --with-apache php56 .  Disabling apache that came with MacOS and ULTRA sure that I'm running the apache from brew.  Navigating to a a site that worked fine under MacOS Apache/PHP serves the PHP code rather than running it.

![image](https://cloud.githubusercontent.com/assets/5122883/20335518/16d7cd9c-ab78-11e6-976d-6a1aa45109db.png)

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       |10.12.1
**Homebrew Version:**   |Homebrew 1.1.0 Homebrew/homebrew-core (git revision f4a7; last commit 2016-11-15)
**PHP Version in use:** | 5.6
**Xcode Version:**      | Version Brew Installed

**Output of gcc -v:**
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP Warning:  Module 'pcntl' already loaded in Unknown on line 0

Warning: Module 'pcntl' already loaded in Unknown on line 0
PHP 5.6.27 (cli) (built: Nov 15 2016 20:03:57) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:**

https://gist.github.com/54b2ad86afb83fd1a62f52b49f798435

**Comment by javian** [comment]
@edgework your're missing some code in the apache config which should have been displayed when you installed php. See https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb#L444-L462

**Comment by edgework** [comment]
What you sent me is for PHP 7 and I'm on 5.6 though I understand what you're getting at.. But it didn't make any difference.

**Comment by javian** [comment]
@edgework the php5 copy is just below https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb#L457-L461 - can you paste what you inserted into the apache config ?

**Comment by javian** [comment]
@edgework did you manage to resolved this issue ?

**Comment by markl181** [comment]
I had the same issue after upgrading from PHP56 to PHP70 with homebrew. It looks like the httpd.conf did not get updated (all of those lines you highlighted were missing). Once I added them and restarted, it did work. thanks!

**Comment by jvdjay** [comment]
im having the same issue but I have no idea where to place these patches in the apache / php files.
