### ISSUE TITLE
PHP doesn't have any output

### ISSUE THREAD

**Issue by colloct** [Homebrew/homebrew-php#3781]
## Description

Nginx upstream to PHP-fpm via unix-socket.

GET /index.php

index.php
```php
<?php
phpinfo();
```

`Status Code: 200 OK`
and have a response header: `X-Powered-By: PHP/7.0.12`

But it doesn't have any output, source code is empty.
Nginx access log records. No error message was recorded in the error log.

BTW, all .html or another static file is OK.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | macOS Sierra 10.12.1
**Homebrew Version:**   | Homebrew/homebrew-core (git revision 5717; last commit 2016-11-21)
**PHP Version in use:** | PHP 7.0.12
**Xcode Version:**      | v8.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.12 (cli) (built: Oct 14 2016 09:56:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
Error: Not log.

**Comment by colloct** [comment]
I've just added the below line:

```
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
```

It works now.

**Comment by javian** [comment]
Glad that you managed to sort it out.
