### ISSUE TITLE
php 7.0.13_6 upgrade configuration can't find ZLIB

### ISSUE THREAD

**Issue by stevewi** [Homebrew/homebrew-php#3782]
## Description
ZLIB library location not known

_Problem description goes here_
Configuration fails

## Context and Logs
/usr/local/Cellar/php70 $ brew upgrade
==> Upgrading 3 outdated packages, with result:
josegonzalez/php/php70 7.0.13_6, josegonzalez/php/php70-mcrypt 7.0.13_5, josegonzalez/php/php70-tidy 7.0.13_5
==> Upgrading josegonzalez/php/php70
==> Downloading https://php.net/get/php-7.0.13.tar.bz2/from/this/mirror
Already downloaded: /Users/stevewi/Library/Caches/Homebrew/php70-7.0.13
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.13_6 --localstatedir=/usr/l
Last 15 lines from /Users/stevewi/Library/Logs/Homebrew/php70/01.configure:
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable PCRE JIT functionality... yes
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/josegonzalez/homebrew-php/issues

Error: Validation Failed
Parameter | Value
--------- | ------------------
**OS X Version:**       | _your OS X version_
10.12.1
**Homebrew Version:**   | _your Homebrew version_
1.1.1
**PHP Version in use:** | _your PHP version_
7.0.12
**Xcode Version:**      | _your Xcode version_
8.1 (8B62)

**Output of gcc -v:**
_result of the CLI output_
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
_result of the CLI output_
PHP 7.0.12 (cli) (built: Oct 23 2016 09:06:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
https://gist.github.com/9b44a213a973c3182fe3b8d07aa7dd68

**Comment by javian** [comment]
Run `xcode-select --install` and it should install the required headers.
