### ISSUE TITLE
Imap is not available for php70

### ISSUE THREAD

**Issue by rpg999** [Homebrew/homebrew-php#3787]
I've recently installed php70 with extension imap 

> brew install php70 --with-imap 

but i've got imap-uw installed. I can't make my code works because i get the error 

> "Call to undefined imap_open()"

i've tried brew search php70-imap, but nothing has been founded. So the question is, has imap for php7 been ported or i did something wrong while installing ?

**Comment by benpoulson** [comment]
What was your solution for this?

**Comment by rpg999** [comment]
I don't remember how i made it works. 

Likely I reinstalled php70 with these parameters.
`brew install php70 --with-imap --with-fpm`

**Comment by vladprokopchuk** [comment]
I have installed like this
brew install php70 --with-imap --with-fpm

but problem is

vlad@MacBook-Pro-Vladimir /etc $ time php -v
PHP 7.1.6 (cli) (built: Jul 3 2017 08:34:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

real	0m5.039s
user	0m0.016s
sys	0m0.011s
vlad@MacBook-Pro-Vladimir /etc $

adding 127.0.0.1 myhost.local to /etc/hosts file did not help
I really need IMAP extension
But every using php-cli takes 5 sec delay
If Iwill install php without imap all works fast

**Comment by rpg999** [comment]
I have the same problem with 5 seconds of delay, but it's seems to me that this is the only way you can make imap works, deal with it.

**Comment by vladprokopchuk** [comment]
I had installed the same way about 3-4 months ago on mac sierra too, php70. All works fine.
Now Im trying 70 or 71 versions both have 5 sec delay, cant understand where is problem....
