### ISSUE TITLE
Major performance difference between PHP 5.5 and 7.0

### ISSUE THREAD

**Issue by staticdreams** [Homebrew/homebrew-php#3794]
## Description

Working the other day on local a wordpress site I noticed huge lags in between page refreshes. At first everything was fine, but when I installed and activated a "resource heavy" theme along with all its components, the time between page reloads were never < 7 seconds. Averaging between 15 et 20 seconds. It drove me crazy. Even wordpress admin took ~20 seconds to refresh a page. I tried everything - reinstalled Apache (also via brew), re-installed various extensions (opcache, memcached, apcu..). Nothing helped. Finally I switched to php55...  and page render time was... (wait for it).... 1.5 seconds! I have no idea why php70 lags so much. I even tried to match configs of both php installations, but maybe I'm just to stupid to see it.

Btw, I never noticed this performance difference on other local websites, granted, they were not so resource hungry.

Anyway, here are both php configs:

https://www.staticdreams.com/php/php55.html
https://www.staticdreams.com/php/php70.html

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | 1.1.2
**PHP Version in use:** | 7.0
**Xcode Version:**      | 8.1

**Output of gcc -v:**
    ``Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin16.1.0
    Thread model: posix
    InstalledDir:      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin``

**Output of php -v:**
``PHP 7.0.13 (cli) (built: Nov 30 2016 17:15:16) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0rc2-dev, Copyright (c) 2002-2016, by Derick Rethans``

**Build logs:** https://gist.github.com/06fedbcdab87afbdd9ed35d9a889adb5

**Comment by javian** [comment]
Your xdebug settings seems different, can that explain the performance impact ?

**Comment by staticdreams** [comment]
@javian thanks for your reply.
I just tried doing ``brew remove php70-xdebug`` and removing ``ext-xdebug.ini`` file associated with it from ``/usr/local/etc/php/7.0/conf.d/`` folder to see if it changes anything. Still lags :(
Is there anything else I can try?

**Comment by javian** [comment]
You seem to have different extensions loaded - would that have any effect on the executed code ?

**Comment by staticdreams** [comment]
@javian I completely uninstall php70 and removed assiciated folder. Than re-installed everything from scratch. Seems to work now. Thank you for you time
