### ISSUE TITLE
How to best upgrade from PHP 7.0.13 to 7.1

### ISSUE THREAD

**Issue by rpkoller** [Homebrew/homebrew-php#3796]
## Description

I have installed the `homebrew/php/php70`formula. With todays release of PHP 7.1 its formula is already available `homebrew/php/php71`. But if I perform a `brew update` and or `brew upgrade` the update isn't showing. Is there a formula providing a continuous upgrade path, means I am able to perform a simple `brew upgrade` to push the PHP version from e.g. 7.0.13 to 7.1? And is there a best practice in regards of upgrading? Delete with `brew uninstall homebrew/php/php70` and then install with`brew install homebrew/php/php71` afterwards? Best regards Ralf

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | homebrew 1.1.2, Homebrew/homebrew-core (git revision 23cdc; last commit 2016-12-02)
**PHP Version in use:** | PHP 7.0.13 (cli) (built: Nov 15 2016 23:48:44) ( NTS )
**Xcode Version:**      | xcode-select version 2343

**Comment by pinepain** [comment]
Hi, you have to uninstal or just unlink php70 and install php71

**Comment by rpkoller** [comment]
Thanks for the fast answer @pinepain ! i went with `brew uninstall php70`. seemed to work flawlessly. `brew install homebrew/php/php71` was easy afterwards. ;) So thanks again for the headsup!
