### ISSUE TITLE
Readme mentions outdated macOS versions

### ISSUE THREAD

**Issue by jonnybarnes** [Homebrew/homebrew-php#3797]
In Requirements neither El Capitan or Sierra are mentioned. The readme implies these are untested releases.

**Comment by josegonzalez** [comment]
Mind issuing a pull request?

**Comment by jonnybarnes** [comment]
what should the list be, guessing yosemite, el capitan, and sierra>

**Comment by javian** [comment]
@jonnybarnes yes.

**Comment by javian** [comment]
Thanks for the help @jonnybarnes ^^
