### ISSUE TITLE
Homebrew is using a weirdly versioned prefix

### ISSUE THREAD

**Issue by jonnybarnes** [Homebrew/homebrew-php#3805]
## Description

Homebrew is using a wierdly versioned prefix.

When I installed `php71` with specific options, meaning it compiled from source, here was the start of the configure line in my terminal:

```shell
./configure --prefix=/usr/local/Cellar/php71/7.1.0_11
```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.1.2-15-g52691cd0d
**PHP Version in use:** |7.1.0
**Xcode Version:**      | 8.0

**Comment by javian** [comment]
If you are referring to the _11 then that's the formula revision and completely normal.

**Comment by jonnybarnes** [comment]
Fair enough
