### ISSUE TITLE
PHP 7.0 installation fails when running `./configure`

### ISSUE THREAD

**Issue by AchoArnold** [Homebrew/homebrew-php#3812]
## Description
When doing `brew install php70 --with-imap --with-postgresql` The installation fails with the following logs

## Context and Logs

https://gist.github.com/AchoArnold/6c1c46e97b03f80a330b07b16291727c

Parameter | Value
--------- | ------------------
**OS X Version:**       |  10.12.1
**Homebrew Version:**   | 1.1.2
**PHP Version in use:** | 7.0
**Xcode Version:**  |  8.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
Inapplicable

**Build logs:** 
https://gist.github.com/AchoArnold/6c1c46e97b03f80a330b07b16291727c

**Comment by javian** [comment]
Does it work without the options if you just do  `brew install -s php70` ?

**Comment by AchoArnold** [comment]
Yes it does
