### ISSUE TITLE
Update optional dependency pattern

### ISSUE THREAD

**Issue by mgoeppner** [Homebrew/homebrew-php#3835]
## Description

There is an issue where if a head-only formula uses a formula as a dependency, and that dependency has optional dependencies, the optional dependency's dependencies will not be installed. 

The code which causes this looks like: `depends_on 'package' if build.include? 'with-foo'` or `depends_on 'package' if build.with? 'with-foo'`.

The fix is pretty straightforward:

1. Deprecate the `with-foo` option and add a `with-package` option.
2. Replace references of `with-foo` in the formula with `with-package`
3.  Change `depends_on 'package' if build.include? 'with-foo'` to `depends_on 'package' => :optional`.

See https://github.com/Homebrew/homebrew-php/pull/3834 and https://github.com/Homebrew/homebrew-core/issues/7719 for additional details.

**Comment by javian** [comment]
The current dependencies that comes to mind that could be affected are
```
depends_on 'curl' if build.include?('with-homebrew-curl') || MacOS.version < :lion
depends_on 'freetds' if build.include?('with-mssql')
depends_on 'imap-uw' if build.include?('with-imap')
depends_on 'libxml2' if build.include?('with-homebrew-libxml2') || MacOS.version < :lion || MacOS.version >= :el_capitan
```
And potentially `if build.include?('with-homebrew-libressl')`
