### ISSUE TITLE
Memcached for PHP 7.1?

### ISSUE THREAD

**Issue by taylorotwell** [Homebrew/homebrew-php#3841]
Thanks so much for providing these formulas!

Will `php71-memcached` be available in the future, or is there some hold up on the Memcached side from this building for PHP 7.1?

**Comment by javian** [comment]
The hold up has been that there's been no stable release of the memcached for any of the php7 versions yet. The head formula for 7.0 was merged a while back and there is a submission for 7.1 amongst the pull requests but I would rather wait until there's release version ready to go. They've been working on it for quite some time and afaik there's been no notification of when a tagged release will be made.

https://github.com/php-memcached-dev/php-memcached/issues

**Comment by RualLee** [comment]
How long laravel can support php7?

**Comment by josegonzalez** [comment]
@javian Closing as there realistically isn't anything actionable here.

**Comment by bryceadams** [comment]
@javian seems like there was one tagged just a couple days ago :) https://github.com/php-memcached-dev/php-memcached/releases

**Comment by javian** [comment]
@bryceadams yes - its currently on the way to be merged.
