### ISSUE TITLE
Can't compile php70 using '--with-httpd24'; unrecognized options: --with-mysql

### ISSUE THREAD

**Issue by cschorr** [Homebrew/homebrew-php#3846]
## Description

I want to install PHP with `libphp7.so` for Apache but compiling failed with Error:
`unrecognized options: --with-mysql`

The option `--with-mysql` is not valid anymore for PHP7

```
$ brew install php70 --with-httpd24
==> Installing php70 from homebrew/php
==> Downloading https://php.net/get/php-7.0.14.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-7.0.14.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.14_7 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/etc/p
Last 15 lines from /Users/cschorr/Library/Logs/Homebrew/php70/01.configure:
--enable-dtrace
--disable-phpdbg
--enable-zend-signals

configure: WARNING: unrecognized options: --with-mysql
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... (cached) sed
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
checking whether the C compiler works... no
configure: error: in `/private/tmp/php70-20161213-17641-sdxo2a/php-7.0.14':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Add php70-zmq formula https://github.com/Homebrew/homebrew-php/pull/3474
Fix: Update gearman for php70-gearman https://github.com/Homebrew/homebrew-php/pull/3814
Installing php70-pthreads breaks built-in webserver https://github.com/Homebrew/homebrew-php/issues/3742
Allow --enable-redis-igbinary for php70-redis https://github.com/Homebrew/homebrew-php/pull/3473
Can't compile php70 using '--with-apache'; unrecognized options: --with-mysql https://github.com/Homebrew/homebrew-php/issues/3736
```

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.1.2
**PHP Version in use:** | 7.0.14
**Xcode Version:**      | 8.1 (8B62)

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
-

**Build logs:** https://gist.github.com/anonymous/c93e68069779bdc5887180e61fcea1ca

**Comment by javian** [comment]
The error is not about mysql - its about `configure: error: C compiler cannot create executables` which is different.

**Comment by madouidesign** [comment]
Hi @cschorr

1 - uninstall xcode 8 with [AppCleaner](https://freemacsoft.net/appcleaner/)
2 - install last version [xcode 8.2](https://itunes.apple.com/us/app/xcode/id497799835?ls=1&mt=12) to fix C compilation error
3 - install or reinstall php70

brew install php70 --with-httpd24
or
brew reinstall php70 --with-httpd24 if it's already installed

4 - Now your php module is in /usr/local/opt/php70/libexec/apache2/libphp7.so

5 - Add this line in your httpd.conf
LoadModule php7_module /usr/local/opt/php70/libexec/apache2/libphp7.so

And it's done

**Comment by cschorr** [comment]
Thanks @madouidesign.
Upgrading to XCode 8.2 solved my problem!

**Comment by madouidesign** [comment]
You're welcome @cschorr

**Comment by manuelselbach** [comment]
I ran into the same problems.
Info screen of Xcode said 8.2, thus I thought everything is ok.

I figured out, that running the following command once more forced Xcode to download the update for the CLI Tools with version 8.2:

```xcode-select —install```

Thus a complete reinstall of Xcode was not necessary.
