### ISSUE TITLE
Invalid SHA hash for n98-magerun formula

### ISSUE THREAD

**Issue by martinboy** [Homebrew/homebrew-php#3851]
## Description

The actual SHA256 hash for the file https://files.magerun.net/n98-magerun-1.97.22.phar is 15cae8e72121991fcc397ea3c3735d67f679b499e76dd427b7bd23dde05dc166 but the expected hash is 199dd0d416260c68e691580ffd3f7a448d60f616529aadadcfee584992d6253e

**Comment by javian** [comment]
There's been new releases of it so we should update to the latest version. Feel free to submit a PR to make the update.

**Comment by javian** [comment]
Thanks for the submission! Closing issue.
