### ISSUE TITLE
how can i fix "No available formula with the name "josegonzalez/php/php56""

### ISSUE THREAD

**Issue by feivorid** [Homebrew/homebrew-php#3854]
## I want uninstall php56-yaf 

▶ brew uninstall php56-yaf

Error: No available formula with the name "josegonzalez/php/php56"
Please tap it and then try again: brew tap josegonzalez/php

and I "brew tap josegonzalez/php"    

▶ brew tap josegonzalez/php
Updating Homebrew...
==> Tapping josegonzalez/php
Cloning into '/usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php'...
remote: Counting objects: 663, done.
remote: Compressing objects: 100% (430/430), done.
remote: Total 663 (delta 432), reused 303 (delta 231), pack-reused 0
Receiving objects: 100% (663/663), 279.64 KiB | 31.00 KiB/s, done.
Resolving deltas: 100% (432/432), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/arcanist.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/behat.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/boris.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/box.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/codeception.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/composer.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/deployer.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/drupal-code-sniffer.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/drupalconsole.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/drush.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/envoy.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/foreman.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/mondrian.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/n98-magerun.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/n98-magerun2.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/pdepend.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phan.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/pharcc.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phing.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php-code-sniffer.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php-cs-fixer.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php-plantumlwriter.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php53-xhgui.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php54-xhgui.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php55-xhgui.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/php56-xhgui.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpab.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpbrew.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpcpd.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpctags.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpdocumentor.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpdox.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phploc.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpmd.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpmetrics.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpmyadmin.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phppgadmin.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpunit-skeleton-generator.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/phpunit.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/pickle.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/psysh.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/puli.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/robo.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/sqlformat.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/symfony-installer.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/terminus.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/virtphp.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/wp-cli.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/josegonzalez/homebrew-php/Formula/xdebug-osx.rb
Formulae found in multiple taps:
 * homebrew/php/php53
 * josegonzalez/php/php53

Please use the fully-qualified name e.g. homebrew/php/php53 to refer the formula.
Error: Cannot tap josegonzalez/php: invalid syntax in tap!

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | 1.1.4
**PHP Version in use:** | 5.6.29
**Xcode Version:**      | 8.2

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
▶ php -v
PHP 5.6.29 (cli) (built: Dec  9 2016 07:03:56)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by javian** [comment]
Just remove the josegonzales tap, you shouldn't be using it.

**Comment by feivorid** [comment]
@javian  yes  ?  your mean is  
"▶ brew untap josegonzalez/php
Error: No available tap josegonzalez/php."

just like this.
thank you.

**Comment by javian** [comment]
I don't have access to a mac at the moment to give specific details but what is the content of `/usr/local/Homebrew/Taps/` . Do you have a josegonzales directory there ?

**Comment by feivorid** [comment]
▶ pwd
/usr/local/Homebrew/Library/Taps
▶ ll
total 0
caskroom
homebrew

just like this , you said `/usr/local/Homebrew/`   no Taps directory ;

▶ pwd
/usr/local/Homebrew
▶ ll
total 48
 CHANGELOG.md
 CODEOFCONDUCT.md
 CONTRIBUTING.md
 LICENSE.txt
 Library
 README.md
 bin
 completions
 docs
 manpages

**Comment by javian** [comment]
Ok than I missed the library part so that is ok. So looking at your taps directory it looks ok so I wonder why it acted like that. Does `brew doctor` tell you anything that could help ?

**Comment by feivorid** [comment]
@javian   yes I have tried `brew doctor` 
`▶ brew doctor
Your system is ready to brew.`

**Comment by feivorid** [comment]
@javian  do you have a wechat or other live chat tools ?

**Comment by javian** [comment]
What does `brew info php56-yaf` output ?

**Comment by feivorid** [comment]
@javian  

▶ brew info php56-yaf
homebrew/php/php56-yaf: stable 2.3.3, HEAD
Yaf is a PHP framework similar to zend framework, which is written in c and built as PHP extension
https://pecl.php.net/package/yaf
/usr/local/Cellar/php56-yaf/2.3.3 (3 files, 217.5K) *
  Poured from bottle on 2015-12-21 at 15:13:29
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56-yaf.rb
==> Dependencies
Build: autoconf ✔
Required: php56 ✔, pcre ✔
==> Options
--without-config-file
	Do not install extension config file
--without-homebrew-php
	Ignore homebrew PHP and use default instead
--HEAD
	Install HEAD version
==> Caveats
To finish installing yaf for PHP 5.6:
  * /usr/local/etc/php/5.6/conf.d/ext-yaf.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the yaf module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run `php -i "(command-line 'phpinfo()')"`
  * - Look for the info on the yaf module.
  * - If you see it, you have been successful!

this is output!

**Comment by javian** [comment]
Can you install and remove other extensions without any issues ?

**Comment by javian** [comment]
@feivorid did you manage to solve this issue ?

**Comment by feivorid** [comment]
@javian   oh  no   I solved   by   reinstall homebrew
