### ISSUE TITLE
`homebrew/php/phpsh` doesn't work after installation due to missing config file.

### ISSUE THREAD

**Issue by koenpunt** [Homebrew/homebrew-php#3868]
## Description

`homebrew/php/phpsh` doesn't work after installation due to missing config file.

```
Warning: require_once(/etc/phpsh/rc.php): failed to open stream
```

But as phpsh is no longer maintained, fixing to make it work is probably not worth it, and so I think maybe this formula should be disabled for macOS Sierra.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | macOS Sierra 10.12.2
**Homebrew Version:**   | 1.1.5
**PHP Version in use:** | 5.6.27
**Xcode Version:**      | 8.2.1 (8C1002)

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.6.27 (cli) (built: Oct 23 2016 11:47:58)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** https://gist.github.com/koenpunt/8627518359e7866e41e7444379d17d94

**Comment by javian** [comment]
Thanks for the report. The repo states 
```
This is an archived project and is no longer supported or updated by Facebook. Please do not file issues or pull-requests against this repo. If you wish to continue to develop this code yourself, we recommend you fork it.
```
so I would be tempted to retire it completely and move it into the boneyard.

**Comment by alcaeus** [comment]
See #3869.
