### ISSUE TITLE
php56-intl error after upgrading icu4c from 58.1 to 58.2

### ISSUE THREAD

**Issue by littleylv** [Homebrew/homebrew-php#3882]
## Description
After upgrading icu4c from 58.1 to 58.2:
``PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.58.1.dylib``

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.2
**Homebrew Version:**   | 1.1.5
**PHP Version in use:** | 5.6/7.1
**Xcode Version:**      | none

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.58.1.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-intl/intl.so' - dlopen(/usr/local/opt/php56-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.58.1.dylib
  Referenced from: /usr/local/opt/php56-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 5.6.29 (cli) (built: Dec 16 2016 16:09:51) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by alcaeus** [comment]
I've created a PR to rebuild the bottles for the intl extension. In the meantime, you can force a rebuild by running `brew reinstall -s php56-intl`.

**Comment by littleylv** [comment]
@alcaeus  Thanks. That works.

**Comment by javian** [comment]
PR now merged. Thanks for the report @littleylv !
