### ISSUE TITLE
Symbol not found: _apr_stat$INODE64

### ISSUE THREAD

**Issue by Kyslik** [Homebrew/homebrew-php#3895]
## Description

`$ sudo apachectl configtest`

`httpd: Syntax error on line 112 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load libexec/apache2/mod_log_config.so into server: dlopen(/usr/libexec/apache2/mod_log_config.so, 10): Symbol not found: _apr_stat$INODE64\n  Referenced from: /usr/libexec/apache2/mod_log_config.so\n  Expected in: flat namespace\n in /usr/libexec/apache2/mod_log_config.so`

php installed `brew homebrew/php/php71 --with-httpd24 --without-ldap` 

Tried googling around for few hours nothing seems to work.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _10.10.5_
**Homebrew Version:**   | _Homebrew 1.1.6-9-g98dadd907_
**PHP Version in use:** | _7.1_
**Xcode Version:**      | _7.2.1_

**Output of gcc -v:**
_Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix_

**Output of php -v:**
_PHP 7.1.0 (cli) (built: Jan  4 2017 21:25:22) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies_

**Output of sudo apachectl -v:**
Server version: Apache/2.4.23 (Unix)
Server built:   Sep 27 2016 15:44:16

**Build logs:** _https://gist.github.com/Kyslik/fae1cfc527ceb768bcd8ac2bcbc3725e_

**Comment by javian** [comment]
That looks an apache issue and not a php issue. Can you try and `brew reinstall httpd24 -s` to reinstall apache from source and see if that works ?

**Comment by Kyslik** [comment]
That did the trick (and additional apache setup).

Thanks
