### ISSUE TITLE
brew should warn if homebrew-core has not checked out master

### ISSUE THREAD

**Issue by ohcibi** [Homebrew/homebrew-php#3899]
## Actual Description

I leave the description of my original issue in here in order to demonstrate how that issue bugged me at a seemingly completely unrelated place.

The actual issue now is simply explained: I had contributed to `homebrew-core` like a month ago and checked out a feature branch for that. After that I forgot to checkout `master` before doing anything like `brew update` or `brew upgrade`. What happens today is:

* I ran `brew update` which updated nothing from `homebrew-core` (because `git pull` was already up-to-date due to my branch being checked out) but everything else, e.g. `php56`
* the dependencies of `php56` had changed but the proper version could not be found amongst the not-updated `homebrew-core` formulas
* ==> `php56` updated to a broken state without any errors, hints or warnings from brew

So my suggestion is: add a test that checks if `homebrew-core` is properly set up regarding git. I'd say it should be reported by brew doctor or - depending on how common or uncommon it is to change the repositories settings - even as a warning/error when doing commands like `brew install` or `brew upgrade` where this is crucial.

The purpose of this issue is to find out if thats desired and how (report of `brew doctor` vs warning/error while installing). If its desired we'd need to define what "properly set up" means. Currently I can only think of a valid/supported repositories URL and the `master` branch being checked out. But maybe there is more. I'd provide a PR when those things are clear.

~~## Description~~

~~I did a `brew update && brew upgrade` today and it fails when it tries to upgrade some php module. It turns out that it simply failed because it's script seems to call `php` which completely stopped working:~~

    php -v
    dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
    Referenced from: /usr/local/bin/php
    Reason: Incompatible library version: php requires version 43.0.0 or later, but libpng16.16.dylib provides version 42.0.0

~~I have repeatedly tried to uninstall and reinstall or unlink and relink libpng as well as php56, php56 and php70. The error only happens with php56 and above but is consistent no matter what uninstall/reinstall strategy I tried.~~

~~## Context and Logs~~

~~Parameter | Value
**OS X Version:**       | _10.12.2_
**Homebrew Version:**   | _1.1.6-43-gdf46d62_
**PHP Version in use:** | _5.6_
**Xcode Version:**      | _8.2 (8C38)_~~

~~**Output of gcc -v:**~~

    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin16.3.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

~~**Output of php -v:**~~

    dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
    Referenced from: /usr/local/bin/php
    Reason: Incompatible library version: php requires version 43.0.0 or later, but libpng16.16.dylib 

~~**Build logs:**~~

~~The command to upload the logs says: `Error: No logs.`~~

~~**Additional info**~~

~~This seems to be related to the numerous issues regarding incorrect loading or searching for dylibs, e.g. #3602 and #3551 but as all of these are able to provide a `php -v` output, my issue seems to be different.~~

**Comment by javian** [comment]
Hi @ohcibi , I think this issue better belongs in the brew repo since its not really related to PHP.

**Comment by ohcibi** [comment]
@javian you are right... I posted it in here because - as I've explained in the issue - it all started with php
