### ISSUE TITLE
PHP56-imagick appears to be broken

### ISSUE THREAD

**Issue by pawel-detka** [Homebrew/homebrew-php#3916]
## Description

PHP56-imagick appears to be broken.
After update imagick to imagemagick-7.0.4-4

Same issue https://github.com/Homebrew/homebrew-php/issues/3912

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.2 (16C68)
**Homebrew Version:**   | 1.1.7
**PHP Version in use:** | 5.6.29
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 5.6.29 (cli) (built: Dec  9 2016 07:03:56) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by Michael-Min** [comment]
I have encountered this problem.

**Comment by captain-geek** [comment]
Have been dealing with this problem since last week also. occurs with both php56 and php70

**Comment by ilovezfs** [comment]
@pawel-detka @Michael-Min @captain-geek Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"

**Comment by pawel-detka** [comment]
@ilovezfs Is there any chance to repair this issue automatically?
I've installed imagemagick@6 and php56-imagick, but normal imagick was installed too. 
I've had to recreate sybmolic links:
/usr/local/opt$ rm imagemagick &&  ln -s imagemagick@6 imagemagick

**Comment by captain-geek** [comment]
@ilovefs Is there a chance to upgrade the version of php56-imagick to 3.4.x? This will work with both 6 & 7 versions of ImageMagick ...

**Comment by fdelaiglesia-mobaloo** [comment]
The fix using brew seems to be:
brew unlink imagemagick
brew install imagmagick@6 (keg only)
brew link imagemagick@6 —force

then restart php and apache

Thanks to @meljtarner 
https://github.com/Homebrew/homebrew-php/issues/3912

**Comment by lukeinage** [comment]
That fix worked!

Just for clarity though, there were a couple of mistakes in that workaround:

brew unlink imagemagick
brew install imagemagick@6
brew link imagemagick@6 --force

**Comment by pawel-detka** [comment]
@meljtarner @fdelaiglesia-mobaloo @lukeinage Thank you

**Comment by javian** [comment]
This has now been fixed and should require no additional commands to make it work as expected.

**Comment by fobin** [comment]
Where is this fixed? Installing imagemagick with following fails:
brew install php70
brew install php70-imagick

And then php -a gives error:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.1.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0

**Comment by alcaeus** [comment]
@fobin Unfortunately, this error reappears everytime the imagemagick formula from homebrew-core is updated. I've created #3948 to bump revisions so the error disappears.

In the meantime, you can `brew install -s php70-imagick`. This will install the formula from source instead of using a bottle, making the error disappear.

**Comment by fobin** [comment]
@alcaeus Thanks for the quick update. Works now!

**Comment by k-vladyslav** [comment]
Another alternative, which helped me (php 5.6):
```
$ brew uninstall php56-imagick
$ brew uninstall imagemagick
$ brew uninstall imagemagick@6
$ brew install --build-from-source homebrew/php/php56-imagick
```

Line 3 may be optional depending on if You have 6 and 7 or just one of them.

**Comment by beginnertutorials** [comment]
This simple command works for me:

`brew reinstall php56-imagick --build-from-source`

Source: [[Fixed] Mac OSX - Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so'](http://www.beginnertutorials.net/Fixed-Mac-OSX-Warning-PHP-Startup-Unable-to-load-dynamic-library-usr-local-opt-php56-imagick-imagick-so)

**Comment by yildizib** [comment]
@k-vladyslav 
works for me. thnx
