### ISSUE TITLE
Prebuilt php70-mcrypt appears broken

### ISSUE THREAD

**Issue by karlshea** [Homebrew/homebrew-php#3951]
## Description

Install caveats indicate "/usr/local/etc/php/7.0/conf.d/ext-mcrypt.ini was created" but the file isn't there.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.2
**Homebrew Version:**   | 1.1.9
**PHP Version in use:** | 7.0.15
**Xcode Version:**      | 8.2.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.15 (cli) (built: Jan 22 2017 08:51:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by karlshea** [comment]
Additionally, php-i returns "/usr/local/opt/php70-mcrypt/mcrypt.so doesn't appear to be a valid Zend extension" when I create the file myself

**Comment by karlshea** [comment]
`brew reinstall -fs php70-mcrypt` works just fine though, the file is created and the extension loads

**Comment by javian** [comment]
That file is not included in the bottle and create by the Formula when installed so I would guess this is a local issue and you got it to work when reinstalling.  I think the mistake you made when adding your own file was that you added it as a zend extension rather than a regular extension by using `zend_extension=<pathtoextension>` rather than `extension=<pathtoextension>`.

**Comment by orditeck** [comment]
Same issue here. Seems like an old one, see https://github.com/Homebrew/homebrew-php/issues/1940

`brew install php70-mcrypt` seems to have worked it but didn't create `/usr/local/etc/php/7.0/conf.d/ext-mcrypt.ini`

`brew reinstall -fs php70-mcrypt` did the job.

**Comment by javian** [comment]
This has now been corrected in the bottle.

**Comment by morrislaptop** [comment]
This just has happened to be on a fresh install?
