### ISSUE TITLE
libpng16.16.dylib error

### ISSUE THREAD

**Issue by TheadoreL** [Homebrew/homebrew-php#3961]
## Description

update to php71 and use php -v show php requires version 45.0.0 or later, but libpng16.16.dylib provides version 38.0.0

## Context and Logs

dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 45.0.0 or later, but libpng16.16.dylib provides version 38.0.0
Abort trap: 6

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.3 (16D32)
**Homebrew Version:**   | 1.1.9
**PHP Version in use:** | php71
**Xcode Version:**      | 8.2.1 (8C1002)

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 45.0.0 or later, but libpng16.16.dylib provides version 38.0.0
Abort trap: 6

**Build logs:**https://gist.github.com/1a04d89a6450fa63b135ad87b8a38da4

**Comment by javian** [comment]
The gist log is from php70 and seems to be ok. Did you post the right gist ?

**Comment by TheadoreL** [comment]
@javian yes I just generate by demo , i think my problem is ` dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib` can you give me some suggest

**Comment by javian** [comment]
@TheadoreL did you manage to solve this ? I would try to install php from source. `brew reinstall -s php71` to see if that solves it

**Comment by javian** [comment]
Closing issue in 2 weeks if no response.

**Comment by remy-actual** [comment]
I had the same issue tonight: 
```zsh
$ php -v
> dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 46.0.0 or later,
  but libpng16.16.dylib provides version 43.0.0
[1]    64122 trace trap  php -v
```

Tried quite a few fruitless things before @javian 's recommendation to reinstall from source with **`brew reinstall -s php71`** finally resolved the problem for me.

**Comment by javian** [comment]
Thanks for the feedback @remy-actual , the bottle for this formula needs to be regenerated which should solve the issue.
