### ISSUE TITLE
Can't locate API module structure `php56_module' in file /usr/libexec/apache2/libphp5.so: dlsym(0x7fb0bae03630, php56_module): symbol not found

### ISSUE THREAD

**Issue by jmevalentin** [Homebrew/homebrew-php#3985]
## Description
I  have had several issues over the past year which required a complete reinstall of homebrew and subsequent install of brew packages. I use it mostly for the development stack on my Mac: Apache, Mysql, PHP (and related libraries and tools such as xdebug). Recently, all of my local php sites stopped working and I discovered that my libphp5.so was missing. After frantically reading stackexchange writeups and following their reinstall directions (several times), I was able to get see the file downloaded to /usr/libexec/apache2/libphp5.so, but y pages still weren't loading. Running apachectl -t  produces the following error: 

`httpd: Syntax error on line 118 of /private/etc/apache2/httpd.conf: Can't locate API module structure 'php56_module' in file /usr/libexec/apache2/libphp5.so: dlsym(0x7fb0bae03630, php56_module): symbol not found`

I have the following line in my httpd.conf file: 

`LoadModule php56_module /usr/libexec/apache2/libphp5.so`

I must now run all of my sites in a virtualbox running ubuntu, which I wouldn't mind if i wasn't taking up more resources. Any suggestions on how to fix the issue?

Thanks.

JV

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.9.5
**Homebrew Version:**   | 1.1.7
**PHP Version in use:** | 5.6.29
**Xcode Version:**      | 6.2 (Build version 6C131e)

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Output of php -v:**
PHP 5.6.29 (cli) (built: Dec 30 2016 23:40:53) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
NOTE: running `brew gist-logs php56` produces 
`Error: No logs.`

**Comment by javian** [comment]
You need to use `LoadModule php5_module ...` and not `LoadModule php56_module`.

**Comment by jmevalentin** [comment]
That was it, thanks javian!
