### ISSUE TITLE
How to install mbstring?

### ISSUE THREAD

**Issue by mityukov** [Homebrew/homebrew-php#3992]
## Description

Hi, I have php70 installed with homebrew. Can I enable mbstring for this PHP installation somehow?
I can't see appropriate formulae, nor it's mentioned in the `brew options php70` :/

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.3 (16D32) / Sierra
**Homebrew Version:**   | 1.1.9
**PHP Version in use:** | 7.0.15 (cli) (built: Jan 22 2017 08:51:45)

**Comment by alcaeus** [comment]
`mbstring` is installed automatically, see https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb#L203. You can run `php -m | grep mbstring` to make sure it is available.

**Comment by mityukov** [comment]
Thank you for the answer. It's that I've got it all wrong. I thought that mbstring would automagically make all my `strtolower`, `trim` and so on to work with utf8. It turns out, however, that adding `mb_` prefix is still necessary :-)

**Comment by alcaeus** [comment]
Ah, yeah. That's not the case.
