### ISSUE TITLE
The future of the PHP tap and formulas, please give your input

### ISSUE THREAD

**Issue by javian** [Homebrew/homebrew-php#4005]
This has turned into a slightly longer text than I would have hoped but I would like to get some feedback. Using an issue might not be the best way to collect this kind of information but it is a start and I'd like to keep it as open as possible for people who input. I also don't know how many people in the community that this will touch but there are other ways of reaching out in case it is needed. The text is not super structured but I have been sitting on this for a while to try and get some input and at this stage it was more important to get it our rather than it being perfect so if something doesn't make sense that's probably why =)

I’ve been thinking about how we can move the PHP tap forward since I currently feel that the code is a bit messy and that the main core formulas really belong in the upstream brew core project and I’ve had a short discussion with Mike about it and he agrees that the “popular” packages should/could be moved across. As I see it that would mean PHP 5.6, 7.0 and 7.1 and any subsequent version released of PHP. Potentially it could be discussed if we should go further back in the PHP release timeline but as we’ve already discussed boneyarding the php 5.3 and 5.4 formulas due to them not being supported upstream then it is probably better to spend that time moving forward.

To be able to move the main php formulas into core we would have to remove the abstractions and make the PHP versions into standalone formulas as well as adopting the new version format used in brew ie.  **php@7.0** . I think this would not be a big issue since the formula code does not change very often and we would also gain the following benefits

_Advantages_
- Easier to read Formula code
- Easier to read if a formula has been updated
- Revisions are currently the only mechanism to upgrade a formula and it is not very clear whether an extension has been updated due to the version abstraction currently in place.
- More maintainers that can merge and maintain updates
- Possibility of creating a new `:php` dependency that would also support versions similar to other programming languages in brew. 
- Possibility of creating core code to support phars and extensions.

_Drawbacks_
- It would increase the time it would take to commit a new PHP version with the current structure but I think that the formula clarity would be preferred over saving a little bit of time. This could of course be changed as will be outlined below.
- Code duplication since a lot of code in the php formulas is shared

The other thing that would need to happen is to decide on how we would want the PHP versions/SAPIs to work in brew. Currently we are supporting the main formula phpXX.rb which includes several different SAPIs (cli, apache, fpm etc) and there has been a previous attempt to split these into separate files which I still think might be a good idea but introduces other challenges. A suggestion could look like this

As I see it the SAPIs we want to support are

- CLI
- phpdbg
- Apache
- FPM
- CGI

CGI is as far as I can tell discouraged to use at least in a production environment http://php.net/manual/en/install.unix.commandline.php . This would not probably affect developer machines necessarily and about 130 people have installed/upgrade it over the past 30 days so I would suggest we keep it and not build it by default as it is now.

Another current hurdle is thread safety which goes hand in hand with the pthreads extension. This could potentially have its own Formula (php-zts@7.0…) since it will break the CI for many php modules if thread safety is turned on which currently happens in the build bot. The usage of a thread safe binary is around 2000 installs over the last two months.

From here on there are 2 paths moving forward as I see it.

Move away from using phpXX.rb and create a Formula for each SAPI
OR
Create an additional set of files for the SAPIs that can be used with thread safety

Each SAPI can be installed separately. For each PHP version released this would then create 4 or 5 files (+ however many TS files) to update when a new version is released of PHP.

Another option would be to build all SAPIs in the main phpXX formula by default
If all SAPIs are bottled it would not require a build from source for that reason alone
Drawback is that more diskspace would be used on the client machines - does this matter ?
Default compile times would be longer - does this matter ?
You could let SAPIs be controlled by options to decrease compile time and diskspace but we would the lose the benefit of bottles.

_Discussion points_
Is the current list of the 5 SAPIs + TS (thread safety) sufficient or should add/remove anything else ?
Should we have 1 formula (+1 formula for all TS sapis) that contains and compiles all SAPIs in one go ?
* Easier to maintain and upgrade
* Bottles all SAPIs so that people who needs them don’t have to recompile unless they want other options turned on/off
What should we do with the current phpXX.rb formulas ?
* Keep them and create dependencies to the currently include SAPIs
* Migrate them to CLI with instructions on how to install the other SAPIs 
How do we deal with core extensions with a seperate formula
* To not end up having a set of each SAPI with their own list of core extension I would suggest that we keep the extensions and build them. This could be done in a way that you can opt not to load a certain extension at build time

How do we deal with core extensions that are currently built as part of php ?
Should we create a config file for each SAPI by default ?
Should we build both an Apache 2.2 and a 2.4 SAPI or just stick to 2.4 ?
Should we consider versioning the compiled binaries to allow for multiple versions to be installed and upgraded side by side ? I believe this is what the Debian project has done see https://wiki.debian.org/PHP#For_packagers_of_PHP_applications.2Fmodules.2Flibraries
* This would produce a set of binaries like php70-cli, php56-cli etc. that would not conflict on upgrades making it easier to use multiple versions side by side
Drawback that users would have to alias php or that a supplementary program like the brew-php-switcher would be needed to easily manage the active versions

**Core extensions**
The current list of core extensions that are built outside of the PHP formula are
php71-gmp.rb
php71-intl.rb
php71-mcrypt.rb (will be replaced in PHP 8 with libsodium)
php71-opcache.rb
php71-pcntl.rb
php71-pdo-dblib.rb
php71-pdo-pgsql.rb
php71-pspell.rb
php71-snmp.rb
php71-tidy.rb

Pcntl is already built in the main php formula so requiring a separate formula for this would not be necessary and only creates more work.

_Discussion points_
Should we remove the pcntl extension formula and always compile it ? 
Or remove it as a standard part of the formula ?
Is there any advantage of keeping it as a separate formula ?
Should we merge all of the modules back into core ?
Less to do when a new version is released
Module can easily be turned off in config if not used

**Modules**
One of the issues with external (non php core sources) modules is that they currently depend on the version of PHP specific to them meaning that if you are using another PHP version you need to unlink and link the correct php version to be able to install any updates. This causes frustration and I’m hoping this is something we could change and adopting the debian way of dealing with php versions would solve this. Are there any other ideas on how this could be done ?

**When could we start ?**
I would suggest that we use PHP 7.2/8.0 when the first alpha is released and use it as a test platform and implement the changes based on the decisions coming out of the above discussion with the new file structure and versioning scheme and then gradually start rolling it out across the existing php versions once we are happy with how 7.2 looks. If the 7.2 releases drags out then this could be reconsidered.

**Comment by ablyler** [comment]
I'm a big fan of moving to separate formulas for each SAPIs.  I started working on that a long time ago, but never finished.  I'm also fine with removing the abstraction for the PHP version + checksums.  We can accomplish the changing of this information via code pretty easily.

I need to look into this some more, but my gut says to not reinvent the wheel.  We should look at how Centos / Ubuntu / name your favorite distro handle PHP and come up with a similar strategy for where to draw the line with the formulas.

**Comment by javian** [comment]
@ablyler I agree - reinventing the wheel should be avoided if possible. Ubuntu breaks out a lot of the core modules so there might be 15-20 packages for every new release which is a bit much imo but I also think that the use case for Ubuntu is more geared towards servers where you might want to turn off modules that you are not using whereas we might not be as picky in the PHP tap since its mainly used by developers.

How would you suggest we deal with dependencies to the modules when using multiple SAPIs ie. which SAPIs should they depend upon ?

**Comment by josegonzalez** [comment]
We used to do this way back when, and it resulted in a lot of duplication, hence my move to the `AbstractPHP` formula.

I'm ambivalent towards a change. Whatever makes it easy for you all to maintain gets a 👍 from me though.

One thing you might do to figure out default extensions is look at what heroku provides. I'd also love to have `intl` as default, but thats a pita to get working properly with PHP core IIRC.

**Comment by ablyler** [comment]
@javian I believe that Ubuntu / Gentoo will install the CLI if you attempt to install a PHP module without any SAPI installed.  I can check tonight.

@josegonzalez yeah, the abstract does make life easier for us. @javian what is the reason for moving away from it? Is it just to allow the moving of these formulas to homebrew proper?

**Comment by javian** [comment]
@ablyler I would guess so too which makes a lot of sense. Since most people who use php from homebrew is working with some kind of development you would expect that everyone uses the cli to some extent so I would suggest that the cli is the only dependency and other SAPIs can be installed as needed.

**Comment by javian** [comment]
@josegonzalez can you recall what was related to the pita of getting intl built by default ? Might there be any record of it in the git logs ?

**Comment by yurikoles** [comment]
So what is the plan now? I'm volunteering to work on this ticket.
Do we need to share some code in OOP?

**Comment by josegonzalez** [comment]
@javian has to do with linking to ICU iirc. It should be in the logs for this repo.

**Comment by yurikoles** [comment]
@josegonzalez, sorry I didn't get it. I see some commits regarding ICU, but what I need to see there?

**Comment by javian** [comment]
@josegonzalez I think this is it https://github.com/Homebrew/homebrew-php/commit/ea9c407ba4231a78b1093d3541575b214e3106d0 - should be easy to check the current status of this @yurikoles . I'm quite busy irl at the moment and probably won't have much time to look at this until easter.

**Comment by javian** [comment]
So the way Ubuntu does PHP is that they install the binaries with an appended version and then there's a seperate mechanims using `update-alternatives` that selects the "right" php version for you and sets up the aliases. As far as I know there's no equivalent in homebrew unless you use `:keg_only` and then link the formulas with some kind of script or manually.

**Comment by javian** [comment]
Ubuntu contains 68 packages that are related to php70. A number of these a modules are the extensions that are bundled with the php source. We have 10 modules as outlined above that sit outside of the core package and I would think that the main argument for that is that they depend on external formulas so if the external formula is updated we don't have to recompile all of php to make it work.

This might have been an idea that was introduced before the bottles existed in homebrew but even if it was decided to include more of the extensions in the core formula then its likely that more revision would need to made between each versioned release. I don't think we need to be as thorough as ubuntu since the homebrew php will not be used in a production server environment so including more modules in core should be fine imo.

**Comment by javian** [comment]
I linked to https://github.com/Homebrew/homebrew-core/pull/16067 which I now consider the next generation php Formula which eventually will be included in core if we can get close enough to something that actually works in a satisfying way. Just wanted to post a reminder here since I haven't received any feedback in that issue =)

**Comment by MikeMcQuaid** [comment]
> What will happen to the php tap is yet to be decided but seeing the direction the formula above is taking it will change quite drastically.

The way things are going I think it is somewhat decided: at some point in the future (probably early 2018) this tap will need to be migrated to a non-Homebrew organisation tap. Before that point we're happy to have many of the formulae in this tap (particularly those in https://brew.sh/analytics/install-on-request/) migrated into Homebrew/homebrew-core. After that point https://jenkins.brew.sh will not be available to this tap.

The same approach is being taken with Homebrew/homebrew-science and Homebrew/homebrew-nginx (the last remaining community taps). With hindsight, it was a mistake on my part to bring all these taps into the Homebrew organisation: the main Homebrew maintainers are not working on maintaining them so the quality, style and support has drifted pretty far from Homebrew/homebrew-core.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
