### ISSUE TITLE
MongoDB: Symbol not found [basic_globals]

### ISSUE THREAD

**Issue by dn5** [Homebrew/homebrew-php#4006]
## Description
While setting up local environment for personal project, I've found out that the installing MongoDB extension creates an error for PHP extension config. Mongo-ext is installed through `brew install php70-mongodb`.

## Context and Logs
- Install MongoDB for PHP7 (`brew install php70-mongodb`)
- Run `php -v`
- Output:
```
~ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mongodb/mongodb.so' - dlopen(/usr/local/opt/php70-mongodb/mongodb.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mongodb/mongodb.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mongodb/mongodb.so' - dlopen(/usr/local/opt/php70-mongodb/mongodb.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mongodb/mongodb.so in Unknown on line 0
PHP 7.0.15 (cli) (built: Feb 15 2017 10:28:27) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.2
**Homebrew Version:**   | 1.1.0 (revision @ `a3f81`)
**PHP Version in use:** | 7.0.15
**Xcode Version:**      | Latest update for v8

**Output of gcc -v:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
````

**Output of php -v:**
*Posted above* at issue description.

**Build logs:** 
https://gist.github.com/dn5/657247ba8efec4a4293233bb6b27796f

**Comment by javian** [comment]
@dn5 my guess would be that it is not compatible with thread safety. Can you try to `brew reinstall -s php70-mongodb` to compile it from source and see if that works ? The bottle is compiled against a non thread safe php.

**Comment by dn5** [comment]
Oh, blame me @javian. It's correct, lately I have been experimenting with CLI pthreads (ZTE) for PHP (I know, I know ...), and seems that since then it was breaking the mongodb extension.

Okay let's see:
```
$ brew reinstall php70 --with-thread-safety --with-postgresql --with-homebrew-curl
$ brew reinstall php70-opcache php70-mcrypt php70-pthreads php70-xdebug --build-from-source
$ brew reinstall php70-memcached --build-from-source --HEAD
$ brew reinstall -s php70-igbinary
$ brew reinstall -s php70-mongodb
```

Result:
```
$ php -v
PHP 7.0.15 (cli) (built: Feb 22 2017 14:13:48) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

``` 
$ php -m | grep "mongo\|pthread"
mongodb
pthreads
``` 

Everything works flawlessly and threading work including the Mongo ext. What was up with that? Was it really compatibility issue and what sort of?

**Comment by javian** [comment]
@dn5 As far as I know the exposed functions between the thread safe php and the non thread safe php is different and a module compiled for one does not work with the other as far as I know. Glad you got it working!

**Comment by javian** [comment]
@dn5 and feel free to close the issue if you are satisfied with the response =)

**Comment by dn5** [comment]
Make sense. Totally forgot about it. Thank you anyway. Closing the issue since it's resolved. 

Cheers 🎉
