### ISSUE TITLE
Error: /usr/local/opt/php56 is not a valid keg

### ISSUE THREAD

**Issue by amorino** [Homebrew/homebrew-php#4009]
## Description

When I try to install php56 I get the following error: 

## Context and Logs

Error: /usr/local/opt/php56 is not a valid keg

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.3
**Homebrew Version:**   | Homebrew 1.1.10
**PHP Version in use:** | 5.6
**Xcode Version:**      | 8.2.1

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 5.6.28 (cli) (built: Dec  6 2016 12:38:54)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
Error: No logs.

**Comment by yurikoles** [comment]
@amorino have you tried `brew gist-logs php56`?

**Comment by coreation** [comment]
+1 same issue atm, brew gist-logs php56 results in "No logs."

**Comment by javian** [comment]
Does `brew doctor` give you any advice on what to do ?

**Comment by javian** [comment]
Could you also try
`brew uninstall php56`
and then reinstall
`brew install php56`
and see if that works ?

**Comment by javian** [comment]
Could you also try `brew prune` and see if that resolves the issue ?

**Comment by javian** [comment]
@amorino it seems that for some reason there directory is left behind. Can you try to examine

`/usr/local/opt/php56`

and check the contents there ? If its empty or doesn't have any files that you need then remove it

`rm -rf /usr/local/opt/php56`

Then just do :

`brew install php56`

and it should work as expected.

**Comment by javian** [comment]
Closing due to no response.

**Comment by adeonir** [comment]
Removing folder /usr/local/opt/php56 and reinstalling worked.
