### ISSUE TITLE
libphp7.so requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0

### ISSUE THREAD

**Issue by tfe2012** [Homebrew/homebrew-php#4015]
Parameter | Value
--------- | ------------------
**OS X Version:**       | _your OS X version_
**Homebrew Version:**   | _your Homebrew version_
**PHP Version in use:** | _your PHP version_
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.15 (cli) (built: Feb 27 2017 10:26:32) ( NTS DEBUG )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

I run:

brew install php70 --with-apxs2 --with-apache --with-gmp --with-imap --with-tidy --with-debug --with-httpd24 --build-from-source

after that run apachectl -t

httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Library not loaded: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib\n Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n Reason: Incompatible library version: libphp7.so requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0

**Comment by javian** [comment]
@tfe2012 does it work with the homebrew apache ?

**Comment by tfe2012** [comment]
What do you mean ?

**Comment by tfe2012** [comment]
apachectl -t return error

**Comment by tfe2012** [comment]
brew install php70  --with-apache

return same probleme

**Comment by javian** [comment]
It looks like apache is reading the config that comes with macOS and not the one that's included with homebrew. If you `which apachectl` it should tell you the path to the script to see if you are using macOS apachectl or homebrews.

**Comment by tfe2012** [comment]
/usr/local/bin/apachectl

**Comment by javian** [comment]
Ok that's homebrew then. I don't get why it tries to read the macos httpd config though - it should read the one in `/usr/local/etc/apache2/...` .

**Comment by javian** [comment]
How about `grep HTTPD /usr/local/bin/apachectl` ?

**Comment by tfe2012** [comment]
michail$ grep HTTPD /usr/local/bin/apachectl
HTTPD='/usr/local/Cellar/httpd24/2.4.25/bin/httpd'
    $HTTPD -k $ARGV
    $HTTPD -t
    $HTTPD "$@"

**Comment by koizorapp** [comment]
@javian 你好! 我也遇到了同样的问题。我使用的是  brew install php71 --with-httpd24  ,安装成功以后 我又通过 brew uninstall --ignore-dependencies httpd24 卸载了apache ，我使用 which apachectl 得到的是/usr/sbin/apachectl。 不知道我这个怎么解决，错误依然是那样。拜托！

**Comment by tfe2012** [comment]
Reason: Incompatible library version: libphp7.so requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0


$ which apachectl   

return:

/usr/sbin/apachectl


$ grep HTTPD /usr/sbin/apachectl 
HTTPD='/usr/sbin/httpd'
    $HTTPD -t
    $HTTPD "$@"
