### ISSUE TITLE
How do I install a specific version of PHP?

### ISSUE THREAD

**Issue by rquadling** [Homebrew/homebrew-php#4051]
## Description

I need to install a specific version of PHP (5.4.32) to do some testing. Travis only has the latest releases. A client can't upgrade and is reporting problems with one of the packages that is passing all tests fine on the latest (and last) PHP 5.4.45.

I can unlink my current PHP70 and install PHP5.4.45, but I can't see the magic I need to cast to install 5.4.32.

Am I missing something obvious?

## Context and Logs

**macOS version:**
```
10.12.3
```

**Homebrew version:**
```
Homebrew 1.1.11
Homebrew/homebrew-core (git revision cc9f7; last commit 2017-03-20)
```

**PHP version in use:**
```
7.0.15
```

**Xcode version:**
```
Xcode 8.2.1
Build version 8C1002
```
**Output of `gcc -v`:**
```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**
```
php -v
PHP 7.0.15 (cli) (built: Jan 22 2017 08:51:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.8, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by javian** [comment]
It is not possible in brew. You can do it with some manual work though. 

I would suggest that you copy the formula file `php54.rb` and hardcode the url and sha and version to the version that you want to use in the new formula file. You can keep the file in the Formula directory without it being affected by other upgrades.

**Comment by rquadling** [comment]
Thank you.
