### ISSUE TITLE
Arcanist.rb has a very old stable

### ISSUE THREAD

**Issue by aleb** [Homebrew/homebrew-php#4055]
The arcanist team does releases by pushing to the `stable` branch, not by creating a tag or by creating a release in github. This happens weekly. The arcanist installed by the arcanist.rb formula is very very old and does not work anymore with recent phabricator instances.

Please tell me if you need more info.

**Comment by aleb** [comment]
I tried something like this, but it does not work:

```
diff --git a/Formula/arcanist.rb b/Formula/arcanist.rb
index 26df7495..3a96827b 100644
--- a/Formula/arcanist.rb
+++ b/Formula/arcanist.rb
@@ -5,12 +5,10 @@ class Arcanist < Formula
   homepage "https://secure.phabricator.com/book/phabricator/article/arcanist/"
 
   stable do
-    url "https://github.com/phacility/arcanist/archive/conduit-5.tar.gz"
-    sha256 "81a9599f0799f4a2b77a01ddb35275894b82d8e51f437b51f9342affd029aa8b"
+    url "https://github.com/phacility/arcanist.git", :branch => "stable"
 
     resource "libphutil" do
-      url "https://github.com/phacility/libphutil/archive/conduit-5.tar.gz"
-      sha256 "a4bc5d2e80ca3c127d26d7dd74ad4b979841c7a648a2891ef2affd6876af8b2b"
+      url "https://github.com/phacility/libphutil.git", :branch => "stable"
     end
   end
```

```
$ brew install ./arcanist.rb
Error: undefined method `head?' for nil:NilClass
[...]
```

**Comment by alcaeus** [comment]
There has been discussion about this in https://github.com/Homebrew/homebrew-php/pull/3731#issuecomment-256469360 and a suggested solution in https://github.com/Homebrew/homebrew-php/pull/3864#issuecomment-268447510.

**Comment by paladox** [comment]
I think #4056 will fix this.

**Comment by paladox** [comment]
You could run brew install arcanist --head

**Comment by javian** [comment]
The PR for updating arcanist have been merged - can you test it and see if it works now ?

**Comment by tuwannu** [comment]
This works well for me.
