### ISSUE TITLE
Error: /usr/local/opt/php71 is not a valid keg

### ISSUE THREAD

**Issue by feivorid** [Homebrew/homebrew-php#4060]
when I try to install php71  show the error     **Error: /usr/local/opt/php71 is not a valid keg** ;

and next I try  : 
```shell
brew tap homebrew/homebrew-php
brew tap homebrew/versions
```
and so on  
but it does not work too!    

so  need help  .

**Comment by javian** [comment]
Can you try

`brew uninstall php71`
`brew prune php71`

and then retry the install

`brew install php71`

and see if that works.

**Comment by feivorid** [comment]
@javian    yes   I tried  ,but it dose not work too ;

**Comment by javian** [comment]
Can you paste the output of `brew config` ?

**Comment by feivorid** [comment]
@javian    

▶ brew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: edff63105ab5f1d366e089774e4dc5c832d256a3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A

**Comment by javian** [comment]
@feivorid just to exclude brew (its not been updated for 3 weeks on your machine) can you `brew update`twice and then run `brew upgrade` and try again ?

**Comment by javian** [comment]
I'm not sure that advice is solid now that I think of it since if you're not running as a developer you will only download the versioned releases.

**Comment by javian** [comment]
What does `brew doctor` output ?

**Comment by javian** [comment]
Could you also try to run `brew install php71 --debug` ?

**Comment by feivorid** [comment]
@javian  
`brew doctor`
Your system is ready to brew.

`brew install php71 --debug`
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php71.rb
Error: /usr/local/opt/php71 is not a valid keg
/usr/local/Homebrew/Library/Homebrew/keg.rb:185:in initialize
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in new
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in block in install
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in each
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in install
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in <main>

and I tried `brew update` twice and then run `brew upgrade` and run `brew install php71` , show same error !  

thank u for your time !

**Comment by erlipknot** [comment]
same error here, exactly the same

brew install php71 --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php71.rb
Error: /usr/local/opt/php71 is not a valid keg
/usr/local/Homebrew/Library/Homebrew/keg.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'

and I tried brew update twice and then run brew upgrade and run brew install php71 , show same error !

Thanks!!!!

**Comment by javian** [comment]
The error comes from https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb#L185 suggesting that something is up with paths or that brew is confused on that topic. Would you be comfortable in debugging that section and see what the variables contain before the raise is executed ?

**Comment by feivorid** [comment]
e ,    I do not understand  !  your mean  I should add some variables in my paths?

**Comment by bvong** [comment]
Same error for me, I fixed it by **remove the broken folder /usr/local/opt/php71** :
`rm -rf /usr/local/opt/php71`

Then just retry : 
`brew install php71`

It works well for me !

**Comment by javian** [comment]
@bvong do you know what the content in that directory was when you removed it ?

@feivorid can you try this solution as well ?

**Comment by bvong** [comment]
It contains only empty folder

**Comment by javian** [comment]
@bvong thanks for the feedback.

**Comment by feivorid** [comment]
yes ,  it works !

thanks so much  @javian  @bvong

**Comment by luozhang002** [comment]
@bvong  why you are so 牛逼，perfect!

**Comment by kasperpeulen** [comment]
Errors message should still improve 🙄

**Comment by Teddy-Zhu** [comment]
@bvong thx , the same problem , try to rm the folder , it works

**Comment by bandanh** [comment]
I had the same problem with 7.2 and deleting fixed it:
The content of this folder where:
- php72
- php72/var
- php72/var/log

But I think its worth to mention, php72 was a folder and not a symlink, also the owner was `root:staff` and not `myuser:staff`
