### ISSUE TITLE
Cannot install php71-redis

### ISSUE THREAD

**Issue by soldovskij** [Homebrew/homebrew-php#4061]
## Description

Cannot install php71-redis.
When try 
`brew install php71-redis --without-homebrew-php`
or any php71-* in terminal see 
`Error: Unsupported PHP API Version`

I think this problem in 
https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php-extension.rb, because in this file has only that versions: 
`{ 53 => 20090626, 54 => 20100412, 55 => 20121113, 56 => 20131106 }`.

**phpize -v output:**
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.12.3-x86_64_
**Homebrew version:**   | _1.1.11php_
**PHP version in use:** | _7.1.3_
**Xcode version:**      | _8.2.1_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.3 (cli) (built: Mar 23 2017 13:57:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by javian** [comment]
@soldovskij you are not using the php that comes with macos and must have installed it in some other way. php 5.6 is what ships with Sierra so using `--without-homebrew-php` is unsupported.

How did you install php on your machine ?

**Comment by SMillerDev** [comment]
I'm thinking 364b98ce135403b2b26f83d70ea73014cd891557 would've fixed this.
