### ISSUE TITLE
Installing php71 and composer in the same brew install command fails

### ISSUE THREAD

**Issue by lachieh** [Homebrew/homebrew-php#4071]
## Description
Not really sure if this is a homebrew-php issue or a homebrew issue, but if you run the following command, it fails:
`brew install php71 composer`

This is because it doesn't recognize that php71 was installed immediately prior.

**Log from `brew install php71 composer`:**
```bash
==> Installing php71 from homebrew/php
==> Downloading https://homebrew.bintray.com/bottles-php/php71-7.1.3_14.sierra.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/php71-7.1.3_14.sierra.bottle.tar.gz
==> Pouring php71-7.1.3_14.sierra.bottle.tar.gz
==> Caveats
    [...trimmed...]
==> Summary
🍺  /usr/local/Cellar/php71/7.1.3_14: 345 files, 39.7MB
==> Installing composer from homebrew/php
==> Installing dependencies for homebrew/php/composer: php70
==> Installing homebrew/php/composer dependency: php70
Error: Cannot install homebrew/php/php70 because conflicting formulae are installed.

  php71: because different php versions install the same binaries.

Please `brew unlink php71` before continuing.
```

If you swap the order around, you get the following:

**Log from `brew install composer php71`:**
```bash
==> Installing composer from homebrew/php
==> Installing dependencies for homebrew/php/composer: php70
==> Installing homebrew/php/composer dependency: php70
==> Downloading https://homebrew.bintray.com/bottles-php/php70-7.0.17_9.sierra.bottle.tar.gz
Already downloaded: /Users/lachlanheywood/Library/Caches/Homebrew/php70-7.0.17_9.sierra.bottle.tar.gz
==> Pouring php70-7.0.17_9.sierra.bottle.tar.gz
==> Caveats
    [...trimmed...]
==> Summary
🍺  /usr/local/Cellar/php70/7.0.17_9: 333 files, 38.8MB
==> Installing homebrew/php/composer
==> Downloading https://homebrew.bintray.com/bottles-php/composer-1.4.1.sierra.bottle.tar.gz
Already downloaded: /Users/lachlanheywood/Library/Caches/Homebrew/composer-1.4.1.sierra.bottle.tar.gz
==> Pouring composer-1.4.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/composer/1.4.1: 5 files, 1.8MB
==> Installing php71 from homebrew/php
Error: Cannot install homebrew/php/php71 because conflicting formulae are installed.

  php70: because different php versions install the same binaries.

Please `brew unlink php70` before continuing.
```

Running the first command will run successfully, but because composer requires php70, the second command will fail until `brew unlink php70` is run.

**Comment by yurikoles** [comment]
I can confirm this issue.

**Comment by javian** [comment]
The reason for this is the somewhat lacking dependency/requirement check in https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb since it only checks for previously installed formula. I'm not sure if there is a way to detect that a formula is about to be installed but I'm open to modifying it since it should preferably not be done this way.

**Comment by lachieh** [comment]
That's fair. Honestly, I'm not sure how other packages handle this so I don't have a solve, it just makes installs on new setups a whole 15 keystrokes longer which is the end of the world, and everyone should panic, obviously.

**Comment by javian** [comment]
@lachieh =D - we need to rewrite the requirement code. I'll give it a go over the weekend because it does also introduce other "bugs" and behaviour that might not want to see.

**Comment by JohnnyWalkerDesign** [comment]
Just wondering. Is there a reason why composer has a dependency requirement on php70 and not php71? 71 is the current stable version of php after all.

**Comment by javian** [comment]
@JohnnyWalkerDesign I think this is a leftover from when we published the formula for the pre-stable versions of php 7.1. We can probably change that now but then doing `brew install php70 composer` would not work either so there's still an issue with the dependency. I would be tempted to remove the php dependency completely from the composer formula since I believe it might not be necessary anymore and replace it with a custom requirement.

**Comment by JohnnyWalkerDesign** [comment]
@javian Awesome. If you can remove the dependency I guess that would solve everything.

**Comment by javian** [comment]
The dependency is now gone and replaced with a caveat.
