### ISSUE TITLE
Error when building php 5.6 --with-libmysql

### ISSUE THREAD

**Issue by AzizSaleh** [Homebrew/homebrew-php#4076]
## Description

I am trying to build php 5.6 (also tried with 5.5 with similar outcome):

$brew install php56 --with-httpd24 --with-postgresql --with-libmysql

The error starts after make:

```
In file included from /private/tmp/php56-20170330-64471-17st5zb/php-5.6.30/ext/mysqli/mysqli_api.c:34:
ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^
In file included from /private/tmp/php56-20170330-64471-17st5zb/php-5.6.30/ext/mysqli/mysqli_prop.c:31:
ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^
1 error generated.
1 error generated.
make: *** [ext/mysqli/mysqli_prop.lo] Error 1
make: *** [ext/mysqli/mysqli_api.lo] Error 1
In file included from /private/tmp/php56-20170330-64471-17st5zb/php-5.6.30/ext/mysqli/mysqli_nonapi.c:33:
ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^
1 error generated.
make: *** [ext/mysqli/mysqli_nonapi.lo] Error 1
In file included from /private/tmp/php56-20170330-64471-17st5zb/php-5.6.30/ext/mysqli/mysqli_report.c:28:
ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^
In file included from /private/tmp/php56-20170330-64471-17st5zb/php-5.6.30/ext/mysqli/mysqli_fe.c:32:
ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^
1 error generated.
make: *** [ext/mysqli/mysqli_report.lo] Error 1
1 error generated.
make: *** [ext/mysqli/mysqli_fe.lo] Error 1
```
Raw: https://gist.githubusercontent.com/anonymous/85a8811b7603c921ee455db8f7684e4f/raw/08084247a2a77a0afafb99b87fa5e4acb2683a9e/02.make

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _Sierra (10.12.3)_
**Homebrew version:**   | _1.1.11_
**PHP version in use:** | _5.6.30_
**Xcode version:**      | _Not Installed_

**Output of `gcc -v`:**
_Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin_

**Build logs:** _https://gist.github.com/85a8811b7603c921ee455db8f7684e4f_

Note that if I remove --with-libmysql it works fine.

**Comment by javian** [comment]
This might be a rock that no one has turned for quite some time. It looks like the code references to a mysql installation in homebrew but its not listed as a dependency. It does look like you have it installed so there's probably is an issue in the Formula somewhere.

**Comment by sbahr001** [comment]
Any update? My work uses mysql_connect :(

**Comment by javian** [comment]
I've submitted a fix for this now since php was lacking the mysql dependency. Will merge later today.

**Comment by javian** [comment]
This should fix it - have a go and test it. I'm closing the ticket but feel free to open it again if you keep having issues.
