### ISSUE TITLE
Cannot find config.m4.  Make sure that you run '/usr/bin/phpize' in the top level source directory of the module

### ISSUE THREAD

**Issue by joygo1943g** [Homebrew/homebrew-php#4088]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _your macOS version (output of `sw_vers -productVersion`)_
**Homebrew version:**   | _your Homebrew version (output of `brew --version`)_
**PHP version in use:** | _your PHP version (output of `/path/to/php -v`)_
**Xcode version:**      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
_result of the CLI output_

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
@joygo1943g did you miss to put the information in the issue ? There's nothing to go on here apart from the title which doesn't give any info.
