### ISSUE TITLE
php5[5-6] fails on libevent w|wo php5[5-6]-event

### ISSUE THREAD

**Issue by BenjaminHCCarr** [Homebrew/homebrew-php#4104]
## Description
Both php55 and php56 fail in `php5x-http/http.so` whether php-event is installed or not. 

I was not wedded to `php55` so thought maybe as I had not pinned things I should move to `php56` to solve the problem; it did not.

This looks remarkably similar to Homebrew/homebrew-php#3991 though installing `php56-event/2.2.1` did not fix this. It looks like the same/similar patch from Homebrew/homebrew-php#3993 needs to be applied to `php{54-56}-http` at least.

libevent is the current bottled version `2.1.8`:
```
brew info libevent
libevent: stable 2.1.8 (bottled)
Asynchronous event library
http://libevent.org
Conflicts with: pincaster
/usr/local/Cellar/libevent/2.1.8 (847 files, 2.2MB) *
  Poured from bottle on 2017-01-31 at 14:54:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libevent.rb
==> Dependencies
Build: autoconf ✔, automake ✔, doxygen ✔, libtool ✔, pkg-config ✔
Required: openssl ✔
```

php55:
```
$ php -i
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-http/http.so' - dlopen(/usr/local/opt/php55-http/http.so, 9): Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/opt/php55-http/http.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-http/http.so' - dlopen(/usr/local/opt/php55-http/http.so, 9): Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/opt/php55-http/http.so
  Reason: image not found in Unknown on line 0
```
php56:
```
$ php -i
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-http/http.so' - dlopen(/usr/local/opt/php56-http/http.so, 9): Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/opt/php56-http/http.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-http/http.so' - dlopen(/usr/local/opt/php56-http/http.so, 9): Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/opt/php56-http/http.so
  Reason: image not found in Unknown on line 0
phpinfo()
PHP Version => 5.6.30
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |  10.11.6
**Homebrew version:**   | Homebrew 1.1.12-24-gd84655efb, Homebrew/homebrew-core (git revision f5bd5; last commit 2017-04-07)
**PHP version in use:** |  PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:18) 
**Xcode version:**      |  Xcode CLT 8

**Output of `gcc -v`:**
```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**
```
php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-http/http.so' - dlopen(/usr/local/opt/php56-http/http.so, 9): Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/opt/php56-http/http.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-http/http.so' - dlopen(/usr/local/opt/php56-http/http.so, 9): Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/opt/php56-http/http.so
  Reason: image not found in Unknown on line 0
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:18) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```
---
```
ls -l /usr/local/opt/libevent/lib/libevent-2.1.6.dylib
-r--r--r--  1 benc  admin  247844 Apr  8 00:14 /usr/local/opt/libevent/lib/libevent-2.1.6.dylib
```
---
```
$ brew list | grep php56
php56
php56-apcu
php56-event [added to try to force the libevent switch from Homebrew/homebrew-php#3993]
php56-http
php56-igbinary
php56-intl
php56-lz4
php56-lzf
php56-mcrypt
php56-memcached
php56-opcache
php56-propro
php56-raphf
php56-xdebug
php56-yaml
```

**Comment by BenjaminHCCarr** [comment]
Side note, the traditional workaround works:
`brew reinstall -s php56-event php56-http`
but a formula/bottle fix would be better.

**Comment by javian** [comment]
Thanks for the report @BenjaminHCCarr ! If you notice that a build from source solves the issue we need to regenerate the bottles for the formula. You can help doing a pull request with an added (or increased) revision number. You can see an example here https://github.com/Homebrew/legacy-homebrew/pull/47430/files . Would you mind taking that on ?

**Comment by BenjaminHCCarr** [comment]
Done, oddly it wouldn't let me do 4 patches on one PR for some reason. So fortunately/unfortunately you get four PRs.

**Comment by BenjaminHCCarr** [comment]
Oh, one other comment; you said to look at:

https://github.com/Homebrew/legacy-homebrew/pull/47430/files

But when I was look for examples in the `homebrew-php` Formulas; the `revision X` was in the bottle section:
https://github.com/Homebrew/homebrew-php/blob/master/Formula/php55-gmp.rb

I did it the way you mentioned, after `sha256`/`version`,  and it might just be the bot rebuild count in the `bottle` stanza. thoughts? Or has this changed over time?

**Comment by javian** [comment]
@BenjaminHCCarr the general rule is never to touch the bottle block since it is automatically updated and generated by the brewbot. Any user initiated revision should be in the place you put it, after the sha. Thanks for putting in the PRs! Can you check that everything seems ok now ?

**Comment by BenjaminHCCarr** [comment]
Thanks for clearing that up about the stanzas, so bottlebot keeps it's one internal counter I guess.

RE: https://github.com/Homebrew/homebrew-php/pull/4108#issuecomment-293189909

It wouldn't let me do a PR of patch-[1-4] see: https://github.com/Homebrew/homebrew-php/issues/4104#issuecomment-293103111

Most maintainers make you squish-squash, and contrort! :)

**Comment by javian** [comment]
@BenjaminHCCarr it shouldn't matter if you do 1 patch with 4 changes or 4 patches with 1 change each - both should work.
