### ISSUE TITLE
Extensions directory wrong after in stall 

### ISSUE THREAD

**Issue by hengsoheak** [Homebrew/homebrew-php#4121]
OSX: MacOS Sierra
version: 10.12.4
PHP version 7.0 , 5.6, 5.3
But i want to used 7.0

Afer I used brew search php70 I found many php extensions so I try to install all thos 

`brew install homebrew/php/php70-scrypt homebrew/php/php70-uopz homebrew/php/php70-geoip homebrew/php/php70-intl homebrew/php/php70-mecab homebrew/php/php70-pdo-pgsql homebrew/php/php70-snmp 
`
But after I change thos extensions directory  and php -v I found errors.

` php -v
Failed loading /usr/local/opt/php70-ioncubeloader/ioncubeloader.so:  dlopen(/usr/local/opt/php70-ioncubeloader/ioncubeloader.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-ioncubeloader/ioncubeloader.so
  Expected in: flat namespace
 in /usr/local/opt/php70-ioncubeloader/ioncubeloader.so
Failed loading /usr/local/opt/php70-opcache/opcache.so:  dlopen(/usr/local/opt/php70-opcache/opcache.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-opcache/opcache.so
  Expected in: flat namespace
 in /usr/local/opt/php70-opcache/opcache.so
Failed loading /usr/local/opt/php70-xdebug/xdebug.so:  dlopen(/usr/local/opt/php70-xdebug/xdebug.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php70-xdebug/xdebug.so
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.18_10/lib/php/extensions/no-debug-zts-20151012/msql.so' - dlopen(/usr/local/Cellar/php70/7.0.18_10/lib/php/extensions/no-debug-zts-20151012/msql.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.18_10/lib/php/extensions/no-debug-zts-20151012/msql.so' - dlopen(/usr/local/Cellar/php70/7.0.18_10/lib/php/extensions/no-debug-zts-20151012/msql.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-*/*.so' - dlopen(/usr/local/opt/php70-*/*.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-*/*.so' - dlopen(/usr/local/opt/php70-*/*.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-amqp/amqp.so' - dlopen(/usr/local/opt/php70-amqp/amqp.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-amqp/amqp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-amqp/amqp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-amqp/amqp.so' - dlopen(/usr/local/opt/php70-amqp/amqp.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-amqp/amqp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-amqp/amqp.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-apcu/apcu.so' - dlopen(/usr/local/opt/php70-apcu/apcu.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-apcu/apcu.so
  Expected in: flat namespace
 in /usr/local/opt/php70-apcu/apcu.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-apcu/apcu.so' - dlopen(/usr/local/opt/php70-apcu/apcu.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-apcu/apcu.so
  Expected in: flat namespace
 in /usr/local/opt/php70-apcu/apcu.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-ast/ast.so' - dlopen(/usr/local/opt/php70-ast/ast.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-ast/ast.so
  Expected in: flat namespace
 in /usr/local/opt/php70-ast/ast.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-ast/ast.so' - dlopen(/usr/local/opt/php70-ast/ast.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-ast/ast.so
  Expected in: flat namespace
 in /usr/local/opt/php70-ast/ast.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-apcu-bc/apc.so' - dlopen(/usr/local/opt/php70-apcu-bc/apc.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-apcu-bc/apc.so
  Expected in: flat namespace
 in /usr/local/opt/php70-apcu-bc/apc.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-apcu-bc/apc.so' - dlopen(/usr/local/opt/php70-apcu-bc/apc.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-apcu-bc/apc.so
  Expected in: flat namespace
 in /usr/local/opt/php70-apcu-bc/apc.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-blitz/blitz.so' - dlopen(/usr/local/opt/php70-blitz/blitz.so, 9): Symbol not found: _sapi_globals
  Referenced from: /usr/local/opt/php70-blitz/blitz.so
  Expected in: flat namespace
 in /usr/local/opt/php70-blitz/blitz.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-blitz/blitz.so' - dlopen(/usr/local/opt/php70-blitz/blitz.so, 9): Symbol not found: _sapi_globals
  Referenced from: /usr/local/opt/php70-blitz/blitz.so
  Expected in: flat namespace
 in /usr/local/opt/php70-blitz/blitz.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-couchbase/couchbase.so' - dlopen(/usr/local/opt/php70-couchbase/couchbase.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-couchbase/couchbase.so
  Expected in: flat namespace
 in /usr/local/opt/php70-couchbase/couchbase.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-couchbase/couchbase.so' - dlopen(/usr/local/opt/php70-couchbase/couchbase.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-couchbase/couchbase.so
  Expected in: flat namespace
 in /usr/local/opt/php70-couchbase/couchbase.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-event/event.so' - dlopen(/usr/local/opt/php70-event/event.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-event/event.so
  Expected in: flat namespace
 in /usr/local/opt/php70-event/event.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-event/event.so' - dlopen(/usr/local/opt/php70-event/event.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-event/event.so
  Expected in: flat namespace
 in /usr/local/opt/php70-event/event.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gearman/gearman.so' - dlopen(/usr/local/opt/php70-gearman/gearman.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-gearman/gearman.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gearman/gearman.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gearman/gearman.so' - dlopen(/usr/local/opt/php70-gearman/gearman.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-gearman/gearman.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gearman/gearman.so in Unknown on line 0
PHP Warning:  PHP Startup: geoip: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: geoip: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: geos: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: geos: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gmagick/gmagick.so' - dlopen(/usr/local/opt/php70-gmagick/gmagick.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-gmagick/gmagick.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gmagick/gmagick.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gmagick/gmagick.so' - dlopen(/usr/local/opt/php70-gmagick/gmagick.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-gmagick/gmagick.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gmagick/gmagick.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gmp/gmp.so' - dlopen(/usr/local/opt/php70-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gmp/gmp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-gmp/gmp.so' - dlopen(/usr/local/opt/php70-gmp/gmp.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-gmp/gmp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-gmp/gmp.so in Unknown on line 0
PHP Warning:  PHP Startup: gnupg: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: gnupg: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: grpc: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: grpc: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-igbinary/igbinary.so' - dlopen(/usr/local/opt/php70-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php70-igbinary/igbinary.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-igbinary/igbinary.so' - dlopen(/usr/local/opt/php70-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php70-igbinary/igbinary.so in Unknown on line 0
PHP Warning:  PHP Startup: libsodium: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: libsodium: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-lua/lua.so' - dlopen(/usr/local/opt/php70-lua/lua.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-lua/lua.so
  Expected in: flat namespace
 in /usr/local/opt/php70-lua/lua.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-lua/lua.so' - dlopen(/usr/local/opt/php70-lua/lua.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-lua/lua.so
  Expected in: flat namespace
 in /usr/local/opt/php70-lua/lua.so in Unknown on line 0
PHP Warning:  PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mecab/mecab.so' - dlopen(/usr/local/opt/php70-mecab/mecab.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-mecab/mecab.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mecab/mecab.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mecab/mecab.so' - dlopen(/usr/local/opt/php70-mecab/mecab.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-mecab/mecab.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mecab/mecab.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-memcache/memcache.so' - dlopen(/usr/local/opt/php70-memcache/memcache.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-memcache/memcache.so
  Expected in: flat namespace
 in /usr/local/opt/php70-memcache/memcache.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-memcache/memcache.so' - dlopen(/usr/local/opt/php70-memcache/memcache.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-memcache/memcache.so
  Expected in: flat namespace
 in /usr/local/opt/php70-memcache/memcache.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mongodb/mongodb.so' - dlopen(/usr/local/opt/php70-mongodb/mongodb.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mongodb/mongodb.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mongodb/mongodb.so' - dlopen(/usr/local/opt/php70-mongodb/mongodb.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mongodb/mongodb.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-msgpack/msgpack.so' - dlopen(/usr/local/opt/php70-msgpack/msgpack.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-msgpack/msgpack.so
  Expected in: flat namespace
 in /usr/local/opt/php70-msgpack/msgpack.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-msgpack/msgpack.so' - dlopen(/usr/local/opt/php70-msgpack/msgpack.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-msgpack/msgpack.so
  Expected in: flat namespace
 in /usr/local/opt/php70-msgpack/msgpack.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mustache/mustache.so' - dlopen(/usr/local/opt/php70-mustache/mustache.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-mustache/mustache.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mustache/mustache.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mustache/mustache.so' - dlopen(/usr/local/opt/php70-mustache/mustache.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-mustache/mustache.so
  Expected in: flat namespace
 in /usr/local/opt/php70-mustache/mustache.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-pcntl/pcntl.so' - dlopen(/usr/local/opt/php70-pcntl/pcntl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-pcntl/pcntl.so
  Expected in: flat namespace
 in /usr/local/opt/php70-pcntl/pcntl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-pcntl/pcntl.so' - dlopen(/usr/local/opt/php70-pcntl/pcntl.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-pcntl/pcntl.so
  Expected in: flat namespace
 in /usr/local/opt/php70-pcntl/pcntl.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so
  Expected in: flat namespace
 in /usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so
  Expected in: flat namespace
 in /usr/local/opt/php70-pdo-pgsql/pdo_pgsql.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-phalcon/phalcon.so' - dlopen(/usr/local/opt/php70-phalcon/phalcon.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-phalcon/phalcon.so
  Expected in: flat namespace
 in /usr/local/opt/php70-phalcon/phalcon.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-phalcon/phalcon.so' - dlopen(/usr/local/opt/php70-phalcon/phalcon.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-phalcon/phalcon.so
  Expected in: flat namespace
 in /usr/local/opt/php70-phalcon/phalcon.so in Unknown on line 0
PHP Warning:  PHP Startup: propro: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: propro: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-pspell/pspell.so' - dlopen(/usr/local/opt/php70-pspell/pspell.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-pspell/pspell.so
  Expected in: flat namespace
 in /usr/local/opt/php70-pspell/pspell.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-pspell/pspell.so' - dlopen(/usr/local/opt/php70-pspell/pspell.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-pspell/pspell.so
  Expected in: flat namespace
 in /usr/local/opt/php70-pspell/pspell.so in Unknown on line 0
PHP Warning:  PHP Startup: raphf: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: raphf: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: rdkafka: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: rdkafka: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-redis/redis.so' - dlopen(/usr/local/opt/php70-redis/redis.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-redis/redis.so
  Expected in: flat namespace
 in /usr/local/opt/php70-redis/redis.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-redis/redis.so' - dlopen(/usr/local/opt/php70-redis/redis.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-redis/redis.so
  Expected in: flat namespace
 in /usr/local/opt/php70-redis/redis.so in Unknown on line 0
PHP Warning:  PHP Startup: scrypt: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: scrypt: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-snmp/snmp.so' - dlopen(/usr/local/opt/php70-snmp/snmp.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-snmp/snmp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-snmp/snmp.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-snmp/snmp.so' - dlopen(/usr/local/opt/php70-snmp/snmp.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-snmp/snmp.so
  Expected in: flat namespace
 in /usr/local/opt/php70-snmp/snmp.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-solr/solr.so' - dlopen(/usr/local/opt/php70-solr/solr.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-solr/solr.so
  Expected in: flat namespace
 in /usr/local/opt/php70-solr/solr.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-solr/solr.so' - dlopen(/usr/local/opt/php70-solr/solr.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-solr/solr.so
  Expected in: flat namespace
 in /usr/local/opt/php70-solr/solr.so in Unknown on line 0
PHP Warning:  PHP Startup: stats: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: stats: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-swoole/swoole.so' - dlopen(/usr/local/opt/php70-swoole/swoole.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-swoole/swoole.so
  Expected in: flat namespace
 in /usr/local/opt/php70-swoole/swoole.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-swoole/swoole.so' - dlopen(/usr/local/opt/php70-swoole/swoole.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-swoole/swoole.so
  Expected in: flat namespace
 in /usr/local/opt/php70-swoole/swoole.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-tidy/tidy.so' - dlopen(/usr/local/opt/php70-tidy/tidy.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-tidy/tidy.so
  Expected in: flat namespace
 in /usr/local/opt/php70-tidy/tidy.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-tidy/tidy.so' - dlopen(/usr/local/opt/php70-tidy/tidy.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-tidy/tidy.so
  Expected in: flat namespace
 in /usr/local/opt/php70-tidy/tidy.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-timecop/timecop.so' - dlopen(/usr/local/opt/php70-timecop/timecop.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-timecop/timecop.so
  Expected in: flat namespace
 in /usr/local/opt/php70-timecop/timecop.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-timecop/timecop.so' - dlopen(/usr/local/opt/php70-timecop/timecop.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-timecop/timecop.so
  Expected in: flat namespace
 in /usr/local/opt/php70-timecop/timecop.so in Unknown on line 0
PHP Warning:  PHP Startup: timezonedb: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: timezonedb: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-trace/trace.so' - dlopen(/usr/local/opt/php70-trace/trace.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-trace/trace.so
  Expected in: flat namespace
 in /usr/local/opt/php70-trace/trace.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-trace/trace.so' - dlopen(/usr/local/opt/php70-trace/trace.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php70-trace/trace.so
  Expected in: flat namespace
 in /usr/local/opt/php70-trace/trace.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-uopz/uopz.so' - dlopen(/usr/local/opt/php70-uopz/uopz.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-uopz/uopz.so
  Expected in: flat namespace
 in /usr/local/opt/php70-uopz/uopz.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-uopz/uopz.so' - dlopen(/usr/local/opt/php70-uopz/uopz.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-uopz/uopz.so
  Expected in: flat namespace
 in /usr/local/opt/php70-uopz/uopz.so in Unknown on line 0
PHP Warning:  PHP Startup: uv: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: uv: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: xmldiff: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: xmldiff: Unable to initialize module
Module compiled with build ID=API20151012,NTS
PHP    compiled with build ID=API20151012,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-yac/yac.so' - dlopen(/usr/local/opt/php70-yac/yac.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-yac/yac.so
  Expected in: flat namespace
 in /usr/local/opt/php70-yac/yac.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-yac/yac.so' - dlopen(/usr/local/opt/php70-yac/yac.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-yac/yac.so
  Expected in: flat namespace
 in /usr/local/opt/php70-yac/yac.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-yaml/yaml.so' - dlopen(/usr/local/opt/php70-yaml/yaml.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-yaml/yaml.so
  Expected in: flat namespace
 in /usr/local/opt/php70-yaml/yaml.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-yaml/yaml.so' - dlopen(/usr/local/opt/php70-yaml/yaml.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php70-yaml/yaml.so
  Expected in: flat namespace
 in /usr/local/opt/php70-yaml/yaml.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-http/http.so' - dlopen(/usr/local/opt/php70-http/http.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-http/http.so
  Expected in: flat namespace
 in /usr/local/opt/php70-http/http.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-http/http.so' - dlopen(/usr/local/opt/php70-http/http.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-http/http.so
  Expected in: flat namespace
 in /usr/local/opt/php70-http/http.so in Unknown on line 0`

**Comment by hengsoheak** [comment]
```
php-fpm -t
[19-Apr-2017 00:01:48] ERROR: failed to open configuration file '/private/etc/php-fpm.conf': No such file or directory (2)
[19-Apr-2017 00:01:48] ERROR: failed to load configuration file '/private/etc/php-fpm.conf'
[19-Apr-2017 00:01:48] ERROR: FPM initialization failed
```

**Comment by javian** [comment]
For your first error it looks like you are using the thread safe version of php with a non thread safe bottle. All bottled formulas are compiled against the non thread safe version so if you want to use them you need to compile them from source using the `-s` flag.

For your second error can you run `which php-fpm` and paste the output just to verify that you are using the homebrew one ?

**Comment by javian** [comment]
@hengsoheak do I take your thumbs up as it is now solved ? =)
