### ISSUE TITLE
brew install codeception phar sha1 signature could not be verified

### ISSUE THREAD

**Issue by Choate** [Homebrew/homebrew-php#4123]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.12.4_
**Homebrew version:**   | _Homebrew 1.1.12_
**PHP version in use:** | _PHP 7.1.3_
**Xcode version:**      | _Xcode 8.3.2_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.3 (cli) (built: Apr  7 2017 17:04:43) ( NTS )

PHP Fatal error:  Uncaught PharException: phar "/usr/local/opt/Homebrew/Cellar/codeception/2.2.10/libexec/codecept.phar" SHA1 signature could not be verified: broken signature in /usr/local/opt/Homebrew/Cellar/codeception/2.2.10/libexec/codecept.phar:3

**Comment by BePsvPT** [comment]
@Choate could you please try to install codeception again and check whether it is still having this error or not.

**Comment by Choate** [comment]
@BePsvPT Yes there is this error .

```
==> Downloading https://homebrew.bintray.com/bottles-php/codeception-2.2.10.sier
Already downloaded: /Users/choate/Library/Caches/Homebrew/codeception-2.2.10.sierra.bottle.tar.gz
==> Pouring codeception-2.2.10.sierra.bottle.tar.gz
🍺  /usr/local/opt/Homebrew/Cellar/codeception/2.2.10: 5 files, 9.9MB
choate:~ $ codecept --version
PHP Fatal error:  Uncaught PharException: phar "/usr/local/opt/Homebrew/Cellar/codeception/2.2.10/libexec/codecept.phar" SHA1 signature could not be verified: broken signature in /usr/local/opt/Homebrew/Cellar/codeception/2.2.10/libexec/cod
```

**Comment by BePsvPT** [comment]
@Choate, please try the following commands

```bash
brew uninstall --force codeception
brew cleanup --prune=0
brew install codeception
codecept --version
```

**Comment by Choate** [comment]
@BePsvPT still can not

```
brew cleanup --prune=0
Warning: Skipping cmake: most recent version 3.8.0 not installed
...
brew prune
Pruned 0 symbolic links and 24 directories from /usr/local/opt/Homebrew

...

brew install codeception --ignore-dependencies
==> Installing codeception from homebrew/php
==> Downloading https://homebrew.bintray.com/bottles-php/codeception-2.2.10.sier
######################################################################## 100.0%

...

codecept --version
PHP Fatal error:  Uncaught PharException: phar "/usr/local/opt/Homebrew/Cellar/codeception/2.2.10/libexec/codecept.phar" SHA1 signature could not be verified: broken signature in /usr/local/opt/Homebrew/Cellar/codeception/2.2.10/libexec/codecept.phar:3

```

**Comment by javian** [comment]
@Choate your issue looks similar to https://github.com/sebastianbergmann/phpunit/issues/1694 - do you have suhosin installed ?

**Comment by Choate** [comment]
@javian no install suhosin.

download the package from the link http://codeception.com/codecept.phar to work properly

**Comment by mschwemer** [comment]
This solved the issue for me:

https://github.com/Homebrew/homebrew-php/issues/4358#issuecomment-320645331
