### ISSUE TITLE
Can't install with deprecated mysql support (mysql_)

### ISSUE THREAD

**Issue by merkjs** [Homebrew/homebrew-php#4133]
## Description

I know, it's deprecated but sometimes i need that library. What I have tried so far;

brew install php56
brew install php56 --with-libmysql

Both of them not installing php with mysql support. Is there an another way to do it or something wrong with me?

Thanks

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.4
**Homebrew version:**   | 1.1.13
**PHP version in use:** | 5.6.30
**Xcode version:**      | 8.1.10

**Comment by javian** [comment]
I committed a fix for this about a week ago since someone else asked the question. I just realised that the code doesn't run for php5.5 and above. It was removed in php7 so it should work in 5.6 and below so I will submit a PR to fix that.

**Comment by javian** [comment]
It should work now - can you test it again please ?

**Comment by merkjs** [comment]
It works now.

`brew reinstall php56 --with-httpd24 --with-libmysql`

Thanks!

**Comment by javian** [comment]
You're welcome!

**Comment by electricBonfire** [comment]
Will this work with MariaDB? 

When I run `brew reinstall php56 --with-httpd24 --with-libmysql` I get the following error:  `Cannot install mysql because conflicting formulae are installed.

  mariadb: because mysql, mariadb, and percona install the same binaries.`

**Comment by merkjs** [comment]
@electricBonfire Yes, it should work. MariaDB acts exactly like MySQL and this problem was related to PHP not to database.

Can you please try full uninstall and reinstall all the stack and use MySQL (at least development environment) if you don't really need MariaDB.

**Comment by electricBonfire** [comment]
Thats what I figured, it just wont install using `MariaDB` to satisfy the mysql dependency.
I have moved my `MariaDB` install and reinstalled `MySQL`. It is working now.

I do need `MariaDB` for a project, it allows for larger unique key parts.
I guess I should theoretically be able to uninstall `mysql` with `--ignore-dependencies` and then reinstall `MariaDB`.

**Comment by javian** [comment]
I hadn't thought about this. There is a hard dependency in the formula for mysql but that can be changed to accommodate mariadb (and percona) as well

**Comment by nahuelhds** [comment]
Hi. I've tried what @merkjs mention... I even unlinked mariadb and linked mysql but I just get the same error once and again

```
checking for specified location of the MySQL UNIX socket... /tmp/mysql.sock
configure: error: Cannot find libmysqlclient_r under /usr/local.
Note that the MySQL client library is not bundled anymore!
```

I don't what to do here since I've did `brew install mysql` already. What I'm missing?

PS: I'm a new MacOS and Homebrew user. So sorry if I'm asking something too newbie

**Comment by SMillerDev** [comment]
@nahuelhds your issue is more likely to be related to https://github.com/Homebrew/homebrew-php/issues/4501 instead of the current issue.

**Comment by fjeddy** [comment]
@SMillerDev Technically, they are both the exact same issue with different variables.

**Comment by nahuelhds** [comment]
Thanks @SMillerDev. I agree with @fjeddy it's just the same issue. Anyway that issue #4501 has a solution for the problem I was facing. So thank you for mention it.

Old php version < 7.x should be able to compile with old mysql extensions. We all have legacy code in production that cannot be updated that simple. If PHP has support for version < 7.x, Homebrew should have it as well.
