### ISSUE TITLE
Unable to load dynamic library php70-mcrypt

### ISSUE THREAD

**Issue by aivus** [Homebrew/homebrew-php#4134]
## Description

After `brew update && brew upgrade` I got broken php70-mcrypt.
I'm getting warnings and can't use mcrypt.
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php70-mcrypt/mcrypt.so, 9): Library not loaded: /usr/local/opt/libtool/lib/libltdl.7.dylib
  Referenced from: /usr/local/opt/php70-mcrypt/mcrypt.so
  Reason: image not found in Unknown on line 0
```

As a workaround I ran `brew reinstall -s php70-mcrypt` and it works fine for now.
But looks like binaries are broken. 

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.4
**Homebrew version:**   | Homebrew 1.1.13 Homebrew/homebrew-core (git revision 0b6694; last commit 2017-04-25)
**PHP version in use:** | PHP 7.0.18 (cli) (built: Apr 16 2017 12:16:19) ( NTS )
**Xcode version:**      | don't have installed Xcode, only xcode-select

**Output of `gcc -v`:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php70-mcrypt/mcrypt.so, 9): Library not loaded: /usr/local/opt/libtool/lib/libltdl.7.dylib
  Referenced from: /usr/local/opt/php70-mcrypt/mcrypt.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php70-mcrypt/mcrypt.so, 9): Library not loaded: /usr/local/opt/libtool/lib/libltdl.7.dylib
  Referenced from: /usr/local/opt/php70-mcrypt/mcrypt.so
  Reason: image not found in Unknown on line 0
PHP 7.0.18 (cli) (built: Apr 16 2017 12:16:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.16.2~mac-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.
```
**Build logs:** https://gist.github.com/anonymous/4fa3c68bd10752b94f99eb2ddd059863

**Comment by javian** [comment]
A fix for this is waiting to be merged but the CI system is currently not working correctly so I need some support from the homebrew team to get it working again.

**Comment by javian** [comment]
This should now be corrected for all php versions.
