### ISSUE TITLE
php70-intl sierra bottle not installing config file

### ISSUE THREAD

**Issue by rbrown** [Homebrew/homebrew-php#4139]
## Description

brew install php70-intl installs the bottle, the bottle doesn't install the config files 

``` brew install php70-intl
==> Installing php70-intl from homebrew/php
==> Downloading https://homebrew.bintray.com/bottles-php/php70-intl-7.0.18_12.sierra.bottle.tar.gz
Already downloaded: /Users/rb/Library/Caches/Homebrew/php70-intl-7.0.18_12.sierra.bottle.tar.gz
==> Pouring php70-intl-7.0.18_12.sierra.bottle.tar.gz
==> Caveats
To finish installing intl for PHP 7.0:
  * /usr/local/etc/php/7.0/conf.d/ext-intl.ini was created,

rb@hyperion ~ $ ls -l /usr/local/etc/php/7.0/conf.d/ext-intl.ini
ls: /usr/local/etc/php/7.0/conf.d/ext-intl.ini: No such file or directory
```

installing with -s does install the config file.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.5
**Homebrew version:**   | Homebrew 1.1.13-139-g698afa2ba
**PHP version in use:** |PHP 7.0.18 (cli) (built: Apr 16 2017 12:16:19) ( NTS )
**Xcode version:**      | Xcode 8.3.2

**Output of `php -v`:**
PHP 7.0.18 (cli) (built: Apr 16 2017 12:16:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with blackfire v1.16.2~mac-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.

**Comment by PascalZajac** [comment]
I just ran into this today, can confirm that running `brew install -s php70-intl` solves the issue temporarily.

**Comment by mtangoo** [comment]
>I just ran into this today, can confirm that running brew install -s php70-intl solves the issue temporarily.

It works under El Capitan too

**Comment by SMillerDev** [comment]
Is this still an issue?
