### ISSUE TITLE
Unable to recognize another user for pool usage in PHPFPM

### ISSUE THREAD

**Issue by bostonmacosx** [Homebrew/homebrew-php#4144]
## Description

Unable to start PHPFPM with any other user defined in a pool definition.

[client_ellen]

; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
user = poolellen
group = pools

listen = 127.0.0.1:9001

listen.mode = 0666
 
pm = dynamic

pm.max_children = 10

pm.start_servers = 3

pm.min_spare_servers = 2

pm.max_spare_servers = 5

; The number of seconds after which an idle process will be killed.
; Note: Used only when pm is set to 'ondemand'
; Default Value: 10s
;pm.process_idle_timeout = 10s;
 

**When I run dscl to get the list of users**
poolellen               510

when I start the phpfpm I get

[01-May-2017 20:22:22] ERROR: [pool client_ellen] cannot get uid for user 'poolellen'
[01-May-2017 20:22:22] ERROR: FPM initialization failed

Parameter | Value
--------- | ------------------
**10.12.4**       | _your macOS version (output of `sw_vers -productVersion`)_
**1.1.13**   | _your Homebrew version (output of `brew --version`)_
**PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies** | _your PHP version (output of `/path/to/php -v`)_
**8.3**      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.41)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
@bostonmacosx how do you start fpm ? Where did you place the poolellen config ? Are you running fpm as root ?

**Comment by bostonmacosx** [comment]
Hello there....it is started as root....through a LaunchDaemon on OSX.....
it was located in the php-fpm.conf file in the /etc/php/5.6 directory


`_www            30097   0.0  0.1  2524084  25016   ??  S     9:43AM   0:27.16 /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf
_www             7362   0.0  0.1  2490032  23964   ??  S    Tue08AM   0:36.21 /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf
_www             1237   0.0  0.2  2525108  28452   ??  S    Tue04AM   0:38.90 /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf
_www             1235   0.0  0.1  2490032  20896   ??  S    Tue04AM   0:36.92 /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf
_www             1233   0.0  0.2  2524084  26504   ??  S    Tue04AM   0:37.35 /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf
root               65   0.0  0.1  2481708  13208   ??  Ss   Tue04AM   0:06.39 /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf`

**Comment by javian** [comment]
@bostonmacosx the config seems to hint that you should seperate the pools in the conf.d directory. Is that what you have done ?
```
;;;;;;;;;;;;;;;;;;;;
; Pool Definitions ;
;;;;;;;;;;;;;;;;;;;;

; Multiple pools of child processes may be started with different listening
; ports and different management options.  The name of the pool will be
; used in logs and stats. There is no limitation on the number of pools which
; FPM can handle. Your system will tell you anyway :)

; Include one or more files. If glob(3) exists, it is used to include a bunch of
; files from a glob(3) pattern. This directive can be used everywhere in the
; file.
; Relative path can also be used. They will be prefixed by:
;  - the global prefix if it's been set (-p argument)
;  - /usr/local/Cellar/php70/7.0.2 otherwise
include=/usr/local/etc/php/7.0/php-fpm.d/*.conf
```
