### ISSUE TITLE
Syntax error on line 245 of /usr/local/etc/apache2/2.4/httpd.conf

### ISSUE THREAD

**Issue by humipine** [Homebrew/homebrew-php#4170]
## Description

I installed, using Homebrew, Apache, MySQL, and PHP to my Mac OS Sierra.
after installing PHP 5.6.30, I started apache on Terminal, and the following error came up;

"AH00526: Syntax error on line 245 of /usr/local/etc/apache2/2.4/httpd.conf:
DocumentRoot '/usr/local/opt/httpd24/Users/whoo/htdocs' is not a directory, or is not readable
macwhoo:~ whoo$ sudo apachectl restart
AH00526: Syntax error on line 245 of /usr/local/etc/apache2/2.4/httpd.conf:
DocumentRoot '/usr/local/opt/httpd24/Users/whoo/htdocs' is not a directory, or is not readable"

I opened the httpd.conf file, and checked the line 245, which is actually 'DocumentRoot "Users/whoo/htdocs" '.

Does anyone know how to fix this problem?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:10.12.4(Sierra)**       | _your macOS version (output of `sw_vers -productVersion`)_
**Homebrew version:1.2.1**   | _your Homebrew version (output of `brew --version`)_
**PHP version in use:5.6.30** | _your PHP version (output of `/path/to/php -v`)_
**Xcode version:8.3.2**      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
_result of the CLI output_

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
Yes, that's not a bug but a feature https://httpd.apache.org/docs/2.4/mod/core.html#documentroot . If `DocumentRoot` is a relative path its prepended with `ServerRoot`.

**Comment by javian** [comment]
Closing due to no response.
