### ISSUE TITLE
ERR_EMPTY_RESPONSE on localhost:9000

### ISSUE THREAD

**Issue by kenorb** [Homebrew/homebrew-php#4185]
## Description

I've successfully installed php71 on macOS Sierra, but when I'm accessing http://localhost:9000/ which is showing ERR_EMPTY_RESPONSE in Chrome. I've followed instruction from `brew info php71`, loaded via `launchctl`, started service and it's successfully listening on 9000. I've no errors in log file, the service is running, I can telnet to 9000, but the page doesn't load. Any suggestions?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |10.12
**Homebrew version:**   | 1.2.1
**PHP version in use:** | 7.1.5
**Xcode version:**      |8.3

```
$ brew info php71
homebrew/php/php71: stable 7.1.5 (bottled), HEAD
PHP Version 7.1
https://php.net
Conflicts with: php53, php54, php55, php56, php70
/usr/local/Cellar/php71/7.1.5_17 (349 files, 39.5MB) *
  Poured from bottle on 2017-05-23 at 21:44:57
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php71.rb
==> Dependencies
Required: freetype ✔, gettext ✔, icu4c ✔, jpeg ✔, libpng ✔, libxml2 ✔, unixodbc ✔, readline ✔, openssl ✔
Optional: enchant ✘, gmp ✔, webp ✔, homebrew/apache/httpd24 ✘, homebrew/apache/httpd22 ✘
==> Requirements
Optional: postgresql ✘
$ curl localhost:9000
curl: (52) Empty reply from server
```

Is it possible that I need to install anything extra or I'm missing anything in configuration?

**Comment by javian** [comment]
You can see a guide to use fpm with apache with homebrew here https://lukearmstrong.github.io/2016/12/setup-apache-mysql-php-homebrew-macos-sierra/ . As far as I can tell you are not supposed to query the fpm port directly in the way you are doing.

**Comment by kenorb** [comment]
Is Apache mandatory to install? It appears on optional list.

**Comment by kenorb** [comment]
Ok, fine, probably you're right. I'll use PHP builtin server then, e.g.

    php -S localhost:8000

Thanks.

**Comment by javian** [comment]
apache or nginx would be the most popular options but there might be others but if you can use the built in server that's probably the easiest way host the files
