### ISSUE TITLE
Support for PHP 7.2

### ISSUE THREAD

**Issue by Schrank** [Homebrew/homebrew-php#4210]
**php-7.2.0alpha1 is out!**

http://news.php.net/php.internals/99452

It would be great if you support PHP 7.2. Unfortunately I have no clue how to implement this, but if someone guide me, I would love to help implement support for it.

**Comment by alcaeus** [comment]
If you want to add it yourself, you can take a look at #3274, which introduced 7.1.0alpha1 - just follow the diff there. If you don't want to try it yourself, I can add it sometime tomorrow.

**Comment by romainneutron** [comment]
FYI I'm going to submit PHP72 formula with most of extensions

**Comment by Schrank** [comment]
Just started with it. Then I'll give it over to you and stop here :-) Thank you very much!

**Comment by Schrank** [comment]
If you need any support @romainneutron tell me! But until now it looks like a lot of copy and paste :-)

**Comment by romainneutron** [comment]
See #4211

**Comment by morloderex** [comment]
Any way we can try out the new argon2 stuff?

**Comment by javian** [comment]
@morloderex that would have to be added to the formula since it requires libargon2 for it to work.

**Comment by morloderex** [comment]
@javian How do we do that? :D

**Comment by javian** [comment]
@morloderex You need to submit a PR against https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb . If you look at how webp has been implemented the argon2 stuff should be very similar. You need to put an optional dependency towards the argon2 formula and add an add the right command line option if the argon2 command line switch has been used. Does that make sense?

**Comment by morloderex** [comment]
@javian 
I have now hacked a bit on this to try and add an option called --with-argon2 that adds this configuration option to the compiler but with no luck so far. 

Can you take a look at my master branch on my fork of this project and guide me a bit more? 

It just doesn't seem to get added (i have verified this with the brew build-logs command) 👍  So getting a little bit of the hang of this.

**Comment by javian** [comment]
@morloderex it might be easier if you submit the PR as is and I/we can comment on it there . I'll also close this issue once the rest of the formulas have been created for 7.2.

**Comment by javian** [comment]
Since we have now merged 7.2 and continue to update it as new releases are published I will close this issue. @morloderex if you want the argon support then please submit the pr =)
