### ISSUE TITLE
php71-intl / ICU issue

### ISSUE THREAD

**Issue by ThauEx** [Homebrew/homebrew-php#4224]
## Description

When I try to use some function form the intl module, I'm getting a warning regarding the `ICU transliterator`.

Here is a sample script: (I'm running `php test.php`)

test.php
```php
<?php

$locale = 'de';
$value = 'HöHä';

$trans = transliterator_transliterate("Any-$locale; Latin-ASCII;", $value);

var_dump($trans);
```
expected output:
`string(4) "HoHa"`

real output:
```
PHP Warning:  transliterator_transliterate(): Could not create transliterator with ID "Any-de; Latin-ASCII;" (transliterator_create: unable to open ICU transliterator with id "Any-de; Latin-ASCII;": U_INVALID_ID) in test.php on line 6

Warning: transliterator_transliterate(): Could not create transliterator with ID "Any-de; Latin-ASCII;" (transliterator_create: unable to open ICU transliterator with id "Any-de; Latin-ASCII;": U_INVALID_ID) in test.php on line 6
bool(false)
```

I tested it with a prebuild version from here (http://php-osx.liip.ch/) and this one is working fine. I already tried to build icu4c, php71-intl and php71 from source, since by default the bottled version is being used, but nothing changed. I only noticed, that the other prebuild version is using ICU 56.1 and the homebrew version uses 58.2.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.5
**Homebrew version:**   | Homebrew 1.2.3, Homebrew/homebrew-core (git revision 46c16; last commit 2017-06-16)
**PHP version in use:** | PHP 7.1.5 (cli) (built: May 13 2017 13:30:32) ( NTS )
**Xcode version:**      | Xcode 8.3.3

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.5 (cli) (built: May 13 2017 13:30:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by javian** [comment]
That ID doesn't seem to exist. Run `php -r "var_dump(transliterator_list_ids());"` and it will list everything that is available in intl.

**Comment by javian** [comment]
Closing due to no response.
