### ISSUE TITLE
PHP 7.1.6

### ISSUE THREAD

**Issue by ellisio** [Homebrew/homebrew-php#4227]
When can we expect PHP 7.1.6 to hit the repo? It's been out since June 8th. Cheers.

**Comment by javian** [comment]
Hi @ellisio - we are dependent on the community to help support the contribution of version upgrades so please feel free to submit a pull request to include the new version. You can see how one is done by looking at the previous commit of the 7.1 series - https://github.com/Homebrew/homebrew-php/commit/45854ffe8d1f99286e501b30f2bdf101e5ae5a98 and don't hesitate to ask any questions in here or in the pull request itself if you need any support.

**Comment by alcaeus** [comment]
That flew right by my head - see #4229 and #4230.

**Comment by javian** [comment]
This has been merged now.
