### ISSUE TITLE
include_path missing from generated config file

### ISSUE THREAD

**Issue by externl** [Homebrew/homebrew-php#4282]
## Description

When generating config files, homebrew-php does:

```
  def config_file
    <<-EOS.undent
      [#{extension}]
      #{extension_type}="#{module_path}"
      EOS
  rescue StandardError
    nil
  end
```

It would be nice for it to also include `include_path=`, eg:

```
  def config_file
    begin
      <<-EOS.undent
      [#{extension}]
      #{extension_type}="#{module_path}"
      include_path="#{opt_prefix}"
      EOS
    rescue Exception
      nil
    end
  end
```

**Comment by javian** [comment]
what difference would that make ? The module_path is hardcoded so I can't see why it would add any benefit.

**Comment by externl** [comment]
The `module_path` is the location to the dynamic library extension loaded by the PHP runtime. The `include_path` being the location to PHP files. Are you saying that PHP looks in the directory of the file specified by`extension=` for PHP files by default?

**Comment by javian** [comment]
But we don't ship any php files with the modules do we ?

http://php.net/manual/en/ini.core.php#ini.include-path says `Specifies a list of directories where the require, include, fopen(), file(), readfile() and file_get_contents() functions look for files.`. Having that in the module configuration doesn't make sense to me. Do you have an example of what you are trying to do so I can try and understand where you are going with this ?

**Comment by externl** [comment]
Sure, we (github.com/zeroc-ice) are getting ready to release Ice 3.7.0 and plan on splitting php out of the `hombrew-core` tap and put it into `homebrew-php`.

You can see what our formulae currently looks like here:
* https://github.com/zeroc-ice/homebrew-tap/blob/master/Formula/ice37b0.rb
* https://github.com/zeroc-ice/homebrew-tap/blob/master/Formula/php71-ice37b0.rb

Our PHP distribution contains both a dynamic library module and php source files. Both of which users need to write Ice applications in PHP.

**Comment by externl** [comment]
We're hoping to merge these files (different names) into `homebrew-php` for the next release. You see any issues, is there a better way to deal with the `include_path`?

**Comment by javian** [comment]
I'm curious why you chose this method of using the code ? I would imagine that today the most common practice would be to create a composer module and distribute it that way. 

Is the source file generated at build time ? I was looking inside the repo but the php files were referencing files that did not exist.

Are you going to get ice merged into homebrew-core ?

**Comment by javian** [comment]
>We looked into composer but they don't have a way to distributed/build modules, and like I mentioned, the php files do nothing without the module.
But there ought to be many composer packages that have dependencies to modules that might not be installed on every system for example intl and mcrypt. If you have a build time dependency to generate the php code it might be different however. I'm mainly curious and not trying to criticise =)

What would make the generated code unique and could that cause any issues with bottling the Formula ie. using the same compiled php module on multiple systems ?

**Comment by externl** [comment]
I'm not sure about other packages, but the versioning of the Ice php files and the dynamic library module are closely intertwined. 

Would it really make sense to have the php files in composer and module in brew? Do you know how are modules (excluding brew distribution) handle this?

For us, distributing both in the same place makes the most sense. Can you think of a reason why composer would be preferable in this case?

The php part of the Ice for PHP build (handwritten and generated (compile time)) can be used with any Ice for PHP module of the *same* version. The module comes in two flavors, a php 5 and a php 7 version. This includes both generated (compile time) and handwritten code.

Have I explained things any better?

**Comment by alcaeus** [comment]
@externl I don't know your library, so I don't know if this approach will work for you. MongoDB for example have rewritten their driver for PHP in a very lightweight fashion and distribute an extension for that. It declares classes for exceptions, types and a few other things. Most of the actual query functionality however is contained in a library distributed via composer that requires the driver. That way, updates to functionality (say a new option in a specific query method) won't require driver updates (as long as they don't extend the query protocol). You could technically talk to MongoDB without using the library and using the driver directly, but the library they offer will simplify things greatly.

**Comment by externl** [comment]
@alcaeus Thank you for your response. For Ice, the PHP and dynamic library are highly dependant on each other. 

Since no other formula have this issue. I think best to close this issue; I'll keep the ini override in our formula once I submit a PR.
