### ISSUE TITLE
php71-ssh2 installs, but php has trouble loading it

### ISSUE THREAD

**Issue by jpmurray** [Homebrew/homebrew-php#4283]
## Description

I've installed php71-ssh2, but it won't load. Trying to invoque anything php will give error, for example:

```shell
$ php --ini
PHP Warning:  PHP Startup: ssh2: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,NTS,debug
These options need to match
 in Unknown on line 0

Warning: PHP Startup: ssh2: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,NTS,debug
These options need to match
 in Unknown on line 0
Configuration File (php.ini) Path: /usr/local/etc/php/7.1
Loaded Configuration File:         /usr/local/etc/php/7.1/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.1/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.1/conf.d/ext-ssh2.ini
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |10.12.6
**Homebrew version:**   | Homebrew 1.2.3. Homebrew/homebrew-core (git revision a88f; last commit 2017-06-22)
**PHP version in use:** | 7.1.5

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP Warning:  PHP Startup: ssh2: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,NTS,debug
These options need to match
 in Unknown on line 0

Warning: PHP Startup: ssh2: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,NTS,debug
These options need to match
 in Unknown on line 0
PHP 7.1.5 (cli) (built: Jun 17 2017 09:46:20) ( NTS DEBUG )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** Running the commands says _no logs_... ?

**Comment by javian** [comment]
Your answer is here
```
PHP Warning:  PHP Startup: ssh2: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,NTS,debug
These options need to match
```
You need to compile the module with the same option(s) as php is compiled with. In this case you have debug enabled on PHP but not in the module. Reinstalling the module from source might solve it `brew reinstall php71-ssh2 -s` .

**Comment by jpmurray** [comment]
Excellent, thank you very much!
