### ISSUE TITLE
php-imap php-cli 5 sec delay

### ISSUE THREAD

**Issue by vladprokopchuk** [Homebrew/homebrew-php#4311]
I have installed like this:

brew install php71 --with-imap --with-fpm

but problem is:

vlad@MacBook-Pro-Vladimir /etc $ time php -v
PHP 7.1.6 (cli) (built: Jul 3 2017 08:34:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

real	0m5.039
suser	0m0.016
ssys	0m0.011s
vlad@MacBook-Pro-Vladimir /etc $

adding 127.0.0.1 myhost.local to /etc/hosts file did not help. I really need IMAP extension.
But every using php-cli takes 5 sec delay.
If I will install php without imap all works fast.

**Comment by javian** [comment]
Do you have ipv6 enabled ? If so you need to add an entry for that too in the hosts file according to  https://serverfault.com/questions/586141/php-cli-with-imap-5-second-startup-delay

**Comment by vladprokopchuk** [comment]
here is my hosts file

127.0.0.1       cweb.local
::1             cweb.local
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost

**Comment by javian** [comment]
Does any of those names match the name of you computer ? I would assume that the output of `hostname` is what needs to be mapped.

**Comment by vladprokopchuk** [comment]
what you mean using "name of computer"?
you mean domain name?

**Comment by littleylv** [comment]
I used to have that problem after install php-imap.

to solve this problem:
1. Go to `System Preferences` => `Sharing`
2. In the `Computer Name` , find something like `Computers on your local network can access your computer at: foo.bar` (you computer name)
3. add 
```
127.0.0.1   foo.bar
::1             foo.bar
```
to `/etc/hosts`

May this work for you .

**Comment by vladprokopchuk** [comment]
thx  a lot! it really works

**Comment by javian** [comment]
@vladprokopchuk glad that you got it working. What I meant was that if you open the terminal and enter the command `hostname` it will output your computer name which you then need to enter into the hosts just as you did now. If the name doesn't match with what's in the hosts file it will not work as you discovered =)
