### ISSUE TITLE
Tapping fails

### ISSUE THREAD

**Issue by sneps85** [Homebrew/homebrew-php#4330]
Trying to use brew tap homebrew/homebrew-php gives me the following output:

==> Tapping homebrew/php
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 757, done.
remote: Compressing objects: 100% (525/525), done.
remote: Total 757 (delta 496), reused 294 (delta 223), pack-reused 0
Receiving objects: 100% (757/757), 309.05 KiB | 0 bytes/s, done.
Resolving deltas: 100% (496/496), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/deployer.rb
invalid attribute for formula 'homebrew/php/deployer': version (nil)
Error: Cannot tap homebrew/php: invalid syntax in tap!

brew doctor gives me 2 warnings about XQuartz and a not up-to-date XCode version.
Any clues?

**Comment by javian** [comment]
Can you post the output of `brew config` ?

**Comment by sneps85** [comment]
Here it is:
`HOMEBREW_VERSION: 1.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7abd33475b98598b414f9c4ee2e20249855437b
Last commit: 9 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1bf6366af6ded2fbb6fb7627ec1b844848293c08
Core tap last commit: 27 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92, 1.8.0_60, 1.7.0_79, 1.7.0_67, 1.6.0_65-b14-468
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.7 => /opt/X11`

**Comment by javian** [comment]
Your home-brew version is not up to date. Can you run `brew update` and try again ?

**Comment by javian** [comment]
@sneps85 did you get it working ?

**Comment by sneps85** [comment]
it is working now, thank you for your help...

i had to reinstall brew, because brew update command did nothing.
