### ISSUE TITLE
no suitable image found

### ISSUE THREAD

**Issue by sh2050** [Homebrew/homebrew-php#4334]
## Description
xdebug.so is not loaded. 

## Context and Logs
/usr/local/opt/php71-xdebug/xdebug.so: dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): no suitable image found. Did find: /usr/local/opt/php71-xdebug/xdebug.so: mach-o, but wrong architecture
Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.5
**Homebrew version:**   | Homebrew 1.2.4-107-gaa8eb21
**PHP version in use:** | 7.1.2
**Xcode version:**      | 8E3004b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): no suitable image found.  Did find:
	/usr/local/opt/php71-xdebug/xdebug.so: mach-o, but wrong architecture
PHP 7.1.2 (cli) (built: Apr 19 2017 19:17:16) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by SMillerDev** [comment]
Is this still an issue?
