### ISSUE TITLE
Apache2.4.27 not compatible with PHP5.6.30ntsWin32-VC15

### ISSUE THREAD

**Issue by latagaw** [Homebrew/homebrew-php#4336]
Having trouble configuring PHP56 with Apache2.4?

"Can't locate API module structure 'php5_module'...

php5apache2_4.dll does not exist in PHP56 so i install php55 instead, where the dll file existed

LoadModule php5_module "C:/PHP/php5apache2_4.dll"
AddHandler application/x-httpd-php .php
PHPIniDir C:/PHP

i haven' tried PHP707Win32VC14x86 yet. as long my server is running smoothly is all I need for now.

**Comment by SMillerDev** [comment]
This seems like a very Windows specific problem. Could it be that you meant to post this issue somewhere else? As Windows isn't really supported in homebrew.
