### ISSUE TITLE
How to install php70-xdebug with debug symbols?

### ISSUE THREAD

**Issue by kenorb** [Homebrew/homebrew-php#4338]
## Description

I've reinstalled php70 with debug symbols via: `brew reinstall php70 --with-debug --with-httpd24`, however I can't do the same with `php70-xdebug`, because there is no `--with-debug` option.

```
$ brew info php70-xdebug
homebrew/php/php70-xdebug: stable 2.5.5 (bottled), HEAD
Provides debugging and profiling capabilities.
https://xdebug.org
/usr/local/Cellar/php70-xdebug/2.5.5 (4 files, 196KB) *
  Poured from bottle on 2017-07-27 at 23:39:09
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php70-xdebug.rb
$ brew info php70
homebrew/php/php70: stable 7.0.20 (bottled), HEAD
```

It's a problem, because XDebug module doesn't load properly when php70 has been compiled with debug symbols, because API doesn't match.

```
$ php70 -i | grep xdebug
Cannot load Xdebug - it was built with configuration API320151012,NTS, whereas running engine is API320151012,NTS,debug
```

How to fix it? How do I reinstall `php70-xdebug` package with the debug symbols?

**Comment by kenorb** [comment]
PR: #4341

**Comment by MichalYosef** [comment]
I get this error too:
Cannot load Xdebug - it was built with configuration API320160303,TS,VC14, whereas running engine is API320160303,NTS,VC14

Was installed from here http://windows.php.net/download/

How do I solve this?

**Comment by kenorb** [comment]
@MichalYosef This sounds like a separate issue, please raise a new ticket for it.

**Comment by SMillerDev** [comment]
@MichalYosef while that sounds unfortunate, a macOS package manager issue tracker is hardly the place for the issues you have with the version the PHP team compiled for windows.
