### ISSUE TITLE
PATH instructions should use static path

### ISSUE THREAD

**Issue by tejasbubane** [Homebrew/homebrew-php#4340]
## Description

The php command line instructions in README for updating `PATH` variable contain a command `brew --prefix`. This if added to `zshrc` or `bashrc` will run the brew command each time a terminal window is opened. It makes opening a terminal window terribly slow.

I assume the brew path (returned by the command) is very unlikely to be changed, unless a version update. It would be better to run that command separately and use static path in the `PATH` export.

**Comment by SMillerDev** [comment]
Seeing as there are very few things actually executed before the `--prefix` command returns, this might not be as big an issue as you make it out to be. It does however provide a very convenient way to set the path.

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L17 for reference

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
