### ISSUE TITLE
imagemagick version > 7.0.6-0 throws errors with php-cli

### ISSUE THREAD

**Issue by hostep** [Homebrew/homebrew-php#4342]
## Description

Running php through cli starts throwing errors with imagemagick version > 7.0.6-0
Error message:
```
$ php --version
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.0.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0
```

This error does not happen with imagemagick version 7.0.6-0, only with 7.0.6-1, 7.0.6-2 and 7.0.6-3
Reverting imagemagick back to 7.0.6-0 solves the problem.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | 1.2.6-4-gac2cbd2
**PHP version in use:** | 7.0.20 (cli)
**Xcode version:**      | 8.3.3

**Output of `gcc -v`:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**
```
PHP 7.0.20 (cli) (built: Jul  9 2017 21:49:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.20, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by trsteel88** [comment]
Having the same issue.

**Comment by trsteel88** [comment]
Installing from source seems to have fixed it for me @hostep 

```
brew uninstall php71-imagick imagemagick
brew install -s php71-imagick
```

**Comment by hostep** [comment]
@trsteel88: thanks, can confirm, installing from source fixes the issue.

Should I leave this ticket open, or is this considered expected behaviour? (I'm very new to homebrew, coming from years of working with macports, so I'm not very familiar yet with how everything is supposed to work with homebrew...)

**Comment by alcaeus** [comment]
@hostep this is somewhat expected, it happens every time imagemagick is updated. #4363 will cause a new bottle for php71-imagick to be compiled, so it will fix the issue. Feel free to close this issue.

**Comment by hostep** [comment]
Ok thanks for the answer @alcaeus.

If I remember correctly from Macports, they used to bump the revision of dependencies (like phpXX-imagick) everytime ImageMagick got an update. Not sure if this is somehow possible in Homebrew's?

But ok, good to know that's how you usually solve this kind of issue (had the same experience with 'jpeg' vs 'php56' last week, got to solve it in the same way), getting used to Homebrew step by step :)

Closing this issue as requested.

**Comment by alcaeus** [comment]
I'm not sure if that's possible here, since imagemagick is hosted in homebrew-core, while phpx-imagick is hosted in homebrew-php. However, @javian is putting in a huge effort to get php into homebrew-core (see https://github.com/Homebrew/homebrew-core/pull/16067), so it might be possible once that's done.
