### ISSUE TITLE
Cannot install PHP 7.1 on OSX 10.9

### ISSUE THREAD

**Issue by theredled** [Homebrew/homebrew-php#4369]
## Description

For `brew install php71 --with-apache --with-httpd24`, 
The installation of nghttp2 dependency fails:

> Error: You are using macOS 10.9.
> We (and Apple) do not provide support for this old version.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.9.5
**Homebrew version:**   | Homebrew 1.3.1-10-g93051b2 / Homebrew/homebrew-core (git revision 25c5; last commit 2017-08-08)
**PHP version in use:** | PHP 7.1.7
**Xcode version:**      | Xcode 6.1.1 / Build version 6A2008a

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 30 2017 14:57:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:**
==> Installing php71 from homebrew/php
==> Installing dependencies for homebrew/php/php71: nghttp2, homebrew/apache/httpd24
==> Installing homebrew/php/php71 dependency: nghttp2
==> Downloading https://github.com/nghttp2/nghttp2/releases/download/v1.24.0/nghttp2-1.24.0.tar.xz
Already downloaded: /Users/theredled/Library/Caches/Homebrew/nghttp2-1.24.0.tar.xz
==> ./configure --prefix=/usr/local/Cellar/nghttp2/1.24.0 --disable-silent-rules --enable-app --with-boost=/usr/local/opt/boost --enable-asio-lib --with-spdylay --di
==> make
Last 15 lines from /Users/theredled/Library/Logs/Homebrew/nghttp2/02.make:
clang++ -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/usr/local/Cellar/nghttp2/1.24.0/share/nghttp2"' -I../lib/includes -I../lib/includes -I../lib -I../src/includes -I../third-party -I/usr/local/Cellar/spdylay/1.4.0_1/include -I/usr/include/libxml2 -I/usr/local/Cellar/openssl/1.0.2l/include -I/usr/local/Cellar/c-ares/1.13.0/include -I/usr/local/Cellar/jansson/2.10/include -DHAVE_CONFIG_H      -g -O2 -MT libnghttpx_a-shrpx_log_config.o -MD -MP -MF .deps/libnghttpx_a-shrpx_log_config.Tpo -c -o libnghttpx_a-shrpx_log_config.o `test -f 'shrpx_log_config.cc' || echo './'`shrpx_log_config.cc
mv -f .deps/libnghttpx_a-shrpx_log.Tpo .deps/libnghttpx_a-shrpx_log.Po
clang++ -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/usr/local/Cellar/nghttp2/1.24.0/share/nghttp2"' -I../lib/includes -I../lib/includes -I../lib -I../src/includes -I../third-party -I/usr/local/Cellar/spdylay/1.4.0_1/include -I/usr/include/libxml2 -I/usr/local/Cellar/openssl/1.0.2l/include -I/usr/local/Cellar/c-ares/1.13.0/include -I/usr/local/Cellar/jansson/2.10/include -DHAVE_CONFIG_H      -g -O2 -MT libnghttpx_a-shrpx_connect_blocker.o -MD -MP -MF .deps/libnghttpx_a-shrpx_connect_blocker.Tpo -c -o libnghttpx_a-shrpx_connect_blocker.o `test -f 'shrpx_connect_blocker.cc' || echo './'`shrpx_connect_blocker.cc
shrpx_log_config.cc:62:1: error: thread-local storage is unsupported for the current target
thread_local std::unique_ptr<LogConfig> config = make_unique<LogConfig>();
^
1 error generated.
make[3]: *** [libnghttpx_a-shrpx_log_config.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libnghttpx_a-shrpx_connect_blocker.Tpo .deps/libnghttpx_a-shrpx_connect_blocker.Po
mv -f .deps/libnghttpx_a-shrpx_worker.Tpo .deps/libnghttpx_a-shrpx_worker.Po
mv -f .deps/libnghttpx_a-shrpx_tls.Tpo .deps/libnghttpx_a-shrpx_tls.Po
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: Your Xcode (6.1.1) is outdated.
Please update to Xcode 6.2 (or delete it).
Xcode can be updated from the App Store.

Error: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Error: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by alcaeus** [comment]
Quoting from the error message:
> Error: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.

What do you expect when you try to run this on 10.9?

**Comment by theredled** [comment]
True. I read somewhere it worked but indeed it's not officially supported.
Anyway for the record, I solved this with `--with-httpd22`!
