### ISSUE TITLE
Unable to build php56 from source

### ISSUE THREAD

**Issue by muchar** [Homebrew/homebrew-php#4378]
## Description
During a recent update, my php56 and php71 builds crashes with a spectacular message shown below.

## Context and Logs
==> make
Last 15 lines from /Users/mucharek/Library/Logs/Homebrew/php56/02.make:
make: *** [sapi/cgi/php-cgi] Error 1
make: *** Waiting for unfinished jobs....
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_syslog$DARWIN_EXTSN", referenced from:
      _php_mail in mail.o
      _php_mail_log_to_syslog in mail.o
      _zif_syslog in syslog.o
      _php_log_err in main.o
      _zlog_ex in zlog.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/fpm/php-fpm] Error 1

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13_
**Homebrew version:**   | _Homebrew 1.3.1_
**PHP version in use:** | _PHP 7.1.7 (cli) (built: Jul 10 2017 21:39:27) ( NTS )_
**Xcode version:**      | _Xcode 9.0_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.26)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 10 2017 21:39:27) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
https://gist.github.com/503cb6f60f8ef004703a1198484a2f11

**Comment by javian** [comment]
Can you verify that you are using the updated versions of Xcode and CLT if either of those are installed ? The information provided isn't detailed enough. You can also `cat /Applications/Xcode-beta.app/Contents/version.plist` to find the installed Xcode version.

**Comment by muchar** [comment]
After looking at the solution in #4381, I noticed I had two Xcode installations - one Xcode Beta 5 and one normal Xcode. Probably the later was used to compile code. After deleting the normal Xcode, everything went well.

So - I'm closing this issue.
