### ISSUE TITLE
install php71 on macos 10.13 beta5  make error

### ISSUE THREAD

**Issue by hainuo** [Homebrew/homebrew-php#4381]
## Description

Undefined symbols for architecture x86_64:
  "_syslog$DARWIN_EXTSN", referenced from:
      _php_mail in mail.o
      _php_mail_log_to_syslog in mail.o
      _zif_syslog in syslog.o
      _php_log_err_with_severity in main.o
      _vzlog in zlog.o
Undefined symbols for architecture x86_64:
Undefined symbols for architecture x86_64:
  "_syslog$DARWIN_EXTSN", referenced from:
  "_syslog$DARWIN_EXTSN", referenced from:
      _php_mail in mail.o
      _php_mail_log_to_syslog in mail.o
      _zif_syslog in syslog.o
      _php_mail in mail.o
      _php_mail_log_to_syslog in mail.o
      _zif_syslog in syslog.o
      _php_log_err_with_severity in main.o
      _php_log_err_with_severity in main.o
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/fpm/php-fpm] Error 1
make: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
make: *** [sapi/cli/php] Error 1
==> Formula
Tap: homebrew/php
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php71.rb
==> Configuration
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fdac095b1d93db3483978fae3017df023f8f23f1
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.2 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_144
macOS: 10.13-x86_64
Xcode: 9.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 9.0.0.0.1.1501856957
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/libxml2:/usr/local/opt/readline:/usr/local/opt/openssl:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.13
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/gettext/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/openssl/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: homebrew/php/php71 7.1.8 did not build
Logs:
     /Users/hainuo/Library/Logs/Homebrew/php71/00.options.out
     /Users/hainuo/Library/Logs/Homebrew/php71/01.configure.cc
     /Users/hainuo/Library/Logs/Homebrew/php71/02.make.cc
     /Users/hainuo/Library/Logs/Homebrew/php71/config.log
     /Users/hainuo/Library/Logs/Homebrew/php71/01.configure
     /Users/hainuo/Library/Logs/Homebrew/php71/02.make

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13_
**Homebrew version:**   | Homebrew 1.3.1 Homebrew/homebrew-core (git revision fdac; last commit 2017-08-13)
**PHP version in use:** | /usr/bin/php PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )Copyright (c) 1997-2017 The PHP Group Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
**Xcode version:**      | _Xcode 9.0 Build version 9M189t_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.31)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** 
https://gist.github.com/4c986142e575be470a8c14b341b02622

**Comment by muchar** [comment]
Got the exact same issue in #4378.

**Comment by javian** [comment]
@hainuo Can you verify that you are using the updated versions of Xcode and CLT if either of those are installed ? The information provided isn't detailed enough. You can also cat /Applications/Xcode-beta.app/Contents/version.plist to find the installed Xcode version.

**Comment by hainuo** [comment]
@javian   
![image](https://user-images.githubusercontent.com/421861/29343002-dde3349c-81f3-11e7-81c2-75783b1cfc69.png)

this it is!

**Comment by hainuo** [comment]
just find that   the Xcode is Xcode 9.0 beta 4

**Comment by javian** [comment]
Accordng to this there is a beta 5 version released https://developer.apple.com/testflight/release-notes/ . Can you try upgrading and see if it still fails ?

**Comment by hainuo** [comment]
thx your sugess.  it works well when upgrade to Xcode beta 5
