### ISSUE TITLE
php70-intl

### ISSUE THREAD

**Issue by m1k3lm** [Homebrew/homebrew-php#4386]
## Description

Error after installing php70-intl 

## Context and Logs

````
php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 7.0.22 (cli) (built: Aug  7 2017 14:07:27) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
````

brew install -s php70-intl or brew install --build-from-source php70-intl don't solve the problem.

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | Homebrew 1.3.1
**PHP version in use:** | PHP 7.0.22
**Xcode version:**      | Xcode 8.3.3

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 7.0.22 (cli) (built: Aug  7 2017 14:07:27) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:** https://gist.github.com/0bdd544ab35212fa3e6505d13f7d9815

**Comment by dennis-berg** [comment]
Same problem, tried reinstalling both from sources and not or php70, php70-intl, icu4c, but nothing works.

**Comment by javian** [comment]
We are awaiting the build of a PR to fix this since some additional code needed to be added to the Formula to make it work see #4392

**Comment by javian** [comment]
This issue should be resolved now.

**Comment by m1k3lm** [comment]
Thanks!

**Comment by tnorthcutt** [comment]
For anyone else stumbling on this, what worked for me was running
```
brew reinstall --build-from-source php70-intl
```
