### ISSUE TITLE
Create phan 0.9.4/0.8.6 release

### ISSUE THREAD

**Issue by TysonAndre** [Homebrew/homebrew-php#4394]
Those were created today, see https://github.com/etsy/phan/releases (I don't have the hardware to verify this)

Also, phan 0.9.5 (next release) will likely require updating ext-ast from 0.1.4 to 0.1.5 (C PHP module)

**Comment by javian** [comment]
Thanks for the information @TysonAndre - would you mind creating the pull requests to change this ?

**Comment by javian** [comment]
This has now been merged.
