### ISSUE TITLE
Link against Homebrew sqlite3

### ISSUE THREAD

**Issue by kosiokarchev** [Homebrew/homebrew-php#4398]
I recently installed PHP 7.2 and found out that the SQLite3 module it uses does not have ICU support. I found out from an old issue [(#702)](https://github.com/Homebrew/homebrew-php/issues/702) that PHP ships its own sqlite3 library and header.
Nevertheless, is there a way to enable PHP to link against the Homebrew version of SQLite3 in order to have control over the extensions that are installed?

**Comment by javian** [comment]
Hi @kosiokarchev . The following snippet is from the php source.
```
        dnl As long as intl is not shared we can have ICU support
    if test "$PHP_INTL" = "yes" && test "$PHP_INTL_SHARED" != "yes"; then
      other_flags="$other_flags -DSQLITE_ENABLE_ICU=1"
    fi
```
currently in the php tap intl is a shared module which seems to prevent sqlite3 to use icu. It might be that https://github.com/Homebrew/homebrew-core/pull/16067 will change this since that does not put intl into a shared module.
