### ISSUE TITLE
php7x-yar need

### ISSUE THREAD

**Issue by dongm2ez** [Homebrew/homebrew-php#4441]
## Description

this ext  in php7x is not add

**Comment by SMillerDev** [comment]
Pull requests are welcome to add Yar support for php7+. It seems like nobody used it with those versions yet

**Comment by mdeboer** [comment]
@dongm2ez do you also require [msgpack](https://github.com/msgpack/msgpack-php)?

**Comment by wenpeng** [comment]
Need Yar extension support too.

**Comment by alcaeus** [comment]
Quoting @SMillerDev:

> Pull requests are welcome to add Yar support for php7+. It seems like nobody used it with those versions yet

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
