### ISSUE TITLE
Is it possible to get 5.6.30 instead of 5.6.31?

### ISSUE THREAD

**Issue by resting** [Homebrew/homebrew-php#4453]
`mysql_escape_string()` seems to be remove in 5.6.31.
I had 5.6.30 setup on another machine and that works fine.

Is it possible to install 5.6.30 instead?
Currently, I'm running `brew install php56`.

**Comment by SMillerDev** [comment]
It's been deprecated since 4.3.0 but it's only removed in PHP7 (http://www.php.net/ChangeLog-5.php#5.6.31)

As for switching to older versions, if it hasn't been cleaned up yet `brew switch php56 5.6.30` is the way to go

**Comment by SMillerDev** [comment]
Did this solve your issue?

**Comment by bunalng** [comment]
i need to switch old php version too:
brew switch php56 5.6.30
Error: php56 does not have a version "5.6.30" in the Cellar.
Versions available: 5.6.31_7

how can swtich to older version?

**Comment by resting** [comment]
@bunalng did you try `brew switch php56 5.6.30` suggested above?
I actually compiled my own `5.6.30` before I saw suggestion, so never got a chance to try it out yet.

**Comment by bunalng** [comment]
@resting yes i tried. but there no older versions.

**Comment by bunalng** [comment]
i really need older than 5.6.30

**Comment by SMillerDev** [comment]
you can try and edit the formula using `brew edit <formula_name>` and install that way. Homebrew isn't really like other package managers in this regard. It doesn't keep around old minor versions of software.

**Comment by bunalng** [comment]
i tried that but i failed. i need a good guide for brew formula editing.

**Comment by SMillerDev** [comment]
The documentation on Formulae is here: https://docs.brew.sh/Formula-Cookbook.html
