### ISSUE TITLE
I can't run phpmyadmin after installing

### ISSUE THREAD

**Issue by carlosmq** [Homebrew/homebrew-php#4458]
## Description

I can't run phpmyadmin after installing

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |   10.12.6 
**Homebrew version:**   |  1.3.2. 
**PHP version in use:** |  7.2.0beta3 _your PHP version (output of `/path/to/php -v`)_
**Xcode version:**      | 8.3.3 _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.2.0beta3 (cli) (built: Aug 23 2017 09:46:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0beta3, Copyright (c) 1999-2017, by Zend Technologies

**Build logs:** Error: No logs. (Or I didn't know what is the Formula for this)

**Issue:**
I installed phpmyadmin (brew install phpmyadmin) and I followed the instructions: 
1.- to add Alias and <Directory ...> into/etc/apache2/httpd.conf
2.- change your secret blowfish
3.- uncomment the configuration lines (pma, pmapass ...)

Then I try go to http://localhost/phpmyadmin
But result was: Not Found / The requested URL /phpmyadmin/ was not found on this server.

After that I restarted apache ant try again with http://localhost/phpmyadmin
but, result was: File not found. 

I verified URLs of 'Alias /phpmyadmin /usr/local/share/phpmyadmin' and '<Directory /usr/local/share/phpmyadmin/>...' ant they are correct, so, I don't know what to do next.

Today is my second day using Homebrew, I like it! 
Could you help me?
Thank you in advance

**Comment by SMillerDev** [comment]
This looks like a configuration issue with apache, can you see in your apache logs what file it tries to read that it can't access?

**Comment by carlosmq** [comment]
SSMillerDev, thank you. It is the error in error_log at /usr/local/var/log/apache2/error_log:
[Mon Sep 11 11:39:55.729374 2017] [proxy_fcgi:error] [pid 81356] [client 127.0.0.1:57108] AH01071: Got error 'Primary script unknown\n'

**Comment by SMillerDev** [comment]
[This SO](https://stackoverflow.com/questions/23162762/apache2-4-php-fpm-phpmyadmin-in-debian) issue seems to be very similar to what you're experiencing. Maybe that can help?

**Comment by carlosmq** [comment]
Thank you SMillerDev, I'll check it.

**Comment by SMillerDev** [comment]
Is this now solved?
