### ISSUE TITLE
Getting dyld: Library not loaded error

### ISSUE THREAD

**Issue by kyoukhana** [Homebrew/homebrew-php#4462]
## Description

I am getting the following error when running brew update.  Not sure how to correct this issue. 

/usr/local/Cellar/httpd24/2.4.27: 1,624 files, 25.8MB
dyld: Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
composer: PHP Phar support is required for this formula

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _your macOS version (10.12.6)_
**Homebrew version:**   | _your Homebrew version (1.3.2)_
**PHP version in use:** | _your PHP version (error)_
**Xcode version:**      | _your Xcode version (output of `8.3.3`)_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
_result of the CLI output_
Getting the following error
dyld: Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found

**Build logs:** _Link to public gist created with ``_

**Comment by SMillerDev** [comment]
What PHP version do you have installed? 
Because issues: #4376 and #4358 seem to be related.
Could you try with the solutions suggested there?

**Comment by kyoukhana** [comment]
Thanks for the help in sort answer this is the best fix

```
wget -c http://www.ijg.org/files/jpegsrc.v8d.tar.gz
tar xzf jpegsrc.v8d.tar.gz
cd jpeg-8d
./configure
make
cp ./.libs/libjpeg.8.dylib /usr/local/opt/jpeg/lib
```
