### ISSUE TITLE
Can't install with php70 with mysql

### ISSUE THREAD

**Issue by deepakagrawal121** [Homebrew/homebrew-php#4463]
I am not able to install mysql pdo driver on max osx sierra

Warning: homebrew/php/php70: this formula has no --with-fpm option so it will be ignored!
Warning: homebrew/php/php70: this formula has no --with-mysql option so it will be ignored!
Warning: homebrew/php/php70: this formula has no --without-apache option so it will be ignored!

How to install mysql driver?

**Comment by SMillerDev** [comment]
FPM, Apache and mysql are all defaults as seen here:[/Abstract/abstract-php.rb]( https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb)

**Comment by SMillerDev** [comment]
Is this issue now resolved?
