### ISSUE TITLE
Pull requests waiting for merges

### ISSUE THREAD

**Issue by alcaeus** [Homebrew/homebrew-php#4468]
Creating an issue to get maintainer attention here. A bunch of pull requests have been sitting open for almost a month: new formulae, fixes for extensions for PHP 7.2 (API version mismatch in the bottles which requires a reinstall from source), RC2 of PHP 7.2, PHP 7.1, and so on. Could we have an update when these pull requests will be merged?

**Comment by josegonzalez** [comment]
Hi @alcaeus!

Sometimes the maintainers have to do extra work on top of any pull requests made (local verification, bumping bottles, investigating whether a "fix" actually fixes something). Other times, they are just busy with things outside of homebrew-php - back when I was maintaining this, my org was gracious enough to give me work time to look over pull requests, but that was by no means my only work task.

I believe that once the active maintainers have a chance, they'll look at the open PRs and merge them. If you have any that you think need urgent attention, please mention me in them and I will attempt to take a look at the end of my work day, assuming one of the other maintainers hasn't already.

Thanks for your patience!

**Comment by alcaeus** [comment]
No worries - I know it's difficult to find the time to take care of OSS work. It's just unusual since pull requests were usually merged quickly. I'll take some time to pick out the pull requests that are more "urgent" than others (quotes since none of these are really urgent, it'd just be nice to get the new versions).

**Comment by alcaeus** [comment]
@josegonzalez off the top of my head, the new PHP versions would be the most important ones:
* PHP 7.1.9: https://github.com/Homebrew/homebrew-php/pull/4457
* PHP 7.0.23: https://github.com/Homebrew/homebrew-php/pull/4474
* PHP 7.2.0RC2: https://github.com/Homebrew/homebrew-php/pull/4465 (RC1 hasn't been merged, so it would be nice to get an RC version in brew - subsequent RCs could theoretically wait a little longer)

Unfortunately, there's a bunch of [pull requests to rebuild php72 bottles](https://github.com/Homebrew/homebrew-php/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20author%3Aalcaeus%20revision) - these are tedious to manually merge but unfortunately required since existing bottles have been compiled against the wrong API version somehow.
