### ISSUE TITLE
Segfault on lauching php56

### ISSUE THREAD

**Issue by muchar** [Homebrew/homebrew-php#4487]
## Description

After multiple reinstallation's, reconfigurations and so on, I just can't manage to launch php anyhow. All I get is:

```
php app/console cache:warmup --env=prod
fish: 'php app/console cache:warmup --…' terminated by signal SIGSEGV (Address boundary error)
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13
**Homebrew version:**   | Homebrew 1.3.4, Homebrew/homebrew-core (git revision 168b6; last commit 2017-09-27)
**Xcode version:**      | Xcode 9.0, Build version 9M202q

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.34.1)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

What else can I provide to fix this problem?

**Comment by SMillerDev** [comment]
What happens when you run `php -v` or `php -i`? Because this seems like you're debugging with a fairly extensive application.

**Comment by muchar** [comment]
That works well. The application on which I'm testing worked earlier - just stopped after updating php56 (when I had problems with libjpeg eg.). On php71 - it works well. Is there anything I can do to find whats the culprit?

**Comment by SMillerDev** [comment]
Can't think of anything specific to homebrew that can help you diagnose it. But luckily there's stackoverflow: https://stackoverflow.com/questions/13079513/how-do-i-diagnose-this-php-segmentation-fault

**Comment by muchar** [comment]
OK, probably some problem on my side. Closing issue.
