### ISSUE TITLE
Arcanist Formula Has Bad SHA

### ISSUE THREAD

**Issue by Roguelazer** [Homebrew/homebrew-php#4488]
## Description

The SHA256 in the arcanist formula in this is bad. This doesn't affect people on Sierra (which has a bottle), but prevents installing Arcanist on High Sierra.

Possibly related to #4055?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | Homebrew 1.3.4
**PHP version in use:** | 7.1.8

**Output of `gcc -v`:**

```
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**

```
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Build logs:**

```
% brew reinstall -s homebrew/php/arcanist
==> Reinstalling homebrew/php/arcanist
==> Downloading https://github.com/wikimedia/arcanist/archive/release/2017-03-08/1.tar.gz
==> Downloading from https://codeload.github.com/wikimedia/arcanist/tar.gz/release/2017-03-08/1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 8edb125944f9aa3dc5ea082f2b080543ae324dba3cb055476f1db40219f222e6
Actual: 95f966e1ba0ebce75cf237c7776b76adb4c24dfc844f80617b4a257c353754d2
Archive: /Users/jbrown/Library/Caches/Homebrew/arcanist-201703081.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by alcaeus** [comment]
This looks more like it's caused by the same thing that caused #4484. Maybe @peff could confirm this?

**Comment by peff** [comment]
Hmm, yeah, it is. My script didn't catch it because the slashes in the tagname threw off my parsing (the archives GitHub generates convert the to dashes when feeding the `--prefix` to `git archive`).

**Comment by alcaeus** [comment]
@peff Thanks for confirming it. #4489 updates to the latest version and fixes the problem at hand.

**Comment by peff** [comment]
@alcaeus Looks good. My script (with the bug fixed) just finished running, and those two were the only hits.
