### ISSUE TITLE
PHP formulas need to be updated to work with httpd migrated to core

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-php#4493]
## Description

Recently, httpd has moved from tap homebrew/apache to homebrew-core. The php formulas will need to be updated to work with the new httpd locations and setup. 

## Context and Logs

For ex. php formulas such as php71 will need a new option ```--with-httpd``` instead of ```--with-httpd24```. And php formulas should not tap homebrew/apache anymore - currently getting a lot of these warnings trying to recompile php:

```
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
```

**Comment by javian** [comment]
This should now have been fixed through merging #4500
