### ISSUE TITLE
Can't install php56 --with-libmysql  :(

### ISSUE THREAD

**Issue by asiop** [Homebrew/homebrew-php#4501]
## Description

Can't install php5.6 with mysql on httpd24, I keep getting this error even on a fresg brew with nothing installed.

I try to run:
brew install php56 --with-libmysql --with-httpd24

The result is:
configure: error: Cannot find libmysqlclient_r under /usr/local.
Note that the MySQL client library is not bundled anymore!

## Context and Logs

Parameter | Value
--------- | ------------------
10.12.6       | _your macOS version (output of `sw_vers -productVersion`)_
Homebrew 1.3.4  | _your Homebrew version (output of `brew --version`)_
5.6 | _your PHP version (output of `/path/to/php -v`)_
Xcode 9.0      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 5.6.31 (cli) (built: Oct  3 2017 21:36:10) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** https://gist.github.com/a0ba5fdfcd750d9ff9e0ce1fa33e46cd

**Comment by asiop** [comment]
Well you can say that also about anything that’s PHP today, unfortunately…

But yeah, I got a huge codebase that has been growing steadily for like 16 years… and was maintained rather well.. I wanted to start to migrate it to 7.1 and for that I need the new php alongside the old (to take care of bugs and development while on parallel on a different branch for upgrading)

Because of all the breaking changes in PHP I’ll have to test the code well and thoroughly before I can deploy the upgrade. so Ironically I need 5.6 to get rid of 5.6. I spent the entire day working on it till I understood it must be a bug. 
An alternative I could probably consider could be to move back and forth from the original lamp installment that’s on the mac os and the brew httpd + php7.1. That might work, but, people who read on the web how to brew 5.6 + mysql will have to spend many hours just like I did before coming to the conclusion that is supported no more, it’s a shame. 
Also one of the nice features of brew is to switch between version, it’s a shame you won’t have it with php anymore. PHP 5.6 will receive security support till dec 31, 2018, so there will be more people looking for answers even if not many, so while this is not dealing with cutting edge technology it could still benefit many people. 

So maybe the docs should be updated, and "brew options” at least should be updated to reflect the discontinuity of this feature. Probably the —with-libmysql option should be removed completely, maybe docs could offer the alternative and  recommend the native lap installation, which will practically become the only options for 5.6 developers, there are still some guides out there on the web of how to use brew to install php 5.6 + mysql, but that’s beyond us.

So yeah, if it’s a small thing to fix it will be a good service for a few developers but you people developing brew is an amazing contribution to the community anyhow, and you should set the priorities for your precious time, thank you very much for brew!




On 4 Oct 2017, at 0:37, Jan Viljanen <notifications@github.com> wrote:

So you might have stumbled upon something that is rarely used and not tested very often. Do you really need to use the old libmysqlclient library ?

**Comment by bunalng** [comment]
i need old mysql library too.

**Comment by trsteel88** [comment]
Require old mysql library for legacy projects also.

**Comment by SMillerDev** [comment]
Just ran some tests on this and it appears the issue only appears when it tries to build apache and libmysql. It works with just apache or just mysql.

**Comment by adc91** [comment]
I'm getting the same error and I'm not finding a solution.

**Comment by mmigliaccio** [comment]
Same problem for me :-(

**Comment by fjeddy** [comment]
Ran into the same problem today trying to use a library that was made for PHP 4.X and use `mysql_connect`

**Comment by bunalng** [comment]
i found a solution:
just copy in `/usr/local/lib`:
```
libmysqlclient.a -> libmysqlclient_r.a
libmysqlclient.dylib -> libmysqlclient_r.dylib
```

try to install php with:
`brew install php56 --with-libmysql --with-httpd --with-pear --build-from-source`

there is no problem for now.

**Comment by nahuelhds** [comment]
@bunalng that solution worked for me!

It should be desirable that old mysql extension could be compiled without this workaround as a lot of people (as me) have many legacy projects with big codebases in production that cannot be updated (because of the costs, EOL, clients decisions, or any other valid reason).

**Comment by kitsguru** [comment]
same problem here. I pinned 5.6.31 along with packages that had it as a dependency.

**Comment by bunalng** [comment]
i think 5.6.29 or older has not this problem. but i cant install older versions. `brew switch` show me latest version always.

**Comment by nd-** [comment]
Thx @bunalng for the tip, it worked for me with php 5.6.32 and mysql.
Unfortunately, it doesn't work with mariadb...

When i `brew link mariadb`i see there are already libmysqlclient_r.a and libmysqlclient_r.dylib so i didn't copy libmysqlclient.a and libmysqlclient.dylib, but the make doesn't work:

> ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found

But i agree with the other comments, the old mysql extension shouldn't have been removed.
We use brew mainly for developpment/testing, and we need to support a large and often old codebase.

**Comment by adc91** [comment]
Thanks for the solution @bunalng. It worked perfect for me.

Unfortunately there are customers who choose to keep obsolete versions on their server to reduce costs and to adapt to them.

**Comment by Wilkolicious** [comment]
Same situation as @nd- here.  Using MariaDB and failing to make php56, php70, php71 for the past few versions.  Have also tried @bunalng's approach, but no cookie.
As much as I'd like to stop using it, legacy work code means I need it.
```
/bin/sh /private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/libtool --silent --preserve-dup-deps --mode=compile clang  -Iext/mysql/ -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mysql/ -DPHP_ATOM_INC -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/include -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/main -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32 -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/date/lib -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/ereg/regex -I/usr/local/Cellar/libxml2/2.9.7/include/libxml2 -I/usr/local/opt/openssl/include -I/usr/local/opt/jpeg/include -I/usr/local/opt/libpng/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gettext/include -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mbstring/oniguruma -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mbstring/libmbfl -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mbstring/libmbfl/mbfl -I/usr/local/include/mysql -I/usr/local/Cellar/mariadb/10.2.10/include/mysql -I/usr/local/Cellar/mariadb/10.2.10/include/mysql/.. -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/sqlite3/libsqlite -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/zip/lib -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/TSRM -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/Zend  -no-cpp-precomp  -I/usr/include -g -O2 -fvisibility=hidden -DZEND_SIGNALS  -c /private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mysql/php_mysql.c -o ext/mysql/php_mysql.lo
/bin/sh /private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/libtool --silent --preserve-dup-deps --mode=compile clang  -Iext/mysqli/ -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mysqli/ -DPHP_ATOM_INC -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/include -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/main -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32 -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/date/lib -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/ereg/regex -I/usr/local/Cellar/libxml2/2.9.7/include/libxml2 -I/usr/local/opt/openssl/include -I/usr/local/opt/jpeg/include -I/usr/local/opt/libpng/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gettext/include -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mbstring/oniguruma -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mbstring/libmbfl -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mbstring/libmbfl/mbfl -I/usr/local/include/mysql -I/usr/local/Cellar/mariadb/10.2.10/include/mysql -I/usr/local/Cellar/mariadb/10.2.10/include/mysql/.. -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/sqlite3/libsqlite -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/zip/lib -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/TSRM -I/private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/Zend  -no-cpp-precomp  -I/usr/include -g -O2 -fvisibility=hidden -DZEND_SIGNALS  -c /private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mysqli/mysqli.c -o ext/mysqli/mysqli.lo
In file included from /private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mysql/php_mysql.c:69:
ext/mysql/php_mysql_structs.h:42:10: fatal error: 'mysql.h' file not found
#include <mysql.h>
         ^~~~~~~~~
1 error generated.
make: *** [ext/mysql/php_mysql.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from /private/tmp/php56-20171109-9720-1ueimqs/php-5.6.32/ext/mysqli/mysqli.c:34:
ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [ext/mysqli/mysqli.lo] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:210:in `raise_api_error': GitHub  (GitHub::AuthenticationFailedError)
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:135:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by Wilkolicious** [comment]
Sorry for the bump, but the following worked:
1. `brew unlink mariadb`
2. `brew install mysql` - ensure mysql is installed
3. `brew link mysql` - use mysql's source to compile lib
4. `brew install php56 --with-httpd --with-libmysql` (also works for `php70` & `php71`)
5. `brew unlink mysql`
6. `brew link mariadb` - return back to mariadb

**Comment by bunalng** [comment]
perfect job @Wilkolicious. i tried to run libmysql with php7 but i could't achieved.
