### ISSUE TITLE
PHP extensions need to be built from source in non standard Homebrew roots

### ISSUE THREAD

**Issue by sandrinr** [Homebrew/homebrew-php#4502]
## Description

When using a Homebrew instance which is not installed in the standard root (`/usr/local`) and installing a php extension, such as apcu (`brew install homebrew/php/php70-apcu`), the extension is installed from a bottle. When PHP tries to load the extension you get the error:
```
[...] Symbol not found: _compiler_globals
```

The issue can be worked around with with `brew install homebrew/php/php70-apcu --build-from-source`

My guess is the Formula needs to be changed to enforce source build outside of the Homebrew standard installation.

**Comment by josegonzalez** [comment]
@sandrinr do you have a link to how other, non-php formula handle that?

**Comment by sandrinr** [comment]
I am not really a Homebrew hacker, but I think this may be achieved with the [cellar](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md#cellar-cellar) setting inside the `bottle` block. For example, in the [php-apcu](https://github.com/Homebrew/homebrew-php/blob/9b7f4128df963895e888c550a400891a0ed1d287/Formula/php70-apcu.rb#L12) there is sth going on with the cellar.

**Comment by josegonzalez** [comment]
Gotcha, so a pull request that removes :cellar from our extensions probably will fix the issue?

**Comment by josegonzalez** [comment]
If you can test removing that and seeing if it works, that'd be awesome :)

**Comment by javian** [comment]
@sandrinr this has nothing to do with the Cellar. You are trying to use a thread-safe php with a non-threadsafe extension and that's why it works when you install it from source.
