### ISSUE TITLE
phpXX-ioncubeloader can not be used

### ISSUE THREAD

**Issue by Eydamos** [Homebrew/homebrew-php#4504]
# Description

When you install ioncubeloader via homebrew you will get the following error:

> Failed loading /usr/local/opt/php70-ioncubeloader/ioncubeloader.so:  dlopen(/usr/local/opt/php70-ioncubeloader/ioncubeloader.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php70-ioncubeloader/ioncubeloader.so
  Expected in: flat namespace
 in /usr/local/opt/php70-ioncubeloader/ioncubeloader.so

The Q&A on the ioncube page states that this error is caused by using thread safe php without the using the thread safe version of the ioncubeloader.
The same problem currently occurs with all php modules you install with homebrew.
The current usual workaround for that is to install the module from source `brew reinstall php70-ioncubeloader --build-from-source`.
Unfortunately this does not work as the hash is not correct:

> ==> Reinstalling homebrew/php/php70-ioncubeloader 
==> Downloading http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_dar_x86-64.tar.gz
Already downloaded: /Users/wv/Library/Caches/Homebrew/php70-ioncubeloader-6.0.9.tar.gz
Error: SHA256 mismatch
Expected: 1c9b17a4750578299277cc69631769ecc63708da0b12253cb333434add10332a
Actual: af0b548d0e27e6fea9f0b5ee73b2c2099e1cd67f6dd9fd74d2e718ff151d994f
Archive: /Users/wv/Library/Caches/Homebrew/php70-ioncubeloader-6.0.9.tar.gz
To retry an incomplete download, remove the file above.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | maxOS Sierra 10.12.4
**Homebrew version:**   | Homebrew 1.3.4
**PHP version in use:** | PHP 7.0.23
**Xcode version:**      | Xcode 9

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP 7.0.23 (cli) (built: Oct  2 2017 16:15:18) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.23, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by SMillerDev** [comment]
The default PHP settings in homebrew are not to have it threadsafe. So any binaries will be generated against the non-threadsafe version and won't work with your install. Unfortunately that means that you have to install them from source.

**Comment by Eydamos** [comment]
Then I wonder why php will currently always be generated thread safe and there is no option to disable this.

Also as you can see at the end of my description I already tried to build it from source which fails based on the outdated checksum.

**Comment by SMillerDev** [comment]
The outdated checksum can be fixed by editing the formula to represent the current SHA of the file. Unfortunately the ioncubeloader downloads aren't versioned so there's no way to keep those in sync other than user contributions.

As for the thread safety, Homebrew PHP isn't thread safe by default. The version you have installed isn't the default homebrew version that all the binaries are build against.

**Comment by Eydamos** [comment]
I have not compiled php with thread safety.
I installed php with this command `brew install php56 --with-httpd` and it was automatically thread safe and screwed up my environment as I had to recompile every additional php module I have installed. Same for php55, php70 and php71

**Comment by javian** [comment]
This has to do with the new httpd Formula. When PHP is compiled it tries and detect in which mode apache is running and the new formula is using (can't recall the name right now) what forces PHP to be compiled as thread safe and this is the root cause of the issue.

**Comment by Eydamos** [comment]
So is there a way to compile it with httpd and without safe thread option? I use heombrew for several years now and never had this issue before.

**Comment by woutersamaey** [comment]
+1 - I'm facing the same issue. PHP is now thread safe and broken. Don't know how to switch back to non-thread safe :(

**Comment by SMillerDev** [comment]
The merging of #4464 should at least fix the issue with building from source.

**Comment by Eydamos** [comment]
--build-from-source now doesn't gives an error but still uses the non thread safe version. Looking at the PR you mentioned the formula just extracts the .tar.gz and moves the .so file to a specific place.
As the source is not actually included in the archive it will not be compiled.

I would recommend a --with-tread-safe option for ioncubeloader which moves the _ts.so file instead of the one without the _ts

I'm not familiar with Ruby (I think .rb files are ruby right?) so I can't create a pull request for this

**Comment by RobRoy** [comment]
If you face this issue, a workaround for this is loading the ioncube loader archive from https://www.ioncube.com/loaders.php and extract the thread safe version "ioncube_loader_dar_x.x_ts.so" into whatever directory your php.ini references and change the zend_extension path accordingly.

**Comment by Eydamos** [comment]
That is what I'm currently doing to keep my installation running.

**Comment by ctrlaltca** [comment]
Isn't t easier to place both the normal and the _ts extensions to the extensions path and let the user load the correct one in the php config?

**Comment by ctrlaltca** [comment]
Looks like httpd is using the prefork module as default now: https://github.com/Homebrew/homebrew-core/commit/05859e7b2fa4bf90bea991617577c86258b3e521 , so the php module installed by phpXX-ioncubeloader is working on a default installation
