### ISSUE TITLE
With pdo-oci fails - Oracle required OCI8 libraries not found

### ISSUE THREAD

**Issue by vhorky** [Homebrew/homebrew-php#4505]
## Description
I'm trying to install php71 with pdo-oci extension via this command:
brew reinstall php71 --with-gmp --with-homebrew-curl --with-homebrew-libxml2 --with-homebrew-libxslt --with-httpd --with-imap --with-postgresql --without-legacy-mysql --with-pdo-oci

And it fails here
checking Oracle Install-Dir... /Library/Oracle/instantclient
checking if that is sane... yes
checking size of long int... (cached) 8
checking if we're on a 64-bit platform... yes
checking OCI8 libraries dir... configure: error: Oracle required OCI8 libraries not found

Thank you for any solution...

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13
**Homebrew version:**   | Homebrew 1.3.4 Homebrew/homebrew-core (git revision 602d95; last commit 2017-10-05)
**PHP version in use:** | PHP 7.1.8 (cli) (built: Sep  1 2017 16:23:13) ( NTS )
**Xcode version:**      | Build version 9A235

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.8 (cli) (built: Sep  1 2017 16:23:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by SMillerDev** [comment]
If I read https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb#L342 correctly it expects $ORACLE_HOME to be set to the location of the client libraries, while for you it seems like it points to the entire client.

What happens when you try and set it to the locations that are pointed out here: http://php.net/manual/en/oci8.installation.php?

**Comment by vhorky** [comment]
@SMillerDev There is no lib directory in instant client folder. According to this post it should point to instant client directory
https://blogs.oracle.com/opal/the-php-quotconfigure-with-oci8quot-option-in-detail

**Comment by SMillerDev** [comment]
That one mentions that you should "Only set ORACLE_HOME if you have a full Oracle install." 
Do you have a full install? Otherwise the easiest way to install might be using PECL or temporarily setting ORACLE_HOME to the library path like in option 8 of the link you provided.

**Comment by vhorky** [comment]
Well...
If I point it (ORACLE_HOME) to Instant client dir - I get the error above
If I point it to /usr/local/lib - I get the error above
And if I do not set ORACLE_HOME - I get 
> Error: Environmental variable ORACLE_HOME must be set to use --with-pdo-oci option.

**Comment by SMillerDev** [comment]
if you have an idea of what the install command should be / how it would work a PR would be much appreciated. I simply don't know enough about OCI to debug the PHP install of it. Otherwise I guess it's waiting until someone else picks this up.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
