### ISSUE TITLE
Can't load memcached with PHP 7.0

### ISSUE THREAD

**Issue by SamusAranX** [Homebrew/homebrew-php#4513]
## Description

I need both memcache and memcache**d** for a project I'm working on, but memcache**d** is refusing to work properly.

To install PHP 7.0 and all necessary extensions, I did this:

```
brew install php70 --with-httpd --with-pear --with-webp
brew install igbinary memcached php70-memcache php70-memcached
```

When I search `phpinfo()`'s output for "memcached", I only find this line:

1 | 2 
-------- | --------
Additional .ini files parsed | /usr/local/etc/php/7.0/conf.d/ext-igbinary.ini, /usr/local/etc/php/7.0/conf.d/ext-memcache.ini, /usr/local/etc/php/7.0/conf.d/ext-memcached.ini

The *.so files listed in those .ini files all exist and don't seem to be corrupt. At least, PHP's not giving me any error messages.

What's going on here?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | 1.3.5
**PHP version in use:** | 7.0.24 
**Xcode version:**      | 9.0 (9A235)

**Output of `gcc -v`:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**
```
PHP 7.0.24 (cli) (built: Oct 11 2017 12:54:55) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

**Build logs:** https://gist.github.com/anonymous/d26abc953f14a2eecfaec8b47ea89c1e

**Comment by SMillerDev** [comment]
Httpd currently makes the PHP install a thread safe version. (this is a known bug)
To be able to install with threadsafe PHP, compile the extension from source using `--build-from-source`.

**Comment by SamusAranX** [comment]
That solved my problem, thanks!
