### ISSUE TITLE
PHP 7.1 installation brew install php71 --php71-pdo-dblib fails 

### ISSUE THREAD

**Issue by jamesmartins** [Homebrew/homebrew-php#4514]
## Description

Hello Guys! I'm not getting connect db Sql server by MacOS Sierra with Homebrew installation.
My installation sequence is:
1 - /usr/bin/ruby -e “$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)”
2 -  brew update
3 - brew tap homebrew/php
4 - brew tap homebrew/apache
5 - brew install httpd
6 - brew install php71 --with-mssql --with-httpd24
7 - brew install --build-from-source php71-intl
8 - brew install --build-from-source php71-xdebug 
9 - brew install --build-from-source php71-pdo-dblib
10 - Httpd.conf and php.ini settings are made

## Context and Logs
Php mssql connection:
$connString = "dblib:host=" . $this->config['host'] . $port . ";dbname=" . $params['Database'];
		$user = $params['UID'];
		$password = $params['PWD'];
        try {
			$this->connection = new PDO($connString, $user, $password);
        } catch (PDOException $e) {
            "Failed to get DB handle: " . $e->getMessage() . "\n";
			$this->connected = false;
        }

Erro: PDOException: SQLSTATE[] (null) (severity 0)

Parameter | Value
--------- | ------------------
**macOS version:**    10.12.6
**Homebrew version:**   Homebrew 1.3.5 ((git revision 057e; last commit 2017-10-11)
**PHP version in use:** PHP 7.1.10
**Xcode version:**   not installed

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP Warning:  Module 'pdo_dblib' already loaded in Unknown on line 0
Warning: Module 'pdo_dblib' already loaded in Unknown on line 0
PHP 7.1.10 (cli) (built: Oct 11 2017 14:28:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

Regards!

**Comment by SMillerDev** [comment]
`php -v` suggests the code loading the pdo_dblib module is ran twice. Could it be that you load the extension on seperate from the config file that's automatically generated?

**Comment by jamesmartins** [comment]
Thanks! I fix this problem disabling the use of pdo_dblib in /usr/local/etc/php/7.1/conf.d/ext-pdo_dblib.ini.
My Output php -v:
PHP 7.1.10 (cli) (built: Oct 11 2017 14:28:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
My php -i:
phpinfo()
PHP Version => 7.1.10
...

...
PDO

PDO support => enabled
PDO drivers => dblib, mysql, odbc, sqlite

...

pdo_dblib

PDO Driver for FreeTDS/Sybase DB-lib => enabled
Flavour => freetds

...

PDO_ODBC

PDO Driver for ODBC (unixODBC) => enabled
ODBC Connection Pooling => Enabled, strict matching

...

odbc

ODBC Support => enabled
Active Persistent Links => 0
Active Links => 0
ODBC library => unixODBC
ODBCVER => 0x0380
ODBC_INCLUDE => -I/usr/local/opt/unixodbc/include
ODBC_LFLAGS => -L/usr/local/opt/unixodbc/lib
ODBC_LIBS => -lodbc

...

But my problem still continues. 
Erro: PDOException: SQLSTATE[] (null) (severity 0)

Thanks per attention!

**Comment by SMillerDev** [comment]
Googling the error suggests it's an error in your code:
https://stackoverflow.com/questions/19518175/pdoexception-with-message-sqlstate-null-severity-0

**Comment by jamesmartins** [comment]
Thanks again my friend! But I taken many hours googling a solution. When I use xdebug my variable 
$connString = "dblib:host=186.202.136.94:1433;dbname=ecommerce".
This variable is used in my code:
...
try {
$this->connection = new PDO($connString, $user, $password);
} catch (PDOException $e) {
"Failed to get DB handle: " . $e->getMessage() . "\n";
$this->connected = false;
}
...

I did the same installation sequence on my Debian Linux with success!!!
But on my Mac OS Sierra not still.
Thanks again!

**Comment by jamesmartins** [comment]
Hello Guys!! It's solved! I reinstalled all enviroment. I updated Sierra to High Sierra and followed steps: 
1 - Normal Homebrew installation.
2 - Normal Apache installation
3 - Installed with : brew install php71 --with-mssql  --with-httpd
4 - Open /usr/local/etc/freetds.conf
5 - Add "client charset = UTF-8" in global section
6 - $ sudo apachectl -k restart
7 - Sucesss!!
