### ISSUE TITLE
PHP 7.1.10 fails with opcache error if php71-opcache is installed on HighSierra

### ISSUE THREAD

**Issue by andig** [Homebrew/homebrew-php#4517]
## Description

PHP CLI failure:

	❯ php -i "(command-line 'phpinfo()')"               
	Failed loading /usr/local/opt/php71-opcache/opcache.so:  dlopen(/usr/local/opt/php71-opcache/opcache.so, 9): Symbol not found: _compiler_globals
	  Referenced from: /usr/local/opt/php71-opcache/opcache.so
	  Expected in: flat namespace
	 in /usr/local/opt/php71-opcache/opcache.so

The troubles started after upgrading to HighSierra, reinstalling apache and php to get rid of the OSX apache.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13
**Homebrew version:**   | 1.3.5-4-g56458f0
**PHP version in use:** | 7.1.10
**Xcode version:**      | 9.0

**Output of `gcc -v`:**

	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 9.0.0 (clang-900.0.37)
	Target: x86_64-apple-darwin17.0.0
	Thread model: posix
	InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**

	Failed loading /usr/local/opt/php71-opcache/opcache.so:  dlopen(/usr/local/opt/php71-opcache/opcache.so, 9): Symbol not found: _compiler_globals
	  Referenced from: /usr/local/opt/php71-opcache/opcache.so
	  Expected in: flat namespace
	 in /usr/local/opt/php71-opcache/opcache.so
	PHP 7.1.10 (cli) (built: Oct 11 2017 23:21:38) ( ZTS )
	Copyright (c) 1997-2017 The PHP Group
	Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
	    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:** https://gist.github.com/99c7a7c80bee28974da0fddd2f1aa013

**Comment by SMillerDev** [comment]
This is probably due to a bug with the `--with-httpd` flag forcing PHP into threadsafe mode. All the extension bottles however are compiled against the non-threadsafe version so they break. Workaround for now is using installing using the `build-from-source` flag.

**Comment by andig** [comment]
Out of despair I've installed 7.3rc3 plus opcache and apcu and didn't get this problem (yet). Shouldn't 7.3 be affected as well?

**Comment by SMillerDev** [comment]
I think you mean 7.2. But as far as I know all versions are affected.

**Comment by netpoe** [comment]
Hi. Any news about this issue?

`brew install php70` I'm getting: 

```
Failed loading /usr/lib/php/extensions/no-debug-non-zts-20160303/opcache.so:  dlopen(/usr/lib/php/extensions/no-debug-non-zts-20160303/opcache.so, 9): Symbol not found: _pcre_free
  Referenced from: /usr/lib/php/extensions/no-debug-non-zts-20160303/opcache.so
  Expected in: flat namespace
 in /usr/lib/php/extensions/no-debug-non-zts-20160303/opcache.so
```

while running:

```
php app/admin/cli/build_theme_css.php --themes=mibanco --verbose
```
