### ISSUE TITLE
Can't install php71, no formula found

### ISSUE THREAD

**Issue by jpmurray** [Homebrew/homebrew-php#4520]
## Description

I'm trying to install PHP71 on a new mac, but homebrew can't seems to find the required formula. I've added all the taps I usually do but it says it's deprecated now. Anyway, trying to `brew install php71` results in this:

```
Error: No available formula with the name "php71" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | brew reinstall php71 --with-httpd
**PHP version in use:** | 5.6.30 (default mac os install)
**Xcode version:**      | 9A235

**Output of `gcc -v`:**
brew reinstall php71 --with-httpd

**Output of `php -v`:**
brew reinstall php71 --with-httpd

**Comment by javian** [comment]
Have you tapped the tap ? `brew tap` will tell you.

**Comment by jpmurray** [comment]
Hum, I might have only tapped the old ones (dupes, etc). I'll see to it monday!

(Ping @ralphdion !)

**Comment by gerchicov-bp** [comment]
@jpmurray 
My initial issue:
`curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect`
google advices the following:
https://github.com/guzzle/guzzle/issues/1797
which leads me to the same bug you describe. Did you fix that?

**Comment by SMillerDev** [comment]
@gerchicov-bp wrong thread I think?
