### ISSUE TITLE
Can i install specific php version，Instead of stable version ?

### ISSUE THREAD

**Issue by phpforlan** [Homebrew/homebrew-php#4524]
## Description
when i execution command : brew install php70, brew will install the php version 7.0.24。
but i want to install php7.0.6，Are there any other solutions?  thanks very much.

## brew info php70 
homebrew/php/php70: stable 7.0.24 (bottled), HEAD
PHP Version 7.0
https://php.net
Conflicts with:
  php53 (because different php versions install the same binaries.)
  php54 (because different php versions install the same binaries.)
  php55 (because different php versions install the same binaries.)
  php56 (because different php versions install the same binaries.)
  php71 (because different php versions install the same binaries.)
  php72 (because different php versions install the same binaries.)

**Comment by SMillerDev** [comment]
You chould checkout a git revision of homebrew-php where php70 was pointing to 7.0.6 and install from source (not head as that always points to the PHP HEAD).
