### ISSUE TITLE
Cannot link php71: /usr/local/sbin is not writable

### ISSUE THREAD

**Issue by alxvallejo** [Homebrew/homebrew-php#4527]
## Description
I'm trying to install Laravel Valet, which requires php71, so when i run brew install php71 I run into this error:

> Could not symlink sbin/php-fpm
> /usr/local/sbin is not writable.

This also occurs if i try to manually link with brew link.

I don't even have an sbin directory so I'm pretty lost on how to proceed.

What is interesting is that if i run php -v, I get php 7.1.7, but when i run valet install, i get 

>Unable to determine linked PHP.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | High Sierra 10.13
**Homebrew version:**   | Homebrew 1.3.5
**PHP version in use:** | PHP 7.1.7
**Xcode version:**      | Xcode 9.0

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by SMillerDev** [comment]
Google provided me with this answer, maybe it helps? https://stackoverflow.com/questions/26647412/homebrew-could-not-symlink-usr-local-bin-is-not-writable

As for the PHP71 install, what was the full command you ran? What happens when you do `brew link php71`? What was the full error output?

**Comment by dadave92** [comment]
The folder /usr/local/sbin does not exists if i try to run this comment:
`sudo chown -R `whoami`:admin /usr/local/sbin`

Why does homebrew uses `sbin` instead of the `bin` folder?

**Comment by jrbin** [comment]
I have the same issue with linking hadoop.
I don't even have a `/usr/local/sbin` folder and `/usr/local/sbin` is not in my `PATH`.
My operating system is also OSX High Sierra 10.13 and home-brew version is 1.3.6
```
$ brew link hadoop
Linking /usr/local/Cellar/hadoop/2.8.1...
Error: Could not symlink sbin/distribute-exclude.sh
/usr/local/sbin is not writable.
```

**Comment by alxvallejo** [comment]
FWIW, this seemed to do the trick for me:
https://stackoverflow.com/questions/46778133/brew-link-php71-could-not-symlink-sbin-php-fpm?noredirect=1

**Comment by viktorbijlenga** [comment]
I’m having the same issue. +1

**Comment by Honest-Objections** [comment]
While I'm new to OSX, my guess is that the sbin folder is no longer created by default in High Sierra. Here is a nice [extract](http://blog.taylormcgann.com/2014/04/11/difference-bin-sbin/) explaining the folders purpose (as I was curious and din't want to make it arbitararily):

```
/bin
    This directory contains executable programs which are needed
    in single user mode and to bring the system up or repair it.

/sbin
    Like /bin, this directory holds commands needed to boot the 
    system, but which are usually not executed by normal users.
```

So to solve the problem, simply create the directory with ```sudo mkdir /usr/local/sbin``` and then set the correct ownership on it with ```sudo chown -R `whoami`:admin /usr/local/sbin```.

**Comment by MilkAndCat** [comment]
first Create an sbin in your local dir.
sudo mkdir sbin
then if you are running the High Sierra 10+
run 
sudo chown -R $(whoami) $(brew --prefix)/*

then you should be able to brew link php71
