### ISSUE TITLE
PHP 7.2 doesnt include sodium module

### ISSUE THREAD

**Issue by merk** [Homebrew/homebrew-php#4536]
## Description

With PHP 7.2 including the libsodium module in core, it seems like the compilation of PHP doesnt include --with-sodium, and no sodium module is installed or active in PHP.

```bash
# php -v
PHP 7.2.0RC3 (cli) (built: Oct  6 2017 00:22:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0RC3, Copyright (c) 1999-2017, by Zend Technologies
# php-7.2.0RC4 php -m | grep sodium
#
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   |1.3.5
**PHP version in use:** | 7.2.0RC3
**Xcode version:**      | not installed

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**

PHP 7.2.0RC3 (cli) (built: Oct  6 2017 00:22:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0RC3, Copyright (c) 1999-2017, by Zend Technologies

**Build logs:**
Error: No logs.

**Comment by merk** [comment]
I'd be happy to contribute a pull request, but I'm not certain how to handle a 7.2+ inclusion by default. Is there a way to do a version compare in self.init?

**Comment by SMillerDev** [comment]
I think argon has specific code for a php version in `Abstract/abstract-php.rb`. That would be a good starting point iyam. (if you can't find it I'll get you the line number)

**Comment by merk** [comment]
I feel that sodium should be installed by default on 7.2+, and it looks like argon isnt defined in that way? It seems to me like you'd want a --without-sodium option on the formula.

I dont see (with a peruse through some formulas) a method of being able to say "we want it for 7.2+, but provide an opt out mechanism" without adding it to the php72.rb formula directly, which means it needs to then be added to 7.3, and so on..?

**Comment by SMillerDev** [comment]
Closing this because the fix is merged
