### ISSUE TITLE
Where to find ext_skel for extension development?

### ISSUE THREAD

**Issue by cviebrock** [Homebrew/homebrew-php#4537]
I'm trying to use the [`ext_skel`](https://github.com/php/php-src/blob/master/ext/ext_skel.php) script that comes with PHP source ... used when creating extensions.

Any idea which brew formula I need to install to get this?

**Comment by SMillerDev** [comment]
There's no formulae that install PHP source. Just some that compile from source. I'm afraid you're gonna have to get this the old fashioned way, cloning the php source.

**Comment by cviebrock** [comment]
That's what I figured.  Thanks!

**Comment by cviebrock** [comment]
Quick followup ... what about `ext/mbstring/php_unicode.h`?  The other header files are available, but not that one.

```sh
$ ls /usr/local/Cellar/php71/7.1.10_21/include/php/ext/mbstring/*.h

/usr/local/Cellar/php71/7.1.10_21/include/php/ext/mbstring/mbstring.h
/usr/local/Cellar/php71/7.1.10_21/include/php/ext/mbstring/php_mbregex.h
/usr/local/Cellar/php71/7.1.10_21/include/php/ext/mbstring/php_onig_compat.h
```

Compared to the PHP source files, it also looks like `mb_gpc.h` and `unicode_data.h` are missing (although the later is probably not required).

**Comment by javian** [comment]
They are not listed in the configure files
```
➜  mbstring git:(master) ✗ grep PHP_INSTALL_HEADERS *
config.m4:  PHP_INSTALL_HEADERS([ext/mbstring], [$PHP_MBSTRING_INSTALL_HEADERS])
config.w32:		PHP_INSTALL_HEADERS("ext/mbstring", "mbstring.h oniguruma/oniguruma.h php_mbregex.h php_onig_compat.h");
config.w32:		PHP_INSTALL_HEADERS("ext/mbstring", "mbstring.h oniguruma/oniguruma.h php_mbregex.h php_onig_compat.h libmbfl/config.h libmbfl/mbfl/eaw_table.h libmbfl/mbfl/mbfilter.h libmbfl/mbfl/mbfilter_8bit.h libmbfl/mbfl/mbfilter_pass.h libmbfl/mbfl/mbfilter_wchar.h libmbfl/mbfl/mbfl_allocators.h libmbfl/mbfl/mbfl_consts.h libmbfl/mbfl/mbfl_convert.h libmbfl/mbfl/mbfl_defs.h libmbfl/mbfl/mbfl_encoding.h libmbfl/mbfl/mbfl_filter_output.h libmbfl/mbfl/mbfl_ident.h libmbfl/mbfl/mbfl_language.h libmbfl/mbfl/mbfl_memory_device.h libmbfl/mbfl/mbfl_string.h");
config.w32:		PHP_INSTALL_HEADERS("ext/mbstring", "php_mbregex.h");
```
so if they are required it seems to be an upstream issue.

**Comment by cviebrock** [comment]
Opened an issue with PHP: https://bugs.php.net/bug.php?id=75441
