### ISSUE TITLE
Supported PHP versions in the contribution guide are outdated

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-php#4540]
## Description

The Contribution guide says:

> All official PHP extensions should be built for all stable versions of PHP included in homebrew-php. These versions are 5.3.29, 5.4.45, 5.5.38, 5.6.27, and 7.0.12.

Not including 7.1 obviously but also showing old versions of the others.

I suggest this line is either removed or doesn't specify the specific bugfix revisions anymore.

**Comment by alcaeus** [comment]
I agree - remove minor version number, add 7.1 and 7.2 and consider dropping PHP 5.3 and 5.4 as more and more extensions are starting to drop compatibility to those PHP versions. I've given up on removing those two (see #3689), but maybe just dropping them from the docs is a starting point.

**Comment by SMillerDev** [comment]
Not sure about marking an RC as stable. But in a month or so, 7.2 seems fine.

**Comment by SMillerDev** [comment]
Hey bot, this is still awaiting a PR 😞

**Comment by alcaeus** [comment]
What's the PR waiting for? I see a `Discussion` label there, but no real discussion taking place ;)

**Comment by SMillerDev** [comment]
yeah, hoping @javian would at least comment on it. I mostly just wanted a discussion about it.
