### ISSUE TITLE
PHP-FPM with httpd

### ISSUE THREAD

**Issue by mcdado** [Homebrew/homebrew-php#4543]
## Description

When installing PHP with Homebrew it is unclear how to setup the proxy from the Apache side, which provided by Homebrew as `httpd`. I had to do some research and found a lot of instructions using   something like `ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/usr/local/var/www/$1` which I personally don't know if it's advisable anymore, what I know for sure is that it does not work with `VirtualDocumentRoot` which is used to get something like http://my-php-app.dev by placing a folder called `my-php-app` inside the web server root.

After some research, I figured out that the solution is to use
```
<FilesMatch \.php$>
  SetHandler proxy:fcgi://localhost:9000
</FilesMatch>
```
in your vhost configuration file ([see my configuration file](https://github.com/mcdado/dotfiles/blob/1e7ac3cf28a85d1a51f0d375c42a79effe7d8ca9/httpd-vhosts.conf)).

I think it's only good if this information was included either in the caveats, or just in this repo (the file [Contributions/Using FPM.md](https://github.com/Homebrew/homebrew-php/blob/91fe1215611f8f02add0b5e6ab197d7743d588f5/Contributions/Using%20FPM.md) looks very outdated, the fastcgi formula isn't even available anymore!) so if it stays in the repo I think it needs an overhaul. Alternatively a Wiki page could be created and linked from the README. I'm sure many people look for this info, since running with Apache module is not really the best way to go isn't it?

[I wrote a blog post about it](http://mcdado.com/post/166619749589/apache-and-php-fpm-via-homebrew-on-macos), I would happily contribute it if you tell me the best way to do so.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13_
**Homebrew version:**   | _1.3.6-28_
**PHP version in use:** | _7.0.24_

**Comment by SMillerDev** [comment]
While I'm not sure if it's `homebrew-php`'s place to tell people how to set up apache with PHP-FPM, if you want to edit the file to include more up to date instructions (at least bumping PHP to a currently supported version 😄 ) I'd be happy to review it for merging into the repo.
