### ISSUE TITLE
last update: unable to load php

### ISSUE THREAD

**Issue by jimblue** [Homebrew/homebrew-php#4556]
## Description

Brew update just broke my environment.

First issue come from Apache:

[Sat Oct 28 15:54:41.585681 2017] [php7:crit] [pid 1170:tid 140735866839872] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed

But following @javian advice fixed that problem (disable event.so and enable prefork.so)

Know I still have an issue I can't fix that come from PHP. (output is below)

Hope you guys have a fix, thanks

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _maxOS 10.13_
**Homebrew version:**   | _Homebrew 1.3.6_
**PHP version in use:** | _php 7.1.11_22_
**Xcode version:**      | _Xcode-select 2349_

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): Symbol not found: _compiler_globals_id
  Referenced from: /usr/local/opt/php71-xdebug/xdebug.so
  Expected in: flat namespace
 in /usr/local/opt/php71-xdebug/xdebug.so
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-apcu/apcu.so' - dlopen(/usr/local/opt/php71-apcu/apcu.so, 9): Symbol not found: _executor_globals_id
  Referenced from: /usr/local/opt/php71-apcu/apcu.so
  Expected in: flat namespace
 in /usr/local/opt/php71-apcu/apcu.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-apcu/apcu.so' - dlopen(/usr/local/opt/php71-apcu/apcu.so, 9): Symbol not found: _executor_globals_id
  Referenced from: /usr/local/opt/php71-apcu/apcu.so
  Expected in: flat namespace
 in /usr/local/opt/php71-apcu/apcu.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-igbinary/igbinary.so' - dlopen(/usr/local/opt/php71-igbinary/igbinary.so, 9): Symbol not found: _basic_globals_id
  Referenced from: /usr/local/opt/php71-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php71-igbinary/igbinary.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-igbinary/igbinary.so' - dlopen(/usr/local/opt/php71-igbinary/igbinary.so, 9): Symbol not found: _basic_globals_id
  Referenced from: /usr/local/opt/php71-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php71-igbinary/igbinary.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-memcached/memcached.so' - dlopen(/usr/local/opt/php71-memcached/memcached.so, 9): Symbol not found: _compiler_globals_id
  Referenced from: /usr/local/opt/php71-memcached/memcached.so
  Expected in: flat namespace
 in /usr/local/opt/php71-memcached/memcached.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-memcached/memcached.so' - dlopen(/usr/local/opt/php71-memcached/memcached.so, 9): Symbol not found: _compiler_globals_id
  Referenced from: /usr/local/opt/php71-memcached/memcached.so
  Expected in: flat namespace
 in /usr/local/opt/php71-memcached/memcached.so in Unknown on line 0
PHP Warning:  PHP Startup: yaml: Unable to initialize module
Module compiled with build ID=API20160303,TS
PHP    compiled with build ID=API20160303,NTS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: yaml: Unable to initialize module
Module compiled with build ID=API20160303,TS
PHP    compiled with build ID=API20160303,NTS
These options need to match
 in Unknown on line 0
PHP 7.1.11 (cli) (built: Oct 28 2017 15:22:54) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies

**Comment by SMillerDev** [comment]
Your extensions are installed threadsafe and your PHP isn't. You can run `brew reinstall <module>` to install the module again to fit your setup.

**Comment by jimblue** [comment]
@SMillerDev `brew reinstall` wasn't enough. I had to uninstall php and module, cleanup and then reinstall everything. Back to work now it's working. Thank you for your help.

**Comment by holtkamp** [comment]
Encountered the same issue, I tried to following in order to uninstall, cleanup and reinstall as suggested:

```
brew uninstall php71-apcu && \
brew uninstall php71-intl && \
brew uninstall php71-opcache && \
brew uninstall php71-mcrypt && \
brew uninstall php71-imagick && \
brew uninstall php71 && \
brew cleanup && \
brew install php71 --with-httpd && \
brew install php71-apcu && \
brew install php71-intl && \
brew install php71-opcache && \
brew install php71-mcrypt && \
brew install php71-imagick
```
All steps succeed, but when starting Apache using `sudo apachectl start` the error still occurs:

```
[Mon Oct 30 15:47:15.300870 2017] [php7:crit] [pid 1320:tid 140735726805824] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed
```

@jimblue any additional suggestions?

**Comment by jimblue** [comment]
You should also try to install-uninstall httpd.

Here is a very good tutorial:

https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions

**Comment by holtkamp** [comment]
thanks, eventually adding the `--with-thread-safety` flag did the trick:

```
brew uninstall php71-apcu && \
brew uninstall php71-intl && \
brew uninstall php71-opcache && \
brew uninstall php71-mcrypt && \
brew uninstall php71-imagick && \
brew uninstall php71 && \
brew cleanup && \
brew install php71 --with-httpd --with-thread-safety && \
brew install php71-apcu && \
brew install php71-intl && \
brew install php71-opcache && \
brew install php71-mcrypt && \
brew install php71-imagick
```

**Comment by SMillerDev** [comment]
@holtkamp Reinistalling httpd would've fixed it as well. The benefit there would be that you can still use bottled formulas for PHP (instead of having to compile them from source)

**Comment by holtkamp** [comment]
@SMillerDev ok, thanks for that pointer. When upgrading to MacOS Sierra High I spent / wasted a complete day on getting `httpd` working again, so I am a bit "afraid" to go down that path again. I know, not the right attitude, but for now I won't touch anything 😨

**Comment by holtkamp** [comment]
Mostly for self-reference, after encountering the same issue as described here https://github.com/Homebrew/homebrew-php/issues/4518, this fixed my installation:

```
brew uninstall php71-apcu && \
brew uninstall php71-intl && \
brew uninstall php71-opcache && \
brew uninstall php71-mcrypt && \
brew uninstall php71-imagick && \
brew uninstall php71 && \
brew cleanup && \
brew install php71 --with-httpd --with-thread-safety && \
brew install --build-from-source php71-apcu && \
brew install --build-from-source php71-intl && \
brew install --build-from-source php71-opcache && \
brew install --build-from-source php71-mcrypt && \
brew install --build-from-source php71-imagick
```

**Comment by javian** [comment]
It is recommended to not run at threaded PHP with apache/httpd so unless you have a good reason for that I would suggest that you change your apache config instead (its a one line change). This would also mean that you can skip everything that you do to make it work @holtkamp =)

**Comment by holtkamp** [comment]
@javian ok will try that now I got more time to experiment with this 👍

**Comment by holtkamp** [comment]
as pointed out [here](http://www.mylinuxguide.com/apache-is-running-a-threaded-mpm-but-your-php-module-is-not-compiled-to-be-threadsafe/), in `httpd.conf` changing

```
LoadModule mpm_event_module modules/mod_mpm_event.so
```
with 

```
LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
```

did the trick combined with:

```
brew install php71 --with-httpd && \
brew install php71-apcu && \
brew install php71-intl && \
brew install php71-opcache && \
brew install php71-mcrypt && \
brew install --build-from-source php71-imagick
```

**Comment by javian** [comment]
imagick needs a revision update if it doesn't work from the bottle.

**Comment by SMillerDev** [comment]
@javian it does, I'll make one later today.
