### ISSUE TITLE
how to --enable-embed

### ISSUE THREAD

**Issue by spring-z** [Homebrew/homebrew-php#4557]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13
**Homebrew version:**   | Homebrew 1.3.6-132-g7caca57 Homebrew/homebrew-core (git revision 89d7; last commit 2017-10-28)
**PHP version in use:** | 7.0.25
**Xcode version:**      | 9.0.1

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.0.25 (cli) (built: Oct 28 2017 23:17:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by SMillerDev** [comment]
Not sure what your issue is. Or with what the issue is.

**Comment by javian** [comment]
Maybe he's referring to 
```
--enable-embed=TYPE     EXPERIMENTAL: Enable building of embedded SAPI library
```

**Comment by spring-z** [comment]
yes，homebrew config no --enable-embed

**Comment by spring-z** [comment]
@BePsvPT
