### ISSUE TITLE
brew tap homebrew/php error!

### ISSUE THREAD

**Issue by fightingbamboo** [Homebrew/homebrew-php#4558]
## Description

invalid attribute for formula 'homebrew/php/php56': version (nil)
Error: Cannot tap homebrew/php: invalid syntax in tap!

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13
**Homebrew version:** | Homebrew 1.1.0 Homebrew/homebrew-core (git revision 35672; last commit 2017-10-30)
**PHP version in use:**| php56 & php71
**Xcode version:**       | Xcode 9.0.1 Build version 9A1004

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies

**Build logs:** 
invalid attribute for formula 'homebrew/php/php56': version (nil)
Error: Cannot tap homebrew/php: invalid syntax in tap!

**Comment by SMillerDev** [comment]
Latest homebrew is 1.3.0, your version is almost a year old. Can you run `brew update` to see if it fixes things?

**Comment by fightingbamboo** [comment]
@SMillerDev thank you!  
run ```/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"```
install latest homebrew,  fixed.

**Comment by zhouzhi2015** [comment]
3Q
