### ISSUE TITLE
Bottled version of drush-launcher is broken

### ISSUE THREAD

**Issue by webflo** [Homebrew/homebrew-php#4567]
## Description

The bottled version of drush-launcher is broken. It failed with the following message.

```
Fatal error: Uncaught exception 'PharException' with message 'phar "/opt/boxen/homebrew/Cellar/drush-launcher/0.4.3/bin/drush" SHA1 signature could not be verified: broken signature' in /opt/boxen/homebrew/Cellar/drush-launcher/0.4.3/bin/drush on line
```

The build from source works well.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1 (fails in 10.12 too)
**Homebrew version:**   | Homebrew 1.3.6-190-ge300713, Homebrew/homebrew-core (git revision 0c79d8; last commit 2017-11-05)
**PHP version in use:** | PHP 7.1.7
**Xcode version:**      | Xcode 9.1, Build version 9B55

**Output of `gcc -v`:**

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by SMillerDev** [comment]
What does it fail?

**Comment by SMillerDev** [comment]
I just installed it from bottle and it tells me I need a Drupal site just fine.

**Comment by webflo** [comment]
@SMillerDev There error message is "SHA1 signature could not be verified: broken signature". It looks like the phar file gets corrupted during the packaging process.

**Comment by SMillerDev** [comment]
I can't reproduce this. What command do you run when you get this error?

**Comment by webflo** [comment]
I get this error on ```drush --drush-launcher-version```. The SHA1 hash of the bottled phar file is different if i download it via github releases directly. 

I checked it with ``openssl dgst -sha1 drush.phar``
