### ISSUE TITLE
PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by jimblue** [Homebrew/homebrew-php#4571]
## Description

Hi,

I'm getting a php warning when I use `composer or just with `php -v` but php seems to work normally.

Thanks for you help

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13.1_
**Homebrew version:**   | _1.3.6_
**PHP version in use:** | _7.2_

**Output of `gcc -v`:**
_Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin_

**Output of `php -v`:**
_PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl, 9): image not found), /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl.so (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl, 9): image not found), /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl.so (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/openssl.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip' (tried: /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip, 9): image not found), /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip.so (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'zip' (tried: /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip, 9): image not found), /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip.so (dlopen(/usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip.so, 9): image not found)) in Unknown on line 0
PHP 7.2.0RC6 (cli) (built: Nov 10 2017 15:26:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0RC6, Copyright (c) 1999-2017, by Zend Technologies_

**Comment by jimblue** [comment]
Still having the issue... would appreciate some feedback!

**Comment by SMillerDev** [comment]
Can you get the output of `brew deps php72 --installed` ?

**Comment by jimblue** [comment]
Sure:

```
freetype
gettext
icu4c
jpeg
libpng
libsodium
libtool
libxml2
openssl
readline
unixodbc
```

**Comment by SMillerDev** [comment]
and the /usr/local/Cellar/php72/7.2.0RC6_9/lib/php/extensions/no-debug-non-zts-20170718/zip.so

files that it errors on exist?

**Comment by jimblue** [comment]
Nope, this folder  `/usr/local/Cellar/php72/7.2.0RC6_9/lib/php` have only one subfolder: `build`

**Comment by SMillerDev** [comment]
then something about the php install is broken. With what options did you install PHP?

**Comment by jimblue** [comment]
with homebrew

**Comment by SMillerDev** [comment]
So you just ran `brew install php72` ? No command line options?

**Comment by jimblue** [comment]
If I remember well I ran `brew install php72 --with-httpd`

**Comment by SMillerDev** [comment]
And what is the output of  `grep -r zip /usr/local/etc/php/7.2/` and ` grep -r openssl /usr/local/etc/php/7.2/` ?

**Comment by jimblue** [comment]
`grep -r zip /usr/local/etc/php/7.2/ output`:

`/usr/local/etc/php/7.2//php.ini:extension=zip`

`grep -r openssl /usr/local/etc/php/7.2/ output`:

```
/usr/local/etc/php/7.2//php.ini:extension=openssl
/usr/local/etc/php/7.2//php.ini:[openssl]
/usr/local/etc/php/7.2//php.ini:;openssl.cafile=
/usr/local/etc/php/7.2//php.ini:; If openssl.cafile is not specified or if the CA file is not found, the
/usr/local/etc/php/7.2//php.ini:; directory pointed to by openssl.capath is searched for a suitable
/usr/local/etc/php/7.2//php.ini:;openssl.capath=
```

**Comment by SMillerDev** [comment]
You're loading the openssl and zip extension manually. These aren't loaded by default, and you might want to remove this configuration or make sure that you're adding them in a place where php can find them.

**Comment by jimblue** [comment]
Fixed!
Thank you so much for your help and explanation @SMillerDev!
