### ISSUE TITLE
php71-opcache: opcache.file_cache doesn't work

### ISSUE THREAD

**Issue by fedeisas** [Homebrew/homebrew-php#4574]
## Description
When `opcache.file_cache` is enabled, PHP stops working.

## Context and Logs

This happens whenever I try to run any PHP script from the command line, ie. `php script.php`

```
dyld: lazy symbol binding failed: Symbol not found: _zend_file_cache_script_load
  Referenced from: /usr/local/opt/php71-opcache/opcache.so
  Expected in: flat namespace

dyld: Symbol not found: _zend_file_cache_script_load
  Referenced from: /usr/local/opt/php71-opcache/opcache.so
  Expected in: flat namespace
```

**Installed packages:**
```
blackfireio/blackfire/blackfire-php71 ✔
homebrew/php/php71 ✔
homebrew/php/php71-apcu ✔
homebrew/php/php71-igbinary ✔
homebrew/php/php71-mcrypt ✔
homebrew/php/php71-opcache ✔
homebrew/php/php71-redis ✔
homebrew/php/php71-xdebug ✔
homebrew/php/php71-yaml ✔
```

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.5
**Homebrew version:**   | 1.3.7
**PHP version in use:** | 7.1.11
**Xcode version:**      | None

**Output of `gcc -v`:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**
```
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.17.3~mac-x64-non_zts71, https://blackfire.io, by SensioLabs
```

**Build logs:** https://gist.github.com/anonymous/d9029c19fe5f9698ea5a19c9eb0f837e

**Comment by SMillerDev** [comment]
What command did you use to install PHP? What command did you use to install Opcache? When do you get these errors?

**Comment by fedeisas** [comment]
@SMillerDev this happens whenever I try to run any PHP script from the command line, ie. `php script.php`. I installed PHP with `brew install php71 php71-opcache`.

**Comment by SMillerDev** [comment]
After a clean install of just PHP with opcache, enabling the file cache doesn't give this error.  Could you check what happens when you do a clean install with just those packages and the config line?

**Comment by fedeisas** [comment]
@SMillerDev how do you enable `file_cache`?
I've found that it stops working with these lines:

```
opcache.file_cache=/var/tmp/php/opcache
opcache.file_cache_only=1
```

**Comment by SMillerDev** [comment]
did you create that directory? cause that doens't exist by default.

**Comment by fedeisas** [comment]
@SMillerDev yes, the directory exists and it's writable. I've found it fails if you set `opcache.enable_cli=1`.

**Comment by fedeisas** [comment]
I can confirm this is also failing on `php72`.

**Comment by fedeisas** [comment]
I think that `php-opcache` needs to be built with an specific flag to have `file_cache` support.

**Comment by SMillerDev** [comment]
There's no flags for file_cache in opcache. `opcache.enable_cli=1` is a different error then you initially reported though. Can you try and do a clean install of php, disabling all your configuration files and installing dependencies and configuration one by one? Because there seems to be an conflict with something on your machine.

**Comment by jaymecd** [comment]
Please check result of the following command:

```
$ php --ri 'Zend OPcache'

Zend OPcache

Opcode Caching => Up and Running
Optimization => Enabled
SHM Cache => Enabled
File Cache => Disabled
...
...
```

The file cache has to be explicitly compiled into PHP 7 using the compile flag `--enable-opcache-file`

**Comment by javian** [comment]
Would it be possible for you to create a PR for adding that @jaymecd ?

**Comment by jaymecd** [comment]
@javian will do later this week
