### ISSUE TITLE
High Sierra php71 install : incompatible libxml2 version -- can't install composer or drush

### ISSUE THREAD

**Issue by Martin-B** [Homebrew/homebrew-php#4575]
## Description

I have followed the recently updated tutorial available here : https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions, till the end of part three, to find out that despite having a functional server that compiles and serves php gracefully for the 3 php versions installed (5.6, 7.0 and 7.1), I have issues with the cli php. Running `$ php -v` outputs the following : 

```$ php -v
dyld: Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Abort trap: 6
```

The same goes when trying to install composer and drush, which is my finality.

The [php switcher script mentioned in this tutorial](https://gist.github.com/w00fz/142b6b19750ea6979137b963df959d11) works well, except that `brew doctor`  complains about unlinked kegs in my cellar when enabling one of the 3 specific versions installed on my system.

I have upgraded from 10.2 to 10.13.1, removed xode with appcleaner and reainstalled, upgraded xcode cli tools with `$ xcode-select --install`, removed all phpversion as well as httpd with brew, uninstalled brew, reinstalled and I am back to square one, I have a really hard time finding a solution. 

I have tried feeding a new libxml2 version to my homebrew php install with commands like `brew reinstall php70 --with-httpd --with-homebrew-libxml2 `, then completely removing a specific version with commands like `brew uninstall php70 --ignore-dependencies` before installing anew.

I have tried installing with the `--interactive` switch as well, trying to force the compiler to update the libxml2 path to the copy installed by brew (--with-libxml-dir=/usr/local/Cellar/libxml2/2.9.7). but It seems like this process, after running `make install` end `exit` does not allow me to link my module with `LoadModule php7_module` in httpd.conf.

At this point, I would like to have a bit of help, as I have wasted a considerable amount of time getting up and running with Drupal dev this this machine and tried a variety of things after looking for closed issues referencing incompatible libraries and  libxml2 issues.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1
**Homebrew version:**   | Homebrew 1.3.7_
**PHP version in use:** | `homebrew-php stable -- PHP 7.1.11 (cli) (built: Nov 13 2017 13:26:53) ( NTS )`
**Xcode version:**      | Xcode 9.1 - Build version 9B55

**Output of `gcc -v`:**

```Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**

```dyld: Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
Referenced from: /usr/local/bin/php
Reason: Incompatible library version: php requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Abort trap: 6
```

**PHP version with phpswitcher script**

Running `sphp71` with [https://gist.github.com/w00fz/142b6b19750ea6979137b963df959d11](https://gist.github.com/w00fz/142b6b19750ea6979137b963df959d11)

```
- - -
Using the phpswitcher script found at https://gist.github.com/w00fz/142b6b19750ea6979137b963df959d11 and running sphp71

PHP 7.1.11 (cli) (built: Nov 13 2017 13:26:53) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
**Build logs:** [https://gist.github.com/4ba03dcc1c546884c47285f37404031d
](https://gist.github.com/4ba03dcc1c546884c47285f37404031d)

**Comment by SMillerDev** [comment]
not sure what the switcher script does, but there is a `brew-php-switcher` formula that allows you to select different brewed php versions easily as well. As for libxml2, could you try doing an uninstall of the current php and libxml, then `brew cleanup` and then installing again?

**Comment by Martin-B** [comment]
The php switcher script seems to do every bit like the brew-php-switcher formula. Unlinks old php version, links new one and makes apache aware of it via the LoadModule command. Apache is then rebooted. Interesting, I was not aware of the brew-php-switcher formula, thanks for sharing!

**Comment by Martin-B** [comment]
As per your instructions, I have uninstalled php version5.6, so I can keep working on 7.1, removed the homebrew libxml2 formula cleaned up and reinstalled with an explicit dependency to homebrew-libxml2.

```
$  brew uninstall php56  --force --ignore-dependencies
Uninstalling php56... (332 files, 48.3MB)
$  brew uninstall libxml2  --force --ignore-dependencies
Uninstalling libxml2... (281 files, 10.4MB)
$  brew cleanup
$  brew install php56  --with-httpd --with-homebrew-libxml2
$  brew unlink php71
$  brew install php56  --with-httpd --with-homebrew-libxml2
==> Installing php56 from homebrew/php
==> Installing dependencies for homebrew/php/php56: libxml2
==> Installing homebrew/php/php56 dependency: libxml2
==> Downloading https://homebrew.bintray.com/bottles/libxml2-2.9.7.high_sierra.bottle.tar.gz
Already downloaded: /Users/uboud8u/Library/Caches/Homebrew/libxml2-2.9.7.high_sierra.bottle.tar.gz
==> Pouring libxml2-2.9.7.high_sierra.bottle.tar.gz
...
/usr/local/Cellar/php56/5.6.32_8: 332 files, 48.3MB, built in 4 minutes 28 seconds
```

### Enabling php 5.6

```
$ sphp 56
PHP version 56 found
Unlinking old binaries...
Linking new binaries...
Linking /usr/local/Cellar/php56/5.6.32_8... 17 symlinks created
Linking new modphp addon...
Password:
/usr/local/lib/libphp5.so
Fixing LoadModule...
Updating version file...
Restarting homebrew Apache...
Done.

PHP 5.6.32 (cli) (built: Nov 14 2017 08:26:20)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

### php-v on active version

```
$ php -v

dyld: Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Abort trap: 6
```

In my ~/.bash_profile file, I have tried removing and adding a precise version to use for php-cli and relading with source ~/.bash_profile : effective, but not a resolution, the current method sets the version properly for the runtime and the cli versions used.

```
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
```

**Comment by Martin-B** [comment]
Hello again, I have not resolved yet, does this look like it is OK? Shoud an attempt be made to relink the libxml2 path  with install_name_tool? The paths seem to be fine, IMHO.

```
php -v
dyld: Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Abort trap: 6
```

```
vp1117097:lib uboud8u$ otool -L /usr/local/bin/php
/usr/local/bin/php:
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/readline/lib/libreadline.7.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 51.0.0, current version 51.0.0)
	/usr/local/opt/jpeg/lib/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.7.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 22.0.0, current version 22.0.0)
	/usr/local/opt/unixodbc/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 59.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
```

```
vp1117097:lib uboud8u$ cd /usr/local/opt/libxml2/lib/
vp1117097:lib uboud8u$ ll -a
total 5488
drwxr-xr-x   9 uboud8u  admin      288 20 nov 07:51 .
drwxr-xr-x  15 uboud8u  admin      480 20 nov 07:53 ..
drwxr-xr-x   3 uboud8u  admin       96  2 nov 16:16 cmake
-r--r--r--   1 uboud8u  admin  1140740 20 nov 07:51 libxml2.2.dylib
-r--r--r--   1 uboud8u  admin  1661304  2 nov 16:16 libxml2.a
lrwxr-xr-x   1 uboud8u  admin       15  2 nov 16:16 libxml2.dylib -> libxml2.2.dylib
drwxr-xr-x   3 uboud8u  admin       96 20 nov 07:51 pkgconfig
drwxr-xr-x   3 uboud8u  admin       96  2 nov 16:16 python2.7
-r--r--r--   1 uboud8u  admin      271 20 nov 07:51 xml2Conf.sh
vp1117097:lib uboud8u$
```

**Comment by SMillerDev** [comment]
This all looks the same as it does for me. I'd love to help but I have no idea what's going wrong 😞

**Comment by Martin-B** [comment]
I have reinstalled my system and all is fine, thanks for taking the time to look at my edge case, it led me to better understand the interactions between the apache, php and mysql and the workings of Brew.
