### ISSUE TITLE
php71-libsodium - Library not loaded: /usr/local/opt/libsodium/lib/libsodium.18.dylib

### ISSUE THREAD

**Issue by fterrag** [Homebrew/homebrew-php#4589]
## Description

After installing php71-libsodium via `brew install php71-libsodium`, PHP is unable to load the libsodium extension:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-libsodium@1.0/libsodium.so' - dlopen(/usr/local/opt/php71-libsodium@1.0/libsodium.so, 9): Library not loaded: /usr/local/opt/libsodium/lib/libsodium.18.dylib
  Referenced from: /usr/local/opt/php71-libsodium@1.0/libsodium.so
  Reason: image not found in Unknown on line 0

The following will fix the issue:
$ cd /usr/local/opt/libsodium/lib
$ cp libsodium.23.dylib libsodium.18.dylib

This error is happening on a fresh install of macOS High Sierra and Homebrew.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1
**Homebrew version:**   | 1.3.7
**PHP version in use:** | 7.1.11
**Xcode version:**      | N/A

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:**
Error: No logs.

**Comment by fterrag** [comment]
Any ideas?

**Comment by javian** [comment]
Try `brew reinstall -s php71-libsodium` - if that works then we need to bump the revision of libsodium (or you can help by creating a PR for it =)).

**Comment by thinkingcap** [comment]
Yup 
`brew reinstall -s php71-libsodium@1.0` 
worked for me.

**Comment by fterrag** [comment]
Thanks @javian @thinkingcap
