### ISSUE TITLE
High Sierra php53 

### ISSUE THREAD

**Issue by clintonpaquin** [Homebrew/homebrew-php#4591]
## Description

I need php 5.3 on macOS High Sierra.
After installalation the binary looks to be found at `/usr/local/bin/php.dSYM` and not `/usr/local/bin/php`

Issue also described here [https://github.com/Homebrew/homebrew-php/issues/3634](https://github.com/Homebrew/homebrew-php/issues/3634)

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |10.13.1 (17B48)
**Homebrew version:**   | _Homebrew 1.3.8 - Homebrew/homebrew-core (git revision 6c2b1; last commit 2017-11-21)_
**PHP version in use:** | Needs to be 5.3.x - symlink not able to be created though
**Xcode version:**      | Xcode 9.1 - Build version 9B55

**Output of `gcc -v`:**
````
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
````

**Output of `php -v`:**
Falling back to system version here, again ... the symlink can't be created
````
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
````
**Build logs:** 
````
n/a
````

**Comment by javian** [comment]
The older version of PHP has not received any love in a long time so its likely that they will break if you try to install them. It is in the plan to remove these unless someone puts the work in to make them work again alternatively moving them to someone else who will maintain a separate tap.

**Comment by dsandstrom** [comment]
@javian What versions are considered older versions?

**Comment by javian** [comment]
@dsandstrom I'd say anything that's no longer supported upstream but 5.3 is broken in brew at the moment and 5.4 is showing its age so those two would be the first to go.

**Comment by dsandstrom** [comment]
Thank you. I'm having problems getting php56 to install so I was wondering
if I should try to get support.

**Comment by SMillerDev** [comment]
anything that's still supported by the PHP project itself will get support here for sure

**Comment by dsandstrom** [comment]
Thank you @javian and @SMillerDev .  My problem was unrelated.  I had to uninstall httpd before reinstalling php56 as inferred from https://github.com/Homebrew/homebrew-apache/issues/126#issuecomment-241625979 .
