### ISSUE TITLE
segmentation fault PHPDBG 7.1

### ISSUE THREAD

**Issue by TNAJanssen** [Homebrew/homebrew-php#4593]
## Description

I obtain phpunit code coverage via phpdbg. In my symfony app I run phpdbg -qrr bin/phpspecThis always leads to a segmentation fault. Just running bin/phpspec works.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1
**Homebrew version:**   | Homebrew 1.3.8 Homebrew/homebrew-core (git revision 128c; last commit 2017-11-22)
**PHP version in use:** | 7.1.7
**Xcode version:**      | n/a (using command-line tools

**Output of `gcc -v`:**
`Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Output of `php -v`:**
`PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies`

**Comment by SMillerDev** [comment]
I think this might be a bug that should be reported upstream (https://bugs.php.net/search.php?cmd=display&order_by=id&direction=DESC&limit=30&package_name[]=phpdbg)

Unless you have a specific reason to assume that homebrew packaging caused this?

**Comment by TNAJanssen** [comment]
Hmm yeah good point, the thing is i have this issue already for a couple of months and tried multiple version and also tried using the HEAD version. PHP7.2 doesn't have this issue..

**Comment by TNAJanssen** [comment]
Yep that solved it
