### ISSUE TITLE
php71-redis with igbinary serializer phpize fails

### ISSUE THREAD

**Issue by ptheofan** [Homebrew/homebrew-php#4595]
## Description
Cannot install php71-redis formula. It dies saying cannot find `igbinary.h`. Thing is, `php71-igbinary` is installed and works fine

Error Message
`checking for igbinary includes... configure: error: Cannot find igbinary.h`

But they are installed and double checked enabled and working
==> Dependencies
Build: autoconf ✔, igbinary ✔
Required: php71 ✔, php71-igbinary ✔

## Context and Logs
 MaCook  ➜  ~ brew install homebrew/php/php71-redis
==> Installing php71-redis from homebrew/php
==> Downloading https://github.com/phpredis/phpredis/archive/3.1.3.tar.gz
Already downloaded: /Users/ptheofan/Library/Caches/Homebrew/php71-redis-3.1.3.tar.gz
==> /usr/local/opt/php71/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php71-redis/3.1.3 --with-php-config=/usr/local/opt/php71
Last 15 lines from /Users/ptheofan/Library/Logs/Homebrew/php71-redis/02.configure:
checking for PHP includes... -I/usr/local/Cellar/php71/7.1.11_22/include/php -I/usr/local/Cellar/php71/7.1.11_22/include/php/main -I/usr/local/Cellar/php71/7.1.11_22/include/php/TSRM -I/usr/local/Cellar/php71/7.1.11_22/include/php/Zend -I/usr/local/Cellar/php71/7.1.11_22/include/php/ext -I/usr/local/Cellar/php71/7.1.11_22/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php71/7.1.11_22/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/Cellar/php71/7.1.11_22/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable redis support... yes, shared
checking whether to enable sessions... yes
checking whether to enable igbinary serializer support... yes
checking for igbinary includes... configure: error: Cannot find igbinary.h

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1 (High Sierra)
**Homebrew version:**   | 1.3.8
**PHP version in use:** | 7.1.11
**Xcode version:**      | Xcode 9.1 (build 9B55) 

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies

**Build logs:** [public gist](https://gist.github.com/4c7aebdb9128874614358013a8af274b)

**Comment by SMillerDev** [comment]
Does reinstalling igbinary help?

**Comment by ptheofan** [comment]
I've already tried uninstall - install and install - reinstall, didn't work

**Comment by SMillerDev** [comment]
After looking at your build logs some more, `brew doctor` probably indicates that igbinary is unlinked. Linking it should fix your issue.

**Comment by ptheofan** [comment]
You are so right! How embarrassing! Link was failing but for whatever reason I never noticed it.

**Comment by SMillerDev** [comment]
Just glad this could be resolved
