### ISSUE TITLE
Cant enable webp

### ISSUE THREAD

**Issue by rakibtg** [Homebrew/homebrew-php#4596]
I needed to use webp, but it was not enabled by default, running this command gives this error:
First i have removed php72, then install webo using brew and finally executed this command `brew install php72 --with-webp` then it gives error and webp dosnt gets enabled.

```
➜  ~ brew install php72 --with-webp
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
pyqt                              qscintilla2                       sip

==> Installing php72 from homebrew/php
==> Downloading https://downloads.php.net/~pollita/php-7.2.0RC6.tar.bz2
Already downloaded: /Users/rakibtg/Library/Caches/Homebrew/php72-7.2.0RC6.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/php72/7.2.0RC6_9 --localstatedir=/usr/local/var --sysconfd
Last 15 lines from /Users/rakibtg/Library/Logs/Homebrew/php72/01.configure:
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 1.0.1
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable PCRE JIT functionality... yes
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
php72-xdebug (new formula, head only) https://github.com/Homebrew/homebrew-php/pull/4439
php72-uuid 1.0.4 (new formula) https://github.com/Homebrew/homebrew-php/pull/4247
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | macOS High seirarararara 10.13.1 (17B48)
**Homebrew version:**   |Homebrew 1.3.8 (Homebrew/homebrew-core (git revision 9020; last commit 2017-11-24))
**PHP version in use:** | none
**Xcode version:**      | Xcode 9.1

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by SMillerDev** [comment]
That's unrelated to webp, it's an issue with your setup. It happens when the command line tools aren't working properly. It's likely an `Xcode-select --install` will fix this.
