### ISSUE TITLE
PHP72 Update for GA

### ISSUE THREAD

**Issue by necrogami** [Homebrew/homebrew-php#4603]
## Description

Can we update the PHP72 formula for the 7.2 General availability 

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**      | 10.12.6 
**Homebrew version:**  | Homebrew 1.3.8-50-g63408a1
**PHP version in use:** |7.2.0RC6
**Xcode version:**   |   Xcode 9.1 Build version 9B55

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.2.0RC6 (cli) (built: Nov  7 2017 19:46:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by SMillerDev** [comment]
We sure can, as soon as PHP 7.2 actually is GA(see https://wiki.php.net/todo/php72#timetable) we'll make an update to the current formula.

**Comment by alcaeus** [comment]
See #4606. Release is still planend for tomorrow around noon UTC.

**Comment by necrogami** [comment]
It's been released \o/

**Comment by javian** [comment]
We should be able to merge it later today.

**Comment by javian** [comment]
Now merged.
