### ISSUE TITLE
php71 mongoDB ext crashing php

### ISSUE THREAD

**Issue by aleksandardragojlovic** [Homebrew/homebrew-php#4607]
After I install php71-mongodb my php stop working.

I have installed on clean system (High Sierra) php71 with necessary extensions. When I install mongoDB my php stop working. In system.log I see segmentation errors. When I uninstall mongoDB php ext. everything is working correctly.

➜  brew doctor
Your system is ready to brew.

➜  brew list -la
total 0
drwxrwxr-x  67 aleksandar  admin  2144 28 Nov 22:55 .
drwxr-xr-x  14 root        wheel   448 26 Nov 19:29 ..
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 apr
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 apr-util
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:38 autoconf
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:38 automake
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:14 boost
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 c-ares
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:43 colordiff
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:54 composer
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:43 curl
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:49 fontconfig
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:49 freetype
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:50 gd
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 gdbm
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:38 geoip
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 gettext
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 git
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:55 httpd
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:43 icoutils
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 icu4c
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 imagemagick
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 jansson
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:14 jemalloc
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:49 jpeg
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 libev
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 libevent
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:49 libpng
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:17 libsodium
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 libssh2
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:50 libtiff
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 libtool
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 libxml2
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 libyaml
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 09:59 lynx
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 mcrypt
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:38 mercurial
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 mhash
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 22:55 mongodb
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:50 mysql
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:14 nghttp2
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 10:54 nmap
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:54 node
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 openssl
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 openssl@1.1
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:14 pcre
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:30 php71
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:37 php71-geoip
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:37 php71-imagick
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:38 php71-intl
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:38 php71-mcrypt
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 22:49 php71-mongodb
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:38 php71-ssh2
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:38 php71-tidy
drwxr-xr-x   3 aleksandar  admin    96 28 Nov 11:38 php71-yaml
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 pkg-config
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:38 python
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:44 rbenv
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 readline
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:44 ruby-build
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 sqlite
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 tidy-html5
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:13 unixodbc
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:50 webp
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:37 wget
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 20:39 xz
drwxr-xr-x   3 aleksandar  admin    96 26 Nov 19:50 zlib

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1
**Homebrew version:**   | Homebrew 1.3.8 - Homebrew/homebrew-core (git revision 7030; last commit 2017-11-28)
**PHP version in use:** | PHP 7.1.11 (cli) (built: Nov 28 2017 11:35:47) ( NTS )
**Xcode version:**      | Xcode 9.1 . - Build version 9B55

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.11 (cli) (built: Nov 28 2017 11:35:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** https://gist.github.com/2f54ba2db5e849b1cf42b033905329d9

**Comment by alcaeus** [comment]
Can you share a **minimal** code snippet that reproduces the segmentation fault?

**Comment by aleksandardragojlovic** [comment]
I checked system.log, and I couldn't locate segmentation fault. httpd and php are working normally.

After that I installed php71-mongodb and I restarted httpd.

brew install php71-mongodb
sudo brew services restart httpd

When I checked system.log I saw:

Nov 29 08:34:04 Aleksandars-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.httpd[1534]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

If I remove php71-mongodb everything will work again.

**Comment by superberni** [comment]
I got also the same problem on High Sierra - with php70 and php71. After installing php7x-mongodb httpd won't start - segmentation fault. 

After removing the mongodb-driver the system works fine.

Also a complete new brew-installation didn't solve the problem

**Comment by aleksandardragojlovic** [comment]
I reinstalled macOS before I figured out it won't help :-)

**Comment by alcaeus** [comment]
Hmm, that's odd. It might be worth creating an issue at https://github.com/mongodb/mongo-php-driver/issues since it doesn't seem to be a problem specific to homebrew.

**Comment by superberni** [comment]
I've compiled also the driver manually from mongo-php-driver - doesn't worked.

**Comment by aleksandardragojlovic** [comment]
I added new issue like @alcaeus suggested: https://github.com/mongodb/mongo-php-driver/issues/681 .

**Comment by derickr** [comment]
Having a lot at  mongodb/mongo-php-driver#681, but a better place to report bugs is at https://jira.mongodb.org/projects/PHPC

**Comment by adamwinn** [comment]
I'm having issues with this too.

In the apache logs, I get `[core:notice] [pid 82690] AH00060: seg fault or similar nasty error detected in the parent process` after I run `brew install php70-mongodb` and do an apache restart

After running `brew uninstall php70-mongodb`, apache will work again

**Comment by vazgen** [comment]
I have the same issue, spend almost a day but without any solution

**Comment by ponchorage** [comment]
This affects 7.2 as well.

**Comment by sibidharan** [comment]
I fixed it guys! Check out https://github.com/Homebrew/homebrew-core/issues/21475#issuecomment-352155715

**Comment by sibidharan** [comment]
@ponchorage @vazgen @adamwinn @derickr @aleksandardragojlovic @superberni 

Compiling drivers with native SSL libraries solved the issue. Check how to do it here https://github.com/Homebrew/homebrew-core/issues/21475#issuecomment-352155715

**Comment by javian** [comment]
There's a beta out of 1.4 now https://github.com/mongodb/mongo-php-driver/releases - has anyone tried this yet and see if it fixes the issue ?

**Comment by jmikola** [comment]
We've just tagged [mongodb-1.4.0RC1](https://pecl.php.net/package/mongodb/1.4.0RC1), which should allow the driver to use macOS [Secure Transport](https://developer.apple.com/documentation/security/secure_transport) instead of OpenSSL, and therefore circumvent the BoringSSL issue described above. The following quote is from our soon-to-be-published release notes:

> This release overhauls the way the extension configures SSL libraries and adds support for LibreSSL and macOS native SSL (Secure Transport). When building from source, `configure` now supports a `--with-mongodb-ssl` option. This defaults to `auto`, which will first attempt to use OpenSSL, followed by LibreSSL, and finally Secure Transport (for macOS only, of course). Additionally, you may specify `openssl`, `libressl`, or `darwin` to force a particular library, or specify `no` to disable SSL entirely.

The [current formula](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php72-mongodb.rb) can probably be updated to pull in t1.4.0RC1 instead of 1.4.0-beta1 for `devel`, and then add the `--with-mongodb-ssl=darwin` as needed.

**Comment by javian** [comment]
This should be resolved now with the new 1.4.0 version of the extension.
