### ISSUE TITLE
php70 was not installed successfully

### ISSUE THREAD

**Issue by pointline** [Homebrew/homebrew-php#4615]
## Description
brew install php70 --with-httpd

_Problem description goes here_

Sorry, I cannot run apxs.  Possible reasons follow:

1. Perl is not installed
2. apxs was not found. Try to pass the path using --with-apxs2=/path/to/apxs
3. Apache was not built using --enable-so (the apxs usage page is displayed)

The output of /private/tmp/php70-20171202-68037-998413/php-7.0.25/["sbin", "bin"] follows:
./configure: line 6186: /private/tmp/php70-20171202-68037-998413/php-7.0.25/["sbin",: No such file or directory
configure: error: Aborting

READ THIS: https://docs.brew.sh/Troubleshooting.html

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |  10.13.1 (17B1003)
**Homebrew version:**   | 1.3.8
**PHP version in use:** | 
**Xcode version:**      | Xcode 9.1 Build version 9B55

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
Does `brew doctor` tell you anything ?

**Comment by rbur0425** [comment]
I found that doing that running the following worked for me

```
brew uninstall httpd
brew install --build-from-source php70
```

**Comment by pointline** [comment]
Thank you. It's settled.
