### ISSUE TITLE
PHP 7.2 sodium extension not working even though loaded

### ISSUE THREAD

**Issue by onlime** [Homebrew/homebrew-php#4622]
## Description

I have installed the following:

```
$ brew tap homebrew/homebrew-php
$ brew install php72 --with-httpd --with-cgi --with-imap
$ brew install php72-apcu
$ brew install php72-imagick
$ brew install php72-intl
$ brew install php72-opcache
$ brew install php72-libsodium
$ brew list --versions | grep php72
php72 7.2.0_10
php72-apcu 5.1.8_1
php72-imagick 3.4.3_1
php72-intl 7.2.0_7
php72-libsodium 1.0.6_1
php72-opcache 7.2.0_10
```

libsodium seems to be correctly loaded and enabled (I have symlinked `/usr/local/etc/php/7.2/conf.d-cli -> conf.d` so that all extensions are loaded also in CLI):

```
$ php -i | grep sodium
/usr/local/etc/php/7.2/conf.d-cli/ext-libsodium.ini,
libsodium
libsodium support => enabled
libsodium compiled version => 1.0.6
libsodium headers version => 1.0.15
libsodium library version => 1.0.15

$ php -m | grep sodium
libsodium
```

Problem is, all seems fine and libsodium enabled, but it is not working (no `SODIUM_*` constants set, no `sodium_*` functions defined):

```
$ php -r 'echo SODIUM_CRYPTO_SECRETBOX_KEYBYTES;'

Warning: Use of undefined constant SODIUM_CRYPTO_SECRETBOX_KEYBYTES - assumed 'SODIUM_CRYPTO_SECRETBOX_KEYBYTES' (this will throw an Error in a future version of PHP) in Command line code on line 1
SODIUM_CRYPTO_SECRETBOX_KEYBYTES
```

Any help greatly appreciated!

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1
**Homebrew version:**   | 1.3.8
**PHP version in use:** | 7.2.0 (cli)
**Xcode version:**      | not installed

**Output of `gcc -v`:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**
```
PHP 7.2.0 (cli) (built: Dec  2 2017 18:41:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologies
```

**Output of `which php`:**

```
$ which php
/usr/local/bin/php

$ ls -lah /usr/local/bin/php
lrwxr-xr-x  1 foo  admin    32B Dec  2 20:06 /usr/local/bin/php -> ../Cellar/php72/7.2.0_10/bin/php
```

**Build logs:**
https://gist.github.com/89390c10d28a1484471da9abe933428c

**Comment by onlime** [comment]
looks like `php72-libsodium` is the old libsodium that uses the `\Sodium\` namespace. I could start writing my Sodium code using legacy libsodium and then later using e.g. https://github.com/mollie/polyfill-libsodium polyfill.
But I don't like this workaround. Also, on production server (Debian Stretch), I have a wonderful running PHP 7.2 that was compiled with `--with-sodium` (see [phpinfo](https://php72.onlime.ch/)).

There is no `--with-sodium` option for Homebrew's php72:

```
$ brew options php72 | grep sodium
--without-libsodium
	Build without libsodium support
```

So, if not providing the `--without-libsodium` option, one could assume php72 is compiled with PHP 7.2 built-in Sodium. Will you include `--with-sodium` by default in the near future?

Is #4536 in master but not yet in php72 7.2.0_10?

**Comment by javian** [comment]
A fix for this has been merged and it should build the bundled extension by default now.

**Comment by onlime** [comment]
hey @javian great thanks for fixing this! I though that `if build.with? "libsodium"` sounded kind of wrong. :)
recompiled and tested, confirm working, all good.
