### ISSUE TITLE
Missed v8js.so extension in PHP 7.2 on High Sierra

### ISSUE THREAD

**Issue by gusbemacbe** [Homebrew/homebrew-php#4623]
## Description

Someobody counselled me to switch from Atom to Visual Studio Code.

I installed `phpcs` from @ikappas and the `phpcs` informations expected me to install `pear` and run `pear install php-code-sniffer`. As his informations were poorly documented. I followed other instructions and see: 
a) https://stackoverflow.com/a/36547172/8041366
b) https://stackoverflow.com/a/41070552/8041366

But their informations and instructions were bad, poorly documented and outdated, so the commands destroyed PHP, causing one of extensions to disappear.  

I tried to repair everything, reinstall Homebrew and PHP, installed php72-v8js and v8, etc., but the error continues the same.

## Context and Logs

```shell
PHP Warning:  PHP Startup: Unable to load dynamic library 'v8js.so' (tried: /usr/local/Cellar/php72/7.2.0_10/lib/php/extensions/no-debug-non-zts-20170718/v8js.so (dlopen(/usr/local/Cellar/php72/7.2.0_10/lib/php/extensions/no-debug-non-zts-20170718/v8js.so, 9): image not found), /usr/local/Cellar/php72/7.2.0_10/lib/php/extensions/no-debug-non-zts-20170718/v8js.so.so (dlopen(/usr/local/Cellar/php72/7.2.0_10/lib/php/extensions/no-debug-non-zts-20170718/v8js.so.so, 9): image not found)) in Unknown on line 0
```

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.1
**Homebrew version:**   | 1.3.8
**PHP version in use:** | 7.2.0
**Xcode version:**      | 9.1<sup>1</sup>

<sup>1</sup> I do not have Xcode installed. I installed only Command Line Tools.

**Output of `gcc -v`:**
```shell
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of `php -v`:**
```shell
PHP 7.2.0 (cli) (built: Dec  3 2017 06:11:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
Gustavos-Mac-mini:~ gusbemacbe$ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Build logs:** 
https://gist.github.com/anonymous/9da2e2f115d2bc3452ccf9ab6e9de7ee

**Comment by javian** [comment]
You need to readjust the path in the v8js extension config. It currently tries to load the extension from `/usr/local/Cellar/php72/7.2.0_10/lib/php/extensions/no-debug-non-zts-20170718/v8js.so` and if you installed the formula the extension should be located in `/usr/local/opt/php72-v8js...` . If you change that it ought to work.

**Comment by gusbemacbe** [comment]
Förlåt, @javian! 

I did a total clean uninstall and install of PHP without Pear. I removed `ext-v8js.ini` and the `extension=v8js.so` from `php.ini`. PHP worked without errors. 

Now I am afraid of reinstalling PHP with Pear and v8js, so the package `phpcs` of Visual Studio Code requires us to use Pear. I had to disable `phpcs`.

**Comment by javian** [comment]
I haven't tested it but I think you should be able to just install the homebrew packages for phpcs other things required and it should work. The install guide points you to pear/pecl and/or composer so maybe the latter would be another alternative.
