### ISSUE TITLE
Executing tap produce errors

### ISSUE THREAD

**Issue by tezrosolutions** [Homebrew/homebrew-php#4637]
## Executing "brew tap homebrew/homebrew-php" produce errors

See attached logs file.
[errors.log](https://github.com/Homebrew/homebrew-php/files/1531800/errors.log)

**Comment by javian** [comment]
Untapping `josegonzalez/php` should fix that.

**Comment by tezrosolutions** [comment]
@javian it says following:

brew untap osegonzalez/php
Error: No available tap osegonzalez/php.

**Comment by SMillerDev** [comment]
if you copy the entire text I think it'll work a lot better

**Comment by tezrosolutions** [comment]
@SMillerDev Here you go:

brew tap homebrew/homebrew-php
==> Tapping homebrew/php
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 801, done.
remote: Compressing objects: 100% (620/620), done.
remote: Total 801 (delta 534), reused 232 (delta 173), pack-reused 0
Receiving objects: 100% (801/801), 316.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (534/534), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/xdebug-osx.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/codeception.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phan@0.9.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/pdepend.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php-plantumlwriter.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phan@0.8.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/boris.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpspec.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/drush.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/robo.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/terminus.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpunit-skeleton-generator.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/behat.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php54-xhgui.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php55-xhgui.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpunit@5.7.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpctags.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phive.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/pickle.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/envoy.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phppgadmin.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpdocumentor.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php53-xhgui.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phing.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phan.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpcpd.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/n98-magerun2.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/terminus@0.13.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/symfony-installer.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/psysh.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php-code-sniffer.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/wp-cli.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpmd.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php56-xhgui.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/infection.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpmyadmin.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/virtphp.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/foreman.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/drush-launcher.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/arcanist.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/composer.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpbrew.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phploc.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpab.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/sqlformat.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/drupalconsole.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/mondrian.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/drupal-code-sniffer.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/composer@1.2.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/deployer.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/n98-magerun.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpdox.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/litmus-cli.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpmetrics.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/puli.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/pharcc.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/box.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php-cs-fixer.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php-code-sniffer@2.9.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phpunit.rb
Formulae found in multiple taps: 
       * josegonzalez/php/php53
       * homebrew/php/php53

Please use the fully-qualified name e.g. josegonzalez/php/php53 to refer the formula.
Error: Cannot tap homebrew/php: invalid syntax in tap!

**Comment by SMillerDev** [comment]
@tezrosolutions your untap command is missing the **j** in `josegonzalez/php`

**Comment by tezrosolutions** [comment]
@smerrill thanks it worked!
