### ISSUE TITLE
php72 --with-pdo-oci compiles successfully but breaks apache

### ISSUE THREAD

**Issue by plashenkov** [Homebrew/homebrew-php#4646]
## Description

I'm trying to use php with pdo-oci:

```bash
ORACLE_HOME=instantclient,/usr/local/lib,12.2 \
brew install php72 --with-httpd --with-pdo-oci --with-pear
```

It compiles successfully. But when trying to start Apache (`sudo apachectl start`), I'm getting the folllowing error:

```
httpd: Syntax error on line 173 of /usr/local/etc/httpd/httpd.conf:
Cannot load /usr/local/Cellar/php72/7.2.0_11/libexec/apache2/libphp7.so into server:
dlopen(/usr/local/Cellar/php72/7.2.0_11/libexec/apache2/libphp7.so, 10):
Symbol not found: _ons_recvthread_clone_sb\n
Referenced from: /usr/local/Cellar/instantclient-basic/12.2.0.1.0/lib/libons.dylib\n
Expected in: flat namespace\n
in /usr/local/Cellar/instantclient-basic/12.2.0.1.0/lib/libons.dylib
```

What's wrong? What can be done to fix this issue?

`php -a` runs fine and connects to Oracle successfully. I.e. the issue is related only to PHP inside Apache. Without `--with-pdo-oci` there is no such problem, Apache starts and serves successfully. I.e. the problem lies in (pdo-oci + starting PHP under Apache).

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | 1.4.0
**PHP version in use:** | PHP 7.2.0 (cli) (built: Dec 12 2017 01:13:48) ( NTS )
**Xcode version:**      | Xcode 9.2, Build version 9C40b

**Output of `gcc -v`:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**
```
PHP 7.2.0 (cli) (built: Dec 12 2017 01:13:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

**Build logs:** https://gist.github.com/a16e07de0389947e1837d959707f8ed8

**Comment by SMillerDev** [comment]
https://stackoverflow.com/questions/41918290/php-pdo-oci-driver-does-not-work-under-apache-but-does-work-from-console

Maybe this can help you? (I looked at the source but I couldn't find anything indicating that the apache config would be different from the CLI one)

**Comment by plashenkov** [comment]
Hmm... Looks like no.
In this SO question, the user says that Apache runs fine, but oci driver in PDO is not presented. In my case Apache does not start at all.
And in the answer I do not find anything I can try to solve the problem. He says that he used `--with-pdo-oci` param and it helped him. I initially use it.
The error I am getting says that symbol `_ons_recvthread_clone_sb` not found (referenced and expected in `libons.dylib`)... And this is only when running under Apache, when Apache tries to load `libphp7.so`...

**Comment by SMillerDev** [comment]
Hmm, if you're willing to give this another try. Can you reinstall both httpd and php72? There might have been some issues before with apache stuff.

**Comment by plashenkov** [comment]
Well, I've switched to pdo-oci v11 and it works (in contrast to oci v12.2).

**Comment by SMillerDev** [comment]
Ah, too bad for me but glad you got it working. Closing this now.

**Comment by plashenkov** [comment]
Thank you for your assistance!
