### ISSUE TITLE
php72 install with debug & enchant options + phalcon 3.2.0 may got 502 bad gateway

### ISSUE THREAD

**Issue by lanlin** [Homebrew/homebrew-php#4649]
## Description

```shell
brew install php72 --with-debug --with-enchant --with-homebrew-curl --with-pear --with-phpdbg --with-postgresql --without-legacy-mysql
```

with options above, install failed, enchant compile error.
remove "--with-enchant" install success, but got "502 bad gateway" after i install phalcon 3.2.0.
though i install phalcon with --build-from-source, still got 502 status.

when remove both "--with-enchant" and "--with-debug", it works.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:** 10.13.2 (17C88)
**Homebrew version:**   1.4.0
**PHP version in use:** 7.2
**Xcode version:**    9.2 (9C40b)

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.2.0 (cli) (built: Dec 13 2017 15:21:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** 
sorry, there's nothing logged. cause finally i install it by another way.

**Comment by SMillerDev** [comment]
Could it be that Phalcon doesn't work well with a PHP build that has debug symbols enabled?

**Comment by lanlin** [comment]
@SMillerDev maybe, i dont know.
I also create a same issue to the phalcon project.
[https://github.com/phalcon/cphalcon/issues/13211](https://github.com/phalcon/cphalcon/issues/13211)

**Comment by sergeyklay** [comment]
You have to remove `--with-debug`

**Comment by lanlin** [comment]
Ok, i did so. This issue can be closed now.

**Comment by javian** [comment]
Just so you know you can close the issue yourself since you created it.
