### ISSUE TITLE
configure: error: ZLIB extension requires gzgets in zlib --with-httpd Mac OS X 10.13.2 High Sierra

### ISSUE THREAD

**Issue by ginko** [Homebrew/homebrew-php#4652]
## Description

I'm running into issues installing php56 with the --with-httpd option. The error is configure: error: ZLIB extension requires gzgets in zlib.

I'm running Mac OS X 10.13.2 High Sierra. I've tried php72 as well and the result is the same. My xCode command line tools are up to date. I tried all the options mentioned above in vain not sure what else to do. I really hope someone can help.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 0.13.2 (17C88)(High Sierra)_
**Homebrew version:**   | _your Homebrew version (output of `1.4.0`)_
**PHP version in use:** | 7.1 (output of `/usr/bin/php -v`)_
**Xcode version:**      | Version 9.2 (9C40b)

**Output of `gcc -v`:**
_result of the CLI output_

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

This is the logout put link
https://gist.github.com/ginko/ad953ab78931173abb44e9d6c2f8b212

**Comment by javian** [comment]
I don't think the `--with-httpd` option makes a difference here. Can you try it without and see if it works ? `brew install -s php56`

**Comment by ginko** [comment]
Same error

hecking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
checking for zlib version >= 1.2.0.4... 1.2.11
checking for gzgets in -lz... no
configure: error: ZLIB extension requires gzgets in zlib

**Comment by SMillerDev** [comment]
> configure:27202: checking for ZLIB support
> configure:27238: result: yes
> configure:27247: checking if the location of ZLIB install directory is defined
> configure:27262: result: no
> configure:27595: checking for zlib version >= 1.2.0.4
> configure:27598: result: 1.2.11
> configure:27701: checking for gzgets in -lz
> configure:27726: clang -o conftest -g -O2 -fvisibility=hidden  -no-cpp-precomp  -Wl,-rpath,/usr/local/Cellar/libxml2/2.9.7/lib -L/usr/local/Cellar/libxml2/2.9.7/lib -Wl,-rpath,/usr/local/opt/openssl/lib -L/usr/local/opt/openssl/lib conftest.c -lz  -lcrypto -lssl -lcrypto -lm  -lxml2 -lz -liconv -lm -lkrb5 >&5
> ld: warning: ignoring file /usr/local/lib/libz.dylib, file was built for i386 which is not the architecture being linked (x86_64): /usr/local/lib/libz.dylib
> Undefined symbols for architecture x86_64:
>   "_gzgets", referenced from:
>       _main in conftest-9d124a.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I see in your logs that the install has some issues with your libxml version it seems. Can you run `brew reinstall libxml2` to see if it helps anything?

**Comment by ginko** [comment]
No luck still the same error

checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
checking for zlib version >= 1.2.0.4... 1.2.11
checking for gzgets in -lz... no
configure: error: ZLIB extension requires gzgets in zlib

**Comment by Chienle** [comment]
I think is the best solution for now and save time for your project is move to using Docker!

**Comment by SMillerDev** [comment]
What does `brew doctor` say?
And can you run `ls -al /usr/local/lib/libz.dylib` because it's trying to link to a dylib file that's not present on my system, and that seems to be for 32-bit systems.

**Comment by ginko** [comment]
After running brew doctor I get some warnings 

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcrypto.1.0.0.dylib
  /usr/local/lib/libcrypto.dylib
  /usr/local/lib/libklcsagt.dylib
  /usr/local/lib/libklcskca.dylib
  /usr/local/lib/libklcsnagt.dylib
  /usr/local/lib/libklcsrt.dylib
  /usr/local/lib/libklcsstd.dylib
  /usr/local/lib/libklcstr.dylib
  /usr/local/lib/libklmspack.0.1.0.dylib
  /usr/local/lib/libklmspack.0.dylib
  /usr/local/lib/libklmspack.dylib
  /usr/local/lib/libsqlite3.0.dylib
  /usr/local/lib/libssl.1.0.0.dylib
  /usr/local/lib/libssl.dylib
  /usr/local/lib/libz.1.2.6.dylib
  /usr/local/lib/libz.1.dylib
  /usr/local/lib/libz.dylib

Also after running -> ls -al /usr/local/lib/libz.dylib I get
-rw-r--r--@ 1 root  wheel  95312 Dec 15  2016 /usr/local/lib/libz.dylib

**Comment by SMillerDev** [comment]
Yeah, it seems like something installed dependencies in "/usr/local/lib/" that aren't compatible with the software you're trying to install. I'd remove the libz and libssl files there at least and try again.

**Comment by ginko** [comment]
Same error 
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by ginko** [comment]
Ok, so after removing the the libz and libssl files and running xcode-select --install fixed the issue ¯\_(ツ)_/¯

**Comment by SMillerDev** [comment]
Good to hear, closing this issue then.
