### ISSUE TITLE
php71-intl breaks PHP: Requires icu4c 60.1 but only 60.2 is installed

### ISSUE THREAD

**Issue by zabbarob** [Homebrew/homebrew-php#4654]
## Description

After updating homebrew PHP failed to run because php71-intl was looking for /usr/local/opt/icu4c/lib/libicudata.60.1.dylib but only /usr/local/opt/icu4c/lib/libicudata.60.2.dylib was installed

Reinstalling with `brew reinstall --build-from-source php71-intl` fixes the problem

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.11.6 El Capitan
**Homebrew version:**   | 1.4.0
**PHP version in use:** | 7.1.12
**Xcode version:**      | 7.3

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.12 (cli) (built: Dec  2 2017 12:14:16) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:** https://gist.github.com/1e461df23b7b4e8d84043e2bce95cf7e

**Comment by aadmathijssen** [comment]
I ran into this issue too, and could resolve it using `--build-from-source` as described above.

I also successfully tested this solution with `php70-intl` and `php56-intl`.

**Comment by alcaeus** [comment]
See #4653.

**Comment by cordoval** [comment]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-intl/intl.so' (tried: /usr/local/opt/php72-intl/intl.so (dlopen(/usr/local/opt/php72-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/opt/php72-intl/intl.so
  Reason: image not found), /usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so (dlopen(/usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-intl/intl.so' (tried: /usr/local/opt/php72-intl/intl.so (dlopen(/usr/local/opt/php72-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/opt/php72-intl/intl.so
  Reason: image not found), /usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so (dlopen(/usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so, 9): image not found)) in Unknown on line 0
q^C

solved it with 

brew reinstall --build-from-source php72-intl

**Comment by inoas** [comment]
@cordoval yes, this solves the issue. Somehow the bottled package is broken.

**Comment by SMillerDev** [comment]
This should be fixed by #4663

**Comment by mcfedr** [comment]
Same for php-55

**Comment by trevorpan** [comment]
I used your reinstall. It was successful. However, I receive this error message. Do you have any ideas where I've gone wrong?

```
Warning: PHP Startup: Unable to load dynamic library '/Applications/MAMP/bin/php/php7.1.12/lib/php/extensions/no-debug-non-zts-20160303/intl.so' - dlopen(/Applications/MAMP/bin/php/php7.1.12/lib/php/extensions/no-debug-non-zts-20160303/intl.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/Applications/MAMP/bin/php/php7.1.12/lib/php/extensions/no-debug-non-zts-20160303/php_intl.so' - dlopen(/Applications/MAMP/bin/php/php7.1.12/lib/php/extensions/no-debug-non-zts-20160303/php_intl.so, 9): image not found in Unknown on line 0
```

**Comment by josegonzalez** [comment]
@trevorpan Judging by the error, that php is likely not the php from homebrew-php, but rather is for MAMP. I suggest you look into your `$PATH` environment variable to see where you are loading the php binary from.

**Comment by trevorpan** [comment]
Hi @josegonzalez thank you. I've been trying to reconcile the two. I've applied this:

`Trevors-Mac-mini:~ trevorpan$  printenv
 MAMP_PHP=/Applications/MAMP/bin/php/php7.1.12/bin
 TERM_PROGRAM=Apple_Terminal
 SHELL=/bin/bash
 TERM=xterm-256color
 TMPDIR=/var/folders/jq/0x4l2gt17p12gttsjnsjm35r0000gn/T/
 Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.mYPOHx34Mk/Render
 TERM_PROGRAM_VERSION=400
 TERM_SESSION_ID=4B9811C0-A500-406D-8CCB-55935224023D
 USER=trevorpan
 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pmLJnIb4sm/Listeners
 PATH=/Applications/MAMP/bin/php/php7.1.12/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local  /mysql/bin
 PWD=/Users/trevorpan
 LANG=en_US.UTF-8
 XPC_FLAGS=0x0
 XPC_SERVICE_NAME=0
 SHLVL=1
 HOME=/Users/trevorpan
 LOGNAME=trevorpan
 _=/usr/bin/printenv`

I'm pretty much brand new to using terminal. Should I add the PATH to the ~/.bash_profile ?

Here's the ~/.bash_profile:

`export MAMP_PHP=/Applications/MAMP/bin/php/php7.1.12/bin
 export PATH="$MAMP_PHP:$PATH"

 if [ -f ~/.bashrc ]; then
	 source ~/.bashrc 
 fi`

**Comment by trevorpan** [comment]
I see. Pardon me, I thought the homebrew-php had to be synced with MAMP. Still trying to piece together all parts.  Thank you.
