### ISSUE TITLE
php71 Unknown: failed to open stream: No such file or directory in Unknown on line 0

### ISSUE THREAD

**Issue by pedropcruz** [Homebrew/homebrew-php#4664]
## Description

Hello there, my problem is after i make ```brew upgrade``` and i get this error on my project

```
Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required (here is the PATH) (include_path='.:') in Unknown on line 0
```

I already found people asking for this, but i cant solve my problem.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | Homebrew 1.4.1-3-g426c998
**PHP version in use:** | 7.1.12
**Xcode version:**      | Xcode 9.2 / Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.12 (cli) (built: Dec  2 2017 12:15:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:** No Logs.

**Comment by moderndeveloperllc** [comment]
@pedropcruz You may wish to try and rebuild from source. If you are sure it's the `intl` extension, try `brew reinstall --build-from-source php71-intl`. You can rebuild as many of the PHP extensions as you wish just by adding it to that list.

**Comment by pedropcruz** [comment]
@moderndeveloperllc already try that and doesnt work. Where i can see where the problem starts or how? thanks

**Comment by SMillerDev** [comment]
Google search suggests that it might be a permission problem. Are you sure the user that you're running this as has access to the files that are being read by PHP?

**Comment by pedropcruz** [comment]
yeap, as @SMillerDev said, its a permission problem.

I have to force php command. I use grunt on my project, so i need to change the command, a force with -f, like:

```js
exec: {
            php: {
                cmd: 'php -S localhost -t web -f web/index.php'
            }
        },
```
