### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-mongodb/mongodb.so'

### ISSUE THREAD

**Issue by Chienle** [Homebrew/homebrew-php#4667]
## Description

I'm got an issue with php72-mongodb, please help me when you have time,
When I install php72 and mongodb with home brew command bellow: 
brew install php72-mongodb --with-http
Then I restart httpd with command: 
sudo apachectl start
My apache cannot start and in the log file have errors with messages bellow: 

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-mongodb/mongodb.so' (tried: /usr/local/opt/php72-mongodb/mongodb.so (dlopen(/usr/local/opt/php72-mongodb/mongodb.so, 9): image not found), /usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-mongodb/mongodb.so.so (dlopen(/usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-mongodb/mongodb.so.so, 9): image not found)) in Unknown on line 0

Please help me or let me know any suggestion.

Parameter | Value
--------- | ------------------
**macOS version:**       |10.13.2 _
**Homebrew version:**   |1.4.1-3-g426c998 _
**PHP version in use:** | 7.2.0_
**Xcode version:**      | _your Xcode version (output of `xcodebuild -version`)_

**Comment by SMillerDev** [comment]
does `/usr/local/opt/php72-mongodb/mongodb.so` actually exist?

**Comment by Chienle** [comment]
yes, it is exist!

**Comment by Chienle** [comment]
Dear @SMillerDev 
Thank for you support!, When I running command: php -v
I got any php extension has supported but I am checking phpinfo() on web  my apache cannot running.

**Comment by SMillerDev** [comment]
`php -v` shouldn't output the supported extensions so that's pretty weird, can you post the complete output for it?

**Comment by silov** [comment]
I met a similar problem with you...

```shell
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-http/http.so' (tried: /usr/local/opt/php72-http/http.so (dlopen(/usr/local/opt/php72-http/http.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/opt/php72-http/http.so
  Reason: image not found), /usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-http/http.so.so (dlopen(/usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-http/http.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-http/http.so' (tried: /usr/local/opt/php72-http/http.so (dlopen(/usr/local/opt/php72-http/http.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/opt/php72-http/http.so
  Reason: image not found), /usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-http/http.so.so (dlopen(/usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-http/http.so.so, 9): image not found)) in Unknown on line 0
PHP 7.2.0 (cli) (built: Jan  3 2018 16:10:21) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0alpha1, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by SMillerDev** [comment]
@silov this means you have a config file for php72-http but no extension installed. Check `ls /usr/local/etc/php/7.2/conf.d/`.

This isn't the same as @Chienle his issue though, according to his description.

**Comment by silov** [comment]
@SMillerDev nop. I have a config file `/usr/local/etc/php/7.2/conf.d/zzz_ext-http.ini`, said that :
```
[http]
extension="/usr/local/opt/php72-http/http.so"
```
and I also have the `.so` file `/usr/local/opt/php72-http/http.so` 

but the warning said I need a `.so` file 
`/usr/local/Cellar/php72/7.2.0_11/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-http/http.so.so` which i do not have
