### ISSUE TITLE
Brew build environment cannot find installed packages

### ISSUE THREAD

**Issue by jyaworski** [Homebrew/homebrew-php#4669]
## Description

I'm wondering if the `brew sh` environment for these extensions is supposed to be so different from my regular shell. Looking at configure logs, it seems that it can't find things that I know are installed; running configure outside of brew finds these files. Is this intentional? If so, could you explain the rationale behind it?

Thank you!

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | Homebrew 1.4.1-7-g75d0321
**PHP version in use:** | PHP 7.1.12
**Xcode version:**      | 9.2

**Output of `gcc -v`:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**
```
PHP 7.1.12 (cli) (built: Dec 21 2017 10:28:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Build logs:**
Not inside Homebrew, `./configure`:

```
checking for re2c... re2c
checking for re2c version... 1.0.3 (ok)
checking for gawk... gawk
...
checking for pkg-config... /usr/local/bin/pkg-config
```

Inside Homebrew:

```
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
...
checking for pkg-config... no
```

**Comment by SMillerDev** [comment]
I think this is a question better asked at https://github.com/Homebrew/brew since it's not really specific to PHP.

**Comment by SMillerDev** [comment]
Actually might be better on https://discourse.brew.sh/ since it isn't really a bug but more of a question. Either way I'm closing it here.
