### ISSUE TITLE
composer not working with passthru()

### ISSUE THREAD

**Issue by symoo** [Homebrew/homebrew-php#4679]
## Description
Hello
I be using composer via brew for a time, and it not working right now. 
```
 ~ composer
```
when I run composer command and it show nothing and hung up there like forever.
so I try to run composer.phar with php, it works perfectly.
```
php /usr/local/Cellar/composer/1.5.6/libexec/composer.phar
Composer version 1.5.6 2017-12-18 12:09:18
.....
```
I found out the problem is  passthru()
in `/usr/local/Cellar/composer/1.5.6/libexec/composer` file it use passthru() function to run composer, so I also try did this
```
php -r 'passthru("/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off/usr/local/Cellar/composer/1.5.6/libexec/composer.phar --ansi -vvv");'
```
and still working good.

Then problem only happens when running a php file which it using `passthru("/usr/bin/env php -/usr/local/Cellar/composer/1.5.6/libexec/composer.phar", $return_var); `

I have no clue what cause this. Is there any thing missing?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |  `10.13.2`
**Homebrew version:**   |  `Homebrew 1.4.1 Homebrew/homebrew-core (git revision 5664; last commit 2017-12-27)`
**PHP version in use:** | `PHP 7.1.12 (cli) (built: Dec  2 2017 12:15:25) ( NTS )`
**Xcode version:**      |  not installed  `xcode-select version 2349.`

**Output of `gcc -v`:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
**Output of `php -v`:**
```
PHP 7.1.12 (cli) (built: Dec  2 2017 12:15:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
```
brew gist-logs composer
Error: No logs.
```

**Comment by SMillerDev** [comment]
So your `passthru()` seems to be broken, but only in PHP files?

**Comment by symoo** [comment]
I spent hours on this problem... but composer works again when I go back after dinner...
