### ISSUE TITLE
Install php 7.1 fails with pear 

### ISSUE THREAD

**Issue by medskill** [Homebrew/homebrew-php#4682]
## Description

$ brew install php71 --with-pear --with-httpd24 
==> Installing php71 from homebrew/php
Warning: homebrew/php/php71: --with-httpd24 was deprecated; using --with-httpd instead!
==> Downloading https://php.net/get/php-7.1.12.tar.bz2/from/this/mirror
Already downloaded: /Users/aram/Library/Caches/Homebrew/php71-7.1.12
==> ./configure --prefix=/usr/local/Cellar/php71/7.1.12_23 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --with-config-file-path=/usr/local/etc/php/7.1 --with-config-file-scan-dir=/usr/local/etc/php/7.1/conf.d --mandir=/usr/local/Cellar/php71/7.1.12_23/share/man --enab
==> make
==> make install
==> /usr/local/Cellar/php71/7.1.12_23/bin/pear config-set php_ini /usr/local/etc/php/7.1/php.ini system
Last 15 lines from /Users/aram/Library/Logs/Homebrew/php71/04.pear:
2018-01-01 23:40:55 +0100

/usr/local/Cellar/php71/7.1.12_23/bin/pear
config-set
php_ini
/usr/local/etc/php/7.1/php.ini
system

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
php71 mongoDB ext crashing php https://github.com/Homebrew/homebrew-php/issues/4607
php71-opcache: opcache.file_cache doesn't work https://github.com/Homebrew/homebrew-php/issues/4574
php71-libsodium - Library not loaded: /usr/local/opt/libsodium/lib/libsodium.18.dylib https://github.com/Homebrew/homebrew-php/issues/4589

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | Homebrew 1.4.2
**Xcode version:**      | Xcode 9.2

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by SMillerDev** [comment]
Could you use `brew gist-logs my-formula` to upload the logs?

**Comment by Garfield-fr** [comment]
Hi,
I have the same problem. Command "brew install php71 --with-pear"
My log: https://gist.github.com/anonymous/c780f9e01b780253df2db76776a92281

Thank's for your help

**Comment by SMillerDev** [comment]
Had to go down the archives pretty far but it seems to be related to the oracle instant client as first discovered when compiling php 5.4: https://github.com/Homebrew/homebrew-php/issues/543#issuecomment-21077776

**Comment by Garfield-fr** [comment]
@SMillerDev Thank's for your comment. I disabled ldap in my install with "brew install php71 --with-pear --without-ldap" and let's go.
