### ISSUE TITLE
Where do I start for building PHP myself.

### ISSUE THREAD

**Issue by rquadling** [Homebrew/homebrew-php#4684]
Hi.

Wanting to play with some changes to the SOAP classes. Having trouble building from outside of HomeBrew, so wondering how I should do things inside HomeBrew.

Is there a  page/blog about building PHP via HomeBrew?

**Comment by SMillerDev** [comment]
you can check how homebrew does the install in ~/Library/Logs/Homebrew/php72/. But the whole idea behind homebrew and package managers in general is compiling software so you don't have to. So I doubt there's much documentation on the matter.

**Comment by rquadling** [comment]
Ah. OK.
