### ISSUE TITLE
Unable to use pdo-pgsql with php 7.1

### ISSUE THREAD

**Issue by Samnan** [Homebrew/homebrew-php#4699]
## Unable to get pdo-pgsql to run with brew and php7.1

I have php 7.1 installed using brew (along with httpd). When i try to install php71-pdo-pgsql, it starts downloading php source code again, and after rebuilding and installing the pgsql extension, apache fails to run. I tried removing all php packages, completely cleaning brew cache, then reinstalled php 7.1, and then installed extensions one by one and tested, as soon as i install pdo-pgsql, apache stop running again. Php complains about unable to load the extension. Tried the same with building from source and without, neither works.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:** 
 10.12.5

**Homebrew version:**
Homebrew 1.3.9
Homebrew/homebrew-core (git revision e3a8; last commit 2017-12-04)

**PHP version in use:**
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so
  Expected in: flat namespace
 in /usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so in Unknown on line 0
PHP 7.1.12 (cli) (built: Jan  5 2018 12:51:49) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies

**Xcode version:**
Xcode 8.2.1
Build version 8C1002

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so
  Expected in: flat namespace
 in /usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so in Unknown on line 0
PHP 7.1.12 (cli) (built: Jan  5 2018 12:51:49) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies

**Build logs:**
https://gist.github.com/30fd38b599b91f7b5681b1c34f62b022

( when i do brew gist-logs php71-pdo-pgsql, it says nothing found, but i know there were no errors in the build when i installed the extension)

**Comment by javian** [comment]
You are using the threaded version of PHP which isn't compatible with the bottled version. You need to do `brew reinstall -s php71-pdo-pgsql` which should resolve the issue.

**Comment by Samnan** [comment]
Thanks, let me try that and I will update the thread with the results.

**Comment by Samnan** [comment]
Its doing the same thing all over again, starts downloading php 7.1.12 just like it did before, i have tried installing from source already as mentioned in the issue, both result is apache failing to run because both times instead of just installing the extension, my php is recompiled in non thread safe mode and that causes apache to fail (because i am using mod event).

**Comment by javian** [comment]
And you can't change apache to use prefork ?

**Comment by Samnan** [comment]
I don't exactly remember the error, but i tried changing mod event to prefork, but it still did not work. It is my main system otherwise i would try running the install to give you a detailed log of my installation problem.

On another note, I tried testing installing some other php extension just to see, and brew install php71-intl also does the same thing.. 

the funny thing is, i installed a few other extension with commands like
brew install php71-apcu -s
brew install php71-phalcon -s
brew install php71-mongodb -s
...

they all seem to just download extension source and compile and things work fine, but with pdo-pgsql and intl extension, brew starts downloading the php full source code, and after that things just go bad when its done.

Maybe that could give you a clue as to what could be the issue and how to resolve it. If I get some time i will try and doing the same on another system to see if i get the same problem and can give you the logs.

**Comment by javian** [comment]
It should download the full source code since those extensions are part of the core php source so that's not wrong. It should however only compile the necessary parts and not touch the rest of php.

**Comment by Samnan** [comment]
That is correct, but why does it start downloading php again for this extension, whereas for all others it uses the one found in homebrew cache?

**Comment by SMillerDev** [comment]
It shouldn't, so that's either a bug or you downloaded it for that extension version before.

**Comment by Samnan** [comment]
Ok it maybe a bug, but i found a workaround to get things going, might help someone else having same issue:

- go to ~/Library/Caches/Homebrew
- extract php source code from the package file (for me it was php-7.1.12)
- cd to the folder and run the original php configure command (check phpinfo() and it will have the full configure command)
- cd into the ext/pdo_pgsql folder and run 'phpize', 'configure', 'make', 'make install'

once done it install the extension in a rather different path, but that is not a big problem. Just added the extension ini to php and now pgsql seems to work for me.
