### ISSUE TITLE
PHP on Mac HighSierra pre-installed

### ISSUE THREAD

**Issue by zishanj** [Homebrew/homebrew-php#4700]
I am using HighSierra and PHP 7.1 comes pre-installed on it. I now wants to install `ext-gmp` and tried with `brew install php71-gmp` successfully and then checked with `phpinfo()`, couldn't found that extension there.

Is there any possibility to use pre-installed 7.1  instead of installing it again with brew?

**Comment by javian** [comment]
The modules needs to be loaded and the gmp formula doesn't support working with whatever comes with macos and therefore it won't work automatically. You should be able to try and load the module in the config and see if that works.
