### ISSUE TITLE
"Abort trap: 6" while attempting to connect to MySQL with SSL

### ISSUE THREAD

**Issue by nexces** [Homebrew/homebrew-php#4707]
## Description

As in topic: Cannot connect to MySQL server with SSL enabled.

Sample code:
```php
$options = [
    PDO::MYSQL_ATTR_SSL_CA   => 'client-key.pem',
    PDO::MYSQL_ATTR_SSL_CERT => 'client-cert.pem',
    PDO::MYSQL_ATTR_SSL_CA   => 'ca-cert.pem',
];
$db = new PDO('mysql:host='.$host.';port='.$port.';dbname='.$db.'', $username, $passwd, $options);
```
As sample DB you can use MySQL image from docker - it is SSL enabled and provides required ssl files.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | Homebrew 1.4.1 Homebrew/homebrew-core (git revision 8ca4cb; last commit 2017-12-28)
**PHP version in use:** | PHP 7.1.12
**Xcode version:**      | Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.13 (cli) (built: Jan  5 2018 15:31:15) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** 
```bash
$ brew gist-logs php71
Error: No logs.
```

**Comment by SMillerDev** [comment]
This stackoverflow issue suggests it's strict host validation: https://stackoverflow.com/questions/46536121/php-7-1-cli-connection-to-remote-db-with-ssl-fails-with-abort-trap-6

**Comment by nexces** [comment]
According to https://bugs.php.net/bug.php?id=71003 there is a constant `PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT`  which can be used to control this verification.

My IDE (PhpStorm) does not know this constant and also php.net does not know this constant. However it is set to something in PHP im using.
```
php > var_dump(PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT);
int(1014)
```
But setting options to:
```php
$options = [
    PDO::MYSQL_ATTR_SSL_CA   => 'client-key.pem',
    PDO::MYSQL_ATTR_SSL_CERT => 'client-cert.pem',
    PDO::MYSQL_ATTR_SSL_CA   => 'ca-cert.pem',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
];
```
gives "Abort trap: 6" error

**Comment by javian** [comment]
Does it work if you try it with the MySQL cli with the same certificates ?

**Comment by nexces** [comment]
Yes, it works - same files, same server, same user.

**Comment by nexces** [comment]
So... anyone? anything?

**Comment by SMillerDev** [comment]
Can you try and get a backtrace with gdb or whatever you prefer?
And can you open a bugreport on bugs.php.net for this, in a worst case scenario it's actually a bug in homebrew, but I suspect it might be a bug in PHP.

**Comment by nexces** [comment]
I can make gdb backtrace. However I would like to ask you to provide me instructions on how to do one.

**Comment by SMillerDev** [comment]
First you'll have to `brew install php --with-debug $YOUR_FLAGS` after which you can use this guide: https://bugs.php.net/bugs-generating-backtrace.php to get a backtrace using `gdb`

**Comment by javian** [comment]
Have you checked if there's anything in the macOS console logs ?

**Comment by nexces** [comment]
i've found this in console:
```
338: 0x495cd0	debuguj	17:10:01.793021 +0100	taskgated	begin request: 4867, 27001
338: 0x495cd0	debuguj	17:10:01.793273 +0100	taskgated	open(/usr/local/Cellar/php71/7.1.13_24/bin/php,0x0,0x1b6) = 3
338: 0x495cd0	debuguj	17:10:01.793312 +0100	taskgated	0x7fa31d7128e0 is a thin file (x86_64)
338: 0x495cd0	wartość domyślna	17:10:01.793795 +0100	taskgated	MacOS error: -67062
338: 0x495cd0	debuguj	17:10:01.794235 +0100	taskgated	0   Security                            0x00007fff58526fb3 Security::CommonError::LogBacktrace() + 87
338: 0x495cd0	debuguj	17:10:01.794266 +0100	taskgated	1   Security                            0x00007fff585274d3 Security::MacOSError::MacOSError(int) + 241
338: 0x495cd0	debuguj	17:10:01.794291 +0100	taskgated	2   Security                            0x00007fff5852756e Security::MacOSError::throwMe(int) + 34
338: 0x495cd0	debuguj	17:10:01.794313 +0100	taskgated	3   Security                            0x00007fff5840a656 SecCodeMapMemory + 170
338: 0x495cd0	debuguj	17:10:01.794335 +0100	taskgated	4   taskgated                           0x000000010042c612 taskgated + 9746
338: 0x495cd0	debuguj	17:10:01.794356 +0100	taskgated	5   taskgated                           0x000000010042cae5 taskgated + 10981
338: 0x495cd0	debuguj	17:10:01.794378 +0100	taskgated	6   taskgated                           0x000000010042cfa1 taskgated + 12193
338: 0x495cd0	debuguj	17:10:01.794398 +0100	taskgated	7   taskgated                           0x000000010042d016 taskgated + 12310
338: 0x495cd0	debuguj	17:10:01.794419 +0100	taskgated	8   taskgated                           0x000000010042e977 taskgated + 18807
338: 0x495cd0	debuguj	17:10:01.794485 +0100	taskgated	9   taskgated                           0x000000010042f140 taskgated + 20800
338: 0x495cd0	debuguj	17:10:01.794536 +0100	taskgated	10  taskgated                           0x000000010042e01b taskgated + 16411
338: 0x495cd0	debuguj	17:10:01.794592 +0100	taskgated	11  libsystem_pthread.dylib             0x00007fff742c16c1 _pthread_body + 340
338: 0x495cd0	debuguj	17:10:01.794642 +0100	taskgated	12  libsystem_pthread.dylib             0x00007fff742c156d _pthread_body + 0
338: 0x495cd0	debuguj	17:10:01.794697 +0100	taskgated	13  libsystem_pthread.dylib             0x00007fff742c0c5d thread_start + 13
338: 0x495cd0	debuguj	17:10:01.794815 +0100	taskgated	no system signature for unsigned /usr/local/Cellar/php71/7.1.13_24/bin/php[30354]
338: 0x495cd0	debuguj	17:10:01.794867 +0100	taskgated	close(3) err: 0
338: 0x495cd0	debuguj	17:10:01.794897 +0100	taskgated	end request
...
30354: 0x495f8d	wartość domyślna	17:10:01.876656 +0100	php	detected source and destination buffer overlap
```

**Comment by javian** [comment]
Looking at the console error `no system signature for unsigned` php might need to be signed. See https://discussions.apple.com/thread/7705551?start=0&tstart=0 and https://github.com/Homebrew/homebrew-core/issues/11378 where there's also an snippet on how to sign it.
