### ISSUE TITLE
phpunit install fails when using php72

### ISSUE THREAD

**Issue by NoodlesNZ** [Homebrew/homebrew-php#4713]
## Description

When trying to install phpunit brew complains about missing core php install, although it's installed. I reinstalled php72, but it didn't help

## Context and Logs

[noodles@macncheese utils (master)]$ brew install phpunit
==> Installing phpunit from homebrew/php
phpunit: Missing a core php install from homebrew-php.
Please run: brew install php72
or install another php version from the homebrew-php tap
Error: An unsatisfied requirement failed this build.

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | Homebrew 1.4.3 Homebrew/homebrew-core (git revision f1bda; last commit 2018-01-16)
**PHP version in use:** | PHP 7.2.1
**Xcode version:**      | Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.2.1 (cli) (built: Jan  5 2018 17:34:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans

**Build logs:** 
```
brew gist-logs phpunit
Error: No logs.
```

**Comment by SMillerDev** [comment]
It should be fixed by now, please let me know if it still fails

**Comment by NoodlesNZ** [comment]
Thanks, working now
