### ISSUE TITLE
Homebrew/php deprecation

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-php#4721]
As [announced today](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. A [PR to add a `php` formula homebrew/core is ongoing](https://github.com/Homebrew/homebrew-core/pull/16067). 

- Once this is merged we'll accept additional `php@` versioned formulae for versions listed both here: https://brew.sh/analytics/install and here: http://php.net/downloads.php that will be still maintained for a reasonable amount of time after 31st March 2018 and [meet all the versioned formulae requirements](https://docs.brew.sh/Versions.html).
- We will not accept versioned formulae such as `php71-mcrypt` but any of those listed on https://brew.sh/analytics/install/ will be accepted as part of the default, core or versioned `php` formulae as `resource`s.
- We will accept additional application (not library) formulae (such as `composer`) listed here: https://brew.sh/analytics/install/

Help is actively welcomed on any of the above. Let's keep conversation away from disagreement with the decision as that's something that's not going to change, thanks.

**Comment by alcaeus** [comment]
> We will not accept versioned formulae such as `php71-mcrypt` but any of those listed on https://brew.sh/analytics/install/ will be accepted as part of the default

Forgive my stupid question, I'm not sure I understand: there won't be a `php71-mcrypt`, but there may be a `php-mcrypt`, as long as it accepts any installed php package?

In the announcement, you also mentioned the CI workload as a reason for deprecating the tap. Until the tap is officially archived, would it make sense to limit formula updates to supported PHP versions (at this time, 5.6, 7.0, 7.1 and 7.2) in order to reduce CI workload and bottle builds?

**Comment by MikeMcQuaid** [comment]
> Forgive my stupid question, I'm not sure I understand: there won't be a php71-mcrypt, but there may be a php-mcrypt, as long as it accepts any installed php package?

There won't be either but we'd accept the `php` or `php@7.1` formula installing `mcrypt` by default.

> In the announcement, you also mentioned the CI workload as a reason for deprecating the tap. Until the tap is officially archived, would it make sense to limit formula updates to supported PHP versions (at this time, 5.6, 7.0, 7.1 and 7.2) in order to reduce CI workload and bottle builds?

I don't want to dictate how this tap is run pre-deprecation. That might not be a bad idea but given the tap is going away in a few months I think it's fine as-is until then.

**Comment by alcaeus** [comment]
> There won't be either but we'd accept the `php` or `php@7.1` formula installing `mcrypt` by default.

Ah, I see, thank you for the explanation! 👍 

As for deprecated PHP versions, I've suggested removing unmaintained versions before but it hasn't really gained any traction so it would make sense to keep old versions around if they are not causing big trouble at this time.

**Comment by javian** [comment]
Yeah lets not touch the older versions until we migrate everything to core and we will remove (or pass it on to another group of people) them altogeher.

**Comment by Aierui** [comment]
kao

**Comment by fterrag** [comment]
I'm sorry, but I'm a little unclear on how older PHP versions will be supported. If one wanted to install PHP 5.6, would that still be done through this repo (i.e., brew tap homebrew/homebrew-php)?

**Comment by javian** [comment]
@fterrag no, the tap would eventually be removed/retired so anything that will be left and supported by the homebrew team will exist in homebrew-core. We are planning on migrating based on current user data which would initially include 7.2, 7.1 and 5.6 .

**Comment by valentinocossar** [comment]
> There won't be either but we'd accept the php or php@7.1 formula installing mcrypt by default.

Sorry, but right now to install php with Homwbrew I have to run `brew install php72`. Why I can't install different versions of php with a suffix like `brew install php@7.2`? It's a stupid question, but I don't understand why other formulae are using a suffix with the `@` to declaring version during the installation process and php doesn't.

Sorry, maybe this is the wrong place where to ask this question, but I noticed the answer quoted above and I decided to ask. Anyway, thank you in advance.

**Comment by MikeMcQuaid** [comment]
> Right now to install php with Homwbrew I have to run brew install php72. Why I can't install different versions of php with a suffix like brew install php@7.2? It's a stupid question, but I don't understand why other formulae are using a suffix with the @ to declaring version during the installation process and php doesn't.

This will change when the migration is complete.

**Comment by MikeLund** [comment]
> We are planning on migrating based on current user data which would initially include 7.2, 7.1 and 5.6

Hi, is there somewhere to see the exact numbers? Is 7.0 really that unpopular to be excluded? I'm still a fan of 7.0 and will be sad to see it gone before it's fully EOL.

**Comment by MikeMcQuaid** [comment]
> Hi, is there somewhere to see the exact numbers?

No, sorry.

> I'm still a fan of 7.0 and will be sad to see it gone before it's fully EOL.

You can maintain the formula in your own tap. I suggest forking this tap before that point so you can still use it.

**Comment by valentinocossar** [comment]
> This will change when the migration is complete.

Oh super! The completion of the migration is planned by the 31st March 2018? Or the new versioning system to install PHP will change later?

Thank you!
