### ISSUE TITLE
"Calling <<-EOS.undent is deprecated!"

### ISSUE THREAD

**Issue by postmastersteve** [Homebrew/homebrew-php#4722]
I ran `brew reinstall php71 --with-httpd` and got this during the build:

```
Already downloaded: /Users/steve/Library/Caches/Homebrew/php71-7.1.13
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!
```

*macOS version:*       | _10.12.6_
*Homebrew version:*   | _1.5.0_

**Comment by SMillerDev** [comment]
should be fixable by running `brew update` since there's already commits to fix this in this tap

**Comment by henryncal** [comment]
Same issue seen multiple times during same reinstall; same Homebrew version, MacOS 10.13.2.

"brew update" had no effect

**Comment by javian** [comment]
If you've not made any changes to your taps yourself then it should be safe to `brew update-reset` to reset homebrew and related taps to their current state.

**Comment by SMillerDev** [comment]
Does this suggestion resolve the issue @henryncal and @postmastersteve ?

**Comment by jocel1** [comment]
I've still the issue on my system after a brew update-reset.
It seems to complain about the <<-EOPLIST.undent (the warning is wrong).
If I change <<-EOPLIST.undent to <<-EOPLIST , no more warning

**Comment by leewillis77** [comment]
I'm also seeing this trying to upgrade to 7.1.13_24.

brew update-reset makes no difference here either.

**Comment by nntoan** [comment]
I keep seeing this even after `brew update-reset`. I'm using OS 10.11

**Comment by Chudesnov** [comment]
Just installed php71 using fresh tapped homebrew-php, same error:

```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!
```

**Comment by SMillerDev** [comment]
There has just been some commits that would fix this. Could anyone check what happens after a `brew update`?

**Comment by JoeNoPhoto** [comment]
Still erroring for me:

```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/puma/homebrew-puma/puma-dev.rb:30:in `caveats'
Please report this to the puma/puma tap!
```

**Comment by alcaeus** [comment]
It says
> Please report this to the puma/puma tap

**Comment by leewillis77** [comment]
@SMillerDev I can confirm that 7.1.14_25 works for me.
