### ISSUE TITLE
Installing php70 --with-httpd on High Sierra fails with error during "make"

### ISSUE THREAD

**Issue by ahc2483** [Homebrew/homebrew-php#4724]
## Description

Installing php70 --with-httpd fails with error during "make"

## Context and Logs
Last 15 lines from /Users/Andrew/Library/Logs/Homebrew/php70/02.make:
sapi/apache2handler/php_apache.h:24:10: fatal error: 'httpd.h' file not found
#include "httpd.h"
         ^~~~~~~~~
1 error generated.
make: *** [sapi/apache2handler/mod_php7.lo] Error 1
/private/tmp/php70-20180121-37474-12w6qp0/php-7.0.27/sapi/apache2handler/sapi_apache2.c:41:10: fatal error: 'ap_config.h' file not found
#include "ap_config.h"
         ^~~~~~~~~~~~~
1 error generated.
make: *** [sapi/apache2handler/sapi_apache2.lo] Error 1
/private/tmp/php70-20180121-37474-12w6qp0/php-7.0.27/sapi/apache2handler/php_functions.c:33:10: fatal error: 'ap_config.h' file not found
#include "ap_config.h"
         ^~~~~~~~~~~~~
1 error generated.
make: *** [sapi/apache2handler/php_functions.lo] Error 1

Parameter | Value
--------- | ------------------
**macOS version:**      10.13.2
**Homebrew version:**   Homebrew 1.5.0
Homebrew/homebrew-core (git revision 69f74; last commit 2018-01-21)
**PHP version in use:** PHP 7.0.27 (cli) (built: Jan  5 2018 12:26:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
**Xcode version:**      Xcode 9.2
Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.0.27 (cli) (built: Jan  5 2018 12:26:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
**Xcode version:**      Xcode 9.2
Build version 9C40b

**Build logs:** https://gist.github.com/20d4e270d949f3cb9d9e0ef16dbaec3d

**Comment by SMillerDev** [comment]
What version of apache was installed?

**Comment by ahc2483** [comment]
I installed version 2.4.29 of the httpd package

**Comment by SMillerDev** [comment]
Seems to be an issue with the apache install. Can you try doing `brew reinstall httpd apr apr-util`? This will reinstall apache, so any missing header files should be reinstalled.

**Comment by ahc2483** [comment]
Thank you for the response - unfortunately, I still received the same error during php70 install after reinstalling httpd with apr and apr-util

**Comment by SMillerDev** [comment]
can you see if reinstalling commandline tools has any affect on this?

**Comment by aolin480** [comment]
Any updates on this? I tried the following and it's still giving me the error:

- `brew reinstall -s apr-util apr httpd24`
- Removed xcode commandline tools and reinstalled

**Comment by SMillerDev** [comment]
The `brew doctor` output in your initial gist mentions that `httpd` is unlinked, which might cause issues with building software that depends on it. (like `php --with-httpd`)

Could you try `brew link httpd`?

**Comment by aolin480** [comment]
@SMillerDev: Oh wow, interesting. So I tried the `brew link httpd` but that gave an error saying it couldn't overwrite httpd, so I just included the `--overwrite` flag, and _then_ tried `brew install php70 --with-httpd` and it went past the configure task, and onto the `make`, and `make install` and it worked perfectly! Thank you!

**Comment by SMillerDev** [comment]
Good to hear.

**Comment by ahc2483** [comment]
My issue was similar - somehow I had httpd22 installed, and linked, without
realizing it. After unlinking httpd22 and linking httpd, all was well.
