### ISSUE TITLE
oci8 driver

### ISSUE THREAD

**Issue by Garfield-fr** [Homebrew/homebrew-php#4725]
Hi,

It's possible to include the oci8 driver into this tap ?

Thank's

**Comment by SMillerDev** [comment]
You mean like doing `brew install php72 --with-pdo-oci` would?

**Comment by Garfield-fr** [comment]
@SMillerDev No, I use oci8 in my dev, not pdo-oci because this driver are limitation for Oracle.

http://pecl.php.net/package/oci8

**Comment by SMillerDev** [comment]
Well, you could send a pull request that adds this extension. However, due to the move of the php versions to homebrew/core and #4721 it probably won't be useful for very long. A better and more maintainable solution would be to install php `--with-pear` and use that to install the extension.
