### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated

### ISSUE THREAD

**Issue by phanphuc** [Homebrew/homebrew-php#4727]
https://github.com/Homebrew/homebrew-php/blob/386622683680f7887b934b9896c3670a0dc5c1bd/Abstract/abstract-php.rb#L620

`
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in 'plist'
`

I change `<<-EOPLIST.undent` to `<<~EOPLIST` it's work well

macOS version: 10.13.2
Homebrew version: 1.5.1-3-ge056e85
Ruby version: 2.3.0p0

**Comment by SMillerDev** [comment]
This seems very similar to the outstanding issue #4722
