### ISSUE TITLE
--with-gmp ignored ? How to build a --with-httpd --with-gmp version of php ?

### ISSUE THREAD

**Issue by jpsarda** [Homebrew/homebrew-php#4761]
## Description

When using the following command :
`brew install php72 --with-gmp`
The php sources are downloaded and compiled, but in the configure command I can see the `--without-gmp` option

```
brew reinstall php70 --with-httpd --with-gmp
==> Reinstalling homebrew/php/php70 --with-gmp --with-httpd
==> Downloading https://php.net/get/php-7.0.27.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/get/php-7.0.27.tar.bz2/from/this/mirror
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.27_19 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/etc/php/7.0 --with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d --mandir=/usr/local/Cellar/php70/7.0.27_19/share/man --enable-bcmath --enable-calendar --enable-dba --enable-exif --enable-ftp --enable-gd-native-ttf --enable-mbregex --enable-mbstring --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip --with-freetype-dir=/usr/local/opt/freetype --with-gd --with-gettext=/usr/local/opt/gettext --with-iconv-dir=/usr --with-icu-dir=/usr/local/opt/icu4c --with-jpeg-dir=/usr/local/opt/jpeg --with-kerberos=/usr --with-mhash --with-ndbm=/usr --with-png-dir=/usr/local/opt/libpng --with-xmlrpc --with-zlib=/usr --with-readline=/usr/local/opt/readline --without-gmp --without-snmp --with-libxml-dir=/usr/local/opt/libxml2 --with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc --with-unixODBC=/usr/local/opt/unixodbc --with-apxs2=/usr/local/bin/apxs --libexecdir=/usr/local/Cellar/php70/7.0.27_19/libexec --with-bz2=/usr --with-openssl=/usr/local/opt/openssl --enable-fpm --with-fpm-user=_www --with-fpm-group=_www --with-curl --with-xsl=/usr --with-ldap --with-ldap-sasl=/usr --with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --disable-opcache --enable-pcntl --without-pear --enable-d .......
```

II know there's a php70-gmp formula but `--with-httpd` is not an available option for this formula, so I can't get a httpd+gmp version of php right now.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**    |   10.13.1
**Homebrew version:**  |  Homebrew 1.5.3 Homebrew/homebrew-core (git revision dc6e7; last commit 2018-02-09)
**PHP version in use:**  | .  PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
**Xcode version:**   |   Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** https://gist.github.com/ac310e80900050ab3f3a6b9876a3c163

**Comment by SMillerDev** [comment]
The phpxx-gmp formula only installs the shared extension. It doesn't do the base install. So `brew install phpxx --with-httpd phpxx-gmp` would work for you (if I understand your question correctly of course)

**Comment by jpsarda** [comment]
Oh OK thx for the command.
