### ISSUE TITLE
Argon2i Hashing not available 

### ISSUE THREAD

**Issue by sgtpepper9907** [Homebrew/homebrew-php#4763]
## Description

I don't have access to Argon2i hashing and can't use `--with-password-argon2` to force the build with it 

When I try to use Argon2i I get 
`PHP Warning:  Use of undefined constant PASSWORD_ARGON2I`

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | 1.5.4
**PHP version in use:** | 7.2.2
**Xcode version:**      | Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP 7.2.2 (cli) (built: Feb  1 2018 11:50:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by javian** [comment]
The option in the php formula is called `--with-argon2` so you need to use that and nothing else to enable the functionality.

**Comment by sgtpepper9907** [comment]
Sorry, I saw the option referenced somewhere else 😅
