### ISSUE TITLE
Ruby error after compiling php72 

### ISSUE THREAD

**Issue by dib258** [Homebrew/homebrew-php#4768]
## Description

Installed php72 with the following command : 

`brew install --with-homebrew-curl --with-httpd php72`

I got this error : 

```
Error: no implicit conversion of String into Array
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:614:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:18:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:573:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:599:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:343:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

But it seems php compiled correctly since when I do `php -v` I get 7.2.2

I tried with php71 since It seems there's no php72-mcrypt but I get the same ruby error at the end

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**   |     10.13.1
**Homebrew version:** |   1.5.4
**PHP version in use:** | PHP 7.2.2
**Xcode version:**   |   Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**

PHP 7.2.2 (cli) (built: Feb 12 2018 13:47:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`

https://gist.github.com/dib258/6340d84c636e593933d1d44ef46d0568

**Comment by javian** [comment]
This has been fixed now #4769
