### ISSUE TITLE
Error while installing php56 --with-httpd

### ISSUE THREAD

**Issue by derweili** [Homebrew/homebrew-php#4781]
## Description
I tried to `brew install php56 --with-httpd` but I get following error:

```
…
> Zend/zend_dtrace_gen.h
error: error reading '/dev/fd/7'
1 error generated.
clang: error: unable to remove file: Operation not permitted
dtrace: failed to compile script /private/tmp/php56-20180222-11580-1tdvxzi/php-5.6.33/Zend/zend_dtrace.d: Preprocessor failed to process input program
make: *** [Zend/zend_dtrace_gen.h] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Installing php55 and php56 makes my mac terminal dead https://github.com/Homebrew/homebrew-php/issues/4602
php56-mongodb _clock_gettime error at runtime https://github.com/Homebrew/homebrew-php/issues/3737
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.12.6_
**Homebrew version:**   | _Homebrew 1.5.4 <br> Homebrew/homebrew-core (git revision 3bb3; last commit 2018-02-22)_
**PHP version in use:** | *currently:*<br>PHP 7.1.12 (cli) (built: Nov 27 2017 15:53:40) ( NTS )<br> Copyright (c) 1997-2017 The PHP Group <br> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies <br> installed within the `/usr/bin/php` direcory but I'm sill trying to install php56 with brew 
**Xcode version:**      | _Xcode 9.2 <br> Build version 9C40b_

**Output of `gcc -v`:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**
PHP 7.1.12 (cli) (built: Nov 27 2017 15:53:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by SMillerDev** [comment]
You installed all of php in /usr/bin/php? And how did you install the current php version?

**Comment by halfnibble** [comment]
I get an error on 10.13.3 with "Cannot find libz"

checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

**Comment by SMillerDev** [comment]
That means you need to reinstall the command line tools

**Comment by evanjwalsh** [comment]
I get the same error with `brew install php56 --with-httpd`.  Removing the `--with-httpd` option works fine.

```
/bin/sh /private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/libtool --silent --preserve-dup-deps --mode=compile clang  -Imain/ -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/main/ -DPHP_ATOM_INC -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/include -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/main -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33 -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/date/lib -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/ereg/regex -I/usr/local/Cellar/libxml2/2.9.7/include/libxml2 -I/usr/local/opt/openssl/include -I/usr/local/opt/jpeg/include -I/usr/local/opt/libpng/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gettext/include -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/mbstring/oniguruma -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/mbstring/libmbfl -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/mbstring/libmbfl/mbfl -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/sqlite3/libsqlite -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/ext/zip/lib -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/TSRM -I/private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/Zend  -no-cpp-precomp  -I/usr/include -g -O2 -fvisibility=hidden -DZEND_SIGNALS  -c /private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/main/fopen_wrappers.c -o main/fopen_wrappers.lo
error: error reading '/dev/fd/7'
1 error generated.
clang: error: unable to remove file: Permission denied
dtrace: failed to compile script /private/tmp/php56-20180306-86173-1622k7z/php-5.6.33/Zend/zend_dtrace.d: Preprocessor failed to process input program
make: *** [Zend/zend_dtrace_gen.h] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Error while installing php56 --with-httpd https://github.com/Homebrew/homebrew-php/issues/4781
php56-mongodb _clock_gettime error at runtime https://github.com/Homebrew/homebrew-php/issues/3737
```

Parameter | Value
-- | --
Mac OS version: | 10.13.3
Homebrew version: | Homebrew 1.5.8 Homebrew/homebrew-core (git revision bd379; last commit 2018-03-05)
PHP version (stock Apple): | PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS ) Copyright (c) 1997-2017 The PHP Group Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
Xcode version: | Xcode 9.2 version 9C40b
gcc version: | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 9.0.0 (clang-900.0.39.2) Target: x86_64-apple-darwin17.4.0 Thread model: posix InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Logs: https://gist.github.com/2490a601edc819e5761b57a801f58a18

**Comment by SMillerDev** [comment]
@evanjwalsh can you try reinstalling commandline tools?

**Comment by evanjwalsh** [comment]
Removed `/Library/Developer/CommandLineTools` and reinstalled via `xcode-select --install`.  Same error.

**Comment by halfnibble** [comment]
My ZLIB issue was fixed by reinstalling command line tools. The other two issues with permissions errors appear to be unrelated. Would `sudo brew` make a difference?

**Comment by evanjwalsh** [comment]
You can't run brew as root.  I tried disabling SIP as well.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
