### ISSUE TITLE
Migrate php7.0, 7.1, and 7.2 scripts to use phan 0.12.1

### ISSUE THREAD

**Issue by TysonAndre** [Homebrew/homebrew-php#4787]
## Description

https://github.com/Homebrew/homebrew-php/pull/4786 was automatically created, but needs more work.

https://github.com/phan/phan/releases/tag/0.12.0 is out. It is a new unified release that supports analyzing projects against PHP 7.0, 7.1, or 7.2. By default, Phan 0.12.0 will analyze the project as if the project was targeting the same PHP minor version as the binary used to run Phan. Config file options and CLI flags can be used by users to override this.

See https://github.com/phan/phan/blob/0.12.1/NEWS.md#25-feb-2018-phan-0120 and https://github.com/phan/phan/blob/0.12.1/NEWS.md#28-feb-2018-phan-0121

I can think of three options. I'm not familiar enough with homebrew-php's packaging process to know which of these are feasible:

1. Keep separate packages here, and continue to make them conflict, but make them point to Phan 0.12.0 (And update CI checks to expect the version of 0.12.0)

   Possibly change the names to php70-phan, php71-phan, and php72-phan.

   **After thinking about it, this seems to be the most practical; a future release of Phan (e.g. 1.0 or 2.0) would eventually drop support for php 7.0**

2. Write wrapper scripts of phan70/phan71/phan72 and make them invoke the script from the Phan download with the different php binaries (php70/71/72)
   (And make the default phan wrapper script get changed at the same time as the default php installation (And corresponding php-ast)

3. Make this depend on any of php70+php70-ast, php71+php71-ast, or php72+php72-ast, and have phan get invoked with the user's chosen `php` binary alternative.

   (Might run into issues if the user switches to a binary that doesn't have ast enabled)

---

I don't have a macbook to test changes on, so I won't be able to implement this myself.

**Comment by TysonAndre** [comment]
This issue seems like it will be blocked on migrating the php formula is completed

> Due to homebrew/php deprecation, homebrew-updater will not update formulas until migration complete.

https://brew.sh/analytics/install/ - The Phan formula looks like it's too infrequently installed via homebrew to show up in the top 1000. Not clear if #4721 was specifically referring to the top 1000 shown on that web page.

Also, Phan 0.12.3 is out.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
