### ISSUE TITLE
Inconsistency with latest changes regarding php and modules names

### ISSUE THREAD

**Issue by mynameisbogdan** [Homebrew/homebrew-php#4795]
Hello fellas,

I updated yesterday all my brew packages and saw that php72 migrated to simply php, but the modules are still using the php72 prefix. 

`brew install php php72-xdebug` is the intended behavior? 

Sorry but I didn't find anything regarding this migration except  #4783

Parameter | Value
--------- | ----------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | 1.5.5-16-g9225dac
**PHP version in use:** | PHP 7.2.2 (cli) (built: Feb 28 2018 08:40:33) ( NTS )

**Comment by awudarowicz** [comment]
Same here.
Somethings wrong with options now. When I'm trying to install php with few options
`brew reinstall php --with-httpd --with-pdo-mysql --with-pdo-pgsql`
then I get warnings:
```
Warning: php: this formula has no --with-httpd option so it will be ignored!
Warning: php: this formula has no --with-pdo-mysql option so it will be ignored!
Warning: php: this formula has no --with-pdo-pgsql option so it will be ignored!
```

Also when I'm trying to check options with homebrew
`brew options php`
There are no options.

**Comment by javian** [comment]
So far yes @mynameisbogdan - the extensions that are still in the tap should place the extension config file in the right directory and it should work. We are currently discussing on which extensions should be included and which we would need to let go. In the new formula you should also be able to use pecl to install the extensions

@awudarowicz as for your question the options that you've mentioned are now built by default and should be included in the default build and included in the bottles downloaded from the homebrew repository.

**Comment by mynameisbogdan** [comment]
@javian well by getting by example the remi repo for centos, `php` always would be the latest version, but where are also php56, php70, php71, php72, etc variants too if you like to use a specific version at all time.

Let go extesions? That's a bummer, I guess I'll have to look into Docker in the near future. 

Also, the subdeps of now mandatory dep  `httpd` are quite large together, in particular `boost`:
```
/usr/local/Cellar/httpd/2.4.29_1 (1,625 files, 26MB) *
/usr/local/Cellar/apr/1.6.3 (60 files, 1.3MB)
/usr/local/Cellar/apr-util/1.6.1_1 (54 files, 778.2KB)
/usr/local/Cellar/boost/1.66.0 (13,101 files, 435.2MB) *
/usr/local/Cellar/c-ares/1.14.0 (70 files, 463.5KB) *
/usr/local/Cellar/jansson/2.10 (11 files, 145.5KB) *
/usr/local/Cellar/jemalloc/5.0.1 (16 files, 1.6MB) *
/usr/local/Cellar/libev/4.24 (12 files, 432.8KB) *
/usr/local/Cellar/libevent/2.1.8 (847 files, 2.2MB) *
/usr/local/Cellar/nghttp2/1.31.0 (33 files, 6.3MB) *
/usr/local/Cellar/openssl/1.0.2n (1,792 files, 12.3MB)
/usr/local/Cellar/pcre/8.41 (204 files, 5.3MB) *
```

Thank your for your response.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
