### ISSUE TITLE
PHP 7.2 CLI unusably slow due to included IMAP extension

### ISSUE THREAD

**Issue by mundschenk-at** [Homebrew/homebrew-php#4799]
# Description

Since moving from `php72` to `php`, the CLI version is unusably slow due to a timeout (probably) caused by the included IMAP extension. Google points to missing `/etc/hosts` entries for `localhost`, but that is not the case here (both `127.0.0.1` and `::1` being included already). Since the extension is included in the default build, there is no way to disable it via `php.ini`.

```bash
$ time php -n -v
PHP 7.2.3 (cli) (built: Mar  2 2018 15:48:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

real	0m5.069s
user	0m0.023s
sys	0m0.014s
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | Homebrew 1.5.8-2-g8d6aa70
**PHP version in use:** | PHP 7.2.3 (cli) (built: Mar  2 2018 15:48:10) ( NTS )
**Xcode version:**      | Xcode 9.2, Build version 9C40b

**Comment by kabel** [comment]
It's your hostname that is the missing enrty in your host file. The .local address from system preferences can be added to see if it helps.

**Comment by mundschenk-at** [comment]
The hostname is already included, with and without `.local`.

**Comment by josegonzalez** [comment]
Can you show the output of

```shell
cat /etc/hosts
```

**Comment by mundschenk-at** [comment]
@josegonzalez I just re-looked at the `/etc/hosts` and tried self-pinging once more before posting the contents, when I noticed that in my current network environment (not at home), the router apparently sets the default domain to `.home` instead of the usual `.local`. Adding entries for my hostname with the `.home` suffix fixed the issue. 

The weird thing is, I remember having tried to force the `search domain` to `local` yesterday in the network settings and it didn't seem to make a difference.

**Comment by wesdollar** [comment]
I'm experiencing similar behavior.

`PHP 7.2.3 (cli) (built: Mar  2 2018 15:48:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
        5.04 real         0.02 user         0.01 sys`

I have included the following in my /etc/hosts file:

`::1             localhost dollar.local
127.0.0.1	localhost dollar.local 
fe80::1%lo0	localhost dollar.local`

What am I missing or doing wrong?

Thanks!

**Comment by mundschenk-at** [comment]
Well, the gist is that the extension is quite finicky (or rather: networking stuff is) and having it always enabled is going to break things for a lot of people.

**Comment by wtorsi** [comment]
Please add this notes to after install help.

**Comment by cixtor** [comment]
This bug report needs more attention; please add a note during installation.

---

As suggested by others, I've added the following entries into my `/etc/hosts` file and problem solved.

```
HOSTNAME=$(hostname); \
echo -e "127.0.0.1    ${HOSTNAME}" | tee -a hosts.txt; \
echo -e "::1          ${HOSTNAME}" | tee -a hosts.txt
```

**Comment by josegonzalez** [comment]
@cixtor would you be interested in making a pull request to add a note about how folks might have invalid hostname configuration?

**Comment by cixtor** [comment]
Here is a pull-request to add the note — https://github.com/Homebrew/homebrew-core/pull/25559

**Comment by josegonzalez** [comment]
Great! Closing this issue as there is a pull request up.
