### ISSUE TITLE
php72-zmq missing

### ISSUE THREAD

**Issue by nesl247** [Homebrew/homebrew-php#4803]
## Description

The formula for php72-zmq is missing.

**Comment by SMillerDev** [comment]
This can be installed using pear/pecl (which is now part of the php formula)

**Comment by nesl247** [comment]
Does that mean the formula for it is considered deprecated? I ask because there is one for 7.1 and other versions I believe.

**Comment by SMillerDev** [comment]
It's not really deprecated. Just nobody ever made it. But with the php formula moving out of the php tap I'd recommend using pecl or pear to install these things.
  
  

  
  
>

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
