### ISSUE TITLE
Please add "--without-httpd" to php72 

### ISSUE THREAD

**Issue by rverrips** [Homebrew/homebrew-php#4804]
## Description

Although I can admit that 95% or more of the case you would want apache/httpd with php and the requires "httpd" makes perfect sense, for those of us who prefer Nginx or no web server at all, there is not a way to specify this during install with something like --without-httpd 

## Snippets from current php.rb

From /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/php.rb

Line 22:   depends_on "httpd"

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | 1.5.8-16-g1ca2ee6
**PHP version in use:** | php 7.2.3
**Xcode version:**      | Xcode 9.2. Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.2.3 (cli) (built: Mar  2 2018 15:48:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies

**Build logs:** 
https://gist.github.com/99305a0cd3599064a6175b3db605cc46

**Comment by SMillerDev** [comment]
You're in luck. Future versions won't pull in httpd again thanks to https://github.com/Homebrew/homebrew-core/pull/24907

**Comment by rverrips** [comment]
***Awesome !*** I just updated brew and it's already showing this change - Thanks SO much!
