### ISSUE TITLE
php72-intl not in core

### ISSUE THREAD

**Issue by billythekid** [Homebrew/homebrew-php#4806]
## Description

looks like this was supposed to be [moved to core](http://formulae.brew.sh/formula/php72-intl) but somehow got missed? no intl functions are available, eg. [idn_to_ascii()](https://secure.php.net/manual/en/function.idn-to-ascii.php)

can't install with `brew install php72-intl` as package missing

**Comment by javian** [comment]
It is there, you just don't have to install a separate Formula anymore.

**Comment by javian** [comment]
```
➜  homebrew-core git:(master) php -m | grep intl
intl
➜  homebrew-core git:(master)
```

**Comment by jimblue** [comment]
Same problem, `brew install php72-intl` return an error.
Also `php72-opcache` can't be found.

It brokes my php setup:

```bash
php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-intl/intl.so' (tried: /usr/local/opt/php72-intl/intl.so (dlopen(/usr/local/opt/php72-intl/intl.so, 9): image not found), /usr/local/Cellar/php/7.2.3_2/lib/php/20170718//usr/local/opt/php72-intl/intl.so.so (dlopen(/usr/local/Cellar/php/7.2.3_2/lib/php/20170718//usr/local/opt/php72-intl/intl.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-intl/intl.so' (tried: /usr/local/opt/php72-intl/intl.so (dlopen(/usr/local/opt/php72-intl/intl.so, 9): image not found), /usr/local/Cellar/php/7.2.3_2/lib/php/20170718//usr/local/opt/php72-intl/intl.so.so (dlopen(/usr/local/Cellar/php/7.2.3_2/lib/php/20170718//usr/local/opt/php72-intl/intl.so.so, 9): image not found)) in Unknown on line 0
PHP 7.2.3 (cli) (built: Mar  8 2018 10:30:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

**Comment by javian** [comment]
@jimblue yes - that's because those modules are no longer available and can't be installed like they were before. You are seeing the errors because you have config files that tries to load the extensions. Check in your `/usr/local/etc/php/7.2/conf.d/` directory and take out the intl and opcache files there.

Also if you check `php -m` you will see that the modules are loaded even if you see the warnings at startup.

**Comment by jimblue** [comment]
ok thanks @javian, I'll look to what you said a bit later.
But what if I need to make a fresh install on an other computer, how can I install `php72-intl` and `php72-opcache`

**Comment by javian** [comment]
@jimblue you don't have to, `brew install php` includes intl and opcache by default.

**Comment by jimblue** [comment]
oh okay good to know, gonna work on this! thanks for the precision @javian.

Cheers

**Comment by OskarStark** [comment]
shouldn't then an upgrade, remove the extra installed extensions?

**Comment by javian** [comment]
@OskarStark we decided not to mess with peoples setup rather than potentially causing havoc. The fix is easy enough, delete the config files and it should be ok.

**Comment by jimblue** [comment]
Thanks @javian!
Checking in `/usr/local/etc/php/7.2/conf.d/` directory and take out the `intl` and `opcache` files fixed my problem.
