### ISSUE TITLE
Phalcon version needs upgrading from 3.3.0

### ISSUE THREAD

**Issue by fendorio** [Homebrew/homebrew-php#4809]
## Description

There is a rather *large bug in Phalcon 3.3.0, which is the latest version of Phalcon which homebrew has in it's repository, in which the default Volt filter throws a runtime error, this is of course quite savage for people working on Phalcon projects made with 2.X, who are running Phalcon/PHP through homebrew.   

[See the Github issue here](https://github.com/phalcon/cphalcon/issues/13244)
 
The fix is to upgrade Phalcon to any version above 3.3.0.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | 1.5.10
**PHP version in use:** | 7.0.27
**Xcode version:**      |  9.2

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.0.27 (cli) (built: Jan  5 2018 12:24:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
