### ISSUE TITLE
Installing php56 and php72 with --with-pdo-oci

### ISSUE THREAD

**Issue by bignall** [Homebrew/homebrew-php#4811]
### PHP 5.6
I tried to `brew install php56 --with-httpd --with-pdo-oci`  with $ORACLE_HOME set to "/usr/local/instantclient/instantclient_12_2" but I get the message 

`Error: Environmental variable ORACLE_HOME must be set to use --with-pdo-oci option.`

I also set $ORACLE_HOME in my .bash_profile in case it uses a new environment but that didn't help. How can I get it to be able to build with pdo-oci?

### PHP 7.2
I also tried to `brew install php72 --with-httpd --with-pdo-oci` and ran into the  issue with no options though I built it last week apparently before the update with --with-httpd and it worked fine.  Is pdo-oci also built by default?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.3.3
**Homebrew version:**   | 1.5.10
**PHP version in use:** |5.6 & 7.2
**Oracle instant client:**|12.2

**Comment by SMillerDev** [comment]
Are you sure you have ORACLE_HOME set so that brew can access it? As an environment variable? What happens when you do `echo $ORACLE_HOME`?

As for php@7.2 httpd is indeed included by default but pdo-oci is not. You can still install it through pecl/pear though which is included now.

**Comment by bignall** [comment]
Thanks for the reply. Here's what I get from echo $ORACLE_HOME

````
$ echo $ORACLE_HOME

/usr/local/instantclient/instantclient_12_2
````

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
