### ISSUE TITLE
run `brew options php` nothing display!

### ISSUE THREAD

**Issue by erigo** [Homebrew/homebrew-php#4812]
## Description

run `brew options php` nothing display.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | Homebrew 1.5.10-14-gc8533db Homebrew/homebrew-core (git revision e7c2; last commit 2018-03-14)
**PHP version in use:** | not installed
**Xcode version:**      | not installed

**Comment by erigo** [comment]
In my env, `brew options php53` and other phpXX is ok.

**Comment by javian** [comment]
There are no options for `php` anymore.
