### ISSUE TITLE
Question: mcrypt for php 7.2

### ISSUE THREAD

**Issue by sairoko12** [Homebrew/homebrew-php#4813]
How to install mcrypt extension wiht php 7.2 on mac os sierra, any idea?

**Comment by SMillerDev** [comment]
You don't. Mcrypt isn't supported for php 7.2 for security reasons mostly. https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by josegonzalez** [comment]
Closing as the current method for installing mcrypt in 7.2 should be via PECL, and developers using _any_ version of PHP are highly recommended to move off to other solutions.

**Comment by sairoko12** [comment]
Thanks a lot for your answers!

Greetings,
