### ISSUE TITLE
No PHP imap support anymore?

### ISSUE THREAD

**Issue by it-can** [Homebrew/homebrew-php#4817]
I have php7.2 on my mac, normally I could install it (or reinstall it) with --with-imap. But this recently stopped working. Is there a way to get this working again?

Parameter | Value
--------- | ------------------
**macOS version:**       |10.13.3
**Homebrew version:**   |1.5.12
**PHP version in use:** |7.2.3
**Xcode version:**      |9.2

```
brew reinstall php --with-imap
==> Reinstalling php
Warning: php: this formula has no --with-imap option so it will be ignored!
```

**Comment by SMillerDev** [comment]
The new formula don't have options but instead have all extensions embedded. Imap was giving issues however so you now have to install that through pecl.

**Comment by it-can** [comment]
And how do I do that?

**Comment by SMillerDev** [comment]
You're right. Just looked at it again, I thought it was. Then that only leaves you the option of maintaining a custom tap with a php formula that does install imap as an extension I suppose.
Or if you have an idea for a solution to the CLI slowdown some people were having with the IMAP extension, make a PR to Homebrew-core.

**Comment by it-can** [comment]
I never experienced the slowdown, but read that the hosts file could be a problem

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
