### ISSUE TITLE
php71-imagick has warnings

### ISSUE THREAD

**Issue by whoacowboy** [Homebrew/homebrew-php#4818]
@SMillerDev 

You marked this issue https://github.com/Homebrew/homebrew-php/issues/2766 as closed with the solution being.

https://github.com/Homebrew/homebrew-php/issues/2766#issuecomment-309829618

```
brew reinstall -s php71-imagick
```

After doing this I still receive the following error. 

```
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 
but version 2103042 is loaded. Imagick will run but may behave surprisingly in 
Unknown on line 0
```
Any ideas?

**Comment by SMillerDev** [comment]
Where do you receive that error?

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
