### ISSUE TITLE
7.2 redis & php-fpm

### ISSUE THREAD

**Issue by danijelk** [Homebrew/homebrew-php#4819]
Hi,
I've installed redis which seems to work in cli mode but not in fpm mode. I'm using valet to start php-fpm https://laravel.com/docs/5.6/valet

php -i | grep redis -A 3                                                                                                                                                     

> release/staging :: 1h :: ⬡
> /usr/local/etc/php/7.2/conf.d/ext-redis.ini,
> /usr/local/etc/php/7.2/conf.d/ext-xdebug.ini,
> /usr/local/etc/php/7.2/conf.d/php-memory-limits.ini
> 
> --
> redis
> 
> Redis Support => enabled
> Redis Version => 3.1.4
> 

--------

PHPINFO()

> Loaded Configuration File | /usr/local/etc/php/7.2/php.ini
> -- | --
> Scan this dir for additional .ini files | /usr/local/etc/php/7.2/conf.d
> Additional .ini files parsed | /usr/local/etc/php/7.2/conf.d/ext-imagick.ini, /usr/local/etc/php/7.2/conf.d/ext-intl.ini, /usr/local/etc/php/7.2/conf.d/ext-opcache.ini, /usr/local/etc/php/7.2/conf.d/ext-xdebug.ini, /usr/local/etc/php/7.2/conf.d/php-memory-limits.ini
> 

But if I add the extension="/usr/local/opt/php72-redis/redis.so" in php.ini it fails to load as it cannot load it twice, so it is trying to load it.. I can't see anything in system.log, any pointers on what to look for next?

**Comment by javian** [comment]
How did you install redis ?

**Comment by josegonzalez** [comment]
Is it starting the correct php-fpm? You may have two different versions of php installed.

**Comment by danijelk** [comment]
Hey guys, thanks for replies.

install: brew install php72-redis
brew search redis                                                                                                                                       

> release/staging :: 4h :: ⬡
> ==> Searching local taps...
> homebrew/php/php72-redis ✔


It is starting correct PHP bin (as phpinfo is showing what ini file it's loading)
0.0  0.2  4490836  40232   ??  S    Thu12PM   0:02.35 /usr/local/opt/php72/sbin/php-fpm --nodaemonize --fpm-config /usr/local/etc/php/7.2/php-fpm.conf
Also as mentioned, if I try to add it to php.ini it fails to start


extension="/usr/local/opt/php72-redis/redis.so"
File /usr/local/etc/php/7.2/php.ini saved
valet restart                                                                                                                                       6s  release/staging :: 4h :: ⬡

Warning: Module 'redis' already loaded in Unknown on line 0
Could not open input file:
Warning: Module 'redis' already loaded in Unknown on line 0

Parse error: syntax error, unexpected 'redis' (T_STRING), expecting ',' or ')' in Command line code on line 2/cli/valet.php

so it's the correct PHP and ini beeing loaded.
