### ISSUE TITLE
Warning: Use php instead of deprecated homebrew/php/php72

### ISSUE THREAD

**Issue by jimblue** [Homebrew/homebrew-php#4825]
## Description

Just upgrade to brew php to `7.2.3_4`.

Now when I run brew doctor I get this message:

`Warning: Use php instead of deprecated homebrew/php/php72`

Wondering if something is broken?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _macOS 10.13.3_
**Homebrew version:**   | _Homebrew 1.5.13 Homebrew/homebrew-core (git revision 30b3; last commit 2018-03-29)_
**PHP version in use:** | _PHP 7.2.3 (cli) (built: Mar 29 2018 04:40:07) ( NTS )_
**Xcode version:**      | _xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance_

**Output of `gcc -v`:**
_Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin_

**Output of `php -v`:**
_PHP 7.2.3 (cli) (built: Mar 29 2018 04:40:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans_

**Comment by javian** [comment]
Hi, can you provide your `brew doctor --debug` output ?

**Comment by MikeMcQuaid** [comment]
@jimblue Can we get your `brew doctor --debug`, `brew deps --installed` and `brew readall --debug` output? Thanks!

**Comment by jimblue** [comment]
Here we go: [brew logs link](https://gist.github.com/jimblue/a361a763ee2b537a516077a7bdf0a3fb)

**Comment by aivus** [comment]
Got same, but for php71
`Warning: Use php@7.1 instead of deprecated homebrew/php/php71`

fixed by `brew untap homebrew/php`

**Comment by inoas** [comment]
@aivus that fixed it for me.
I am using `brew install php` now followed by a `brew install php72-apcu` cause for me it was missing.

**Comment by AJCrowley** [comment]
That also fixed it for me. Thanks!

**Comment by jimblue** [comment]
Yep `brew untap homebrew/php` fixed it! thanks @aivus !
