### ISSUE TITLE
Formulas missing: php71-opcache, php71-intl, php71-mcrypt

### ISSUE THREAD

**Issue by holtkamp** [Homebrew/homebrew-php#4826]
## Description
When trying to install some extensions using formulas, these formulas are not found:

- php71-opcache
- php71-intl
- php71-mcrypt

It seems they are missing from the list

```
➜  ~ brew tap
blackfireio/blackfire
caskroom/cask
caskroom/versions
heroku/brew
homebrew/apache
homebrew/core
homebrew/dupes
homebrew/php
homebrew/science
homebrew/services
homebrew/versions

➜  ~ brew search php71                                     
==> Searching local taps...
blackfireio/blackfire/blackfire-php71 ✔        homebrew/php/php71-ioncubeloader               homebrew/php/php71-ref
blackfireio/blackfire/blackfire-php71-zts ✔    homebrew/php/php71-libsodium@1.0               homebrew/php/php71-sodium
homebrew/php/php71-amqp                        homebrew/php/php71-lua                         homebrew/php/php71-solr
homebrew/php/php71-apcu                        homebrew/php/php71-lz4                         homebrew/php/php71-ssh2
homebrew/php/php71-apcu-bc                     homebrew/php/php71-lzf                         homebrew/php/php71-stats
homebrew/php/php71-ast                         homebrew/php/php71-mailparse                   homebrew/php/php71-swoole
homebrew/php/php71-blitz                       homebrew/php/php71-maxminddb                   homebrew/php/php71-timecop
homebrew/php/php71-couchbase                   homebrew/php/php71-mecab                       homebrew/php/php71-timezonedb
homebrew/php/php71-ds                          homebrew/php/php71-memcached                   homebrew/php/php71-trader
homebrew/php/php71-ev                          homebrew/php/php71-meminfo                     homebrew/php/php71-translit
homebrew/php/php71-event                       homebrew/php/php71-molten                      homebrew/php/php71-uopz
homebrew/php/php71-gearman                     homebrew/php/php71-mongodb                     homebrew/php/php71-uuid
homebrew/php/php71-geoip                       homebrew/php/php71-mosquitto                   homebrew/php/php71-uv
homebrew/php/php71-geos                        homebrew/php/php71-msgpack                     homebrew/php/php71-v8js
homebrew/php/php71-gmagick                     homebrew/php/php71-mustache                    homebrew/php/php71-xdebug
homebrew/php/php71-gnupg                       homebrew/php/php71-oauth                       homebrew/php/php71-xdiff
homebrew/php/php71-grpc                        homebrew/php/php71-phalcon                     homebrew/php/php71-xmldiff
homebrew/php/php71-hprose                      homebrew/php/php71-propro                      homebrew/php/php71-xxtea
homebrew/php/php71-http                        homebrew/php/php71-protobuf                    homebrew/php/php71-yac
homebrew/php/php71-ice                         homebrew/php/php71-raphf                       homebrew/php/php71-yaf
homebrew/php/php71-igbinary                    homebrew/php/php71-rdkafka                     homebrew/php/php71-yaml
homebrew/php/php71-imagick                     homebrew/php/php71-redis                       homebrew/php/php71-zmq
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...

If you meant "php71" specifically:
It was migrated from homebrew/php to homebrew/core.
```  

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |10.13.3
**Homebrew version:**   |Homebrew 1.5.13-6-g6654ff6 / Homebrew/homebrew-core (git revision 727f38; last commit 2018-03-29)
**PHP version in use:** | 7.1.15
**Xcode version:**      |Xcode 9.2 / Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.15 (cli) (built: Mar 29 2018 09:21:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.15, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.18.2~mac-x64-non_zts71, https://blackfire.io, by SensioLabs

**Comment by holtkamp** [comment]
Ah, it seems they are being migrated to `homebrew/core` as of https://github.com/Homebrew/homebrew-php/commit/ab5fffa7cf3b7dca77f2ffa6f6104fc09fd72221

So I guess some patience will resolve this, any idea how long it takes before the `homebrew/core` gets updated?

**Comment by SMillerDev** [comment]
just brew upgrade should already update homebrew/core

**Comment by vyuldashev** [comment]
intl, xdebug and other php packages are not available...

**Comment by aivus** [comment]
@vyuldashev they are pre-compiled now in binaries.

**Comment by vyuldashev** [comment]
@aivus How are they installed now?

**Comment by SMillerDev** [comment]
@vyuldashev they are now part of the PHP binary.

**Comment by SMillerDev** [comment]
well, intl is. Xdebug can be installed through pecl.

**Comment by aivus** [comment]
> Xdebug can be installed through pecl.

xdebug still persist in homebrew: `homebrew/php/php71-xdebug`

**Comment by vyuldashev** [comment]
Okay. How do I install Lua then? It was available through php71-lua.

**Comment by SMillerDev** [comment]
> Okay. How do I install Lua then? It was available through php71-lua.

https://pecl.php.net/package/lua

**Comment by holtkamp** [comment]
aah, ok, this one got them included indeed:

`brew install php@71 `

Thanks!

**Comment by jrgd** [comment]
when i `brew install php@7.1` and then `php -v`, I get:

```
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): image not found
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php71-mcrypt/mcrypt.so, 9): image not found in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php71-mcrypt/mcrypt.so, 9): image not found in Unknown on line 0
```

Not sure where to take it from there…

**Comment by aivus** [comment]
@jrgd look at https://github.com/Homebrew/homebrew-php/issues/4827#issuecomment-377218383
xdebug should be installed with pecl

**Comment by jrgd** [comment]
Thanks @aivus but it's complaining about php71-xdebug and php71-mcrypt which shouldn't be around anymore with php@7.1 from what I understand.

I'm unsure how to remove those 2 autoloaders and where from.

**Comment by zachattack** [comment]
@aivus thank you for that tip on commenting out the lines to silence those warnings.

**Comment by jsgv** [comment]
I need to install some additional formulas along with `php71`. 
`php71-pdo-pgsql` and `php71-imagick`

Any idea when the formula will be available?

**Comment by aivus** [comment]
@jsgv they will not be available soon as separate modules.

`php71-pdo-pgsql` is already pre-compiled and you don't need this external module now.
`php71-imagick` still can be installed from this tap:
```
➜  ~ brew search php71-imagick
==> Searching local taps...
homebrew/php/php71-imagick
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...
➜  ~ 
```
