### ISSUE TITLE
Cannot rebuild `php70-intl`

### ISSUE THREAD

**Issue by msbit** [Homebrew/homebrew-php#4828]
## Description

Attempting to rebuild `php70-intl` (to link against updated `icu4c`) fails with a compilation error.

## Context and Logs

**macOS version:**
```
10.13.3
```
**Homebrew version:** 
```
Homebrew 1.5.13-6-g6654ff6
Homebrew/homebrew-core (git revision 5b9ed8; last commit 2018-03-29)
```
**PHP version in use:**
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 7.0.27 (cli) (built: Jan  5 2018 12:26:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```
**Xcode version:** 
```
Xcode 9.2
Build version 9C40b
```

**Output of `gcc -v`:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Build logs:** https://gist.github.com/a5c96462e5fb56b4ba17ac7165b71399

**Comment by mszterlingmage** [comment]
Same here

`brew reinstall --build-from-source php70-intl
==> Reinstalling homebrew/php/php70-intl
==> Downloading https://php.net/get/php-7.0.27.tar.bz2/from/this/mirror
Already downloaded: /Users/mszterling/Library/Caches/Homebrew/php70-intl-7.0.27.tar.bz2
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-intl/7.0.27_24 --with-php-config=/usr/local/opt/php70/bin/php-config --enable-intl --with-icu-dir=/usr/local/opt/icu4c
==> make
Last 15 lines from /Users/mszterling/Library/Logs/Homebrew/php70-intl/03.make:
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/collator/collator_create.c  -fno-common -DPIC -o collator/.libs/collator_create.o
/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/intl_convertcpp.cpp:59:40: error: unknown type name 'UnicodeString'; did you mean 'icu_61::UnicodeString'?
zend_string* intl_charFromString(const UnicodeString &from, UErrorCode *status)
                                       ^~~~~~~~~~~~~
                                       icu_61::UnicodeString
/usr/local/Cellar/icu4c/61.1/include/unicode/unistr.h:286:20: note: 'icu_61::UnicodeString' declared here
class U_COMMON_API UnicodeString : public Replaceable
                   ^
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/collator/collator_is_numeric.c  -fno-common -DPIC -o collator/.libs/collator_is_numeric.o
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/collator/collator_error.c  -fno-common -DPIC -o collator/.libs/collator_error.o
4 errors generated.
make: *** [intl_convertcpp.lo] Error 1
make: *** Waiting for unfinished jobs....
mkdir common/.libs
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180329-64321-1gt4g28/php-7.0.27/ext/intl/common/common_error.c  -fno-common -DPIC -o c`

**Comment by msbit** [comment]
Looking into it a bit more, it's likely due to:

http://site.icu-project.org/download/61#TOC-Migration-Issues

as reported in:

https://bugs.php.net/bug.php?id=76153

so this will likely end up being an upstream PHP bug, and resolved there.

**Comment by allrude** [comment]
same problem here,  tried over an hour to get my valet working any idea's :-(

**Comment by SMillerDev** [comment]
yeah, it's a bug in PHP that was sorta patched only yesterday. 

You can edit the formula to add a workaround until PHP comes up with a real solution:

```ruby
# icu4c 61.1 compatability
ENV.append "CPPFLAGS", "-DU_USING_ICU_NAMESPACE=1"
```

**Comment by mszterlingmage** [comment]
@SMillerDev - can you help - how to edit the formula?

**Comment by SMillerDev** [comment]
`brew edit <formula>`

**Comment by SMillerDev** [comment]
Since this tap is going into archive mode soon, the solution is provide, and there are no shared extensions in the php formulae in core, I'm going to close this.

**Comment by msbit** [comment]
@SMillerDev ah so close.

On the topic of `homebrew/core` what's happening with the extensions? Are they all going to be compiled into PHP proper?

**Comment by SMillerDev** [comment]
For the current formula in core the extensions that are actually working are compiled in.

**Comment by msbit** [comment]
@SMillerDev cool! Is there a list handy of the ones that make the cut?

**Comment by SMillerDev** [comment]
> Is there a list handy of the ones that make the cut?

`php -m`
