### ISSUE TITLE
Unable to install php71 formulae

### ISSUE THREAD

**Issue by shiftedreality** [Homebrew/homebrew-php#4830]
## Description
Possibly caused by https://github.com/Homebrew/homebrew-php/pull/4798
Update brew recently, and now running
```
brew reinstall --build-from-source php71-mcrypt
```
throws error
```
Error: No available formula with the name "php71-mcrypt"
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13.3_
**Homebrew version:**   | _Homebrew/homebrew-core (git revision 3c1e07; last commit 2018-03-29)`)_
**PHP version in use:** | _PHP 7.1.15 (cli) (built: Mar 29 2018 09:21:29) ( NTS )_
**Xcode version:**      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
_Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin_

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by danemacmillan** [comment]
I resolved this by untapping `homebrew/php` and installing from `homebrew/core`. Go this route if you do not depend on `7.0.x`.

**Comment by Saeven** [comment]
intl is built in now it seems, as are many others.  run php -i before you check for a missing brew package.

**Comment by SMillerDev** [comment]
Yes, the core extensions are now part of the formula. Any other extensions should be installed through PECL.
