### ISSUE TITLE
Unable to install php70-intl.so

### ISSUE THREAD

**Issue by Januszpl** [Homebrew/homebrew-php#4831]
## Description

Suddenly I've got problem with loading and reinstalling php70-intl.so
`brew reinstall -s php70-intl
==> Reinstalling homebrew/php/php70-intl
==> Downloading https://php.net/get/php-7.0.27.tar.bz2/from/this/mirror
Already downloaded: /Users/DL/Library/Caches/Homebrew/php70-intl-7.0.27.tar.bz2
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-intl/7.0.27_24 --with-php-confi
==> make
Last 15 lines from /Users/DL/Library/Logs/Homebrew/php70-intl/03.make:
mkdir common/.libs
/private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl/intl_convertcpp.cpp:28:25: error: unknown type name 'UnicodeString'
int intl_stringFromChar(UnicodeString &ret, char *str, size_t str_len, UErrorCode *status)
                        ^
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl/common/common_error.c  -fno-common -DPIC -o common/.libs/common_error.o
/private/tmp/php70-intl-20180329-4790-umka7s/php-7.0.27/ext/intl/intl_convertcpp.cpp:59:40: error: unknown type name 'UnicodeString'; did you mean 'icu_61::UnicodeString'?
zend_string* intl_charFromString(const UnicodeString &from, UErrorCode *status)
                                       ^~~~~~~~~~~~~
                                       icu_61::UnicodeString
/usr/local/Cellar/icu4c/61.1/include/unicode/unistr.h:286:20: note: 'icu_61::UnicodeString' declared here
class U_COMMON_API UnicodeString : public Replaceable
                   ^
4 errors generated.
make: *** [intl_convertcpp.lo] Error 1
make: *** Waiting for unfinished jobs....`

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP Parse error:  syntax error, unexpected '' - dlopen(/usr/local/opt/php7' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in Command line code on line 5
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
Could not open input file:
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Parse error: syntax error, unexpected '' - dlopen(/usr/local/opt/php7' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in Command line code on line 5/cli/valet.php`

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**      | 10.13.13
**Homebrew version:**  | Homebrew 1.5.13-10-g40e7ac2
**PHP version in use:** | 7.0.27 
**Xcode version:**      | 9.2

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 7.0.27 (cli) (built: Jan  5 2018 12:26:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27, Copyright (c) 1999-2017, by Zend Technologies`

**Build logs:** https://gist.github.com/Januszpl/4b7948195016cec03c831f9b739473d0

**Comment by gfritzdev** [comment]
I am having the exact same problem right now.  I believe it happened after a brew update && brew upgrade.

**Comment by Kyslik** [comment]
Yea, they are doing some black magic with this tap, I am personally still on 10.10.5, so I can not complain.

I made it work (for php71-intl, but its same for **php70-intl**) using https://github.com/Kyslik/homebrew-php/commit/7a6aaf9b480a3b23abaa317151b4634e5a6d5fad (`brew edit phpxx-intl`) taken from [migrated php formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb#L69-L70).

> **Note**: I also had to checkout core tap before migration so I checked out [9c38a2df59c5191e3d72a30455f11028ab3117bc](https://github.com/Homebrew/homebrew-core/commit/a0b705d836195c4116721e568fcb5a33835bcb5f), I think thats because of me being on 10.10.5 and the magic with `@` (php@71) does not work or something, no time for real debugging).

But now I have to maintain my own fork of this repository, which I will not I just pinned the tap.

**Comment by remklov** [comment]
@Kyslik You Sir, saved my day! 

After adding the `ENV.append "CPPFLAGS", "-DU_USING_ICU_NAMESPACE=1"` to my php70-intl and reinstalling it, everything works again.

**Comment by Kyslik** [comment]
I also updated formulas for
- 55 (not tested) 
- 56 (not tested), 
- 70 (not tested)
- 72 has intl compiled in

```shell
brew tap kyslik/homebrew-php
```

>**Note**: I am not going to maintain the fork. So find another solution ASAP.

**Comment by EirikSl** [comment]
Have got same Error. @remklov or @Kyslik could you please write more detailed instruction how to fix that?

**Comment by Kyslik** [comment]
I am newbie in brew (formula aspect), following should do it

```shell
brew tap kyslik/homebrew-php
brew install kyslik/php/php71-intl
```

**Comment by Januszpl** [comment]
Thanks Kyslik for tmp fix ;)

**Comment by EirikSl** [comment]
Thanks a lot! Kyslik
