### ISSUE TITLE
Updating PHP 7.1 Downgrades to PHP 7.1.7

### ISSUE THREAD

**Issue by epreston** [Homebrew/homebrew-php#4832]
## Description

Hello, the updated php an noticed my php has been downgraded by a number of point releases.

I just ran a `brew update` on my Mac, saw the package rename from `php71` to `php@7.1`.  After doing the `brew upgrade` it downgraded my php 7.1.14(or 15) to 7.1.7.    Did someone build the new package with an old version ?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | Homebrew 1.5.13
**PHP version in use:** |  PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
**Xcode version:**      | Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** 
None apply.

**Comment by epreston** [comment]
Ok I see, it's unlinked php and I'm back to the system default php.

What was the meaningful upgrade path for people using php 7.1 (and php71-igbinary, php71-imagick, php71-libsodium@1.0, php71-lzf, php71-mongodb, php71-redis, php71-uopz, php71-uuid, php71-xdebug, php71-yaml) ?

**Comment by danielrose28** [comment]
I saw this today. Did you happen to get yours linked? I see this now `Warning: Use php@7.1 instead of deprecated homebrew/php/php71`. Maybe I missed something. Thanks for the help.

**Comment by SMillerDev** [comment]
@danielrose28 that's answered here: https://github.com/Homebrew/homebrew-php/issues/4825

**Comment by SMillerDev** [comment]
@epreston the core extensions in that list are now part of the php binary. As for things like uopz and UUID, those are now back to the default way to install PHP extensions (pecl).
